### ISSUE TITLE
BaseNetworkable with INetworkSerializer stops reading network data after Hotload 

### ISSUE THREAD

**Issue by DevulTj** [sboxgame/issues#1039]
I have a List<MyAssetType> in a BaseNetworkable class, which is updated manually with INetworkSerializer via 			WriteNetworkData().

(Using INetworkSerializer due to https://github.com/Facepunch/sbox-issues/issues/1021)

This works fine until hotload. Then INetworkSerializer.Write is executed, but INetworkSerializer.NetRead never gets called.

**Comment by garrynewman** [comment]
Where is the variable? Is it directly on the entity?

**Comment by DevulTj** [comment]
This is directly on an EntityComponent. Same code from https://github.com/Facepunch/sbox-issues/issues/1021 but the List is a List of assets and networked manually.

**Comment by DevulTj** [comment]
Following up from https://github.com/Facepunch/sbox-issues/issues/1021 's journey. Similar code, but stuff just networked manually with INetworkSerializer. 

I was calling from a [Net]'d component which already fucked things up. 

However, Upon removing that [Net]'d component and grabbing it directly with Components.Get, I still stop receiving network data after a hotload. (with INetworkSerializer, doing manual WriteNetworkData() updates.)

Code below:

```csharp
	public partial class InventoryComponent : EntityComponent, INetworkSerializer
	{
		public int MaxItems => 4;
		public bool IsFull => Items.Count >= MaxItems;

		public List<Assets.Item> Items { get; protected set; } = new();

		public virtual bool AddItem( Assets.Item item )
		{
			Items.Add( item );
			WriteNetworkData(); // @INetworkSerializer
			return true;
		}

		public virtual void RemoveItem( int index )
		{
			Items.RemoveAt( index );
			WriteNetworkData(); // @INetworkSerializer
		}

		// @INetworkSerializer
		public void Write( NetWrite write )
		{
			write.Write( Items.Count );
			foreach ( var item in Items )
				write.Write( item );
		}

		//@INetworkSerializer
		public void Read( NetRead read )
		{
			Items = new();
			var count = read.Read<int>();
			for ( int i = 0; i < count; i++ )
			{
				var item = read.ReadClass<Assets.Item>();
				Items.Add( item );
			}
			Event.Run( "inventorycomponent.update" );
		}

		public void DebugPrint()
		{
			var position = Host.IsServer ? new Vector2( 100, 100 ) : new Vector2( 100, 400 );

			string build = Host.IsServer ? "Server:" : "Client:";
			foreach ( var item in Items )
				build += $"\nItem: {item}";

			DebugOverlay.ScreenText( position, 0, Color.White, build, 0.05f );
		}
}
```

I know I should use [Net] here - but this should probably still work.
