### ISSUE TITLE
Deleting entity than your currently viewing in the inspector make your game crash

### ISSUE THREAD

**Issue by Matspyder51** [sboxgame/issues#1046]
**Describe the bug**
If your currently looking at a deleted entity in the inspector, your game freeze & crash

**To Reproduce**

1. Spawn an entity
2. Select it in the inspector
3. Close the console
4. Delete the entity
5. Reopen the console
6. Your game freeze and crash

**Expected behavior**
To not crash, auto swapping to another entity or no entity at all, or draw a "Deleted" label or something like that

**Comment by garrynewman** [comment]
No crash here - which entity were you looking at?

**Comment by Matspyder51** [comment]
I was able to reproduce it again just now, it seem related to the hotreloading, if I delete the entity while the game hotreloading, opening the inspector in the process will makeyour game freeze if your actually looking at the specified entity or one of it's childs

If I don't trigger the hotreload or wait few seconds before opening the inspector, it's okay

[A small video if you need](https://streamable.com/ld1jxk)

**Comment by garrynewman** [comment]
Okay so your repro is:

1. Spawn entity
2. Select entity in inspector
3. Delete entity
4. Hot reload
5. Open console

Right?

**Comment by Matspyder51** [comment]
I trigger the hot reload before deleting it, I can delete it quickly with a bind to undo, on the video when you hear the small "pop" it's me deleting it
