### ISSUE TITLE
Introduce #pragma once for shader preprocessor

### ISSUE THREAD

**Issue by ogniK5377** [sboxgame/issues#1066]
**What can't you do?**
Currently include guards need to be used for shaders. Introducing `#pragma once` automatically adds the include guards and reduces the margin of error caused by include guards.

**How would you like it to work?**
```hlsl
#pragma once

// Code here...
````

**What have you tried?**
```hlsl
#ifndef MY_INCLUDE_GUARD
#define MY_INCLUDE_GUARD

// Code here...

#endif
```

**Additional context**
Prefixing and appending the file with a unique include guard instead of having to manually define them will greatly simplify the need of them

**Comment by handsomematt** [comment]
Not going to do anything out of standard for FXC
