### ISSUE TITLE
SCSS background-position with edge offsets

### ISSUE THREAD

**Issue by ogniK5377** [sboxgame/issues#107]
**What can't you do?**
Set the background-position in SCSS

**How would you like it to work?**
```scss
background-position: right 0px bottom 0px;

background-position: right 1000px bottom 1000px;
 ```

**What have you tried?**
N/A

**Additional context**

**Comment by garrynewman** [comment]
This already exists - is it not working for you?>

**Comment by rtm516** [comment]
By the looks of the (decompiled) code it only handles `x` and `y` pos and not the edge offsets.
https://developer.mozilla.org/en-US/docs/Web/CSS/background-position
