### ISSUE TITLE
Character's arm turns red when walking into new light areas

### ISSUE THREAD

**Issue by Nukiloco** [sboxgame/issues#1105]
**Describe the bug**
It seems like the character's arm turns red when walking into new areas with different lights.

**To Reproduce**

1, Go on construct
2. Walk into a building
3. Notice that your arms turn red for a split second

**Expected behavior**
Your arms shouldn't turn red for a split second.

**Screenshots**

https://user-images.githubusercontent.com/16618467/137621365-2c40bdb9-1630-42d8-b1ff-49734fc27981.mp4

**Comment by xezno** [comment]
Looks like this was fixed a while ago, I can't reproduce it
