### ISSUE TITLE
Allow markdown in game descriptions.

### ISSUE THREAD

**Issue by sanny-io** [sboxgame/issues#1113]
**What can't you do?**
Use markdown to style game descriptions.

**How would you like it to work?**
Just standard markdown styling like how it is on GitHub. WYSIWYG editing would be extra nice.

**What have you tried?**
I've tried using markdown and it doesn't work.

**Comment by robotboy655** [comment]
I have added a basic implementation, to both in-game and on asset.party. 

I have disabled links/images for now, so people don't go overboard.
