### ISSUE TITLE
Animated Foliage Shader

### ISSUE THREAD

**Issue by gvarados1** [sboxgame/issues#1133]
We need an animated foliage shader

**Comment by gvarados1** [comment]
Any updates on this? I remember ognik showed off a treesway shader a few months ago but we haven't seen anything since.
I made a cool forest map and animated leaves would help a ton

![sbox_0009](https://user-images.githubusercontent.com/39461072/172074338-b0c35516-afbe-4689-ad24-6272d44fe820.jpg)

**Comment by ogniK5377** [comment]
Still planned, we just need a nice way to make it simple for everyone to use it

**Comment by DoctorGurke** [comment]
Would classic freedom of movement map + common sway parameters not be nice enough?

**Comment by gvarados1** [comment]
I think gmod/source1 did it pretty well. I didn't see anything obviously wrong with it. It's just a few parameters in the material.
https://developer.valvesoftware.com/wiki/$treeSway

Would be lovely to have a map entity to configure wind speed, similar to s1 env_wind
https://developer.valvesoftware.com/wiki/Env_wind

And the ability to have a per-material override that ignores env_wind

**Comment by handsomematt** [comment]
Added a while back https://wiki.facepunch.com/sbox/Foliage_Shader
