### ISSUE TITLE
Whitelist json posts

### ISSUE THREAD

**Issue by rtm516** [sboxgame/issues#115]
**What can't you do?**
Make a HTTP post with json as the method requires `System.Text.Json/System.Text.Json.JsonSerializerOptions` this is caused because one of the optional for PostAsJsonAsync is a `JsonSerializerOptions`.
It also needs `System.Net.Http/System.Net.Http.HttpResponseMessage` so the response can be got.

**How would you like it to work?**

**What have you tried?**
```csharp
private HttpClient client = new();
private SomeObject data = new();
client.PostAsJsonAsync( "https://example.com/", data );
```

**Additional context**

**Comment by Oppossome** [comment]
In addition to `System.Net.Http/System.Net.Http.HttpResponseMessage` 
`System.Net.Http/System.Net.Http.HttpContent` would be useful to get the body of the response.

**Comment by abbydiode** [comment]
In addition `System.Net.Http.Json` would be useful for interacting with APIs, for example when storing data for a global leaderboard or making gamemodes that allow players to make progression.

**Comment by FlorianLeChat** [comment]
No, go away, this request is very useful.

**Comment by handsomematt** [comment]
https://wiki.facepunch.com/sbox/http
