### ISSUE TITLE
Indirect Lighting doesn't bounce correct colour from Tint

### ISSUE THREAD

**Issue by Jake-NSW** [sboxgame/issues#1159]
**Describe the bug**
vrad doesn't use the tint while baking ambient lighting onto the lightmap, instead just using the albedo which is most situations is just plain white, resulting in incorrect lighting

**To Reproduce**
1. Make a tinted object
2. Make a non tinted object
3. Add a sun
3. Bake lighting
4. See result

**Expected behaviour**
To bounce tint colour on indirect

**Screenshots**
Left is normal untinted material - Right is tinted orange material (where the albedo is white)
![image](https://user-images.githubusercontent.com/55055481/138623643-9ef7a477-c92d-4f5f-b6cc-1de441ade2f0.png)

Does it in HLA too: (Left being a white albedo with tint, and right being a yellowish albedo no tint)
![image](https://user-images.githubusercontent.com/55055481/138623153-7350c0df-5554-4c4c-a8b1-6f0ce3385f1f.png)

**Comment by VeeSaus** [comment]
Although meshwork does tint according to its colour, the effect is not saturated enough, giving unrealistic results.
Here is an example of how the effect should look. I am using the dev_measuregeneric01 mat here.
Here is the scene in fullbright:
![image](https://user-images.githubusercontent.com/75756114/148800191-7d669757-a327-405e-877d-d4cf6030783d.png)
Here is the scene in albedo:
![image](https://user-images.githubusercontent.com/75756114/148800289-f2852722-f2eb-4da2-9ffe-bbca7a986242.png)
And here is the scene in rt baked lighting:
![image](https://user-images.githubusercontent.com/75756114/148800320-f513636a-182b-439c-abd9-91b37effe7db.png)
![image](https://user-images.githubusercontent.com/75756114/148800338-7e7ea5b0-9620-4d7e-b87e-442b3b4b4570.png)
But here is how indirects interact with tinted materials.
I am using the corrugated_wall_a mat in this scene. I have tried to match the albedo tint with the measuregeneric mat
![image](https://user-images.githubusercontent.com/75756114/148800387-d5998302-9e91-4c78-a131-46442c49b624.png)
![image](https://user-images.githubusercontent.com/75756114/148800412-2fea5596-92b2-499e-b1e9-efedf7fd3f1a.png)
![image](https://user-images.githubusercontent.com/75756114/148800497-4dea7d2d-1872-473f-961f-41d6d8b3e9b2.png)
![image](https://user-images.githubusercontent.com/75756114/148800534-b8b2f83f-fb44-4bcb-b801-65585bb4baeb.png)

Here is another example with the metal_painted_a_hs mat:
![image](https://user-images.githubusercontent.com/75756114/148800579-d1123b14-2cd3-4227-b697-95e89b848809.png)
![image](https://user-images.githubusercontent.com/75756114/148800592-072a6c21-73b1-4e58-beb6-3f2f50626896.png)
![image](https://user-images.githubusercontent.com/75756114/148800602-45e1958f-6954-49bc-ba1b-e2cb536aa196.png)
![image](https://user-images.githubusercontent.com/75756114/148800622-0d3c74fd-49b9-442e-89bb-5a0c86974411.png)

These issues are happening with an irradiance scale of 1 and a env light brightness of 3.
![image](https://user-images.githubusercontent.com/75756114/148800712-eb38c86c-1662-4e23-825e-138f91ed24cc.png)

![image](https://user-images.githubusercontent.com/75756114/148800699-6fc5e696-73b8-4978-98a7-33020ba17d99.png)

**Comment by KayaDLX** [comment]
This is still happening, cube plain red tinted, light spot with a brightness of 10
![sbox-dev_7bYFGsoMfH](https://user-images.githubusercontent.com/67245359/235149860-2e4d50c5-e3b4-4cf7-a079-72e956dd4004.png)
![sbox-dev_5y9Rj4gvsv](https://user-images.githubusercontent.com/67245359/235149914-e9fe4945-f525-49eb-a144-39cf2becedd9.png)

**Comment by KayaDLX** [comment]
Using reflectivity 90 and still a plain red color, this doesn't feel saturated enough as stated by Vee previously
![image](https://user-images.githubusercontent.com/67245359/235151032-e89632db-537a-4963-a5dd-f9289662c998.png)
![image](https://user-images.githubusercontent.com/67245359/235151170-0e2f9125-861a-4ab5-948d-1208ebf83ba4.png)
