### ISSUE TITLE
Source 1 Importer fails when upgrading VTX files

### ISSUE THREAD

**Issue by ogniK5377** [sboxgame/issues#1165]
**Describe the bug**
The material replacement list is completely invalid on upgraded VTXs and the offset is also incorrect. This seems to be an issue due to the upgrade process of the VTX files.

**To Reproduce**
mdltodmx breen.mdl from Half Life 2. See Additional context for test file

**Expected behavior**
Upgrade should be a correct VTX file and not crash/read uninitialized memory

**Screenshots**

**Additional context**
In the asset browser, type "breen"
[mdlcrash.zip](https://github.com/Facepunch/sbox-issues/files/7411694/mdlcrash.zip)

**Comment by xezno** [comment]
We don't ship the Source 1 importer anymore
