### ISSUE TITLE
Press Tab to highlight dev console autocomplete

### ISSUE THREAD

**Issue by randomperson189** [sboxgame/issues#1190]
**What can't you do?**
I can't press Tab to highlight the auto-completions in the console just like the up and down arrows.

**How would you like it to work?**
Press Tab and it will act like pressing down arrow, starting at top and going down every time you press it.

**Additional context**
Having to use the arrow keys is really annoying and slows down the workflow. Pressing tab like in Source 1 is quick and easy.

**Comment by robotboy655** [comment]
Should be working as expected after the game next updates.
