### ISSUE TITLE
SVG Image Support

### ISSUE THREAD

**Issue by Jake-Rich** [sboxgame/issues#120]
**What can't you do?**

Use Texture.Load() on SVG images.

**How would you like it to work?**

I'm not entirely sure but here's my best guess. Since we are only using SVG images in the UI you could avoid textures and have a new Panel class with a `string svgPath` field that figures out the size as it's rendering to avoid allocations. Otherwise if you want to load the svg as a texture you could have `Texture.LoadSVG( string path, int width, int height )` that would load and render the svg to that texture, but that would have extra allocations & you might not have a pixel perfect size.

**What have you tried?**

Using PNGs for now.

**Comment by cheddZy** [comment]
Yes please! SVG image support would be great.

**Comment by justynboi** [comment]
Still relevant

**Comment by MoonlyDays** [comment]
Still relevant

**Comment by gabefollower** [comment]
Still relevant

**Comment by cr4yz** [comment]
Just got this in, you can load an svg using `Texture.Load("file.svg?w=100&h=100&color=red");`

Leaving out width & height will use the svg's default size, and giving it a color will paint the whole svg that color (useful for icons).

If you have any issues let us know.
