### ISSUE TITLE
Whitelist more `System.Private.CoreLib/System.Threading.Tasks.Task` methods.

### ISSUE THREAD

**Issue by sanny-io** [sboxgame/issues#1234]
**What can't you do?**
Use the following methods:

`System.Threading.Tasks.Task.get_CompletedTask`
`System.Threading.Tasks.Task.FromResult`
`System.Threading.Tasks.Task.FromException`
`System.Threading.Tasks.Task.FromCanceled`
`System.Threading.Tasks.Task.WhenAll`
`System.Threading.Tasks.Task.WhenAny`

Maybe some more, too, but I haven't used more than these.

**How would you like it to work?**
How they'd work anywhere else.

**What have you tried?**
I've tried using them and get this error.

> Not in whitelist: System.Private.CoreLib/System.Threading.Tasks.Task.get_CompletedTask()

**Additional context**
Some of these have generics, and I would like those as well.

**Comment by sanny-io** [comment]
I think I put the wrong label. Should probably be api design.

**Comment by handsomematt** [comment]
Sorry it took so long, should all be whitelisted now.
