### ISSUE TITLE
Hammer - Model Path

### ISSUE THREAD

**Issue by gvarados1** [sboxgame/issues#1239]
**What can't you do?**
We can't use the path tool to make things like fences or rock paths.

**How would you like it to work?**
Model Path in path tool. It should support single models and multi-model fences.
![image](https://user-images.githubusercontent.com/39461072/140793994-8be83a72-3574-42a0-9a9d-18b7b1939f98.png)

This fence is made of multiple models. It has separate upright posts connecting it:
![image](https://user-images.githubusercontent.com/39461072/140794660-e118e68d-facd-4bcb-997f-d7bb5aa33a99.png)

This should also support prefabs, not just models.

**What have you tried?**
Currently we have to use tilesets (slow) or place the models manually (very slow)

**Comment by aylaylay** [comment]
This is something I've wanted to do for a while, some thought needs to be put into how it's designed

**Comment by kote2345** [comment]
Duplicate ? https://github.com/Facepunch/sbox-issues/issues/886
