### ISSUE TITLE
Hammer Asset Browser - Save Selected Addons

### ISSUE THREAD

**Issue by gvarados1** [sboxgame/issues#1306]
My selected addons should be saved between sessions in the hammer asset browser.
Every time I launch hammer or even open a new map I have to disable the citizen and rust addons for every tab in the asset browser.

![image](https://user-images.githubusercontent.com/39461072/142509897-0979131a-ad48-4b53-83bc-443ed6123f2b.png)

**Comment by aylaylay** [comment]
The asset browser in hammer should now be saved

**Comment by gvarados1** [comment]
yay :)

**Comment by gvarados1** [comment]
This only works on docked asset browsers. I keep mine floating on a second monitor, and it doesn't save.

**Comment by garrynewman** [comment]
I think this might be a regression of mine, will look into it today

**Comment by gvarados1** [comment]
Also I noticed the floating window is missing the new Recent tab 
![image](https://user-images.githubusercontent.com/39461072/149744025-d3e020b7-000c-4caf-b7b5-ad4271f1973e.png)

**Comment by KaesarZZ** [comment]
I was about to open an issue lol, it's happening in the main asset browser yeah, something has been screwed up since the addon change.

**Comment by KaesarZZ** [comment]
> Latest commit might help - let me know

Fixed for me.

**Comment by gvarados1** [comment]
Doesn't work.

The docked window saves, but the floating window doesn't.

**Comment by gvarados1** [comment]
Just confirmed this still doesn't work on floating windows

https://user-images.githubusercontent.com/39461072/151651532-465a1b38-e569-4304-b696-9f6c5ba1f0fc.mp4

.

**Comment by KayaDLX** [comment]
Can confirm too.

**Comment by gvarados1** [comment]
still an issue. happens every time I open a map

**Comment by gvarados1** [comment]
This was never fixed, why was it closed?
