### ISSUE TITLE
Add DDS support to Texture.Load/LoadAsync

### ISSUE THREAD

**Issue by SK83RJOSH** [sboxgame/issues#1307]
**What can't you do?**
Currently you cannot load DDS images in Sandbox.

**How would you like it to work?**
Just like any other texture format? :)

Perhaps something for a separate issue, but Image exposes support loading textures from streams, and it would be really cool to get this exposed as an overload for `Texture.Load(string name, Stream stream)` to allow us to piggyback off texture caching where possible. The reason I mention this will become more obvious when you read additional context.

**What have you tried?**
Writing my own DDS parser and feeding it's results into a texture builder. Kind of works, but also kind of a nightmare and not particularly maintainable. There's plenty of good libraries out there for this, but most of them are unsafe and thus cannot be used in addons without a lot of modification. Preferably Sandbox would handle this and just cut out the middleman.

**Additional context**
I'm currently working on an importer for assets from a past project of mine that have a pretty small footprint due to being wrapped in a custom archive format. This makes them pretty perfect for embedding into an addon, and so I'd strongly prefer to keep using these assets as is and just write up the tooling for importing. The DDS issue is the only thing really preventing me from wrapping things up at this point.

**Comment by handsomematt** [comment]
I don't see us adding this
