### ISSUE TITLE
Allow AnimEntities with server-only animgraphs to be animated on the client

### ISSUE THREAD

**Issue by goaaats** [sboxgame/issues#1321]
**What can't you do?**
Currently, trying to animate e.g. the Citizen as a client-only entity does not work anymore, since its animgraph is set to run on the server exclusively.
All modifications to animgraph variables, and posing bones manually using SetBoneTransform, fail silently.

`EnableClientsideAnimation` in AnimEntity is obsoleted and stubbed.

**How would you like it to work?**
Client-spawned AnimEntities that have a server-only animgraph can still be animated by hand or manually set animgraph variables.

**What have you tried?**
It's possible to get around this by using an AnimSceneObject, but it's missing a few things that keep me from using it effectively (e.g. BoneCount, inherited from ModelEntity in AnimEntity).

**Additional context**
Garry said that this was dogshit and that you guys could fix it
[![image](https://user-images.githubusercontent.com/16760685/142763638-6a0b99f8-1ecb-4961-b0cd-c34dad5e386c.png)](https://canary.discord.com/channels/833983068468936704/837215495496663040/908742665280045068)

**Comment by peter-r-g** [comment]
Bump, just ran into this doing custom networking. Since it's not using the server realm at all it means no sausage men for me :\

**Comment by Fortune117** [comment]
Just ran into this myself when trying to add a first person body.

**Comment by the-remeko** [comment]
I encountered this as well while trying to make a ScenePanel with a SceneModel Terry on it.

**Comment by kurozael** [comment]
This should be fixed in the next build - if you have anymore issues let me know :)
