### ISSUE TITLE
Post-processing support for VR

### ISSUE THREAD

**Issue by xezno** [sboxgame/issues#1357]
**What can't you do?**

Post-processing effects do not apply when using VR.

**How would you like it to work?**

I can imagine that this is probably done intentionally, but I have various use cases that I'd like to explore:

- HLA-style "wall intersection" overlay (the orange thing that pops up when you shove your head into a wall)
- Player death effects (like a simple desaturation effect or something)
- An effect for night vision goggles

**What have you tried?**

Applying the post-processing effect as described in #1333 seems to have no effect.

**Comment by xezno** [comment]
I believe this is fixed now

**Comment by handsomematt** [comment]
RenderHooks work in VR now yeah
