### ISSUE TITLE
Networking Static Variables

### ISSUE THREAD

**Issue by Oppossome** [sboxgame/issues#1408]
**What can't you do?**
It is currently impossible to network a static variable. It just silently fails which leads to confusion.

**How would you like it to work?**
```cs
[Net]
public static string Thing { get; set; }

[ServerCmd]
public static void SetThing()
{
  Log.Info( "Value set to wow" );
  Thing = "wow";
}

[ClientCmd]
public static void GetThing()
{
  Log.Info( $"Current Value: {Thing}" );
}
```

**What have you tried?**
Current workaround is having a static instance variable, which only goes so far depending on what you're trying to accomplish.

**Additional Information**
It would be nice if it didn't silently fail in the meantime as it's lead several of my peers to be confused.

**Comment by handsomematt** [comment]
![image](https://user-images.githubusercontent.com/1388267/145735268-15114cdf-f921-4f2a-97fc-24a304f505ce.png)

It already throws an error at you when you try to do this.

Supporting these doesn't make much sense to me, any reason you wouldn't just have a networked class on Game?

**Comment by Oppossome** [comment]
I checked again right now, It does not appear that the released build of the client throws an error for a networked static.
