### ISSUE TITLE
SCSS: `overflow: hidden` does not respect the element's `border-radius`

### ISSUE THREAD

**Issue by xezno** [sboxgame/issues#143]
**Describe the bug**

The `overflow` property doesn't respect `border-radius` when set to `hidden`. This might be linked to #114?

**To Reproduce**

[Here's an example on JSFiddle](https://jsfiddle.net/kz15qbce/23/). (Exact same example should work in s&box, but the extra HTML / SCSS needs uncommenting)

**Expected behavior**

The top bit should be rounded like its parent.
Here's what it looks like in my browser (Edge v90):
![image](https://user-images.githubusercontent.com/12881812/117900365-f3e0e800-b2c0-11eb-954e-b3b422c5bb29.png)

**Screenshots**

Here's what it looks like in s&box:
![image](https://user-images.githubusercontent.com/12881812/117900380-f93e3280-b2c0-11eb-8c8c-c0dd02508449.png)

**Additional context**
N/A

**Comment by xezno** [comment]
Still relevant

**Comment by PolSpock** [comment]
Same problem here 😥

**Comment by Hlowy** [comment]
+1
Doesn't work for me

**Comment by Radeoxx** [comment]
A workaround is to set the inherited properties manually in every child and set the non-inherited properties to ensure it gets a good appearance, 

I think you just need to set `border-radius` in the child too, and if its width or length is variable and could be for example 5% and it bugs out becouse the rounded corners, you just can hide it behind something.

Here it's a small healthbar I did using `overflow: hidden;`

![image](https://user-images.githubusercontent.com/12381901/183444180-ac15e103-c7d9-40ad-bfe5-f3e7a5786943.png)

```
.MainContainer {
    top: 925px;
    left: 50px;
    width: 375px;
    height: 100px;
    background-color: transparent;
    justify-content: center;
    align-items: center;
    overflow: hidden;
}

.mainContainer > .healthContainer { same properties as above, plus some tweaks as background-color }

.mainContainer > .healthContainer > .healthBackground { 
height: 60px; -> hides the overflow
}

mainContainer > .healthContainer > .healthBackground > .slider {
height: 100px; -> this only gets 60px but its size still 100px
}
...
```

And so on...

**Comment by xezno** [comment]
This is fixed now! Thank you Matt! 🙂 
![image](https://user-images.githubusercontent.com/12881812/211199978-c5ee014c-a3df-4989-b09b-7b6bf2ac0d68.png)
