### ISSUE TITLE
Jigglebones are working different and not properly ingame.

### ISSUE THREAD

**Issue by KaesarZZ** [sboxgame/issues#1440]
**Describe the bug**

I'm trying to see how the jigglebones work in playermodels, I've noticed that in Modeldoc activating the "Toggle cloth sim" option they work decently but when I go ingame they break a lot more using the same animation. 

I have been several hours trying to update ingame looking for a similar result but it seems impossible.

**Expected behavior**

Trying to get some info about why this is happening and at least, get what we see in ModelDoc. I guess I can share the model if needed.

**Screenshots**

https://user-images.githubusercontent.com/40291120/147509454-62648579-8146-4887-ada0-ca22a27ed388.mp4

https://user-images.githubusercontent.com/40291120/147509604-8690290d-ff57-4ed8-acfb-854b8344be43.mp4

**Comment by aylaylay** [comment]
send model

**Comment by KaesarZZ** [comment]
> send model

Is possible get an email or whatever to send you the link? I don't want to share the source files publicly yet.

**Comment by KaesarZZ** [comment]
I think everything you need is here, if you need anything else we can see it.

https://drive.google.com/file/d/1WiDjQHStZEwVoerJiu-3_mqWIvda7ija/view?usp=sharing

**Comment by aylaylay** [comment]
Your character is moving forward so it's influencing the jiggle bones more than what you see in modeldoc, I agree it looks shit, I'm trying to see if there's a way to make it look less shit

**Comment by KaesarZZ** [comment]
Hey, thanks for looking at it. They're not so shit now, but not even close to decent.

When you said that "Your character is moving forward ingame, not like in modeldoc" looking at the citizen as reference, I thought something was wrong on my animations, but I get the same result anyway. (Take a look on the ground plane)

https://user-images.githubusercontent.com/40291120/159092660-586da5c6-b3d9-47fa-a1b4-274ce7c23b52.mp4

So if I'm not wrong, there is no way to test jigglebones in modeldoc or Idk wtf is happening.

The idea would be to get something like in source1 I guess?, see exactly how they work ingame through modeldoc. If We need to compile every time We want to see a change good luck + there is 0 documentation of what many properties do, you've to imagine it and then go ingame to test "something".

So let's just wait for the whole cloth issue to clean up, I guess.

**Comment by aylaylay** [comment]
I don't have run_n_copy

**Comment by aylaylay** [comment]
Send me the uncompiled files, not just the compiled model, including that run animation that triggers the treadmill

**Comment by aylaylay** [comment]
I have made it simulate jiggle bones in modelspace instead of worldspace so that only the animation influences it. I'll need to make this an option at some point but I figure that most people will only need the animation to influence it for now.

**Comment by aylaylay** [comment]
I've had to undo this, while it looks great in this situation with just the animation driving it, we really should find out why it looks so bad when movement is involved.

**Comment by aylaylay** [comment]
I think you just have to mess around with the params, I got the jiggle bones on your model working pretty well with just changing the length and tip mass.

**Comment by KaesarZZ** [comment]
Oh I see what you mean, at least with your first commit now it looks like by changing params I get something decent. I've to continue researching and see if I can improve it.

https://user-images.githubusercontent.com/40291120/159115627-1b906706-1751-4f51-923f-6b209b53cff7.mp4

Maybe with jigglebones like these, which are in the leg area and it's easy for them to go through, yeah, it would be cool to have the option for X jigglebones to work with the animation and maybe saves time. 

But yeah overall, I think the goal here is to get a "Ingame Jigglebone test" in ModelDoc somehow, get sliders on all params and try to get them all working perfectly and without being a pain.

**Comment by KaesarZZ** [comment]
I did more tests and yeah good shit. Feel free to close it or not if you want to make more mentioned stuff as "feature request's" already. Thanks <3.

**Comment by aylaylay** [comment]
Cool. I agree that the jiggle bone params are cryptic and something needs to be done about that. Could also look into having a simple character controller in model doc so you can see how it looks when it's actually moving. (When the animation is running on the treadmill, it's actually not moving, as far as jiggle bones are concerned)

**Comment by KaesarZZ** [comment]
Hello, adding another feature request, when you have many jigglebones to pick, you can't use ctrl to select all, you need to go one by one.
