### ISSUE TITLE
Whitelist System.Threading.Tasks.Task.FromResult<TResult>()

### ISSUE THREAD

**Issue by peter-r-g** [sboxgame/issues#1445]
**What can't you do?**
Use `System.Threading.Tasks.Task.FromResult<TResult>()` to return from a potentially asynchronous method synchronously. For example, if you have an interface method that returns a Task<T> so that both sync and async methods are supported you can't use a sync method without something like Task.FromResult.

**How would you like it to work?**
Just as it should. The following snippet is an example of its use case:
```cs
public Task<bool> FileExists( string filePath )
    => Task.FromResult( FileSystem.FileExists( filePath ) );
```

**What have you tried?**
`System.Threading.Tasks.Task.RunSynchronously`: Isn't whitelisted.
Creating a new Task instance with the code in a lambda. No way to execute it with the current whitelist.

**Comment by Rohansi** [comment]
We'll do this but you might want to consider `ValueTask` for potentially synchronous things.
