### ISSUE TITLE
Generic classes aren't networked properly

### ISSUE THREAD

**Issue by kolexxx** [sboxgame/issues#1448]
**Describe the bug**

Generic classess aren't networked properly. The following example is adding weapons to the player's inventory.

**To Reproduce**

1.
```cs
public partial class ProjectileWeapon<T> : Weapon where T : Projectile, new() { ... }
```

2. 
```cs
player.Inventory.Add( new ProjectileWeapon<Projectile>() );
```

**Expected behavior**

The weapon should be networked to the client.

**Screenshots**

![Desktop Screenshot 2021 12 29 - 17 54 28 51](https://user-images.githubusercontent.com/48793595/147686566-bff634b2-1e44-4988-9cd3-2b929349b16e.png)
![Desktop Screenshot 2021 12 29 - 17 56 20 03](https://user-images.githubusercontent.com/48793595/147686574-6262424f-b0c5-4bbd-a92b-d5b0ee38ab2a.png)

**Source code**
How the weapon is added: https://github.com/kolexxx/sbox-paintball/blob/master/code/systems/gamestates/MainGameState.cs#L50
The generic class: https://github.com/kolexxx/sbox-paintball/blob/master/code/entities/weapons/ProjectileWeapon.cs
The inventory which I hope shouldn't cause any problems: https://github.com/kolexxx/sbox-paintball/blob/master/code/entities/player/Inventory.cs

**Comment by LeQuackers** [comment]
Somewhat related; BaseNetworkable has issues with generics as well:

```cs
// Compiles in VS2022, but fails in s&box:

namespace BugTest1
{
	public partial class Example : Entity
	{
		[Net]
		public TestNetworkable<Example> Foo { get; set; }
	}

	public partial class TestNetworkable<T> : BaseNetworkable
	{
		public T Bar { get; set; }
	}
}

// generated:

namespace BugTest1
{
	partial class Example
	{
		public Sandbox.Internal.VarClass<global::BugTest1.Example> _repback__Foo = new Sandbox.Internal.VarClass<global::BugTest1.Example>(  );
		
	}
}
```

```cs
// Fails in VS2022 and s&box:

namespace BugTest2
{
	public partial class Example : Entity
	{
		[Net]
		public TestNetworkable<int> Foo { get; set; }
	}

	public partial class TestNetworkable<T> : BaseNetworkable
	{
		public T Bar { get; set; }
	}
}

// generated:

namespace BugTest2
{
	partial class Example
	{
		public Sandbox.Internal.VarClass<int> _repback__Foo = new Sandbox.Internal.VarClass<int>(  );
		
	}
}
```

**Comment by FoxTTT** [comment]
I wanted to write a response to help with this issue for now, but its a bit fishy:

IF you make an object such as:

```csharp
	public partial class TestNetworkable<T> : BaseNetworkable where T : class
	{
		[Net] private BaseNetworkable value { get; set; }

		public T Value
		{
			get => value as T;
			set
			{
				// No double checking stuff here, only demonstration.

				value = value as T;
			}
		}



	}
```

```csharp
public class TestNetworkable_Int : TestNetworkable<int>{

       // You need this for Hotloading.
       public TestNetworkableInt(){

       }
}
```
