### ISSUE TITLE
sbox-dev editor has duplicate slider

### ISSUE THREAD

**Issue by rugg0064** [sboxgame/issues#1466]
**Describe the bug**
There's 2 bars you can click on to resize the console/main window in the sbox-dev.exe menu

**To Reproduce**

1. Open sbox-dev.exe
2. Observe that there are 2 areas to move the size instead of one.

**Expected behavior**
It should only have one slider

**Screenshots**

![sboxbb](https://user-images.githubusercontent.com/35048262/148656914-3734986a-1469-4ba0-b3d3-05b011140096.gif)

**Comment by robotboy655** [comment]
This appears to be fixed with the recent dock system change.
