### ISSUE TITLE
Networking a large structure crashes the game to desktop

### ISSUE THREAD

**Issue by rugg0064** [sboxgame/issues#1469]
**Describe the bug**
Using [Net] for a something that is very large will cause the following error
CNetworkGameServerBase::PackEntity():
PackEntity: g_pFlattenedSerializers-> Encode false (ent 157).

**To Reproduce**

Make a gamemode with this snippet
```
		[Net] public List<int> bigList { get; set; }
		public Game()
		{
			bigList = new List<int>( );
			for(int i = 0; i < 16384; i++ )
			{
				bigList.Add( i );
			}
// . . .
```

**Expected behavior**
It's okay that you can't network such a big list, I assume this won't be a feature as I was once told "why the fuck would u [network such a large list]" but it would be preferable if a regular c# exception was thrown and it didn't boot you to the desktop.

**Comment by PolSpock** [comment]
I tried to network my List of Vertices and Indices for my mesh and I get the same error & crash lol

So I have to change my logic, but yeah avoiding crash would be preferred 🙃
