### ISSUE TITLE
$includemodel equivalent for ModelDoc

### ISSUE THREAD

**Issue by N-cognito** [sboxgame/issues#1473]
**What can't you do?**
I can't reference an existing model for the animations it contains. This becomes a problem when I have a model containing a TON of animations, and I have a similar model that uses those same animations but slightly altered. I have to completely duplicate the animations and their settings, and if I make a change on one model animations it doesn't reflect onto the other.

[$includemodel](https://developer.valvesoftware.com/wiki/$includemodel) is a QC parameter that would allow you to reference a model, from which animations would be loaded. This is extensively used in almost any source game to make animations that are shared way easier to manage and extend to new models.

**How would you like it to work?**
I would like to be able to add a new setting/input, probably something like AppendAnims, that allows me to reference an existing VMDL's animation list. This would allow use of existing animations and settings without having to completely duplicate them for every model that uses them.

On top of this, it should have the ability to override animations appended this way (ex: AppendAnims -> Run_N vs This Model -> Run_N, the latter would take priority and be chosen over the former). I believe how this works in S1 is by the order in which they appear, though I'd prefer it to work in a similar fashion as an override method, where animations directly in the model would have priority over appended ones regardless.

**Comment by GunnarKafel** [comment]
Not sure about the overriding part but I know you can already do this using Prefabs in ModelDoc. On your base model with all the animations, select the animations you want to include. Right click them, then select Move Into Prefab. After that you can instantiate the .vmdl_prefab file in any model you want and it will reflect the changes from the base. You can even edit the prefab from other models and it'll effect every other instance.
![image](https://user-images.githubusercontent.com/65134886/148779505-2ac90fa1-dfe0-4637-821d-bee48af17dcb.png)
![image](https://user-images.githubusercontent.com/65134886/148779605-554d1275-8777-455d-af8f-a0aa00d784ce.png)

**Comment by NotGaylien** [comment]
that works, its what i am doing currently, but its also annoying.
Since you have to manually update the prefab with the new animations and changes from the citizen every time it gets updated.

maybe one day all the citizens stuff (excluding model related stuff) will get put into a prefab to use for custom player models/animations in game modes without having to manually keep track of updating your own prefab

**Comment by robotboy655** [comment]
Is this solved?
![image](https://user-images.githubusercontent.com/3299036/199245963-d6b5fa07-43f4-497e-b115-e5e2bde9f6e8.png)
