### ISSUE TITLE
Ability to broadcast game events from server to clients.

### ISSUE THREAD

**Issue by MoonlyDays** [sboxgame/issues#1479]
**What can't you do?**
Ability to be able to run a specific game events server-side and have client elements like HUD be able to listen to them without the need to make a sub rpc function just to run the event again clientside.

**How would you like it to work?**
Something like `Event.Run(string eventname, bool broadcast, args...)` as an overload
or `Event.Broadcast(eventname, args...)`

**What have you tried?**
```csharp
public static void DoEvent( int arg1, bool arg2, string arg3 )
{
  Event.Run( "MyEvent", new MyEventArgs( arg1, arg2, arg3 ) );
  if ( Host.IsServer ) DoEventClient( arg1, arg2, arg3 );
}

[ClientRpc]
public static void DoEventClient( int arg1, bool arg2, string arg3 )
{
  DoEvent( arg1, arg2, arg3 );
}
```
And this honestly looks very messy especially when you have a lot of events that you want to broadcast.

**Additional context**

**Comment by Geeknerd1337** [comment]
Honestly just having an `Event.Run.Client("someEvent")` would be useful to have and probably would be easier to set up with how I understand the code generation for ClientRPCs work.
