### ISSUE TITLE
Objects & surfaces outside of probes will never receive any reflection

### ISSUE THREAD

**Issue by KayaDLX** [sboxgame/issues#1483]
**Describe the bug**

Whenever your map is missing a probe in a certain area, all that part of your map will be totally missing reflections & accurate lighting. This has been the case for a few months now.

**Expected behavior**

In Half-Life: Alyx and previously in s&box, any objects outside of probe boundaries would receive light data from the closest probe.

**s&box**
![image](https://user-images.githubusercontent.com/67245359/149186708-0e1bc7d6-1b1a-48a5-b71b-612da2e5550f.png)

**HLA**
![image](https://user-images.githubusercontent.com/67245359/149186773-1d96d960-565c-486d-af74-027acc6873fc.png)

**Video (HLA vs s&box)**

https://user-images.githubusercontent.com/67245359/149185762-e9bc0d5a-a7e4-4443-8ff7-1e2a4c5021ee.mp4

**VMAP + VPK files**

[probes.zip](https://github.com/Facepunch/sbox-issues/files/7856417/probes.zip)

**Additional context**

At some point in s&box, the objects would receive light data from the FIRST (and not closest) probe placed in your map, which was reported and "fixed", now it's totally blank. (see https://github.com/Facepunch/sbox-issues/issues/369)

**Comment by Moofers** [comment]
Same.
