### ISSUE TITLE
Cubemaps boundaries will z-fight if placed exactly on the map surfaces

### ISSUE THREAD

**Issue by KayaDLX** [sboxgame/issues#1484]
**Describe the bug**

Related to https://github.com/Facepunch/sbox-issues/issues/1483 & asked by @ogniK5377 to open a separate issue for this:

As surfaces outside of probes don't receive any reflections, if your cubemaps boundaries are exactly placed on your mesh, it will z-fight between the cubemap reflection & the surface that doesn't receive light.
(That is just my guess, I don't exactly know what's happening but I'm sure it's somewhat related).

https://user-images.githubusercontent.com/67245359/149188577-902a5d5d-4904-49cf-ba33-88cb3507bc16.mp4

**To Reproduce**

1. Place a `env_combined_light_probe_volume`  on your map
2. Resize it to be sized perfectly on a surface
![image](https://user-images.githubusercontent.com/67245359/149189319-2588be25-fcd8-44c5-8b9d-4db307004736.png)
3. Flickers on the surface will happen in game once baked

**Expected behavior**

As surfaces are supposed to receive reflections even if they're outside of cubemap boundaries (https://github.com/Facepunch/sbox-issues/issues/1483), the cubemaps reflections should not z-fight.
See this HLA's video clip showcasing it:

https://user-images.githubusercontent.com/67245359/149188982-96f54f3f-b75c-491e-a359-788466d5d2c8.mp4

**Comment by celebeimre67** [comment]
yeah I was previously mentioned the z-fighting issue. It's still there and it's annoying.. https://github.com/Facepunch/sbox-issues/issues/1149

**Comment by erikSaandy** [comment]
This is still not fixed! Having to resize the cubemap volumes to get around this is a suboptimal workaround. this affects every map with cubemap reflections.
