### ISSUE TITLE
Host's game silently crashes upon sending files to connecting clients

### ISSUE THREAD

**Issue by Leafdroid** [sboxgame/issues#1509]
**Describe the bug**
Game appears to silently crash when under too much load from clients downloading your content, this takes a pretty long while to reproduce and there is nothing in the log about it so it's pretty iffy to describe. I had it occur ages ago when I had thousands of files that needed to be downloaded and just had it happen again today with 2000 files to download (500MB iirc) so I thought I should probably make an issue for it.

**To Reproduce**
1. Host a game with a large amount of content to download
2. Let someone join and download it
3. Wait...
4. Silently crash

**Expected behavior**
Not crash, or log why.

**Comment by KayaDLX** [comment]
That happened to me twice today too, was just alt tabbed while a few friends were joining me and downloading stuff from the #1508 issue, and it crashed my client from time to time.

**Comment by handsomematt** [comment]
![image](https://user-images.githubusercontent.com/1388267/158630404-6ca53b71-d82f-4fd0-a271-94ea3c6a5e37.png)

Probably same error, need to look for a memory leak in the file sending.
