### ISSUE TITLE
move gradient and cubemap fog to c# entities

### ISSUE THREAD

**Issue by DoctorGurke** [sboxgame/issues#1510]
**What can't you do?**
Have a gradient/cubemap fog entity on the map and have it appear in the entity list to modify its values in-game.

**How would you like it to work?**
Have env_gradient_fog and env_cubemap_fog moved to c# entities similar to spot lights etc, to be able to manipulate them at runtime via c#, including the entity inspector.

**What have you tried?**
The entities are currently in cpp and therefore do not appear in the entity list/inspector and cannot be changed by us at runtime.

**Additional context**
Might be worth to consider the volumetric fog entities as well, as since those can be for dynamic fog, too.

**Comment by ogniK5377** [comment]
I'll be planning on doing this when fog is reworked 👍

**Comment by DoctorGurke** [comment]
any update/info on this?

**Comment by DoctorGurke** [comment]
I'm not up-to-date on this, has there been any updates on this and/or can the issue be closed?
