### ISSUE TITLE
Zero-distance traces don't hit ragdolls

### ISSUE THREAD

**Issue by Leafdroid** [sboxgame/issues#1556]
**Describe the bug**
Traces that end and start at the same position completely ignore ragdolls unless they have a large radius.

**To Reproduce**
1. Run "TraceTest 0".
2. Doesn't hit.
3. Run "TraceTest 0.0001".
4. Hits.
```cs
[ServerCmd( "TraceTest" )]
public static void TraceTest( float traceDistance = 0f )
{
	ModelEntity ent = new ModelEntity( "models/citizen/citizen.vmdl" );
	ent.SetupPhysicsFromModel( PhysicsMotionType.Dynamic );

	TraceResult[] traces = Trace.Sphere( 16f, 0f, traceDistance )
		.EntitiesOnly()
		.RunAll();

	if ( traces == null )
	{
		Log.Info( "Did not hit ragdoll!" );
		ent.Delete();
		return;
	}
	else
	{
		foreach ( TraceResult trace in traces )
		{
			if ( trace.Hit && trace.Entity == ent )
			{
				Log.Info( "Hit ragdoll!" );
				ent.Delete();
				return;
			}
		}
	}

	Log.Info( "Did not hit ragdoll!" );
	ent.Delete();
}
```

**Expected behavior**
Hit ragdolls no matter the trace travel distance, same way it hits everything else.

**Additional context**
For some reason it does hit the ragdoll anyway if the trace radius is larger, but I can guarantee that the ragdoll is within range of the smaller radius aswell, in other words it should definitely hit.

**Comment by ogniK5377** [comment]
Is there any reason not to use `Physics.GetEntitiesInSphere` here? a 0 distance trace doesn't make much sense
