### ISSUE TITLE
Manipulating bone transforms on models with Dynamic PhysicsMotionType

### ISSUE THREAD

**Issue by Leafdroid** [sboxgame/issues#1569]
**What can't you do?**
You can't modify the bone transforms on physically simulated models, even if the bone in question doesn't have a connected PhysicsBody.

**How would you like it to work?**
Have SetBone() / SetBoneTransform() modify the bone on dynamic modelentites if it has no connected physicsbodies.

**What have you tried?**
This should ideally bend all of the fingers but only works if the PhysicsMotionType isn't set to Dynamic.
```cs
[ServerCmd]
public static void BreakFingers()
{
	if ( ConsoleSystem.Caller == null || ConsoleSystem.Caller.Pawn is not Player player )
		return;

	AnimEntity victim = new AnimEntity( "models/citizen/citizen.vmdl" );
	victim.SetupPhysicsFromModel( PhysicsMotionType.Dynamic );
	victim.Position = player.Position;

	for ( int i = 0; i < victim.BoneCount; i++ )
	{
		if ( !victim.GetBoneName( i ).Contains( "finger" ) )
			continue;

		Transform oldTransform = victim.GetBoneTransform( i );
		Rotation twisty = Rotation.FromPitch( Rand.Float( -60f, 60f ) );
		Transform transform = new Transform( oldTransform.Position, oldTransform.Rotation * twisty );
		victim.SetBone( i, transform );
	}
}
```
**Additional context**
I'm doing active ragdolling and need this to work in order to match the non-physical bones of the ragdoll to the animated model.

**Comment by Phyksar** [comment]
You're supposed to work with velocities if you're trying to move bodies, that's how any physics engine works. Changing bone transforms is pointless, you'll just end up teleporting into obstacles.

**Comment by Leafdroid** [comment]
If you actually read my issue you'd know I wasn't trying to physically move any bodies, I wanted the ability to change the rotation of bones that don't have any connected physics body.

**Comment by Phyksar** [comment]
The rotation is done by using `AngularVelocity`.
