### ISSUE TITLE
Low FPS

### ISSUE THREAD

**Issue by nocturni** [sboxgame/issues#1577]
**Describe the bug**

I have a Ryzen 7 3700X and a RTX 3070 that don't have any problems running modern games (170-250 fps depending on the game) except s&box, I get 40 to 60 at best, if nothing is rendered (noclipping into the void) it goes up to 80-110

In the main menu fps seem fine, 230-280 (getting in the games menu however, makes it go from 170 to 210, but I think that this is normal)

I run the game on a 1920x1080 165hz monitor, I want to also add that when I got access months ago, I didn't have so much problems running the game

**To Reproduce**

just launch s&box, get into the Sandbox gamemode (the official one, not a fork) and launch any map

**Expected behavior**

get a bit more fps

**Screenshots**

s&box dev performance tab in main menu
https://imgur.com/a/45dLA9z

s&box dev performance tab in construct
https://imgur.com/a/oL6dfS0

**Comment by ogniK5377** [comment]
Does the same happen when you run it in non-dev mode?

**Comment by nocturni** [comment]
Yes, if not worse.

**Comment by ogniK5377** [comment]
I do find it very odd that you're only getting 40-60 with that kind of hardware. Are you sure you're not running something in the background causing it to drop performance? Could it be a PC issue? We've had similar performances from other users with much higher framerates

**Comment by nocturni** [comment]
Certain, s&box is the only game where the issue happens.

**Comment by Unreal852** [comment]
Same here, it's even worse when i look at the buildings in the construct map. I also have a decent computer, and it only happens in this game.

**Comment by PixelQubed** [comment]
Same here; I mean, tiled rendering helped a little bit but not as much as I hoped. Not to mention tiled rendering has introduced this weird tiling bug in certain lighting situations. You are aware of this already, I believe. Hopefully, this performance issue can be fixed sometime soon.
