### ISSUE TITLE
Add Support for Gamemode Specific Damage Types/Flags

### ISSUE THREAD

**Issue by LeQuackers** [sboxgame/issues#1615]
**What can't you do?**
I can't add gamemode specific damage types/flags to ```DamageInfo```.

**How would you like it to work?**
Make ```DamageInfo``` a class so it can be inherited.

**What have you tried?**
```C#
public static class DamageInfoExt
{
	// Adding extra flags: only two bits to work with
	public static DamageFlags Ice => (DamageFlags)(1 << 30);
	public static DamageFlags Psychic => (DamageFlags)(1 << 31);


	// Using combinations: easially misinterpreted/error prone
	public static DamageFlags Bullet9mm => DamageFlags.Bullet | (DamageFlags)0x00000001; // DamageFlags.Crush (idk, probably fine)
	public static DamageFlags Bullet45acp => DamageFlags.Bullet | (DamageFlags)0x00000002; // DamageFlags.Bullet45acp would be equivalent to DamageFlags.Bullet
	public static DamageFlags Bullet556mm => DamageFlags.Bullet | (DamageFlags)0x00000004; // DamageFlags.Slash (might use incorrect decal)
	public static DamageFlags Bullet762mm => DamageFlags.Bullet | (DamageFlags)0x00000008; // DamageFlags.Burn (ignites things, lol)
}
```

**Additional context**
Rough draft example:
```C#
// not [Flags] in this case
public enum MyGamemodeAmmoTypes
{
	Generic = 0,
	Bullet9mm,
	Bullet45acp,
	Bullet556mm,
	Bullet762mm,
	
	// ...
	
	Bullet357mag = 99,
	Bullet50ae,
	Bullet57mm,
	
	// ...
	
	TankShellAPC = 219,
	TankShellAPFSDS,
	TankShellHEAT,
}

public class MyGamemodeDamageInfo : DamageInfo
{
	public MyGamemodeAmmoTypes AmmoTypeUsed { get; set; }
}
```
```C#
[Flags]
public enum OtherGamemodeElementFlags
{
	Generic = 0,
	Ice = 1 << 0,
	Psychic = 1 << 1,
	Earth = 1 << 2,
	Wind = 1 << 3,
}

public class OtherGamemodeDamageInfo : DamageInfo
{
	public OtherGamemodeElementFlags ElementFlags { get; set; }
}
```
```c#
public class SomeClass
{
	public void SomeMethod()
	{
		// ...
		var info = new MyGamemodeDamageInfo { AmmoTypeUsed = MyGamemodeDamageTypes.Bullet9mm };
		theEntity.TakeDamage(info);
		// ...
	}
}

public partial class MyEntity : Entity
{
	public override void TakeDamage(DamageInfo info)
	{
		if (info is MyGamemodeDamageInfo myInfo)
		{
			CustomBehaviorA(myInfo);
		}
		else if (info is OtherGamemodeDamageInfo otherInfo)
		{
			CustomBehaviorB(otherInfo);
		}
		
		DefaultBehavior(info);
	}
}
```

**Comment by Adesii** [comment]
Any reasons you aren't just making your own damage system? TakeDamage is just the base's game way of doing it. but nothing stops you from just making your own system. and have entities inherit your own Damage interface that takes your own DamageInfo

**Comment by LeQuackers** [comment]
I'm already doing that, and you're missing the point. The point of this is to have a common class that can be derived from. The benefits of polymorphism should be obvious, but these are probably the most important in this case:
* You would be able to derive from ```DamageInfo``` and do whatever you needed to.
* There would be, at minimum, ```DamageInfo``` compatibility between damage systems because of upcasting.

Keeping ```DamageInfo``` as a struct makes no sense. Telling people to build their own system while it's a struct makes even less sense and is a great way to make code smell:
* It's redundant; reinventing the wheel is a waste of time when you can just derive from it.
* It's not standardized; everyone that needs to will develop their own damage system, which means:
* If a developer uses an addon/gamemode with a struct DIY damage system in their own project, they need to tailor their own struct DIY damage system to match the addon/gamemode's system, or vise versa.

What arguments do you have for keeping ```DamageInfo``` a struct?
How do you expect developers to integrate damage systems with zero compatibility into their own damage system?

**Comment by Adesii** [comment]
its pretty much obsolete and only exists because the engine itself had it.
Giving people some basic thing is fine. But in most projects it should be custom regardless. 
(its way easier to make something custom than trying to fit something existing into your project)

it isn't redundant since it would be tailored to your gamemode. It doesn't need to be standardized because each gamemode would use it differently anyway.
and about addon/gamemode doing their own DIY damage system. yes that is the right way to do it. Gamemodes and addons don't need to be cross-compatible. this isn't gmod.
If you create a Addon for a Gamemode it needs to be specifically made for that Gamemode. so having their own Damage solution is irrelevant.

i don't have arguments to keep it a struct, i would probably prefer for it to just be removed.
or made into a Generic EntityComponent that takes a custom class.

The last question i don't really understand. it doesn't matter if there is zero compatibility.

**Comment by DevulTj** [comment]
This is being worked on on an internal branch.

In its current state, it works like this:

Api:
```csharp 
var dmg = DamageInfo.Generic( damageAmount ).WithFlag( "bullet" );
```
Usage:
```csharp
if ( dmg.HasFlag( "bullet" ) ) { ... }
```

**Comment by LeQuackers** [comment]
The latest refactor solves this, thanks!
