### ISSUE TITLE
Custom asset type crash on load using default values in structs without a struct constructor present

### ISSUE THREAD

**Issue by DoctorGurke** [sboxgame/issues#1625]
**Describe the bug**
Having default values on struct properties used in a custom asset type will crash the game on load if there's no struct constructor present, assuming the asset type has at least one value changed from its default.

**To Reproduce**

Create an asset type using the code below
```csharp
using Sandbox;
using System.ComponentModel;

public struct TestStruct
{
    [Property] public float Test { get; set; } = 1;
}

[Library("testbug"), AutoGenerate]
public class TestAsset : Asset
{
    [Category("Info")] public string AssetInfo { get; set; } = "asset_info";
    [Category("Test Category")] public TestStruct TestStruct { get; set; }
}
```
Create an asset using this type. First leave the default values and notice it loads fine. Then, change at least one of the default values, in this case the string value of AssetInfo and notice the game will crash on load.

This will NOT crash.
![image](https://cdn.discordapp.com/attachments/837215495496663040/942444600851853392/sbox-dev_hBZINK5mlw.png)

This WILL crash.
![image](https://cdn.discordapp.com/attachments/837215495496663040/942444615909380146/sbox-dev_PT59bW86KS.png)

Adding a constructor to the struct will prevent the crash.

```csharp
using Sandbox;
using System.ComponentModel;

public struct TestStruct
{
    [Property] public float Test { get; set; } = 1;

    public TestStruct(float test)
    {
        Test = test;
    }
}

[Library("testbug"), AutoGenerate]
public class TestAsset : Asset
{
    [Category("Info")] public string AssetInfo { get; set; } = "asset_info";
    [Category("Test Category")] public TestStruct TestStruct { get; set; }
}
```

**Expected behavior**
For it to properly handle default values on structs when an asset type has changed values, without crashing on load.

**Additional context**

This crash will not produce a crash mdmp.

**Comment by robotboy655** [comment]
Looks like you are hitting this bug:
https://github.com/dotnet/runtime/issues/62983

Which by the looks of it is fixed for .NET 7
