### ISSUE TITLE
Add "retry" concommand to reconnect to server

### ISSUE THREAD

**Issue by randomperson189** [sboxgame/issues#1640]
**What can't you do?**
There is no retry command as there was in Source 1 and so that means I can't easily reconnect to a server if I got disconnected.

**How would you like it to work?**
Add the "retry" concommand to the console

**What have you tried?**
I've tried to go find the server again to reconnect but that takes too long compared to typing a simple command.

**Comment by DevulTj** [comment]
Use `restart`, it already exists.
