### ISSUE TITLE
Support for Hammer Entities to have Array Properties

### ISSUE THREAD

**Issue by matekdev** [sboxgame/issues#1645]
**What can't you do?**

I want to be able to define Arrays on Entities and modify them in hammer.

**How would you like it to work?**

Similar to how they function in assets, I'm pretty sure you can at least define arrays of strings on assets.
```cs
[Property]
public AmmoType[] AmmoTypesToSpawn { get; set; }
```

**What have you tried?**

The following code above which generates an error 
```
Failed to load FGD file 'C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\ttt\config\matt.ttt.fgd'. Encountered errors:
 12:32:47   C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\ttt\config\matt.ttt.fgd(109): FGD Parse error:  near ']' - No choices specified. Expected '=' '[' ']'
```

**Comment by handsomematt** [comment]
I thought this already worked with List<T>?

**Comment by mzegar** [comment]
So attempting `List<string>`/`List<int>` gets you something like this
![image](https://user-images.githubusercontent.com/32153021/158285713-176c86ac-1a30-4df5-958d-bb9b7de890a9.png)

It'd be cool if we could actually have a list appear in the Hammer editor, similar to how `List` works in the `assets`.

**Comment by Geeknerd1337** [comment]
This would still be nice to have
