### ISSUE TITLE
Asset properties with custom names remain uninitialized on load

### ISSUE THREAD

**Issue by TheBerkin** [sboxgame/issues#1699]
**Describe the bug**
When an Asset property is given a custom name override like this:

```cs
[Library("test"), AutoGenerate]
public class TestAsset : Asset
{
    [Property("test_property")]
    public string TestProperty { get; set; }
}
```

... it generates a correct .asset with the expected property name:

```fgd
@BaseClass = test : ""
[
    test_property(string) : "Test Property" :  : ""
]
```

... and assets created with that type in the Inspector use the correct property name as well.

However, when those assets are loaded via `Asset.FromPath<TestAsset>( ... )` the property is not set and will retain its default value. 

**To Reproduce**

1. Create a custom asset class with a property including a `[Property]` attribute with a custom name.
2. Create an asset of that type in the Inspector and save it somewhere.
3. Attempt to load it ingame using `Asset.FromPath<T>`.
4. Log the loaded asset and observe that the property in question has not been initialized.

**Expected behavior**
Asset properties with custom names should be initialized as expected.

**Comment by robotboy655** [comment]
I am fairly certain this is no longer a problem.
