### ISSUE TITLE
OnChildAdded() gets called before ClientSpawn()

### ISSUE THREAD

**Issue by kolexxx** [sboxgame/issues#1702]
**Describe the bug**
`OnChildAdded()` gets called before `ClientSpawn()`, I don't think this is the intended behavior.

**To Reproduce**
1. Download [minimalexample.zip](https://github.com/Facepunch/sbox-issues/files/8341511/minimalexample.zip)
2. Observe the logs.

**Expected behavior**
`ClientSpawn()` should be getting called first, because we might be setting something in it that might be then checked in`OnChildAdded()`.

**Screenshots**
![Desktop Screenshot 2022 03 24 - 13 43 24 33](https://user-images.githubusercontent.com/48793595/159919776-590c4a3c-71bc-40f1-b19f-5ffe0a30d9c6.png)

**Comment by DoctorGurke** [comment]
Is onchildadded being called serverside? Clients pawn gets called clientside when the entity is replicated to the client, so if child added is called serverside it'd make sense that it's this way around

**Comment by kolexxx** [comment]
> Is onchildadded being called serverside? Clients pawn gets called clientside when the entity is replicated to the client, so if child added is called serverside it'd make sense that it's this way around

OnChildAdded is being called clientside as well, before ClientSpawn.
