### ISSUE TITLE
Downloading S&Work model Overrides model in Addon folder

### ISSUE THREAD

**Issue by Baik90** [sboxgame/issues#1710]
**Describe the bug**
If you download your own model from s&works it overrides the one in you Addon folder.

**To Reproduce**
1. open a Gamemode wich has S&works in it (Like Sandbox)
2. Go to the S&works tab in the "Q" Menu
3. Download your model from S&works
4. Try to Make a Change on your Model in ModelDoc
5. Nothing change.

**Expected behavior**
See the Changes you made on your Model even if you Download it from s&works

**Video**
https://user-images.githubusercontent.com/88790023/160266103-e0980d52-c761-48bb-be76-08ab319a0d82.mp4

**Additional context**
It looks like he set the .vmdl in the Download folder with a Higher Hierarchy.

**Comment by ogniK5377** [comment]
I feel as if this will open up a huge range of issues regarding dependencies if we allow this. Is there any reason you need to do this? Generally you'll be verifying your models before uploading them

**Comment by Baik90** [comment]
I think you got me wrong, my bad sorry.
lets say you create a Model and Upload it.
to test it you open a Game and Download it from s&works
Now you have to Copys of your file one in the Download folder and One in the addon folder
later the day you want to change something like add AO Proxy or add a Material group or whatever.
you will not be able to see any changes until you either upload the file (the one on you addon folder) or delete the old file from the download folder.
if this is intended, then just ignore what I said
