### ISSUE TITLE
Hotloading causes errors with [Net] marked Lists on EntityComponents

### ISSUE THREAD

**Issue by Fortune117** [sboxgame/issues#1712]
**Describe the bug**
After hotloading the game twice, the console begins to be filled with errors that look like this:

![image](https://user-images.githubusercontent.com/7847372/160470469-f27a83f5-3324-4aca-9640-47d429da9c33.png)

**To Reproduce**

1. Define a custom component and class:
```CS
public partial class TestComponent : EntityComponent
{
    [Net] public List<TestClass> TestList { get; set; }

    public void Test()
    {
        for (var i = 0; i < Rand.Int(1, 4); i++)
        {
            var test = new TestClass();
            test.MyFavouriteInt = Rand.Int(10);
            TestList.Add(test);
        }
        Log.Info("test");
    }
}

public class TestClass : BaseNetworkable
{
    public int MyFavouriteInt { get; set; }
}
```
2. Bind the component to the player
```CS
[BindComponent]
public TestComponent TestComponent { get; }

public override void Spawn()
{
      Components.Create<TestComponent>();
      TestComponent.Test();
}
```
3. Hotload twice. After the first hotload, there'll be messages like this in console:
![image](https://user-images.githubusercontent.com/7847372/160470830-c2a17602-8c35-43a4-a0fb-118cee1c9ee9.png)

After the second hotload, you'll see the aforementioned errors.

**Expected behavior**
No errors appear in console.

**Extra Info**
I believe this also happens with dictionaries, but haven't thoroughly tested that.

**Comment by TheBerkin** [comment]
I ran into this as well. Here's my stack trace and relevant type layout in case it helps:

![image](https://user-images.githubusercontent.com/1622492/160487318-eae3b339-bc05-4e72-ae41-c02b6558f564.png)

![image](https://user-images.githubusercontent.com/1622492/160487338-43d4717b-d436-4f84-8109-24dc45f70c1f.png)

![image](https://user-images.githubusercontent.com/1622492/160487365-a70b1997-15e3-4f71-a6cd-54b6b444c2de.png)

**Comment by DevulTj** [comment]
Relatively certain this is the same problem as https://github.com/Facepunch/sbox-issues/issues/1039

**Comment by trundler-dev** [comment]
Same issue but I'm using a `[Net] IList<string>` so I don't think it's specific to BaseNetworkables.
