### ISSUE TITLE
`BaseNetworkable` / `Components` should support `NetworkIdent`

### ISSUE THREAD

**Issue by matekdev** [sboxgame/issues#1719]
**What can't you do?**

Use `NetworkIdent` on a `BaseNetworkable`/`Component` I created.

**How would you like it to work?**

Just like `NetworkIdent` when using anything else.

**Additional context**

When trying to fetch the `NetworkIdent` of a `BaseNetworkable`/`Component` it ends up being `0`.

**Comment by xezno** [comment]
This exists, it points to the NetworkIdent of the entity itself (because that's how we network components)
