### ISSUE TITLE
Create Sound Asset With Multiple Sound Files

### ISSUE THREAD

**Issue by gvarados1** [sboxgame/issues#1720]
**What can't you do?**
We can't select multiple sound files and create one sound asset containing all the files

**How would you like it to work?**
If we have multiple sounds selected, we should be able to right click and create a sound asset that contains all the selected files.

If we select one sound file, we can create a sound asset:
![image](https://user-images.githubusercontent.com/39461072/161189258-59636c1e-07d8-4199-930a-e6676ccb804a.png)

If we select multiple sounds, we don't have that option:
![image](https://user-images.githubusercontent.com/39461072/161189386-b4fa031a-a4b2-4a81-9f01-6568f5c35555.png)

We should be able to select multiple sounds & click Create Sound. This would add all the select sound files to one asset:
![image](https://user-images.githubusercontent.com/39461072/161189559-9d2ee416-bf00-4786-9a00-92b7d081c3df.png)

**What have you tried?**
Currently, we have to select one sound file, create the asset, then manually add each alternative sound file.

**Comment by DoctorGurke** [comment]
Adding to this, the inspector is really annoying to use when you're dealing with multiple asset files. Having something like the material editor where multiple assets are opened in the same window and listed on the side would be awesome, maybe even grouped by extension

**Comment by robotboy655** [comment]
This is solved.

![image](https://user-images.githubusercontent.com/3299036/204866665-70e25e2e-036a-4d64-843b-371e7c5fc9fc.png)

You can also drag'n'drop multiple files from the new asset browser to the asset editor.
