### ISSUE TITLE
More AO Proxy Shapes

### ISSUE THREAD

**Issue by gvarados1** [sboxgame/issues#1735]
**What can't you do?**
Currently we only have box and capsule ao proxy shapes in modeldoc. This works for most props but is very awkward for something like a spool or barrel which is all cylinders
![image](https://user-images.githubusercontent.com/39461072/161888295-48913184-66cc-4aac-bdc9-5342425a35f6.png)

**How would you like it to work?**
We should have cylinder and sphere shapes to be consistent with physics shapes.
![image](https://user-images.githubusercontent.com/39461072/161888491-5a10482f-7093-440d-b518-373745c04a5e.png)

It would also be nice if we could use meshes for AO proxy but idk how any of that works so it might be unfeasible.

**Comment by samzanemesis** [comment]
I have plans to include a cylinder shape, the data structures for that are in place

Sphere should just be a 0-length capsule
