### ISSUE TITLE
Hammer Entity to Detect Which Game You're Playing

### ISSUE THREAD

**Issue by gvarados1** [sboxgame/issues#1751]
**What can't you do?**
We can't determine which game is being played with map logic.

This is useful for minor core entity changes between games. (entities in the core addon ex. prop_physics, lights)
For example, if I wanted my map to support Prophunt and Conquest, I would have to make two separate versions. One version with a lot of physics props for Prophunt, and one map without props for Conquest.
![image](https://user-images.githubusercontent.com/39461072/163036158-d08e0455-51bd-4b36-9503-b523298ab9fe.png)

**How would you like it to work?**
A map entity would probably work best. We'd set a property for the game name (ex. matt.ttt) and it'd check if we're on that game. If we are, it fires an output.

**What have you tried?**
Currently we have to do a super hack:
We have to place a game-specific entity in our map (ex. weapon from ttt) and check if that exists with a trigger. If it exists, we know that we're on that game.

**Comment by handsomematt** [comment]
Closing since we're aiming for stuff like this to be done as cloud entities
