### ISSUE TITLE
Custom Asset Types aren't converted to the Asset itself. When using [ResourceType]

### ISSUE THREAD

**Issue by Adesii** [sboxgame/issues#1798]
**What it is**
Custom Asset Types set in Hammer have to be on String Properties rather than on the Asset type itself.
This causes an unnecessary step that should be avoided.

this is the current way you need to set an Asset if exposed to Hammer:
![image](https://user-images.githubusercontent.com/37816311/166920624-6030e054-ed17-4ffa-ac41-a25c4a7914a5.png)

Having to manually get the Asset instead of it Auto Assigning to the correct AssetType. Seems like a Redundant step.

**What it should be**
The ResourceType Attribute should directly return the Correct Asset type so this Extra step isn't needed.
instead of how its shown in the picture above it should be as simple as:
![image](https://user-images.githubusercontent.com/37816311/166921233-441779ec-640d-4771-90d6-132188aa22b3.png)

Perhaps even without the Library Type name, since it could just derive the Type from the Property Type.
![image](https://user-images.githubusercontent.com/37816311/166921499-b3d80bf5-7d73-4aba-acac-7b0d9bec155c.png)

**Comment by robotboy655** [comment]
I am fairly certain this was fixed a while ago.

**Comment by Adesii** [comment]
> I am fairly certain this was fixed a while ago.

![image](https://user-images.githubusercontent.com/37816311/203165485-592e0c7b-210b-4d4d-9f55-13e6afc7a986.png)
does not seem to be fixed

**Comment by robotboy655** [comment]
Should be working now, without the need for `[ResourceType]`

**Comment by Adesii** [comment]
Yeah works great now. Thanks
