### ISSUE TITLE
CSM Shadows on Light_Spot

### ISSUE THREAD

**Issue by PixelQubed** [sboxgame/issues#1818]
### For?

S&Box, Hammer

### What can't you do?

Hello, I would like to see the CSM shadow system added to light_spot so the shadows cast are sharp just like light_ortho. The reason I cant just use light_ortho is due to there not being a cone of influence so the light doesn't spread out at more than one specific angle. I tried using per-pixel lighting on the light_spot but it's useless when you need sharp shadows on the light.

### How would you like it to work?

Add an option for sharp shadows or overwrite per-pixel lighting so it uses the same system as light_ortho and light_env

### Additional context

**Light Ortho**
<img width="1920" alt="sbox_NaLajJzg1F" src="https://user-images.githubusercontent.com/32498714/167669113-d1204e8d-255d-4b4b-9d22-46248a49fe0b.png">
**Light Spot**
<img width="1920" alt="sbox_sLCwTHMwWV" src="https://user-images.githubusercontent.com/32498714/167669129-3c32402c-bb82-4c43-a133-96b62ceb5069.png">

**Comment by VeeSaus** [comment]
The resolution of a given shadow is always defined by the lightmap quality/resolution of that area. Lowering the light source radius and adjusting the cone angles will yield sharper shadows.

**Comment by PixelQubed** [comment]
This is still an issue currently.
