### ISSUE TITLE
Tools: Cannot properly disable resizability on custom tools windows

### ISSUE THREAD

**Issue by DoctorGurke** [sboxgame/issues#1827]
### Describe the bug

Trying to fully disable resizability on tools windows seems to do nothing. The resize button on the StatusBar will always be there unless the StatusBar is destroyed and your cursor will always go into resize mode on the window edges.

### To Reproduce

Use the following code to make a test window.

```csharp
public class TestWindow : Tools.Window
{
	public TestWindow()
	{
		ResizeButtonsVisible = false;

		Size = new( 500, 500 );

                // hack to disallow resizing
		MinimumSize = Size;
		MaximumSize = Size;
		
		Show();
	}

	[Tools.Menu( "Editor", "Test Window/Open Rescale Test Window" )]
	public static void ExampleMenuOption()
	{
		_ = new TestWindow();
	}
}

```

### Expected behavior

Risizable should probably just be a single bool on the window that controls all of this. Disable the resize button, resizing of the window and the resize cursor on window egdes.

### Media/Files

![sbox-dev_IQlYkWPtWh](https://user-images.githubusercontent.com/12602100/168325476-672af604-55b5-4299-98c7-5e9255f21183.png)

### Additional context

If there is any property I've missed that already allows this that's my bad.

**Comment by xezno** [comment]
This is pretty old, I think you can just derive from Dialog (instead of Window) to get this functionality now - does that cover your use case?
