### ISSUE TITLE
Editor: GameResources with an underscore in their extension will compile with the wrong extension

### ISSUE THREAD

**Issue by xezno** [sboxgame/issues#1859]
### Describe the bug

Using an underscore in the file extension for a custom GameResource will cause it to end abruptly as if it's using that underscore as the offset for a substring

### To Reproduce

1. Download this minimal repro game:
[gameresource_repro.zip](https://github.com/Facepunch/sbox-issues/files/8759076/gameresource_repro.zip)
2. Run the game so that the game recognises the custom asset type
3. Right-click on the data folder, and add a "New Example Resource" (next to `test.ex_rsrc`)
4. Change the fields and save, or force a full compile
5. Observe how the extension for the compiled asset is incorrect:
![image](https://user-images.githubusercontent.com/12881812/169934956-a8fe7431-bf6d-4324-83ff-6c6c630db4f1.png)

### Expected behavior

Rather than `test.ex_c`, the compiled file should be `test.ex_rsrc_c`. Either that or the game should tell you that you can't put underscores in extensions.

**Comment by garrynewman** [comment]
I think this makes sense, we should forbid extensions with these underscores instead.
