### ISSUE TITLE
Add map <empty> to lobby map selection UI

### ISSUE THREAD

**Issue by DrewBritt** [sboxgame/issues#1890]
### For?

S&Box

### What can't you do?

Players are unable to select no map/\<empty> in the map selection UI. For my game Sketch, the camera simply spins in circles (like Pixel Wall), and I'd like to support \<empty> as well as other maps in case the player wants a "background" for the game.

### How would you like it to work?

Players should be able to select \<empty> as a map from the lobby map selection UI (all maps/"this list only" maps).

### What have you tried?

Currently, my game uses Gvarados' "empty.map" which in practice is the same thing, however supporting the official solution (\<empty>) is ideal.

**Comment by DevulTj** [comment]
I don't think we should be supporting this officially
