### ISSUE TITLE
Devcam - Hold Space to Move Up

### ISSUE THREAD

**Issue by gvarados1** [sboxgame/issues#1908]
### For?

S&Box

### What can't you do?

We can't move the camera directly up with the devcam. This is very useful for cinematic video shots

### How would you like it to work?

Holding the jump key should move the camera up in the devcam

### What have you tried?

there is nothing to try other than making my own devcam

**Comment by GunnarKafel** [comment]
Would be nice if crouch moved the camera down as well

**Comment by gvarados1** [comment]
crouch is slow, so move down would have to be another key like reload

**Comment by walllable** [comment]
who said is has to be slow?

**Comment by gvarados1** [comment]
me

**Comment by JammieDodgerr** [comment]
In Unreal the scroll wheel changes your speed when flying around, works pretty well.

**Comment by gvarados1** [comment]
yeah that'd be better
