### ISSUE TITLE
Introduce [ServerRPC](or a better name) Attribute similar to [ClientRPC]

### ISSUE THREAD

**Issue by ogniK5377** [sboxgame/issues#191]
**What can't you do?**
Ability to call server-side functions from the client. Currently, the only way to relay information from the client back to the server is via `[ServerCmd]` and `ConsoleSystem.Run`. Having something less hacking would be nice, similar to how the `[ClientRPC]` attribute is setup.

**How would you like it to work?**
```cs
// Server
[ServerRPC]
public static void Foo(Player caller, int foo, int bar) {
	// ...
	// foo is 123
	// bar is 456
}

// Client
Foo(123, 456);
```

**What have you tried?**
```cs
// Server
[ServerCmd("Foo")]
public static void(int foo, int bar) {
	Player caller = ConsoleSystem.Caller;
	// ...
	// foo is 123
	// bar is 456
}

// Client
ConsoleSystem.Run( "Foo", 123, 456 );
```

**Additional context**
ServerRPC is not really a good name as it implies that the server is replicating a client value but it's not something always being done at this point. It's usually used to indicate an action to the server. A name like `Notify` might work better

**Comment by AMastryukov** [comment]
I think it would be nice to have simpler implementations for server messages than having to explicitly create methods with the RPC attributes.

Perhaps something that does this on the backend automatically and allow developers to just call a static method to send RPCs with a static method, like so:

From Server to Specific Client:
Network.ToClient(Method(), Client)

From Server to All Clients:
Network.ToAllClients(Method())

From Client to Server:
Network.ToServer(Method())

I think this would keep things cleaner and simpler to look at. The backend could have auto generated RPC static methods if needed.

**Comment by trende2001** [comment]
bump
