### ISSUE TITLE
ShadingModelStandard looks incorrect when fully unlit

### ISSUE THREAD

**Issue by Willco2** [sboxgame/issues#1961]
### Describe the bug

A shader/material that uses `ShadingModelStandard` still appears slightly visible when completely unlit.

### To Reproduce

1. Spawn a model that uses `ShadingModelStandard` in the `<empty>` map
2. Observe that the model is still partially visible
3. Edit the shader to use `ShadingModelValveStandard` instead and it will appear fully unlit as expected

### Expected behavior

ShadingModelStandard should look mostly like the Valve version, in terms of being fully darkened by absence of light.

### Media/Files

ShadingModelStandard:
![bad](https://user-images.githubusercontent.com/33941498/174713862-3f231a4a-bb7b-4f17-9bd9-830e7acecc5f.png)

ShadingModelValveStandard:
![good](https://user-images.githubusercontent.com/33941498/174713864-659caff0-f781-4cec-8864-6d090f32c0bd.png)

### Additional context

I've made sure to turn off any ambient lighting with `Map.Scene.AmbientLightColor = Color.Black;`

**Comment by handsomematt** [comment]
Deleted this ages ago
