### ISSUE TITLE
Animgraph - Transfer morphs from bonemerged models if you use the same animation name

### ISSUE THREAD

**Issue by KaesarZZ** [sboxgame/issues#1964]
### For?

Other

### What can't you do?

First of all, I don't know if this would be possible, but I have found myself needing to have something like this, so I'll just throw the idea out there. 

My example is a playermodel and a balaclava model that I want to merge, I've created an animation in both models using morphs called "Open_Mouth" for the voicechat, but currently a merged model isn't able to reproduce morphs. 

### How would you like it to work?

It would be nice if when you add a merged model in animgraph (or ingame) it would also activate its morphs somehow using the animation node (if the merged model has the animation with the same name).

### What have you tried?

Currently, I believe the only option that has been considered but not done is to control every morph using code. I guess this is a simpler alternative in these cases?

**Comment by MaxLebled** [comment]
We already have a feature in place so that bonemerged models replicate the morphs of their parent as long as they are named the exact same. Only the parent needs to be animated.

A ConVar is controlling it, sbox_feature_inheritmorphs, but it should be on by default?

**Comment by KaesarZZ** [comment]
Oh, nice. 

I mean, why not? I don't see a problem with this being on by default, you always do it consciously. And we get the possibility to test it in modeldoc/animgraph.

**Comment by MaxLebled** [comment]
I'll be filing an issue internally to have this working in tools
