### ISSUE TITLE
Make EyePosition, EyeLocalPosition, EyeRotation, EyeLocalRotation virtual

### ISSUE THREAD

**Issue by rileyzzz** [sboxgame/issues#1965]
### What it is?

EyePosition, EyeLocalPosition, EyeRotation, and EyeLocalRotation are not virtual properties, even though stuff like Location, Rotation, etc are

### What should it be?

These properties should be made virtual so that derived classes can specify their own behavior for getting and setting an entity's eye transforms.

**Comment by handsomematt** [comment]
I wonder if we should delete these.

**Comment by rileyzzz** [comment]
I think there's an argument to keep them, because if you're building your own pawns deriving from Entity (instead of Player) they serve as an easily accessible serverside view offset (even if the actual view updating is going on inside CameraMode)
Of course people can just roll their own, but if you've got gamemodes or libraries or whatever interacting with each other and you're trying to get the direction a player or NPC is looking, you might only know that the target is an Entity
that isn't too critical of a thing for my use case, but it is annoying that they aren't virtual because I've got a few classes that would really benefit from being able to provide custom EyePosition/EyeRotation accessors
I'd say either make them virtual or remove them entirely to prevent confusion

**Comment by garrynewman** [comment]
TBH we should really look through the entire of Entity and work out what properties we should/shouldn't have on there. Things like life state and health shouldn't be in there imo. Like sure it makes things easier, if you're doing that, but Entity should be the bare ass minimum. Basically a transform.

**Comment by handsomematt** [comment]
All of this turned into [AimRay](https://asset.party/api/Sandbox.Entity.AimRay)
