### ISSUE TITLE
info_particle_system "Start Active" Doesn't work in multiplayer

### ISSUE THREAD

**Issue by gvarados1** [sboxgame/issues#1979]
### Describe the bug

"Start Active" on info_particle_system only starts when the server starts. It's not sent to new players when they join, so only the host sees the particles.
![image](https://user-images.githubusercontent.com/39461072/175834715-dcefad38-2926-4de8-9e74-820e71290f87.png)

### To Reproduce

1. Start a server locally on a map that has "Start Active" particles (Cursed Shaft, Desert Ruins)
2. You will see the particles

(Cursed Shaft and Desert Ruins have a rolling fog/dust particle)

https://user-images.githubusercontent.com/39461072/175834631-352b0499-a2d6-46e0-894a-9051705101c6.mp4

4. Join a server running a map that has "Start Active" particles
5. You will not see the particles

### Expected behavior

Particles with "Start Active" should play on new clients, not just clients who were on the server when it initially started (server host)

**Comment by robotboy655** [comment]
I have made some changes to the base game that should address particle state not being synched in multiplayer properly, especially for joining players.
