### ISSUE TITLE
Utility function for loading a vmap into a SceneWorld

### ISSUE THREAD

**Issue by JamDoggie** [sboxgame/issues#1990]
### For?

S&Box

### What can't you do?

It is currently very annoying creating any sort of scene in a SceneWorld, as you have to hardcode the positions of every object and light in it. 

### How would you like it to work?

A solution to this problem would be some sort of way to load a compiled vmap, or maybe even just hammer prefabs or something.

Actual use could look something like `SceneWorld.LoadFromMap(map)`

### What have you tried?

N/A

### Additional context

Obviously this doesn't necessarily have to be actual compiled maps, but just some way of getting objects from hammer into a SceneWorld would be nice.

**Comment by aylaylay** [comment]
It's pretty easy to just spawn a (compiled) vmap so it wouldn't have to be uncompiled, uncompiled wouldn't even work anyway. The issue currently with vmap spawning is that it doesn't play nice spawning multiple of them. Spawning a single vmap into a scene world might be a good place to start with this feature so I'll look into that.

**Comment by JamDoggie** [comment]
Sounds great, this feature would be really cool for setting up neat backgrounds for game menus (kinda like the CSGO menu, but actually rendered and not an mp4)

**Comment by aylaylay** [comment]
We now have scene maps which allow you to render (compiled) maps in scene worlds
