### ISSUE TITLE
Better Default Navmesh Generation Parameters

### ISSUE THREAD

**Issue by gvarados1** [sboxgame/issues#1999]
### For?

Hammer

### What can't you do?

The current default navmesh generation parameters do not include jump up/down (aka climb/drop) connections. Most maps will use this so most maps will have sub-optimal nav.

![image](https://user-images.githubusercontent.com/39461072/177054640-8d740c89-3a3c-467b-b522-8158542ea6bc.png)

By default, Agent 0 uses the Half-Life: Alyx Combine Soldier nav settings. There are no climb/drop) connections so this limits npcs on any map without a custom nav.
The new NavPathBuilder lets us specify maximum climb/drop heights, so this will not affect npcs that can not climb/drop.

### How would you like it to work?

The default Max Jump Down/Up Dist for Agent 0 should be set to a large number. I think 1024 sounds reasonable but the input box currently only goes up to 1000:
![image](https://user-images.githubusercontent.com/39461072/177055162-60bacce2-9561-4646-9fdc-ca6847b489ea.png)

Again, there is no downside to this because you limit how far an npc will climb/drop in the code. If you only want your npc to jump 64 units, you'd tell that to NavPathBuilder.

### What have you tried?

Currently any game that wants to support npcs jumping needs to have all their maps use a custom navmesh. This includes NPC zombie horde and also games like Conquest on Metro. Bots/NPCs can't path up/down little ledges like this without custom nav parameters:
![image](https://user-images.githubusercontent.com/39461072/177055282-95a9e303-486a-4c68-bd99-249ff88d4811.png)

### Additional context

Also any time we load a map with custom nav parameters we get this little warning in the top of the screen. It doesn't mean anything and can be removed
![image](https://user-images.githubusercontent.com/39461072/177055366-74940c02-b940-411d-9f92-fcaa4fed6d47.png)

**Comment by yuberee** [comment]
The "Navigation mesh was generated with non-default agent settings." is clearly a leftover from Half Life: Alyx, I thought it only showed up in Tools Mode but I've had it show up in Release Mode as well.
I'm sure it's a line away from being removed.

**Comment by bakscratch** [comment]
Addressed these 2 issues, feel free to close if its ok

**Comment by gvarados1** [comment]
Thank you bakky ❤❤❤❤
