### ISSUE TITLE
New Assets Browser - dmx file type filter toggle

### ISSUE THREAD

**Issue by QuackCola** [sboxgame/issues#2054]
### For?

S&Box, Assets Browser

### What can't you do?

Unable to just click to toggle on/off dmx file filtering.

### How would you like it to work?

Just like the other filters.

### What have you tried?

adding t:dmx to the search bar manually, which is fine by me but it would make sense it be included along with the rest of the filters.

**Comment by handsomematt** [comment]
By that logic we should add fbx, obj, wav, mp3, basically any source files. Seems like it'd completely bloat the list?

**Comment by DoctorGurke** [comment]
Aren't sound files under one category right now? Just unify model formats under one as well then if possible

**Comment by QuackCocaine** [comment]
> By that logic we should add fbx, obj, wav, mp3, basically any source files. Seems like it'd completely bloat the list?

you make a good point there matt. I guess merging model formats as @DoctorGurke suggested would be preferred instead of adding more bloat

**Comment by handsomematt** [comment]
If I'm looking for a model in Hammer, I really don't want it filled with fbx and dmx and bullshit too.
