### ISSUE TITLE
Non-Uploaded Local Gamemodes only available to play in Dev-tools

### ISSUE THREAD

**Issue by TheNameIsMatt** [sboxgame/issues#2057]
### Describe the bug

When I try to launch the game in normal s&box (non dev-tools) I am unable to start a local new game and get the following error.

![image](https://user-images.githubusercontent.com/77700466/180660566-6107ef6f-adb2-46a8-9846-cb58ca6602f6.png)
![image](https://user-images.githubusercontent.com/77700466/180660657-40b521fe-ec81-44c6-83e8-29dc3aae075a.png)

Launching my gamemode in dev-tools mode allows me to launch the gamemode normally.

Extra Issue (Might be related):
Changing Org to local in dev-tools mode and then restarting s&box in dev-tools mode, will also stop the gamemode being playable in dev-tools mode. until it is changed back to my organisation.

### To Reproduce

Unsure if this will be reproducible without my org.

1. Clone Repo https://github.com/imPukes/sboxTestingGrounds
2. Launch normally in dev-tools
3. Close down s&box and try to open local gamemode in standard s&box

### Expected behavior

Should be able to click "Create new game" when clicking on my local gamemode in normal s&box.

### Media/Files

Non tools mode
https://user-images.githubusercontent.com/77700466/180661112-deb38122-22be-4dd4-b8b3-959f75f470e0.mp4

Working tools mode

https://user-images.githubusercontent.com/77700466/180661175-45ce81ce-2716-47d5-897b-d5a55b45e79d.mp4

### Additional context

Windows 10.
NVIDIA Geforce GTX 1070 TI
16GB DDR4
Intel Core i5-8600K
TUF Z370-PLUS GAMING Motherboard

**Comment by imPukes** [comment]
Issue seems to be with the ident getting saved with a capital letter at the start. 

![image](https://user-images.githubusercontent.com/77700466/180661656-12c5dddc-43f7-4c22-8608-ce8113285929.png)

**Comment by handsomematt** [comment]
fixed ages ago (i think)
