### ISSUE TITLE
Custom sounds in maps don't play

### ISSUE THREAD

**Issue by gabengaGamer** [sboxgame/issues#2068]
### Describe the bug

After each restart of the game, the hammer editor forgets the path to the sound files.

### To Reproduce

1. Use entity witch sound import
2. Import CUSTOM sound file
3. Restart game
4. See this bug

### Expected behavior

Hammer must remember imported sounds

### Media/Files

https://user-images.githubusercontent.com/54669564/181542073-6810290a-d1e1-4fcf-ba41-e4f2eae1290a.mp4

### Additional context

This bug was in source 2, since the days of HLA, very annoying.

**Comment by gabengaGamer** [comment]
it doesn't work for me after compilation, minute, I'll upload the video

**Comment by gabengaGamer** [comment]
ops, I accidentally closed the issue, sorry

**Comment by gabengaGamer** [comment]
so, video: https://www.youtube.com/watch?v=MJULIJBkPSk

**Comment by handsomematt** [comment]
I think I see, the quality of the video is quite low but are the sounds you're using custom sounds in your map addon?

**Comment by gabengaGamer** [comment]
Additional: if you re-import bugged sounds, they will start working in the game in (1-40 sec)

**Comment by handsomematt** [comment]
Ah I see there's a few bugs around all this. I'll need to make sounds a proper dependency of maps. Thanks for the report. 👍

**Comment by roblox34** [comment]
When did you get the game?

**Comment by handsomematt** [comment]
This should finally work properly now, sounds will need to be reselected which will now include their full path, this will then make the map reference the assets properly so they'll always be uploaded / loaded with the map.
