### ISSUE TITLE
Map Uploading Not working

### ISSUE THREAD

**Issue by MikeShaughnessy** [sboxgame/issues#2134]
### Describe the bug

When I try to upload the map it either doesnt show up on asset.party or not all the assets get uploaded.

### To Reproduce

I dont know what causes this issue, Although when uploading, putting the maps vpk will include the assets if it normally doesnt. I was able to get the version to update after moving it to a diffrent org, and then after multiple trys it worked again after I added a file to the addons material folder. 

### Expected behavior

IT should update the version and upload all the assets.

**Comment by robotboy655** [comment]
Is this still a problem you are having? I have just updated the uploader to better handle errors, maybe it will give you an actual 
 error when it fails to upload.
