### ISSUE TITLE
Bodygroups are not adjusted properly with ClothingContainer.DressEntity

### ISSUE THREAD

**Issue by liquiad** [sboxgame/issues#2155]
### Describe the bug

If a player is currently dressed with clothing, and you remove those clothes and run DressEntity again, Terry's bodygroups from the old clothes will disappear.

My understanding is that DressEntity tries to handle setting the bodygroups correctly but it isn't working for some reason.

Maybe I am just doing this wrong? I tried manually resetting the bodygroups when re-dressing my player but I was getting strange inconsistent behavior.

### To Reproduce

I attached a repro addon.
[clothingcontainerbug.zip](https://github.com/Facepunch/sbox-issues/files/9305919/clothingcontainerbug.zip)

It loads a preset outfit I provided from JSON.

Look at yourself with the debug camera and then run `ClearClothing` in the console

```cs
[ConCmd.Server]
public static void ClearClothing()
{
	var player = (Player)ConsoleSystem.Caller.Pawn;
	
	player.Clothing.Clothing.Clear();
	player.Clothing.DressEntity(player);
}
```

![image](https://user-images.githubusercontent.com/13039986/184060906-8ee3da0e-297f-4afa-ae0b-f939245c51ca.png)

### Expected behavior

Terry should reset to being naked and not invisible.

### Media/Files

https://user-images.githubusercontent.com/13039986/184060740-c6bbf609-2ca0-4756-95a3-b063c74d9b71.mp4

**Comment by Watermelon914** [comment]
I've also noticed for some clothing items, it's does the mask the wrong way. Take a look below.
![image](https://user-images.githubusercontent.com/37270891/215077854-8b550495-1142-451a-b9cf-7488779f10c6.png)
![image](https://user-images.githubusercontent.com/37270891/215077869-aca76402-4f1c-4b2d-ab9e-2bb8c0e80e61.png)
When the clothing item is being worn, the skin is visible when it should be invisible. When it isn't, the skin is invisible when it should be visible.

Clothing item used is 1875643260
