### ISSUE TITLE
Crash on trying to offload SetupPhysicsFromModel

### ISSUE THREAD

**Issue by gartia** [sboxgame/issues#2160]
### Describe the bug

Whether or not i shouldn't be trying to async this. I was recommended to make a bug report due to it crashing.  I was trying to offload as much as possible to different threads, kept crashing used vscodes debugger to achieve the error below.

`Exception has occurred: CLR/System.AccessViolationException
An unhandled exception of type 'System.AccessViolationException' occurred in Sandbox.Game.dll: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'
<Cannot evaluate the exception stack trace>`

### To Reproduce

1. Create new ModelEntity
2. Run await GameTask.RunInThreadAsync( () => SetupPhysicsFromModel( PhysicsMotionType.Static ) );
3. Crash

### Expected behavior

Either this should just work, or send an error that it shouldn't be async'd. 

### Example Code
```using Sandbox;
public partial class TestModel : ModelEntity
{
	public async override void Spawn()
	{
		Model = Model.Load( "models/citizen_props/crate01.vmdl" );
		await GameTask.RunInThreadAsync( () => SetupPhysicsFromModel( PhysicsMotionType.Static ) );
	}
}

**Comment by aylaylay** [comment]
I feel like there's plenty of things you could optimize before ever needing to run this async. I'll just assert it.

**Comment by aylaylay** [comment]
Added an assert if you try to do this.
