### ISSUE TITLE
Visual bug when custom asset properties are hidden due to a ConditionalVisibilityAttribute

### ISSUE THREAD

**Issue by liquiad** [sboxgame/issues#2163]
### Describe the bug

If you have properties in a custom asset type that are currently hidden due to `ConditionalVisibilityAttribute`, the UI will flicker like crazy when editing other properties.

### To Reproduce

Create a property on a custom asset type with a `ConditionalVisibilityAttribute`, and make sure the condition fails and it is hidden.

Then start editing a string property, the UI will start flickering.

### Expected behavior

The UI does not start flickering.

### Media/Files

https://user-images.githubusercontent.com/13039986/184254724-7ed573ba-b43e-4a4c-b422-9a3f3ac92f4d.mp4

**Comment by robotboy655** [comment]
Cannot reproduce, assuming fixed?
