### ISSUE TITLE
Tiled Rendering degrades performance and renders lighting incorrectly

### ISSUE THREAD

**Issue by Redesaile** [sboxgame/issues#2190]
### Describe the bug

When Tiled Rendering is enabled, the lighting looks very weird, except for the dynamic Environment Light, and the FPS drops by 10x.

### To Reproduce

1. Launch S&box
2. Open console
3. Enter `r_tiled_rendering 1`

### Expected behavior

The illuminated area should break into a bunch of tiles, some of which can be normal, the second will not render lighting at all, and the third will be overexposed. On top of that, performance degrades by 10x, causing my 80 fps to become 6-8 fps.

## Media/Files

**<div align="center"><h3>Without Tiled Rendering</h3></div>**

![Menu](https://user-images.githubusercontent.com/90133781/185432196-f7054245-d9f6-44fe-b768-90fef5594613.png)
![Hammer](https://user-images.githubusercontent.com/90133781/186253775-9e457bc2-a9fb-4c50-9065-833eecb28e3d.png)

<div align="center"><h3>With Tiled Rendering</h3></div>

<div align="center">at the time of the report</div><br>

![Menu](https://user-images.githubusercontent.com/90133781/185432208-198e1895-d583-4fb0-bcc4-7d8607a9f39b.png)
![Hammer](https://user-images.githubusercontent.com/90133781/186253841-d8affd65-cf24-4fef-bf09-59f07c9c59f4.png)

<div align="center">5 days later</div><br>

![Menu 5 days later](https://user-images.githubusercontent.com/90133781/186250286-e40b5191-63b3-4f0e-81ce-8b73c8f1cd91.png)

### Additional context
**Device:** Laptop
**OS:** Windows 10 21H1
**Processor:** Intel(R) Core(TM) i7-3537U CPU @2.00GHz
**Memory:** 4 GB RAM
**Graphics:** Nvidia GeForce GT 720M

**Comment by karl-police** [comment]
I tried running s&box on some laptop.

![image](https://user-images.githubusercontent.com/12023782/187229757-0da63d3c-4e65-48a6-bc40-37834d9a4a39.png)


![image](https://user-images.githubusercontent.com/12023782/187229768-fcfffdfa-efc4-4e1d-b7f1-5b4010c5ae5f.png)


The laptop doesn't have a graphic card actually, just integrated graphics from Intel.

Intel Core i7-7500U
Intel HD Graphics 620

**Comment by Redesaile** [comment]
It seems to be fixed.

https://user-images.githubusercontent.com/90133781/198873969-b83739b3-19bd-4106-b779-b4aadef28cd0.mp4


https://user-images.githubusercontent.com/90133781/198873974-eb15b114-bb29-4f09-b279-2cabd59e2222.mp4

**Comment by samzanemesis** [comment]
Looks fine on Snapdragon, should be the same behaviour on Xe
