### ISSUE TITLE
Add between/fixed value types from the soundscape editor to the sound editor.

### ISSUE THREAD

**Issue by googleooer** [sboxgame/issues#2204]
### For?

S&Box, Other

### What can't you do?

See images:
The soundscape editor lets you choose between fixed values or ranged ("between") values. The sound editor doesn't.

![github1](https://user-images.githubusercontent.com/35429559/185802758-a555128f-24de-4ea5-a6b3-cc16cc2b5053.png)
![github2](https://user-images.githubusercontent.com/35429559/185802759-0a5d2737-8c49-47f5-ad7d-e1745686e9dc.png)

### How would you like it to work?

Have the fixed/between types for the "volume random" and "pitch random" variables in the sound editor instead of only the fixed type.

### What have you tried?

There's nothing I can try in this case

**Comment by robotboy655** [comment]
This was done.
