### ISSUE TITLE
Map can differ from host when a local map exists with the same name

### ISSUE THREAD

**Issue by JustPlayerDE** [sboxgame/issues#221]
**Describe the bug**

When you start a new game (either with "Create Game" or "Find Game) it will favour the local map vpk with the same name (e.g. `testing.vpk` on the host will let the player download `gkarts.testing` instead, if the client has `testing.vpk` in the local game but the server has `gkarts.testing` it will favour that `testing.vpk` for the client instead of `gkarts.testing`)

**To Reproduce**

Host:
1. Download the testing.zip i put in this issue and put the `testing.vpk` somewhere on your local game where it can be loaded from
2. select `gkarts.testing` when creating a new game
3. let the client join your game

Client:
1. Download the testing.zip i put in this issue and put the `testing.vpk` somewhere on your local game where it can be loaded from
2. Join a server with any map that has `xxx.testing` as name (in this case `gkarts.testing` could be used)

**Expected behavior**

The Client should download the current map from server if they have different versions.

**Screenshots**

https://files.justplayer.de/justin/a2bcd9ba725ee3987e349f556d9afbfc93505cfc.mp4
https://files.justplayer.de/justin/35b9c8ca89921c64eef06430a67ca613d97ccf04.mp4

**Context**

The test map called `testing.vpk` (can be tested with `gkarts.testing`): 
[testing.zip](https://github.com/Facepunch/sbox-issues/files/6511094/testing.zip)

**Comment by JustPlayerDE** [comment]
https://files.justplayer.de/justin/ba9130c0d5557a4c9b57d37a4656616de0dfc68c.mp4
just forgot to delete my local copy of construct.vpk and that happened lul

**Comment by KayaDLX** [comment]
Bumping this very old issue as this is still a thing, there's no verification whatsoever for the map vpk versions, your map can differ from the host.
