### ISSUE TITLE
Models and Lighting Break After Launching Gamemode

### ISSUE THREAD

**Issue by Fortune117** [sboxgame/issues#2211]
### Describe the bug

When working on my gamemode I noticed that every now and then all the lighting seemed to break and my player model would turn invsible. This extended to just about all the models in my gamemode. To fix it, I had to restart s&box.

I'm unsure what causes it but I believe Kaesar has found a reliable reproduction, here is a video:

https://user-images.githubusercontent.com/7847372/185970443-35f2895d-4969-48da-9f94-35bf30fbd5ca.mp4

### To Reproduce

1. Launch into a game of Ghosts of the Zone. You can press C to go third person.
2. Then launch into a game of sandbox.
3. Launch once more into Ghosts of the Zone. Your model should now be invisible.

### Expected behavior

Models don't disappear.

### Additional context

Adesi also ran into this with Speed Dial.

**Comment by DoctorGurke** [comment]
Does this happen if you just launch your game and restart it? 'restart' concmd for example

**Comment by Fortune117** [comment]
> Does this happen if you just launch your game and restart it? 'restart' concmd for example

Yep, just tested it.

**Comment by DoctorGurke** [comment]
Yea the same thing is observable with speed-dial, even the backend upload. It seems to break a few different things rendering wise. Cubemaps/lightprobes are broken map side as well and random scene objects seem to not draw at all, it's super ghastly

**Comment by yuberee** [comment]
This happens to xoxoxo as well.

- Characters T-Posing
- Random animations being played
- Lightmaps malfunctioning
- Entities are pitch black
- Entities not appearing

Sometimes it's just one of those, other times it's all. 
90% of the times it happened when restarting, I thought it might have something to do with compiling since it mostly happens on the local version.
I really tried to debug it by commenting out code until it stopped happening, but at that point it decided to randomly stop for a few restarts then happens again.

**Comment by handsomematt** [comment]
Are you creating entities in constructors by any chance?

**Comment by yuberee** [comment]
In Stud Jump's case, the only entity I create in the game's constructor is the level's geometry, but we've already tried setting it up after all map entities loaded and it would still happen.
As for XOXOXO, only thing I'm doing in the constructor is creating the HUD.
Both of them are getting a static property of the game's instance set though, but I've done it on basically every project so far.

**Comment by Fortune117** [comment]
haven't had this happen in months, gonna assume something fixed this

**Comment by yuberee** [comment]
Was fixing old games, and the problem persists. But it's much harder to encounter now, probably had it once every 100 restarts.

![image](https://user-images.githubusercontent.com/59583743/222981435-ba737d79-5e95-4e16-b5ff-d61185a5fb01.png)
