### ISSUE TITLE
InputButton - Add Arrow Keys

### ISSUE THREAD

**Issue by Nickishero** [sboxgame/issues#2218]
### For?

S&Box

### What can't you do?

I am unable to access the Arrow Keys as inputbuttons in my game.
I want to use it as a feature to navigate in the UI, without restricting the player from doing other things.

Of course, I could make it interactable with mousebuttons or WASD. But that would take away a part of the players experience.

I would like to make something thats somewhat immersive, being able to navigate with a phone viewmodel with a worldpanel on it for instance, I'd still want my player to be able to walk around, The arrowkeys are amazing for this.

### How would you like it to work?

To be honest, this feature request for more inputbuttons (arrowkeys) are part of a bigger problem.

I've seen multiple discussions about the (lack of) InputButtons in the discord, and while I understand that games shouldnt be ran on entirely the keyboards, it is just something that differs per game.

Perhaps allow games to implement their own "InputButton" system. Perhaps even with a notification such as: "This game is using a modified keybind system. The default keybinds of this game are set, overriding the default S&box, user configured ones. You can access this game its keybind system and modify its keys *here*".

### What have you tried?

With the current system, in my opinion, more mature games will likely use the inventory buttons as a substitution. Likely the latter inventory-buttons, 7,8,9,0; While prompting the user in-game on join to rebind these keys to "arrow-left, H, P and arrow-right" for example.

I feel like this will happen, because a lot of games would not need 10 slots just for inventory/weapon control. However, they do require other keys.

It just decreases the end-user's experience in my opinion. Having to rebind keys each time you play a different game, I think that's whats going to happen if the current system will stay.

**Comment by DevulTj** [comment]
I'm not a fan of having these as specific InputButtons, personally. 

There's definitely a think required about how we proceed with the Input system, looking at other games, they're doing inputs in a pretty great way. You'd define an action, say Shoot, Reload, etc - and normally there's two keys defined for it, one for Keyboard & Mouse, one for Controller. They're separated. You can also define a secondary key for any action on the same input device. Say a shortcut on the mouse for throwing a grenade in a shooter game.

![image](https://user-images.githubusercontent.com/22372616/191032098-f732d42a-f1f4-4f2a-ae87-559cff32c460.png)

It's definitely something we've got on our minds for the future.

**Comment by handsomematt** [comment]
Input actions
