### ISSUE TITLE
snd_event_point doesn't work in-game until the sound has been manually played in the asset browser

### ISSUE THREAD

**Issue by gvarados1** [sboxgame/issues#2222]
### Describe the bug

snd_event_point does not play a sound until you manually play the sound in the asset browser first then restart the map. I've only tested this in dev mode. I don't know if this happens for published maps.

### To Reproduce

1. Have a snd_event_point in your map
2. Restart s&box or make sure you haven't listened to the sound in-game yet
3. Load the map and try to play the snd_event_point
4. You won't hear anything

How to fix:
1. Manually play the sound file in the asset browser
![image](https://user-images.githubusercontent.com/39461072/186602634-0ef1ff18-01b4-4a2a-b7f8-61a4dfb06111.png)
2. Restart the map, you will now hear the sound in-game.

### Expected behavior

snd_event_point should work as expected without having to manually play it from the asset browser every time you launch s&box.

**Comment by gvarados1** [comment]
This same issue happens in modeldoc when previewing animation sound events

**Comment by Gmod4phun** [comment]
Had a similiar issue about a month ago, doing a hard recompile on the sound fixed it, you could try doing that.

**Comment by PixelQubed** [comment]
For some reason, if you have two addons, they won't get called if they are not in the one that has included code in it. It's weird. So If you have an asset addon and a code addon separate, the sounds in the asset addon won't get called when loading into the game where as the sounds in the code addon get called when loading into the game. It's weird.

**Comment by handsomematt** [comment]
Should be fixed now, you'll need to re-select your sounds unfortunately to get the full path.
