### ISSUE TITLE
Hammer Triggers - Excluded Tags

### ISSUE THREAD

**Issue by gvarados1** [sboxgame/issues#2223]
### For?

Hammer

### What can't you do?

We can't exclude tags from triggers. For example, if we had a trigger that we wanted to affect everything EXCEPT players, that wouldn't be possible.

### How would you like it to work?

We should be able to add Excluded Tags to triggers in hammer. If an entity has any of these tags, they will not trigger the trigger.
![image](https://user-images.githubusercontent.com/39461072/186603990-c2735cff-afb4-40a6-b2fc-3caf5876bef2.png)

### What have you tried?

There is no workaround

**Comment by garrynewman** [comment]
Things to think about here is what would happen if they have tags in both, which takes priority - ignore or activation?

**Comment by Fortune117** [comment]
The rule of thumb I've always used is 'can overrides cant'

**Comment by gvarados1** [comment]
If the entity has any of the excluded tags it gets ignored

**Comment by gvarados1** [comment]
This could be an option but I think 96% of cases will want to ignore everything with the tag.

**Comment by urnotnick** [comment]
I think it’d be a nice feature to have the ability to select how it handles tags in both
