### ISSUE TITLE
Making a Material with the Blendable shader using 4 layers will crashe the game

### ISSUE THREAD

**Issue by codecakegit** [sboxgame/issues#2239]
### Describe the bug

When I open my map that contains a Material file that is using the Blendable shader, any .vmat that contains x4 layers will crash the game when attempting to open the map **or** when attempting to create a material like this in material editor. Removing these files will prevent the crash. I tried a fresh s&box install with no addons, and trying to make this kind of material file will crash the game.

Spent 2 weeks hunting this issue down so I could continue dev, hope it helps <3

### To Reproduce

1. Make new Material File
2. Set shader to Blendable
3. Set layers to x4
4. Save material
5. Game should crash

### Expected behavior

No problems with loading material files with the Blendable shader that use x3 layers, But x4 layers and attempting to save the material file or open the file will crash every time.

### Media/Files

[https://imgur.com/a/aymYSRh](url)

### Additional context

I'm Running windows 10 64-bit

- **CPU** AMD Ryzen 7 3800X 8-Core Processor 3.9Ghz
- **GPU** NVIDIA GeForce GTX 750 Ti
- **RAM** 32gb
- **MOBO** X570 AORUS ULTRA

**Comment by samzanemesis** [comment]
Looks more to be a GPU problem due to register pressure, are you on latest drivers?

I'll look more into it regardless, there are some things to alleviate sampler pressure

**Comment by codecakegit** [comment]
I had one of the staff members **Ognik** test this method and they also had their game crash, not sure what GPU they have.

**Comment by codecakegit** [comment]
My GPU's are updated as far as they can be, I also tried this with my GTX 1080 Ti and same issue, I have 2 gpus cause I like to monitor what lags my map on an average consumer gpu.

**Comment by ogniK5377** [comment]
Should be fixed next update 👍

**Comment by codecakegit** [comment]
Fixed :) Thank you all so much <3
