### ISSUE TITLE
Allow dedicated servers to use the `BaseFileSystem` during Shutdown

### ISSUE THREAD

**Issue by matekdev** [sboxgame/issues#2259]
EDIT: Here is the updated issue https://github.com/Facepunch/sbox-issues/issues/2259#issuecomment-1264711215

### For?

S&Box

### What can't you do?

I'm unable to write and read files via the [`BaseFileSystem`](https://wiki.facepunch.com/sbox/FileSystem) API on a dedicated server.

### How would you like it to work?

Exactly the way as when you locally host a game. 

### What have you tried?

Launching up a dedicated server, attempting to use the [`BaseFileSystem`](https://wiki.facepunch.com/sbox/FileSystem) to read and write some local files.

### Additional context

I'm assuming this doesn't work because by default sbox saves all of these files to a `/data/<org>/<game>` folder by default. Whereas a dedicated server can be hosted from any folder?

**Comment by handsomematt** [comment]
are you saying `FileSystem.Data` doesn't work on dedicated servers?

**Comment by mzegar** [comment]
Yes, I didn't know if this was intended or a bug.

**Comment by DevulTj** [comment]
Can you show the code you're using for this? I'm doing this locally without issue:

```csharp
FileSystem.Data.CreateDirectory( "data_folder" );
FileSystem.Data.WriteAllText( "data_folder/testing.txt", "hi this is some text" );

FileSystem.OrganizationData.CreateDirectory( "organization_folder" );
FileSystem.OrganizationData.WriteAllText( "organization_folder/testing.txt", "hi this is some organization specific text" );```
```

![image](https://user-images.githubusercontent.com/22372616/192572412-3612b8ff-2349-4bed-baee-81d1fe731cf6.png)
![image](https://user-images.githubusercontent.com/22372616/192572438-5a0440fb-25fd-4075-bdb4-2f753ff9ae73.png)

**Comment by matekdev** [comment]
My bad I was writing during `Shutdown` which seems to fail to write. I should have tested it somewhere else.

**Comment by DevulTj** [comment]
I think that's a problem, so I'll reopen and set the title to reflect this.

**Comment by matekdev** [comment]
Sure, here is what I was experiencing...

1. In the game `Shutdown()` override write some code that writes to the filesystem
```
FileSystem.Data.CreateDirectory( "data_folder" );
FileSystem.Data.WriteAllText( "data_folder/testing.txt", "hi this is some text" );
```
2. Close the dedicated server via the `X` button at the top right of the window
3. Notice that nothing gets written to the file system

If you type in `quit` in the dedicated server console, everything gets written properly.

**Comment by matekdev** [comment]
no longer relevant
