### ISSUE TITLE
Specify Clipping Planes for a SceneObject

### ISSUE THREAD

**Issue by Gmod4phun** [sboxgame/issues#2260]
### For?

S&Box

### What can't you do?

Can't use a clipping plane to visually clip a SceneObject.

### How would you like it to work?

I would like it to work by specifying a clip plane and enabling/disabling the use of that plane on a per object basis. Pretty much how GMod's entity clip planes worked: https://wiki.facepunch.com/gmod/Entity:SetRenderClipPlane and https://wiki.facepunch.com/gmod/Entity:SetRenderClipPlaneEnabled

So probably something like `SceneObject.ClipPlane` and `SceneObject.ClipPlaneEnabled` would be a nice solution.

The possibility of having multiple clipping planes on a single SceneObject would be nice, too, but a single one would still be good enough.

### What have you tried?

Tried setting the render attributes, just like `ScenePortal.SetClipPlane` does it.

Here is an example of a simple box that should have a half of it visually clipped.
```
public partial class TestBox : Prop
{
	public override void Spawn()
	{
		base.Spawn();
		SetModel( "models/citizen_props/crate01.vmdl" );
		SetupPhysicsFromModel( PhysicsMotionType.Static );
	}

	[Event.Frame]
	public void Frame()
	{
		var plane = new Plane( WorldSpaceBounds.Center, Rotation.Up );
		SceneObject.Attributes.Set( "EnableClipPlane", true );
		SceneObject.Attributes.Set( "ClipPlane0", new Vector4( plane.Normal, plane.Distance ) );
	}
}

```

**Comment by mahalis** [comment]
This would be really nice to have. I assume it would make the shader permutation situation a little worse, but given the variety of things it would be useful for (I’ll admit, portals are one of the big ones, but spawn / despawn effects would benefit too) I think it’d be worth it.

**Comment by Gmod4phun** [comment]
UPDATE: Turns out it is possible to enable the Clip Plane using `Attributes.SetCombo( "D_ENABLE_USER_CLIP_PLANE", true );`

Good job MuffinTastic for figuring this out.

I still think there should be a more straightforward way of doing this, such as the above proposed methods. Also the clipped models don't seem to be behaving correctly at all times, but that is a topic for another issue.

**Comment by xezno** [comment]
I've added these under nicer properties, `SceneObject.ClipPlane` and `SceneObject.ClipPlaneEnabled`, let me know if there's any problems with these.

**Comment by mahalis** [comment]
Outstanding, thank you!

**Comment by Gmod4phun** [comment]
Works very nicely, thank you. The only issue is that the getters are not public, which is probably just an oversight, I believe those should be public so we can know if a sceneobject has an active clip plane, and what that plane is.

Regarding their functionality, I noticed they were probably silently changed to be relative to the active camera (I think this happened several months ago). Setting the position of the plane to a specific point requires to specify it as (point - Camera.Position) (basically just subtract the camera position from the real worldspace coords of the plane) in order to work as it did before. I am not sure if changing it back to the old behaviour will break some things, if yes, then it would probably be a good idea to make it known that the planes are now relative to the active camera position.

**Comment by xezno** [comment]
Will take a look

**Comment by xezno** [comment]
Should have getters on next build, lmk if there's anything else

**Comment by Gmod4phun** [comment]
Getters are working now, thanks for the additions.

The only other thing that comes to mind is, how many planes are supported by default? I seem to remember from somewhere 4 planes (planes 0-3), and if so, maybe expose those to the API too. I am not sure if there are such planes, and if they even work correctly.

**Comment by Redhacker1** [comment]
@Gmod4phun I am pretty sure that depends on the shader.

**Comment by Gmod4phun** [comment]
I believe these are either shader agnostic or a part of the base shader or something (I'm not a shader guy), but the current clip plane system seems to work with all shaders.
