### ISSUE TITLE
TypeLibrary: Let us override engine entities like prop_physics and ent_door

### ISSUE THREAD

**Issue by LeQuackers** [sboxgame/issues#2267]
### What it is?

Most of the time overriding base classes and using a different LibraryAttribute name works; however, if an addon needs to actually replace something from TypeLibrary like prop_physics, ent_door, divs, etc. there currently isn't a good solution to do so.

### What should it be?

I would advocate giving LibraryAttribute names from the currently active addon priority over LibraryAttribute names from the base that already exist.

At a glance, adding an extra check to the query in ```internal TypeDescription TypeLibrary.GetTypeByName(string, Type)``` should work.

**Comment by Redhacker1** [comment]
I don't think that replacing stuff under the same name is a good idea conceptually, to me even if it does work it seems like a recipe for confusion and disaster later down the line.

**Comment by LeQuackers** [comment]
If multiple addons were active at once, then I would agree with you; however, to my knowledge there weren't any plans to support "code addons for gamemode addons" and instead would be forks of the original gamemode addon, so there should only ever be one active gamemode addon at a time.

**Comment by Redhacker1** [comment]
A: toybox addons will be a thing. B: Overriding Sbox internal entities and types, in general, is a pretty shit idea. You make things more confusing for yourself, you fuck over maps that use those entities and expect the default behaviors, you potentially screw with the engine's ability to distinguish between the two.

**Comment by LeQuackers** [comment]
For context, I'm making a gamemode addon that (should be) compatible with simple maps; however, my gamemode uses custom systems for damage, collision, etc. that aren't compatible with entities from the base, like prop_physics, ent_door, func_physbox, and so on. Replacing the entities at runtime with my_prop_physics, my_ent_door, etc. sounds like it would work on paper, but in practice it breaks all the map logic because the Output properties on the base entities are all protected.

**Comment by garrynewman** [comment]
I think the fundamental problem of "I can't override prop_physics" is a legit one.. so we'll treat this as a request for that kind of stuff.
