### ISSUE TITLE
Asset Browser - File path breaks when path contains spaces

### ISSUE THREAD

**Issue by KayaDLX** [sboxgame/issues#2268]
### Describe the bug

When you have an addon path looking like this `"c:/program files (x86)/steam/steamapps/common/sbox/addons/tf-source-2/"`, the new asset browser will break if you try to add any search filter.

### To Reproduce

1. Select any of your addon in the asset browser that has a path with spaces
2. Try to filter by any asset type
3. See how it breaks and fails to filter anything

### Expected behavior

It should correctly resolve the path. A workaround I found is to add back `"` around the addon path to make the search filters work again.

### Media/Files

![image](https://user-images.githubusercontent.com/67245359/188266531-d33f35db-f973-4251-99e0-6893bde0e72b.png)
![image](https://user-images.githubusercontent.com/67245359/188266557-53de96dc-c44e-43b9-8d49-ecbd8ca88ff3.png)

**Comment by xezno** [comment]
This is still a problem, but now that paths aren't part of the search bar (they get separated out) this is harder to fix manually.

https://user-images.githubusercontent.com/12881812/204604959-c8e2a7f5-028c-4e97-ab05-fbfb30694619.mp4

**Comment by robotboy655** [comment]
That issue should now also be fixed.

**Comment by magnusm1908** [comment]
OMG Thank you Rubat finally!!
I can confirm it has been fixed.

> That issue should now also be fixed.
