### ISSUE TITLE
Call Entity methods after its constructor (Spawn for example)

### ISSUE THREAD

**Issue by peter-r-g** [sboxgame/issues#2282]
### What it is?

Currently, `Entity.Spawn` (and maybe other methods) is called before the construction of an Entity has finished. This creates the problem of not having all the data needed for the Entity before methods are invoked on it like Spawn. For example, if someone wants to pass some information to an entity's constructor and then use it in Spawn they won't be able to as the constructor won't be invoked before Spawn has been invoked.

Below I'll leave an example of one of my use cases.
```cs
protected virtual string WeaponName => AssetDefinition.WeaponName;
protected virtual string ModelPath => AssetDefinition.Model;

[Net]
protected WeaponAsset AssetDefinition { get; set; }

public GrubWeapon( WeaponAsset assetDefinition )
{
    Log.Info( "Constructor" );
    AssetDefinition = assetDefinition;
}

public override void Spawn()
{
   Log.Info( "Spawn" );
   base.Spawn();

   Name = WeaponName;
   SetModel( ModelPath );
}
```
Will produce:
![image](https://user-images.githubusercontent.com/11802285/188508379-35f3d50b-f6c8-4ea1-8109-b4c1225c9c55.png)
With the error being:
![image](https://user-images.githubusercontent.com/11802285/188508453-a45d74ac-0459-4d26-a34b-472713608757.png)

### What should it be?

Methods on classes should be invoked after a class has been constructed. Not before or during.

**Comment by Redhacker1** [comment]
This has already IIRC been asked a few times on the discord, I think they have cited both networking and other technical issues as to why this cannot be done.

**Comment by garrynewman** [comment]
There are issues with passing in parameters to the constructor. The main one being that the networking system has to create a clientside version of that entity - and it won't be able to do that if there are constructors.. so generally it's not a good idea.

I do feel your pain here though.. it's not totally satisfying for me either. You really want to create an entity, set its properties and then spawn it. Manually calling spawn to actually create the entity is the way we should go?

**Comment by Ephememory** [comment]
> Manually calling spawn to actually create the entity is the way we should go?

To me, it's more intuitive that this is the case. It's how I assumed it worked before I realized that the constructor actually calls Spawn anyway under the hood.

If this is what you are proposing:
```cs
var ent = new MyEnt();

// Set custom properties of the entity's class.
ent.CustomField = 42;

// Set general Entity base class properties.
ent.Owner = Client;
ent.Position = Vector3.Zero;
ent.Rotation = Rotation.FromYaw(90);

ent.Spawn(); // Actually spawn the entity in the world.
```
Then, I personally would agree with that being how it should work.

**Comment by anthonysharpy** [comment]
Sorry for being nosey but would it not be possible for the object to be instantiated on the client using the constructor with parameters as opposed to the parameterless one? The server could send the parameters and the constructor information to the client and the client could instantiate the object with this information using reflection (or maybe, using code generation, a switch statement that chooses between constructors) or something like that. I don't really know much about how it works under the hood so I may just not be realising something.

I think there are drawbacks to calling Spawn separately. For example, it could lead to a lot of boilerplate:

```
cat1 = new Cat();
cat1.Position = new Vector3(0, 0, 0);
cat1.Name = "Fred";
cat1.Age = 7;
cat1.Spawn();
cat2 = new Cat();
cat2.Position = new Vector3(100, 0, 0);
cat2.Name = "Stan";
cat2.Age = 5;
cat2.Spawn();
cat3 = new Cat();
cat3.Position = new Vector3(200, 0, 0);
cat3.Name = "Carl";
cat3.Age = 11;
cat1.Spawn();
```

Versus

```
new Cat(new Vector3(0, 0, 0), "Fred", 7);
new Cat(new Vector3(100, 0, 0), "Stan", 7);
new Cat(new Vector3(200, 0, 0), "Carl", 7);
```

One way around this could be to add a "setup" function to the class, but that seems a bit hacky since really that is supposed to be the purpose of the constructor. Even still it does technically double the number of lines of code needed to spawn the entity.

I can see how having more control over when the entity is spawned could sometimes be useful but personally what I would say to that is don't instantiate the class until you actually want to spawn it.

**Comment by Gmod4phun** [comment]
Isn't there already a way to do this? Setting the properties while spawning the entity, for example:

```
var ent = new Prop
{
	Position = tr.EndPosition + Vector3.Down * model.PhysicsBounds.Mins.z,
	Rotation = modelRotation,
	Model = model
};
```

**Comment by Redhacker1** [comment]
@Gmod4phun that is not really doing it in the constructor, that is equivalently
```
var ent = new Prop()
ent.Position = tr.EndPosition + Vector3.Down * model.PhysicsBounds.Mins.z,
ent.Rotation = modelRotation,
ent.Model = model
```

**Comment by Gmod4phun** [comment]
I have to admit the current Spawn method is a bit wonky. If the system will stay like it is, with Spawn being called before the constructors, there would probably be a benefit from having a `PostSpawn` method that will be called after the constructors have run their shit. For example, things like the entity's Position/Rotation are not returning the proper values inside of Spawn so if you need to do something with those values (proper values) rightaway you currently need to do it in another method that gets called after a small delay, and I guess alot more things suffer from this.

Unless I'm missing something, having a sort of `PostSpawn` method could be a workaround for these issues, but it would probably confuse developers alot, having both Spawn and PostSpawn, with some things working fine inside of Spawn whereas other stuff would need to be done in PostSpawn.

**Comment by anthonysharpy** [comment]
Actually had this issue today on my Pistol weapon class. My constructor was setting the model name, and Spawn() was calling SetModel() with the model name. But sometimes the constructor was being called before Spawn() and sometimes it wasn't, causing it to try to set an empty model in some cases.

If the pistol was a map entity, the constructor was correctly called first. If I created the Pistol programmatically (via reflection in this case), Spawn() was called first.

```
var type = GlobalGameNamespace.TypeLibrary.GetDescription( className )?.TargetType;
var entity = GlobalGameNamespace.TypeLibrary.Create<ModelEntity>( type );
```

![image](https://user-images.githubusercontent.com/55365296/195946896-eb6d53fa-6692-4066-972d-9c80befbee90.png)

**Comment by peter-r-g** [comment]
No longer relevant
