### ISSUE TITLE
Categorization of game settings

### ISSUE THREAD

**Issue by peter-r-g** [sboxgame/issues#2289]
### For?

S&Box

### What can't you do?

Currently, all game settings are in a long list with no formatting or categorization for related settings.

### How would you like it to work?

Add a `Category` input to each game setting. Settings with the same category will be put under a single drop-down menu. Settings with no category can just display at the top with no drop-down.

### What have you tried?

Nothing, as far as I know, there is no way to get this kind of functionality without implementing the whole system yourself in the menu and editor.

**Comment by DevulTj** [comment]
This is something we'll most probably do when redesigning the main UI.

**Comment by peter-r-g** [comment]
Closing as this is now sorted by game menus
