### ISSUE TITLE
Local map selector along side the gamemode launch config selector

### ISSUE THREAD

**Issue by Xenthio** [sboxgame/issues#2292]
### For?

S&Box

### What can't you do?

It would be nice to be able to switch between local maps in a launch config with a seperate dropdown so that we can keep the amount of launch configs down, this is annoying if you switch between test maps quickly and frequently

### How would you like it to work?

![image](https://user-images.githubusercontent.com/28588188/188996360-1e18fbaf-a87b-4cca-af26-2d6dc18cadbb.png)
something like this would be nice

### What have you tried?

i've tried selecting a gamemode config and using the addon manager to launch a map but the gamemode doesn't actually change until you click the launch config play button meaning i get plopped into the sandbox gamemode

**Comment by Xenthio** [comment]
> I did think of this myself.. I does feel like it makes sense to have it like this. Lets mull this over for a while.

I think that atl east the gamemode selector should change the gamemode convar on selection so that people don't have to type in `gamemode blahblahblah.blahblah` everytime they want to run their map in a gamemode
![image](https://user-images.githubusercontent.com/28588188/191378041-10746be6-9886-4bce-b152-852c266ae22b.png)

**Comment by JustTab** [comment]
i agree this should be added so I don't have to go to hammer every time to launch a custom map
