### ISSUE TITLE
Sbox-dev - Fullscreen is "randomly" bugged

### ISSUE THREAD

**Issue by KaesarZZ** [sboxgame/issues#2294]
### Describe the bug

For several weeks I've been running into a annoying bug with the fullscreen mode, causing it to not work properly.

I can't find a way to reproduce it, seems totally random to me. Just opening sbox-dev and happens, but maybe by reporting it We will find a solution.

### To Reproduce

https://user-images.githubusercontent.com/40291120/189100587-8c73daad-935f-49df-9d6f-ecaf5202abf5.mp4

### Expected behavior

Should work properly as before.

**Comment by anthonysharpy** [comment]
I was getting something the same or similar to this the other day - it was enabled as full screen but it wouldn't actually show up as full screen until you clicked on the game window. Can't reproduce it now though so it's a bit temperamental perhaps.

**Comment by garrynewman** [comment]
I've run into this, and yeah it's annoying af. I'll see what I can do..

**Comment by garrynewman** [comment]
I checked around the code and couldn't find anything obvious.. but I have cleaned it up a bit. Let me know if it still happens..

**Comment by KaesarZZ** [comment]
This is fixed.
