### ISSUE TITLE
Soundscape Volume Entity

### ISSUE THREAD

**Issue by gvarados1** [sboxgame/issues#2305]
### For?

Hammer

### What can't you do?

We can't make volume soundscape entities, only radius

### How would you like it to work?

We should be able to make soundscape volume entities. I'm fine with either having trigger style mesh volumes or box volumes like light probes. We should probably be able to make any type.

example of mesh volume style soundscape
![image](https://user-images.githubusercontent.com/39461072/189502236-ab2d5ab2-4c9e-4920-ade6-19f7a769ead2.png)

example of box volume style soundscape
![image](https://user-images.githubusercontent.com/39461072/189502160-5524d47a-575b-49fa-87b2-0f1986072329.png)

### What have you tried?

Currently we only have soundscape radius which is pretty annoying to work, especially because the default radius is massive and we can't adjust the helper in the 3d view.

![image](https://user-images.githubusercontent.com/39461072/189502143-fc16c47c-b5de-48c8-9846-f0d2e2951a6c.png)

### Additional context

It would also be nice to have a combined entity with `env_combined_light_probe_volume`
Most soundscape with overlap exactly with light probes so `env_combined_light_probe_soundscape_volume` makes sense
![image](https://user-images.githubusercontent.com/39461072/189502340-09ad3637-f2a2-4490-bb9d-8e6fbbf29cda.png)

**Comment by KingOfTheFBI** [comment]
Late but yeah I have a lot of use cases for this already. Would be a game changer

**Comment by robotboy655** [comment]
After seeing things like this:
![image](https://user-images.githubusercontent.com/3299036/199085406-94d514e4-eca6-475a-8179-8460507cb891.png)

I decided this should be added sooner.
