### ISSUE TITLE
Missing D3D renderings

### ISSUE THREAD

**Issue by CerealYe** [sboxgame/issues#2307]
### Describe the bug

Yesterday, I launched S&Box I haven't played since September 1. (This isn't my first time doing this), and I see the 3D renderings suddenly become missing textures. I have no idea how it happened.

The error message said:
"C:\buildbot\work\sbox\sbox\src\rendersystem\dx\dxfunctions.h (118) : Assertion Failed in function _DOD3D(): false D3D call for D3D11Device()->CreateTexture2D( &desc, bImmutable ? pSubResource : NULL, ( ID3D11Texture2D ** ) &pDx11Texture ) failed with 0x80070057, logging minidump"

### To Reproduce

1. Launch S&box
2. See the missing 3D Renderings
3. See Errors

### Expected behavior

The 3D renderings should be working seen as well and not missing textures.

### Media/Files

Home Menu:

![image](https://user-images.githubusercontent.com/59343254/189520812-3ce6c6d3-45cf-41e5-861c-8658678fef96.png)

Character Customization:

![image](https://user-images.githubusercontent.com/59343254/189520822-ff906643-577e-48b6-aacd-77a9d21074e8.png)

Render Scene Test:

![image](https://user-images.githubusercontent.com/59343254/189520924-13a4b02f-804f-45c6-a005-660d6e8f6807.png)

### Additional context

I'm running on Windows 10, and my PC specs are:

CPU: Intel Pentium(R) Dual-Core CPU E6700
GPU: AMD Radeon R5 200 Series

(I know, my PC is shit. It barely runs almost any S&box Gamemodes at around 15-20+ framerates at 1280x720 with the lowest in-game resolution scale and using my own config. It lags so much playing the Sandbox game mode on S&box at 5-10 framerates because of the blur UI thing, it causes lag and I don't know how to disable this)

**Comment by garrynewman** [comment]
This is my bad, I'll fix it

**Comment by CerealYe** [comment]
> 

That's alright, thanks!

**Comment by garrynewman** [comment]
Hey can you take another look at this please and let me know if it's fixed?
