### ISSUE TITLE
RT Baked Lighting doesn't use tonemapping

### ISSUE THREAD

**Issue by GunnarKafel** [sboxgame/issues#2321]
### Describe the bug

In Hammer, the exposure in RT Baked Lighting doesn't match my overridden tonemap scale. It seems to be locked at the default exposure.

In both images the tonemap scale is overridden to 5:
![image](https://user-images.githubusercontent.com/65134886/190286262-74f542fa-7835-4c5f-8115-738240cb2e9e.png)
![image](https://user-images.githubusercontent.com/65134886/190285284-aa9e603a-d710-4353-82f1-7a458d43cd59.png)
![image](https://user-images.githubusercontent.com/65134886/190285386-98e5d0ea-6db0-4436-a112-c7d8b94235bd.png)

When I set the tonemap scale to 1, it closely resembles RT Baked Lighting.
![image](https://user-images.githubusercontent.com/65134886/190285709-06425d87-7730-4388-80f6-90c2f40ea675.png)

### To Reproduce

1. Override the tonemap scale in Hammer to a high value
2. Switch to RT Baked Lighting
3. The exposure will not match the tonemap scale

### Expected behavior

The exposure of the baked lighting preview should match the exposure in All Lighting.

**Comment by gvarados1** [comment]
This is a huge one for me. I always thought RT Baked was busted because the preview never looks anything like it does in-game.

**Comment by bakscratch** [comment]
This is how it should act.
https://user-images.githubusercontent.com/8184184/193582572-b071234c-2609-49a4-83e3-b3a9a80e4609.mp4

**Comment by GunnarKafel** [comment]
This works swimmingly ty!
