### ISSUE TITLE
Allow changing gamemode programmatically

### ISSUE THREAD

**Issue by lotuspar** [sboxgame/issues#2325]
### For?

S&Box

### What can't you do?

Switch gamemodes from an active gamemode

This was discussed on the Discord recently and previously (very briefly) in [#999](https://github.com/Facepunch/sbox-issues/issues/999)
Gamemode switching can be very useful for some projects, and while it (of course) can be used in ways that are less-than-ideal, I feel like even a new developer can understand the ways it can go wrong (and even then misuse of it only results in MAYBE a confusing codebase at worst)

### How would you like it to work?

Allow gamemode switching similar to `Global.ChangeLevel()`

### What have you tried?

Using ConsoleSystem

**Comment by DevulTj** [comment]
Ideally, you'd make a game that abstracts the game loop - letting you control what the game type is and what that game type does ([see Spire's gamemode system](https://github.com/Facepunch/sbox-spire/blob/main/code/Gamemodes))

Only thing I can think of to advocate for this feature would be partitioning your game content - instead of one big monolithic blob, you're only loading the content you'd actually need.. **however** it might be better to download it all at once instead of having a big wait time when switching gamemode.

**Comment by DevulTj** [comment]
Though, if you or other members of the community can come up with a more solid use case for this, we'd be happy to implement this feature.

**Comment by peter-r-g** [comment]
> Though, if you or other members of the community can come up with a really solid use case for this, we'd be happy to implement this feature.

For Grubs I'm thinking of doing a separate terrain making game and with that it would be nice to implement a play button where you can go to the main Grubs gamemode and start playing with the terrain you just made. Once you're done you can click another button and go back to the terrain maker.

**Comment by robotboy655** [comment]
One use case I can think of for this is a Fretta type thing/servers with very different gamemodes that wouldn't make sense to have all in a single gamemode.

**Comment by Fortune117** [comment]
I'd been thinking of setting up a gamemode that was like a base-building system that was effectively singleplayer, and it'd then connect back into a multiplayer gamemode. Kind of like having your own tarkov labs/hideout.

It'd also let different gamemodes set up their own matchmaking system/official server hubs, kinda like gmod Tower used to.

**Comment by SleepyMode** [comment]
> I'd been thinking of setting up a gamemode that was like a base-building system that was effectively singleplayer, and it'd then connect back into a multiplayer gamemode. Kind of like having your own tarkov labs/hideout.
> 
> It'd also let different gamemodes set up their own matchmaking system/official server hubs, kinda like gmod Tower used to.

I feel like a gamemode-changing system is not appropriately describing what you're looking for here.
You're looking for a more server-changing option, to transition players between servers (kind of like how in Garry's Mod we'd run the `connect` command on clients to connect them to a different server). Perhaps a new issue would be best for this.
