### ISSUE TITLE
LPV Debug probes not showing up correctly 

### ISSUE THREAD

**Issue by QuackCocaine** [sboxgame/issues#2326]
### Describe the bug

When I enable lpv debugging the imposters should be plain spheres and or squares but instead, they are just a circular greyscale missing texture.

### To Reproduce

1. Go into any compiled map with Light Probe Volumes and set `r_light_probe_volume_debug_grid` to `1`
2. Observe that instead of spheres or cubes you should be getting missing texture spheres in their place.

### Expected behavior

What they should look like when setting `r_light_probe_volume_debug_grid` to `1`

![sbox_s5gZzx9AMW](https://user-images.githubusercontent.com/23345567/190643527-d2a78566-f5b4-4336-85e3-3b2fb9ba2f8f.png)

### Media/Files

What LPV Debugging looks like currently :

![sbox-dev_t8dUaZxXhv](https://user-images.githubusercontent.com/23345567/190643671-7042cff7-204d-4e2a-b6ad-a3347dd883e9.png)

**Comment by ogniK5377** [comment]
Is this still happening on the latest update which was just pushed? if so, is there anything in the console?

**Comment by QuackCocaine** [comment]
upon enabling lpv depug the console will get spammed with the following bellow . : 
`2022/09/17 05:06:14.950	RenderSystem	Texture manager doesn't know about texture "materials/default/default_normal_tga_36476129.generated.vtex" - returning error texture in CTextureManagerDx11::GetResourceView`	
and 
`2022/09/17 05:06:14.950	RenderSystem	Texture manager doesn't know about texture "materials/default/default_rough_tga_8918b8fc.generated.vtex" - returning error texture in CTextureManagerDx11::GetResourceView`	

![sbox-dev_YgUjeYzFpT](https://user-images.githubusercontent.com/23345567/190849163-5e4db290-a86d-4fb1-bf49-ab65551af1e8.png)

**Comment by QuackCocaine** [comment]
do note it sometimes spits out the above when I just load into a map and sometimes when I toggle lpv debugging

**Comment by Gmod4phun** [comment]
This is still a problem 
![image](https://user-images.githubusercontent.com/5991682/228249414-d1f45b95-1187-48b0-8451-0bf212f79c21.png)

**Comment by trende2001** [comment]
seemed to have been fixed once, then it broke again
