### ISSUE TITLE
SCSS: Add Support for "mask-image" Property.

### ISSUE THREAD

**Issue by LeQuackers** [sboxgame/issues#2329]
### For?

S&Box

### What can't you do?

I can't fade out text near the edges of a transparent div (see Additional Context section for example).

### How would you like it to work?

As expected: mask-image should support images and gradients.

### What have you tried?

I've tried mix-blend-mode and the gradient overlay that fades to the div's background color trick, but both fail because the div is transparent.

### Additional context

Here's a JSFiddle showing what I'm trying to do: [https://jsfiddle.net/r5wL9acm](https://jsfiddle.net/r5wL9acm). Notice how the text fades out as it nears the edge of the div.

**Comment by xezno** [comment]
Hey, this should be in now:

https://github.com/sboxgame/issues/assets/12881812/f42c5ea9-0cd5-4832-ace3-6c9d6752019d

Let me know if there's any problems, feel free to close if this is fixed.

**Comment by LeQuackers** [comment]
Works like a charm; thanks.
