### ISSUE TITLE
Hammer - ToggleFullscreenLayout dosent work correctly on displays higher than 1920x1080

### ISSUE THREAD

**Issue by QuackCocaine** [sboxgame/issues#2331]
### Describe the bug

When in any of the available view modes aside from `Four-View Quad`  , pressing `shift`  + `alt` + `z` to toggle Fullscreen layout in hammer will result in the fullscreen layout being incorrect in some way.

For example.  `Single View` below instead of being one viewport appears to be split/duplicated between the other 3 even though it's set to `Single View`.

On my secondary 2560x1440 Monitor that I primarily use the s&box editor on :
![sbox-dev_ZfHoAkQZt8](https://user-images.githubusercontent.com/23345567/190890846-d8aedd63-27ec-4278-b9e8-48246e7c5fea.png)

### To Reproduce

1. Open up hammer and make sure the hammer is open on a display greater in resolution than 1920x1080. 
2. make sure your on a  view mode that isn't `Four-View Quad`
3. press `shift`  + `alt` + `z` to toggle Fullscreen layout.
4. Observe the issue.

### Expected behavior

For each view type/mode to work just fine as if hammer was on a 1920x1080 monitor.

`Single View`
On my main 1920x1080 Monitor :
![sbox-dev_UuLvq8MIVG](https://user-images.githubusercontent.com/23345567/190890967-9f2505d5-c42f-411d-ac67-92519f43a7a5.png)

### Additional Context 

Every view type aside from `Four-View Quad` will be messed up in some way when FullscreenLayout is toggled.

**Comment by handsomematt** [comment]
![image](https://user-images.githubusercontent.com/1388267/192821375-5423e330-4e27-48d2-b351-af4bcc50721f.png)

Can't seem to recreate on any view modes

**Comment by QuackCocaine** [comment]
hmm, I'll do some further testing on my end

**Comment by QuackCocaine** [comment]
Still getting the issue on my end, but I've narrowed it down to the windows display settings and what display is set to a main display

broken view modes 
![ApplicationFrameHost_sQ8frvJp6e](https://user-images.githubusercontent.com/23345567/192830077-8991eb97-a709-46c1-9bdb-8d1c710e408a.png)

No Broken Veiwmodes
![ApplicationFrameHost_d1TIsN31wp](https://user-images.githubusercontent.com/23345567/192830244-e28957de-92c2-4f25-80f8-d2fb9bc67a1d.png)

**Comment by handsomematt** [comment]
Ah I see the swapchain is limited by the main monitor, will have a think thanks.

**Comment by handsomematt** [comment]
Should be fine now, feel free to reopen if not.
