### ISSUE TITLE
Provide a way to disable dashed DebugOverlay lines on client

### ISSUE THREAD

**Issue by Phyksar** [sboxgame/issues#2337]
### What it is?

The current logic is just not convinient and making no sense, dashed lines decrease visibilty, especially when trying to draw custom shapes with these lines. Anyone should choose whenever they want to see dashed or solid lines despite of the client/server context. 

### What should it be?

void [Line](https://asset.party/api/Sandbox.Internal.Globals.DebugOverlay.Line(Vector3,Vector3,Color,float,bool))( [Vector3](https://asset.party/api/Vector3) start, [Vector3](https://asset.party/api/Vector3) end, [Color](https://asset.party/api/Color) color, float duration = 0, bool depthTest = True, bool dashed = False )

Or whatever you want it to look like.

**Comment by DoctorGurke** [comment]
This sounds a bit like you're trying to stretch the use for debugoverlay lines. I'd assume clientside lines are dashed to easily make the distinction when *debugging*. 
What are you trying to do?

**Comment by Phyksar** [comment]
To make it clear, I am struggling with some sort of a car physics framework. 
I have startes from drawing debug overlay fully with serverside context - at first that was ok as all values I wanted to track were computed by the server. But this led to an issue that, obviously, all that is drawn with server is updating at slower rate than is drawn to screen, which results in all lines and captions jumping around, making it impossible to read when the car is moving even at low speed. This made me switch to draw debug overlay at clientside. But there I have no control of what type of lines I want to draw. 

> I'd assume clientside lines are dashed to easily make the distinction when debugging.
There's no benefit from it, as long as you cannot override the hardcoded behaviour. As I said the dashed lines are harder to track. This wouldn't be so much of an issue if there was any other API that draw lines in 3D world with such simplicity as the debug overlay API.
