### ISSUE TITLE
Blendable Shader Renders Incorrectly in-game

### ISSUE THREAD

**Issue by gvarados1** [sboxgame/issues#2343]
### Describe the bug

The blendable shader looks wrong in-game. It's much darker than it should be. It used to render correctly but broke sometime after June I think.

### To Reproduce

Use a blend material somewhere on a map. The default materials & construct have this issue. It's very obvious here:
![image](https://user-images.githubusercontent.com/39461072/191398178-bf1bab57-9a93-4816-8971-20922ae2fcf9.png)

It looks good in hammer, and it used to look good in-game:
![image](https://user-images.githubusercontent.com/39461072/191398483-9744e856-da21-454d-a258-36e31d87eda9.png)

### Expected behavior

Blend materials should work as intended

### Media/Files

In-game the blend material floor is a different color from the debris pile
![image](https://user-images.githubusercontent.com/39461072/191397119-57119137-83c4-4cad-90ac-0ac8e0a143cb.png)

They are the same color in hammer
![image](https://user-images.githubusercontent.com/39461072/191397152-b8f584ec-0c43-445c-9207-f86d4d32cc3e.png)

This screenshot is from June. The shader worked then
![image](https://user-images.githubusercontent.com/39461072/191397279-6766580a-13b6-4bb3-856e-3f912001b8e0.png)

Here is another example from Metro
In-game:
![image](https://user-images.githubusercontent.com/39461072/191397676-5815c35c-3403-4f7f-a376-54288e42ca56.png)

Hammer:
![image](https://user-images.githubusercontent.com/39461072/191397689-daf5c022-f70c-48b6-8a9a-83bd21022e37.png)

Old screenshot:
![image](https://user-images.githubusercontent.com/39461072/191397714-ceb5b93b-21a9-46ba-b2c8-ac29e63536db.png)

Regular materials look good in-game. You can see (or rather, can't see) the transition here:
![image](https://user-images.githubusercontent.com/39461072/191397828-3b5c9ba4-e7b9-4404-9178-ce7562149c70.png)

**Comment by gvarados1** [comment]
You shouldn't need to recompile to test this, but here's a simple map and custom materials to showcase it
![image](https://user-images.githubusercontent.com/39461072/200998529-968e3e3f-ac3d-44f1-8ed9-2a3cf28f6b9d.png)
[materials.zip](https://github.com/sboxgame/issues/files/9977242/materials.zip)
[map.zip](https://github.com/sboxgame/issues/files/9977246/map.zip)

**Comment by samzanemesis** [comment]
should be gucci

**Comment by gvarados1** [comment]
perfect! thank you!!!!
