### ISSUE TITLE
Vertex color sometimes(?) gets removed from models with lightmap compiles

### ISSUE THREAD

**Issue by DeltaDesigns** [sboxgame/issues#2355]
### Describe the bug

It seems like models that use vertex color/blending materials have their vertex color removed when a maps lightmaps are compiled. Mesh created in hammer isn't affected though. Compiling maps with no lightmaps also doesn't cause this issue.

### To Reproduce

Not exactly sure how to reproduce, having a few different models usually causes it but just 1 seems fine?
Kind of confusing

### Expected behavior

Have vertex color(s) not removed

### Media/Files

No bake: 
![20220924213713_1](https://user-images.githubusercontent.com/50308149/192124825-cafa90f5-60fb-4d5d-947e-cff511714db9.jpg)

Bake: 
![20220924213652_1](https://user-images.githubusercontent.com/50308149/192124830-9d21fb77-5761-4aa5-bef5-855022a93cc7.jpg)

**Comment by aylaylay** [comment]
This should be fixed by using VertexPaintBlendParams semantic name in your shader. Blending vertex data gets stripped otherwise.

**Comment by aylaylay** [comment]
Ended up being a shader fix ```float4 vColorBlendValues : Color0 < Semantic( Color ); >;```
