### ISSUE TITLE
Indicate assets without local source content present

### ISSUE THREAD

**Issue by DoctorGurke** [sboxgame/issues#2364]
### For?

S&Box

### What can't you do?

When having an addon loaded/enabled that only has compiled files, or when compiled files are eventually left over, there is no clear way of seeing if the content has source files present without attempting to open said assets. The only indicator would be the extension of the path `_c`, which doesn't work well in icon mode.

### How would you like it to work?

There should be a clear indicator in the asset browser, perhaps just on the icon of said asset.

### What have you tried?

The shown filepath will technically show the _c, but this can be ommitted in specific situations where the filepath is too long, see #2363

**Comment by DoctorGurke** [comment]
having a source present means it can be opened and edited, seeing that on a quick glance seems beneficial to me

**Comment by xezno** [comment]
#3205 mentions a pretty good use case for this, so I'll take a look at it after I'm done with my current asset browser changes
