### ISSUE TITLE
Cannot network static variables

### ISSUE THREAD

**Issue by timmybo5** [sboxgame/issues#2374]
### Describe the bug

I'm not sure if this is intended behavior or not but it would be a very nice feature to be able to network static variables, in this case I'm not using an enum to allow consumers to define their own ammo types ontop of the base types.

// Doesn't work
```
public partial class AmmoTypes : BaseNetworkable
{
    public static readonly AmmoType SMG = new(3, "SMG");
}

[Net]
public int AmmoType { get; set; } = AmmoTypes.SMG;
```

// Works
```
[Net]
public int AmmoType { get; set; } = new(3, "SMG");
```

**Comment by timmybo5** [comment]
A workaround to the problem is to instantiate a new instance every time the static variable is called using `=>` instead of `=`.

**Comment by DevulTj** [comment]
This has left me awfully confused.

Why's AmmoTypes a BaseNetworkable? Why not use [GameResource](https://asset.party/api/Sandbox.GameResource)? Why are you networking ints and not just the enum type?
