### ISSUE TITLE
Some BaseNetworkable Classes Don't Network In Networked Dictionaries And Lists

### ISSUE THREAD

**Issue by anthonysharpy** [sboxgame/issues#2376]
**EDIT: see latest comment first**

### Describe the bug

I have this class that describes an item:

```
public partial class ItemInventoryInfo : BaseNetworkable
{
	[Net] public bool GoesInInventory { get; set; } = true;
	[Net] public string Name { get; set; }
	[Net] public int Width { get; set; }
	[Net] public int Height { get; set; }
}
```

In my WeaponBase class I have:

`public ItemInventoryInfo OurItemInventoryInfo;`

In my Pistol class (which inherits WeaponBase) I set it like this in its parameterless constructor:

```
OurItemInventoryInfo = new ItemInventoryInfo
{
	Name = "Pistol",
	Width = 4,
	Height = 2
};
```

In my Inventory class I have a networked dictionary of ItemInventoryInfo objects:

`[Net] public IDictionary<string, ItemInventoryInfo> InventorySlots { get; set; } // The key will be e.g. "3,2" (x, y).`

Doing the following will not replicate to the client (they will see that there is a key that's been added, but all the values of inventoryInfo for that key will be zero-values). inventoryInfo is the same object that was defined in Pistol:

`InventorySlots.Add("0,0", inventoryInfo );`

It does work if I make the **original** variable from WeaponsBase networkable (I guess this sort of makes sense):

`[Net] public ItemInventoryInfo OurItemInventoryInfo { get; set; }`

However, doing so gives me errors, even though the client now gets the value perfectly:

![image](https://user-images.githubusercontent.com/55365296/193337317-17cf1452-b293-40bd-979e-0222288f075b.png)

![image](https://user-images.githubusercontent.com/55365296/193337343-d9b204ba-eb70-4911-a6d5-823d1ec5b240.png)

### To Reproduce

See above

### Expected behavior

No errors.

Also, should it really need to be a [Net] property in order to be added to a [Net] dictionary? In fact, doing the following and re-creating the class right before adding it to the dictionary also fixes it (with no errors as well):

```
var test = new ItemInventoryInfo()
{
	Name = inventoryInfo.Name,
	Width = inventoryInfo.Width,
	Height = inventoryInfo.Height,
	GoesInInventory = inventoryInfo.GoesInInventory
};

// Works.
InventorySlots.Add("0,0", test);
```

**Comment by anthonysharpy** [comment]
Also finding this sort of thing happening again.

The following code fails to network savedEntityData.Items (which is a [Net] IList of BaseNetworkable classes) to the player:

```
public static bool CreatePlayerFromFile( string file, PlayerBase player )
{
	if ( !Database.FileExists( file ) )
		return false;

	var loadedData = Database.LoadData<SavedEntityData>( file );

	var savedEntityData = CreateNew( SavedEntityDataType.Player, player, player.Client.SteamId.ToString() );

	savedEntityData.SavedPosition = loadedData.SavedPosition;
	savedEntityData.SavedRotation = loadedData.SavedRotation;

	foreach ( var item in loadedData.Items.Contents )
		savedEntityData.Items.Add( item.Clone(), false );

	savedEntityData.Health = loadedData.Health;
	savedEntityData.Money = loadedData.Money;
	savedEntityData.EntityClassName = loadedData.EntityClassName;
	savedEntityData.OwnersName = loadedData.OwnersName;
	savedEntityData.OwnersSteamID = loadedData.OwnersSteamID;

	player.Position = loadedData.SavedPosition;
	player.Rotation = loadedData.SavedRotation;
	player.SavedData = savedEntityData;

	return true;
}
```

The following code works perfectly and does network it. The only difference between the two is the order of execution and the way assignments are done. They should probably both work.

```
public static bool CreatePlayerFromFile( string file, PlayerBase player )
{
	if ( !Database.FileExists( file ) )
		return false;

	var loadedData = Database.LoadData<SavedEntityData>( file );

	var savedEntityData = CreateNew( SavedEntityDataType.Player, player, player.Client.SteamId.ToString() );

	player.Position = loadedData.SavedPosition;
	player.Rotation = loadedData.SavedRotation;
	player.SavedData = savedEntityData;

	player.SavedData.SavedPosition = loadedData.SavedPosition;
	player.SavedData.SavedRotation = loadedData.SavedRotation;
	player.SavedData.Health = loadedData.Health;
	player.SavedData.Money = loadedData.Money;
	player.SavedData.EntityClassName = loadedData.EntityClassName;
	player.SavedData.OwnersName = loadedData.OwnersName;
	player.SavedData.OwnersSteamID = loadedData.OwnersSteamID;

	foreach ( var item in loadedData.Items.Contents )
		player.SavedData.Items.Add( item.Clone(), false );

	return true;
}
```

PS: the reason I'm stupidly cloning classes everywhere is because it seems to be the only workaround at the moment (although, the above also shows that even when you do that, it can still act weird sometimes).

Happy to send a dev my project if it helps track it down.

**Comment by anthonysharpy** [comment]
so I think this is actually caused by trying to put a non-networked class into a networked list of classes.

so if you have 

```
[Net] public IList<ItemInventoryInfo> Contents { get; set; }
```

assume that ItemInventoryInfo derives from BaseNetworkable.

then if you try and put Thing2 into Contents, it won't work, since it's not networked. But Thing1 would work.

```
[Net] public ItemInventoryInfo Thing1 {get; set;}
public ItemInventoryInfo Thing2 {get; set;}
```

this is surprising and ideally it wouldn't work this way imo.

to get around this, you can create a new instance of ItemInventoryInfo and then add it to the list.

```
var newThing = new ItemInventoryInfo();
newThing.Field1 = Thing2.Field1;
newThing.Field2 = Thing2.Field2;
Contents.Add(newThing);
```

**Comment by LeQuackers** [comment]
Does it make a difference if you add a `Component` to the `Enitity` or not?

The `Sandbox.Internal.VarEmbedList` and `Sandbox.Internal.VarEmbedDictionary` classes have a check in their `Build` methods to see if you have 0 components, and if you do they return. Not sure why it's there, but it seems really out of place.

![image](https://user-images.githubusercontent.com/16133099/211940683-cfc9246a-51da-4d3c-9ccf-83c75cc2836b.png)

**Comment by anthonysharpy** [comment]
@LeQuackers hey, sorry been busy with stuff.

i gave it a try and it seems to still be the same issue. for example, i can reproduce this when the player picks up a gun. i tried putting a dummy component on the gun and the player but it's no good.

FWIW, when i remove my workarounds, the engine spews a bunch of errors at me:

![image](https://user-images.githubusercontent.com/55365296/212572141-e5c93077-26f9-43ac-8efd-123def64d680.png)
![image](https://user-images.githubusercontent.com/55365296/212572150-a987bf7d-52e9-4241-8ab1-2f4fc206ed78.png)
![image](https://user-images.githubusercontent.com/55365296/212572206-d29a56b4-1aa0-401d-bb7c-3a5d0a62934d.png)
![image](https://user-images.githubusercontent.com/55365296/212572240-2484d466-248d-4e10-abce-c1b53bc0fd02.png)

**Comment by anthonysharpy** [comment]
think it's obvious these days that the basenetworkable stuff just doesn't work great a lot of the time... i guess it will get re-worked eventually. i wouldn't really recommend trying to reproduce any of the code above since it's all a bit vague. i'll leave this open just in case a dev is desperate for some clues or something. but otherwise feel free to close this whenever is convenient, this is all stuff i worked around long ago anyway 👍
