### ISSUE TITLE
Can't use devcam screen effects outside of local games

### ISSUE THREAD

**Issue by gvarados1** [sboxgame/issues#2382]
### Describe the bug

You can't use the devcam screen effects outside of local game
![image](https://user-images.githubusercontent.com/39461072/193397795-b983a009-5e5e-42d5-a746-9ee1dff25699.png)

The game needs to be locally installed to use the tab devcam tab menu. If you want to use it on Sandbox you need to have the repo installed locally

### To Reproduce

1. try to use devcam tab menu on non-local game
2. doesn't work
3. try to use devcam tab menu on local game
4. does work

### Expected behavior

screen effects should work on non-local games

**Comment by garrynewman** [comment]
This should work, it should really be allowed for anyone that is an admin on the server. If that's not working then we're fucking up somewhere.

**Comment by gvarados1** [comment]
I think it worked at one point but it's been like this for at least 6 months

**Comment by garrynewman** [comment]
I got this solved on my extensions branch, will keep it open until we mount

**Comment by handsomematt** [comment]
Should be good now?

**Comment by bakscratch** [comment]
Working
