### ISSUE TITLE
Tools: GraphicsLine allocates twice

### ISSUE THREAD

**Issue by MuffinTastic** [sboxgame/issues#2383]
### Describe the bug

When a GraphicsLine (or child class thereof) is created, it yells about a double allocation

### To Reproduce

1. Download repro (cut-down version of NodeGraph) https://github.com/MuffinTastic/sbox-tools-repros/tree/graphicsline-double-alloc
2. Open the window (bug icon)
3. Click and drag anywhere in the window to create a line
4. Get yelled at in console

### Expected behavior

No double allocs, no yelling

### Media/Files

![sbox-dev_ZBWaKh2CKx](https://user-images.githubusercontent.com/10884425/193423958-39e8ddbe-ce7b-42ed-bb5d-10a4a526139d.png)

### Additional context

Build f0a37c

**Comment by xezno** [comment]
I think this was fixed at some point because I can't reproduce this (using your repository). Feel free to let me know if it's still an issue and I'll re-open this
