### ISSUE TITLE
TypeLibrary: Support type full name in GetDescription( string name )

### ISSUE THREAD

**Issue by peter-r-g** [sboxgame/issues#2413]
### What it is?

Right now you can only get type descriptions by a class name. The problem is if there are classes with the same name but in different namespaces then they will clash.

### What should it be?

Continue to support giving a class name but allow being able to search by [Type.FullName](https://learn.microsoft.com/en-us/dotnet/api/system.type.fullname?view=net-6.0). My use case for it is in custom networking to network a type by its fully qualified name so that there are no duplicate class name clashes

**Comment by robotboy655** [comment]
I am fairly certain this was resolved 2 days ago.

https://commits.facepunch.com/427667
