### ISSUE TITLE
Whitelist: Allow System.Diagnostics.Debugger.IsAttached and System.Diagnostics.Debugger.Break

### ISSUE THREAD

**Issue by LeQuackers** [sboxgame/issues#2415]
### For?

S&Box

### What can't you do?

I'm unable to add debug assertions to my project that should be removed in release mode (related to #2320, originally from #2408).

Whitelisting `System.Diagnostics.Debugger.IsAttached` and `System.Diagnostics.Debugger.Break` would allow for the creation of assertions without the need to whitelist `System.Diagnostics.Debug.Assert`.

### How would you like it to work?

Simply whitelisted.

### What have you tried?

I've tried `System.Diagnostics.ConditionalAttribute`, but it isn't whitelisted.
I've also tried the `Sandbox.Assert` static class, but they aren't removed in release mode.

**Comment by LeQuackers** [comment]
I forgot about `System.Diagnostics.DebuggerHiddenAttribute`; It would go well with these, but isn't required. It basically hides a particular method from the debugger, i.e. the wrapper/helper method for `Debugger.Break`.

**Comment by handsomematt** [comment]
I've whitelisted System.Diagnostics.ConditionalAttribute which should let you do what you want, I don't really like the idea of whitelisting this debugger stuff.

**Comment by LeQuackers** [comment]
I would be really nice for custom assertions, but if it's not in the cards feel free to close this.

**Comment by handsomematt** [comment]
I thought about it some more and I really don't like that Debugger.Break would ask you to attach a debugger when one isn't attached. Sorry!

**Comment by LeQuackers** [comment]
Final question about this; would adding an `Assert.Break` method like the one below be acceptable? It would only break if a debugger was already attached, so users wouldn't be prompted to attach one.
```cs
public static class Assert
{
	[DebuggerHidden]
	[Conditional("DEBUG")]
	public static void Break()
	{
		if (Debugger.IsAttached)
		{
			Debugger.Break();
		}
	}
	
	...
}
```

**Comment by Redhacker1** [comment]
I'm not sure that this is a good idea in general. If you need that kind of functionality, you can always just place a breakpoint. You can use a simple semicolon to add a no-op where you want it.
