### ISSUE TITLE
VR controller angular velocity is incorrect when the VR anchor is rotated

### ISSUE THREAD

**Issue by ShadowBrian** [sboxgame/issues#2423]
### Describe the bug

I'm making a disc golf gamemode and the reported angular velocity on the controllers makes the disc do all sorts of weird things when the vr anchor's yaw isn't zero'd.

I've worked around it for now by manually figuring out the angular velocity from the controller rotation delta but it's not ideal.

### To Reproduce

Rotate the VR.Anchor transform to 90 degrees and observe the yaw rotation basically not doing much if you twist your arm.
It's a bit tricky to actually test but it appears as though the rotation vector is angled incorrectly?

### Expected behavior

Proper rotation regardless of the anchor rotation...

### Media/Files

https://user-images.githubusercontent.com/11138884/197048777-7d122c1c-ea23-46a8-a2db-c275a820252b.mp4

In this video up here I have a debug text showing the yaw rotation, when it's 180 the yaw of the angular velocity appears to be reversed, when it's 90 or 45 it does... no idea? Something else? It appears to swap places with the pitch value for some reason.
When it's 0 (or near it) the rotation is correct and the disc rotates the way I release it with my hand.

**Comment by handsomematt** [comment]
this works as expected for me now I think, it wasn't really making any sense to transform it for the anchor

**Comment by ShadowBrian** [comment]
Appears to be sorted on most controllers- seeing some slight weird behavior on Index but nothing that'd make it unusable like before.
Index problem might need a proper issue on Valve's side given that it's just taking OpenVR data now.
