### ISSUE TITLE
Objects disappear when they get too far away in VR

### ISSUE THREAD

**Issue by ShadowBrian** [sboxgame/issues#2424]
### Describe the bug

Whenever an object gets far enough away it seems to flicker out of existence in VR.
This appears to be directly related to how large the object is, but the flickering effect indicates it's not entirely culling related and the whole thing seems rather strange.

### To Reproduce

Go to the "Disc golf" gamemode or even the "Table tennis" gamemode in VR, "Revolver Hysteria" also has this issue on enemy bullets, you can't see them coming until they're like 400 units away from you.
Get the disc or pingpong ball a bit away from you- with the ping pong ball it feels like about 300 units, the disc disappears at about 700 or so units by my estimate...

### Expected behavior

Objects shouldn't just flicker out of existence while you can still clearly see them, it's terrible and ruins object tracking from far away.

### Media/Files

https://user-images.githubusercontent.com/11138884/197052966-28f93a28-f122-4a6c-8ac7-10cb74e8fa79.mp4

Here's me throwing the disc around, it takes a bit of distance but the flickering effect should be pretty visible.
I used to be able to work around this by overlaying a debug circle but that doesn't appear to work anymore.

**Comment by handsomematt** [comment]
Should work perfectly now, let me know if there are any side effects with objects potentially culling too close to you now - it was all fine when I was testing though.

**Comment by ShadowBrian** [comment]
Appears to work! Thank you matthew :D
