### ISSUE TITLE
Screen recording often either crashes or breaks game audio

### ISSUE THREAD

**Issue by xezno** [sboxgame/issues#2427]
### Describe the bug

When I try to record my game using F6, the game either crashes entirely or my game audio stops working.
This seems to be dependent on the length of the recording: if I only record for a couple of seconds, it's less likely to crash.

### To Reproduce

1. Hit F6
2. Depending on hardware config it'll either crash or work fine - I haven't found a way to repro this reliably (sorry)

### Expected behavior

The game shouldn't crash and audio should work properly.

### Media/Files

I couldn't find anything that seemed important or relevant for this.. here's a crash recording, which probably isn't useful at all - I did two recordings, one lasting a couple seconds, the other lasting a few seconds longer; the longer recording crashed:

https://user-images.githubusercontent.com/12881812/197351626-5d206a8e-d159-4a3c-ab99-d545d9851477.mp4

Here's the log file from that session, which contains basically nothing useful:
[Log.log](https://github.com/Facepunch/sbox-issues/files/9844836/Log.log)

### Additional context

Sorry about there not being too much info - I felt like it was better to report this though, rather than leaving everyone in the dark about it..

I have tried re-installing my game entirely, but the issue still persists - so I'm pretty sure it's not a game config issue. I have a pretty standard setup (Ryzen 5 3600, GTX 1070, 32GB ram).

Let me know if there's any other info / files you need.

**Comment by aylaylay** [comment]
Out of ideas with this one, unless I can get it to happen there's not much I can do

**Comment by xezno** [comment]
Yeah that's understandable. I've tried messing around with configs and hardware and stuff, I'm not sure what the issue is either. 
I'm not sure whether it's worth keeping this issue up while there's no proper repro though

**Comment by aylaylay** [comment]
Found out recently this might be a threading issue, the video encoder is due a rewrite so will get fixed then.

**Comment by aylaylay** [comment]
Video recorder was recoded so not sure if this issue applies anymore. If there's still crashes with the new one please open a new issue.
