### ISSUE TITLE
Trying to put client in server but we have no gamemode!

### ISSUE THREAD

**Issue by PoPenguin** [sboxgame/issues#2444]
### Describe the bug

When I update s&box today,it haven't gamemode can play,I think it is a serious bug!
![QQ截图20221028090000](https://user-images.githubusercontent.com/99338058/198434867-a65c4e70-e19e-4c72-915a-8da037c66871.png)

### To Reproduce

1.Open s&box 2.chose gamemode 3.chick "Start Game" 4.See bugs

### Expected behavior

play sandbox gamemode happily

**Comment by Arr-n-D** [comment]
Commenting to mention this doesn't seem to be an isolated bug but many people on Discord are currently having this issue as of 8:37 PM EST

**Comment by trende2001** [comment]
issue for everyone, in result nobody can play s&box right now

**Comment by garrynewman** [comment]
Doh - should mostly be fixed on next build

**Comment by MuffinTastic** [comment]
Seems to be fixed for me
