### ISSUE TITLE
Addon upload timed out on file, now manifest/version is broken and seemingly cannot be salvaged

### ISSUE THREAD

**Issue by DoctorGurke** [sboxgame/issues#2455]
### Describe the bug

I tried to upload a map, vpk is 303mb, got a backend error 524 (timeout)
The backend still thinks the file is up, however, so I cannot reupload it, but the addon has no version/content on asset.party
can't upload under a new ident either, only solution seems to be to rename and recompile the map entirely, assuming the other files did actually end up on asset party somewhere

### To Reproduce

I assume it just breaks if a single file upload fails for some reason, but the manifest was already updated with said file info

### Expected behavior

:( 

### Media/Files

![sbox-dev_bh6kXnUu8o](https://user-images.githubusercontent.com/12602100/198831845-9a5b1174-b3ac-48ba-98f7-79e070bcec19.png)

![firefox_ydeLCKa2UD](https://user-images.githubusercontent.com/12602100/198831847-cf0bd670-3a2a-42a5-a93b-069d7fac874a.png)

**Comment by garrynewman** [comment]
Have you got a link to the asset?

**Comment by DoctorGurke** [comment]
https://asset.party/eagleone/nachzehrer_map/version

**Comment by garrynewman** [comment]
So to summarize what I think is happening here..

You go to make a new release, but it won't let you do it because all the files that need to be uploaded are already uploaded.

Solution is that it should let you make a release even if there were no files changed, because obviously other stuff may have changed.

**Comment by DoctorGurke** [comment]
Ideally the backend manifest wouldn't even assume a file is present if the upload failed, right?
