### ISSUE TITLE
Arbitary scaling for skeletal animation

### ISSUE THREAD

**Issue by sndrec** [sboxgame/issues#2458]
### For?

S&Box

### What can't you do?

Currently, skeletal animation does not support scaling on any arbitrary axis. It's just a single scalar value. This is somewhat limiting for animation, especially of a more cartoony or exaggerated style.

https://user-images.githubusercontent.com/10429809/198860252-57de59df-e12f-4526-ab30-87a304cb44ba.mp4

The above video demonstrates several animations which make heavy use of scaling on different axes to convey motion and power. These were created for use in a platform fighter.

https://user-images.githubusercontent.com/10429809/198860302-75f4183a-74a0-4373-b634-a48353fa9aad.mp4

This is how these animations look without scaling.

https://user-images.githubusercontent.com/10429809/198860427-540e80bd-13f5-42a5-a93c-67e9bc67fb63.mp4

The above video demonstrates some squash and stretch for 3d modeled letters done with skeletal animation, and how they show up in modeldoc after import.

### How would you like it to work?

I'd like for skeletal animations to support scaling on arbitrary axes. Even if it does not support scaling physics bodies attached to the bones, this would be an excellent feature for characters in gamemodes which do not rely on accurate hitboxes on the character model.

### What have you tried?

The only workaround I could imagine would be to use two or more additional bones on each joint in order to accomplish a similar effect, but this would be a lot of additional work for a solution which is overall less (or differently) effective.

### Additional context

Because my animation style leans heavily into these sorts of principles, this missing feature blocks me from developing a platform fighter on s&box, which I'd like to do after I've gotten the [gamemode I'm currently working on](https://asset.party/freakorg/test_stuff) into a state I'm comfortable with.

**Comment by NotGaylien** [comment]
I have actually really wanted to be able to do this as well and ended up dropping a project because it wasn't possible.

Getting that cartoony Squash and Stretch without fucking with loads and loads of morphs
(this is genuinely ass please dont recommend us to do that, since you might need hundreds of them to achieve what you want in some cases, thats why i dropped a project i saw it was just awful and gave up)
is just not possible and would be really appreciated and help animators get super creative and stylized with their animations.

**Comment by MaxLebled** [comment]
This has been added but for various reasons we can't support non-uniform scaling. For those purposes we recommend you bake morph shapes corresponding to each axis and script yourself a workflow that can emulate scaling through exporting animation using them
