### ISSUE TITLE
All sounds stop working after a while

### ISSUE THREAD

**Issue by yuberee** [sboxgame/issues#2461]
### Describe the bug

Playing our game after a while seems to stop all sounds on S&box.
We haven't found what causes it yet, it might happen as you're walking down the road or while getting jumpscared.
It's probably related to the sound's volume, as it's similar to something happening in Cat Harvest's secret ending, where you're supposed to get a loud sound but nothing plays out. I'm sure we would've noticed about this bug earlier if it wasn't for the fact that the secret jumpscare ending in Cat Harvest also crashes your game (on purpose).
This is the code (sorry) for the old cat's jumpscare:
```
current.Jumpscare = true;
Sound.FromScreen( "angry0" ).SetVolume( 255f );
Sound.FromScreen( "angry0" ).SetVolume( 1f );
Sound.FromScreen( "angry0" ).SetVolume( 10f );
Sound.FromScreen( "angry0" ).SetVolume( 50f ); //Just to be sure, not sure why it doesn't play sometimes
ChangeMusic( "" );
await current.Task.Delay( 2000 );
while ( true ) { };
```

This is the repo for our jam game:
https://github.com/Small-Fish-Dev/Cryptid-Hunt
and this is Cat Harvest:
https://github.com/yuberee/cat_harvest

I modified all sounds to make them uncompressed, stereo, and louder by themselves, so I would just do .SetVolume(2) instead of .SetVolume(5) for the jumpscare. But unfortunately it happend to me as well.

### To Reproduce

1. Play Cryptid Hunt
2. Wait a while
3. The sound stops working

or

1. Play Cat Harvest
2. Collect El Wiwi (In tools mode, it's the only one you can select with the Entity Viewer, just make it larger because it's tiny)
3. This plays the secret ending, where you're supposed to be jumpscared and then have your game crashed (This might not be the same bug)

### Expected behavior

I'm assuming it's supposed to limit sounds but doesn't.

### Media/Files

https://clips.twitch.tv/BetterRelentlessPigeonCharlietheUnicorn-SHZnbBggeYkDzmkY

### Additional context

- I tried replicating the sounds not playing on Cat Harvest but couldn't get it to happen, even in an async context.
- I tried playing very very loud sounds but those didn't seem to cause the problem.
- I tried switching the audio codec and compression model, but that didn't change anything.
- In Cat Harvest, I disabled the game crashing, got no sounds where it was supposed to, but after closing the game I had normal sounds in S&box. As opposed to Cryptid Hunt completely removing all sounds from S&box.
- You are supposed to hear the sound of stepping on the gravel path, but for some reason that doesn't play for anyone but me, and that was after I recompiled it (It's a base s&box sound), might be related or might not.

**Comment by yuberee** [comment]
I just enabled debugging stuff in Cryptid Hunt's repo, you'll want to skip the nextbot section so get straight into the forest game.
Sprinting is now way faster and you'll be able to see the different ranges of the monster.
It usually happens around the pond, if it doesn't then it might be related to the playtime since you're speeding through.

**Comment by yuberee** [comment]
Just caught it happening on camera.

https://user-images.githubusercontent.com/59583743/199248274-696ec6f4-747f-46c0-bb13-a5c231e74de7.mp4

This is the file in question: https://github.com/Small-Fish-Dev/Cryptid-Hunt/blob/main/sounds/polewik/jumpscare.wav
And this is where the sound is being played: https://github.com/Small-Fish-Dev/Cryptid-Hunt/blob/8ab234bd50bc295e767aebf69ea95eea0a5cd132/code/Entities/Polewik.cs#L197

**Comment by yuberee** [comment]
I've set my general s&box volume to be at around 60% and played several times, that seemed to fix it so I assume it really is an audio level problem.

**Comment by cr4yz** [comment]
I've found the problem here, your Polewik footstep sound occasionally plays at an insane position: `81410590000000000000,0,4102587000000000` 

This is making the audio system fall apart and requires S&box to be restarted to hear again.  We're working on a fix.  In the meantime, if you want to patch it up you could run a sanity check on Polewik's footstep trace result before playing a sound.

I am curious how your trace result is coming up with that number, if that's our fault that should be looked into as well

**Comment by yuberee** [comment]
Good catch! This is the line:
https://github.com/Small-Fish-Dev/Cryptid-Hunt/blob/c424dc93db3f40ab7a89657199d97fd0ad1af356/code/Entities/Polewik.cs#L651

The trace is just 10 units in length, so the problem probably comes from the AnimFootEvent in the vmdl.

**Comment by ogniK5377** [comment]
I've gone ahead and done a partial fix for this, I've setup an issue internally to track the remaining issues for it. However that being said, the sound shouldn't be broken anymore 👍
