### ISSUE TITLE
Qt Menus don't have enough width with Icon + Text + Shortcut

### ISSUE THREAD

**Issue by QuackCocaine** [sboxgame/issues#2462]
### Describe the bug

Under `File`  part of the text showing the key-combo to open the solution is partially obscured 

### To Reproduce

1. Open the Editor.
2. Click on `File` in the top left of the window.
3. Observe the issue when you look to open a solution that way.

### Expected behavior

To not have text going over other text.

### Media/Files

![He5sLgsx1I](https://user-images.githubusercontent.com/23345567/199008499-bd43b2ea-1c9f-4dd1-a710-95f602158e01.png)

**Comment by DevulTj** [comment]
This'll be fixed when an update hits Steam
