### ISSUE TITLE
Hammer: Overlay projection distance property is number field instead of using the box helper

### ISSUE THREAD

**Issue by DoctorGurke** [sboxgame/issues#2469]
### What it is?

The property "projection distance" on overlays is a number field that you have to manually type into

### What should it be?

It should just use the box helper in-editor

![sbox-dev_Kb5RXYDLjf](https://user-images.githubusercontent.com/12602100/199351434-3d15a8b0-0c47-45cf-83fc-752694f88c9d.png)

![sbox-dev_yG0cAkzYSo](https://user-images.githubusercontent.com/12602100/199351476-81949e15-43bc-43ed-8023-2d39037c0d89.gif)

**Comment by robotboy655** [comment]
It's not a box helper but a mesh (a plane) internally, which makes it that much more difficult to solve when it comes to scaling rotated overlays.

I have made some changes that should help in most cases, but it still won't work correctly when box scaling rotated overlays.

I am not sure it is possible to "fix" without changing how projected decals work in Hammer to be more like Orthographic Lights which would make decals lose the ability to be scaled with anything else (i.e. the mesh they are projecting onto) at the same time.

**Comment by DoctorGurke** [comment]
This is much nicer now, thanks
