### ISSUE TITLE
Hammer: Default value for active material (reflectivity 30)

### ISSUE THREAD

**Issue by DoctorGurke** [sboxgame/issues#2470]
### For?

Hammer

### What can't you do?

I'd like to be able to quickly reset the active material back to the default (reflectivity 30), similar to other pickers in tools like the material editor

### How would you like it to work?

Similar to texture inputs and other parameters in the material editor:

![sbox-dev_XSgEpijHFp](https://user-images.githubusercontent.com/12602100/199356637-ed5d4dcb-412d-4689-8417-07ce44d359ba.png)

![sbox-dev_eIvinZr1Ug](https://user-images.githubusercontent.com/12602100/199356641-234a7f8f-3e11-4c8e-a9b8-370491d544b6.png)

### What have you tried?

the material only seems to reset to default on a full editor restart, other than that there doesn't seem to be an obvious way to reset to the default dev material without manually picking it

**Comment by robotboy655** [comment]
Added, as well as a command for F1
