### ISSUE TITLE
Asset Browser: Option to create new map file from asset browser context menu

### ISSUE THREAD

**Issue by DoctorGurke** [sboxgame/issues#2471]
### For?

S&Box

### What can't you do?

I can't easily create map files like I can material, model, etc, right through the asset browser

### How would you like it to work?

In the same context menu as material & model preferrably, on right click

![sbox-dev_CuUlxsg3nD](https://user-images.githubusercontent.com/12602100/199356937-f3471f01-00ee-422e-9164-4f33d6c3be13.png)

### What have you tried?

Currently you need to open hammer, make a new file, save it and navigate to your addon/folder to make a new map file. Being able to just create a vmap from the asset browser would greatly improve this workflow for creating prefabs, test maps and other such maps that aren't a main map project

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/233698074-8824414e-9d22-4e7c-a364-fa920f15ac9d.png)
