### ISSUE TITLE
Asset browser: full asset path tooltip on long hover

### ISSUE THREAD

**Issue by DoctorGurke** [sboxgame/issues#2473]
### For?

S&Box

### What can't you do?

I can't easily see the full system path of an asset in the asset browser

### How would you like it to work?

a tooltip with the full path on long hover or an extra label in the inspector could do the trick, not sure

### What have you tried?

it's possible to open the asset location in the system explorer, but that's one step too many and too far to just quickly see where your files are on your system. 
the "copy path" option only copies the in-asset-system location, relative to an addon etc. Which is fine and definitely how it should be, but there's no alternative for a full path

### Additional context

![sbox-dev_3HMDqGqI1X](https://user-images.githubusercontent.com/12602100/199358429-34d51646-0708-48e8-8700-e860226b9510.png)

![sbox-dev_qgpfyTLUIy](https://user-images.githubusercontent.com/12602100/199358436-64497dd9-c055-46ff-b9c9-7e23e5e072ba.png)

**Comment by robotboy655** [comment]
I have made it show the full path in the status bar of the window the asset browser is attached to, let me know if you think that's shit

**Comment by DoctorGurke** [comment]
this is nice, thanks
