### ISSUE TITLE
Hammer Input: empty parameter for expected type "string" results in NRE

### ISSUE THREAD

**Issue by DoctorGurke** [sboxgame/issues#2475]
### Describe the bug

trying to pass an empty string as an empty parameter through entity io results in a nre

### To Reproduce

1. Use the provided test entity on a map with some basic button io
2. firing the string input with a blank parameter results in a nre

### Expected behavior

it should get a `default` string value if the expected type is string and nothing was passed

### Media/Files

test entity:
```csharp
[HammerEntity]
public class TestEntity : Entity
{
	[Input]
	public void TestInput( string name )
	{
		Log.Info( $"my name is: {name}" );
	}
}
```

works fine:
![sbox-dev_GapKCk9zsa](https://user-images.githubusercontent.com/12602100/199353501-a009ea31-98cd-47f9-8a3f-150dac42dd44.png)

throws:
![sbox-dev_Epxb9BiBJ3](https://user-images.githubusercontent.com/12602100/199353527-d4278f86-c3ae-47fc-8fe2-5b8c8feacb5b.png)

![sbox-dev_nGQc9m8Vo9](https://user-images.githubusercontent.com/12602100/199353542-877d7fa4-1d08-4569-b129-155d27bfe08b.png)

![sbox-dev_lHCugBzJuv](https://user-images.githubusercontent.com/12602100/199353559-bab5bf55-a30e-4730-a099-3c9ab6177aa0.png)

![sbox-dev_RWYAjM25Sa](https://user-images.githubusercontent.com/12602100/199353566-54c3167c-fbe1-4c98-b898-aca6d9b6b665.png)

**Comment by robotboy655** [comment]
I have improved error handing for inputs in Hammer, so it will display nicer errors.

I have made strings default to an empty string rather than null/default. You can override this if you really must by giving default value to your parameter.
