### ISSUE TITLE
Model without render mesh counts as invalid for scenemodels, breaks thumbnail generation and probably some other things

### ISSUE THREAD

**Issue by DoctorGurke** [sboxgame/issues#2476]
### Describe the bug

a model without a render mesh will not count as a valid model, despite other visual nodes such as particles via generic game data

### To Reproduce

1. make a model without a rendermesh, but with nodes such as particles, attachments, etc.
2. Try to generate a thumbnail in the asset browser
3. see errors and no thumbnail

### Expected behavior

While models without meshes could very well be considered a specific case, I believe the amount of data that can be in a model makes an approach like this very viable for specific situations, such as aligning particles relative to another model via attachments or producing a model with only a render particle and physics hull for an effects entity

### Media/Files

![sbox-dev_Lg1yzu1waV](https://user-images.githubusercontent.com/12602100/199359641-9c389626-6a37-412a-9839-4db4b5966c8c.png)

![sbox-dev_8Sl7Mwa4a3](https://user-images.githubusercontent.com/12602100/199359605-ad9bf1d9-5f03-4ca9-8ee3-19d9af802463.png)

![sbox-dev_lbwKdauOy0](https://user-images.githubusercontent.com/12602100/199359654-b1f99e92-6226-4e46-9043-8db36ec7f99a.png)

![sbox-dev_ZZzWwWsHGk](https://user-images.githubusercontent.com/12602100/199359666-e83d0637-89f6-4442-83cf-197495c2f117.png)

![sbox-dev_Yx3TYfgXjC](https://user-images.githubusercontent.com/12602100/199359671-d871c898-1aac-42fd-b85b-7fdea2e048df.png)

**Comment by aylaylay** [comment]
I have protected against this in tools. You'll get an assert if you purposefully try to create a sceneobject with a model with no meshes as this wold make no sense. No meshes = No scene objects

**Comment by DoctorGurke** [comment]
would/should the particle attached to the model not get a scene object and render that? exactly like how particle thumbnails are generated, it should probably be able to generate a thumbnail for a model without meshes but particles, since it's perfectly supported by the tools and engine. The model can be used as a hammer editor model and spawned at runtime and will generate the proper particle systems.

**Comment by aylaylay** [comment]
Are you just wanting this so you can use a particle for a editor model? If so it would probably be better to just support particles directly in editor model attribute or have a new helper for it

**Comment by DoctorGurke** [comment]
I used this in a practical example for our game jam game nachzehrer. I had a model for a rune with a particle system and an attachment. I used it both directly as the editor model and as the runtime entity model. I then used said attachment to position another entity and collisions from code procedually. Using it as an editor model was mostly coincidence as it just seemed to be the easiest way to get my particle in the editor preview.

**Comment by aylaylay** [comment]
So basically you just want included particles on models to show up in preview and thumbnails?

**Comment by DoctorGurke** [comment]
Yes, even if they don't have render mehes. If it's a valid compiled asset it should get a proper thumbnail basically

**Comment by aylaylay** [comment]
That's fair
