### ISSUE TITLE
Asset browser: context menu option to quickly copy org.ident for asset.party assets

### ISSUE THREAD

**Issue by DoctorGurke** [sboxgame/issues#2477]
### For?

S&Box

### What can't you do?

Easily use asset.party content for games by just copying their `org.ident` from the cloud section in the asset browser

### How would you like it to work?

Similar to copying the asset path of regular assets, just for the org.ident of said cloud asset

### What have you tried?

currently I have to open the asset in my browser, look at the url and construct the `org.ident` based on that, this makes me sad

![sbox-dev_jSNcEhitNw](https://user-images.githubusercontent.com/12602100/199359897-2b75856d-a0ac-446b-8bca-2cfa8f743c37.png)

**Comment by bakscratch** [comment]
Just added this :)
