### ISSUE TITLE
Asset Browser: default new material uses invalid texture reference for core source file and therefore results in an error material

### ISSUE THREAD

**Issue by DoctorGurke** [sboxgame/issues#2480]
### Describe the bug

creating a brand new material through the asset browser creates an error material due to a source file reference that does not ship with the game

### To Reproduce

1. rightclick the asset browser
2. create new material
3. save somewhere
4. see error material

### Expected behavior

it should use a texture source file that actually ships with the game, probably just testgrid to be in line with the default model

### Media/Files

![sbox-dev_ECdnnUrVtp](https://user-images.githubusercontent.com/12602100/199361139-14b1aeff-db26-4325-a6f2-3bab7a741180.png)

![sbox-dev_KtI0nyEhsq](https://user-images.githubusercontent.com/12602100/199361147-05009820-1f37-44d8-8b23-fcf0a900e936.png)

**Comment by bakscratch** [comment]
Should be fixed now
