### ISSUE TITLE
Asset Browser: tag support for assets and ability to exclude/include specific tags

### ISSUE THREAD

**Issue by DoctorGurke** [sboxgame/issues#2481]
### For?

S&Box

### What can't you do?

I can't tag assets for my game and filter them accordingly for different purposes

### How would you like it to work?

I would like to be able to attach tags to assets in the inspector and filter using those tags

### What have you tried?

the legacy asset browser had a tag filter with pre-defined tags
this is probably ass and should just be left up to people's projects
the new asset browser does not have a tags function

**Comment by robotboy655** [comment]
Related issue: https://github.com/sboxgame/issues/issues/641
