### ISSUE TITLE
Asset browser: Rename

### ISSUE THREAD

**Issue by DoctorGurke** [sboxgame/issues#2482]
### For?

S&Box

### What can't you do?

I can't rename asset files directly from the asset browser

### How would you like it to work?

via the context menu per-asset

### What have you tried?

I have to switch back to my file explorer to rename files, which also seems to not update properly in the asset browser (this might be worth another issue)

### Additional context

it'd be lit if it's integrated into the asset browser in a way that all currently active asset references for said asset are automatically updated, too

**Comment by kristiker** [comment]
Don't forget to tie it to the F2 button.

**Comment by DoctorGurke** [comment]
god yes please

**Comment by DevulTj** [comment]
I've added rename as a context menu option. It doesn't update any asset references as of right now, as that needs some more thought.
