### ISSUE TITLE
Setting your game's map selection to "this list only" isn't respected when selecting maps

### ISSUE THREAD

**Issue by ShadowBrian** [sboxgame/issues#2490]
### Describe the bug

When my game is set to "this list only" it still just shows all maps- I think none of the other map selection modes work either but not sure.

### To Reproduce

1. Go to any game set to "this list only" and make a lobby.
2. Change the map.
3. See that it just shows every map available.

### Expected behavior

The expected result should be that it only shows the maps you set in your game's settings.

### Additional context

This probably came along with the new main menu UI.

**Comment by handsomematt** [comment]
Should work good now.

**Comment by ShadowBrian** [comment]
It does! Thank you Matt 🙏
