### ISSUE TITLE
Apply settings button doesn't work

### ISSUE THREAD

**Issue by trundler-dev** [sboxgame/issues#2491]
### Describe the bug

When you try to apply settings, nothing happens.

### To Reproduce

1. Open settings
2. Change something
3. Press apply settings
4. Nothing happens

### Expected behavior

Settings should apply

### Media/Files

https://user-images.githubusercontent.com/57276947/199592956-d77c0dd9-bfe9-48f5-b58c-44f76a9f6182.mp4

**Comment by Arr-n-D** [comment]
Happens to me as well

**Comment by handsomematt** [comment]
give that a go trundler-chan

**Comment by trundler-dev** [comment]
works great, thanks ^-^
