### ISSUE TITLE
asset.party uploader should convert spaces to underscores when converting asset name to ident

### ISSUE THREAD

**Issue by walllable** [sboxgame/issues#2493]
### For?

S&Box

### What can't you do?

Sometimes I can't upload a `.sound` file because the auto-generated backend ident has spaces in it, which the uploader doesn't like, so I have to manually change it to use underscores.
![image](https://user-images.githubusercontent.com/10066958/199632880-4af941f3-ed0c-445a-be90-08ee6ebf2773.png)

### How would you like it to work?

I think it should just convert the spaces in the filename to underscores when publishing an asset.

### What have you tried?

changing the spaces to underscores manually which sucks

**Comment by robotboy655** [comment]
Done.
