### ISSUE TITLE
SCSS: Transition Error when no easing function is provided

### ISSUE THREAD

**Issue by Adesii** [sboxgame/issues#2496]
### Describe the bug

when not completing the transition statement in SCSS like this:
`transition: all 0.5s;` <- this doesn't work

It compiles just fine but when it is actually used it can't find a easing function and errors on the panel.
`transition: all 0.5s ease-in-out;` <- this works 

### To Reproduce

Have a transition on any UI panel like this: `transition: all 0.5s;`

Trigger a Transition and see that it errors.

### Expected behavior

it should either not compile or default to ease-in-out

**Comment by ogniK5377** [comment]
Should be fixed next update 👍

**Comment by Adesii** [comment]
Works now thanks!
