### ISSUE TITLE
character counter for ident when uploading asset

### ISSUE THREAD

**Issue by walllable** [sboxgame/issues#2497]
### For?

S&Box

### What can't you do?

If I wanna check my character count on an ident to make sure I don't go over 16 characters, I have to go to another website, and spend 30 seconds to find this
![image](https://user-images.githubusercontent.com/10066958/199635493-b7862278-5df4-43fd-89d5-8c55857b44cd.png)
when I could've spent half a second looking at an integrated character counter instead.

### How would you like it to work?

A live-updating character counter in (or just near) the text box would work fine, I think.
![image](https://user-images.githubusercontent.com/10066958/199635736-7d70373b-a6e4-47ea-bbd5-6cfb6a2545d5.png)
![image](https://user-images.githubusercontent.com/10066958/199635740-1d8c5265-10ea-4d10-987d-5c17e13da2fe.png)

### What have you tried?

going to a website and copy-pasting my ident to check the character count

**Comment by robotboy655** [comment]
You will now see errors when your input is invalid.

![image](https://user-images.githubusercontent.com/3299036/200065977-224b94fb-0088-4522-8ee8-c6eda9096a1a.png)
