### ISSUE TITLE
Networking Codegen: Default value missing namespace

### ISSUE THREAD

**Issue by peter-r-g** [sboxgame/issues#2509]
### Describe the bug

Right now, having a default value on a networked property that is a part of a non-global namespace will throw a `The name 'x' does not exist in the current context` error.

### To Reproduce

1. Create a networked property of a non-standard type.
2. Add a default value to that property.
3. Receive the error once codegen passes over the property.

### Expected behavior

For there to be no error.

### Media/Files

Grubs had this issue at commit [a0d4f45cafd94e72a4a75980077eb31ef8454202]( https://github.com/apetavern/sbox-grubs/blob/a0d4f45cafd94e72a4a75980077eb31ef8454202/code/Terrain/TerrainZone/TerrainZone.cs#L21)

### Additional context

This was previously an issue and was fixed. In the past couple of weeks, this broke again.

**Comment by robotboy655** [comment]
Should be fixed now.
