### ISSUE TITLE
Enabled Addon Presets

### ISSUE THREAD

**Issue by PixelQubed** [sboxgame/issues#2511]
### For?

S&Box

### What can't you do?

Currently, it's annoying to enable and disable addons one by one. There is no way to do it in a launch preset or the addon menu.

### How would you like it to work?

I would like it to work so you can have presets in with the launch configs of what addons you want to be enabled, so you don't have to disable the unrelated ones one by one before entering the game. This would also reduce the number of conflicts between assets you may have, like if one addon overwrites another's assets, and you can't figure out why until you go through disabling assets. Another way would be to add custom categories to the addon manager so you can arrange your projects into different sections for each separate project where you can mass enable or disable content if you need or don't need it.

### What have you tried?

Well, nothing. I'm, not a coder. I've done some scripting but that's about it. 
This section needs to be removed from feature requests in my opinion.

**Comment by DevulTj** [comment]
I think this is too niché
