### ISSUE TITLE
Adding gamemode entities from asset party in hammer does not work

### ISSUE THREAD

**Issue by KingOfTheFBI** [sboxgame/issues#2512]
### Describe the bug

Adding game entities from the hammer ent page does not work. It will say it's downloading and then nothing happens when completed.

### To Reproduce

Open Hammer
Entity tool
Click "Add Game"
Add whatever game

### Expected behavior

The game entities are added

**Comment by handsomematt** [comment]
Oops this was only accidentally working before, should be good now.

**Comment by KingOfTheFBI** [comment]
Test
