### ISSUE TITLE
Can't set Entity for PhysicsBody

### ISSUE THREAD

**Issue by Adesii** [sboxgame/issues#2513]
### For?

S&Box

### What can't you do?

Set the Entity on a PhysicsBody.
This is important so that when a trace hits it. It returns the Entity for the PhysicsBody.
But if creating custom PhysicsBodies  it can't find the Entity and just returns Null in traces.

Im creating ClientSide PhysicsBodies for my Floating Origin Game so that the local player can select Entities since the Positions will be different for each player i can't do serverside traces and use ModelEntity.

### How would you like it to work?

Either a Field on the PhysicsBody named `Entity Entity {get;set;}`
or being able to pass the Entity through the Constructor.

### What have you tried?

Nothing really.. since no field is available for it.

I will have to iterate over every custom entity i created and do a comparison with its Physics Body Field, which will be really slow with lots of physicsbodies. especially if i hit a child physicsbody

**Comment by aylaylay** [comment]
When you create your own physics body, they're not linked to an entity so just setting an entity property on a physics body makes no sense.

**Comment by Adesii** [comment]
hmm... yeah probably. Someway to link an custom entity to a custom physics body would be nice tho. So that you can trace the created physics bodies and get your custom entity from it.
