### ISSUE TITLE
Allow System.Security.Cryptography: MD5, SHA1, SHA256 (and possibly other hash algorithms)

### ISSUE THREAD

**Issue by MuffinTastic** [sboxgame/issues#2514]
### For?

S&Box

### What can't you do?

I currently cannot use System.Security.Cryptography in any capacity

### How would you like it to work?

For tools, just add references to the appropriate assemblies
For games, direct whitelisting or maybe some kind of wrapper if there's a security issue

### What have you tried?

Nothing, seems kinda awful to grab something from the web or implement it myself if it's already part of .NET

### Additional context

Apart from these being generally useful, right now I'm particularly wanting SHA1 in the tools context. I'm trying to get two way communication between tool code and game code for some nifty custom live editing stuff, and I feel like the cleanest way to do that would be to have the tool host a websocket server. There's no websocket server in .NET (and even if it did exist System.Net.WebSockets isn't available in tools anyways) so I'm implementing it myself, and the websocket spec specifically requires SHA1 for the initial handshake.

**Comment by handsomematt** [comment]
I've added types from System.Security.Cryptography.Algorithms.dll and System.Security.Cryptography.Primitives.dll which will let you do standard algorithms like MD5, SHA1 etc - anything past that seems excessive.

This is done in both game and tools.

**Comment by handsomematt** [comment]
I also made System.Net.WebSockets available to tool addons

**Comment by MuffinTastic** [comment]
Thanks!
