### ISSUE TITLE
prop_animated active physics simulation

### ISSUE THREAD

**Issue by PixelQubed** [sboxgame/issues#2516]
### For?

S&Box, Hammer

### What can't you do?

I can't have an animated prop with active physics simulation "gravity". This makes it impossible to make what I call a "Consolidated Prop" to upload to _asset.party_. If I want a togglable animation on a physics prop, I would have to separate it into many entities in hammer currently, but this makes it impossible to upload to _asset.party_. Then I would have to upload a particle and a prop_physics separately.

### How would you like it to work?

I would like prop_animated to have a togglable physics option in hammer so you can have animated physics objects in-game without making tons of entities to achieve the same result.

### What have you tried?

I tried doing it all separately, such as having an info_particle_system parented with an ent_button to a prop_physics. This works but with one huge catch. You cant upload it to _asset.party_ and have it a simple setup. This is also just for a particle. If you wanted to create an object that needs active physics and needs animation, you would need to create a custom entity, there for it couldn't be uploaded as a standalone prop on _asset.party_.

### Additional context

I know this is a pretty "niche" use, but I feel it is important for certain situations.

**Comment by robotboy655** [comment]
Can you give example of what exactly you want/are trying to do with this? My concern is physics bodies following the animation (graph), I don't know how stable that would be, or if it will work at all.

Perhaps the asset uploading system needs to be improved to also upload particles the model uses if it doesn't already do that (there's a node that can spawn particles on the model)

**Comment by PixelQubed** [comment]
> Can you give example of what exactly you want/are trying to do with this? My concern is physics bodies following the animation (graph), I don't know how stable that would be, or if it will work at all.
> 
> Perhaps the asset uploading system needs to be improved to also upload particles the model uses if it doesn't already do that (there's a node that can spawn particles on the model)

What I'm trying to do is make a candle togglable so that I can turn it _On_ and _Off_ without requiring me to make a new entity. The way I thought to achieve this was to use 2 animations. _On_ and _Off_. The _On_ animation would have an "act_create_particle_system" to create a particle at an attachment point, and the _Off_ animation would deactivate that particle. This way, I could have the particle upload with the model on _asset.party_ without creating a new gamemode to accommodate an entirely new entity for such a simple purpose.

I guess this could be achieved by allowing map prefabs to be uploaded so you can drag and drop them into Hammer or even in-game and use them as intended in-game with base game logic or hammer logic. This would make making simple logic for entities really simple and allow you to attach them to what the player would see as a model.

Either that or allow basic logic to be embedded into a model for this kind of use case, but I can see that having issues.

Oh, and particles do automatically upload with models to _asset.party_ if used in modeldoc on _animations_ or as _gamedata_ for the object.

Hopefully, that clears up what I'm trying to get at.

**Comment by robotboy655** [comment]
Yeah, that sort of thing is definitely better suited for map prefabs rather than trying to hack around with animations spawning particles.

Besides, even granting you what you want will not solve your problem - you still have to set up the toggling outside of the model itself - in Hammer or in code.
