### ISSUE TITLE
FirstPersonCamera clips through walls near the edges of the display when playing at ultra-wide resolutions

### ISSUE THREAD

**Issue by googleooer** [sboxgame/issues#2517]
### Describe the bug

When playing with an ultra-wide resolution like 2560x1080, the camera clips through walls.

### To Reproduce

1. Play s&box with the resolution set to something with an ultrawide aspect ratio
2. When you're near walls, the camera clips through them 

### Expected behavior

The camera shouldn't clip through walls at ultra-wide resolutions. 

### Media/Files

![Imgur](https://imgur.com/ocu1Oah.png)
![Imgur](https://imgur.com/d9Nk9pG.png)

### Additional context

OS: Windows 11
CPU: AMD Ryzen 5 5600X
GPU: NVIDIA GeForce RTX 3070
RAM: 32GB

**Comment by DoctorGurke** [comment]
This happens on any aspect ratio to a degree, this is just due to the camera nearz. You can change this in your own game.

**Comment by googleooer** [comment]
If that's the case then I really think they should adjust the base nearz, I don't see why someone would want this to be the norm

**Comment by garrynewman** [comment]
Yeah we should really fix this by default

**Comment by robotboy655** [comment]
Defaulted ZNear to 4 as the fallback number (was 10), fixes it for first & third person cameras both.
