### ISSUE TITLE
Widget.MaximumHeight give maximum width.

### ISSUE THREAD

**Issue by DaddyFrosty** [sboxgame/issues#2518]
### Describe the bug

The screenshot says it all. Someone just made a misstake.
Note that this is a issue for both Widget.MinimumHeight & Widget.MaximumHeight.

![image](https://user-images.githubusercontent.com/34773409/200154643-37967a89-88c0-4b69-97c1-3b2f4e5780e8.png)

### To Reproduce

Widget.MinimumHeight = 10;
Log.Info( Widget.MinimumHeight ) != 10;

### Expected behavior

Widget.MinimumHeight => Widget.MinimumSize.y;

**Comment by robotboy655** [comment]
Should be fixed.
