### ISSUE TITLE
Entity.AddOutputEvent doesn't do anything

### ISSUE THREAD

**Issue by rileyzzz** [sboxgame/issues#2519]
### Describe the bug

Entity.AddOutputEvent used to work, however it no longer does anything. I'm assuming this has something to do with the recent timesToFire change.

### To Reproduce

Add an output event to an entity.

### Expected behavior

The StandardOutputDelegate parameter of AddOutputEvent should be called when the output is fired.

**Comment by robotboy655** [comment]
Should be fixed, was not setting timesToFire, so it always ended up 0.
