### ISSUE TITLE
Map Manifest

### ISSUE THREAD

**Issue by PixelQubed** [sboxgame/issues#2522]
### For?

S&Box

### What can't you do?

You cant have multiple maps in one map addon and have them show locally in the games menu. This hinders things like campaigns and also makes mounting multiple addons for each map in a campaign an unnecessary annoyance.

### How would you like it to work?

I would like a map manifest. Something that can define where maps are in one addon, so you don't have to separate them for them to be individually detected. Either that or have them automatically be found when mounting the addon.

### What have you tried?

Individually creating separate addons for related maps. It's both an inconvenience and very annoying.

**Comment by DoctorGurke** [comment]
Map addons suck. Should just be uploaded like any asset.party asset. As far as I know this is already planned, so trying to work around the shittiness of map addons is likely not gonna happen

**Comment by PixelQubed** [comment]
> Map addons suck. Should just be uploaded like any asset.party asset. As far as I know this is already planned, so trying to work around the shittiness of map addons is likely not gonna happen

I thought I would mention it anyway. It makes sense doing it this way for now until the system gets revamped.

**Comment by robotboy655** [comment]
Map addons are no more and are treated as other assets.
