### ISSUE TITLE
Ability to get a Material from a Model

### ISSUE THREAD

**Issue by damienfamed75** [sboxgame/issues#2524]
### For?

S&Box

### What can't you do?

While experimenting to change materials during runtime I noticed that there's no way to get a material from a model already in-game. There's already methods on getting the active Material Group so why not be able to get the Materials from the group?

### How would you like it to work?

If you're making an addon or attempting to support maps that aren't your own, having the ability to get a material from Models within the map can be helpful when trying to slightly alter how certain objects look.

Perhaps there can be a way to get the Materials based on the current Active Material Group such as a method with a signature of:
```csharp
Material[] GetMaterialsFromGroup(int group)
```

### What have you tried?

So far I've just been looking around at the API around ModelEntity, ModelBuilder, Model, Mesh, and Material and haven't found anything to workaround this.

**Comment by aylaylay** [comment]
added
