### ISSUE TITLE
[UI] Ability to Disable Clipping on Background Images

### ISSUE THREAD

**Issue by Fortune117** [sboxgame/issues#2529]
### For?

S&Box

### What can't you do?

I'm trying rotate an image using `transform: rotate(90deg)` but it is clipped as if it were untransformed, see here:

https://user-images.githubusercontent.com/7847372/201001298-d8680cce-8096-44cc-b297-a57fa74cb20f.mp4

### How would you like it to work?

A simple css value such as `background-clipping: none`, or something to that effect, which disables clipping on the background image of the panel.

### What have you tried?

I can alleviate the problem by changing the `overflow` of the panels parents, but then other things start showing outside the container that I don't want.

Ideally, I should be able to mark panels as exceptions.

**Comment by gris-fuego** [comment]
Not familiar with proper CSS/HTML terminology but I believe the issue is that s&box's css implementation is only rotating the drawing, not the box model.

**Comment by handsomematt** [comment]
I think this is just a duplicate of your other issues #1059 #2619 , again it should all be fixed.

**Comment by Fortune117** [comment]
Yep this is fixed now, thanks.
