### ISSUE TITLE
Project Manager: Add from asset.party needs some love

### ISSUE THREAD

**Issue by DevulTj** [sboxgame/issues#2531]
### Describe the bug

There's field validation but nothing is displayed to the end user. We can make that better for sure.

### To Reproduce

1. Open in Editor
2. Open Explorer Tab
3. Add Project from asset.party
4. Observe when trying to add a project to an existing directory
5. Another one is when trying to add a project that you already have installed

### Expected behavior

Should display warnings / errors to the user instead of being hidden, causing confusion

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/201418872-354df5f4-8da3-4af9-8271-fb50f7f9de42.png)
