### ISSUE TITLE
Project Manager: Trying to add project via git (when not installed) gives verbose error

### ISSUE THREAD

**Issue by DevulTj** [sboxgame/issues#2532]
### Describe the bug

Trying to add project via git (when not installed) gives verbose error

### To Reproduce

1. Open Editor
2. Open Explorer
3. Add project from asset.party
4. Observe console error

### Expected behavior

Should describe to the user that git isn't installed - or we should package git ourselves

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/201411534-5515ee2f-0416-46da-9d54-1b7bd8ce055f.png)

This should be nicer.
