### ISSUE TITLE
Shader compiler doesn't handle UTF8 BOM

### ISSUE THREAD

**Issue by MuffinTastic** [sboxgame/issues#2533]
### Describe the bug

Whenever I create a new .vfx in Visual Studio and save, for me it defaults to saving as UTF8 with a BOM. The shader compiler instantly chokes on this and refuses to compile, and I have to choose to save as UTF8 without a BOM every time. Not a showstopper by any stretch but it's annoying

### To Reproduce

1. Create a new .vfx file in Visual Studio, kinda like how there's .vfx files in base/code/PostProcess/ObjectHighlight
2. Copy-paste a working shader into it
3. Save
4. See it fail to compile

### Expected behavior

It should compile as usual.

### Media/Files

Here's a repro .vfx just in case you can't get it to fail for some reason
[this_will_fail.zip](https://github.com/sboxgame/issues/files/9988949/this_will_fail.zip)

### Additional context

BOM-less shader files with unicode text work fine so long as that text is in comments, so even if the compiler doesn't otherwise have proper unicode support and you don't want to bother implementing it, it won't matter as long as you skip the BOM. I think it's fine if we can't have unicode variable names etc

**Comment by ogniK5377** [comment]
should be fixed next update 👍

**Comment by MuffinTastic** [comment]
Yep, works now

**Comment by MuffinTastic** [comment]
This has had a regression since the shader branch merge

**Comment by aylaylay** [comment]
Oops, I'll add this back

**Comment by aylaylay** [comment]
Back in now, sorry for that.
