### ISSUE TITLE
Server Transitions

### ISSUE THREAD

**Issue by SleepyMode** [sboxgame/issues#2539]
### For?

S&Box

### What can't you do?

Transfer players between servers. For example, moving players from a centralized server into an instance.

### How would you like it to work?

Using a function on the `Client` class, e.g.:
```cs
client.Transfer(/*server ip/steam id/et cetera - any option that is valid with the connect concmd*/);
```

Notably, the player should probably be asked if they are willing to connect to the new server before being transferred.

### What have you tried?

Looking up alternatives in the API and open suggestions, as far as I can tell - none are available at the moment.

### Additional context

Following up on https://github.com/sboxgame/issues/issues/2325#issuecomment-1257434307

**Comment by handsomematt** [comment]
#1456
