### ISSUE TITLE
Lists Fail To Network Consistently When Replaced

### ISSUE THREAD

**Issue by anthonysharpy** [sboxgame/issues#2540]
### Describe the bug

The code below will cause the contents of InventoryContents to be different on the server and the client. In particular, as expected, one of the items in InventoryContents will be deleted on both client and server. However, on the client, the wrong item is deleted.

This is probably caused by the replacement of the List through the call to ToList().

```
[Net] public IList<ItemInventoryInfo> InventoryContents { get; private set; }

public void RemoveFromInventory(ItemInventoryInfo item)
{
  InventoryContents = InventoryContents.Where( x => x.UniqueID != item.UniqueID ).ToList();
}
```

The code below has the same behaviour but works properly on both client and server.

```
[Net] public IList<ItemInventoryInfo> InventoryContents { get; private set; }

public void RemoveFromInventory(ItemInventoryInfo item)
{
  var itemToRemove = InventoryContents.Single( x => x.UniqueID == item.UniqueID );
  InventoryContents.Remove( itemToRemove );
}
```

### To Reproduce

See above

### Expected behavior

Should work as expected, or if not supported then should throw a networking error.

**Comment by peter-r-g** [comment]
https://wiki.facepunch.com/sbox/Networked_Types#lists

**Comment by anthonysharpy** [comment]
> Setting it to another List will copy from that list
> Further changes to the original list won't apply to the Networked List

This seems to imply that replacing a [Net] List with a List is supported and should work.

> If <T> is a BaseNetworkable then you cannot exchange them between networked lists

Technically not relevant here I think, since there seems to be only one networked list in this case (the .ToList() List is not a networked List... I guess?). Although I imagine the reason this doesn't work is related to this.

I suspect it's not supported for some reason or another, but if possible I think this should be throwing an error nonetheless, since the result here is very surprising and I lost a good 2+ hours to it.

**Comment by lotuspar** [comment]
if you're using BaseNetworkable give Entity a try

if that works you might have an issue discussed on the discord: https://discord.com/channels/833983068468936704/833983416390385685/1024717895135154196

**Comment by anthonysharpy** [comment]
yeah this seems to be what i'm trying to do

![image](https://user-images.githubusercontent.com/55365296/201535760-5c7c242d-ff8d-47ec-aece-f48f7a72452f.png)

from the sounds of it this sounds like something they hope to improve one day so i'll leave this issue here for now 😛 not making a new list is a good enough workaround for me for now
