### ISSUE TITLE
Hammer Custom Asset Dragging Issue 

### ISSUE THREAD

**Issue by A1steaksa** [sboxgame/issues#2542]
### Describe the bug

When dragging a model out of the Asset Browser in Hammer, some assets don't appear to drag out correctly. They did previously but something has changed that broke the functionality. Some of our models do work and we're not sure why.

### To Reproduce

1. Open S&Box in game dev mode
2. Import a custom, non-animated, model into Model Doc
3. Assign it Archetype "Static Prop Model"
4. Compile it
5. Open Hammer
6. Locate custom model in the asset browser
7. Attempt to drag it directly into Hammers viewport

### Expected behavior

The model should be spawned in Hammer as a static prop

### Media/Files

https://user-images.githubusercontent.com/8369707/201714996-859c1027-91e4-4f9b-873d-e9d23c3cebf6.mp4

**Comment by robotboy655** [comment]
Could not reproduce the "2 layers deep" theory, still works on my end, full path in my test case being `W:\GitHub\sbox\game\addons\rubat\models\props\frames\something\model.vmdl`, `addons\rubat` being a content addon.

**Comment by robotboy655** [comment]
I have noticed symbols ` `, `,` and `;` in the filename/path will cause drag'n'drop to not work so I fixed that.

Id doesn't seem like the filepaths in your video have those, but you can try again and see if the latest changes fix it you.
