### ISSUE TITLE
half of my screen is black

### ISSUE THREAD

**Issue by Stnkyabo** [sboxgame/issues#2545]
![20221116001402_1](https://user-images.githubusercontent.com/83509008/201970971-944537c5-a8aa-4ff6-9535-3f3a797ae075.jpg)
I believe this may have occurred after an update as this was not happening earlier in the day

Tried closing some stuff in the background, entering different gamemodes, playing with all of the video settings... nothing fixed it

This does not effect the UI and some other objects which render properly

**Comment by strongpoint25** [comment]
Same issue here.

**Comment by handsomematt** [comment]
oops, should be fixed next update
