### ISSUE TITLE
Whitelist `ConsoleSystem.GetValue("avatar")`

### ISSUE THREAD

**Issue by timmybo5** [sboxgame/issues#2548]
### For?

S&Box

### What can't you do?

Recently garry removed access to engine convars, would be nice to whitelist just the avatar convar getting, or another easy way to get player clothing clientside (if it already exists then I don't know about it).

![image](https://user-images.githubusercontent.com/4988198/202193260-7a5cfa5b-b691-4089-88c9-a456de329f40.png)

**Comment by handsomematt** [comment]
Sandbox.ClothingContainer will take care of dressing an avatar for you, it uses `cl.GetClientData( "avatar" );`
