### ISSUE TITLE
`say` causes an exception on a dedicated server

### ISSUE THREAD

**Issue by alexavil** [sboxgame/issues#2552]
### Describe the bug

When I try to use `say` on a dedicated server, I get `Generic  Exception when calling command "say"`. Tested on the Sandbox gamemode running Flatgrass.

### To Reproduce

1. Launch a dedicated server and connect to it.
2. Type `say` and any message into the server console.
3. Observe.

### Expected behavior

The server should be able to send messages into chat.

### Media/Files

![image](https://user-images.githubusercontent.com/32246131/202270046-c5d6b18e-3998-4153-a71e-5271e0e01cfb.png)
Client view after executing `say`.

**Comment by ogniK5377** [comment]
Should be fixed next update 👍

**Comment by alexavil** [comment]
Works fine now, thanks!
