### ISSUE TITLE
Time.Now increases by 4 time step durations while calling the Simulate method after adding bot to the game

### ISSUE THREAD

**Issue by Phyksar** [sboxgame/issues#2554]
### Describe the bug

I have a code that makes animation by setting its start time to `Time.Now` and then interpolating values by the differense of start time and `Time.Now` inside a server tick event. I've noticed that several of its first frames gets broken when I add bot to the game. I suppose that `Time.Now` increases by `4 *  Time.Delta` while processing the `Simulate` method because of the logs I've collected:
```csharp
Log.Info($"{Time.Now:n3} | {ServerTickTime:n3} | {Time.Now - ServerTickTime:n3}");
```
```
 10:55:06   2.580 | 2.580 | 0.000
 10:55:06   2.600 | 2.600 | 0.000
 10:55:06   2.620 | 2.620 | 0.000
 10:55:06   2.640 | 2.640 | 0.000
 10:55:06   2.660 | 2.660 | 0.000
 10:55:06   2.680 | 2.680 | 0.000
 10:55:06   > bot_add
 10:55:06   "Clancy" has joined the game
 10:55:06   2.800 | 2.720 | 0.080
 10:55:06   2.820 | 2.740 | 0.080
 10:55:06   2.840 | 2.760 | 0.080
 10:55:06   2.860 | 2.780 | 0.080
 10:55:06   2.880 | 2.800 | 0.080
 10:55:06   2.900 | 2.820 | 0.080
```
I have no idea why it happens and if this is some effect of prediction logic I expect this should be clarified in API why it occurs.

### To Reproduce

The code to reproduce the logs by extending basic game template:
```csharp
partial class Pawn : AnimatedEntity
{
    private float ServerTickTime;

    public override void Simulate(Client client)
    {
        ...
        if (Host.IsServer && !client.IsBot) {
            Log.Info($"{Time.Now:n3} | {ServerTickTime:n3} | {Time.Now - ServerTickTime:n3}");
        }
    }

    [Event.Tick.Server]
    private void ServerUpdate()
    {
        ServerTickTime = Time.Now;
    }
}
```

### Expected behavior

I expect there should be no difference between `Time.Now` in Simulate method and `Time.Now` in server tick event no matter what.

**Comment by kurozael** [comment]
@Phyksar 

I'm actually seeing results like this even without a bot:

```
 06:01:48   Server 14.560 | 14.480 | 0.080
 06:01:48   Server 14.580 | 14.500 | 0.080
 06:01:49   Server 14.600 | 14.520 | 0.080
 06:01:49   Server 14.620 | 14.540 | 0.080
 06:01:49   Server 14.640 | 14.560 | 0.080
 06:01:49   Server 14.660 | 14.580 | 0.080
 06:01:49   Server 14.680 | 14.600 | 0.080
 06:01:49   Server 14.700 | 14.620 | 0.080
 06:01:49   Server 14.720 | 14.640 | 0.080
 06:01:49   Server 14.740 | 14.660 | 0.080
 06:01:49   Server 14.760 | 14.680 | 0.080
```

Infact, I'm seeing the discrepancy reduce after adding a bot:

```
 06:02:19   Server 45.080 | 45.020 | 0.060
 06:02:19   Server 45.100 | 45.040 | 0.060
 06:02:19   Server 45.120 | 45.060 | 0.060
 06:02:19   Server 45.140 | 45.080 | 0.060
 06:02:19   Server 45.160 | 45.100 | 0.060
 06:02:19   Server 45.180 | 45.120 | 0.060
 06:02:19   Server 45.200 | 45.140 | 0.060
 06:02:19   Server 45.220 | 45.160 | 0.060
 06:02:19   Server 45.240 | 45.180 | 0.060
 06:02:19   Server 45.260 | 45.200 | 0.060
 06:02:19   Server 45.280 | 45.220 | 0.060
 06:02:19   Server 45.300 | 45.240 | 0.060
 06:02:19   Server 45.320 | 45.260 | 0.060
```

However, I've managed to keep the discrepancy the same (0.08) whether there is a bot or not by adding a function call that was previously missing.

There are reasons why there might be a discrepancy between `Time.Now` in `Simulate` and in `Tick` and that's related to the tick base for each entity during simulation.

Either way, now you can expect that this will not be affected by a bot's presence on the server 👍

**Comment by Phyksar** [comment]
@kurozael Thanks, I was expecting that the reason of this is some dark magic happening inside a simulation loop. I solved this issue by eliminating interactions with time inside the `Simulate` call and using an event-like approach. I just would like to see this documented and explained in the wiki or the codebase, so this doesn't confuse anyone who's coming across.
