### ISSUE TITLE
C# Code For Map Addons

### ISSUE THREAD

**Issue by GunnarKafel** [sboxgame/issues#2556]
### For?

S&Box, Hammer

### What can't you do?

I can't write code that runs with a map or make custom entities without adding it to a game or extension.

### How would you like it to work?

Like global addons but integrated with the map and Hammer. Custom entities would let me fill in the gaps that base entities and I/O can't achieve. 

### What have you tried?

I can add entities to my own games, but this doesn't help me if I'm making UGC for a game like Gunfight. 

### Additional context

In my Gunfight level I'd like a helicopter flying over the player space with a camera aiming at random players. I'm sure I can find a way to do this with base entities, but it'd be a lot more elegant just to do this with a custom entity.

I'd also like to do post processing effects on a point_camera. This wouldn't be an issue if I was working on my own game, but since it's UGC for Gunfight this isn't possible. I could also make an issue and potentially have the feature added to base, but this means I would have to stop what I'm doing to write the issue and wait for it to get it added. With custom entities I could have already iterated on a few ideas. 

For Office we wanted to make new sound entities. These entities would allow us to play sounds along paths, or at the closest point inside of a volume. Since we were targeting the Sandbox game mode, this wasn't possible.

I also wanted to add a few easter eggs to Office to encourage map exploration, like a padlocked door with a randomly generated code. I'm sure with the base entities I could make a similar system, but it'd be elegant to have 1 or 2 entities that does it all instead of many. This would also allow me to make custom UI for the padlock, which isn't possible without it being an addon.

**Comment by yuberee** [comment]
Would be awesome to have, I've personally abandoned a few projects because they weren't feasable without this.
Like recreating the Sawmill map from Tub for the game Platformer, I had no way to make a treadmill to move players with the current tools:
![image](https://user-images.githubusercontent.com/59583743/202534482-aa78b65a-383f-4ac0-9307-72920f39e80d.png)
I know of other developers that haven't published maps from their games because they would be missing a few key entities.

**Comment by handsomematt** [comment]
This was already on my list, mainly needed justification on if anyone would use it but this all sounds like you really would - thanks for making an issue 😄 

With how I've got packages and meta working on maps already this is relatively simple to implement, so I'll see what I can do.

**Comment by gvarados1** [comment]
yes please ❤❤❤❤❤
I want to make lights that randomly flicker

**Comment by PixelQubed** [comment]
C# (VScript) alternative for S&box, here we come!

**Comment by gvarados1** [comment]
Any idea when this will get in? I want to make an elevator but I would rather code it than use 50 hammer entities

**Comment by handsomematt** [comment]
Basic implementation is in, you can use entities from addons tagged "map entity" in your maps, the addons can't target games but can provide basic entities.

We'll see how well it works, and then I have some ideas on how to make the UX better in Hammer

**Comment by gvarados1** [comment]
This sounds nice! Would be nice if we could upload prefabs to use with the entities
ex. basic elevator prefab to show how the entity works
