### ISSUE TITLE
UI Doesn't Update Properly Anymore

### ISSUE THREAD

**Issue by damienfamed75** [sboxgame/issues#2559]
### Describe the bug

Any UI element that updates often such as the in-game console, a timer, etc. doesn't update correctly anymore.

No matter what you set to a razor BuildHash it just doesn't update correctly.

### To Reproduce

Go to the in-game console and type some commands. Type and delete, you'll see suggestions pop up but no text appears.
This is propagated throughout all the gamemodes on s&box currently.

### Expected behavior

The UI updates when changes happen

### Media/Files

Below is the in-game console not updating while typing

https://user-images.githubusercontent.com/17505288/202586368-25fa41a6-e470-4822-b269-6880c5ad86bd.mp4

Below is my gamemode TerryKing with a timer at the top of the screen. This is a seconds timer and it ONLY updates when I open and close other UI elements. Otherwise it just sits there forever

https://user-images.githubusercontent.com/17505288/202586567-7f042bf8-671a-49a4-9f4a-0b73e86d8179.mp4

**Comment by TheBoxTrot** [comment]
yeah same here my health ui is severely delayed in updating

**Comment by DevulTj** [comment]
This was fixed a few days back
