### ISSUE TITLE
SpeechRecognition sometimes stops listening without sending anything to response

### ISSUE THREAD

**Issue by TheBoxTrot** [sboxgame/issues#2562]
### Describe the bug

sometimes when having SpeechRecognition listening with a list of choices it seems if you say something that isn't on the list sometimes it will stop listening but without sending anything to the response function not even null 

### To Reproduce

setup speech recognition with a list of options 
set it up to a method that says the output and then recalls the speech recognition function
start shouting random crap to your computer that isn't on the list of choices.
 profitand 

### Expected behavior

the function is called with null or the SpeechRecognition just doesn't stop

**Comment by kurozael** [comment]
@TheBoxTrot I've obsoleted SpeechRecognition.Listen and added SpeechRecognition.Start. This will pass a `SpeechRecognitionResult` with the following:

```csharp
/// <summary>
/// From 0-1 how confident are we that this is the correct result?
/// </summary>
public float Confidence { get; set; }

/// <summary>
/// The text result from speech recognition.
/// </summary>
public string Text { get; set; }

/// <summary>
/// Did we successfully find a match?
/// </summary>
public bool Success { get; set; }
```
