### ISSUE TITLE
Sounds don't follow their entity

### ISSUE THREAD

**Issue by Weldify** [sboxgame/issues#2564]
### Describe the bug

`Entity.PlaySound()` and `Sound.FromEntity()` don't follow their entity
![image](https://user-images.githubusercontent.com/66477673/202706189-399780b1-ef36-48b1-a73e-97b56694fc44.png)

### To Reproduce

1. Make a moving entity
2. Play a sound on it

### Expected behavior

The sound should follow the entity

**Comment by DoctorGurke** [comment]
noticing this issue as well now, patching up speed dial. Sounds definitely used to follow the entity but don't anymore

**Comment by DevulTj** [comment]
This is super obvious with footsteps when you've got high ping.
