### ISSUE TITLE
UI Shouldn't scale with viewport size

### ISSUE THREAD

**Issue by Weldify** [sboxgame/issues#2566]
### For?

S&Box

### What can't you do?

Currently UI elements scale with the viewport. So if you have a 16px ui element and youre playing your game in the s&box editor window, itll get scaled down to like 8-10px which makes it look like shit.

I feel like UI shouldn't scale with the viewport at all, but it might be useful for someone, so making an option to toggle it on or off would be better.

### How would you like it to work?

A button here perhaps?
![image](https://user-images.githubusercontent.com/66477673/202716089-65d64e32-9bb5-46dc-8586-89c321115646.png)

### What have you tried?

![image](https://user-images.githubusercontent.com/66477673/202716243-f9bf68a3-762c-4cc4-b68f-f8b0373ae648.png)
You can change your viewport resolution here to match your screen resolution, but it affects everything and as such will chop half of your game off:
![image](https://user-images.githubusercontent.com/66477673/202716761-526eabb4-52e0-442e-aeec-d16dfb2eb849.png)
(i have the menu open in this screenshot)

**Comment by handsomematt** [comment]
It's specifically designed to scale with the viewport, if you want to turn it off for your game you can override [Sandbox.UI.RootPanel.UpdateScale(Rect)](https://asset.party/api/Sandbox.UI.RootPanel.UpdateScale(Rect)).

If you want to draw a crosshair the best approach is using [Sandbox.Graphics](https://asset.party/api/Sandbox.Graphics) within [Game.RenderHud()](https://asset.party/api/Sandbox.GameBase.RenderHud())
