### ISSUE TITLE
Teleport Volume Input to Set Remote Destination

### ISSUE THREAD

**Issue by GunnarKafel** [sboxgame/issues#2568]
### For?

Hammer

### What can't you do?

I can't set the Remote Destination of a Teleport Volume through Hammer I/O.

### How would you like it to work?

Teleport volumes should have an input that sets the remote destination entity. 
![image](https://user-images.githubusercontent.com/65134886/202776632-d4f63427-cef1-4b8d-a592-3f145cf72c8e.png)

### What have you tried?

I can use multiple teleports overlapping the same space and turn them on/off, but this feels messy

**Comment by ogniK5377** [comment]
Should be good now 👍 

https://user-images.githubusercontent.com/25727384/202831168-309d6ce1-5ed4-4d31-bdc1-0b1e5cdce111.mp4
