### ISSUE TITLE
Editor "Edit" Toolbar Doesn't Open

### ISSUE THREAD

**Issue by a1steaksa** [sboxgame/issues#2572]
### Describe the bug

When trying to access the "Edit" toolbar menu, it fails to open.

### To Reproduce

1. Launch the editor via Steam
2. Click the "Edit" toolbar
3. Error in console: `QWindowsWindow::setMouseGrabEnabled: Not setting mouse grab for invisible window QWidgetWindow/'QMenuClassWindow'`

### Expected behavior

The edit toolbar should open.

### Media/Files

![image](https://user-images.githubusercontent.com/8369707/202864955-6bfc5e98-a733-4c7b-a242-f8f328809325.png)

### Additional context

I have a gamemode code error that happens whenever the project opens due to some code left broken.  Might be related.

The issue also happens when other toolbar menus are already opened and you hover over the Edit menu option.  It doesn't break the hovering for other menus, so nothing else seems to break other than the Edit menu.

**Comment by DevulTj** [comment]
It's a placeholder, this won't happen when we add stuff to the toolbar
