### ISSUE TITLE
Select gamemode button doesn't appear if description is too long

### ISSUE THREAD

**Issue by matekdev** [sboxgame/issues#2575]
### Describe the bug

If your description for your game is too long, the cancel/select button won't appear (even if you scroll).

### To Reproduce

1. Create a game with a long description
2. Notice that the buttons aren't there

### Expected behavior

The buttons should be there. 

### Media/Files

![image](https://user-images.githubusercontent.com/32153021/203123427-d5cd8a16-a20e-40f7-93ad-576ec4820de1.png)

**Comment by ogniK5377** [comment]
Should be good next update
