### ISSUE TITLE
Invite to Party from current game

### ISSUE THREAD

**Issue by kythre** [sboxgame/issues#2576]
### For?

S&Box

### What can't you do?

I'm unable to.... click the "plus" button for my party and select someone from my current game

### How would you like it to work?

I would like the plus button to show epic gamers that are in also in my currently occupied server

### What have you tried?

I have tried... clicking the dumb little plus button and also doing a minor and quick search of other feature requests

**Comment by DevulTj** [comment]
not super relevant anymore with new menu flow
