### ISSUE TITLE
`ConCmd.Server` calls the wrong method when using overloads

### ISSUE THREAD

**Issue by Fortune117** [sboxgame/issues#2577]
### Describe the bug

I have two methods marked as `ConCmd.Server` with the following signatures:
``` CS
[ConCmd.Server]
public static void RequestEquipItem(int equipmentID, int itemID, SlotID slotID) //<-- method 1
{
    //do stuff
}

[ConCmd.Server]
public static void RequestEquipItem(int equipmentID, int itemID) //<-- method 2
{
    //do stuff mark 2
}
```

Clientside, I'm calling the method like this: 
```CS
ServerInventoryManager.RequestEquipItem(GearSlot.Equipment.NetID, itemPanel.Item.NetID, GearSlot.SlotID);
```

This should be calling method 1, but results in a call to method 2.

### To Reproduce

1. Create two `ConCmd.Server` methods with signatures like I described (SlotID is an enum)
2. Call the first method from client.
3. See the second method is called.

### Expected behavior

Calls the correct method

**Comment by peter-r-g** [comment]
This wouldn't make sense to work I don't think. You're calling a console command of which only one will exist. So the one that was defined last is the one that is called. There would be no concept of overloads on commands (unless they add support for that?).

**Comment by DevulTj** [comment]
We should probably have the game moan a bunch when you try to do something like this

**Comment by Fortune117** [comment]
Yeah I don't mind changing method names, figured I'd make an issue about it though. Although, since the console commands aren't named I assumed they'd be based on the method somehow.

**Comment by peter-r-g** [comment]
> Yeah I don't mind changing method names, figured I'd make an issue about it though. Although, since the console commands aren't named I assumed they'd be based on the method somehow.

Not passing a name to the `ConCmd.Server` attribute will default the command name to the method's name, which is your problem. You could get away with it in code by just creating two random command names in the attributes. That way, to your code it looks like two overloads on a single command. Then on the console side, it shows two different commands.

**Comment by DevulTj** [comment]
We'll support this
