### ISSUE TITLE
Associate razor files with cs files, just like html and scss

### ISSUE THREAD

**Issue by DoctorGurke** [sboxgame/issues#2580]
### For?

S&Box

### What can't you do?

Currently, scss and html files are automatically put in a filetype association via the auto-generated csproj, this displays the related files underneath the main cs file in a hierarchy. This would be neat for razor too.

![Code_DO2Wh2ujTh](https://user-images.githubusercontent.com/12602100/203637454-40e215b0-12cd-4a81-bd91-20081aa85f38.png)

### How would you like it to work?

I assume this just needs to be supported by the project generators on the editor side

### What have you tried?

N/A

**Comment by DevulTj** [comment]
Gave this a quick look, because it'd be cool, but `<AdditionalFiles Include="**/*.razor" />` takes precedent and without it VS doesn't recognize any of the razor types.
