### ISSUE TITLE
Change to Editor Console Filtering

### ISSUE THREAD

**Issue by a1steaksa** [sboxgame/issues#2581]
### For?

S&Box

### What can't you do?

Currently, the info/warning/error filtering options in the editor can be confusing and annoying to use for a couple of reasons:
- Non-destructive filtering options are presented nearly identically next to buttons that take irreversible action (Clearing the console)
- The info filtering option's current color scheme makes it appear disabled/unavailable even when enabled/available because of the relatively dark gray color used as compared to the lighter color on the clear and save buttons.

### How would you like it to work?

I'd like there to be a delineation between what is filtering options and what is action-taking buttons, as well as a brightening of the info icon to prevent confusion around whether or not it's disabled.

Currently, this is how the section looks.  Note that all filtering options are enabled and the leftmost icon appears much darker than other gray icons.
![image](https://user-images.githubusercontent.com/8369707/203642486-a52fdd1a-25b7-4b24-9a63-c655f18ac9e2.png)

I've made a quick mockup of roughly what I'm imagining:
![ProposedConsoleFilterChange](https://user-images.githubusercontent.com/8369707/203642714-e1074bac-e77d-4f41-ad77-d67d692e3066.png)

### What have you tried?

N/A

**Comment by a1steaksa** [comment]
While we're on the topic, it would be nice if there was an option to filter all messages for things like what namespace they come from, or by project, etc.

When trying to chase down an error, I often want to make the rest of the codebase shut up so I can focus on just the messages that matter to me.  Being able to filter by message source in addition to message severity would be great for debugging

**Comment by robotboy655** [comment]
![](https://files.facepunch.com/rubat/1b2511b1/A0aAcWaH3M.png)

**Comment by a1steaksa** [comment]
Outrageous
