### ISSUE TITLE
Option on prop_static to toggle whether it gets merged with other geometry or not upon map compile

### ISSUE THREAD

**Issue by QuackCocaine** [sboxgame/issues#2582]
### For?

Hammer

### What can't you do?

Currently, you cannot disallow a prop_static entity to be merged with other geometry when the map is compiled.

This could be problematic for these use cases as pointed out by Delta & DoctorGurke on the Discord server.

https://discord.com/channels/833983068468936704/837029412892442654/1044451779812790324
https://discord.com/channels/833983068468936704/837029412892442654/1045075313849282611
 
![Discord_LoHemdSsJs](https://user-images.githubusercontent.com/23345567/203643275-7ecd62e2-f671-400f-ab52-f1628c4bb480.png)

![Discord_PmOf6AqQ6P](https://user-images.githubusercontent.com/23345567/203643561-a5a7a890-e0aa-4ded-a7a1-72b6eef8a8dd.png)

### How would you like it to work?

A toggleable option like in DeskJob/Dota2 hammer called `Disable Mesh Merging` to toggle whether a prop_static is kept separate,  and unmodified from other prop_statics/map geometry or not. 

![deskjob_CIpqgX6md1](https://user-images.githubusercontent.com/23345567/203623489-7d7f976a-28a3-457c-a064-fabc891b5f3f.png)

of course, this would only function when `Bake To World` is checked

### What have you tried?

Nothing, as this isn't a feature in s&box hammer.

**Comment by aylaylay** [comment]
This setting has been added

**Comment by QuackCocaine** [comment]
tested it a while ago and works as expected, just forgot to close this 😅
