### ISSUE TITLE
Style Inspector in the UI Inspector

### ISSUE THREAD

**Issue by Xenthio** [sboxgame/issues#2583]
### For?

S&Box

### What can't you do?

Can we get a style inspector in the ui inspector? it would make finding what overrides what in the scss easier aswell as maybe editing on the fly too

### How would you like it to work?

similar to the one in chrome, Right Click > Inspect Element
![image](https://user-images.githubusercontent.com/28588188/203677055-c9411fc8-25d1-471d-b249-f6ea0a91e29e.png)

### What have you tried?

Why is "What have you tried?" a required section that's dumb.

**Comment by DoctorGurke** [comment]
you can sorta do this by changing the classes property of panels in the inspector, but that kinda sucks and I've only used it a few times when debugging. Some more tools for specifically debugging panel styles would be awesome

**Comment by DevulTj** [comment]
A form of this has been implemented
