### ISSUE TITLE
Maps/Addons Don't Autosave Outside of Steamapps/common/sbox/addons

### ISSUE THREAD

**Issue by gvarados1** [sboxgame/issues#2585]
### Describe the bug

Maps & Addons that are saved outside of Steamapps/common/sbox ( /addons? ) do not autosave
This is an especially big issue because the _default location_ to save addons is outside of this folder.

### To Reproduce

1. Save an addon outside of Steamapps/common/sbox ( /addons? )
2. Doesn't autosave

The default autosave location is steamapps\common\sbox\.source2\autosave

### Expected behavior

Autosave should work

### Additional context

If they do autosave, it's outside of the default autosave folder and I can not find it

**Comment by handsomematt** [comment]
![image](https://user-images.githubusercontent.com/1388267/203791571-e00899b4-6ef3-4956-9112-8a4cf39e61ca.png)

Weird, they end up relative to the game directory. I'll sort it.

**Comment by handsomematt** [comment]
They'll save in .source2/autosave now
