### ISSUE TITLE
Properties in the API search results don't always match with the documentation

### ISSUE THREAD

**Issue by brecert** [sboxgame/issues#2586]
### Describe the bug

When searching the API, property accessors may not always match between the search result and the result page.

### To Reproduce

Search GameIdent, note the result `Sandbox.Global.GameIdent { get; set; }`.
Go to the documentation page for `Sandbox.Global.GameIdent` and note `static string GameIdent { get; }`.
The accessor `{ get; set; }` differ between the two.

### Expected behavior

Poperty accessors should be consistent between search results and the documentation page.

### Media/Files

![Search Results](https://user-images.githubusercontent.com/11599528/203826010-575ac679-9838-4767-83a6-5ce5f8fa756e.png)
![Documentation Page](https://user-images.githubusercontent.com/11599528/203826056-2b44480b-5aaf-42e0-87f8-64081b325855.png)

**Comment by robotboy655** [comment]
Should be fixed.

![image](https://user-images.githubusercontent.com/3299036/204033257-b22f6dca-01d0-4196-a650-70b2e01bec60.png)
