### ISSUE TITLE
Typo in "Dependencies" submenu in Asset viewer

### ISSUE THREAD

**Issue by trundler-dev** [sboxgame/issues#2589]
### Describe the bug

Currently, the Dependencies submenu in the Asset viewer is misspelled as "Dependancies".

### To Reproduce

1. Open an asset
2. Notice the "Dependancies" typo

### Expected behavior

It should say Dependencies instead.

### Media/Files

![image](https://user-images.githubusercontent.com/57276947/203876279-43905e94-7f1d-4ad5-b8d3-ec208e189fc6.png)

**Comment by robotboy655** [comment]
Fixed.
