### ISSUE TITLE
HitBoxes don't work if no parent bone set

### ISSUE THREAD

**Issue by TheBoxTrot** [sboxgame/issues#2592]
### Describe the bug

![image](https://user-images.githubusercontent.com/29888245/203934345-fc665a41-2e8f-46cf-9af3-e71edfe5c0fa.png)
this works

this wont 
![image](https://user-images.githubusercontent.com/29888245/203936006-1f414b54-527d-4ccc-8df5-5c5717d4a566.png)

### To Reproduce

create a model with a hitbox and don't have a bone to attach to

### Expected behavior

if no bone is set the parent bone should just be set to the root of the model

**Comment by aylaylay** [comment]
What doesn't work about it? Both images are the same.

**Comment by aylaylay** [comment]
Should be fixed when the game next updates.
