### ISSUE TITLE
Resources don't save floats marked with `Range` unless edited first

### ISSUE THREAD

**Issue by Fortune117** [sboxgame/issues#2594]
### Describe the bug

I have a `GameResource` with a list of structs that look like this:
```CS
public struct LootTableEntry
{
    [Range(1, 1000)]
    public float Weight { get; set; }
    public ItemResource ItemResource { get; set; }
}
```
They appear in the editor window properly like this:
![image](https://user-images.githubusercontent.com/7847372/204072215-dd578bc5-3087-441c-b85d-6efc6c778fc1.png)

It displays the value for weight as 1 in the editor window, but it doesn't actually save that value anywhere:
![image](https://user-images.githubusercontent.com/7847372/204072237-7e62ae4a-c7f2-411e-97fd-0f30add0fd58.png)

### To Reproduce

1. Create a struct with a float marked with `Range(1, 1000)`.
2. Create a game resource with a `List<MyStruct>` and add some of em
3. See that the default value is not saved.

### Expected behavior

Displayed value is what the resource is saved with

**Comment by robotboy655** [comment]
Are you certain it's an issue with the Range attribute, and not the fact that JSON exporter (probably) doesn't export default values? Does it work like you expect it to specifically without the attribute?

**Comment by Fortune117** [comment]
> Are you certain it's an issue with the Range attribute, and not the fact that JSON exporter (probably) doesn't export default values? Does it work like you expect it to specifically without the attribute?

Without the range attribute it displays the value of Weight as 0 if you don't edit it, and that's what it is when you use the game resource in code.

With the `Range` attribute, you can see that the editor displays the value of Weight as the minimum of the range, which is 1.

But if you then save the resource without changing the weight at all, it doesn't actually write a value for it, causing it to be 0 when evaluated in code, despite the editor showing 1 as its value.

**Comment by robotboy655** [comment]
Should be fixed when the game next updates. Was an issue with the bind system.
