### ISSUE TITLE
Texture.CreateArray shouldn't be deprecated

### ISSUE THREAD

**Issue by rileyzzz** [sboxgame/issues#2595]
### Describe the bug

Currently, Texture.CreateArray is marked as obsolete, and says to use Texture.CreateVolume instead.
However, 2d texture arrays and 3d texture volumes are not the same thing - Texture.CreateArray is something that needs to exist.
Additionally, it seems like the implementation of Texture.CreateArray might be broken. The decompiled C# for CreateArray shows that it doesn't actually set its Depth parameter, even though it's an argument.
If I try to work around that by using WithSize, I get a D3D out of memory error when creating the texture, suggesting that the C++ implementation is broken.

### To Reproduce

Try using Texture.CreateArray to create a texture.

### Expected behavior

Texture.CreateArray shouldn't be deprecated, and it should work as expected.

**Comment by robotboy655** [comment]
The whole material creation API needs redoing as it's a copy paste mess right now, but please do tell what the difference is between arrays and 3D textures.

**Comment by DoctorGurke** [comment]
mip maps will behave differently with 3d textures vs 2d texture arrays. For 3d textures, width, height AND depth decrease with mip levels, 2d texture arrays will retain their depth

**Comment by rileyzzz** [comment]
Exactly. Additionally, 2d texture arrays have completely different resource limits in dx11. Looking at the dx docs, it seems 2d texture arrays can have their width and height go up to 16384, whereas for 3d textures the u/v/w components are limited to 2048 (the benefit of 3d textures being the ability to sample between two layers).
If you'd prefer to have a `WithLayers` parameter in TextureBuilder or an `AsTextureArray` parameter in Texture3DBuilder, then that's fine by me lol. But the option for us to create one needs to be there if
A) there's a clear difference between them in directx, in both functionality and creation through the dx11 API, and
B) the shader API already supports CreateTexture2DArray.

**Comment by handsomematt** [comment]
It should work good now, I've unobsoleted it and hooked up the count. Let me know how it functions
