### ISSUE TITLE
SetModel Before Spawn Error Message Outdated

### ISSUE THREAD

**Issue by a1steaksa** [sboxgame/issues#2596]
### Describe the bug

The error message for calling `SetModel` before `Spawn` links to https://wiki.facepunch.com/sbox/warning-pre-spawn which is not a valid wiki page.

If there's a wiki page that explains the correct lifecycle of an Entity/ModelEntity, that would be a great replacement

### To Reproduce

1. Create an entity class using the code included below.
2. Spawn the entity.

### Expected behavior
Either a fixed link, or a description that clarifies that `Spawn` will be called automatically and is where `Entity` setup code should go

### Media/Files

![image](https://user-images.githubusercontent.com/8369707/204106183-4710db3c-66da-4fb6-8015-aa6b3111489b.png)

"SetModel" was called before Spawn. You should only call this during or after Spawn is called. [https://wiki.facepunch.com/sbox/warning-pre-spawn]

```csharp
class TestEntity : ModelEntity {
    public TestEntity() {
        SetModel( "anything" );
    }
}
```

**Comment by DoctorGurke** [comment]
do you just want the link/page to be fixed? your stated expected behavior just seems to be reproduction steps again

**Comment by a1steaksa** [comment]
Of note: The phrasing of the error is just barely unclear enough to warrant a link to some page.  If the error was slightly more clear about the fact that `Spawn` is a method that will be called automatically when the entity spawns and should be largely used for constructor-y things, you may not need the link at all.

**Comment by a1steaksa** [comment]
> 

Good catch.  I've updated the issue.

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/204321808-c2915eb2-81b8-47b5-aa0c-1f6a04fd9ae0.png)

Is this better?

**Comment by a1steaksa** [comment]
Yeah, I think that's more clear on what's causing the issue and what would fix it.  Thanks!
