### ISSUE TITLE
Serializing a list of classes only serializes the base class properties

### ISSUE THREAD

**Issue by Remscar** [sboxgame/issues#2597]
### Describe the bug

I have some classes as such:

```
public class EntityPlacement
{
    public string EntityClassName { get; set; }
    public Vector3 Position { get; set; }
}

public class RotatedEntityPlacement : EntityPlacement
{
    public Rotation Rotation { get; set; }
}

public class ZombieSpawnerPlacement : EntityPlacement
{
    public float SpawnRadius { get; set; }
}
```

I create a list of entity placements `List<EntityPlacement>` and serialize as JSON `Sandbox.FileSystem.Data.WriteJson(GetFileName(), placements);`

The resulting JSON will not have derived classes properties, it will only serialize the list as if it was `EntityPlacement` even if the list contains instances of derived classes.

```
[
  {
    "EntityClassName": "zw_zombie_spawner",
    "Position": "462.0955,1374.664,-30.9943"
  }
]
```

### To Reproduce

Use the above classes, create a list with some derived classes, serialize.

### Expected behavior

The serializer should serialize the elements in the list as the class which they are, not the base class which the list is of.

Ie; `Rotation` and `SpawnRadius` should be serialized out.

```
[
  {
    "EntityClassName": "zw_zombie_spawner",
    "Position": "462.0955,1374.664,-30.9943",
    "SpawnRadius": 150
  }
]
```

### Additional context

I have ran the code with a debugger and verified that there is derived classes in the `List`.

**Comment by Remscar** [comment]
This apparently is not supported in .NET 6, but is in .NET 7;
https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/polymorphism?pivots=dotnet-6-0
https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/polymorphism?pivots=dotnet-7-0#polymorphic-type-discriminators

**Comment by robotboy655** [comment]
We have updated to .NET 7 and you can now do this like so:
```csharp
[JsonPolymorphic( UnknownDerivedTypeHandling = JsonUnknownDerivedTypeHandling.FallBackToBaseType)]
[JsonDerivedType(typeof(ZombieSpawnerPlacement), typeDiscriminator: "zambie")]
[JsonDerivedType(typeof(RotatedEntityPlacement), typeDiscriminator: "rotated")]
public class EntityPlacement
{
	public string EntityClassName { get; set; }
	public Vector3 Position { get; set; }
}

public class RotatedEntityPlacement : EntityPlacement
{
	public Rotation Rotation { get; set; }
}

public class ZombieSpawnerPlacement : EntityPlacement
{
	public float SpawnRadius { get; set; }
}

[ConCmd.Server]
public static void test_json()
{
	List<EntityPlacement> placements = new();

	placements.Add( new EntityPlacement() { EntityClassName="base class" } );
	placements.Add( new ZombieSpawnerPlacement() { SpawnRadius = 13.37f, EntityClassName="zambie" } );
	placements.Add( new RotatedEntityPlacement() { Rotation = Rotation.Identity, EntityClassName="rotated zomb" } );

	Sandbox.FileSystem.Data.WriteJson( "json_test.json", placements );
	var readStuff = Sandbox.FileSystem.Data.ReadJson<List<EntityPlacement>>( "json_test.json" );

	foreach( var item in readStuff )
	{
		Log.Warning( $"Got item {item}" );
	}
}
```

I did try to make it work automagically through `Sandbox.Json` but I don't think I can get that in the game until a painday. 

I am also not even sure if I should, I do not like the attribute juggling in the "proper .NET 7" approach, but maybe we should keep it that way.

**Comment by Remscar** [comment]
Fixed with .NET 7 update
