### ISSUE TITLE
`Sandbox.Json.Serialize`

### ISSUE THREAD

**Issue by Remscar** [sboxgame/issues#2598]
### For?

S&Box

### What can't you do?

I want to serialize a C# class into a string.

### How would you like it to work?

I call `Sandbox.Json.Serialize(object source)` which returns a `string`

### What have you tried?

Writing to a file by serializing an object as json and then reading it as text.

### Additional context

This could make web socket communication easier (if we had json payloads inside of it) and would also allow you to serialize to json and then write to file as text (if you want.)

Could we just have https://www.newtonsoft.com/json included?

**Comment by Adesii** [comment]
you can use System.Text.Json.JsonSerializer.Serialize

**Comment by robotboy655** [comment]
Sandbox.Json just handles Resource and GameResources automagically for you, otherwise just use `System.Text.Json.JsonSerializer`.

**Comment by Remscar** [comment]
Thank you! Closing the issue.
