### ISSUE TITLE
ModelDoc Compilation with Base Model Recursion Locks Computer

### ISSUE THREAD

**Issue by A1steaksa** [sboxgame/issues#2600]
### Describe the bug

If you set a modeldoc file to have itself as a base model, it locks your computer and the CPU/GPU spin up significantly.  On our end it had to be shut down via the switch.  The original file was recoverable if you deleted the output model, otherwise the same thing would happen again.

### To Reproduce

1. Create a new model in model doc
2. Add some mesh to it
3. Save it
4. Set the base model to the saved file
5. (_Don't_) Click compile

### Expected behavior

It should not let you set the base model to the same file or anything containing that file.

**Comment by a1steaksa** [comment]
"Hey, check if this tree is cyclic" is more or less what I'm asking
