### ISSUE TITLE
Global.GameIdent has `#local` substring appended to it when testing locally.

### ISSUE THREAD

**Issue by Ephememory** [sboxgame/issues#2605]
### What it is?

Results vary when running games locally vs published since GameIdent has `#local` appended to it.

### What should it be?

It would be nice if this were handled differently, maybe by just slicing off the "#local" suffix when S&box knows we are running a local Game for us so we don't have to ```Replace( "#local", "" )``` everywhere in in our code that references the `GameIdent` ourselves.

Real world example:
```cs
var queryResult = await Package.FindAsync( $"type:map game:{Global.GameIdent.Replace( "#local", "" )}", take: 99 );
```
Would be much better if we didn't have to worry about differences like that when running locally vs live.

**Comment by matekdev** [comment]
Personally, it probably should never include the `#local` inside the ident. I don't see why this should behave different when running on local vs. a non local build.

**Comment by DoctorGurke** [comment]
Knowing whether or not you're on the local version of a game itself can totally be benefitial. Having a Dev version of a websocket connection for testing stuff in-dev for example.

**Comment by matekdev** [comment]
> Knowing whether or not you're on the local version of a game itself can totally be benefitial. Having a Dev version of a websocket connection for testing stuff in-dev for example.

I agree that it is useful, but that information shouldn't be contained in the game indent. It should be moved to some other API that would be more obvious. I don't think people will look at `Global.GameIndent` and their thought would be, oh hey, this is how I determine whether or not I'm running a local build.

**Comment by Ephememory** [comment]
Yeah I completely agree with both of you. I was originally going to suggest an addition of something like `Game.IsLocalAddon`

**Comment by DevulTj** [comment]
#local is appended on purpose. I don't see a benefit of having Game.IsLocalAddon.
