### ISSUE TITLE
HammerEntity BoundsHelper attribute cannot extend past entity center

### ISSUE THREAD

**Issue by A1steaksa** [sboxgame/issues#2606]
### What it is?

Currently there is no native way to add a BoundsHelper for a volume that does not contain the Entity's origin

For example, I cannot move the bounds any further away here: 
![image](https://user-images.githubusercontent.com/8369707/204155393-e584f338-420f-40fd-828c-c601b737c648.png)

### What should it be?

The BoundsHelper should be able to move arbitrarily relative to the "owning" Entity.  It would also be nice to have the option to switch from local to global position.

**Comment by a1steaksa** [comment]
That is what is allowing the above screenshot to be anywhere other than directly centered on the entity, so it still constrains it to the entity even with autocenter off, which unfortunately doesn't solve the issue
