### ISSUE TITLE
Allow drawing custom helpers in Hammer

### ISSUE THREAD

**Issue by Adesii** [sboxgame/issues#2607]
### For?

S&Box, Hammer

### What can't you do?

currently we are limited to the existing Attributes like BoundsHelper,Axis etc.

But it would be nice if there is a way to expose Rendering per Entity to allow drawing custom helpers even in packaged Gamemodes from Asset Party.

### How would you like it to work?

Something like  Event.Hammer.Draw/Selected
which gets ran inside of hammer and allowing the use of DebugOverlay methods or drawing to the Hammer scene with custom SceneObjects for example. but just DebugOverlay would already be fantastic.

Another nice to have would be to add custom gizmos that can be linked to Properties using a binding system.
like a Axis Gizmo linked to a specific Vector Property etc.

### What have you tried?

you can do something similar using Tool Addons already but that would require a seperate addon and does not allow to share these with Uploaded Gamemodes.

**Comment by handsomematt** [comment]
We have this now with Entity.DrawGizmo 😄
