### ISSUE TITLE
Texture Settings do not apply any more in the Material Editor

### ISSUE THREAD

**Issue by justyn0** [sboxgame/issues#2608]
### Describe the bug

When trying to change anything to a texture using the Texture Settings window. It does not apply any of the settings anymore.

### To Reproduce

- Open up an material that has textures
- Under any texture entry, under the file path click the gear icon. This would open up the Texture Settings window
- Change any setting in the Texture Settings window
- Click "Accept"

### Expected behavior

Nothing would be applied

### Media/Files

https://user-images.githubusercontent.com/17112771/204161305-2c65a03e-c31d-40e6-9966-d55ed93ac698.mp4

**Comment by aylaylay** [comment]
Do you know when this was last working?

**Comment by aylaylay** [comment]
Should be fixed when the game next updates

**Comment by justyn0** [comment]
Seems to be fixed now! Thank you!
