### ISSUE TITLE
Ability to move assets to different folders in asset browser

### ISSUE THREAD

**Issue by TheBoxTrot** [sboxgame/issues#2610]
### For?

S&Box

### What can't you do?

select an asset and drag it into a folder and have that asset now in that folder

### How would you like it to work?

as described above

### What have you tried?

have to open up the system file explorer to do it

### Additional context

this isn't exactly a required feature but its just a bit weird that you can create folders within the asset browser but you have to use your system file browser to do anything with those folders

**Comment by xezno** [comment]
Fixed this a while ago with #3183 and forgot to mention it (sorry)!

**Comment by TheBoxTrot** [comment]
One thing ive noticed is that if you move an asset to a new folder it leaves the compiled version behind. if its possible maybe having it move both the source and the compiled version together when available or deleting the compiled version. just annoying having to delete a bunch of compiled-only files everytime you move something.
