### ISSUE TITLE
Create Particle Snapshots At Runtime

### ISSUE THREAD

**Issue by GunnarKafel** [sboxgame/issues#2613]
### For?

S&Box

### What can't you do?

I can't create a particle snapshot through C# then apply it to a particle system.

### How would you like it to work?

I'd like to be able to build a snapshot through code, then pass it through a particle's SetSnapshot method

```
var snapshot = new ParticleSnapshot();

var point = new SnapshotVertex();
point.Position = Vector3.Zero;
point.CreationTime = 1f;
point.Normal = Vector3.Up;

snapshot.AddVertex(point);

particle.SetSnapshot(0, snapshot);
```

### What have you tried?

I've tried using control points, but it's not very scalable with large particle counts.

### Additional context

Half-Life Alyx uses these runtime snapshots for the Reviver storm and toner puzzle paths. 

Reviver Storm:
https://streamable.com/8gdnrc
https://streamable.com/e0femp
![hlvr_99EtUoUsGB](https://user-images.githubusercontent.com/65134886/204434084-fc24473c-ab54-40fe-b8e7-ad2ba6f24dd3.jpg)

Toner Puzzle:
![image](https://user-images.githubusercontent.com/65134886/204435021-26e431d1-51f0-4dde-99bc-20de9ed94bf8.png)
![20221128231752_1](https://user-images.githubusercontent.com/65134886/204438120-ce1856a5-6883-400f-ba2a-67798174cbe1.jpg)
![image](https://user-images.githubusercontent.com/65134886/204435076-c7b95951-4497-4094-908c-89550ea93365.png)

**Comment by aylaylay** [comment]
Hey that's not a bad idea

**Comment by aylaylay** [comment]
Merged this in, please test it and let me know if it works as expected.

**Comment by GunnarKafel** [comment]
Works perfectly, thank you!
