### ISSUE TITLE
Allow changing the order of settings in Project Settings

### ISSUE THREAD

**Issue by Fortune117** [sboxgame/issues#2614]
### For?

S&Box

### What can't you do?

I want to change the order of my settings in the Project Settings menu, but they're fixed in place.

### How would you like it to work?

Allow you to drag the settings around in this little box to determine their order.
![image](https://user-images.githubusercontent.com/7847372/204455872-06d8a60b-eff9-48d9-8cc5-012d32791f32.png)

### What have you tried?

You can just delete and remake the setting if you want to change the order but that's pretty tedious.

**Comment by DevulTj** [comment]
Right click it, Move Up / Move Down

**Comment by Fortune117** [comment]
> Right click it, Move Up / Move Down

Excellent, thanks! :D Probably should of tried that first, woops.
