### ISSUE TITLE
Metallic textures do not work in SceneWorlds

### ISSUE THREAD

**Issue by timmybo5** [sboxgame/issues#2615]
### For?

S&Box

### What can't you do?

I cannot get my metallic textures to display properly in custom SceneWorlds due to a missing env map. The env map gets created by the EnvironmentLightEntity but there is no way for me to add one to my SceneWorld.

## Current
![image](https://user-images.githubusercontent.com/4988198/204539683-51704de5-df96-4b5d-af00-03d5737df7bb.png)

## Desired
![image](https://user-images.githubusercontent.com/4988198/204539815-46563f4b-fa84-4130-938a-b5a14ec5e1a5.png)

**Comment by aylaylay** [comment]
I have added SceneCubemap. To get reflections to show up, add one of these to the scene and make sure your scene camera has some ambient lighting set
