### ISSUE TITLE
Tools in a Game project

### ISSUE THREAD

**Issue by gio3k** [sboxgame/issues#2616]
### For?

S&Box

### What can't you do?

Have tool code in a gamemode without separating them

I'd like to make Hammer tools / editors just for the specific gamemodes they would be used for

### How would you like it to work?

Allow tool code in gamemodes

### What have you tried?

Putting tool code in a gamemode (did not work)

**Comment by LeQuackers** [comment]
Wouldn't #2228 solve this? Why don't you want to separate them?

**Comment by Adesii** [comment]
This sounds like a bad idea.. since tool addons dont have a whitelist you are able to do anything in c#. 
So combining both would defeat the purpose of the gamemode whitelist.
Referencing games from tools would be great tho.

**Comment by lotuspar** [comment]
#2228 does sound like the way to go, but I'm not sure about having a whole tool addon for a small gamemode specific tool (what if I just want a feature or two in Hammer?)

> since tool addons dont have a whitelist you are able to do anything in c#.
>
That's interesting to know. Maybe bundling the tools with the gamemode without compiling them as one would be a better option?

I'll close this for now but I'm still not sure

**Comment by handsomematt** [comment]
You can make an Editor folder in your game project now
