### ISSUE TITLE
`transform: translate` is still broken after a year

### ISSUE THREAD

**Issue by timmybo5** [sboxgame/issues#2619]
### Describe the bug

**Related Issues:**
- https://github.com/sboxgame/issues/issues/1059
- https://github.com/sboxgame/issues/issues/551
- https://github.com/sboxgame/issues/issues/2537

The render pipeline does not get updated properly after running `transform: translate` thinking it is still in the old position.

**Before using `transform: translate` the panel is cut off as it should:**
![image](https://user-images.githubusercontent.com/4988198/204908426-b9b84981-8dd8-40ea-abb5-3de982dd8a99.png)

**When moving the panel with `transform: translate(-100%, 0);` it should be fully visible but it is still cut off as it would be in its old position:**
![image](https://user-images.githubusercontent.com/4988198/204908290-531bff39-42af-4298-8640-c7b7118aef04.png)

**Comment by DoctorGurke** [comment]
I've also noticed an issue when combining pointer events with transform in some weird, but haven't quite nailed down a reproduction yet.

**Comment by handsomematt** [comment]
I think I fixed all of this now, it might misbehave if you do some real stupid nested stuff, but having that work adds a lot of complexity to something that is probably never gonna be a real issue.

![image](https://user-images.githubusercontent.com/1388267/211205717-00e262f7-c11f-401c-8eb7-7aa8f5c53055.png)
![image](https://user-images.githubusercontent.com/1388267/211205723-1cabe466-e9c1-4c14-8904-aa4b041e1461.png)
