### ISSUE TITLE
Add Copying Model/Material/Sound Paths from Asset Browser

### ISSUE THREAD

**Issue by a1steaksa** [sboxgame/issues#2627]
### For?

Other

### What can't you do?

When using the Asset Browser to find a placeholder model, I found a perfect Vending Machine model but it's not possible to meaningfully use the asset you find from the browser.

### How would you like it to work?

I'd like to be able to open a context menu on an asset and get the ability to copy the model path so it can be pasted into an Entity.

It might also work, depending on how this kind of asset works on asset.party, to add functionality to `ModelEntity.SetModel()` to let it take a package ident instead of a model name.

The Hammer legacy Asset Browser has a lot of the functionality I want, but is locked away in a tool I rarely use
![image](https://user-images.githubusercontent.com/8369707/205373866-b6d14194-59ff-4fc2-af7c-8ffbaad16050.png)

### What have you tried?

This is what the context menu currently looks like.

![image](https://user-images.githubusercontent.com/8369707/205372305-2538ccc9-24a3-4e75-bf33-77f3cc17d9c3.png)

"Open in Editor" shows the model in modeldoc, but doesn't seem to immediately have a way to get the model path.
"View in Browser" is similarly unhelpful
"Copy Package Ident" might be useful somewhere to someone, but currently it just feels like it's tauntingly close to what I want without actually helping.
"Install" is maybe my least favorite of the available context options.  I have no idea what it does and there's no feedback if it worked or not.  Do I have to install an asset before I can use it?  Are the assets downloaded automatically when I reference them?  No idea.

### Additional context

I think you might want a "Feature Request" "For" option for "Main Editor" because currently I think that falls under "other"

**Comment by robotboy655** [comment]
Added "Copy Asset Path" to that context menu, will appear if the asset is installed.
