### ISSUE TITLE
Editor Crashes right after when you click "Select" when in the Shader Selection Window within the Material Editor

### ISSUE THREAD

**Issue by QuackCocaine** [sboxgame/issues#2628]
### Describe the bug

When you click on the `Select` button to confirm a shader selection with either the `glass` or `water` shader selected it will appear it's going to work as intended for a second or two then the entire Editor will crash.

### To Reproduce

1. Open the Editor
2. Open the Material Editor and open a fresh blank material.
3. Go and select either the `glass` or `water` shader and then click on `Select`.
4. Observe the Editor will crash.

### Expected behavior

To change to the selected shader without crashing.

### Media/Files

https://user-images.githubusercontent.com/23345567/205381571-847313f6-bfee-4ed5-9d2f-dfc3e7df237e.mp4

### Additional context

Glass and water are the only two shaders that seem todo the crashing business though

**Comment by aylaylay** [comment]
Try now, can't get it to crash for me

**Comment by QuackCocaine** [comment]
Yup, it doesn't crash now :D
