### ISSUE TITLE
Custom shader not loading properly in-game from packages

### ISSUE THREAD

**Issue by edisonlee55** [sboxgame/issues#2634]
### Describe the bug

When launching the game without dev mode (`sbox.exe`).
Try to load a model in-game from packages that use a custom shader, it will not load properly.

When launching in dev mode (`sbox-dev.exe`), it will load properly.
**All local resources are already disabled for controlled experiments.**

### To Reproduce

1. Launch s&box in none-dev mode (`sbox.exe`)
2. Start a game in gamemode that supports in-game model loading (Eg, [Sandbox](https://asset.party/facepunch/sandbox))
3. Load a model that uses a custom shader (Eg, [Alice Chan (MToon)](https://asset.party/edison/alice_chan))
4. Bug reproduced. The model's materials (or shader) are not loading properly.

### Expected behavior

The model's materials (or shader) should load properly in both dev mode and none-dev mode.

### Media/Files

Loading model from package with custom shader in-game (not dev mode / `sbox.exe`):

![20221203225826_1](https://user-images.githubusercontent.com/5277788/205447389-0c540152-c29d-4c51-a1ca-247110093982.jpg)

---

Loading model from package with custom shader in-game (dev mode / `sbox-dev.exe` / all local packages are disabled):

![Screenshot 2022-12-03 225927](https://user-images.githubusercontent.com/5277788/205447411-545b646c-c0db-43cf-b0ad-b328ca94ccb2.png)

### Additional context

- Windows 11 (22H2 / 22621.900)
- NVIDIA GeForce RTX 3060 Ti (Driver: 526.98)

**Comment by aylaylay** [comment]
This should be working now, can you test and check for me please?

**Comment by edisonlee55** [comment]
It is working now. Thank you!
