### ISSUE TITLE
Rider is not a valid code editor until it is opened

### ISSUE THREAD

**Issue by lewisakura** [sboxgame/issues#2639]
### Describe the bug

I have Rider EAP installed, but the s&box editor fails to recognize I do until I open it.
Opening this configuration window also shows this:
` 08:01:39   Code editor 'Rider' not installed, using default`
The moment I open Rider, it will offer Rider as an option and work as intended.

### To Reproduce

1. Install Rider EAP
2. Open s&box editor
3. Attempt to change code editor in preferences
4. See that Rider is not available as a code editor
5. Open Rider
6. S&box immediately recognizes that Rider is installed and can be used as an option

### Expected behavior

Rider should show up as a valid option without needing to be started first.

### Media/Files

![image showing that rider is not visible in the code editor dropdown](https://discord.coffee/2dzDj6t.png)
![console log reporting that rider is not installed](https://discord.coffee/B97RA4c.png)
![picture demonstrating rider is installed via jetbrains toolbox](https://discord.coffee/9dnDrsP.png)
![picture demonstrating that upon opening rider, s&box detects it as valid and presents an option](https://discord.coffee/8d5EU2Z.png)

### Additional context

Rider is installed through Jetbrains Toolbox. S&box is installed on a separate drive to Rider (Toolbox installs into the AppData folder on C:\, my Steam library is on E:\). ~~I have not tested if the non-EAP version does the same, thus I have reported it as an issue with specifically EAP until disproven.~~ Based on @SchrodingerHH's response, this doesn't appear to be an EAP specific issue, therefore I have broadened it.

**Comment by handsomematt** [comment]
So... Rider doesn't install properly until it gets launched once? I don't see how this is an issue we can/should resolve.

**Comment by lewisakura** [comment]
No, Rider is installed correctly and works fine, s&box just doesn't detect the installation *until* it gets opened in the current editor session. It forgets it's installed after closing, so it seems like it's unable to detect the installation initially.

**Comment by lewisakura** [comment]
I've recorded a demo video that demonstrates the behaviour: https://streamable.com/wuwusg
To describe what is happening in each part:
- Opening s&box and showing Rider is not detected
- Opening Rider *after* opening s&box, then showing that Rider is now detected
- Closing and reopening s&box *whilst* Rider is open, then showing Rider is still detected
- Closing both Rider and s&box, then reopening s&box, then showing that Rider is no longer detected

**Comment by SchrodingerHH** [comment]
Can confirm, occured to me with Rider 2022.2.3 and 2022.2.4

**Comment by edisonlee55** [comment]
S&box's code editor preference will not distinguish between different versions of the same brand IDE.
Which is ambiguous when the user has multiple versions of it.

It should be able to distinguish it like what Unity does. And therefore fix this issue as there is no more ambiguity about which version should s&box open.
![image](https://user-images.githubusercontent.com/5277788/205696337-0ec42dd4-4bc5-4c6b-b155-0a0f3929c666.png)

**Comment by kira0x1** [comment]
This still occurs for me
