### ISSUE TITLE
Resources: Add an `ISet<T>`/`HashSet<T>` Property Editor

### ISSUE THREAD

**Issue by LeQuackers** [sboxgame/issues#2640]
### For?

S&Box

### What can't you do?

I'm unable to have a unique set of things (in my case strings) in a resource file.

### How would you like it to work?

It'd probably just be copy of the `ListProperty` editor with a few changes to make sure that the elements are unique and to warn the user if they try to add a duplicate value.

### What have you tried?

I'm gonna build a `SetProperty` editor tomorrow, but this is something that should probably be in the base tools.

**Comment by robotboy655** [comment]
Added.

![image](https://user-images.githubusercontent.com/3299036/207419554-89751d0c-4ddc-4db0-9b25-25239b1aedaa.png)
