### ISSUE TITLE
Resources: Make a `Resource` Equivalent to `Particles`

### ISSUE THREAD

**Issue by LeQuackers** [sboxgame/issues#2641]
### For?

S&Box

### What can't you do?

I'm unable to directly use the `Particles` class in a resource file, unlike `Model`, `SoundFile`, `Texture`, and `Material`.

### How would you like it to work?

Having a resource class similar to `Model` that has an internal field that references the actual `Particles` class would probably work.

### What have you tried?

I've tried using `[ResourceType("vpcf")]` on the particular property in my resource file, but in my case the property is a `Dictionary<string, string>`, which causes the property editor to think both the key and the value are a vpcf (see #2219).

**Comment by aylaylay** [comment]
ParticleSystem is now a resource

**Comment by LeQuackers** [comment]
Works like a charm, thanks!
