### ISSUE TITLE
Better naming of list titles in File Uploads menu

### ISSUE THREAD

**Issue by Gmod4phun** [sboxgame/issues#2644]
### What it is?

The _**Not Upload**_ and _**Uploaded**_ titles should be changed to something that better represents the status of the files in those lists. The Not Upload name makes it seem like files that would get ignored and not get uploaded.

![image](https://user-images.githubusercontent.com/5991682/205639556-a40e3fba-b6cb-4c4f-84fc-aaf86fc2309f.png)

### What should it be?

I think the better option would be something along the lines of _**Files to be uploaded**_ and _**Already in cloud/Already uploaded**_

**Comment by robotboy655** [comment]
Changed to "Pending Upload"
