### ISSUE TITLE
Shader won't compile

### ISSUE THREAD

**Issue by DissolveDZN** [sboxgame/issues#2647]
### Describe the bug

When trying to assign a custom shader to a material for example the one in the S&box wiki you will get the following error: "ERROR! Missing a valid shader header. 'shaders/shader_name' was not properly compiled, even though the shader itself is fine.
Other people also encountered the same problem. Restarting, recompiling or reinstalling the game doesn't help. There are also no errors in the console

![image](https://user-images.githubusercontent.com/66252754/205876261-99af09e0-5d55-4cfc-a894-2cfad58df7d3.png)
![image](https://user-images.githubusercontent.com/66252754/205876457-47802b00-df97-484e-a18d-abb805b3a6f1.png)

### To Reproduce

Add a new shader.
Compile the shader.
Go to the material editor and try to select it.

### Expected behavior

The shader should work.

### Additional context

running on windows 11 and the newest version of s&box

**Comment by DoctorGurke** [comment]
Can confirm 
![sbox-dev_l6sLa99VOI](https://user-images.githubusercontent.com/12602100/205876884-ea1e0274-191d-48e8-99aa-01ebfabe6f15.png)

**Comment by aylaylay** [comment]
This is happening only for me on steam version so give me some time to figure it out because I can't easily debug it.

**Comment by aylaylay** [comment]
Should be working now

**Comment by DissolveDZN** [comment]
yes it seems to be working now
i'll close this issue then
