### ISSUE TITLE
Uploading hammer maps

### ISSUE THREAD

**Issue by xMrMarauder** [sboxgame/issues#2648]
### Describe the bug

When I try to upload a map from hammer via the uploading to asset party process, i get stuck on the file uploads screen with it showing that i have nothing to upload, to which i cant get past it.

### To Reproduce

1. Make map
2. Go through the asset upload process

### Expected behavior

I assume it lists the map files as well as an missing from the previous upload

### Media/Files

![image](https://user-images.githubusercontent.com/119049583/205916247-fd657bfd-a5ad-44e0-9f47-548fea62449a.png)

**Comment by handsomematt** [comment]
did you compile the map

**Comment by xMrMarauder** [comment]
Yes. many times

**Comment by handsomematt** [comment]
I assume there was an error in your console related to something I fixed recently. If it's still a problem for you, reopen the issue with your Log.txt file
