### ISSUE TITLE
Support WorldPanel in map entity addon

### ISSUE THREAD

**Issue by edisonlee55** [sboxgame/issues#2654]
### For?

S&Box, Hammer

### What can't you do?

Currently, only Razor files in gamemode support WorldPanel.
Razor files in map entity Addon cannot inherit from WorldPanel.

### How would you like it to work?

I want to create a map entity addon with WorldPanel that works across different maps and gamemodes.
(Eg, an in-game music player with WorldPanel can be placed on any map. And can be customized by the mapper.)

### What have you tried?

Tried to compile the Razor files inherited from WorldPanel in Addon. But it fails to compile.

**Comment by garrynewman** [comment]
Why doesn't worldpanel work for razor?

**Comment by mi1agency** [comment]
The type or namespace name 'WorldPanel' could not be found (are you missing a using directive or an assembly reference?)

**Comment by handsomematt** [comment]
I think addons don't ref base currently rather than this being anything todo with razor

**Comment by mi1agency** [comment]
> I think addons don't ref base currently rather than this being anything todo with razor

addons do ref base now for some days, it is only in razor where this fails, even when @inherits Sandbox.UI.WorldPanel

RootPanel works fine, only WorldPanel is failing for some reason
