### ISSUE TITLE
ViewAngle Pitch missing

### ISSUE THREAD

**Issue by SryEyes** [sboxgame/issues#2656]
### Describe the bug

The Entity ViewAngle (not the ClientInput ViewAngle) Pitch isn't set anymore and stays 0. Seems broken since the removal of Entity.EyeRotation. 

### To Reproduce

cl_showpos 1 in console

### Expected behavior

ViewAngle pitch should be set.

**Comment by DevulTj** [comment]
You're going to have to be more specific, Entity doesn't have `ViewAngle`

**Comment by DevulTj** [comment]
Thanks, I understand what you mean now. This is also the case with `getpos`

**Comment by DevulTj** [comment]
I've removed cl_showpos, `getpos` still exists and will output the correct position and rotation to your console.

**Comment by SryEyes** [comment]
Thank you!
But i liked Information getting displayed on the screen rather than in the console itself :C
