### ISSUE TITLE
Add a "New Shader.." button in the asset browser

### ISSUE THREAD

**Issue by xezno** [sboxgame/issues#2657]
### For?

S&Box

### What can't you do?

Making a shader is a very manual process at the moment - you have to copy a base shader into your addon and rename it.

### How would you like it to work?

It'd be much easier if we could just right click in the asset browser and click "New Shader.." like other assets:
![image](https://user-images.githubusercontent.com/12881812/206506340-9779c50a-7320-477b-ba18-9efc29e74b0b.png)

This would ideally make a .shader file with basic shader contents already included (i.e. it makes a shader with just a solid green colour, or something similar).

### What have you tried?

I have tried making a shader manually. While this works, it's not convenient and it's not consistent with other asset types.

**Comment by aylaylay** [comment]
Done

**Comment by xezno** [comment]
Works perfect, thank you!
