### ISSUE TITLE
Input.AnalogLook and Input.AnalogMove aren't included in usercmds by default

### ISSUE THREAD

**Issue by DoctorGurke** [sboxgame/issues#2658]
### Describe the bug

Input.AnalogLook and Input.AnalogMove aren't included in usercmds by default.

### To Reproduce

Some basic debug text will show that only the client knows about analog look/move

```csharp
public override void Simulate( Client cl )
{
	var shift = Host.IsServer ? 5 : 0;

	DebugOverlay.ScreenText( $"analog move: {Input.AnalogMove}", 1 + shift );
	DebugOverlay.ScreenText( $"analog look: {Input.AnalogLook}", 2 + shift );
}
```

### Expected behavior

All basic input states, should be networked by default, [ClientInput] should be for anything more complex or derived (turning the look delta into a rotation, encoding custom data into usercmds, etc). This is already the case for everything else, including button states, mouse wheel, mouse delta, etc.

**Comment by handsomematt** [comment]
There's no context for Input within an [Event.Tick] because there's no client, this should be throwing an assert however so I'll look at why that's not happening.

**Comment by DoctorGurke** [comment]
yea, derp. The same problem persists within simulate though

I'd like to note however that this same code would've worked previously with the host input pretty sure. Was nice for debugging in-dev, but that's fine

**Comment by DoctorGurke** [comment]
Right so, fucked up my test code a bit so this was a dud. Input.Down works fine in simulate and throws an assert anywhere else.

That aside, I do think default Input accessors like AnalogMove/Look should be networked/included in usercmd by default, I'll edit the issue accordingly

**Comment by DoctorGurke** [comment]
updated for those two properties specifically, sorry about that derp

**Comment by DoctorGurke** [comment]
much appreciated, cheers!
