### ISSUE TITLE
Fixed sound event parameters (Volume/Pitch) are silently interpreted as ranged

### ISSUE THREAD

**Issue by Phyksar** [sboxgame/issues#2660]
### Describe the bug

I have noticed it accidentally, at first I thought that changing these parameters doesn't work.
Obviously, I shouldn't be able to hear the sound with such parameters but I do, and it sounds like it still randomizing in the volume range.
![2022-12-08 22_22_26-Window](https://user-images.githubusercontent.com/13320416/206548322-8da5b2f5-7cac-4399-b96b-6682358c3062.png)

### To Reproduce

The contents of the sound file:
```
<!-- kv3 encoding:text:version{e21c7f3c-8a33-41c5-9977-a76d3a32aa0d} format:generic:version{7412167c-06e9-4698-aff2-e63eb59037e7} -->
{
	data = 
	{
		UI = false
		Volume = "0.00,1.00,0"
		Pitch = "1.00,1.00,1"
		Decibels = 120
		SelectionMode = "Random"
		Sounds = 
		[
			resource:"sounds/physics/breaking/break_flesh_01.vsnd",
			resource:"sounds/physics/breaking/break_flesh_02.vsnd",
			resource:"sounds/physics/breaking/break_flesh_03.vsnd",
		]
		MaximumDistance = 3299.7227
		MinimumDistance = 164.98613
	}
}
```

### Expected behavior

The sound should have fixed volume and pitch if the corresponding option is chosen.

**Comment by robotboy655** [comment]
Oops, sorry, should be fixed when the game next updates. No changes to assets needed on your end.
