### ISSUE TITLE
Runtime addons fail due to failed references to underlying game

### ISSUE THREAD

**Issue by nykez** [sboxgame/issues#2661]
### Describe the bug

When compiling runtime addons referencing the sandbox gamemode it will fail to compile.

With errors such as: `The type or namespace name 'Prop' could not be found (are you missing a using directive or an assembly reference?)`

The gamemode is referenced in both editor settings and visual studio. The issue does not appear until the addon is compiled when loaded in.

### To Reproduce

1. Create a runtime addon
2. Reference sandbox from asset.party
3. Add some code from sandbox. Such as `Prop`
4. Attempt to run the gamemode with the local addon selected 

Test code:

```
    public class TestEnt : Prop, IUse
    {
        public int Test { get; set; }
        public override void ClientSpawn()
        {
            base.ClientSpawn();
        }

        public bool IsUsable(Entity user)
        {
            throw new NotImplementedException();
        }

        public bool OnUse(Entity user)
        {
            throw new NotImplementedException();
        }
    }
```

### Expected behavior

Expected behavior: compile should not fail

### Media/Files

Sandbox is referenced in dependencies 
![image](https://user-images.githubusercontent.com/14931886/206549831-33882b23-b797-42b4-8fad-e85987d494e3.png)

Visual studio shows no error with referencing 
![image](https://user-images.githubusercontent.com/14931886/206550452-afdc4fe0-55ae-41ce-9887-f8a067fd1f5d.png)

When loading into game:
![image](https://user-images.githubusercontent.com/14931886/206550561-55b4e0ff-edd3-4080-a79d-2d6e43ab579a.png)

**Comment by Ceiridge** [comment]
This does not reference the underlying game, but the *base* project/assembly. `Prop` is part of core\base.
I can confirm this issue.
