### ISSUE TITLE
Camera Refactor: AimRay.Origin uses AbsOrigin instead of EyePos

### ISSUE THREAD

**Issue by SryEyes** [sboxgame/issues#2663]
### Describe the bug

When using Entity.AimRay it returns a Ray with the Origin and the Rotation.Forward of that Entity.
Origin should get changed to the Eye Position of that Entity since you dont aim with your feet.
When using the AimRay many people will get confused. The removed EyePosition should get used instead.

### To Reproduce

Look at the Entity.AimRay get wich this.Position gets fed in.

### Expected behavior

AimRay.Origin should be = EyePos  rather than the Origin

**Comment by SryEyes** [comment]
Seems very misleading. Why having a value when its wrong till u override it? When i have a normal Player i expect AimRay to be right out of the box. 
With that argumentation not every Entity has or needs an Origin but still it does what you expect.
Maybe an automatic override if entity is a player is the right way to go. Stripping code is all cool n stuff but there needs to be an end somewhere. I wanna use a game engine and not write all that basic stuff myself beacuse it isnt universal for everyting

**Comment by DoctorGurke** [comment]
What is "right"? Why should it be assumed that a player has eyes? Your average top down rts might not even have a player pawn at all, so having this as part of the base entity type makes no sense. Things like these will be mediated somewhat once templates roll out, those will have respective base pawn entities that make sense for their scope.

**Comment by DoctorGurke** [comment]
Also entities definitely all should have an origin. A transform is a very basic property of scene objects, so replicating that for entities is just natural.

**Comment by SryEyes** [comment]
If you got an rts without a player pawn than you can get the camera stuff. And if I wanna create an Entity without it being visible and without a transform i dont need an origin. If every var or function which isnt being used in some rare edge case gets stripped the engine would be empty. 99% of the games there is a player with eyes so there should be a value for it.

**Comment by DoctorGurke** [comment]
No, there will just be a base template for you to work off of in the future that will provide some sort of pawn type with the relevant logic and properties.
Instead of saying that any entity should be usable as a player entity with eyes.

I don't think a Transform is comparable with the concept of eyes on a global post processing entity, for example.
