### ISSUE TITLE
[Proton] Game can't load gamemodes on startup

### ISSUE THREAD

**Issue by 5FB5** [sboxgame/issues#2666]
### Describe the bug

When I enter to the game, it load gamemodes in loop and I can't play them, including connection to servers

### To Reproduce

- Open S&box on Linux via Proton
- See the problem

### Expected behavior

Normal working of the app

### Media/Files

![image](https://user-images.githubusercontent.com/15859698/206766562-313224c2-c921-41e6-9b69-835f41b3c0e7.png)

### Additional context

OS: Linux Mint
Kernel version: 5.13.0-44-generic
Proton version: Proton Hotfix
Video card: Nvidia Geforce RTX 3050
Video card driver version: 5.15

**Comment by handsomematt** [comment]
https://github.com/ValveSoftware/Proton/issues/4940

Nothing we can do, Proton needs additional .NET 7 support.
