### ISSUE TITLE
TextureLoader.Image has been marked as internal

### ISSUE THREAD

**Issue by yuberee** [sboxgame/issues#2673]
### What it is?

TextureLoader.Image being marked as internal means we cannot access Image.Load( Stream ) anymore due to its protection level.
We used to load images from the web and I haven't been able to find an alternative except for writing it from scratch myself.

### What should it be?

TextureLoader.Image to be marked as public

**Comment by garrynewman** [comment]
Texttre.Load( "http://ffffff" ) works though right?

**Comment by yuberee** [comment]
![image](https://user-images.githubusercontent.com/59583743/207010730-a5381707-7a34-481e-81aa-9e52dfa42a89.png)
Oh I never noticed it, I always used TextureLoader.Image.
I'll try it when I'm home, I still suggest changing it from "filename" to "url" to avoid any confusion.

**Comment by yuberee** [comment]
Yep does just what I needed.
