### ISSUE TITLE
Tags in DamageInfo is private with no way to retrieve them.

### ISSUE THREAD

**Issue by Ephememory** [sboxgame/issues#2675]
### What it is?

The Tags member is private with no public getter.
![image](https://user-images.githubusercontent.com/66768086/206924875-f0dca411-7f47-4988-9108-6b45b1365133.png)

### What should it be?

The Tags member have a public getter at the very least so we can easily access them for things like networking.

**Comment by DevulTj** [comment]
Let me know if that's enough for you, DamageInfo.Tags was made public

**Comment by Ephememory** [comment]
> Let me know if that's enough for you, DamageInfo.Tags was made public

Yep, all fixed. Thanks.
