### ISSUE TITLE
@Body like directive for Razor

### ISSUE THREAD

**Issue by Remscar** [sboxgame/issues#2676]
### For?

S&Box

### What can't you do?

If I have some code like this:
```razor
<MyRazorThing>
  <div>Hello World 123</div>
</MyRazorThing>
```

And let's say `MyRazorThing` looked like
```razor
<root>
  <div>Meow mix</div>
  <div>I am a cat</div>
</root>
```

Currently output would be 

```razor
<MyRazorThing>
  <div>Meow mix</div>
  <div>I am a cat</div>
  <div>Hello World 123</div>   <--------
</MyRazorThing>
```

But what I actually want is
```razor
<MyRazorThing>
  <div>Meow mix</div>
  <div>Hello World 123</div> <--------
  <div>I am a cat</div>
</MyRazorThing>
```

By being able to control when/where the inner html (children) is placed.

### How would you like it to work?

I would like to write `MyRazorThing` like:

```razor
<root>
  <div>Meow mix</div>
  @Body
  <div>I am a cat</div>
</root>
```

So that the inner html when I created `<MyRazorThing>` is rendered at `@Body` similar to this: https://learn.microsoft.com/en-us/aspnet/core/blazor/components/layouts?view=aspnetcore-7.0

### What have you tried?

I have had to make my components more specialized than I would like. I'm making a store with tabs, i'd like to do something like

```razor
<TabbedPages>
  @foreach(var category in categories) {
    <Page title="@category.Name">
        <StorePage Items="@category.Items" />
    </Page>
  }
</TabbedPages>
```

But instead i'll have to pass a bunch of params to `<TabbedPages>`, and eventually it will create my `StorePage`'s but it will be dicey and `<TabbedPages>` will be way less reusable.

### Additional context

Things like React which is probably the most widely used front end library supports things like this, and even Blazor does.
It would be really nice to create ui libraries for s&box and this would make it so much easier.

Take a look at some documentation for React Material UI to see how powerful this is:
https://mui.com/material-ui/react-button-group/
https://mui.com/material-ui/react-backdrop/
https://mui.com/material-ui/react-stack/

**Comment by DevulTj** [comment]
Render Fragments should have what you need - https://wiki.facepunch.com/sbox/ui-razor-templates

**Comment by Remscar** [comment]
> Render Fragments should have what you need - https://wiki.facepunch.com/sbox/ui-razor-templates

A year late, but thank you king
