### ISSUE TITLE
Let AnimEvents play in the Animgraph Editor.

### ISSUE THREAD

**Issue by yourbadandimbest** [sboxgame/issues#2679]
### For?

Animgraph Editor

### What can't you do?

When I was making an animgraph I realised that its AnimEvents do not play. This means if you use bodygroup events you cannot see it.

### How would you like it to work?

When it plays an animation in the animgraph it would be great quality of life if it also play its animation events alike in the modeldoc.

### What have you tried?

While it is possible to load up a game and try it in-engine, preferably it should all work inside of the Animgraph Editor. Another less logical solution is playing animations in order manually in the Modeldoc, but this method quickly falls apart for more complex animation sequences.

### Additional context

I don't know if every possible animation event would be possible in the environment of an animgraph, but specifically bodygroup and sound events would be very useful if it played in the animgraph.

**Comment by aylaylay** [comment]
I have added basic support for start and stop sound animevents, let me know how you get on with that

**Comment by yourbadandimbest** [comment]
Sound AnimEvents works in the Animgraph now. Sound was the most important to me, but I hope this basic support will eventually allow for other useful AnimEvents to be supported as well. Thanks a thousand, Layla.
