### ISSUE TITLE
Game.ChangeLevel crashes often

### ISSUE THREAD

**Issue by Weldify** [sboxgame/issues#2680]
### Describe the bug

I'm working on a game that makes heavy use of Game.ChangeLevel
Right now it's a gamble whether its going to crash me or not

### To Reproduce

1. Make a game that utilizes Game.ChangeLevel
2. Upload to asset.party (editor *seems* to work fine?)
3. Keep changing levels until it crashes you (should happen about once every 5-10 times)

### Expected behavior

It should be more stable

### Additional context

Windows 10 22h2

**Comment by Weldify** [comment]
![image](https://user-images.githubusercontent.com/66477673/208984666-2ebde9ef-a42c-45f3-aabc-9efe5be240e0.png)
Last time it crashed this thing popped up

**Comment by Remscar** [comment]
Been getting this too, at least in the editor. Will test on dedicated servers soon

**Comment by handsomematt** [comment]
Might be fixed now

**Comment by Weldify** [comment]
Seems to be fixed
