### ISSUE TITLE
Mutex

### ISSUE THREAD

**Issue by Remscar** [sboxgame/issues#2681]
### For?

S&Box

### What can't you do?

There are no mutexes, the ones in `System.Private.CoreLib/System.Threading.Mutex` are not whitelisted.

### How would you like it to work?

`Sandbox.Mutex` which is just `System.Threading.Mutex`

### What have you tried?

Nothing yet, but i'm about to try some really dumb things.

**Comment by LeQuackers** [comment]
What are you trying to do that can't be done with a `lock`? Just curious.

**Comment by Remscar** [comment]
> What are you trying to do that can't be done with a `lock`? Just curious.

Nothing currently! That worked like a charm, thank you!
