### ISSUE TITLE
css `color` does not support `lighten` and `darken`

### ISSUE THREAD

**Issue by Remscar** [sboxgame/issues#2682]
### Describe the bug

When I use `lighten` and `darken` with `color` attributes I get an error like
```
Client [/ui/skills/skills.scss:137]: lighten(hsl(4, 44.45%, 68%), 20%) is not valid with color
```

No matter what I do, rgb, hex, hsl, using variables, i always get an error.

`background-color` however, works

### To Reproduce

```
color: darken(#fff, 20%)
```

### Expected behavior

It should darken and lighten the color

**Comment by DevulTj** [comment]
I've made some changes that should amend this issue - please let me know if the latest build on Steam resolves your issue.

**Comment by Remscar** [comment]
> I've made some changes that should amend this issue - please let me know if the latest build on Steam resolves your issue.

```
darken(rgba(10, 10, 10, 0.1), 10%) is not valid with background-color
darken(hsl(4, 44.45%, 68%), 10%) is not valid with color
```

Didn't seem to work, and it appears `background-color` suffers the same issue

**Comment by Remscar** [comment]
> I've made some changes that should amend this issue - please let me know if the latest build on Steam resolves your issue.

Seems to work, however the behavior seems wrong.

The SASS language manual says

> The darken() function decreases lightness by a fixed amount, which is often not the desired effect. To make a color a certain percentage darker than it was before, use [color.scale()](https://sass-lang.com/documentation/modules/color#scale) instead.

However it appears that `darken` and `lighten` are scaling by a % of the original luminosity. Darkening a color by 50% will decrease it's lightness by 50% of it's current lightness, not an absolute 50%.

This is the behavior you would expect from `color.scale()`

**Comment by DevulTj** [comment]
I believe the problem you're describing is outside of the scope of this issue. If you think it's a valid problem, please make another issue.
