### ISSUE TITLE
`BaseGameManager.Shutdown` is called on the client

### ISSUE THREAD

**Issue by Remscar** [sboxgame/issues#2683]
### Describe the bug

I noticed that the `Shutdown` method of a `GameManager` is getting called on the clientside.

It is confusing whether this is intentional or not as the comment says "Called when the server is going away"

### To Reproduce

```
public override void Shutdown()
    {
        if (Game.IsClient)
        {
            Log.Info("bowowow");
            return;
        }
}
```

`bowowow` is printed to console

### Expected behavior

`bowowow` is not printed to console

### Additional context

I have been trying to run some logic before the server completely shuts down and before all the clients have been disconnected.

When running the game via editor, if you hit the refresh or stop button, there is not `ClientDisconnect` call made.
Instead it immediately goes to `Shutdown` and at that point all of the `Client` objects are gone.

**Comment by DevulTj** [comment]
This is fine. This is called when the server is going away, meaning it's shutting down - this will inform the clients about it too.
