### ISSUE TITLE
SpotLightEntity doesn't update until it changes position

### ISSUE THREAD

**Issue by Weldify** [sboxgame/issues#2684]
### Describe the bug

I use a `SpotLightEntity` for the flashlight in my game. When you set `SpotLightEntity.Enabled` it won't do anything until you move it/your camera.

The bug also appears with `SpotLightEntity.Toggle()`, `SpotLightEntity.TurnOn()`, `SpotLightEntity.TurnOff()`

### To Reproduce

1. Create a `SpotLightEntity` that follows your camera
2. Turn it on or off while standing still

### Expected behavior

You shouldn't have to move your camera to see the light being enabled/disabled

**Comment by aylaylay** [comment]
Have you got a repro project? It works fine in sandbox

**Comment by Weldify** [comment]
@aylaylay https://github.com/Weldify/Frightworks
Doubt it's possible to play the game now, since it relies on local maps. Hopefully this will be of some use
Flashlight code is located in Player/Survivor/SurvivorPlayer.Flashlight.cs
