### ISSUE TITLE
[Web] Player Activity/New Players Not Updating

### ISSUE THREAD

**Issue by damienfamed75** [sboxgame/issues#2690]
### Describe the bug

People playing your game modes doesn't update the Players menu since Nov. 23-24 according to Just Another Night and Demo Dash even though I know that people are playing games like Just Another Night, they're not showing up in the player list. *(see below in media/files for context)*

### To Reproduce

1. Play any gamemode
2. Go to the players tab on the asset.party page for it
3. See that it hasn't been updated

An example
1. Play [Just Another Night](https://asset.party/gimlet/a_night)
2. Then look at the [players page](https://asset.party/gimlet/a_night/players)

### Expected behavior

Players should show up after playing a gamemode and be added to the list.

### Media/Files

> Remscar confirming that he played Just Another Night on the 13th. And he mentions that others have been playing it too.
![remscar confirming he played Just Another Night on the 13th and others as well](https://user-images.githubusercontent.com/17505288/207931095-bf95c709-38a2-4bfa-a0d9-871c523d59e0.png)

> Image showing the players hasn't been updated for Just Another Night since 21 days ago.
![image showing that remscar is not on the list of players nor is anyone else within the last 21 days](https://user-images.githubusercontent.com/17505288/207930871-fd654c5c-5306-46b2-91cc-1c60e17f214d.png)

**Comment by DevulTj** [comment]
Pretty sure this has been fixed for a while now.
