### ISSUE TITLE
`Game failed to load: Argument null or empty (Parameter 'fileName')` when launching from FacePunch servers

### ISSUE THREAD

**Issue by matekdev** [sboxgame/issues#2691]
### Describe the bug

When launching `matt.ttt` from FacePunch servers you get the error `Generic Game failed to load: Argument null or empty (Parameter 'fileName')`. The gamemode properly compiles and works locally, and I've made sure the uploaded build is the compiled and working version.
![image](https://user-images.githubusercontent.com/32153021/207970709-d5da0254-f4be-4448-bf5b-65a5cd027960.png)
![image](https://user-images.githubusercontent.com/32153021/207970713-0dc836ef-6d58-447e-8974-232a2c48a197.png)

This seems to only be impacting our game, but the error message is extremely vague and only occurs when loading from FacePunch servers. So, not sure where to go from here.

### To Reproduce

1. Launch TTT from the main menu
![image](https://user-images.githubusercontent.com/32153021/207970793-b2837f1f-0992-42ab-ab30-2ed84770c494.png)
2. Notice that the game doesn't launch and gives the previously mentioned console errors.

### Expected behavior

The compiled and working game should launch.

**Comment by matekdev** [comment]
Got rid of all warnings in the project as well, didn't make any difference (not that it should have).

**Comment by Ephememory** [comment]
I uploaded a copy of the gamemode to my own org on asset.party to verify that it wasn't something weird about the org's specific files and I still encountered this error. From what I can tell this error is happening *before* even the gamemode's GameManager constructor is called. Might have something to do with codegen but I'm not sure why that would only be an issue on the cloud version.

**Comment by matekdev** [comment]
I had an enum in one of my game resources that was referencing `CitizenAnimationHelper.HoldTypes.None` as a default value... here is the full line.
```
	[Category( "WorldModels" )]
	public CitizenAnimationHelper.HoldTypes HoldType { get; set; } = CitizenAnimationHelper.HoldTypes.None;
```

This issue resolved itself after changing it to
```
	[Category( "WorldModels" )]
	public CitizenAnimationHelper.HoldTypes HoldType { get; set; } = 0;
```

I'm assuming there might be some issue with referencing an enum as a default value inside a game resource? I'm going to leave this issue up since the error message you get is *extremely* unhelpful.

**Comment by matekdev** [comment]
This got fixed at some point, thanks.
