### ISSUE TITLE
Ability to override default convars

### ISSUE THREAD

**Issue by Stromic** [sboxgame/issues#2696]
### Describe the bug

You have the ability to override ConVars from the project settings, this breaks the game as they get unregistered when you leave the game.

### To Reproduce

1. Open your project settings
2. Select the project settings tab
3. Add a new ConVar, give it a name of a default ConVar
4. Join the game

### Expected behavior

The default ConVars should be blacklisted, indicate it in the UI and throw an error, or segregate them somehow.

### Additional context

I also notice that if the gamemode ConVar doesnt exist it throws an error that says:
CLIENT_NO_MAP

Could be an idea to throw a relevant error.

**Comment by Cruton45** [comment]
+Rep

**Comment by Cruton45** [comment]
+WEP

**Comment by GAMEDEVTYCOONXD** [comment]
+REP GREAT ISSUE! 👯

**Comment by kurozael** [comment]
GameSettings have been removed now so this won't be a problem.
