### ISSUE TITLE
SetMaterialOverride has strange effect on models that dont have materials set

### ISSUE THREAD

**Issue by TheBoxTrot** [sboxgame/issues#2697]
### Describe the bug

when set the material seems to be overly shiny and have no pbr normals 

### To Reproduce

create a model that doesnt have a material
use setmaterialoverride to a material
profit

### Expected behavior

setmaterialoveride should have the same effect whether the model  has a material set or not before using the code

**Comment by aylaylay** [comment]
Is this for setting on ModelEntity or SceneObject?

**Comment by TheBoxTrot** [comment]
ModelEntities I haven't tested on scene

**Comment by aylaylay** [comment]
Yeah, currently looking into it, it's a weird one
