### ISSUE TITLE
Add the possibility to retrieve a Morph value by his Index (or Name)

### ISSUE THREAD

**Issue by PolSpock** [sboxgame/issues#2699]
### For?

S&Box

### What can't you do?

Hello, i'm looking to create a Ragdoll of my playermodel which gonna keep the value of my Morphs.

Currently there is no `CopyMorphsFrom` method (like `CopyBonesFrom`, `CopyBodyGroups`, `CopyMaterialGroup`...)
So the other way to achieve that is to retrieve value from my Morph but the https://asset.party/api/Sandbox.MorphCollection hasn't this possibility yet.

### How would you like it to work?

So i would love to get the possibility to get my Morph float value like this : `this.Morphs.Get( myIndex )` or `this.Morphs.Get( myMorphName )`
And additionality, add the `this.CopyMorphsFrom( ModelEntity ent)` method too (but can be useless)

### What have you tried?

I've already looked at the https://asset.party/api/Sandbox.MorphCollection : this feature is not present.
The only way currently its to store each value in a dictionary (or whatever) and loop it to retrieve each morph value. This is sad.

**Comment by aylaylay** [comment]
Added
