### ISSUE TITLE
Allow us to get the max player count of a server

### ISSUE THREAD

**Issue by matekdev** [sboxgame/issues#2705]
### For?

S&Box

### What can't you do?

I'm unable to get the max player count of a server since `ConsoleSystem.GetValue( "maxplayers" )` is no longer allowed.

### How would you like it to work?

`Game.MaxPlayerCount` or something like that.

### What have you tried?

Looking through your APIs & and discord.

**Comment by DevulTj** [comment]
Added, see Game.Server.MaxPlayers

Might take a while to be seen on steam, our build server is currently down.
