### ISSUE TITLE
Feature request asset.party Cloud Support for SFM/s&box editor

### ISSUE THREAD

**Issue by KEDI103** [sboxgame/issues#2709]
### For?

Source Film Maker

### What can't you do?

Can't load cloud (asset.party) maps to sfm + s&box editor.
![Ekran Alıntısı2](https://user-images.githubusercontent.com/52115509/209577136-822e766c-e42c-417e-a050-3a32ead843e0.PNG)

### How would you like it to work?

I want to select them in set map in sfm.
![Adsız](https://user-images.githubusercontent.com/52115509/209577759-9cb5d943-0a93-48ea-aae8-ff77960bba7c.png)

### What have you tried?

Right now its so hard (nearly imposibble) to use cloud maps from asset.part in SFM and s&box editor.
Without cloud support you have to do this steps.

    1. Go to \sbox\download\assets and try to not drown ni chaos of there.
    2. Find map .vpk.621621a6aaaas521 and delete .621621a6aaaas521 part of it
    3. Create project and put .vpk there.
    4. Open it but if map got additional models and texture good luck to find by one by it that \sbox\download\assets chaos. And repeat 2 and 3 steps for each.
![Ekran Alıntısı](https://user-images.githubusercontent.com/52115509/209577344-a4386090-2cdf-44cd-ac58-c9ca5c4e9aa4.PNG)

### Additional context

It will be awesome if its added to cloud (asset.party) map support. It will be so awesome have that support. 
https://forum.facepunch.com/t/feature-request-asset-party-cloud-support-for-sfm-s-box-editor/259488

**Comment by handsomematt** [comment]
donezo

**Comment by KEDI103** [comment]
Thank you but still s&box-dev not still see maps in asset.party. Just showing models in map picker.
![resim](https://user-images.githubusercontent.com/52115509/217693419-f535fa10-53ab-4a87-979b-50a727506f75.png)

**Comment by handsomematt** [comment]
it should default to t:map, but you can type it in there

**Comment by KEDI103** [comment]
> it should default to t:map, but you can type it in there

My bad sorry I need type t.maps I was so exhausted when I tried it. Thank you so much for this update. I will do my best with s2fm and s&box.

**Comment by handsomematt** [comment]
You already can.

**Comment by SplatzyXD** [comment]
Oh alright.
