### ISSUE TITLE
`Panel.DrawContent` not called

### ISSUE THREAD

**Issue by Remscar** [sboxgame/issues#2710]
### Describe the bug

When override the `DrawContent` method on panels it never gets called (at least for Razor panels.)

The `DrawBackground` does get called however.

### To Reproduce

Override the `DrawContent` method

### Expected behavior

It gets called

### Additional context

The `.\sbox\addons\base\code\UI\TextEntry.cs` uses this, but it doesn't seem to work.

**Comment by cr4yz** [comment]
There's a HasContent property you can override to true to allow this to be called, does it work if you do that?

**Comment by handsomematt** [comment]
![image](https://user-images.githubusercontent.com/1388267/211050104-7bc6da36-7bd7-46d9-9a7e-7c6fc48c21af.png)
