### ISSUE TITLE
Using noclip command via keybind gets error

### ISSUE THREAD

**Issue by Kacpergibas** [sboxgame/issues#2713]
### Describe the bug

When i press the V key where i binded to use noclip command, it gives one error in console, but it works property

It also happens every gamemodes with noclip mechanic and command

### To Reproduce

1. Open the console
2. Type "bind [key] noclip" (without quotes) into input. [key] is where you put the key you want.
3. Press your [key]
4. Double-check the console log

### Expected behavior

The noclip should work without making errors even when using via keybind

### Media/Files

Here's an log:
[Log.log](https://github.com/sboxgame/issues/files/10310303/Log.log)

### Additional context

OS: Windows 11
CPU: Intel Core i5-10300H
RAM: 8GB
GPU: NVIDIA GeForce GTX 1650

**Comment by bakscratch** [comment]
noclip isn't a base command its per game now, so it is up the the developers to support it.

**Comment by DrewBritt** [comment]
I'm willing to bet that you're just getting a prediction error, which is nothing to worry about as its unavoidable in some instances. For example, swapping out a pawn's controller to a noclip controller.

**Comment by Kacpergibas** [comment]
> noclip isn't a base command its per game now, so it is up the the developers to support it.

Yeah, its per-game command.

For example, when you use this piece of code:
```
[ConVar.Admin("noclip")]
public static void Noclip()
{
    var player = ConsoleSystem.Caller.Pawn();
    if (player.DevController == null) player.DevController = new NoclipController();
    else player.DevController = null;
}
```
and then use that through "bind" command and pressing that will generate errors.
It *DOES* mean i need to fix my issue?

**Comment by DoctorGurke** [comment]
Prediction just complains that the value (controller) was different on the client than on the server. This is normal as you're overriding the controller on the server via a server command. It gets auto corrected, it doesn't matter in this case.
