### ISSUE TITLE
Nesting the same razor panel crashes game completely

### ISSUE THREAD

**Issue by lotuspar** [sboxgame/issues#2714]
### Describe the bug

This crash makes sense - maybe it shouldn't crash the whole game though?

Just create a razor panel and add it to its own `<root>`

### To Reproduce

in `YourPanel.razor`...
```
@namespace YourNamespace
<root><YourPanel/></root>
```

### Expected behavior

Exception or similar error message without full crash

**Comment by Fortune117** [comment]
> Could you send the project to me (or give me access to your repo) so I can test it please, cheers

I'm getting the same sort of error, busted the UI in my gamemode. I can add you to the repo if it helps

**Comment by xezno** [comment]
Yeah I think there's a better way of doing what I did, I'll take a look first thing in the morning. Please do send repros, too

**Comment by Fortune117** [comment]
> Yeah I think there's a better way of doing what I did, I'll take a look first thing in the morning. Please do send repros, too

Sent you a collaborator invite for my gamemode 👍

**Comment by xezno** [comment]
> Sent you a collaborator invite for my gamemode 👍

Thanks, pushed a fix - let me know if this works for you both

**Comment by Fortune117** [comment]
> > Sent you a collaborator invite for my gamemode 👍
> 
> Thanks, pushed a fix - let me know if this works for you both

Fixed for me now, thanks :)

**Comment by anthonysharpy** [comment]
works perfectly now thank you

**Comment by lotuspar** [comment]
lgtm, wonderful work!
