### ISSUE TITLE
Showing panels with pointer-events: all can reset view angle via Input.AnalogLook

### ISSUE THREAD

**Issue by the-remeko** [sboxgame/issues#2715]
### Describe the bug

When showing a panel with pointer-events: all that was previously hidden, the game will sometimes set Input.AnalogLook to a value that resets the player's view to where it was before the panel was hidden.
If the pointer-events: all element is nested inside of another element with pointer-events: none, the problem happens a lot more, and Input.AnalogLook is updated with actual mouse movement even while the pointer-events: all panel is shown (this can be desirable).

### To Reproduce

I have attached a project with a pointer-events: all element that is nested inside a pointer-events: none element. You can hold your View key (default C) to hide the panel. Just move your mouse around quickly while periodically pressing and releasing your View key.
If you change pointer-events to all for the "wtf" class in WTFHud.scss, the problem still sometimes happens.
[PointerAnalogLookTest.zip](https://github.com/sboxgame/issues/files/10315775/PointerAnalogLookTest.zip)

### Expected behavior

I should at least have the option to disable the panel's ability to mess with Input.AnalogLook.

### Media/Files

https://user-images.githubusercontent.com/94231804/209855559-e5f20ef2-a673-4d1e-8e10-9bb5ecbdff31.mp4

### Additional context

It seems like this is related to https://github.com/sboxgame/issues/issues/2706#issue-1510393620. The game resets the cursor position to where it was the last time the cursor was visible, and this sometimes affects Input.AnalogLook.

**Comment by DoctorGurke** [comment]
YES! This issue! I have been trying to get a consistent reproduction going for this for a while but never quite got there. In my experience anything with transitions is utterly fucked and certainly didn't help this issue either.

**Comment by the-remeko** [comment]
Closing since this seems to be fixed by the recent input update. Input.AnalogLook is also no longer updated while the pointer-events: all panel is shown in the setup I made, but there are probably workarounds for people that really want that.
