### ISSUE TITLE
Compiled Fog Lights Appear in Hammer

### ISSUE THREAD

**Issue by GunnarKafel** [sboxgame/issues#2719]
### Describe the bug

When I use a baked volumetric light and compile the map ingame, the fog from the compiled level shows up in Hammer.

### To Reproduce

1. Create a light with volumetric fog
2. Add a fog controller and volume
3. Compile the level
4. The compiled fog will appear in Hammer

### Expected behavior

The compiled fog shouldn't appear in Hammer, it makes it very difficult to make changes to fog once there is a built map.

### Media/Files

Baked fog in game 
![image](https://user-images.githubusercontent.com/65134886/210060110-ba665316-c289-4011-b6cb-040249df756d.png)

Hammer
![image](https://user-images.githubusercontent.com/65134886/210060180-c0bb7247-f52b-47be-80f8-d00b929cf1ef.png)

When you load the vmap for this you should see 2 fog beams, one is from the compiled level and the other is from Hammer.
Deleting the vpk will remove the compiled fog beam.
[baked_fog_reproduction.zip](https://github.com/sboxgame/issues/files/10324190/baked_fog_reproduction.zip)

**Comment by KayaDLX** [comment]
https://user-images.githubusercontent.com/67245359/220627648-d98ce5ef-c679-4d56-97fc-889b465952d3.mp4

Currently running into this issue, it even does it with dynamic fog

**Comment by GunnarKafel** [comment]
This has been fixed! Thank you so much sam :3
