### ISSUE TITLE
Property To Control Cubemap Blending Distance

### ISSUE THREAD

**Issue by GunnarKafel** [sboxgame/issues#2722]
### For?

Hammer

### What can't you do?

Right now cubemap blending is the same across all volumes. This is an issue for interior spaces with thin walls, since the cubemap has already blended out when it reaches the walls.

With `r_cubemap_debug_colors` enabled. Green is the exterior cubemap and purple is the interior. 
![image](https://user-images.githubusercontent.com/65134886/210124009-568c1d5a-792b-41b9-a901-23ea1c49fe0a.png)
![image](https://user-images.githubusercontent.com/65134886/210123962-d9bedaa2-1049-4089-beab-1fb6d9a25741.png)

### How would you like it to work?

A property on the cubemap entity that controls the distance until it's fully blended would be very helpful. This would let me set a much shorter distance so my interior walls are fully influenced, but also keep the longer blending between exterior cubemaps where space isn't an issue.

### What have you tried?

I can heavily increase the thickness of my walls, but that would introduce unrealistic proportions. I can also drag the volume outside of the room until the walls are influenced, but that would ruin the box projection and move the blending problem to the exterior. The only remaining solution would be to redesign the level around this issue, which isn't an appealing option.

### Additional context

Finding that this was the issue with my cubemaps was actually pretty difficult since s&box doesn't have a dedicated cubemap debug view. The cubemap debug colors just happened to be similar shades of green so the transition wasn't visible. #489 is exactly what I was looking for and would make debugging these problems much easier.

**Comment by KayaDLX** [comment]
https://user-images.githubusercontent.com/67245359/220184412-34814c98-6ff8-4ce2-9c42-114d633c1ebd.mp4

Yeah I have this annoying issue as well, it's always blending with the other nearest lightprobe on any volume, being able to set the blending distance would avoid this and allow me to only blend volumes with the ones I want

**Comment by samzanemesis** [comment]
We have this now 😘
