### ISSUE TITLE
Use `EqualityComparer<T>.Default` instead of `object.Equals(a, b)`

### ISSUE THREAD

**Issue by LeQuackers** [sboxgame/issues#2723]
### What it is?

I was looking through some classes to figure stuff out (`Var`, `NetworkBaseList<T>`, `PredictionDataStore`, etc.) and I noticed that `object.Equals(a, b)` is used in a lot of places.

### What should it be?

`EqualityComparer<T>.Default` should probably be used were applicable.

**Comment by handsomematt** [comment]
Is this actually causing any problems or what

**Comment by LeQuackers** [comment]
Not that I know of, but it'd be nice if sbox's internals supported `IEquatable<T>` out of the box for value types and reference types that have value equality (i.e. records).

For value types specifically, the `Object.Equals` method causes boxing and its default implementation is not very efficient because it uses reflection, so it's considered a best practice to use `IEquatable<T>` (which is called from `EqualityComparer<T>.Default`) whenever possible.

**Comment by LeQuackers** [comment]
Not even a low priority?
