### ISSUE TITLE
ShatterGlass is invisible 

### ISSUE THREAD

**Issue by TheBoxTrot** [sboxgame/issues#2728]
### Describe the bug

can't see the glass or the shards when shot but can hear it

### To Reproduce

load up construct or make a map with shatterglass entity and look

### Expected behavior

it be there

### Media/Files

![sbox-dev_3nyVkG55vp](https://user-images.githubusercontent.com/29888245/210165110-18b27c0d-2104-4462-90b0-deca5105c27d.png)

**Comment by aylaylay** [comment]
Should be fixed now
