### ISSUE TITLE
Water reflection seems to reflect underwater objects

### ISSUE THREAD

**Issue by Gmod4phun** [sboxgame/issues#2729]
### Describe the bug

The water reflections seem to be bugged, it looks like it is reflecting things that are under the water (which I don't think it should). Happens in tools mode and regular game mode.

![image](https://user-images.githubusercontent.com/5991682/210172733-2d1b8e1d-5d82-4a12-933b-dd135ad4900f.png)

You can also see the ladder underwater being reflected above the water surface:

https://user-images.githubusercontent.com/5991682/210172765-fb67246c-9f4a-4a50-ac23-ffae8e20c049.mp4

Water also is sometimes visible through walls.

### To Reproduce

Just spawn a bunch of stuff and see for yourself.

### Expected behavior

No glitches :)

**Comment by Moofers** [comment]
It seems to be the water reflections are reversed.

**Comment by Redhacker1** [comment]
@Moofers either that or they are not using clip planes to prevent pixels partially under the water from being processed.
