### ISSUE TITLE
Modeldoc crash

### ISSUE THREAD

**Issue by Unusuario2** [sboxgame/issues#2733]
### Describe the bug

when i try i import this fbx mesh modeldoc crashes

### To Reproduce

1. Download the zip
2. Change the file extension to .rar (.zip -> .rar) (Sorry but github wouldn't let me add the other parts of the .zip)
3. Extract the file
4. Open the model doc 
5. Go to File -> Import Model
6. Import the fbx model

### Expected behavior

Crash of ModelDoc

### Media/Files

https://user-images.githubusercontent.com/110506367/210460490-d82792b9-1abd-4de9-a03c-d24bc22c9c20.mp4

[cgaxis_american_elm_100_49_fbx.part1.zip](https://github.com/sboxgame/issues/files/10340440/cgaxis_american_elm_100_49_fbx.part1.zip)
[cgaxis_american_elm_100_49_fbx.part2.zip](https://github.com/sboxgame/issues/files/10340441/cgaxis_american_elm_100_49_fbx.part2.zip)
[cgaxis_american_elm_100_49_fbx.part3.zip](https://github.com/sboxgame/issues/files/10340442/cgaxis_american_elm_100_49_fbx.part3.zip)
[cgaxis_american_elm_100_49_fbx.part4.zip](https://github.com/sboxgame/issues/files/10340443/cgaxis_american_elm_100_49_fbx.part4.zip)

### Additional context

Windows 10 (x64)

**Comment by FireKeep-HLA** [comment]
I can't even download the model correctly, are you sure this isn't an issue on your end? How big is the model?

![image](https://user-images.githubusercontent.com/69137890/210469634-d5ba1fdc-d953-4e67-87e9-f1bcb2f9a265.png)

**Comment by Unusuario2** [comment]
hello, sorry for the inconvenience in this video I show how to unzip it,  git hub won't let me upload .rar files and files larger than 25 mb so i change the file extesion in order to upload to github (the model size is 120 mb)

https://user-images.githubusercontent.com/110506367/210531907-a4d1ddc6-d920-4535-821d-1c53e51a6909.mp4

**Comment by handsomematt** [comment]
it's a 120mb fbx
