### ISSUE TITLE
New Asset Browser is laggy

### ISSUE THREAD

**Issue by Mike466-0** [sboxgame/issues#2736]
### Describe the bug

When first typing in the asset browser before getting to a specific result Ex: letter a then typing to awesome. There is always a short delay between pressing the first key then finishing the oword

### To Reproduce

go to the asset browser
type something in

### Expected behavior

shouldnt be so laggy

**Comment by GrayWolf64** [comment]
This issue itself is a bit abstract and provides little information on the actual bug/problem.

**Comment by MikeShaughnessy** [comment]
> This issue itself is a bit abstract and provides little information on the actual bug/problem.
The bug is that it lags when loading a large amount of asset which results in lag everytime you start typing.

**Comment by GrayWolf64** [comment]
> > This issue itself is a bit abstract and provides little information on the actual bug/problem.
> > The bug is that it lags when loading a large amount of asset which results in lag everytime you start typing.

Oh, I see.

**Comment by TheBoxTrot** [comment]
are you sure it isnt stutters from the game compiling the models or materials your viewing as you type

**Comment by MikeShaughnessy** [comment]
> are you sure it isnt stutters from the game compiling the models or materials your viewing as you type?

It doesnt lag with the old asset browser
