### ISSUE TITLE
movement_path Doesn't Work.

### ISSUE THREAD

**Issue by yourbadandimbest** [sboxgame/issues#2738]
### Describe the bug

When I try to make a movement_path track for a moving platform I can't set OnPass output. In the outliner it looks like the `movement_path_node` is an invalid class.

### To Reproduce

1. Select path tool.
2. Place a few movement_path nodes.
3. Click on any of the movement_path's nodes.

### Expected behavior

The `movement_path` path should use valid nodes.

### Media/Files

![image](https://user-images.githubusercontent.com/91832803/210582596-9446493b-ac5e-4b94-82d2-e6bf173e2ef7.png)

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.

**Comment by yourbadandimbest** [comment]
Thank you
