### ISSUE TITLE
"Players" aren't being reported on the asset.party backend anymore

### ISSUE THREAD

**Issue by ShadowBrian** [sboxgame/issues#2740]
### Describe the bug

This happened a while back after a big API refactor I think.
Might be worth hooking back up.

### To Reproduce

I have multiple gamemodes with zero players reported at the moment.

### Expected behavior

I'd expect the players tab to either record who plays your game for how long, or to just not exist.

**Comment by garrynewman** [comment]
Should be back up to speed now (was using the wrong data source)
