### ISSUE TITLE
Collision doesn't update on animated props.

### ISSUE THREAD

**Issue by yourbadandimbest** [sboxgame/issues#2741]
### Describe the bug

When I use a prop_animated it doesn't update its collision when the physics body is animated. I have attached a few videos to demonstrate this in effect.

### To Reproduce

1. Parent a physics body to one of the bones in an animated model in the modeldoc.
2. Place a prop_animated with the model and select an animation.
3. Play the map.

### Expected behavior

If a physics body moves in an animation the prop_animated should update its collision realtime to match. If that is too taxing it could also be a setting.

### Media/Files

In modeldoc:

https://user-images.githubusercontent.com/91832803/210655785-d343c9ec-14c4-4bfd-a468-61d23b9be5ca.mp4

In game:

https://user-images.githubusercontent.com/91832803/210656086-ee69f2c7-6f83-4d1e-abc7-ab3883d48a74.mp4

The prop_animated only uses the physics of when the first map loaded. The left prop_animated has default animation opened, while the right has default animation closed.

https://user-images.githubusercontent.com/91832803/210656443-5ad3ca3c-0ad1-4539-88d9-8fc03c1adc4b.mp4

**Comment by aylaylay** [comment]
You probably need to set DoAnimateOnServer

**Comment by yourbadandimbest** [comment]
That was it. I don't know how I missed that, sorry!
