### ISSUE TITLE
Template .editorconfig doesn't apply to razor files

### ISSUE THREAD

**Issue by lotuspar** [sboxgame/issues#2742]
### Describe the bug

The game template .editorconfig only applies to `*.cs` files. The one in the game root does seem to handle razor files correctly but this isn't applied

### To Reproduce

I'm using the game template in Rider

### Expected behavior

Code style should be applied to razor files

**Comment by xezno** [comment]
Should be fixed on next update. I don't think this makes a difference to visual studio (doesn't seem to support formatting razor files) but IDEs that do support this should benefit.
