### ISSUE TITLE
Steam offline - causes editor and game to crash.

### ISSUE THREAD

**Issue by harbour0** [sboxgame/issues#2743]
### Describe the bug

When the steam network is down ->

You are unable to use the editor and game client. It results in a crash with an "Backend error - returned Unauthorized".

Also: "Could not establish connection to steam servers.."

### To Reproduce

1. Steam offline (downtime)
2. Launch sbox with editor. 
3. Load local gamemode
4. Error should occur within 2-5 mins.

### Expected behavior

With steam being up 99% of the time this is probably a rare issue to encounter but logged it anyway.

I assume you would want to allow "offline" access.

### Media/Files

![image](https://user-images.githubusercontent.com/110195246/210898251-7c0a7270-1cce-4402-8345-354b327dbbb6.png)
![image](https://user-images.githubusercontent.com/110195246/210898260-3f331bb0-9a34-4b1f-8e98-8a92528ba81b.png)
![image](https://user-images.githubusercontent.com/110195246/210898270-98ab1c2b-e0f5-47aa-9a77-4f54dc1fa82a.png)

### Additional context

I assume security / piracy issues are the result of said crash.

**Comment by handsomematt** [comment]
When you say crash do you just mean that small error message

**Comment by harbour0** [comment]
> When you say crash do you just mean that small error message

The whole editor and game physically crashed. I was unable to use editor and game while Steam was offline yesterday.

**Comment by trende2001** [comment]
I guess this is kind of an issue sometimes. It depends on the steam servers, but mostly no issue because they are always up. I don't know about a fallback server or something

**Comment by harbour0** [comment]
> I guess this is kind of an issue sometimes. It depends on the steam servers, but mostly no issue because they are always up. I don't know about a fallback server or something

I only had this issue with the unexpected downtime earlier last week. I've tried to see if I can replicate this with ensuring no internet is coming into PC but this doesn't seem to happen. It seems to only happen if Steam servers are not available but internet is available I believe. 

I was still getting the backend error message as shown above but no crash..

**Comment by trundler-dev** [comment]
I have never experienced this before. Are you sure you weren't running into an unrelated crash while the servers were down?

**Comment by harbour0** [comment]
> I have never experienced this before. Are you sure you weren't running into an unrelated crash while the servers were down?

I don't believe I had made any code changes / breaking code prior to the steam servers being down. 

However there is a chance it could be an unrelated crash due to the fact I can't replicate the issue.
