### ISSUE TITLE
Player becomes invincible from bullets with certain clothing

### ISSUE THREAD

**Issue by Bagtock** [sboxgame/issues#2747]
### Describe the bug

If you equip certain clothes player becomes invincible from bullets (but not from explosions or prop impact)

### To Reproduce

You need to equip any t-shirt, pants, gloves, boots and specifically knight's helmet ¯\_(ツ)_/¯
Wont work if some clothes aren't equipped

### Expected behavior

Can't be killed with bullets
Other players can't grab you with phys gun

### Media/Files

https://user-images.githubusercontent.com/74205853/211083494-1727022d-76d3-40a2-be79-1dd7c36f7166.mp4

**Comment by harbour0** [comment]
@Bagtock Is this related to this issue I posted a while ago?
https://github.com/sboxgame/issues/issues/2124

**Comment by handsomematt** [comment]
I've disabled clothes dressed on an entity from having traces enabled at all (games will need a reupload to take base changes), so long as a trace is using `UseHitboxes()` it should work fine.

![image](https://user-images.githubusercontent.com/1388267/211091175-385d10e2-9bde-4e5c-9b18-334321588c3a.png)

**Comment by Bagtock** [comment]
> @Bagtock Is this related to this issue I posted a while ago? #2124

It seems to be about the same. I didn't do a good search.
