### ISSUE TITLE
Nested partial class files with Razor files

### ISSUE THREAD

**Issue by harbour0** [sboxgame/issues#2748]
### For?

Other

### What can't you do?

With the introduction of Razor to S&box I thought it would be cool if we could see the feature of having nested C# files associated to the said Razor file.

Blazor currently does this and it makes a solution look and feel a lot cleaner and helps with organisation. 

![image](https://user-images.githubusercontent.com/110195246/211091339-7a6e05b6-b251-45e7-8e7a-f4d317cb64dc.png)

### How would you like it to work?

1. User creates a razor file: "Scoreboard.razor".
2. User then creates a partial class file named "Scoreboard.razor.cs".

> Partial class automatically gets nested under "Scoreboard.razor". 

### What have you tried?

Using custom file nesting settings with the rule "addedExtension" allows for this to work. 
![image](https://user-images.githubusercontent.com/110195246/211092239-33c1b361-b876-4f6f-bd2f-7fab8754a349.png)

![image](https://user-images.githubusercontent.com/110195246/211092214-739d0624-d981-49b5-91c1-52ae706f3b96.png)

Just thought it would be good to have baked in from the get go.

**Comment by DevulTj** [comment]
I think we'd rather not include a filenesting.json in projects - I gave this a look a few months back to see if we could use the csproj but it doesn't look like Visual Studio supports what we want - to show razor files independently and also show nested razor files.

Not worth the hassle, unless someone figures out an alternative method.
