### ISSUE TITLE
Box shadow no longer gets clipped by `overflow: scroll;`

### ISSUE THREAD

**Issue by matekdev** [sboxgame/issues#2753]
### Describe the bug

If you use `box-shadow` on an element in a scrollable list, it will no longer be hidden by `overflow: scroll;`

### To Reproduce

1. Create a scrollable list with `overflow: scroll;`
2. Make sure the items have some box shadow on it
3. Check out the video, notice that they don't get clipped.

If you want, you can launch up `TTT`, start a round, set yourself to traitor or detective `ttt_setrole traitor`, and view the shop menu via C.
https://github.com/CigarLounge/sbox-TTT/tree/main/code/UI/Player/RoleMenu/Shop

### Expected behavior

The box shadow should be hidden.

### Media/Files

https://streamable.com/4we4r5
![image](https://user-images.githubusercontent.com/32153021/211216415-68175b84-9dba-40a0-9100-6d89396f82b5.png)

**Comment by handsomematt** [comment]
oops oversight by me, thanks for the issue. I've made it respect the original overflow again this is what it looks like for me now which I believe is correct, let me know if not though

![image](https://user-images.githubusercontent.com/1388267/211219271-99a2dac6-213f-417c-a3ef-349a84fc96f2.png)

**Comment by matekdev** [comment]
Yeah works now, appreciate all the UI fixes recently.
