### ISSUE TITLE
Tags in `Hitbox` are internal with no way to retrieve them

### ISSUE THREAD

**Issue by matekdev** [sboxgame/issues#2754]
### What it is?

Same issue as https://github.com/sboxgame/issues/issues/2675
I want to be able to access the tags inside of a `Hitbox` so I can network them.

### What should it be?

The tags inside of `DamageInfo.Hitbox` should be public so we can see what is inside them (right now the only way is through bools).

**Comment by Ephememory** [comment]
Also, at this point it seems like `DamageInfo` could probably be moved out of managed Sandbox.dll and into the base addon. That way projects can modify, replace or not use it at all. I'd understand `Hitbox` being a bit iffy and left in since models use them, making it closer to the engine.

**Comment by DevulTj** [comment]
Can you describe the use case for this?

**Comment by matekdev** [comment]
if you are asking me, I need to network the hitbox tags from a server to a client. We display various UI elements depending on what hitbox was hit. Very similar to the previous issue with tags on damageinfo.

I can get around it by checking to see if the original damage info hitbox has x tag (via the bool functions), adding the appropiate tag to the damage info, then networking those tags. I would be nice if we just had access to all the tags directly though.

**Comment by garrynewman** [comment]
You know @DevulTj, we should probably make the hitbox/damageinfo tags a generic stringtoken list struct that can be networked around (as a list of ints). That'd help retain its main purpose of being fast and small, while giving some extra functionality.

**Comment by Fortune117** [comment]
> Can you describe the use case for this?

It would let me aggregate these two tag lists into one object for the purpose of this function:

```CS
    public LimbBase GetLimbFromDamageInfo(DamageInfo info)
    {
        var hitbox = info.Hitbox;
        
        if (hitbox.HasTag(StalkerTags.HitBox.Head) || info.HasTag(StalkerTags.HitBox.Head))
            return Head;

        if (hitbox.HasTag(StalkerTags.HitBox.Chest) || info.HasTag(StalkerTags.HitBox.Chest))
            return Chest;
        
        if (hitbox.HasTag(StalkerTags.HitBox.Stomach) || info.HasTag(StalkerTags.HitBox.Stomach))
            return Stomach;

        if (hitbox.HasAllTags(StalkerTags.HitBox.Arm, StalkerTags.HitBox.Left) || info.HasAllTags(StalkerTags.HitBox.Arm, StalkerTags.HitBox.Left))
            return ArmLeft;
        
        if (hitbox.HasAllTags(StalkerTags.HitBox.Arm, StalkerTags.HitBox.Right) || info.HasAllTags(StalkerTags.HitBox.Arm, StalkerTags.HitBox.Right))
            return ArmRight;

        if (hitbox.HasAllTags(StalkerTags.HitBox.Leg, StalkerTags.HitBox.Left) || info.HasAllTags(StalkerTags.HitBox.Leg, StalkerTags.HitBox.Left))
            return LegLeft;
        
        if (hitbox.HasAllTags(StalkerTags.HitBox.Leg, StalkerTags.HitBox.Right) || info.HasAllTags(StalkerTags.HitBox.Leg, StalkerTags.HitBox.Right))
            return LegRight;

        return null;
    }
```

**Comment by matekdev** [comment]
no longer relevant
