### ISSUE TITLE
Automatic texture resizing to powers of 2

### ISSUE THREAD

**Issue by Ceiridge** [sboxgame/issues#2758]
### For?

Material Editor

### What can't you do?

Easily load textures that have a square aspect ratio, but are not a power of 2

### How would you like it to work?

Automatically resize the texture to the nearest power of two, preferably to the higher one.
The user could get a warning with a message box that can be declined, in which case the texture is not resized.

Potentially, if the color texture is not a square, a translucency map could be set up automatically, too, although I'm not sure if translucency works like this.

### What have you tried?

(Loading a texture that is not a power of 2)

**Comment by handsomematt** [comment]
You should be able to use non power of 2 textures just fine, no?

**Comment by DeltaDesigns** [comment]
Bumping this ancient issue, though its not a huge deal, it would be convenient. It seems non-power of 2 textures were allowed at one point but was changed?
![image](https://github.com/user-attachments/assets/cb2f05bc-fb43-44fc-a8d2-b650805dab39)
