### ISSUE TITLE
-dev breaks game

### ISSUE THREAD

**Issue by SplatzyXD** [sboxgame/issues#2761]
### Describe the bug

Everytime i put -dev into the launch params it crashes it used to always work it broke one day then worked the next day. and now its broken again

### To Reproduce

Go to Properties
put -dev in the launch options
Launch the game in regular mode

### Expected behavior

It should give you an error window as seen in media.

### Media/Files

![image](https://user-images.githubusercontent.com/101920640/211612320-3152a744-b40d-4bff-b0a0-4a35511b28d8.png)

### Additional context

I'm on windows 10 
Specs.
RX 580
32 GB DDR4 Ram
AMD ryzen 5 2600x

**Comment by SplatzyXD** [comment]
i was told in the past to fix files as that did not work but then worked the next day so i believe it just randomly breaks

**Comment by handsomematt** [comment]
Delete addons/base, addons/menu and verify your game files
