### ISSUE TITLE
Add Source2 legacy model editor for models with complex morphs

### ISSUE THREAD

**Issue by BaboDragon** [sboxgame/issues#2763]
### For?

S&Box, Source Film Maker, Other

### What can't you do?

The new ModelDoc is great and better than the old legacy Modeleditor, but it just cant handle complex morph setups, like Corrective Shapekeys, Dominators and Supressors. Since Sbox is already capable of using models compiled by the legacy ModelEditor from HL-Alyx, I dont think it would be to much trouble to add it.

### How would you like it to work?

It should be added and get its own icon under the ModelDoc editor in Developer Tools and that is basically all.

### What have you tried?

I tried a lot to make Complex morphs work in ModelDoc, I even Issued a Bug here since it aint working as intended. It sure is not easy to fix, so I though it would be easier to add the legacy ModelEditor, so its dealth with, for now.

**Comment by DoctorGurke** [comment]
Surely these features should just be added to modeldoc instead of making/supporting a totally separate but similar tool?

**Comment by aylaylay** [comment]
Please open an issue with the actual issue. We're not going to add an old tool.
