### ISSUE TITLE
[Security] [Compatibility] Patching in addition of wrapping.

### ISSUE THREAD

**Issue by Sl4vP0weR** [sboxgame/issues#2765]
### What it is?

As we know, main Core library have vulnerable parts which is not safe for the game and OS.
**Facepunch** restricted access to this via whitelisting & wrapping/recreating code.
I have some thoughts about not just wrapping/recreating existing code, but patching original methods.

We can pick `System.IO` namespace and code from it as example:
For example, we need to have access to the file system, files/folders.
In default .NET workspace we could use `System.IO.File` for read/write access of a file.
In the game workspace we can use `Sandbox.BaseFileSystem Sandbox.FileSystem.Data` property that wraps the code and makes it more safe to use cause it's scoped to ingame directory.

### What should it be?

We can patch methods like `System.IO.File.ReadAllText` to redirect us to `FileSystem.Data.ReadAllText` cause eventually it's the same approach to read all text from file.

**Same we can do with other Core library code.**

**Why is this important?**: 
_Other libraries & code bases already using `System.IO` namespace by default._
_With this approach it will not break everything and will allow to use external libraries that's not using Sandbox code._

**How Facepunch can make it easier to do:**
1. _Create internal attribute `PatchAttribute` in which you can set methods that should be patched to redirect to this method._
2. _Patching can be done by hooking the methods(in order to do something like this, we can look into Harmony.Lib implementation, used for Mono and Unity, maybe not the best way to do it)_
3. _Patch all entries on the game load and it's done._

**Comment by Sl4vP0weR** [comment]
@handsomematt 
What do you think is wrong with this? 
Please, let me know!
Thumbs down not tells to me much about your thoughts.

**Comment by DevulTj** [comment]
This isn't practical
