### ISSUE TITLE
We need Super LODs for open worlds

### ISSUE THREAD

**Issue by redesaile** [sboxgame/issues#2768]
### For?

S&Box

### What can't you do?
If i create world lods, i will have to deal with the problem of an increased number of draw calls. This problem appears because when the large world lod appears, many smaller props are still active, because their origin is not in the center of the huge model, therefore, they will be displayed along with the world lod for a while.

### How would you like it to work?

For a better understanding, I will divide the lod of a piece of the world (world lod/environment lod) into 3 categories - **Super LOD**, **Medium LOD** and **Reference**, where...
- **Super LOD** - a large model containing a low-detailed version of a piece of the map;
- **Medium LOD** - a model containing low-detailed version of merged objects;
- **Reference** - the original piece of the map, containing many models, and used in the creation of Medium LOD and Super LOD.

### Engine
For this system to work, it is necessary to extend the **prop_static** functionality by adding two string parameters `Name` and `Parent` to it, where...
- **Name** - well, it's just the name used in **Parent**;
- **Parent** - the name of one of the previously listed categories.

### Editor
Let's imagine that I have already created the necessary models based on the **Reference**. What now?

**Now I have to do these things:**
1. I place all static props;
2. I specify names for Super LOD and Medium LOD objects;
3. I specify Medium LOD as a parent for Reference(-es);
4. I specify Super LOD as a parent for Medium LOD;
5. Well, I did everything necessary and now I can look at how one category replaces another.

### Functions
* When the Activator reaches the certain Super LOD switching threshold, disable Super LOD and enable Medium LOD for the Activator.
* When the Activator reaches the certain Medium LOD switching threshold, disable Medium LOD and enable Reference for the Activator.

### Not a very good scheme of how it works
![slod](https://user-images.githubusercontent.com/90133781/211832673-b90f65b5-f2a3-4f85-8a69-7e7edf58b236.png)

### Examples from Grand Theft Auto V
**Reference and Medium LODs**

https://user-images.githubusercontent.com/90133781/211817863-022b273a-e596-49c5-88b6-7f49dfaadf93.mp4

https://user-images.githubusercontent.com/90133781/211820907-80e1bdd0-523e-45f6-b008-9ea86df5e09f.mp4

---

**Super LOD**

https://user-images.githubusercontent.com/90133781/211817885-e9045e2d-5036-445c-8a0b-8c702f810ef4.mp4

### What have you tried?

1. Get over it and start making do with what I have.
2. Split the map into many squares, 400 by 400 meters each, thereby worsening the optimization.

### Additional context
I work in a team that develops role-playing project. For this project, we are creating a large map (≈15 km), but at the stage of thinking about future optimization, there was a problem with creating the level of detail of the world.

What I described above is used by **Rockstar Games** in their latest games. Their games use a lot more world lod models, but anything that isn't super lods they just call lods.

I hope I wrote clearly what I would like to see.

**Edit:** There is a similar technology in Unreal Engine. See [Hierarchical Level of Detail](https://docs.unrealengine.com/5.2/en-US/hierarchical-level-of-detail-in-unreal-engine).

**Comment by AngryNeox** [comment]
I wonder if a similar feature could somehow be added to map prefabs? Every static mesh within a prefab could be disabled at a set distance and be replaced with a single (LOD) mesh for the whole prefab. With the option to put prefabs inside prefabs you could have as many LOD levels you want and combine them in any way you want.

**Comment by Titanovsky** [comment]
This thing is good for open worlds.
