### ISSUE TITLE
`requested missing file (postprocess/objecthighlight/highlight_object.shader_c)` 

### ISSUE THREAD

**Issue by timmybo5** [sboxgame/issues#2778]
### Describe the bug

When starting a multiplayer game with any gamemode some players will be unable to join and will be kicked with this error: `requested missing file (postprocess/objecthighlight/highlight_object.shader_c)`. 

Not sure what causes this but the fix is that the host removes that shader from `sbox\addons\base\Code\PostProcess\ObjectHighlight`.

**Comment by DevulTj** [comment]
Should be fixed now
