### ISSUE TITLE
Animgraph - Parameter presets

### ISSUE THREAD

**Issue by KaesarZZ** [sboxgame/issues#2779]
### For?

S&Box

### What can't you do?

When you get a big enough animgraph it's a pain to have to be editing parameters all the time you want to test a specific animation. 

### How would you like it to work?

It would be nice to have an option to save the current edited parameters/the ones you are interested in testing and use them with 1 click.

Example:

Ladder up: "b_ladder" on + "move_z" +56

### What have you tried?

Edit parameters every time I test the animgraph.

**Comment by aylaylay** [comment]
Done - params are saved going to and from preview
