### ISSUE TITLE
cvar setang and setpos not working

### ISSUE THREAD

**Issue by SryEyes** [sboxgame/issues#2780]
### Describe the bug

the cvar setang doen't work at all and overloading setpos should change the angle too - but doesn't

### To Reproduce

write "setpos 0 0 0 0 0 0" or "setang 0 0 0" in console

### Expected behavior

Angle should change to 0 0 0 but doesnt change at all

**Comment by garrynewman** [comment]
I removed these because they seemed dumb, can you explain how/why they're used?

**Comment by SryEyes** [comment]
Thx for the fast response.
I used them for quick testing stuff and was confused they didn't work after vacation. Pretty useful for map comparisons and also for testing my lockpick minigame which is angle based.
I feel like these cmds are nice to have since changing angles in code just to see if something works / or looks good in that specific angle seems a bit off. Quite a nice thing would also be that one argument in these cvars would be the index of the entity wich executes that cmd.
For me personally the tools provided to create stuff like animgraph are great but when it comes to easy testing stuff ingame s&box lacks features out of the box. Especially when it comes to things you aren't able to calculate the best value like what leaning angle in an fps is looking good and hits the sweet spot or water reflections in specific angles . Having some basic cvars like that one would contribute fixing that. 
cl_showpos and other nice to have cvars are already removed and since getpos still works and prints out a c&p ready "setpos *Origin* *Angles*" not being able to use this is a missed opportunity for quality of life.

**Comment by bakscratch** [comment]
Does the inspector not achieve this? Can edit the values.
![image](https://user-images.githubusercontent.com/8184184/212500043-a289bc77-fecf-4408-8d4b-0dafcbbf3f89.png)

**Comment by SryEyes** [comment]
not outside of the tools mode and its doesn't support the fast c&p ready solution like getpos / setpos does

**Comment by SryEyes** [comment]
Edit: editing the values in the inspector doesn't seem to work for me at all
