### ISSUE TITLE
map Addons Do not Work

### ISSUE THREAD

**Issue by TheBoxTrot** [sboxgame/issues#2781]
### Describe the bug

entities added with map addons show up in hammer. but when you try and run the map 
![image](https://user-images.githubusercontent.com/29888245/212468029-669dbd88-0815-4ba5-b173-4fd45d6c9153.png)
you get this error

this happens on local map versions published map versions published addon local addon all the different ways you can do it

### To Reproduce

create a map addon.
put the entity in the map,
run the map,
check console Create

### Expected behavior

the entity is loaded into the map

**Comment by QuackCocaine** [comment]
A similar thing happens with soundscape assets  when placed in a map addon but then they load fine when in a content addon

**Comment by handsomematt** [comment]
Pretty sure these are all good now.
