### ISSUE TITLE
VC causing lag spike

### ISSUE THREAD

**Issue by DeeMoney7** [sboxgame/issues#2783]
### Describe the bug

Every time I try to use voice chat the game lags big time. 

Some people have said it happens for them too... but only the first time they try to use VC. This is persistently happening to me every time I try to use voice. 

I restarted steam, my pc, reinstalled the game. Issue persists.

### To Reproduce

1: Load Game
2: Join Server
3: Attempt to use VC

### Expected behavior

No Lag

### Media/Files

https://user-images.githubusercontent.com/80512693/212519772-c2ab2f65-1d72-40c5-82ee-014571b2266e.mp4

**Comment by xezno** [comment]
Closing in favour of #3026
