### ISSUE TITLE
Filemanagement for Projects on asset.party

### ISSUE THREAD

**Issue by Andiq** [sboxgame/issues#2785]
### For?

Other

### What can't you do?

Please make it clean up stuff on asset.party and not just add to it. I added a skybox to my map for testing. Uploaded it and now after i have removed it its still in my project on asset.party.

### How would you like it to work?

Please make it compare the contents of the Project folder with the currently uploaded last version and remove files that you dont have in your Project folder anymore.

### What have you tried?

I have changed the skybox back but it wont remove it from asset.party .

**Comment by handsomematt** [comment]
When you upload a new version of your map it will only upload the referenced files. It's not going to delete the skybox from your current map version.

**Comment by Andiq** [comment]
What i meant is clean up the uploaded parts on asset.party.
