### ISSUE TITLE
Local lan connections are busted

### ISSUE THREAD

**Issue by matekdev** [sboxgame/issues#2786]
### Describe the bug

1. Have one client host and play my game (with `sv_lan 1` enabled)
2. Have another client on the SAME machine join the game (`connect localhost`)
3. I get an `INVALID` error

### To Reproduce

1. Have one client host and join the game
2. Have another client on the SAME machine join the game
3. Notice the second joining client gets the error posted below

### Expected behavior

Should be able to run multiple clients on the same machine for debugging purposes

### Media/Files

![image](https://user-images.githubusercontent.com/32153021/212555829-f8e3db7b-5d5a-4449-b05a-9dcac2709796.png)

**Comment by anthonysharpy** [comment]
i've heard that you also need sv_lan 1 on the joining client as well. not sure if that will make a difference in your case though.

**Comment by matekdev** [comment]
nah doesn't make a difference, but thanks for the comment.

**Comment by DoctorGurke** [comment]
You enabled sv_lan before you opened the host server, right?

**Comment by handsomematt** [comment]
This was a bad file path, now fixed
