### ISSUE TITLE
Draw 3D Skybox Render Option

### ISSUE THREAD

**Issue by GunnarKafel** [sboxgame/issues#2789]
### For?

Hammer

### What can't you do?

In Hammer I can only toggle the entire skybox, both 2d and 3d. I'd like to be able to toggle just the 3d sky while keeping the background.

### How would you like it to work?

A toggle in the lighting dropdown for the 3d sky would be lovely!
![image](https://user-images.githubusercontent.com/65134886/212819874-44af7817-d859-4276-8ab4-7a32c8fe3871.png)

### What have you tried?

The console command `r_3d_skybox` affects Hammer as well, but it'd be nice to be able to toggle it without going to the console.

**Comment by aylaylay** [comment]
Done

**Comment by GunnarKafel** [comment]
Works perfect, thank you!
