### ISSUE TITLE
VC Lag Spike

### ISSUE THREAD

**Issue by dazd-pkz** [sboxgame/issues#2792]
### Describe the bug

Everytime i press V (my voice button) my game freeze for like 2-3 seconds and sometimes, when i release the button, it freeze for 1 sec (most of the time it just don't freeze)

### To Reproduce

Launch any game
Press Voice button
GET FREEZED LIKE BRRRR

### Expected behavior

Just having a smooth game with no freezes

### Media/Files

https://user-images.githubusercontent.com/87366355/213159323-f6a72444-1b51-48c5-b0bb-b78fd00856b0.mp4

(needed to compress it cause too large)

### Additional context

OS: Windows 10
GPU: RTX 3060 TI GIGABYTE EAGLE OC
CPU: I7 7800X (eXtreme)
RAM: 32 GB (3600mhz) Corsair Vengeance RGB PRO SL
DRIVE: SSD NVME M.2 WESTERN DIGITAL BLUE SN570 1TB

**Comment by harbour0** [comment]
Is this the same issue? https://github.com/sboxgame/issues/issues/2783

**Comment by Dazd-Pkz** [comment]
yes but with more important information like a record of the perf graph

**Comment by JustPlayerDE** [comment]
i also noticed a "lag" spike in my game if i try to use the voice chat (noticed with the graph)
it seems like the spike only happens at the first time and after a delay of usage

**Comment by xezno** [comment]
Closing in favour of #3026
