### ISSUE TITLE
Cloud assets not loading in Assets Browser

### ISSUE THREAD

**Issue by yuberee** [sboxgame/issues#2797]
### Describe the bug

Inside of the Assets Browser, also in the Hammer version, the asset.party section is empty.
No cloud assets are show, even when searching for them.

### To Reproduce

Open Assets Browser and select asset.party

### Expected behavior

To load and view the cloud assets

### Media/Files

![image](https://user-images.githubusercontent.com/59583743/213541674-22458bd6-4837-411a-9043-8be1e81b1fd2.png)
![image](https://user-images.githubusercontent.com/59583743/213542410-66ebf1ec-42bd-4bd9-8620-2cd7674047d6.png)

### Additional context

I've made sure that I wasn't accidentally filtering out anything.
I also cleared my cookies and verified game files integrity.
Oddly enough, when searching for something, the categories will pop up on the left, but they will return 0 results.

**Comment by MathieuRelmy** [comment]
The issue does not limit to the editor's Asset Browser. The same bug happens in game when trying to fetch asset.party content :

![image](https://user-images.githubusercontent.com/60399897/213584428-0c8799f0-f652-446a-8d01-f3a776e75b98.png)

The yielded error is the same as the one the editor returns which is **`"Couldn't deserialize Sandbox.Api+Packages+Find".`**

**Comment by DevulTj** [comment]
A fix for this should be live within 15 minutes. If you believe it's fixed, please close this issue. ❤️

**Comment by yuberee** [comment]
Alright seems to be working now! Thanks Devul2K23
![image](https://user-images.githubusercontent.com/59583743/213647778-9faa538b-8937-427b-b25b-88a8a5f6673d.png)
