### ISSUE TITLE
Asset.Party login issues.

### ISSUE THREAD

**Issue by TheJaxophone** [sboxgame/issues#2799]
### Describe the bug

Asset.Party website states "There was a problem authenticating your login with Steam" after attempting to log in, persists after clearing cookies, restarting browser, and restarting PC. Does not work on mobile browser either.

### To Reproduce

1. Click the log in button on the asset.party home page.
2. Log in using my Steam account and authenticating with the mobile app.
3. Log in prompt pops up again, log in again.
4. Sends me back to the home page and displays the error message as shown in the screenshot.

### Expected behavior

It should only prompt me once to log in, and it should allow me to log in and access the website,

### Media/Files

![image](https://user-images.githubusercontent.com/44627230/213610078-ad47835c-2ed4-4754-80a5-a3a102a2a159.png)

### Additional context

Windows 10, tried on Chrome mobile and on my PC using both chrome and edge.

**Comment by handsomematt** [comment]
i'd imagine steam was down at the time or something
