### ISSUE TITLE
Screen Space Particles Are Always White

### ISSUE THREAD

**Issue by Fortune117** [sboxgame/issues#2805]
### Describe the bug

My screen space particles, which should be black, appear as white both in game and in the particle editor:
![image](https://user-images.githubusercontent.com/7847372/213840451-05ab2b6f-a0bc-4ecc-90d0-bd2537d474b1.png)

However, when the same vpcf is used in the Dota 2 particle editor it looks as it should (thanks bakscratch):
![image](https://user-images.githubusercontent.com/7847372/213840462-272384be-42cd-4474-9476-f8a0ffb5b7fc.png)

### To Reproduce

1. Open the provided vpcf
2. See the particles are white despite the color blend

### Expected behavior

Colors appear as the expected color.

### Media/Files

Here is the vpcf I used
[psy_screen_smoke.zip](https://github.com/sboxgame/issues/files/10471371/psy_screen_smoke.zip)

**Comment by samzanemesis** [comment]
Should be gucci, I went and cleaned up how screenspace translucents are rendered as well, will be live soon
![image](https://user-images.githubusercontent.com/6563447/220636717-a8462220-854a-4a9a-8a38-7effa3dd17c1.png)

**Comment by Fortune117** [comment]
It's much better now, but I noticed a strange flickering when I tested it:



https://user-images.githubusercontent.com/7847372/220676807-e81ff788-0fdb-4c70-b357-d262973f95e5.mp4


Heres the vpcf from the clip: [claw effect.zip](https://github.com/sboxgame/issues/files/10805676/claw.effect.zip)

**Comment by Fortune117** [comment]
By setting diffuse lighting to zero for the sprite renderer, the flickering went away entirely.

![image](https://user-images.githubusercontent.com/7847372/220789968-27404772-afae-4570-8479-e6e441b97568.png)

**Comment by samzanemesis** [comment]
I can't replicate that flicker, I've put some changes to make sure we're passing lighting constants properly to the screenspace layer though, although I think for 99% of cases you'd never really use lit particles on screenspace

**Comment by Fortune117** [comment]
alrighty, thanks Sam!
