### ISSUE TITLE
Mounted Packages Don't Automatically Download/Mount for Clients Anymore

### ISSUE THREAD

**Issue by Fortune117** [sboxgame/issues#2806]
### Describe the bug

On my gamemode Ghosts of the Zone, the model for the player is set through asset party and has been for some time:

```CS
       // called every respawn
	private async Task SetCloudModel()
	{
		Log.Info("-----------------------FETCHING MODEL-----------------------");
		var package = await Package.Fetch("https://asset.party/sboxmp/stalker_dolg", false);

		var model = package.GetMeta( "PrimaryAsset", "models/dev/error.vmdl" );

		await package.MountAsync();
		
		Log.Info(model);
		SetModel(model);
	}
```
Before, players automatically downloaded the model from asset party upon joining the host and it all worked nicely.

Right now the host sees the models fine:
![image](https://user-images.githubusercontent.com/7847372/213862583-d2267214-32b6-426d-8a30-33a2e4873d95.png)

But clients who join just see an error:
![image](https://user-images.githubusercontent.com/7847372/213862611-cfa54e33-91d1-4d04-abc3-bf873cda7eff.png)

### To Reproduce

1. Create a game of Ghosts of the Zone
2. Connect to the game from a second client (bug works even on locally hosted games from the same computer)

### Expected behavior

Model is visible for everyone

**Comment by Fortune117** [comment]
confirmed this happens in the sandbox gamemode as well:
![image](https://user-images.githubusercontent.com/7847372/219966488-e9977a23-3dda-4f93-a486-49ac6659500b.png)

**Comment by garrynewman** [comment]
Should be fixed now
