### ISSUE TITLE
[Input] Replace .Using* with .PreferredInput

### ISSUE THREAD

**Issue by Weldify** [sboxgame/issues#2812]
### What it is?

`Input.UsingMouse` and `Input.UsingController` should be removed.

### What should it be?

Instead of them, there should be an enum `Input.PreferredInput`.
This is better because the 2 properties that we have now do the same thing as this, but my suggestion is a lot more concise and scalable. It will also make rebuilding glyph ui easier!

(`PreferredInput` might not be the best name, you could go with just `Preferred` or `PreferredInputType`)

**Comment by handsomematt** [comment]
It's not really a preference though, it's what input the user is using right at that moment.

And you shouldn't need to rebuild your glyph UI, the API is designed so you can call it every frame and not care.

**Comment by Weldify** [comment]
In any case, using this would make hashing for UI more convenient and would still be faster (wouldn't matter at that scale though)

Perhaps this should be added but the old properties should be kept?
