### ISSUE TITLE
Soundscapes don't play on local map, only uploaded/mounted versions do

### ISSUE THREAD

**Issue by KayaDLX** [sboxgame/issues#2814]
### Describe the bug

Whenever I tried setting a soundscape in my map, I could only fully preview it in game once the map was uploaded and I was playing the uploaded version instead of my local one.

### To Reproduce

1. Place any generic soundscape in your map
2. Try to preview it in your local map (won't work)
3. Upload your map
4. Try to preview it in your uploaded map (will work)

### Expected behavior

Should play regardless of being uploaded or not.

**Comment by handsomematt** [comment]
Are these local soundscapes or cloud soundscapes?

**Comment by robotboy655** [comment]
Would be nice to have an example map that reproduces the issue, at at the very least console logs when it doesn't work for you.

**Comment by KayaDLX** [comment]
> Are these local soundscapes or cloud soundscapes?

Local soundscape I made myself

**Comment by robotboy655** [comment]
I have applied a change that should fix the problem if your soundscapes were in a map addon. If the next update does not fix the issue for you, please let us know where **exactly** are your soundscape and map files are stored.

**Comment by KayaDLX** [comment]
It works locally now (and for the record, my soundscape was in fact in a map addon).
I've also noticed a strange behaviour with soundscapes where they always seem to take a few seconds before actually playing in game, regardless of being local or not.

https://user-images.githubusercontent.com/67245359/214913120-183e4401-4463-4b31-8928-115597727dc3.mp4

**Comment by robotboy655** [comment]
Yeah, it's a PVS issue that's unrelated to this issue.

**Comment by KayaDLX** [comment]
Gotcha, thanks for the above fix!
