### ISSUE TITLE
Hammer clipboard data on the system clipboard

### ISSUE THREAD

**Issue by KayaDLX** [sboxgame/issues#2815]
### For?

Hammer

### What can't you do?

For now we can't send Hammer data from our session to another user quickly apart from sharing vmaps or vmdls.
Current Hammer has a TODO notice that has been there since Alyx and still exists in Dota 2 saying:
`(TODO: Hammer clipboard data on the system clipboard.)`

### How would you like it to work?

How'd that work? Basically you copy anything in Hammer, whether it's a group, a few meshes, a prefab, an entity etc to your system clipboard with CTRL+C and it'll copy a string of text referencing those and readable by another user's Hammer (just like modeldoc's node paste) and you'd be able to send it anywhere through a text message to someone on Discord/Slack or anywhere else and paste it in your Hammer. It'll allow easy cooperation for teams working on the same project, or helping each other on Discord etc.

This would also greatly help bug reproductions, you'd just send a string of text to a dev and they'll be able to paste in in their Hammer and try it right away than downloading a vmap file etc.

### What have you tried?

Apart from sending individual vmdls or vmaps for singular models or prefabs, there's no good way of just quick sending data from Hammer to another user. I know it'll be supported through asset.party but that's for stuff that should last longer, copy pasting straight from Hammer is far more useful in the context of team cooperation or help.

### Additional context

I saw this feature in Overwatch's game editor (TED) during a developer livestream, it's quickly explained how it works there at the 48th minutes timestamp https://youtu.be/KNBZrNmJD1k?t=2883

**Comment by aylaylay** [comment]
I'll get around to this but the paste is gonna be massive unless I shrink it down somehow, not ideal to be pasting into discord, which is probably why valve didn't bother

**Comment by aylaylay** [comment]
We probably wont end up doing this for native hammer, the pastes will just be too massive.

**Comment by LiminalCrab** [comment]
I was joking when I brought up paste.party but if it makes anything easier, might be cool to have a section on the site where we can just paste and copy these. Sort of like how Shadergraph works. I don't know how massive it is though. Quick way to share entity settings.

**Comment by LiminalCrab** [comment]
Actually, it looks like we can control + shift to select the properties and copy them. I'm fine with this
{
	cubemapfogheightstart = "2000.0"
	cubemapfogheightwidth = "0.0"
	cubemapfogfalloffexponent = "2.0"
	cubemapfogenddistance = "6000.0"
	cubemapfogstartdistance = "0.0"
	cubemapfogheightexponent = "2.0"
}
