### ISSUE TITLE
Add more languages in localization settings

### ISSUE THREAD

**Issue by KayaDLX** [sboxgame/issues#2816]
### For?

S&Box

### What can't you do?

Currently only English and "Pirate" is supported in s&box, the French & Russian being the two other biggest communities, I think it's worth adding those so gamemodes can already plan ahead localization for those languages.

I've already localized @bakscratch's Boomer gamemode in French a few months ago at his request, but it's currently impossible to use it in game.

### How would you like it to work?

Adding French and Russian options in s&box's language settings.

**Comment by Weldify** [comment]
When and if Russian gets added, I'd be happy to help translating the menu to Russian.

**Comment by KayaDLX** [comment]
We're currently implementing localization in TF:S2 and getting a lot of contributions for the community all around the world on https://github.com/AmperSoftware/TF-Source-2-Localization

It would be nice to be able to use them all 😊

**Comment by xezno** [comment]
Hey, I've added a selection of languages, mainly the ones Steam supports - we might not support these in our UIs yet but you can use them for localization in your games :+1:
