### ISSUE TITLE
func_brush doesn't set custom health on compile

### ISSUE THREAD

**Issue by KingOfTheFBI** [sboxgame/issues#2817]
### Describe the bug

Giving the func_brush health will not work on compile. The entity will not take damage when given a set health value. It does work when you change in in the entity viewer in the editor. Looks like hammer just isn't changing it.

### To Reproduce

1. Make a func_brush
2. Give it a custom health value
3. Compile

### Expected behavior

It breaks with breakpieces

**Comment by robotboy655** [comment]
Should be fixed when the game next updates. Map recompile is NOT needed.

**Comment by KingOfTheFBI** [comment]
I downloaded the latest update (after your post) and it still is broke for me.

**Comment by handsomematt** [comment]
Individual games will need to be reuploaded to propagate the base addon changes.

**Comment by KingOfTheFBI** [comment]
Ah ok, I tested on sandbox.

**Comment by KingOfTheFBI** [comment]
TTT updated and I confirmed it works now. Thanks guys, going to close this one out.
