### ISSUE TITLE
vrad3 doesn't take correct cooridnates for selfillum textures

### ISSUE THREAD

**Issue by Moofers** [sboxgame/issues#2819]
### Describe the bug

vrad3 doesn't seem to take correct coordinates for selfillum textures

### To Reproduce

1. Compile a map with self-illumination texture

### Expected behavior

Correctly colour and position of lighting from self-illum texture.

### Media/Files

[image](https://user-images.githubusercontent.com/41448134/214046071-7bc88f2f-c369-44c1-92c0-8ce8efbc6b65.png)

**Comment by ogniK5377** [comment]
What specifically is your albedo & mask? It seems to be fine here?
![image](https://user-images.githubusercontent.com/25727384/218651994-7b11547a-73bb-4607-8381-7a61f1d4aa8e.png)
![image](https://user-images.githubusercontent.com/25727384/218652111-7646fd8c-8d64-429f-9cac-686362a49611.png)

**Comment by ogniK5377** [comment]
I've also gone ahead and make the mask texture high resolution too, see if that fixes your problem 👍

**Comment by Moofers** [comment]
![image](https://user-images.githubusercontent.com/41448134/218662011-ef79aa70-810d-4171-be53-1f675eb7e750.png)
Yeh somethings not right.

**Comment by Moofers** [comment]
![image](https://user-images.githubusercontent.com/41448134/218665127-575a908c-b7f2-4495-91f2-e857839e1f9a.png)
Nope still not working.

**Comment by ogniK5377** [comment]
Can you provide me both textures please, thanks!

**Comment by Moofers** [comment]
![test_selfillum](https://user-images.githubusercontent.com/41448134/218665668-908e3c6e-4ce9-4256-b7db-9ac1fea21340.png)
![test_selfillum_color](https://user-images.githubusercontent.com/41448134/218665672-ce625522-0650-4f72-9a9f-837317aaa99b.png)

**Comment by ogniK5377** [comment]
Not entirely sure what you're doing here but it seems to be working fine? did you recompile the map after the change?
![image](https://user-images.githubusercontent.com/25727384/218673450-bff0c278-17c8-4b63-a6eb-9f6c6ca134a9.png)
![image](https://user-images.githubusercontent.com/25727384/218673094-d4d1ab56-ca6a-495c-8b36-9d843b2ec108.png)

**Comment by Moofers** [comment]
Issue was a outdate shader vmat =P
