### ISSUE TITLE
line-height css property

### ISSUE THREAD

**Issue by kodi022** [sboxgame/issues#2822]
### For?

S&Box

### What can't you do?

Currently the only way I know of to change line-height is every part where the string changes lines on the Label, cut it out and turn it into a new label and position it under. This is an example of the a unfortunate line-height gap with Poppins font, this is a single Label
![sbox-dev_Ul7FXCStBf](https://user-images.githubusercontent.com/29390269/214172429-8aa8ccab-de73-43ab-93aa-0c4b4cd38cbe.png)

### How would you like it to work?

Implement the line-height css property, where it takes a length like width or height does and separate lines by that much
https://developer.mozilla.org/en-US/docs/Web/CSS/line-height

### What have you tried?

margin, padding, font-size, gap

**Comment by DevulTj** [comment]
This was added at some point
