### ISSUE TITLE
Text does not scale with respect to WorldPanel bounds

### ISSUE THREAD

**Issue by Gmod4phun** [sboxgame/issues#2827]
### Describe the bug

Looks like text does not scale like everything else when having a panel with different bounds.

In the picture, I have 2 world panels drawing the same thing: one has bounds of 500x500, the other one has bounds of 2048x2048. You can see that the text in the red area is supposed to be scaled in relation to the panel, but it looks like the text's render size is the same for both of the panels. The text gets affected when setting the Size property on the Panel itself (however that does not change the rendered size of the panel, only the text changes).

I don't know if this works fine on normal panels, but on World Panels it seems to be broken. From what I checked this affects every text (text, textarea, label, etc.).

![image](https://user-images.githubusercontent.com/5991682/214969822-f73d2421-7a18-4d8e-a834-84fde817f900.png)

### To Reproduce

Make a worldpanel with some elements and some text, then make multiple instances of it with different bounds each time, and see the issue.

### Expected behavior

Text elements should scale properly depending on the panel bounds.

**Comment by anthonysharpy** [comment]
i know with 2D UIs the normal behaviour is that the text scales with the screen size (although, i've never understood why they made it that way), but maybe that's not the case with worldpanels. could it just be that you specified your panel sizes in terms of %, but not your text?

**Comment by Gmod4phun** [comment]
> 

Yea I was using % for everything, even the text. I tried other units for sanity checking, same issue with that.

**Comment by anthonysharpy** [comment]
it does seem like a bit of an oversight. 

i don't know if this works for worldpanels or if it will help at all but if you had a worldpanel class you could try overriding UpdateScale and set the scale to something like your_panel_bounds.x * some_const

protected override void UpdateScale( Rect screenSize )
{
    Scale = 1;
}

failing that your best bet might be to just set the font size to a fixed value and have a different entity for each differently-sized panel 😢

**Comment by Gmod4phun** [comment]
One 'workaround' I tried to use for this was to set the font-size to (fixed_value * scale_var), where scale_var was the percentage of the current panel height/width divided by the original height/width (at which the fixed_value was decided upon). This however uncovered another problem, which is text being way too pixelated on panels with small bounds, which I presume is because of how the fonts are rendered.
