### ISSUE TITLE
func_precipitation (rain) is unusable due to fps

### ISSUE THREAD

**Issue by sugmagaming** [sboxgame/issues#2828]
### Describe the bug

when using func_precipitation the fps goes straight to hell. I have to close the game. I've tried changing the density to 10 and its still unusable. pwease fix.

### To Reproduce

Step 1. Make a func_precipitation entity box and add the rain particles.
Step 2. Cry.

### Expected behavior

i can play da gaem with rain. makes me happy. instead garry decided to ruin my life.

**Comment by DrewBritt** [comment]
You are going to have to give more context (a reproduction project, system specs, a video, etc.).

On a map with just a 512x512x512 cube, a sky + light, a combined lightprobe volume, and a func_precipitation, I'm getting 280 FPS on a 3700x and 2070 Super with the rain_inner/rain_outer particles for the precipitation.

**Comment by sugmagaming** [comment]
My cube dimensions are 2240x14400x11172 and my specs are i7-12700KF and RTX 3080.

**Comment by sugmagaming** [comment]
It seems to be happening because of the water. I placed a func_precipitation cube above on my ship and it worked fine. but i delete the one on the ship and place it near the water and it gets 0fps and freezes again.
