### ISSUE TITLE
Make GPU low memory warnings toggleable

### ISSUE THREAD

**Issue by MrBrax** [sboxgame/issues#2829]
### For?

S&Box

### What can't you do?

When on a PC with low VRAM, doing practically anything will make the console unusable due to the massive amount of low VRAM spam (every tick).

I just want to be able to tinker with small code stuff, the graphics looking worse than N64 with 15 fps does not bother me.

![1674809831566](https://user-images.githubusercontent.com/1517911/215047252-a7339243-0cb9-4c4f-83de-da33261c6ae1.png)

### How would you like it to work?

Have the console clean on old video cards

### What have you tried?

Searching the console commands list to no avail, nothing seems to disable it.

**Comment by handsomematt** [comment]
They're not really warnings, it's telling you you've run out of vram and can't do anything - toggling this off would be bad.

We've resolved quite a few vram leaks since this issue.
