### ISSUE TITLE
Expose QGraphicsItem.prepareGeometryChange

### ISSUE THREAD

**Issue by lotuspar** [sboxgame/issues#2830]
### For?

S&Box

### What can't you do?

Can't use QGraphicsItem.prepareGeometryChange

This is important for resizing GraphicsItems etc

### How would you like it to work?

GraphicsItem.PrepareGeometryChange

### What have you tried?

```csharp
[DllImport( "QT5Widgets.dll", EntryPoint = "?prepareGeometryChange@QGraphicsItem@@IEAAXXZ" )]
private static extern void QGraphicsItem_prepareGeometryChange( nint ptr );

private static nint? GetItemSelfPtr( GraphicsItem target )
{
	// get the QGraphicsItem
	var obj = target.GetType().GetField( "_graphicsitem", BindingFlags.Instance | BindingFlags.NonPublic )
		?.GetValue( target );

	// get QGraphicsItem.self
	var self = obj?.GetType().GetField( "self", BindingFlags.Instance | BindingFlags.NonPublic )?.GetValue( obj );

	return (nint?)self;
}

public static void PrepareGeometryChange( this GraphicsItem item )
{
	var ptr = GetItemSelfPtr( item );
	ArgumentNullException.ThrowIfNull( ptr );
	QGraphicsItem_prepareGeometryChange( ptr.Value );
}
```

### Additional context

with prepareGeometryChange before resize:

https://user-images.githubusercontent.com/91263142/215184416-30c47a65-963b-4591-be6e-2538adc47027.mp4

without:

https://user-images.githubusercontent.com/91263142/215184519-fff5b1ba-6dcd-4339-9c12-b09b4f4bdadb.mp4

**Comment by aylaylay** [comment]
PrepareGeometryChange is now public
