### ISSUE TITLE
Tick() Is Called Before The Entity Becomes Predictable, IsAuthority Broken

### ISSUE THREAD

**Issue by anthonysharpy** [sboxgame/issues#2831]
### Describe the bug

Entities are predictable through the Predictable field which defaults to true.

If you have a Tick() function (e.g. on an NPC) that's designed to predict some stuff on the client, you'll get the following error, even though the entity should be predictable:

![image](https://user-images.githubusercontent.com/55365296/215270451-12e737a3-8a2d-4f80-99ad-76e1933d08af.png)

The offending line:

![image](https://user-images.githubusercontent.com/55365296/215270463-70b26832-96a6-4442-9a49-c155b74dc0d5.png)

This seems to only happen (I think) the first time Tick is called... it seems it's taking the server a while for it to tell the client that the entity can be predicted.

I used to be able to avoid this by returning on the client if IsAuthority was false, but the behaviour of this seems to have changed in a recent update, and now IsAuthority is always false on the client.

![image](https://user-images.githubusercontent.com/55365296/215270761-ed268706-54c3-4451-b9c8-bc15852090bf.png)

Checking Predictable doesn't help since it's always true.

### To Reproduce

![image](https://user-images.githubusercontent.com/55365296/215270656-c7bedfd0-5192-4438-aff8-9041ed16c063.png)

### Expected behavior

Tick() should be called after the entity becomes predictable and/or IsAuthority should work here.

**Comment by DoctorGurke** [comment]
Use a proper simulate context for prediction. The shared tick event is not the same as predicted simulate.

**Comment by anthonysharpy** [comment]
i don't think using the simulate context that comes from GameManager would work for this use case (NPCs) since on the server Simulate is called for every tick for every client; i just want it to be called every tick. i could have all my serverside code in a serverside Tick and all my client code in a clientside Simulate but then i'd have my code in two different places and that's a bit weird, and if they don't sync up right then it could maybe lead to prediction errors.

this was working for quite a while so i'd be surprised if they completely 100% didn't support predicting inside of Tick.

**Comment by DoctorGurke** [comment]
Prediction for npcs makes no sense, you predict things that depend on client input and immediate client feedback. Hence why simulate processes for every Client. Use server tick for npcs

**Comment by anthonysharpy** [comment]
whether predicting something "makes sense" depends on the context in which it is done, and this would include consideration of a number of factors such as typical player connection quality (_lots of overseas players?_), pace of gameplay (_racing games?_), server tick rate, rate at which the entity is networked (may not necessarily be the same as the tick rate), whether there is an expectancy of high server load, etc etc.

if what i suggested [here](https://github.com/sboxgame/issues/issues/2809) is ever implemented then this sort of pattern is required anyway.
