### ISSUE TITLE
Make PropertySheet.AddProperty public

### ISSUE THREAD

**Issue by lotuspar** [sboxgame/issues#2835]
### For?

S&Box

### What can't you do?

Use AddProperty() on a PropertySheet

Not too sure why this isn't a thing already

### How would you like it to work?

PropertySheet.AddProperty

### What have you tried?

```csharp
public static Widget AddProperty( this PropertySheet sheet, object target, string targetName )
{
	var method = sheet.GetType().GetMethod( "AddProperty", BindingFlags.Instance | BindingFlags.NonPublic, null,
		new[] { typeof(object), typeof(string) }, null );
	if ( method == null )
	{
		throw new Exception( "Couldn't get AddProperty!" );
	}

	return (Widget)method.Invoke( sheet, new[] { target, targetName } );
}
```

**Comment by DoctorGurke** [comment]
#2638 
this seems to be already done on garry's entity prefabs branch
![Discord_CmZgp18VnZ](https://user-images.githubusercontent.com/12602100/215364706-5637d021-a1c4-44ea-9e60-515db853d862.png)

**Comment by lotuspar** [comment]
oh wonderful thanks gurke
