### ISSUE TITLE
allow to have lists in hammer entities

### ISSUE THREAD

**Issue by TheBoxTrot** [sboxgame/issues#2836]
### For?

Hammer

### What can't you do?

have a way where we can expose lists to hammer for our entities such as having a list of materials so that you can keep adding materials in the hammer entity kinda like the taglist system but to be able to change the resourcetype for it to any asset

### How would you like it to work?

allow as to apply the [property] to a list<>

### What have you tried?

using taglists and having to write everything as strings. not ideal

**Comment by DoctorGurke** [comment]
Duplicate #2198
