### ISSUE TITLE
[Material Editor] Blendable texture crash with 4 layers

### ISSUE THREAD

**Issue by AfteraOfficiel** [sboxgame/issues#2837]
### Describe the bug

Since some days, blendable texture crash if we have 4 layers

But it work with 3 layers

### To Reproduce

New Blendable texture
check 4 Layers
--- > Crash

### Expected behavior

Not crash

### Media/Files

N/A

### Additional context

N/A

**Comment by ogniK5377** [comment]
Should be fixed next update

**Comment by AfteraOfficiel** [comment]
Fixed
