### ISSUE TITLE
Native version for ARM-based devices (Mac M1/M2)

### ISSUE THREAD

**Issue by pakkographic** [sboxgame/issues#2838]
As you can see in the title, I'd like to **feature request** a **native version for ARM-based devices including M1/M2 Macs**.

**Comment by Space-Clustercompany** [comment]
I would like to see that

**Comment by handsomematt** [comment]
Not gonna happen sorry

**Comment by pakkographic** [comment]
That's probably because Source 2 doesn't support Mac so the game can't the exported, right? If the development wasn't abandoned on Unreal Engine, a Mac version could be released.

**Comment by lotuspar** [comment]
source 2 supports mac fine it just doesn’t make sense for s&box to support it rn

**Comment by pakkographic** [comment]
Because of the current Mac marketshare which is around 2.4%? Not enough gamers on Mac? Doesn't make sense to maintain a game for a tiny community? Doesn't make sense is a vague to me, if you'd provide a specific reason, it'd be great.

**Comment by lotuspar** [comment]
you answered it yourself really - there just aren’t enough mac players rn to justify supporting it in dev preview

while i’d love mac support in the future (especially if s&box is trying to be a game engine) it doesn’t really make sense for support rn

**Comment by Nytrona** [comment]
What about [Windows on Arm](https://learn.microsoft.com/windows/arm/overview) hardware like Microsoft's ARM powered Surface devices?

**Comment by TehBrian** [comment]
> you answered it yourself really - there just aren’t enough mac players rn to justify supporting it in dev preview
> 
> while i’d love mac support in the future (especially if s&box is trying to be a game engine) it doesn’t really make sense for support rn

six months later, do you think there's a chance that, in the future, after the public release, mac might eventually gain support? (I'm really looking forward to s&box, but I don't have a Windows computer, so that sorta sucks.)

**Comment by PixelQubed** [comment]
> > you answered it yourself really - there just aren’t enough mac players rn to justify supporting it in dev preview
> > while i’d love mac support in the future (especially if s&box is trying to be a game engine) it doesn’t really make sense for support rn
> 
> six months later, do you think there's a chance that, after the public release, mac might eventually gain support? (I'm really looking forward to s&box, but I don't have a Windows computer, so that sorta sucks.)

Why would it happen? Macs are just not made for gaming. End of. Arm devices are just not powerful enough for main stream gaming yet. Not saying this will always be the case but it is currently.

**Comment by TrieBr** [comment]
> Why would it happen? Macs are just not made for gaming. End of. 

Unity, Godot and Unreal engine all work on Mac. So does Source Engine (Dota 2). There have also been several releases of AAA games on Mac (CyberPunk, Death Stranding). Diablo 4 also runs amazingly well under the game porting toolkit. I don't think the argument that Arm is not powerful enough still holds.

> Macs are just not made for gaming

Macs are made for productivity though. _Developing_ games is different from actually gaming.
