### ISSUE TITLE
Add the ability to set the playing time of a sound

### ISSUE THREAD

**Issue by ceitine** [sboxgame/issues#2840]
### For?

S&Box

### What can't you do?

I can't set a sound's current playing time without having to mess around with SoundStreams and sound samples.

### How would you like it to work?

I'd like to have some method or property to set a sound's current playing time.
Example:
```csharp
sound = Sound.FromEntity( "bla bla bla", this );

// Somewhere else...
sound.Seek( 10f ); // Sets the sound's playing time to 10 seconds.
```
Obviously it doesn't have to be a method called Seek but it's just for example.

### What have you tried?

I've tried using SoundStreams by getting samples with SoundFile.Load and playing the samples from a specific position but that's not a perfect solution either (see: https://github.com/sboxgame/issues/issues/2390).

**Comment by GAMEDEVTYCOONXD** [comment]
PLEASE FIX! I AGREE BIG PROBLEM!

**Comment by Weldify** [comment]
C# sound API is overall horrendous! Might as well upvote #2700 since it's closely related

**Comment by ceitine** [comment]
Layla's commit for the MusicPlayer class has this.
https://commits.facepunch.com/449684
