### ISSUE TITLE
"Games" tab empty. Cannot join servers.

### ISSUE THREAD

**Issue by colleen05** [sboxgame/issues#2843]
### Describe the bug

When opening the game, no games are listed. Clicking on the "Games" tab results in non-ending loading. Joining servers will bring me to the "Init" screen, and then boot me back to the menu because I don't have the associated map(?).

This has been going on for the past few updates.

### To Reproduce
1. Launch the game
2. Stare at a blank "Games" tab.
3. Fail to join a server.

### Expected behavior

I should be able to view the "Games" tab, and be able to join servers (and have it automatically download the required resources), but neither of those work.

### Media/Files

I don't have any media to show! s&box got removed from my account, and Steam says it was because the beta period closed. I believe this might be because of detected inactivity (even though I launch the game after every update, checking if this issue persists). This is only conjecture, though.

### Additional context

I am running s&box on Ubuntu 22.04 through Proton Experimental (I have tried 7.x), with an AMD GPU (this has caused issues in the past, but I highly doubt even the worst spaghetti code could result in this being the issue).

**Comment by handsomematt** [comment]
https://github.com/ValveSoftware/Proton/issues/4940 known here with a solution

**Comment by colleen05** [comment]
Alright, thanks! My bad for not looking into Proton compatibility issues.
