### ISSUE TITLE
Animated UI Textures (APNG, GIF, VMAT support)

### ISSUE THREAD

**Issue by timmybo5** [sboxgame/issues#2844]
### For?

S&Box, Material Editor

### What can't you do?

I am unable to use animated UI images, animations that are not possible/easy with css. GIF/APNG are the obvious formats here but vmat could be interesting too with the scrolling texture features or animated sequence. 

I have tried .vmat, .gif, and .mks formats on panels:
`myPanel.Add.Image("materials/hud/killstreaks/static.gif", "cuavStatic");`

**Comment by aylaylay** [comment]
You can now use gif and webp in UI
