### ISSUE TITLE
ent_path_platform causing significant FPS drop

### ISSUE THREAD

**Issue by sugmagaming** [sboxgame/issues#2845]
### Describe the bug

My moving boat ent_path_platform is causing massive FPS drop. I go from 105 FPS with it enabled to 160 FPS with it removed. Another user (Xenthio <3) reported going from around 20 FPS to 60. The model the ent_path_platform is tied to is 41,000 triangles if that helps.

### To Reproduce

1. Go on my map Roy the small ship.
2. Check FPS.
3. Type ent_remove smallboat in console
4. Check FPS

### Expected behavior

The ent_path_platform should not cause such massive drop in frames.

### Media/Files

![fpsbefore](https://user-images.githubusercontent.com/15720147/216022623-51c6ff22-c515-41ee-8f76-cc4ecd6dd5f4.png)
![fpsafter](https://user-images.githubusercontent.com/15720147/216022633-f7590eb0-da7d-47d0-9ae8-1367865ef9c0.png)

**Comment by robotboy655** [comment]
I did some tests, and I can confirm the issue happening, but from what I can tell it's not an issue with `ent_path_platform` itself, but with simply setting position and rotation on the entity every frame/tick.

If I had to guess - the problem is with the complex physics shape of the model used.

**Comment by sugmagaming** [comment]
If anyone else has this issue go to modeldoc and under the physics mesh file set the max vertices per mesh to as low as possible while still keeping the shape so it doesn't impact performance.
