### ISSUE TITLE
Text Inside a Label Creates a Duplicate Label

### ISSUE THREAD

**Issue by Geeknerd1337** [sboxgame/issues#2847]
### Describe the bug

Whenever I create a label using the `<label>` tag and put some placeholder text in it, it creates a label element in the inspector for the text as well.

### To Reproduce

1. Create a razor file with a single label, like so:
```html
<root>
	<div class="labelHolder" @ref="TestPanel">
		<label class="myLabel">Hello matt!</label>
	</div>
</root>
```
2. Launch the gamemode with the UI and open the UI inspector.
3. Observe that an additional label panel containing the text is nested within your label.
![image](https://user-images.githubusercontent.com/15205856/216159504-b0fa825b-aa99-4e54-8da4-534537823db6.png)

### Expected behavior

If text is nested directly inside a label, it shouldn't create a duplicate element around it, but set the parent label's text panel to use that text.

**Comment by Geeknerd1337** [comment]
A workaround for this for the time being is to set the text property on a label like so:
`<label text="Hello Matt!"></label>

**Comment by DevulTj** [comment]
I've changed some behavior here - let me know if that fixes things

**Comment by Geeknerd1337** [comment]
![image](https://user-images.githubusercontent.com/15205856/216164548-7eb1d0c5-9b3e-4604-a4f2-d762db9c307b.png)
Seems to be working as intended now, thank you!
