### ISSUE TITLE
Frequent crashes from Csg updates

### ISSUE THREAD

**Issue by trundlr** [sboxgame/issues#2854]
### Describe the bug

I have started using the Facepunch csg-demo for Grubs. While subtracting from the terrain, I keep crashing. I don't have any logs from the crash, but it is very easy to reproduce.

### To Reproduce

1. Clone Grubs and check out the rewrite branch: https://github.com/apetavern/sbox-grubs/tree/rewrite
2. Start up Grubs with the default option in launcher
3. Hold left click and walk around (W/S for aim, A/D for movement)
4. Let the crash happen!!

### Expected behavior

No crashy crashy

**Comment by PolSpock** [comment]
Maybe link to https://github.com/Facepunch/sbox-csg/issues/10  ?

**Comment by Metapyziks** [comment]
Closing this one as it's an issue with Facepunch/sbox-csg
