### ISSUE TITLE
Apply Morph on a SceneModel then Update() resulting a bugged model

### ISSUE THREAD

**Issue by PolSpock** [sboxgame/issues#2856]
### Describe the bug

Hello,

I'm trying to create Player Avatar with `TextureBuilder` and `Graphics.RenderToTexture`
So i'm using Scene API to achieve that : SceneWorld/SceneModel
Then i apply Update() to get over the T Pos.

That works well, but when i try to include Morphs on my SceneModel, the SceneObject.Update() method has a strong chance of totally breaking my SceneModel. See the pictures bellow.

### To Reproduce

Simplified Razor file :
```
<root>
	<scene @ref=WorldScene></scene>
</root>

@code {

	public ScenePanel WorldScene { get; set; }
	public SceneWorld MenuWorld { get; set; }

	private SceneModel AvatarModel;

	public override void OnHotloaded()
	{
		RefreshWorld();
	}

	protected override void OnAfterTreeRender(bool firstTime)
	{
		base.OnAfterTreeRender(firstTime);

		if (firstTime)
		{
			RefreshWorld();
		}
	}

	void RefreshWorld()
	{
		// Cleanup
		MenuWorld?.Delete();

		MenuWorld = new SceneWorld();

		AvatarModel = new SceneModel(MenuWorld, "models/citizen/citizen.vmdl", Transform.Zero);
		AvatarModel.Morphs.Set("LipSidewaysL", 1.0f);

		foreach (var sceneObject in SceneObjects)
		{
		        // BUGGED MORPHS
			(sceneObject as SceneModel).Update(1f);
		}

		Angles angles = new(15f, 157.5f, 0);
		Vector3 position = Vector3.Up * 45f + angles.Forward * -60f;

		WorldScene.World = MenuWorld;
		WorldScene.Camera.Position = position;
		WorldScene.Camera.Rotation = Rotation.From(angles);
		WorldScene.Camera.FieldOfView = 80;
		WorldScene.Camera.AmbientLightColor = Color.White;
		WorldScene.Camera.Name = "MenuWorld";
	}
}
```

### Expected behavior

My goal is not to apply each tick the Update() method, i just want to advance the animation without getting crazy morph

### Media/Files

Without Update() : no problem but no morph applied
![image](https://user-images.githubusercontent.com/5229571/216562969-2edbe659-a705-4a85-b6d2-320d7c0a5c24.png)

With the Update() call : getting crazy morph
![image](https://user-images.githubusercontent.com/5229571/216562998-e9911ba4-77fc-4112-8d1f-5ba7afeeb155.png)

**Comment by aylaylay** [comment]
I can't get this to happen

**Comment by PolSpock** [comment]
This a s&box project to reproduce the error : https://github.com/PolSpock/sbox-scenepanelmorphbug
![image](https://user-images.githubusercontent.com/5229571/218421843-4563fbbe-19ca-4c91-86b3-3c95625e8af1.png)

**Comment by aylaylay** [comment]
I tried the project and it works for me

**Comment by PolSpock** [comment]
> I tried the project and it works for me

Sometimes is working, sometimes not

This my way to get the bug :
1) I start s&box with editor mode
2) I start the project with the auto Generated project 
![image](https://user-images.githubusercontent.com/5229571/218984139-8bd5acc4-282f-4ccc-a9f2-06a2b79ea235.png)
3) tadam : ![image](https://user-images.githubusercontent.com/5229571/218984280-92e3ae30-4af2-4965-b897-31ccbb45dfbe.png)

**Comment by aylaylay** [comment]
Thanks, I'll try them steps

**Comment by aylaylay** [comment]
I have pushed a potential fix, let me know if it fixes it for you when it hits steam

**Comment by PolSpock** [comment]
Seems to be fixed !
I try and retry by restarting/hotreloading my game and my Terry still looking good : 
![image](https://user-images.githubusercontent.com/5229571/219308124-c120893b-a28c-455f-954d-1bddb4f8a917.png)

Thx Laylad, i'm closing the issue
