### ISSUE TITLE
EntityComponent<T> should be : IEntity instead of : Entity

### ISSUE THREAD

**Issue by Weldify** [sboxgame/issues#2858]
### What it is?

Since Client became IClient it's now impossible to create client EntityComponents

### What should it be?

Honestly, no idea. I don't know why Client was replaced by IClient in the first place.

**Comment by garrynewman** [comment]
IClient derives from IEntity, which has a Components property

**Comment by Weldify** [comment]
That's not the problem. The problem is that you can't create a generic EntityComponent for clients. Sprry if the initial explanation was off

**Comment by garrynewman** [comment]
Here you go

```
	public class ClientComponent : EntityComponent
	{
		public IClient Client => Entity as IClient;
	}
```

**Comment by Weldify** [comment]
Guess that works! Although it isn't really intuitive. You said that IClient is also IEntity, would it be possible to replace the generic with IEntity instead of Entity in that case?

**Comment by garrynewman** [comment]
Yeah but not until pain day
