### ISSUE TITLE
Use SRGB color space in `background-image-tint` for consistency with other color properties

### ISSUE THREAD

**Issue by Gmod4phun** [sboxgame/issues#2859]
### What it is?

The CSS property `background-image-tint` does not seem to use SRGB color space, whereas other properties like `background-color`, `border-color` etc do. This results in different colors unless converting the color to 32bit with SRGB, which can be done for custom Colors but (afaik) not the CSS defined colors.

This is how the elements look with both of their CSS color properties set to `MyCustomColor.Rgb`

![image](https://user-images.githubusercontent.com/5991682/216712666-f9301a7f-8d6f-47d2-a2fa-96c61cdf4055.png)

And this is how it looks with the image tint converted to 32bit SRGB using `MyCustomColor.ToColor32(true).Rgb`
![image](https://user-images.githubusercontent.com/5991682/216712711-005aa016-ca17-4e54-af33-0236cfb08d20.png)

### What should it be?

The `background-image-tint` property should use the same color space as the other properties for the purpose of consistency

**Comment by xezno** [comment]
Should be fixed on next update, let me know if not

**Comment by Gmod4phun** [comment]
Yep, seems to be good now. Thank you :)
