### ISSUE TITLE
make default code for gamemode project also include deletion of entities after a few seconds

### ISSUE THREAD

**Issue by DingusPingus** [sboxgame/issues#2860]
### For?

S&Box

### What can't you do?

Currently the default code causes you to spawn ragdolls when you use your `PrimaryAttack`  This serves as an introduction to basic spawning of entities however these entities are permanent and no method at the start is implemented to delete them.

### How would you like it to work?

I would suggest implementing some more default code to automatically delete the entities after a few seconds, it would also be a great example of a proper method of deleting entities to someone who is creating a game mode for their first time (such as me!).

### What have you tried?

Currently the workaround was for me to browse through the methods attached to the ragdoll entity in the default code and to call `DeleteAsync`.

### Additional context

some sample usage of `Log.Info` might also be helpful such as saying things like "Entitiy has Spawned" or "Entity has Despawned!"

**Comment by ThePawlow** [comment]
Bump - Prevention of people who crash their Editor with spamming Ragdolls, but blame it on S&box 😐

**Comment by MuffinTastic** [comment]
Well, short of crossing some fixed threshold like the 16k entity limit it really shouldn't crash, should it...? That's worthy of a (separate) issue IMO. It should ideally just lag to high hell
