### ISSUE TITLE
Entity Prefab properties break when a [Net]worked property precedes the [Prefab]s in the file

### ISSUE THREAD

**Issue by trundler-dev** [sboxgame/issues#2862]
### Describe the bug

When a property marked with [Net] is placed above properties marked with [Prefab], the Prefab properties do not properly populate the Prefab editor.

### To Reproduce

1. Create a custom entity prefab type
2. Add [Prefab] marked properties
3. Add a [Net] marked property above the Prefab marked properties
4. Open an asset of that type, and notice the properties not populating in the editor as expected.

### Expected behavior

The properties should populate in the editor no matter where they are placed in relation to Networked properties.

### Media/Files

https://user-images.githubusercontent.com/57276947/216772864-077794b7-fe04-46ae-bfa6-a39b6b143a8f.mp4

### Additional context

If you can't seem to reproduce, here is the code and branch I am working on: https://github.com/apetavern/sbox-grubs/tree/rewrite

**Comment by garrynewman** [comment]
wtfwtfwtfwtfwtf

**Comment by garrynewman** [comment]
Do you know whether this still happens if you're not defining the default value?

**Comment by trundler-dev** [comment]
> Do you know whether this still happens if you're not defining the default value?

It seems to work fine if I remove all of the default values. Having just one will break it!

**Comment by garrynewman** [comment]
I pushed something that may help this. I think codegen was adding a `#line` between the attributes which may have caused some confusion

**Comment by trundler-dev** [comment]
Yep, that worked. Thanks garry!
