### ISSUE TITLE
`Game.Server.MaxPlayers` is always 0

### ISSUE THREAD

**Issue by timmybo5** [sboxgame/issues#2864]
### Describe the bug

For this issue (https://github.com/sboxgame/issues/issues/2705) `Game.Server.MaxPlayers` was added but it doesn't seem to work.
Even though `maxplayers` = 10, `Game.Server.MaxPlayers` = 0.

**Comment by DevulTj** [comment]
I haven't been able to reproduce this locally

**Comment by timmybo5** [comment]
I can confirm it still doesn't work, the following code prints 0 for me.

```csharp
[ConCmd.Server("maxplayers_print")]
public static void MaxPlayersPrint()
{
    Log.Info(Game.Server.MaxPlayers);
}
```

**Comment by DevulTj** [comment]
Thanks, that's what I was missing. Will push a fix for this now.
