### ISSUE TITLE
<List>s don't work properly with [Prefab]s

### ISSUE THREAD

**Issue by trende2001** [sboxgame/issues#2865]
### Describe the bug

Whenever I try to use <List> with the [Prefab] tag (usually has multiple values), it just leaves a blank space in the Entity Prefab editor. Trying to make an upgrade system and fit all of the values in 1 row.

### To Reproduce

1. Create a custom entity prefab type
2. Add [Prefab] marked properties to a <List> with multiple values
3. Save it
4. Open the prefab itself, and press the plus button, it will just create a blank row

### Expected behavior

It should show multiple values in one row.

### Media/Files

![Screenshot 2023-02-04 203709](https://user-images.githubusercontent.com/68961063/216786491-7c612be7-d413-44dc-bc07-4d7e637e68a9.png)
![Screenshot 2023-02-04 202818](https://user-images.githubusercontent.com/68961063/216786489-06d801df-1a72-4c86-bf4c-b4ddd7f53252.png)

(my tower has multiple upgrades, so there's multiple blank rows)

**Comment by NotGaylien** [comment]
thank you for your hard work trende!

**Comment by trende2001** [comment]
lol no problem, if i find an issue with my updated upgrade system i'll reopen it
