### ISSUE TITLE
Dedicated Server Instantly Crashes With Segfault

### ISSUE THREAD

**Issue by anthonysharpy** [sboxgame/issues#2867]
### Describe the bug

With facepunch.construct:

![image](https://user-images.githubusercontent.com/55365296/216790987-3b1eb260-086f-4065-8105-1fbb1951b39e.png)

With my own map:

![image](https://user-images.githubusercontent.com/55365296/216791157-02fe400c-6f14-49bb-a4e9-2e02af9ca0bf.png)

It seems to crash no matter what map I use. Other gamemodes work fine.

Technically the gamemode is not public... but in my defence I made it public and it still didn't work, so I put it back to private for now.

My gamemode is designed to only run on a single dedicated server so this sort of stops me dead in my tracks... been working on this for the past four months or so so would really appreciate if it would be possible to look into a fix 😊😊😊😊😊😊😊

### To Reproduce

Launch a dedicated server with the commands from the screenshot, it will crash.

### Expected behavior

Doesn't crash.

### Additional context

The game works in the editor and in the actual s&box game (over LAN).

I tried deleting the whole dedicated server and re-downloading it. Didn't help...

**Comment by collinoc** [comment]
Possibly unrelated but does `[Official] LameRP` need quotes around it?

**Comment by anthonysharpy** [comment]
@collinoc it's a good idea but it's the same result even with LameRP, "[Official] LameRP" or "LameRP" sadly 😢

**Comment by garrynewman** [comment]
Looks like it's crashing when the server closes? Are you meaning to close the server?

**Comment by anthonysharpy** [comment]
@garrynewman i think it's closing itself... i do have a thing that can automatically kick players... i've just commented it out and force-redownloaded the gamemode on the dedicated server but it's still giving me the same crash

it might just be disconnecting because of this? not sure what it's trying to tell me though

![image](https://user-images.githubusercontent.com/55365296/216813240-dc0a535d-f8e3-4701-819d-f48890e23034.png)

**Comment by garrynewman** [comment]
it'd be more useful to post the log file (in the logs folder)

**Comment by anthonysharpy** [comment]
@garrynewman these are the interesting looking ones

[Log.log](https://github.com/sboxgame/issues/files/10610695/Log.log)
[connection_log_27015.txt](https://github.com/sboxgame/issues/files/10610698/connection_log_27015.txt)
[configstore_log.txt](https://github.com/sboxgame/issues/files/10610699/configstore_log.txt)

**Comment by garrynewman** [comment]
That's a weird one, I've committed something that might help

**Comment by anthonysharpy** [comment]
@garrynewman thanks a bunch, this is working for me now 😄 

have a nice weekend
