### ISSUE TITLE
"fps_max" causes issues when set to lower values

### ISSUE THREAD

**Issue by PixelQubed** [sboxgame/issues#2868]
### Describe the bug

When you try to limit your fps to something like 90 with the fps_max ConVar, it tends to have issues in the editor. The editor windows, such as hammer and model doc, tend to fight each other for that fps cap. What I mean by this is the game will go to something like 30fps, and then you can only use 60fps in the active editor window. Then if you open something like modeldoc alongside that, it further reduces the fps as the game tries to balance between the windows under the mentioned cap.

### To Reproduce

1. Open the console.
2. Type fps_max 60.
3. Open an editor such as Hammer and load a map.
4. Watch as both the game and the editor fight to stay under this fps cap causing lag in either of them.

### Expected behavior

The fps should use the limit for each independent window instead of fighting globally to stay under this limit.

**Comment by DevulTj** [comment]
Yes. This has since been resolved.

**Comment by PixelQubed** [comment]
> Yes. This has since been resolved.

Thanks for resolving this.
