### ISSUE TITLE
Project Creator: Add a IgnoreFolders/IgnorePath metadata section.

### ISSUE THREAD

**Issue by Adesii** [sboxgame/issues#2871]
### For?

S&Box

### What can't you do?

Currently when cloning a Template repository like the FPS template: https://github.com/DevulTj/sbox-template.fps
It creates a .git folder which also gets copied over when creating a new project from it.

with a "IgnoreFolders" section in the .addon file we could make it ignore that path and easier keep our templates up to date.
i would assume that this also would be useful for other folders like a .vscode or similar workspace settings files that you don't want to copy over into every project.

### How would you like it to work?

a simple IgnoreFolders or IgnorePath section in the .addon file that ignores a folder path or even files when creating a new project.

### What have you tried?

The only way to not create a .git folder is by downloading a Zip of the repository which makes it a bit harder to know if its up to date.
With a clone its as simple as fetching the new changes

**Comment by DevulTj** [comment]
I'd prefer we handle this ourselves on all projects, instead of including manually

**Comment by DevulTj** [comment]
See how that works out for you - directories that start with a "." will be excluded (while making sure we include .localization)

**Comment by Adesii** [comment]
seems to work. 👍
