### ISSUE TITLE
Adding gamemode entities from asset party in hammer does not work

### ISSUE THREAD

**Issue by KingOfTheFBI** [sboxgame/issues#2873]
### Describe the bug

Adding game entities from the hammer ent page does not work. It will say it's downloading and then nothing happens when completed.

### To Reproduce

Open Hammer
Entity tool
Click "Add Game"
Add whatever game

### Expected behavior

The game entities are added

### Additional context

Made a new one because github would not let me reopen the old issue

**Comment by sugmagaming** [comment]
can confirm im having the same issue

**Comment by trende2001** [comment]
same here

**Comment by trende2001** [comment]
it seems to be working?

**Comment by matekdev** [comment]
Hey, it seems like this issue only happens with Murder & TTT. I've double checked the attributes and everything seems in line. I've even copied and pasted the attributes from other gamemodes as well, no luck. 

These gamemodes were working before and no longer do, so my best guess is that it isn't on my end.
https://github.com/CigarLounge/sbox-TTT/blob/main/code/Items/Weapons/M4.cs#L5-L10

Could I get someone to look into why they are failing to pull? There isn't any error message unfortunately. Thank you!

**Comment by matekdev** [comment]
It was related to a bad asset, the gamemode would still function correctly, however pulling assets didn't.
![image](https://user-images.githubusercontent.com/32153021/219254023-9e266228-66b0-495a-b57d-a12759ef3070.png)

**Comment by KingOfTheFBI** [comment]
Remeko fixed the issue for TTT, closing this issue now since it was a TTT issue not FP.
