### ISSUE TITLE
Request to add a new event for the Client-Side something like a "OnClientSpawn"

### ISSUE THREAD

**Issue by SuperCoolNinja** [sboxgame/issues#2874]
### For?

S&Box

### What can't you do?

I can't delete the previous RootPanel created using Addon with my Static Class.

### How would you like it to work?

So the way i'm working with addon it's that, i do have a static class which get call automaticaly from the engine
when the addon is loaded, but then since the addon is getting destroy after each save to be re created 

i don't have the time to destroy the previous RootPanel to avoid having duplicated RootPanel.
so to do that, i need an event which is called Once the player spawn to create the RootPanel and then using HotLoading i can make a way to destroy it after each change to avoid spamming new RootPanel.

I hope to be clear on my explanation.

### What have you tried?

I do have try the event [Event.Entity.PostSpawn] which get called after the map has been loaded
but since this is call only server-side i can't create the RootPanel from it.

so this is why i'm asking a another version of it but for client-side verry usefull for Addon.

**Comment by timmybo5** [comment]
Since you are making an addon isn't a rootpanel supposed to be created by the gamemode already? It's very easy to attach panels to an existing root panel if that's the case.

**Comment by SuperCoolNinja** [comment]
no. it would be the same at the end, you will not be faced to have multiple RootPanel but instead Multiple Panels inside your RootPanel.
