### ISSUE TITLE
Level Streaming Compiled Maps

### ISSUE THREAD

**Issue by GunnarKafel** [sboxgame/issues#2878]
### For?

S&Box

### What can't you do?

I can't load a compiled level into a running game. 

### How would you like it to work?

I want to be able to load a level through game code. Ideally, I would input the map's name and optionally offset it with a transform. The load function would return a class that lets me access its spawned entities and unload it if I need to. A benefit of this is preserving baked lighting, instead of relying entirely on dynamic lights. I'm assuming vis and nav would be an issue, since they'd need to be combined with the main map. But I'd be okay with just spawning the static geometry, entities, and lighting. 

### What have you tried?

I've used Hammer prefabs that load at runtime, but it's pretty useless for procedural games since they'll always be at the same location. I tried using models as well, but the workflow was less than ideal and looked terrible with dynamic lighting. I could bake lighting into the model itself, but dynamic objects won't be up to par since they need cubemaps and light probes to match the environment.

### Additional context

Combined with #2156, high quality procedural games would be a lot more accessible in s&box.

**Comment by geferon** [comment]
Why has this been closed?
Has this been added and/or decided against?
@handsomematt 
If it has been decided against or isn't going to be worked on then that's fine, I would just want to know rather than having the issue closed without any sort of comment about it.

**Comment by handsomematt** [comment]
You can do it in the new scene workflow. It's not quite to the point where you can reposition the maps yet but it'll get there.
