### ISSUE TITLE
Give the Full Path after taking a video/recording

### ISSUE THREAD

**Issue by craighulme** [sboxgame/issues#2882]
### For?

S&Box

### What can't you do?

I was unable to find the video that was saved. Because of how ambiguous the save path was.

### How would you like it to work?

Save locally to my Videos/Pictures folder. OR Just give us the full path instead of a short localised path.
someone also recommened allowing us to click the console log of the path to open the folder (Utility.OpenFolder)

### What have you tried?

boogers

**Comment by aylaylay** [comment]
It now logs full path
