### ISSUE TITLE
`Entity.FindInSphere` Does not work clientside

### ISSUE THREAD

**Issue by timmybo5** [sboxgame/issues#2884]
### Describe the bug

Using `Entity.FindInSphere` does not give the same results clientside as serverside, I am unable to find any Players when using the function on client.

I added some demo code below, `Found a player!` will never print on client. 

```csharp
[Event.Tick]
public void FindInSphereTest()
{
    var foundEnts = Entity.FindInSphere(Vector3.Zero, 999999);

    foreach (var ent in foundEnts)
    {
        // Log.Info(ent.GetType());
        if (ent is Player)
        {
            Log.Info("Found a player!");
        }
    }
}
```

**Comment by Gmod4phun** [comment]
AFAIK All of the FindIn* methods rely on the physics instead of the entity's origin, so unless every other client has the physics object of the players networked to them, they don't know about it
