### ISSUE TITLE
Sudden 50% performance drop since last night

### ISSUE THREAD

**Issue by Gmod4phun** [sboxgame/issues#2888]
### Describe the bug

After booting up S&box this morning I noticed that the framerate in the main menu itself was really low. After loading up a game of Sandbox on Flatgrass, where I used to have around 170 FPS, I was pretty shocked. The game now runs at about 90. Same goes for other maps such as Construct, where the drop is more impactful, going from 60-70ish FPS to 30-40. 

I don't believe something magically went wrong with my system overnight because other games seem to be having the same performance as they did before yesterday, however if this turns out to be bogus, sorry in advance.

I am wondering if it was one of these commits which accidentally caused the performance drop, as they were the only commits to the master branch overnight @garrynewman :
![image](https://user-images.githubusercontent.com/5991682/217596509-52663f1a-e562-4fe5-8154-693ca39e158e.png)

### To Reproduce

Play game, try and remember if you see a difference I guess :P

### Expected behavior

More performance, like before.

### Additional context

Specs: Windows 10, RTX 3060 Ti, Ryzen 5700X, 32GB RAM

**Comment by Ephememory** [comment]
What is your fps_max set to? I noticed this as well I think and moved my fps_max from 60 to 100 and now I'm getting around 60-70fps.

**Comment by DrewBritt** [comment]
Noticing the same performance regression. Setting my fps_max to 0 (defaults to 300 every time I boot the game) increases performance from ~100 FPS on main menu to 900+ and increases performance on Sandbox - Flatgrass from ~90-110 FPS to ~200-250 FPS (RTX 2070 Super, 3700x, 2x16 DDR4 3200 MHz).

**Comment by Gmod4phun** [comment]
My fps_max was set to 190, I still only achieved about 90 FPS. Setting it to 0 does indeed boost performance and I can get over 300 FPS on flatgrass, so I guess that helps. However I haven't touched my fps_max prior to this, and the performance drop had to be caused by something. As DrewBritt mentioned, the reported frametime also seems to be awfully high.

**Comment by NotGaylien** [comment]
its strange i had no max fps before and was getting just under 700fps in a game im helping on thats super simple.
set fps_max to 60 and its only 45-50fps max, so something is going on there

**Comment by Fortune117** [comment]
Just tried this as well - jumped from 120fps on flatgrass to 270 when I set fps_max to 0

**Comment by garrynewman** [comment]
Thanks for the research - should be fixed next build

**Comment by Gmod4phun** [comment]
Looks like its fixed. Thank you 👍
