### ISSUE TITLE
Modeldoc create animgraphs in wrong folder with the create button

### ISSUE THREAD

**Issue by TheBoxTrot** [sboxgame/issues#2892]
### Describe the bug

when you click create animgraph in modeldoc it will by default save it to Addonname/addonname/animgraphs
it will do the root folder twice

### To Reproduce

go to modeldoc
click the create button for animgraph
save animgraph
check folder

### Expected behavior

should save it like addonname/animgraph

**Comment by aylaylay** [comment]
Should be fixed now

**Comment by TheBoxTrot** [comment]
seems sorta fixed. on projects that were affected it still seems to default to Addonname/addonname/animgraphs but I think that may just be a thing with the windows file browser?. but I tried on a new project and it defaulted to addonname/animgraphs
