### ISSUE TITLE
`Screen.GetOrthoRay` returns a ray from the middle of the screen even though the camera is orthographic

### ISSUE THREAD

**Issue by xezno** [sboxgame/issues#2897]
### Describe the bug

`Screen.GetOrthoRay` has the following summary:

```
If current view is orthographic returns a world space ray from the cameras' position in cameras' direction.
If current view is NOT orthographic, returns a ray from the middle of the screen, so the position param is effectively ignored.
```

However, it currently returns a ray from the middle of the screen even though the camera is orthographic. Looking at the disassembly, it doesn't even seem to take any of the ortho properties into account.

### To Reproduce

Either use this repro: [ortho_repro.zip](https://github.com/sboxgame/issues/files/10711561/ortho_repro.zip)

Or stick this in FrameSimulate, make sure you've got an ortho camera set up:

```cs
var direction = Screen.GetOrthoRay( Mouse.Position ).Forward;

var tr = Trace.Ray( Camera.Position, Camera.Position + direction * 8192 ).Run();
DebugOverlay.Sphere( tr.EndPosition, 32.0f, Color.Red, 1f, false );

if ( Input.Pressed( InputButton.PrimaryAttack ) )
{
    TargetLocation = tr.EndPosition;
}
```

### Expected behavior

It should return a world space ray from the cameras' position in cameras' direction. See the video below for more info

### Media/Files

What it does
https://user-images.githubusercontent.com/12881812/218218250-37857518-36e5-4871-abdb-4051a6c03b8c.mp4

What it should do
https://user-images.githubusercontent.com/12881812/218218255-8a913853-e22c-4d7b-b755-c1a325e94825.mp4

### Additional context

I wrote my own `GetOrthoRay` to get around this, it's probably not correct but it works in my use case:
```cs
public static Ray GetOrthoRay( Vector2 screenPosition )
{
	var screenSize = Screen.Size;

	float screenX = screenPosition.x;
	float screenY = screenPosition.y;

	float halfScreenHeight = Camera.Main.OrthoHeight / 2f;
	float halfScreenWidth = halfScreenHeight * screenSize.x / screenSize.y;

	float orthoX = (2f * screenX / screenSize.x - 1f) * halfScreenWidth;
	float orthoY = (1f - 2f * screenY / screenSize.y) * halfScreenHeight;

	var forward = Camera.Rotation.Forward;
	var pos = Camera.Position;
	var right = Camera.Rotation.Right;
	var up = Camera.Rotation.Up;

	Ray result = new()
	{
		Position = pos + right * orthoX + up * orthoY,
		Forward = forward
	};

	return result;
}
```

**Comment by aled93** [comment]
Not a bug, don't ignore `Position` field of ray returned by `Screen.GetOrthoRay`, ortho cameras ray origin isn't same as camera position

**Comment by kurozael** [comment]
While you probably should be using `Position` from the `Ray` as @aled93 said, nice find, because regardless it would be from the center of the screen. The code determining this was commented out because we removed and then re-added ortho some time ago. I'll fix this.

**Comment by aled93** [comment]
As workaround you can use perspective camera with very small fov and far away from camera target, don't forget to adjust `ZNear` and `ZFar`

**Comment by kurozael** [comment]
Should be all good now @xezno I also made `SceneCamera.GetRay` return the correct result if the `SceneCamera` is orthographic.

**Comment by xezno** [comment]
Awesome, thank you!
