### ISSUE TITLE
Stuttering when creating a large `WebPanel` `WorldPanel`

### ISSUE THREAD

**Issue by matekdev** [sboxgame/issues#2899]
### Describe the bug

Creating a large `WebPanel` `WorldPanel` will leave your game is a stuttery mess. If there is no intention to improve it for this use case, feel free to close this issue.

### To Reproduce

1. Download the map and gamemode I provided
2. Change the `PanelBounds` inside `WebScreen` to be larger to exacerbate the issue i.e `PanelBounds = new Rect( 0, 0, screen.Model.Bounds.Maxs.y * 40, screen.Model.Bounds.Maxs.z * 40 );`
3. Set a video using `theatre_video <yt_id>` i.e `theatre_video ijju9rbeN1A` console command
4. Walk around and notice your console gets spammed with `CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event`

### Expected behavior

The game should run without suttering

### Media/Files

https://streamable.com/93pji3

[drive.google.com/file/d/1wJrLrsRsuFLst2Q8PIu0-ZF1StFQLkSz/view](https://drive.google.com/file/d/1wJrLrsRsuFLst2Q8PIu0-ZF1StFQLkSz/view)

**Comment by handsomematt** [comment]
I don't really see any way we can improve rendering a 40000 x 40000 resolution web panel, other than not letting you make them that big.
