### ISSUE TITLE
Change Sound IsFinished to IsPlaying

### ISSUE THREAD

**Issue by TheBoxTrot** [sboxgame/issues#2901]
### What it is?

the property for sound IsFinished returns true if the sound isn't playing and returns false if it is playing

### What should it be?

the property for sound IsFinished should be renamed to IsPlaying as it makes a bit more sense since IsFinished returns true even if the sound was never played to begin with so having it named isPlaying just kinda makes more sense 
returns true if the sound is currently being played. returns false if it is not playing

**Comment by anthonysharpy** [comment]
100% agree

also, i noticed that IsFinished is always true on a dedicated server. maybe this was intended... but if so, could a comment be added to it that mentions this? it sort of catches you out currently, especially since it works when running a server via the editor.

**Comment by garrynewman** [comment]
I agree

**Comment by DevulTj** [comment]
Added `Sound.IsPlaying`, and made `Sound.Finished` obsolete.
