### ISSUE TITLE
Entity Inspector display (Tostring) . 

### ISSUE THREAD

**Issue by FoxTTT** [sboxgame/issues#2907]
### For?

S&Box

### What can't you do?

When I override ToString in an entity component it doesn't display it's new name in the entity inspector.

### How would you like it to work?

I would like this feature if possible.

### What have you tried?

I have tried overriding ToString.

**Comment by DevulTj** [comment]
The Entity List will now show the component's name via ToString - if you haven't set it, it'll be set in this order:

If IComponent.Name is set, it'll choose that. This is set (currently) for prefabs.
If it isn't set, it'll fall back to its DisplayInfo (with Component Id).
