### ISSUE TITLE
[Hammer] Valve Shading Model not affected by Baked Lighting Complexity visualization

### ISSUE THREAD

**Issue by DeltaDesigns** [sboxgame/issues#2910]
### Describe the bug

Materials using ShadingModelValveStandard are not affected by the Baked Lighting Complexity visualization in Hammer. Regardless of Baked Light Indexing being checked on or off, any light will be treated as if Baked Light Indexing is turned on.

https://user-images.githubusercontent.com/50308149/218887196-53e1b483-270c-4116-891a-75ed6affb97a.mp4

*Notice the player spawn entity and cubemap being affected

### To Reproduce

-Place a block or something using the Blendable shader
-Place many lights with Baked Light Indexing off
-View Baked Lighting Complexity visualization
-Profit

### Expected behavior

Baked Light Indexing should affect Baked Lighting Complexity visualization on ShadingModelValveStandard

**Comment by bakscratch** [comment]
If I remember correctly its non-core (custom) shaders not calculating baked lighting complexity correctly

**Comment by KayaDLX** [comment]
Noticed that on the newest blend shader indeed, makes it quite difficult to deal with when your map is 90% blend shaders like Viaduct.

**Comment by samzanemesis** [comment]
Should be fixed with the new shadingmodel rework
