### ISSUE TITLE
Add Tags Generator to the Inspector

### ISSUE THREAD

**Issue by Fortune117** [sboxgame/issues#2921]
### For?

S&Box

### What can't you do?

It'd be super convenient to be able to specify strings in custom resources and prefabs the same way it is done in the asset upload wizard:
![image](https://user-images.githubusercontent.com/7847372/219353707-fe5629db-ea4d-4cc0-b061-0e5db52a6b8c.png)

### How would you like it to work?

Same way it does in the upload wizard.

### What have you tried?

You can use a list of tags but it's much less clean and more tedious to modify.

**Comment by DevulTj** [comment]
![image](https://user-images.githubusercontent.com/22372616/219544437-29a9ecb9-d9d8-4d02-ba50-f0224bc8c01c.png)

Let me know if this works as intended for you 👍🏻

**Comment by Fortune117** [comment]
works great ❤️
