### ISSUE TITLE
Prop Despawning

### ISSUE THREAD

**Issue by Mike466-0** [sboxgame/issues#2924]
### Describe the bug

When I try to add a circulating prop aroudn the map (car) on a platform it will go invisible randomly.

### To Reproduce

1. have a prop tied to a path platform,.
2. Have the prop go out of the map while going on its loop
3. it will then despawn at somepoint

### Expected behavior

Shouldnt despawn

**Comment by DoctorGurke** [comment]
Sounds vis related, that'd be a map issue

**Comment by MikeShaughnessy** [comment]
> Sounds vis related, that'd be a map issue

Either way its still a bug, theres no way to have it go out and job disappear, and theres no param for it to never disappear ,

**Comment by aylaylay** [comment]
What map does this happen on?
