### ISSUE TITLE
Clicking usernames in chat lobby forces you to restart S&box

### ISSUE THREAD

**Issue by codecakegit** [sboxgame/issues#2927]
**Description**
When you're in the main s&box lobby ( In Editor mode ) and use the lobby chat, clicking on someone's username will open their steam page within s&box. This steam page window cannot be closed and you are forced to restart s&box to get rid of the window. This is a Low Priority issue.

**To Reproduce**
- Open s&box In Editor Mode
- view chat lobby
- Click on a users name
- Bug begins here. Un-closable steam profile window.

**Expected Behavior** 
I should be able to close the steam profile window and continue using s&box.

**Comment by DevulTj** [comment]
This is a problem only when you're in editor mode, as we can't disable steam overlay ourselves with the current Steam API.

**Comment by codecakegit** [comment]
Correct, This only happens in S&box Editor mode.

**Comment by SharpMars** [comment]
Had it happen to me too, but its possible to close it. Just need to focus on editor window and use the steam overlay shortcut.
