### ISSUE TITLE
Lag Compensation is almost always off by one tick

### ISSUE THREAD

**Issue by the-remeko** [sboxgame/issues#2931]
### Describe the bug

The server almost always rewinds entities to where they were on the tick after the client's tick. When it's not off by one tick, it's off by two or more.

### To Reproduce

I have attached a minimal project that lets you shoot rays at a citizen moving side to side with your primary attack button. If the citizen is hit on the client, it will immediately draw a box at the citizen's position (not the hit position). If the citizen is hit on the server, the server will send an RPC to the client with the entity's rewound server position, which the client will then use to draw another box. The server box's position is almost always one tick ahead of the client box. It is possible to hit the citizen on the client and not the server, and vice versa. Speeding the citizen up makes this even easier to accomplish.

[LagCompTest.zip](https://github.com/sboxgame/issues/files/10774878/LagCompTest.zip)

### Expected behavior

Lag compensation should almost always rewind entities to the proper tick.

### Media/Files

![lagcomptest](https://user-images.githubusercontent.com/94231804/219881700-8b338ce3-6611-401d-b827-c15d062daae2.png)

**Comment by kurozael** [comment]
I've seemingly resolved the issue, as is confirmed by @the-remeko, but it makes no sense. Further investigation pending but I'm closing it as resolved for now.
