### ISSUE TITLE
[ModelDoc] Generated IKLockDriver bones do not respect Extract Motion, causing Lightprobe and LOD issues

### ISSUE THREAD

**Issue by N-cognito** [sboxgame/issues#2936]
### Describe the bug

When extracting motion from an animation that has IK bones in it, the resulting autogenerated helper bones do not respect the removal of motion. Instead, they keep their original position/animation, resulting in HUGE bounding boxes that cause issues with lightprobes and LODs

The IK bones themselves properly have the motion removed, and the IK Solve behaves as expected, but the excessive bounds caused by the IkLockDrivers causes visual issues within the game

### To Reproduce

1. Have animation with root movement, and bones that are used for IK within ModelDoc
2. Apply ExtractMotion markup to animation
3. Under Bounding Volumes in ModelDoc viewport, turn on Active Sequence Bounds

### Expected behavior

IkLockDriver bones should respect the Extract Motion markup, or be completely disregarded when calculating bounds.

### Media/Files

![image](https://user-images.githubusercontent.com/8404018/219986126-3d58ad79-f744-4efe-88da-404ca08206fe.png)

https://user-images.githubusercontent.com/8404018/219986227-794d1929-6420-45e5-a414-f0e0083d98cf.mp4

https://user-images.githubusercontent.com/8404018/219986230-985ce16f-7f0b-4e06-a79a-930e6177b5ea.mp4

**Comment by MaxLebled** [comment]
It looks like you can solve this by using IKChain nodes instead of IKChainOld/IKRigBiped nodes. Here's some info coming from previous answers I received from Valve engineers:

> **IKChainOld is just an old format for holding the IK chain config data, and should be replaced by IKChain.** The old system used to use bone data to drive whether the ground IK should turn on and off.  It would create a new, fake bone on the skeleton, and set the X value of the bone's translation to be the amount that the Ik should be blended in. For AnimGraph, we instead created the Foot Motion data, which has information about whether the foot is in the air or on the ground, as well as other info.  And the Stride Retargeting node uses that data to IK the legs to the ground. **We also started moving from specifying all the settings of the IK from ModelDoc to the nodes that run the IK in the graph, with the idea that you might want to use different settings with the same IK chain depending on the circumstances**

This leads me to believe that we should not be using IKRigBiped or IKChainOld nodes, because **IK settings are now always superseded by what's in the animgraph.**

I've disabled the IKChainOld nodes on citizen.vmdl and this is fixing the sequence bounds issue there (all graph IK nodes were already using the newer IK chains anyway).

Does this solution work for you?

**Comment by N-cognito** [comment]
This fixes the animation bounds issue, but I can't seem to figure out how to properly use the IKchain. At the moment, it solves only the next bone in the hierarchy, instead of the whole chain

![Screenshot_61](https://user-images.githubusercontent.com/8404018/220193122-a8cf1e84-d1a7-4ae2-ba06-9b5c7d1b5c5d.png)
![Screenshot_60](https://user-images.githubusercontent.com/8404018/220193190-1fa664d7-aca7-458b-9436-951954658160.png)

It's only correcting the knee, when I would expect it to correct the hip as well

**Comment by N-cognito** [comment]
Thank you, this seems to work. Requires a bit of reorganizing the animgraph but MUCH better than having to manually remove root motion from each animation.
