### ISSUE TITLE
[Animgraph/Shadergraph] Add 'Reroute' nodes to make wiring neater.

### ISSUE THREAD

**Issue by yourbadandimbest** [sboxgame/issues#2941]
### For?

Other

### What can't you do?

Sometimes nodes get in the way of wiring and make it hard to see connections.

### How would you like it to work?

Similar to how Blender does it, a reroute node would relay inputs to make wiring neater.
![image](https://user-images.githubusercontent.com/91832803/220320364-080be016-1c60-498f-bfd1-1f512e952b18.png)

### What have you tried?

The citizen animgraph uses empty groups to force wires to line up correctly.

### Additional context

https://docs.blender.org/manual/en/latest/interface/controls/nodes/reroute.html

**Comment by aylaylay** [comment]
This has been added
