### ISSUE TITLE
Developper Torture system not working

### ISSUE THREAD

**Issue by PolEpie** [sboxgame/issues#2948]
### Describe the bug

Hi, since few hours this link not working https://asset.party/get/developer/preview

<img width="1919" alt="CleanShot 2023-02-22 at 16 37 09@2x" src="https://user-images.githubusercontent.com/36932762/220673795-439d4f3d-2cbb-4b13-9cf6-22b0bed04eaf.png">
<img width="1918" alt="CleanShot 2023-02-22 at 16 36 53@2x" src="https://user-images.githubusercontent.com/36932762/220673809-84709d1d-d658-469d-aba2-75f590c0903b.png">

### To Reproduce

Just go there https://asset.party/get/developer/preview

### Expected behavior

You know it

**Comment by domon41c** [comment]
I have the same problem...

**Comment by jakey1995abc** [comment]
I am also having the same issue.

**Comment by TheJaxophone** [comment]
Yup, its doing that to me too

**Comment by Toasty-Engineer** [comment]
still busted as of rn

**Comment by garrynewman** [comment]
This isn't busted, the keys just ran out.
