### ISSUE TITLE
[BindComponent] property becomes null if component is not enabled.

### ISSUE THREAD

**Issue by NotGaylien** [sboxgame/issues#2949]
### Describe the bug

If a component you access via a `[BindComponent]` property is set the components `Enabled = false;`
that property now becomes null.
The component is still there though, and i can still get it with the normal methods you would use to get a disabled component outside of `[BindComponent]` but i want to use the property i made for it!

### To Reproduce

1. create a property like `[BindComponent] public MyEntityComponent MyComponent { get; }`
2. on spawn or whatever create it like `Components.Create<MyEntityComponent >();` you can now use property in step 1 to access it
3. try access it via `MyComponent` it works fine and returns it fine! now you can do `MyComponent.Enabled = false;`
4. try RE access it via `MyComponent` it now is null (im guessing its only looking for active components)

```csharp
[BindComponent] public MyEntityComponent MyComponent { get; }

public override void Spawn()
{
    Components.Create<MyEntityComponent >();
    
    // by default the method above sets the component enabled
    // so MyComponent is returning the component just fine
    Log.Info($"MyComponent - {MyComponent}"); // shows the component in console just fine
    
    MyComponent.Enabled = false;
    
    // now its disabled but its still there i would want to still get it
    // so MyComponent is now returning null
    Log.Info($"MyComponent - {MyComponent}"); // now its null, because its disabled, i still want to get it though!
    
    // HOWEVER if i manually get it and include disabled in the search it returns the component, so its still there!
    Log.Info($"Components.Get<MyComponent>(true);");
}
```

### Expected behavior

Ideally i would have thought it would grab it even if it wasnt enabled.

I would like to to grab it ignoring if its enabled or not.

**Comment by NotGaylien** [comment]
If its not a bug and intended could we at least get a way to manually specify on [BindComponent] to be able to include disabled component.
like
`[BindComponent(includeDisabled = false)]` by default false so it only gets enabled
but i can do
`[BindComponent(true)]` on the property instead to get enabled and disabled

**Comment by DevulTj** [comment]
Lemme know how that works for you - you can now do `[BindComponent( IncludeDisabled = true )]`
