### ISSUE TITLE
Hotloading breaks entity component prediction

### ISSUE THREAD

**Issue by Weldify** [sboxgame/issues#2952]
### Describe the bug

Hotloading breaks entity component prediction in certain scenarios. Noticed it in my game and devultj's sbox fps sample. Couldnt make a minimal repro project. Hopefully this issue will still be useful

### To Reproduce

1. Download and set up https://github.com/DevulTj/sbox-fps_sample
2. Start the game
3. Hotload
4. Walking, jumping, etc will now spam prediction errors

### Expected behavior

Shouldnt break

### Media/Files

![sbox-dev_0SI4co1nIe](https://user-images.githubusercontent.com/66477673/221214270-f8222d74-4b68-48fe-be6a-d044c94e77bd.gif)

**Comment by Weldify** [comment]
I found another bug recently and I'm pretty sure that's exactly whats causing this issue
https://github.com/sboxgame/issues/issues/3391

**Comment by Weldify** [comment]
Didn't mean to close this

**Comment by Metapyziks** [comment]
Should be fixed now along with #3391, but please reopen if it's still an issue.
