### ISSUE TITLE
List of classes properties flicker on prefab editor

### ISSUE THREAD

**Issue by TheBoxTrot** [sboxgame/issues#2953]
### Describe the bug

List of classes properties flicker on prefab editor

### To Reproduce

create a prefab with an entity that has a list of a class with accessible properties 

### Expected behavior

no flickering 

### Media/Files

https://www.youtube.com/watch?v=UdWMLmfNjAY

**Comment by tjones4701** [comment]
![image](https://user-images.githubusercontent.com/49579085/233505943-f3f9020c-6f9a-416f-9eb3-d4c100fd34e4.png)

I have this same issue too.
