### ISSUE TITLE
[Hammer] Expose the tangent values of piecewise bezier path nodes

### ISSUE THREAD

**Issue by AngryNeox** [sboxgame/issues#2954]
### For?

Hammer

### What can't you do?

I currently can't see or adjust the incoming or outgoing tangent values of path nodes via the object properties window.

### How would you like it to work?

Show the offset of the tanget points in the object properties window of path nodes.

For example:
![grafik](https://user-images.githubusercontent.com/6373976/221323377-f6aee469-6298-4900-959f-d2d74f2d92c7.png)

### What have you tried?

You can adjust their values by moving the tangent points in the viewports. It's quick and easy for rough adjustments, but if you want to set their position to on a specific value you need to turn down the grid and find the correct position manually.

![grafik](https://user-images.githubusercontent.com/6373976/221322201-c9b2d5a5-3fbd-48c5-9176-f016fe4ee081.png)

### Additional context

A small bonus would be a field to see the calcuatated length of a tangent line and the option to adjust it while keeping the direction of it.

**Comment by robotboy655** [comment]
Yes, that would be a separate issue.
