### ISSUE TITLE
Error and Crash on using GameTask.RunInThreadAsync

### ISSUE THREAD

**Issue by byplt** [sboxgame/issues#2958]
### Describe the bug

When uses GameTask.RunInThreadAsync, giving this error:
CRenderContextBase::SetAssociatedThreadIndex():
Too many threads accessing the render device, need to increase -r_max_device_threads

There was no any problem about it, and was working properly, I did not update my addon. I guess started error one week ago.

### To Reproduce

1. Start Sandbox gamemode
2. Spawn entities->Map Parser
3. Spawn some maps and will be occur

### Expected behavior

 No popup or crash, as expected without error.

**Comment by handsomematt** [comment]
I think I fucked this, will investigate.

**Comment by byplt** [comment]
fixed
