### ISSUE TITLE
Entity hitbox not detected by Trace.Ray()

### ISSUE THREAD

**Issue by quntherdev** [sboxgame/issues#2959]
### Describe the bug

I created an entity that has a model and hitboxes.

In spawn() method, I have specified :
		EnableHitboxes = true;

In the class of my player, in **FrameSimulate**, I write :

```
var trace = Trace.Ray( AimRay.Position+AimRay.Forward, AimRay.Position+AimRay.Forward*100 ).Ignore( this ).UseHitboxes().Run();
		
Log.Info( trace.Hitbox.GetName());
```

What is displayed : "invalid"

My model's hitbox is not detected, I'm not the only one who had this problem.

Moreover, by adding "EnableHitboxes = true;", my entity isn't movable anymore, I can't manipulate it with the physic gun, I wonder if it is normal

### To Reproduce

1- Make an Entity class, which loads a model containing hitboxes
2- Add `EnableHitboxes = true;` to its spawn() override method
3- In Player class, in FrameSimulate(), add :

```
var trace = Trace.Ray( AimRay.Position+AimRay.Forward, AimRay.Position+AimRay.Forward*100 ).Ignore( this ).UseHitboxes(  ).Run();
		
Log.Info( trace.Hitbox.GetName());
```

4- Run gamemode
5- Stare the hitbox(s) of your entity
6- Look at the console, "invalid" should be written

### Expected behavior

Instead of "invalid", the hitbox name should be written

**Comment by Fortune117** [comment]
Try adding `SurroundingBoundsMode = SurroundingBoundsType.Hitboxes;` to your entity

**Comment by DevulTj** [comment]
Does your entity have a bone? Currently it needs to have at least one for the hitboxes to be created.
