### ISSUE TITLE
Asset Browser type filter ui doesn't know about custom GameResources

### ISSUE THREAD

**Issue by DoctorGurke** [sboxgame/issues#2967]
### Describe the bug

The Editor Asset Browser doesn't know about custom GameResources that are mounted atfer the game originally loads.
The game needs to be restarted to see custom GameResource types in the asset browser's type filter ui, there does not seem to be an intuitive way to refresh the ui either.

### To Reproduce

To observe this behavior, see the asset browser type filter ui as seen attached.

1. Have some project with a custom GameResource definition
2. Launch the game with the project **disabled**
3. Enable the project, note the asset browser
4. Restart the game with the project still **enabled**
5. Works fine

### Expected behavior

The asset browser tag picker ui should probably refresh on game hotload to properly refresh according to the activated/mounted content.

### Media/Files

![jE0CPWeOVV](https://user-images.githubusercontent.com/12602100/221608336-dd54f2ff-c8db-4578-9c00-99061cba4f46.png)
![06Xg0anGRD](https://user-images.githubusercontent.com/12602100/221608347-362d0d02-ec66-4027-baaa-5fae9a6633f2.png)

**Comment by robotboy655** [comment]
This should be fixed.

**Comment by DoctorGurke** [comment]
This seems to be even more broken now? I just activated speed-dial and had to restart the editor before I could find any of the custom resource types at all. They just wouldn't show up, manually typing `t:sdwep` for example also did nothing.

**Comment by DoctorGurke** [comment]
To clarify, they wouldn't show up in the asset browser at all, even with no filter or tags applied

**Comment by robotboy655** [comment]
Are you sure the gamemode you enabled compiled successfully? There is an unrelated bug to do with compiling gamemodes in menu state.

**Comment by DoctorGurke** [comment]
just checked again and it seems to work fine now, not sure what changed
anyways thanks for the fix!
