### ISSUE TITLE
Project Setup Resource Paths won't include custom file types

### ISSUE THREAD

**Issue by yuberee** [sboxgame/issues#2973]
### Describe the bug

We encode and decode our own .qoa sound file (As an alternative to the current sound API) but when joining a server the .qoa files aren't uploaded.
This is what our Resource Paths look like:
![image](https://user-images.githubusercontent.com/59583743/222004538-1a59d8e6-53b1-4b65-8873-a2beb7ead65d.png)

### To Reproduce

1. Download the .qoa file below
2. Copy our custom Resource Paths settings so it includes .qoa files or anything inside the folder it's located in
3. Try uploading the game to asset.party or getting someone to join and download the file
4. You'll see that the file isn't included in the files to upload to asset.party or it doesn't get downloaded to the client

### Expected behavior

Any custom resource should get uploaded if included in the Resource Paths

### Media/Files

The .qoa file:
https://drive.google.com/file/d/1mp5tAmNGLAH8o7MIuMs7RbqAFARFybJR/view?usp=sharing
(Github won't let me upload .qoa files)

### Additional context

Since we're reading the bytes, right now we are "tricking" S&box by changing the file type to be .json, which isn't optimal and doesn't cover all cases.

**Comment by handsomematt** [comment]
should be able to use whatever now
