### ISSUE TITLE
Bounding box traces will sometimes return a normal of (0,0,0)

### ISSUE THREAD

**Issue by xezno** [sboxgame/issues#2974]
### Describe the bug

Under some circumstances, a bounding box trace will return a normal value of (0,0,0) despite hitting a surface.

### To Reproduce

I put together a quick repro so you can test this easily. To use it, approach a surface and primary attack/left click. This will display info about the trace for a few seconds.

Here's the project: [trace_normal_repro.zip](https://github.com/sboxgame/issues/files/10855624/trace_normal_repro.zip)
(this is just the minimal template with changes in Pawn.cs from lines 68 to 90).

https://user-images.githubusercontent.com/12881812/222005738-de14a215-f177-4c68-b6a2-bf7e11bde732.mp4

### Expected behavior

Sphere traces don't seem to have this issue; if you change Pawn.cs line 76 from `.Size( Mins, Maxs )` to `.Radius( 16f )`, you'll get the expected surface normal:

https://user-images.githubusercontent.com/12881812/222005759-b2d103d4-cd36-4d1a-b0f7-7a784cd30035.mp4

### Additional context

Entirely possible I could just be doing something dumb here, but I asked around and nobody seemed to know what was going on either

**Comment by cr4yz** [comment]
The box trace has a negative Z value and extends into the ground, starting solid.  Are you looking to extract a normal from traces that start solid?
