### ISSUE TITLE
Baked fog doesn't appear in game

### ISSUE THREAD

**Issue by DrewBritt** [sboxgame/issues#2975]
### Describe the bug

Baked fog simply doesn't appear in game. It still bakes, so the data is still in the map, it just doesn't appear in game at all. Unfortunately I can't pinpoint when exactly this happened as I had a break for the weekend, but I believe it worked sometime around 2/24/23.

### To Reproduce

1. Load into map with baked fog ([repro project with singular light/baked fog](https://github.com/sboxgame/issues/files/10857026/fog_repro.zip) or "pmg.ce_basement" on asset.party)
2. Observe baked fog (fog over table) not appearing as such: ![fog not appearing](https://cdn.discordapp.com/attachments/1040189599286296578/1080228428944511036/image.png)

### Expected behavior

Prominent fog over table (baked fog) should appear in game as such (screenshot is from same compile as current asset.party upload): ![fog appearing](https://media.discordapp.net/attachments/1040189599286296578/1080228428575416403/image.png)

**Comment by samzanemesis** [comment]
Should be fixed, I've done some changes on how baked fog is previewed and is decided to be shown
