### ISSUE TITLE
Add Parallax occlusion mapping.

### ISSUE THREAD

**Issue by DoctorGurke** [sboxgame/issues#2981]
### For?

S&Box

### What can't you do?

Parallax Occlusion mapping has been removed as a shader (feature) almost half a year ago as part of a general shader purge. (approx. 06/09/2022 afaik). We've since been left without a replacement.
It turns out there has been numerous "attempts" over the past couple months, even with a merge to master... which got reverted within the hour...

### How would you like it to work?

Any basic parallax occlusion mapping would be better than nothing. Not even asking for fancy steep solutions or whatever. Maybe make it work with blendable #1429 #831 while we're at it.

### What have you tried?

N/A

### Additional context

Said attempts have been on the now seemingly stale shader-pain branch. then on shader-pain-part1. Then on complex-parallax. What's going on here?

![Discord_vq2mOWb4A3](https://user-images.githubusercontent.com/12602100/222796541-5baf8458-b4f8-4270-9b0c-55b44b8667cc.png)

![Discord_IBF9vOQVSx](https://user-images.githubusercontent.com/12602100/222796549-8ba12c0b-d6c4-4c4d-ab04-6b2c136e8ade.png)

![Discord_dpmAkyE3TX](https://user-images.githubusercontent.com/12602100/222796565-da446b0e-60af-49c3-872b-90c00b72fcee.png)

**Comment by DoctorGurke** [comment]
Any news on this? 😄

**Comment by PixelQubed** [comment]
Pretty please

**Comment by DevulTj** [comment]
I believe this is in - gonna keep it open for a few days though..
