### ISSUE TITLE
Hammer: Active Material window does not remember selected icon layout

### ISSUE THREAD

**Issue by Gmod4phun** [sboxgame/issues#2983]
### For?

Hammer

### What can't you do?

The Hammer Active Material window resets itself to the Small Icons view everytime its reopened.

![image](https://user-images.githubusercontent.com/5991682/222900379-9acadd3b-9184-446f-8e0a-be24aa4f61f8.png)

### How would you like it to work?

Remember the selected type of icon (medium, big, etc.) when reopening the window.

### What have you tried?

Changing it everytime like a maniac.

**Comment by robotboy655** [comment]
This is done on purpose, but I have make it not reset the icon size. It will still reset to icons from a list though for stuff like selecting shaders.

**Comment by handsomematt** [comment]
No worries, I was gonna do the same thing.

**Comment by Gmod4phun** [comment]
Seems to be working nicely, thank you. I will leave the issue open for a white to be sure, in case there are any issues.
