### ISSUE TITLE
Setting game specific ConVars on dedicated servers

### ISSUE THREAD

**Issue by ItsRifter** [sboxgame/issues#2989]
### For?

S&Box

### What can't you do?

In dedicated servers, there's no possible method to setting ConVars before a game starts up

### How would you like it to work?

You should be able to set the games convars either in the .bat file or through some other method before a game starts up

Should be able to set the ConVar to the appropriate value needed like bools etc.

### What have you tried?

Tried setting +[ConVarName] to a value but has no effect

**Comment by DevulTj** [comment]
@kurozael I believe you implemented something like this a couple months ago

**Comment by kurozael** [comment]
> @kurozael I believe you implemented something like this a couple months ago

Hmm, I did, it worked then. I'll check tomorrow something may have broken it.

**Comment by ItsRifter** [comment]
Any update?

**Comment by kurozael** [comment]
There's a build underway now @ItsRifter that should solve the issue. Can you confirm after the build is up on Steam, please also make sure your game is re-compiled/re-uploaded to Assert Party just to ensure it has the latest codegen. It's all working for me locally.

**Comment by ItsRifter** [comment]
Can confirm with both game and server updated (and reuploaded to backend)
