### ISSUE TITLE
[Hammer] Lightshaft support for environment lighting

### ISSUE THREAD

**Issue by KayaDLX** [sboxgame/issues#2991]
### For?

Hammer

### What can't you do?

At the moment we can't really have nice lightshafts accross all our level apart from using fog volumes with fake directional lights to simulate the sunlight creating godrays.

### How would you like it to work?

Unreal Engine has this cool feature called Lightshaft on their environment lighting, it looks mostly screenspace based. There are controls to change the range of the occlusion, the color of the bloom, its intensity and all that.

Here's an exagerated example from my UE5 project:

https://user-images.githubusercontent.com/67245359/223586299-540f94ff-1df7-403f-96c6-5f032ae345f3.mp4

Fiddling around with the parameters:

https://user-images.githubusercontent.com/67245359/223586277-176b634e-bc49-4ac7-8e23-f4f51f675e29.mp4

### What have you tried?

Using individual fog volumes with fake additional lights to simulate the sunlight volumetrics.

### Additional context

Worth adding that volumetric fog by itself absorbs light in the levels making the scene darker, and the sunlight itself cannot contribute to volumetrics fog in the current engine, which is where lightshafts would come in clutch I believe.
![image](https://user-images.githubusercontent.com/67245359/223586010-962d3202-95d7-4d90-961e-510bc2e050b5.png)

**Comment by DoctorGurke** [comment]
looks like it could be potentially screen space? would be a cheaper and easier to setup alternative

**Comment by samzanemesis** [comment]
That's silly, I've got light shafts to work with light_env, I'd like to keep things as unified as possible
