### ISSUE TITLE
VR: Immediate mode Scene instances do not render correctly while in VR

### ISSUE THREAD

**Issue by xezno** [sboxgame/issues#3003]
### Describe the bug

The new `SceneInstance` API doesn't seem to draw scenes correctly while in VR. Instead of drawing the scene as it should, it renders two gizmos in stereo view, and doesn't appear to clear buffers correctly.

![image](https://user-images.githubusercontent.com/12881812/224460932-ac5f40fe-7c36-4a21-bce0-00e697b2551c.png)

It would be nice to have this because prefabs make it quick and easy to iterate on things. I'm using prefabs for my VR hands, for example, as it allows me to adjust the offsets of the hand models easily.

### To Reproduce

1. Launch the game with the `-vr` command line option
2. Create or find an existing prefab, launch the prefab editor

### Expected behavior

Launching without `-vr` gives me the expected result:
![image](https://user-images.githubusercontent.com/12881812/224461048-a221fb4a-69ff-40d5-99a5-289f87309b4b.png)

### Additional context

This doesn't appear to happen in scenes inside the C++ tools (e.g. ModelDoc, Material Editor previews).

**Comment by handsomematt** [comment]
Should be fixed for any scene rendered from tools now, let me know if not
