### ISSUE TITLE
`AddMeshShape()` or `AddHullShape()` with wrong vertices crash s&box

### ISSUE THREAD

**Issue by PolSpock** [sboxgame/issues#3008]
### Describe the bug

Hello, i'm currently learning mesh generation and manipulation

I'm inspired by works from https://github.com/Facepunch/sbox-worldcraft/ and https://github.com/Facepunch/sbox-csg

My objective is to retrieve vertices from triangle by a given position.
So i try to create a physics shape for each of the triangles of my mesh and retrieve it with [Sandbox.TraceResult.Triangle](https://asset.party/api/Sandbox.TraceResult.Triangle)
I'm maybe wrong with my logic, I'm still learning and experimenting with many things.

But when I try to add shape to my PhysicBody with `AddMeshShape()` or `AddHullShape()`, my game crash :
Maybe I put the wrong vertices in my Shape but I don't think an s&box crash is a good result.

### To Reproduce

1) Add this function to an entity :
```
public void GenerateHulls()
{
	// From [CSG logic](https://github.com/Facepunch/sbox-csg/blob/0d5798bc88713c9fe793bd7d494f0ebf954b8191/code/CsgSolid.Mesh.cs#L37)
	SetupPhysicsFromSphere( PhysicsMotionType.Static, 0f, 1f );
	PhysicsBody.ClearShapes();
	
	// From [Worldcraft](https://github.com/Facepunch/sbox-worldcraft/blob/master/code/Primitives/PrimitiveBox.cs)
	float Size = 64f;
	var positions = new Vector3[]
	{
		new Vector3(-0.5f, -0.5f, 0.5f) * Size,
		new Vector3(-0.5f, 0.5f, 0.5f) * Size,
		new Vector3(0.5f, 0.5f, 0.5f) * Size,
		new Vector3(0.5f, -0.5f, 0.5f) * Size,
		new Vector3(-0.5f, -0.5f, -0.5f) * Size,
		new Vector3(-0.5f, 0.5f, -0.5f) * Size,
		new Vector3(0.5f, 0.5f, -0.5f) * Size,
		new Vector3(0.5f, -0.5f, -0.5f) * Size,
	};

	var faceIndices = new int[]
	{
		0, 1, 2, 3,
		7, 6, 5, 4,
		0, 4, 5, 1,
		1, 5, 6, 2,
		2, 6, 7, 3,
		3, 7, 4, 0,
	};

	var uAxis = new Vector3[]
	{
		Vector3.Forward,
		Vector3.Left,
		Vector3.Left,
		Vector3.Forward,
		Vector3.Right,
		Vector3.Backward,
	};

	var vAxis = new Vector3[]
	{
		Vector3.Left,
		Vector3.Forward,
		Vector3.Down,
		Vector3.Down,
		Vector3.Down,
		Vector3.Down,
	};

	List<SimpleVertex> verts = new();
	List<int> indices = new();

	for ( var i = 0; i < 6; ++i )
	{
		// I just want to add shapes, so i ugly clear the list for the other face
		verts.Clear();
		indices.Clear();

		var tangent = uAxis[i];
		var binormal = vAxis[i];
		var normal = Vector3.Cross( tangent, binormal );

		for ( var j = 0; j < 4; ++j )
		{
			var vertexIndex = faceIndices[(i * 4) + j];
			var pos = positions[vertexIndex];

			verts.Add( new SimpleVertex()
			{
				position = pos,
				normal = normal,
				tangent = tangent,
				texcoord = Vector2.Zero,
			} );
		}

		indices.Add( i * 4 + 0 );
		indices.Add( i * 4 + 2 );
		indices.Add( i * 4 + 1 );
		indices.Add( i * 4 + 2 );
		indices.Add( i * 4 + 0 );
		indices.Add( i * 4 + 3 );
		
		// Create shape for each face
		var physicsShape = PhysicsBody.AddMeshShape( verts.Select( x => x.position ).ToList(), indices );
	}

}
```
2) Call the function & crash

### Expected behavior

I think my logic is wrong, or my vertices are wrong but the documentation of https://asset.party/api/Sandbox.PhysicsBody.AddMeshShape(List,List) or https://asset.party/api/Sandbox.PhysicsBody.AddHullShape(Vector3,Rotation,List,bool) said : "The created shape, or null on failure."
But i can't get a null on failure cause the game crash each time

**Comment by aylaylay** [comment]
You're indexing vertices outside of the array, you're clearing verts and indices in your loop (correct) but then your indices are i * 4 (incorrect)

I will see about protecting against this though instead of crashing

**Comment by aylaylay** [comment]
It should now throw an exception instead.

```		indices.Add( 0 );
		indices.Add( 2 );
		indices.Add( 1 );
		indices.Add( 2 );
		indices.Add( 0 );
		indices.Add( 3 );
```

Try these indices instead

**Comment by PolSpock** [comment]
I'm not crashing anymore, thanks 💌
I can continue my learning 😂
