### ISSUE TITLE
Prefabs: `struct` Types Show "Unknown Editor"

### ISSUE THREAD

**Issue by LeQuackers** [sboxgame/issues#3013]
### Describe the bug

When I try to mark a `struct` property with `[Prefab]`, it displays "Unknown Editor".

### To Reproduce

1. Create a `struct` with test properties
2. Create some test `Entity` class that is marked with `[Prefab]`
3. Add a property to the test `Entity` that uses the previously created `struct` type
4. See that the `struct` property displays "Unknown Editor" in the prefab editor

### Expected behavior

`struct` types work in the prefab editor in a similar manner to how they work in the inspector.

### Media/Files

Here's the test code and results:
```cs
public struct StructTest
{
	public int StructFoo1 { get; set; }
	public int StructFoo2 { get; set; }
	public string StructFoo3 { get; set; }
}

/// <summary>
/// <see cref="TestEntityFoo2"/> displays "Unknown Editor".
/// </summary>
[Prefab]
public partial class TestEntity : Entity
{
	[Prefab]
	public int TestEntityFoo1 { get; set; }

	[Prefab]
	public StructTest TestEntityFoo2 { get; set; }
}

/// <summary>
/// <see cref="ResourceFoo2"/> works fine.
/// </summary>
[GameResource( "Test Resource", "test", "a test resource" )]
public class ResourceTest : GameResource
{
	public int ResourceFoo1 { get; set; }
	public StructTest ResourceFoo2 { get; set; }
}
```
`TestEntity` in the prefab editor:
![image](https://user-images.githubusercontent.com/16133099/224601385-a012b182-783d-4016-82f3-3542a0b3a876.png)
`ResourceTest` in the inspector:
![image](https://user-images.githubusercontent.com/16133099/224601453-5d4d0e0b-13e3-4cef-99db-9f87e6632e77.png)

**Comment by LeQuackers** [comment]
After digging a bit more into this, there isn't actually a `struct` property editor; it's all handled in `PropertySheet.AddProperty( PropertyInfo, ref object )` for some reason, which also explains why `struct` types work in the inspector and not prefabs. This is very strange because you can find things like `CanEditAttribute.CreateEditorFor( "struct" );` here and there in the code, which threw me way off.

The easiest way to fix this would probably be to add a legit `struct` property editor.

**Comment by garrynewman** [comment]
The way this property editor works right now is kind of taped together. 

I'm going to be looking at rewriting it over the next few months to make it suck less and support a bunch of stuff that it currently doesn't support (like multi-selection editing etc)
