### ISSUE TITLE
Model Shows as an Error when Drag and Drop into Game window.

### ISSUE THREAD

**Issue by Baik90** [sboxgame/issues#3017]
### Describe the bug

When you Drag and Drop an model it Shows the Error model when any other Model is Active Selected.

### To Reproduce

1.Select any Model in your Asset Browser
2.Drag&Drop any other Model which is not Selected
3.See an Error model Popping up

### Expected behavior

The Model you drag into the Game Window should load in.

### Media/Files

https://user-images.githubusercontent.com/88790023/224802892-5bbcd38d-d9fb-4702-b296-4d45e343120a.mp4

**Comment by robotboy655** [comment]
Should be fixed when the game next updates.
