### ISSUE TITLE
`ClearMaterialOverride` on `SceneObject`

### ISSUE THREAD

**Issue by timmybo5** [sboxgame/issues#3018]
### For?

S&Box

### What can't you do?

A clean way to remove material overrides on a SceneObject.
I found a workaround by calling `SceneObject.SetMaterialOverride` with a `null` value. 
However it would be nice to keep it consistent on classes that support material overrides.

### How would you like it to work?
`SceneObject.ClearMaterialOverride()`

**Comment by robotboy655** [comment]
Added.
