### ISSUE TITLE
Certain decals apply textures to entire map, cannot undo when placed.

### ISSUE THREAD

**Issue by BatterySand** [sboxgame/issues#3019]
### Describe the bug

decals will randomly apply to meshes within hammer editor, and the undo button, or control z does not undo it. have to completely restart map without saving to undo it. Do not know which decals cause the issue, as it is seemingly random.

### To Reproduce

Go to hammer editor.

try to apply decal to map, try different ones because some work some dont.

try to undo when applied to mesh instead of wall.

### Expected behavior

Apply decal to wall normally. 

### Additional context

Im running on windows 11, RTX 2080 TI, intel core i7 9700k @ 3.60 GHZ,  32 gig ram

**Comment by Gmod4phun** [comment]
Shouldn't you see the decal in the outliner and be able to select it there and then delete it?

**Comment by BatterySand** [comment]
> Shouldn't you see the decal in the outliner and be able to select it there and then delete it?

it doesnt show up in  the outliner

**Comment by DoctorGurke** [comment]
How are you applying the decal? Which decals have you tried? Can you show some screenshots or videos?

**Comment by DoctorGurke** [comment]
Also will the bugged decal show up on the compiled map in-game or just in hammer?

**Comment by handsomematt** [comment]
pretty sure I've fixed this now
