### ISSUE TITLE
Artifacting in menus

### ISSUE THREAD

**Issue by Sporeo** [sboxgame/issues#3030]
### Describe the bug

Loading the game into the main menu/editor results in the images suffering from artifacting. As with any game mode. This only affects S&box, no other game title suffers from this. 

What I have done:
1. upgrading GPU drivers to newest version.
2. Downgrading GPU drivers to previous version.
3. Removing the drivers all together by DDU, then reinstalling.
4. Uninstalling S&Box, then reinstalling.
5. Validating files.
6. Clearing steams download cache, removing S&box, then reinstalling.

All of which results in the issue persisting.

![sbox_5CRd77Jpf1](https://user-images.githubusercontent.com/12488324/225717115-e5e42b7f-0706-4d47-9e45-ec5489362172.jpg)
![sbox-dev_Zk8QuJX5Kw](https://user-images.githubusercontent.com/12488324/225717188-3dff8aab-ec4b-460d-b428-8d40b9c79cf3.png)
![sbox_MW4zRuugpx](https://user-images.githubusercontent.com/12488324/225717265-eaab9017-9d84-4ca4-a92c-82703d8db6f2.png)

### To Reproduce

1. Load S&Box game or editor.
2. Observe the main menu or sub menus.

### Expected behavior

Images to not have artifacts on them.

### Additional context

Operating System: Windows 11 Pro, 22H2, build version 22621.1265
CPU: Ryzen 7 5800X
GPU: Radeon 6800XT driver version 23.3.1
RAM: 32 GB DDR4

Running latest steam build for the game.

If you need more information, please let me know.

**Comment by trende2001** [comment]
this is happening with amd drivers. downgrade your version to the previous one

**Comment by SryEyes** [comment]
Ye amd adrenaline 23.3.1 bricked that

**Comment by SryEyes** [comment]
Still occurring at amd adrenaline version 23.4.1

**Comment by Vasolix** [comment]
still in adrenaline version 23.4.3

**Comment by handsomematt** [comment]
#3347 I'll get this fixed soon

**Comment by aylaylay** [comment]
Should be fixed now.

**Comment by Sporeo** [comment]
> Should be fixed now.

Yes, it is fixed.
