### ISSUE TITLE
`filter` css property seems to affect scale with margin elements

### ISSUE THREAD

**Issue by kodi022** [sboxgame/issues#3031]
### Describe the bug

for what i've found so far, any filter on something with any `margin` makes it scale or shrink when it shouldn't.

the greater the margin, the greater the shrinkage.
this does not happen without margin, it does not happen with padding either.

```
.menubutton {
    background-color: rgb(255, 191, 71);
    border: 2px;
    width: 200px;
    margin-left: 20px;
    align-items: center;
    justify-content: center;
    aspect-ratio: 3;
}
.menubutton:hover {
    filter: brightness(1.5);
}
```
no hover:
![sbox-dev_W1O18YvVKS](https://user-images.githubusercontent.com/29390269/225753336-e6afb42d-c8b5-4ab3-988d-d67ec868cfdf.png)

hover:
![sbox-dev_le9SDidLps](https://user-images.githubusercontent.com/29390269/225752811-169423ee-d901-45e3-902b-0e2b93dcce91.png)

with `margin-left: 600px;`:
![sbox-dev_P4EARDhyYI](https://user-images.githubusercontent.com/29390269/225753917-80aa8196-d7fb-4f78-bef8-e8aa444f2211.png)

### To Reproduce

1. aaa well make a panel with these
```
.menubutton {
    background-color: rgb(255, 191, 71);
    border: 2px;
    width: 200px;
    margin: 60px;
    align-items: center;
    justify-content: center;
    aspect-ratio: 3;
    filter: brightness(1.4);
}
```
2. comment/uncomment the filter, witness the change

### Expected behavior

filter shouldnt apply scaling to the panel

### Media/Files

https://user-images.githubusercontent.com/29390269/225755297-bc9cdc4b-e50e-4542-9c60-44a3a19d5a27.mp4

**Comment by cr4yz** [comment]
Got it, should be sorted in the next update.  Lemme know if you have any more troubles
