### ISSUE TITLE
env_sky isn't displaying color correctly even with light_environment having the same sky color

### ISSUE THREAD

**Issue by MrBrawls** [sboxgame/issues#3038]
### Describe the bug

I'm trying to have a sky have a different color than the original texture has, but while it works in-editor, it doesnt work ingame even if the light_environment sky color is the same as the env_sky color.

### To Reproduce

1. create a new map with env_sky and light_environment
2. set sky material in env_sky to " materials/skybox/light_test_sky_night_basic.vmat "
3. change skybox tint color in env_sky to a different color (i tried to make it #ff89ab)
4. go to light_environment and go to the sky property and set the color to the same color as in the env_sky skybox tint color
5. run the map after a full compile (x1024,Standard lighting for quicker results) and see that the sky isn't displaying the color correctly

### Expected behavior

Should've seen the sky have the color shown within the editor as seen below.

### Media/Files

expected editor sky color:
![image](https://user-images.githubusercontent.com/116766298/226082395-aa492866-29b6-4ff9-ba0e-ce732f193e49.png)

in-game sky color: 
![image](https://user-images.githubusercontent.com/116766298/226082060-8a8e792f-8b1e-470f-aade-c363864e02f0.png)

### Additional context

OS: Windows 10 Home 21H2
Graphics: NVIDIA GeForce RTX 3070 Ti
CPU: 11th Gen Intel Core i7-11700KF @ 3.60 GHz
RAM: 16 GB

don't think this is hardware specific, but I put it in just in case

**Comment by aylaylay** [comment]
I've set the light sky color and sky tint the same and it works fine. Can you give me a small map that isn't working?

**Comment by MrBrawls** [comment]
> I've set the light sky color and sky tint the same and it works fine. Can you give me a small map that isn't working?

something else in the map might be causing the problem, because making a new map doesnt make the problem appear. >;/ unsure what to do about this other than sending the small map with the exact geometry of the map except for the custom material.. so here it is [bug example.zip](https://github.com/sboxgame/issues/files/11186240/bug.example.zip)

**Comment by aylaylay** [comment]
Okay so I'm a bit confused. You're right in that the skybox is tinted incorrectly but I tried that skybox and color on a new map but it still is tinted incorrectly.

**Comment by MrBrawls** [comment]
ah man, yeah that's incredibly frustrating. tried deleted the stuff within the map that might've done it but no luck

**Comment by aylaylay** [comment]
It has nothing to do with what's in the map, we're just handling skybox tint incorrectly

**Comment by MrBrawls** [comment]
ahhh alright good to know that it is an actual bug. thank you for looking into this.

**Comment by aylaylay** [comment]
Should be fixed when the game next updates, let me know if it works for you

**Comment by MrBrawls** [comment]
damn it didnt work after recooking 
![image](https://user-images.githubusercontent.com/116766298/230818520-4b88bf28-34ef-4ed6-8622-6f8da28bde90.png)

**Comment by aylaylay** [comment]
@MrBrawls Sandbox gamemode just needed reuploading because base changed. It should be working now.

**Comment by MrBrawls** [comment]
ayyyyyy its working! 
![image](https://user-images.githubusercontent.com/116766298/230834960-b347ece3-d1b0-4fb9-aa43-9b0c2dc5722c.png)
thank you so much!

**Comment by aylaylay** [comment]
Awesome
