### ISSUE TITLE
Hammer and SFM Compaitbilty

### ISSUE THREAD

**Issue by EladTheLevy** [sboxgame/issues#3040]
### For?

S&Box, Hammer, Source Film Maker

### What can't you do?

You are unable to Make maps in hammer and add SFM compataible rigs for certain objects.

### How would you like it to work?

I'd like it to work by having the option in hammer that'll allow you to add SFM rigs into the object(s) that You Wish to add them those rigs.
And after You added them, You can Open up SFM(in sbox) and you can move **those** object(s) that You added them the SFM Rigs!

### What have you tried?

I didn't try that because I know that Hammer is currently in C++, and That ya'll at FacePunch studios would need to add the C++ And convert it into C#

### Additional context

None

**Comment by yuberee** [comment]
So a way to pose ragdolls in your map and also give them clothing to then bake/place?
Makes sense if you want to have corpses laying around.

**Comment by EladTheLevy** [comment]
or If you have a box that a character needs to move around

**Comment by EladTheLevy** [comment]
or _or_ **o r** if you have a charater that needs to have physices and also needs to be moved around by you in SFM

**Comment by handsomematt** [comment]
I doubt we'll do this.
