### ISSUE TITLE
EditorModel attribute doesn't accept vmdl_c

### ISSUE THREAD

**Issue by yuberee** [sboxgame/issues#3047]
### What it is?

The [EditorModel] attribute only accepts ".vmdl" file paths, it's unintuitive since right-click -> Copy file path returns the ".vmdl_c" path and other attributes such as [Model] do accept it.

### What should it be?

It should accept both .vmdl and .vmdl_c file paths or/and right-click -> Copy file path to return the ".vmdl" path instead

**Comment by robotboy655** [comment]
Done.
