### ISSUE TITLE
[Editor] Multiple "Supported Games" entries for Map projects

### ISSUE THREAD

**Issue by DrewBritt** [sboxgame/issues#3048]
### For?

S&Box

### What can't you do?

Currently, you are unable to add multiple "Supported Games" to s&box map projects. The selector only lets you select one package at a time.

![image](https://user-images.githubusercontent.com/43252311/226806667-b066ca2c-ee57-4e8c-97dc-2af6998e91d5.png)

This setting is essential for games that have `Any with Support` for their `Map Selection`, so properly being able to select multiple games for one map would be nice.

### How would you like it to work?

The UI should support selecting multiple "Supported Games" in case your map supports multiple games' entities, say a map for Crazy Eights and Alex's Poker. It'd probably be best to have a list you can add/remove entries from and select packages for said entries.

### What have you tried?

You can already support multiple packages with one map project if you directly edit the project's `.addon` file. This works as expected in game.

![image](https://user-images.githubusercontent.com/43252311/226807222-4b1e711f-5908-4f9d-9fbb-2cab61f6bd8d.png)

**Comment by DevulTj** [comment]
Pretty sure you can just pick multiple packages in the Package Selector with shift/right click. Or by comma-separating idents manually.

https://user-images.githubusercontent.com/22372616/228059148-148c0aa9-15f8-49b8-87bc-d96dcf685123.mp4
