### ISSUE TITLE
ent_platform and ent_path_platform broken for months?

### ISSUE THREAD

**Issue by MrBrax** [sboxgame/issues#3060]
### Describe the bug

I'm not sure if it's the entity itself or some kind of value not created by hammer because new platforms don't work. I might just be choosing the wrong settings, but I feel like it's the default stuff.

### To Reproduce

1. Make map with ent_platform and button
2. Press it and nothing will happen

### Expected behavior

Platform should move

### Media/Files

[platform_test.zip](https://github.com/sboxgame/issues/files/11064829/platform_test.zip)

**Comment by MrBrax** [comment]
Did it get pushed to steam? It doesn't seem to be working for me.

**Comment by handsomematt** [comment]
Whatever gamemode you're testing on needs to be recompiled with the latest base changes.

**Comment by MrBrax** [comment]
That would be sandbox then, is that not automatically compiled?

**Comment by robotboy655** [comment]
I keep forgetting about this..

**Comment by MrBrax** [comment]
It works again, nice!

Something i just noticed that would have wasted many of my troubleshooting hours is that i named the first **node** of the path instead of the path itself, not sure if this is a new feature or i just lucked out the first time. Probably an easy mistake to make.

**Comment by robotboy655** [comment]
It's definitely something that has to stay (so you can target individual nodes, to change per-node speed, etc), so I am not sure what can be done about it besides classifying it as user error.

**Comment by MrBrax** [comment]
I suppose that's fair.
