### ISSUE TITLE
Add support for CS2 contents.

### ISSUE THREAD

**Issue by Kud-Fountain** [sboxgame/issues#3061]
### For?

Other

### What can't you do?

Currently S&Box can not load any CS2 assets on the editor.

### How would you like it to work?

As title

### What have you tried?

I have tried unpacking CS2 assets into S&Box, but none of them working. (including models and textures)

**Comment by GunnarKafel** [comment]
Can we get HL2 assets as well? Need it for my roleplay game

**Comment by Kud-Fountain** [comment]
> Can we get HL2 assets as well? Need it for my roleplay game

Not the same engine. You can use some import tools to convert them into Source 2. What I am talking about is not `CSGO`, is `CS2`

**Comment by PixelQubed** [comment]
> 

He is joking. This is a well-known fact by now. Garry doesn't want to pay royalties for the assets included with other Source 2 valve games since it would increase the per-sale royalty percentage from what is already apparently relatively high.
https://www.youtube.com/shorts/Or8TG0oFFpQ

**Comment by Kud-Fountain** [comment]
> > 
> 
> He is joking. This is a well-known fact by now. Garry doesn't want to pay royalties for the assets included with other Source 2 valve games since it would increase the per-sale royalty percentage from what is already apparently relatively high. https://www.youtube.com/shorts/Or8TG0oFFpQ

I don't see there's a problem, since garry's mod is not `using` other assets from Valve, except some of them from `HL2`. They just make it compatible with the other Source games instead of `using` it.

**Comment by PixelQubed** [comment]
> > > 
> > 
> > He is joking. This is a well-known fact by now. Garry doesn't want to pay royalties for the assets included with other Source 2 valve games since it would increase the per-sale royalty percentage from what is already apparently relatively high. https://www.youtube.com/shorts/Or8TG0oFFpQ
> 
> I don't see there's a problem, since garry's mod is not `using` other assets from Valve, except some of them from `HL2`. They just make it compatible with the other Source games instead of `using` it. In fact I am just asking support for the contents, not adding `CS2` assets into S&Box.

It's a problem because the asset system has been changed from the original source 2 engine they received which in tern makes both asset systems from both games incompatible with eachother. They would have to license the assets to have the ability to use the source files to recompile them for the sbox asset system. Not to mention shader systems have changed and will continue to change.

**Comment by Kud-Fountain** [comment]
> > > > 
> > > 
> > > 
> > > He is joking. This is a well-known fact by now. Garry doesn't want to pay royalties for the assets included with other Source 2 valve games since it would increase the per-sale royalty percentage from what is already apparently relatively high. https://www.youtube.com/shorts/Or8TG0oFFpQ
> > 
> > 
> > I don't see there's a problem, since garry's mod is not `using` other assets from Valve, except some of them from `HL2`. They just make it compatible with the other Source games instead of `using` it. In fact I am just asking support for the contents, not adding `CS2` assets into S&Box.
> 
> It's a problem because the asset system has been changed from the original source 2 engine they received which in tern makes both asset systems from both games incompatible with eachother. They would have to license the assets to have the ability to use the source files to recompile them for the sbox asset system. Not to mention shader systems have changed and will continue to change.

You got the point. But this is reason we're here. We'll see they will consider it or not. On my opinion I don't think that's a good idea if S&Box does not compatible with every Source 2 games. (At least release by `Valve`) My knowledge on how Valve works with Source Engine license its permanently and keep up to date for the developers who use their engines.

**Comment by PixelQubed** [comment]
> > > > > 
> > > > 
> > > > 
> > > > He is joking. This is a well-known fact by now. Garry doesn't want to pay royalties for the assets included with other Source 2 valve games since it would increase the per-sale royalty percentage from what is already apparently relatively high. https://www.youtube.com/shorts/Or8TG0oFFpQ
> > > 
> > > 
> > > I don't see there's a problem, since garry's mod is not `using` other assets from Valve, except some of them from `HL2`. They just make it compatible with the other Source games instead of `using` it. In fact I am just asking support for the contents, not adding `CS2` assets into S&Box.
> > 
> > It's a problem because the asset system has been changed from the original source 2 engine they received which in tern makes both asset systems from both games incompatible with eachother. They would have to license the assets to have the ability to use the source files to recompile them for the sbox asset system. Not to mention shader systems have changed and will continue to change.
> 
> You got the point. But this is reason we're here. We'll see they will consider it or not. On my opinion I don't think that's a good idea if S&Box does not compatible with every Source 2 games. (At least release by `Valve`) My knowledge on how Valve works with Source Engine license its permanently and keep up to date for the developers who use their engines.

I'm telling you they won't consider it. Also your source engine license knowledge is invalidated due to it being a different engine and licensed under new terms. Nobody other than Facepunch are aware of these terms since they are the only 3rd party that we know of at this moment in time that have a license for the Source 2 engine this invalidating any theory's that the licenses of Source 1 and Source 2 are the same.

**Comment by Kud-Fountain** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > He is joking. This is a well-known fact by now. Garry doesn't want to pay royalties for the assets included with other Source 2 valve games since it would increase the per-sale royalty percentage from what is already apparently relatively high. https://www.youtube.com/shorts/Or8TG0oFFpQ
> > > > 
> > > > 
> > > > I don't see there's a problem, since garry's mod is not `using` other assets from Valve, except some of them from `HL2`. They just make it compatible with the other Source games instead of `using` it. In fact I am just asking support for the contents, not adding `CS2` assets into S&Box.
> > > 
> > > 
> > > It's a problem because the asset system has been changed from the original source 2 engine they received which in tern makes both asset systems from both games incompatible with eachother. They would have to license the assets to have the ability to use the source files to recompile them for the sbox asset system. Not to mention shader systems have changed and will continue to change.
> > 
> > 
> > You got the point. But this is reason we're here. We'll see they will consider it or not. On my opinion I don't think that's a good idea if S&Box does not compatible with every Source 2 games. (At least release by `Valve`) My knowledge on how Valve works with Source Engine license its permanently and keep up to date for the developers who use their engines.
> 
> I'm telling you they won't consider it. Also your Source Engine license knowledge is invalidated due to it being a different engine and licensed under new terms. Nobody other than Facepunch are aware of these terms since they are the only 3rd party that we know of at this moment in time that have a license for the Source 2 Engine thus invalidating any theory's that the licenses of Source 1 and Source 2 are the same.

So we'll see about that. You have very interesting opinion but I don't think so tho. As you said is invalidated, who knows.

**Comment by handsomematt** [comment]
Not going to happen, they use different shaders and different file format versions.

The asset pipeline is so easy though, just decompile to fbx/png and import them like a normal asset. Lots of stuff on the wiki
