### ISSUE TITLE
Prefabs RootEntity scale resets back to 1 once you reopen

### ISSUE THREAD

**Issue by yuberee** [sboxgame/issues#3065]
### Describe the bug

After editing and saving a prefab's scale, it will reset back to 1 when you open it back up.
I've verified it's not just visual.

Before opening it again:
![image](https://user-images.githubusercontent.com/59583743/227805683-0eb3b7e2-846b-437d-8dee-ea16426513a5.png)
After opening it again:
![image](https://user-images.githubusercontent.com/59583743/227805698-5721dab1-e141-46c5-8a01-8c063fe135ea.png)

### To Reproduce

1. Create a new prefab
2. Add a rootentity
3. Scale the rootentity
4. Save and close the editor
5. Open the prefab and save it
Now the scale is set back to 1

### Expected behavior

The scale to persist correctly

### Media/Files

https://streamable.com/jwmau7

### Additional context

I've tested it with other normal prefabs RootEntity like ModelEntity and it happens with that too
This only happens with the scale, other properties like ColorOverride work fine

**Comment by DevulTj** [comment]
https://user-images.githubusercontent.com/22372616/227810166-6453f16c-7e96-4ff5-8da0-33537bb0f335.mp4


I added a missing control for Scale on root entities & stopped the scale being set back to 1 when opening the editor. Let me know if that works the way you wanted it😄

**Comment by yuberee** [comment]
Yup it's good
