### ISSUE TITLE
Hammer Volumetric Fog Preview is incorrect to in-game map compile

### ISSUE THREAD

**Issue by trende2001** [sboxgame/issues#3069]
### Describe the bug

When I want to preview how the fog is actually going to turn out, I have to compile the map.
At least that's what I have to do now after I discovered that the fog was completely wrong when I compiled my map.

**Another issue I found is you can't have more than 2 `env_volumetric_fog_volume`s and then after that the fog starts to not work on other fog volumes above this limit**

### To Reproduce

1. Put down any type of light
2. Put down an `env_volumetric_fog_controller` and a `env_volumetric_fog_volume` in the area of where you put down the lights
3. Tweak it to your liking, or don't choose to do that
4. Do a 512 or 1k light compile, 512 is faster
5. Fog will be overexaggerated, resulting in an ugly, foggy mess.

### Expected behavior

The fog should look like (in-game) how it does in Hammer 

### Media/Files

In Hammer:
![image](https://user-images.githubusercontent.com/68961063/228075363-f372c569-7cba-40a0-bf01-3595f0806cc4.png)

In game, fully compiled, 2K:
![image](https://user-images.githubusercontent.com/68961063/228075419-fdcac625-69a8-4bed-86de-702e7c749743.png)

**Comment by F0gboy** [comment]
I have the same issue :(

**Comment by trende2001** [comment]
bump

**Comment by Redhacker1** [comment]
Yeah, I don't know what you're expecting here... There's always going to be differences between the baked fog and the dynamic approximation that they're using

**Comment by trende2001** [comment]
> Yeah, I don't know what you're expecting here... There's always going to be differences between the baked fog and the dynamic approximation that they're using. If it were feasible and/or worth doing the baked fog dynamically they probably would already.

here's the thing. this started happening somewhat recently, and dynamic fog is super laggy so i'm not gonna be using it as a substitute. I was expecting it to work like it always did, but now that's not the case (for now)

**Comment by Redhacker1** [comment]
I'm pretty sure that's because they completely reworked the old baked fog pretty recently to improve it and allow it to interact better with lighting.

**Comment by Redhacker1** [comment]
Just so long as you know that it's possible that might not be a fixable issue and that previews and Hammer are not a replacement to baking your lighting to ensure correctness.

**Comment by trende2001** [comment]
> Just so long as you know that it's possible that might not be a fixable issue and that previews and Hammer are not a replacement to baking your lighting to ensure correctness.

The fog in game used to look exactly like it did in Hammer, but now it doesn't

**Comment by trende2001** [comment]
Related to #3001, one of Sam's latest commits fixed it. 👍  
I'll reopen this if I have any other issues
