### ISSUE TITLE
Ability to override base entities

### ISSUE THREAD

**Issue by Xenthio** [sboxgame/issues#3072]
### For?

S&Box

### What can't you do?

I was trying to change something in prop_physics (seperate issue for this too) and I asked on the discord for an idea.
![image](https://user-images.githubusercontent.com/28588188/228436625-4f8b97e6-f5ab-458e-b511-00077018469a.png)
The end idea didn't work but I thought that being able to do things like this would be very useful 

### How would you like it to work?

like the above screenshot would make sense but I don't mind how it works as long as it works and doesn't look like shit 

### What have you tried?

nothing, i can't think of any other ways to do something like this

**Comment by LeQuackers** [comment]
Beat you to it #2267
