### ISSUE TITLE
Weld stuff to the world

### ISSUE THREAD

**Issue by MNOGOZNAAL** [sboxgame/issues#3074]
### For?

S&Box

### What can't you do?

I want to weld my props to the ground(world)

### How would you like it to work?

I could weld my props to the world in Garry's mod. 

### What have you tried?

Add the ability to weld not only props, but also to the world. For static fixation of prop. The Garry's mod had a hammer that worked according to this logic.

**Comment by aylaylay** [comment]
Disabling physics would be a weld to world
