### ISSUE TITLE
[Hammer] Ambient Lighting on light_environment doesn't work (at least for dynamic lighting)

### ISSUE THREAD

**Issue by Fortune117** [sboxgame/issues#3078]
### Describe the bug

When trying to modify the ambient light in hammer, there is no visual feed back and it does nothing in game:
[Image was too big too upload](https://cdn.discordapp.com/attachments/837029412892442654/1090859934322790440/image.png)

I have been using fully dynamic lights in this instance.

However, you can set the ambient light from the C# side of things just fine using the following:
```CS
var brightness = 0.15f;
Sandbox.Game.SceneWorld.AmbientLightColor = new Color( brightness, brightness, brightness );
```
[And that looks like this in game](https://cdn.discordapp.com/attachments/837029412892442654/1090860009967075399/image.png)

### To Reproduce

1. Open a map in hammer
2. Add a light_environment
3. adjust ambient lighting settings:
![image](https://user-images.githubusercontent.com/7847372/228733470-7eeb658c-3dce-4d36-a9fd-a004164b8ba2.png)
4. build map, no visible effect in game

### Expected behavior

Ambient lighting should have an effect when set from hammer.

**Comment by aylaylay** [comment]
Have you tried setting sky intensity? Ambient color has been coded to be baked only.

**Comment by Fortune117** [comment]
> 

Sky Intensity seems to only work for baked lighting.

**Comment by aylaylay** [comment]
Okay I'll see what's up

**Comment by aylaylay** [comment]
Basically, ambient light is only applied when outside of light probes. If you just want the same effect as SceneWorld.AmbientLightColor then I can make that work

**Comment by Fortune117** [comment]
Some way to get that effect from inside hammer would be perfect.

**Comment by aylaylay** [comment]
Okay, ambient light will now be applied if the light is dynamic

**Comment by aylaylay** [comment]
I'll see if I can show it in hammer but let me know if it's working in game how you'd like it to

**Comment by Fortune117** [comment]
yep, works great
