### ISSUE TITLE
Add randomizer for material group on Asset Spray tool

### ISSUE THREAD

**Issue by Fortune117** [sboxgame/issues#3080]
### For?

Hammer

### What can't you do?

I am unable to randomize the material group on models selected to be sprayed with the asset spray tool:
![image](https://user-images.githubusercontent.com/7847372/229054748-3df18d59-728b-4918-b686-577e59992387.png)

### How would you like it to work?

Either a toggle that just picks randomly from all material groups, or a ranged float like the other options.

### What have you tried?

Creating a bunch of different models with the different materials.

**Comment by handsomematt** [comment]
Done 🤪🙃😋

**Comment by FullStack0verfl0w** [comment]
@handsomematt 
You forgot #2730
