### ISSUE TITLE
`.scss` files do not download when the hosted gamemode is present locally

### ISSUE THREAD

**Issue by timmybo5** [sboxgame/issues#3086]
### Describe the bug

Joining a dedicated server with a gamemode that is also present in the addons folder will make it so that `.scss` files are not downloaded. This is a recent issue and used to work fine last week.

__The temporary fix is to remove the gamemode from the addons folder before joining the server.__

![image](https://user-images.githubusercontent.com/4988198/229255195-061a9d76-25a5-443e-9a36-783eb97b70d0.png)

**Comment by garrynewman** [comment]
Hey - does this only happen when joining a dedicated server?

**Comment by garrynewman** [comment]
Also - is the gamemode on the dedicated server packaged, or is it a local addon?

**Comment by timmybo5** [comment]
I did some tests:
- local server with local files present: works
- local hosted server with uploaded gamemode: works
- local dedicated server with local files on same pc as client: works
- local dedicated server with local files on different pc than client: works
- remote dedicated server with uploaded gamemode: does NOT work

**Comment by garrynewman** [comment]
If my theory is correct then this same bug should trigger if all true

- client joining any other hosted game (dedicated or listen)
- server is running via package
- client has the package locally

**Comment by timmybo5** [comment]
The issue seems fixed, thanks a ton! playtests here we goo :D
