### ISSUE TITLE
Avatar command break menu

### ISSUE THREAD

**Issue by Akulla-A** [sboxgame/issues#3089]
### Describe the bug

Can't use the S&Box menu anymore without at least going in-game one time. 
However, I still can load a configuration and go in-game, if I go back again in the menu everything is working and my avatar is still there.

Console error: AvatarLoader - Couldn't get avatar for 0 (avatarsmall:0)

### To Reproduce

- Use the avatar command in client console, without any parameters. Like this: "avatar "
- Restart the game

### Expected behavior

- Be able to use the s&box menu
- Reset the avatar when the game starts if it is invalid

PS: Resaving avatar after editing doesn't fix the issue.
### Media/Files
Before in-game:
![image](https://user-images.githubusercontent.com/73881726/229301864-303eb588-d997-4eaa-83ea-5a41bd6fee91.png)
![image](https://user-images.githubusercontent.com/73881726/229302146-7e84ff8b-e61f-4ee4-8f30-b76a13beb7a5.png)

After:
![image](https://user-images.githubusercontent.com/73881726/229302243-4af35d3a-5bb3-4457-b4a7-6772a7c63efc.png)

**Comment by Gmod4phun** [comment]
The AvatarLoader error message has been there for a while. The menu not loading properly has started happening only very recently, it seems to happen randomly though.
