### ISSUE TITLE
Annoying gaps when changing `BackgroundPosition` property

### ISSUE THREAD

**Issue by nikita-strelok** [sboxgame/issues#3090]
### Describe the bug

When I changing Panel's style BackgroundPosition property(X or Y) there gaps are formed between textures

### To Reproduce

You can see this issue in UITests->Backdrop filter. Or use this test code
```
using Sandbox;
using Sandbox.UI;
using System;

public partial class MyGame : GameManager
{
	Panel bg;
	public MyGame()
	{
		if ( Game.IsServer ) return;

		Game.RootPanel = new();

		bg = Game.RootPanel.AddChild<Panel>();
		bg.Style.SetBackgroundImage( "ui/tests/background.png" );
		bg.Style.Width = Length.Percent( 100 );
		bg.Style.Height = Length.Percent( 100 );
		bg.Style.Position = PositionMode.Absolute;
	}

	public override void Simulate( IClient cl )
	{
		if ( bg != null )
		{
			bg.Style.BackgroundPositionX = RealTime.Now * -10.0f;
			bg.Style.BackgroundPositionY = MathF.Cos( RealTime.Now * 2.0f ) * 50.0f;
		}
	}
}
```

### Expected behavior

There should be no gaps, the image should be "solid".

### Media/Files

There gaps are very small but in some cases they can be up to 5px width.
![pr1](https://user-images.githubusercontent.com/88283901/229307845-c95537eb-1435-4f06-8c24-ebf8783b97e9.png)
No gaps
![tobe](https://user-images.githubusercontent.com/88283901/229307847-24e4d0e2-70c3-4b39-9804-c89a2eb2e9e8.PNG)

**Comment by xezno** [comment]
I fixed this a while ago, but feel free to re-open if this is still an issue for you
