### ISSUE TITLE
-dev.exe - Widgets are gone if I don't change the resolution

### ISSUE THREAD

**Issue by KaesarZZ** [sboxgame/issues#3095]
### Describe the bug

Every time I open the game, the widgets are gone if I don't change the resolution of the main window.

### To Reproduce

Explained in the video.

### Expected behavior

Should work as per usual.

### Media/Files

https://user-images.githubusercontent.com/40291120/229768071-611e7249-9f4f-4826-80dd-32245fdfc15c.mp4

**Comment by garrynewman** [comment]
Should be fixed now
