### ISSUE TITLE
Default .gitignore on project creation

### ISSUE THREAD

**Issue by Weldify** [sboxgame/issues#3096]
### For?

S&Box

### What can't you do?

When creating a project, a .gitignore file should be created containing common stuff you wouldn't want in your repository such as compiled assets, etc.

### How would you like it to work?

A yes/no option to make a .gitignore file during project creation.

### What have you tried?

I usually use https://github.com/Eagle-One-Development/sbox-equivalent/blob/main/.gitignore, but it would be nicer to have a curated .gitignore

**Comment by robotboy655** [comment]
Added this option:
![image](https://user-images.githubusercontent.com/3299036/235951864-4e59fd3b-3e4c-430a-80d5-7ae43b59d9b1.png)

Which will create this .gitignore
```

# This file describes files and paths that should not be tracked by Git version control
# https://git-scm.com/docs/gitignore

# Auto-generated code editor files
.vs/*
.vscode/*
*.csproj
obj/*
Properties/*
code/obj/*
code/Properties/*

# Auto-generated asset related files
*.generated.*
*.*_c
*.los
```

I kept it small on purpose, if you think there should be more additions to it, do not hesitate to let us know.

**Comment by eagleonedevteam** [comment]
.VPK files would be a great addition to this list

As a dedicated mapper, I would hate to constantly spam partially compiled versions of the map during its production. The VMAP will be all that's needed, and the final build of VPK files usually above the size limit

**Comment by robotboy655** [comment]
Added, makes sense to go with other compiled assets
