### ISSUE TITLE
Updating skybox tint color in game only works once

### ISSUE THREAD

**Issue by Remscar** [sboxgame/issues#3100]
### Describe the bug

If you change the `.TintColor` on a maps skybox it will send to clients only once. Future updates to the tint color have no effect even though the editor inspector shows the tint color has changed.

### To Reproduce

- Make an entity that targets the `Sky` skybox of the map
- Adjust the color on Server Tick

### Expected behavior

The color always changes

**Comment by aylaylay** [comment]
You should now be able to change tint color and skyname whenever you want

**Comment by Remscar** [comment]
> You should now be able to change tint color and skyname whenever you want

Works like a charm, thank you!
