### ISSUE TITLE
BindComponent setter

### ISSUE THREAD

**Issue by Weldify** [sboxgame/issues#3102]
### For?

S&Box

### What can't you do?

Creating bound components is tedious

### How would you like it to work?

Before
```cs
[BindComponent] MyComponent Component {get;}

Components.Create<MyComponent>()
```
After
```cs
[BindComponent] MyComponent Component {get; set;}

Component = new MyComponent()
```

Internally the setter should basically do the same thing.

### What have you tried?

`Components.Create<MyComponent>()`

**Comment by Adesii** [comment]
wait, I'm confused.
They both do the same thing and are the same length pretty much.

also wouldn't this more be better classified as a Api Design issue rather than feature request?

**Comment by Weldify** [comment]
Yes, they do the exact same thing. Even though they are almost the same length, the new addition conveys to the programmer that this is component is used by a property with BindComponent.

This maybe more of an API design issue, yeah, I just thought I'd put it here since it doesn't change any functionality - just adds it.

**Comment by DevulTj** [comment]
I don't see the point in this. BindComponent runs codegen that replaces the getter of the property with `Components.Get<Type>( false );`
