### ISSUE TITLE
Cylinder/Capsule shape for player collision

### ISSUE THREAD

**Issue by matekdev** [sboxgame/issues#3103]
### For?

S&Box

### What can't you do?

I would like to use a cylinder or capsule shape instead of a rectangle for the player collision. The shapes provide a lot of advantages when the player is forced to collide against world/objects that are rotated. Alongside providing a more accurate shape of the player's size.

For instance, in my particular use case, I had a wall climbing system that would end up with the rectangle intersecting with the world when the world was at a 45-degree angle.

### How would you like it to work?

We already have some of the methods...

`SetupPhysicsFromCapsule`
`SetupPhysicsFromCylinder`

We would need some additional methods added to the trace class that would allow for passing in the size of said cylinder. 

### What have you tried?

I imagine that I could write my own implementation, but, it'd be nice to have the option in the engine by default since other engines such as Unity use a capsule by default.

### Additional context

Here is Garry talking about considering a cylinder implementation for the player controller.
https://discord.com/channels/833983068468936704/833983416390385685/1090943669487554570

There are some methods already for a capsule, but there seems to be a bug related to them https://github.com/sboxgame/issues/issues/2877

**Comment by garrynewman** [comment]
Any idea what they're using in cs2? Is it still an aabb?

**Comment by QuackCocaine** [comment]
Mmm aabb still ![cs2_OMahopGdop](https://user-images.githubusercontent.com/23345567/230601768-cd21d224-ec4a-4614-8834-03032ea95c60.png)

**Comment by matekdev** [comment]
https://discord.com/channels/833983068468936704/835035328779518023/1151726376597065768
cylinder trace was included here, also we have capsules now since the other issue was fixed.
