### ISSUE TITLE
Joining a local version of a game sometimes downloads random assets

### ISSUE THREAD

**Issue by peter-r-g** [sboxgame/issues#3107]
### Describe the bug

Sometimes when you join a local version of someone's game it will start to download random asset files on the host's computer.

### To Reproduce

1. One player host a local version of their game. They should also have other projects added to S&box. Does not matter if the projects are enabled or disabled.
2. Second player joins the hosted game.
3. Profit

### Expected behavior

Only the files that are used in the game are to be sent to the joining clients.

### Media/Files

This happened between @Matt9440 and @JammieDodgerr while we were testing [Parkour Painters](https://github.com/apetavern/parkour-painters) locally. In this case Jammie was the host and only had the Parkour Painters project enabled. All others were disabled, Matt ended up seeing this while downloading:
![image](https://user-images.githubusercontent.com/11802285/230650673-589a221b-51ae-4c39-a53c-064db76baad4.png)

**Comment by garrynewman** [comment]
Should be fixed next build
