### ISSUE TITLE
Change EntityComponent generic constraint to IEntity interface

### ISSUE THREAD

**Issue by peter-r-g** [sboxgame/issues#3109]
### What it is?

Currently, the `EntityComponent` generic constraint limits you to a class type of `Entity`.

### What should it be?

It should instead be limited to a type that implements the `IEntity` interface. This way you can use classes that implement `IEntity` and you can use interfaces that derive from `IEntity`. This would be useful in cases where you have entities with different bases but implement similar functionality.

**Comment by LeQuackers** [comment]
I think this is already planned in the next pain day #2858

**Comment by DevulTj** [comment]
Duplicate of https://github.com/sboxgame/issues/issues/2858
