### ISSUE TITLE
Bots that mimic should not use ClientInput entity properties

### ISSUE THREAD

**Issue by peter-r-g** [sboxgame/issues#3110]
### What it is?

Right now, a bots default behavior is to copy all client input of the player. This works fine until you start making use of entities marked with the `ClientInputAttribute`. What this will do is give the bot an entity that is owned and used by the player to work with. Which now starts to break the functionality of the game and forces you to put in a special case code to deal with bot mimicking.

### What should it be?

S&box should either warn you when a situation like this is occurring or the bot should look for an entity that fits best with the players version.

**Comment by kurozael** [comment]
I think in this case we'll have to warn and just ignore that `ClientInput` property for the bot.

**Comment by kurozael** [comment]
I'm wondering if perhaps adding a BotIgnoreAttribute could be worth doing here. So you can explicitely ask mimic bots to ignore an input?

**Comment by peter-r-g** [comment]
> I'm wondering if perhaps adding a BotIgnoreAttribute could be worth doing here. So you can explicitely ask mimic bots to ignore an input? Or even having that as an optional property on `ClientInputAttribute` itself, for example:
> 
> ```cs
> [ClientInput( BotIgnore = true )]
> ```

Yeah the optional parameter would work great for this
