### ISSUE TITLE
Editor crash on startup

### ISSUE THREAD

**Issue by WYVERN2742** [sboxgame/issues#3115]
### Describe the bug

Upon launching s&box tools, the process will crash after scanning for assets.
Initial runs after a restart will result in a "Hang" dialog for ~10 seconds, before closing. All starts until next reboot will not show a hang dialog.

Issue persists after a clean install of s&box (including deletion of all previous addon files), however starting s&box in game mode works great with no issues. s&box has previously worked on my laptop, but has not been used on this device for more than 5 months.

(As expected:)
- Crash still exists when launching sbox_dev.exe directly
- Crash still exists when launching sbox.exe -tools

### To Reproduce

1. Start in tools mode from steam
2. Splash screen will display scanning for assets
3. Splash screen will close, and the process will end

### Expected behavior

1. Tools open normally

### Media/Files

(IIRC there is now a sentry service to upload crash dumps, if this isn't the case, ask and I'll upload mine here)

### Additional context

Build ID: 10959792
Windows Ver: 10.0.1905 Build 19045
CPU: Intel 11th Gen
GPU: Intel UHD Graphic 30.0.101.1338
GPU: NVIDIA RTX 3060 Laptop 31.0.15.2225

**Comment by DevulTj** [comment]
Can you provide your latest Log file from the logs folder?

**Comment by NotGaylien** [comment]
Have you tried deleting the contents of your config folder.
thats a common reason for the game crashing all the time on startup.
could be any of the config files, ive had client cookies, tool cookies, video cookies, menu cookies all cause it to happen

**Comment by WYVERN2742** [comment]
Tested after updating to the newest version, and the crash has stopped. Unsure what could've changed, but here's my old log from when the issue 
was occuring; [Log.7.log](https://github.com/sboxgame/issues/files/11209019/Log.7.log) I have a few logs which are exactly the same.

The config folder was deleted with the sbox re-install, but I'll keep it in mind if it happens again.

The log from my (new) working tools is as follows; [Log.log](https://github.com/sboxgame/issues/files/11209053/Log.log)
It does contain multiple D3D errors and texture creation failures, is this something i should open an issue about?
