### ISSUE TITLE
Whitelist System.Diagnostics.UnreachableException

### ISSUE THREAD

**Issue by peter-r-g** [sboxgame/issues#3116]
### What it is?

Right now the [System.Diagnostics.UnreachableException](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.unreachableexception?view=net-7.0) that was introduced in .NET 7.0 is not whitelisted.

### What should it be?

It should be whitelisted, it's just a type of exception that is used to define a code path that should not be reachable.

**Comment by peter-r-g** [comment]
None of the constructors for the exception was whitelisted. I can't seem to re-open this issue either.

**Comment by handsomematt** [comment]
Should be fine in next build now @peter-r-g
