### ISSUE TITLE
Whitelist returning readonly ref structs (like Span<T>)

### ISSUE THREAD

**Issue by peter-r-g** [sboxgame/issues#3117]
### What it is?

If you try to return a `readonly ref struct` you will get a whitelist error like the following:
`Whitelist Error: Namespace.Class.Method(..) - [ReturnPtrToStack] Return type is ByRef, TypedReference, ArgHandle, or ArgIterator.`

### What should it be?

For this type of functionality to be whitelisted. With the `stackalloc` keyword and unsafe code blocks not being whitelisted I don't see a security issue regarding this.

**Comment by handsomematt** [comment]
Should work fine now
