### ISSUE TITLE
Strange warping happening on textures and models after recent updates

### ISSUE THREAD

**Issue by sugmagaming** [sboxgame/issues#3120]
### Describe the bug

A texture on the floor of my map has a weird warping issue. Also the cliff_a.vmdl has a weird warping issue that i believe is the same thing. This has started happening only recently. The file size is too big for a video so I linked an unlisted video of the 2 issues on youtube.

### To Reproduce

.

### Expected behavior

.

### Media/Files

[https://youtu.be/sozWUZB0Bt8](https://youtu.be/sozWUZB0Bt8)

**Comment by handsomematt** [comment]
What shader are these materials using?

**Comment by Gmod4phun** [comment]
Looks like Parallax enabled without a parallax map applied
