### ISSUE TITLE
Allow tools to compile with unsafe code

### ISSUE THREAD

**Issue by trundlr** [sboxgame/issues#3124]
### For?

S&Box

### What can't you do?

Currently, tools cannot use unsafe code. You can get around this a few ways, but they are rather inconvenient. 

The error exists as follows: `Generic [Error](arg:0) | Unsafe code may only appear if compiling with /unsafe`

### How would you like it to work?

Unsafe code should be allowed to be compiled!

### What have you tried?

I have tried using unsafe code, but it would not let me.

**Comment by lotuspar** [comment]
Definitely no reason not to have this - you can already edit memory with Marshal, unsafe code would just be a little more convenient

**Comment by xezno** [comment]
This should be fixed now - let me know if not

**Comment by trundlr** [comment]
Works great, thanks!
