### ISSUE TITLE
Entities take a few seconds to replicate to client after spawning serverside

### ISSUE THREAD

**Issue by chrisspieler** [sboxgame/issues#3125]
### Describe the bug

In my personal, experimental fork of the Sandbox game mode, I made a couple different entities that when spawned each inexplicably take a few seconds to replicate to the client.

### To Reproduce

1. In the S&box editor, launch the game duccsoft.super_ducc_test on the default map
2. Run the console command "empty_add"
3. Check the entities list for an "EmptyTest" entity to appear in Uncategorized. 
4. The EmptyTest entity will start blue (server only), then turn green (replicated) after a number of seconds.

https://user-images.githubusercontent.com/8889285/231029129-64b7125b-784f-485f-b861-5cac0212eb29.mp4

Note: Outside of the editor, a very similar behavior can be seen if you start duccsoft.super_ducc_test and run the command "projector_add". The spotlight in the map will immediately go out as it is deleted on the server, and the new spotlight that spawns serverside to replace it does not appear for a few seconds.

https://user-images.githubusercontent.com/8889285/231029412-ec4f478d-6841-4eff-9585-a454ed6a7397.mp4

### Expected behavior

The aforementioned entities should have spawned more or less instantly.

**Comment by the-remeko** [comment]
Have you tried adding `Transmit = TransmitType.Pvs;` or `Transmit = TransmitType.Always;` in `Spawn` for the TheaterProjector?

The description of the default transmit type is "Engine will decide when to transmit the entity." https://asset.party/api/Sandbox.TransmitType

**Comment by chrisspieler** [comment]
> Have you tried adding `Transmit = TransmitType.Pvs;` or `Transmit = TransmitType.Always;` in `Spawn` for the TheaterProjector?
> 
> The description of the default transmit type is "Engine will decide when to transmit the entity." https://asset.party/api/Sandbox.TransmitType

Thanks, that seems to help. `TransmitType.Pvs` causes the extreme delay in entities getting transmitted, but `TransmitType.Always` shows only a negligible delay. Closing this issue.
