### ISSUE TITLE
Summary for Panel requiring a RootPanel

### ISSUE THREAD

**Issue by EmanSza** [sboxgame/issues#3127]
### What it is?

In the Reference API Root Panel or Panel don't have a summary explaining that in order to have a Panel you need to have a Root Panel

### What should it be?

the [Panel Referance](https://asset.party/api/Sandbox.UI.Panel) should just mention that you need to have a RootPanel, will assist younger developers who lack problem solving skills. Its not a major issue or one that needs to be changed. but might be good to add.

**Comment by robotboy655** [comment]
This should suffice:
![image](https://user-images.githubusercontent.com/3299036/231513278-046f23df-bfab-4a4d-a218-758948f0d82c.png)
