### ISSUE TITLE
Graphics API no longer works on Addons

### ISSUE THREAD

**Issue by trende2001** [sboxgame/issues#3132]
### Describe the bug

When I try to use render hooks or pretty much anything within the bounds of the Graphics API in an addon, it doesn't work in game

Although when I paste my code over into a gamemode, it all works nice and well.

### To Reproduce

[pixel_shader_overlay.zip](https://github.com/sboxgame/issues/files/11213522/pixel_shader_overlay.zip)
Here's the repro, incase this helps diagnose the problem

### Expected behavior

Render hooks should work as intended in an addon environment. It should apply the pixelated shader effect which is what I am going for.

## Addon
![image](https://user-images.githubusercontent.com/68961063/231508985-7d2392ce-ca17-4a71-84bf-982f0f27dd33.png)
## Gamemode (addon disabled, all of the renderhook addon code inside gamemode)
![image](https://user-images.githubusercontent.com/68961063/231510218-85557c87-b8e0-45ae-acbf-90393242fea4.png)

### Additional context

I remember a lens flare addon that used render hooks and it was functioning just fine before a certain update

**Comment by garrynewman** [comment]
Is this render hooks or any clientside hooks?

**Comment by garrynewman** [comment]
Looking at your repro code, I don't think this should _really_ work anyway. You see, you're adding the renderhook in Spawn - which is only called on the server.

**Comment by trende2001** [comment]
I think I'm doing something wrong then. But this is the only workaround if I want people to control how strong the pixel shader is with a hammer entity. I hope there's a better way

**Comment by DoctorGurke** [comment]
Have you considered the client spawn override instead?

**Comment by trende2001** [comment]
I'll try that

**Comment by trende2001** [comment]
It's working now. Thank you
