### ISSUE TITLE
[Shader Graph] Add 'Save As' option 

### ISSUE THREAD

**Issue by QuackCocaine** [sboxgame/issues#3134]
### For?

Other

### What can't you do?

Occasionally I want to save the shader graph that I'm working on under a different name but currently, that isn't an option you can choose in the file menu.

### How would you like it to work?

File -- > Save As 

### What have you tried?

Copying the shader and renaming it manually in file explorer 
or 
opening a new shader graph and copying everything over then naming that one.

**Comment by aylaylay** [comment]
Done :)

**Comment by QuackCocaine** [comment]
Thanks a bunch Laylad!
