### ISSUE TITLE
Cryptic ClientRpc error message could be improved

### ISSUE THREAD

**Issue by anthonysharpy** [sboxgame/issues#3138]
### What it is?

(this is all on a class that inherits BaseNetworkable)

if you call a client RPC function like this...

```
[ClientRpc]
public void ClientOnWeaponChanged()
{
    RoleplayGameBase.HUD.OnChangeWeapon();  // this bit is probably irrelevant but keeping it in
}

...
ClientOnWeaponChanged(To.Single(Owner)); // called on server
...

```

you will get a cryptic error message:

![image](https://user-images.githubusercontent.com/55365296/232163439-f2ba6d76-1996-4d99-b294-d0317d502829.png)

![image](https://user-images.githubusercontent.com/55365296/232163453-087c0504-bff6-458f-aa92-69cb75ab94b7.png)

if you change the function (ClientOnWeaponChanged) to a static function, it works and no error message is thrown.

### What should it be?

assuming this is intended behaviour the error message could say something like "Failed to call ClientRpc "[FunctionNameHere]": function should be marked as static"

even better if it doesn't compile

**Comment by kurozael** [comment]
[ClientRpc] are not yet supported on types derived directly from `BaseNetworkable`. They're only supported on types derived from `Entity`, `EntityComponent` or on static methods.

I've added a compile error now to warn you of this if you try to put a `ClientRpc` attribute on an invalid method.

**Comment by anthonysharpy** [comment]
TIL... thank you 😄
