### ISSUE TITLE
Change OnChanged Methods no longer fire

### ISSUE THREAD

**Issue by Sp00n3xJR** [sboxgame/issues#3139]
### Describe the bug

When using Change on Networked properties, OnPropertyNameChanged methods should be called, but no longer are. Defining the method directly with nameof(method) doesn't work either, so I suspect Change just completely broke. This worked fine a couple days ago.

### To Reproduce

Create a new networked property, give it change.
Create OnPropertyNameChanged method.
Add some code to it.

### Expected behavior

OnPropertyNameChanged methods should be called, but aren't.

### Media/Files

https://gyazo.com/d762f4c6e48db488e7c7d88d4d491f26
https://gyazo.com/6836b5a02d61eb292c083b2fb8f7ab98

**Comment by kurozael** [comment]
Update: this could potentially be an issue with incremental codegen stuff. @Metapyziks is going to take a look, and if it's not, he can pass it back to me 👍

**Comment by Metapyziks** [comment]
Fixed in Facepunch/sbox@d1506526b411bcf9e392b2058fcb09adb425004d
