### ISSUE TITLE
Inherited [Event] methods are ignored by the event system

### ISSUE THREAD

**Issue by TheBerkin** [sboxgame/issues#314]
**Describe the bug**
If you create an instance of an entity class that inherits from another entity class containing `[Event]` methods, the inherited handler methods are seemingly ignored by the event system. Only event methods annotated in the instance type work. This also extends to certain built-ins like `[Event.Frame]`, but it looks like `[Event.Tick]` still somehow works as expected.

**To Reproduce**

Create a base entity class with something like this:
```cs
public abstract class BaseNpc : ModelEntity
{
    [Event.Tick]
    protected virtual void OnTick()
    {
        // works as expected
    }

    [Event.Frame]
    protected virtual void OnFrame()
    {
        // never called on client
    }

    [Event("npc.set_combat")]
    private void OnSetCombatState()
    {
        // does not work
        Log.Info("npc.set_combat called in BaseNpc");
    }
}
```

Inherit `BaseNpc` in another entity class:

```cs
public class Ghost : BaseNpc
{
    protected override void OnTick()
    {
        // works as expected
    }

    protected override void OnFrame()
    {
        // never called on client
    }

    [Event.Frame]
    private void OnGhostFrame()
    {
        // works as expected
    }

    [Event("npc.set_combat")]
    private void OnGhostSetCombatState()
    {
        Log.Info("npc.set_combat called in Ghost");
        // works as expected
    }
}
```
When an instance of `Ghost` is created, the events in `BaseNpc` are ignored. Calling `Event.Run("npc.set_combat")` will only show log output for the handler in `Ghost`:
```cs
Event.Run("npc.set_combat");
// log: "npc.set_combat called in Ghost"
```

**Expected behavior**

All event methods in the entire type chain for an entity class should be registered and called as expected when the associated events are dispatched.

**Additional context**

N/A

**Comment by garrynewman** [comment]
I suspect this problem is really down to Event's being on private members than anything else. I can probably fix that.

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by TheBerkin** [comment]
Seems to work as expected now, thanks!

**Comment by TheBerkin** [comment]
This problem appears to have resurfaced. I'm noticing that any events that aren't marked on the concrete entity type are ignored.

**Comment by TheBerkin** [comment]
After looking some more, this issue seems to only happen to private `[Event]` methods in parent classes. No other visibility levels seem to have the problem. Private `[Event]` methods in the concrete type are always picked up.

**Comment by handsomematt** [comment]
give that a whirl x

**Comment by handsomematt** [comment]
Ah I see why, bit of a pain to do but I think I know how to do it in a non sucky way.
