### ISSUE TITLE
[Asset Browser] Add "New Shader Graph" to context menu

### ISSUE THREAD

**Issue by QuackCocaine** [sboxgame/issues#3149]
### For?

S&Box, Other

### What can't you do?

At the moment there isn't an out-of-the-box way to create a _shader graph_ via the asset browsers _context menu_.

### How would you like it to work?

Within Asset Browser Window: _Right Click --> New Shader Graph_

### What have you tried?

While Opening the shader graph and then saving it in the desired location is alright I much prefer it to be something you can create just like the other asset types in the _context menu_ directly where you want it first.

**Comment by xezno** [comment]
This should be added now - let me know if there's any problems
![image](https://user-images.githubusercontent.com/12881812/232744684-b2b1088c-8dce-4328-a7fc-3a806f733b46.png)

**Comment by QuackCocaine** [comment]
Works as expected. Appreciate it Alex!
