### ISSUE TITLE
Library Type Packages can't have Assets

### ISSUE THREAD

**Issue by Adesii** [sboxgame/issues#3153]
### For?

S&Box

### What can't you do?

Libraries can't have any kind of assets.
This means it can't have any custom Shaders which my SpriteKit Library needs.

### How would you like it to work?

Allow uploading and Editing Assets in Libraries.

As a compromise limiting the types of assets could also be a possibility. tho i personally don't see the point in limiting it.

### What have you tried?

Enabling Assets through the .addon
It kinda works as the game seems to find the Shaders but they don't show up in the Asset browser so i can't recompile them.

**Comment by kurozael** [comment]
Should be good now!
