### ISSUE TITLE
[Shader Graph] Ability to create a comment node from a selection of nodes

### ISSUE THREAD

**Issue by QuackCocaine** [sboxgame/issues#3154]
### For?

Other

### What can't you do?

At the moment there is no way to quickly create a comment from a selection of nodes. You would first have to create a comment and then resize the comment node to what you would want inside it.

### How would you like it to work?

Pretty much select which nodes you'd like to be framed within a comment node and either **_Right-click_** to open up the context menu and select **_Create Comment From Selection_** or just press the hotkey **_C_**  to place your selection within a new comment node.

![sbox-dev_OAp1KlfUsN copy](https://user-images.githubusercontent.com/23345567/232943813-939686f2-daa0-4344-9d67-1da873085ead.png)

### What have you tried?

While creating a comment node and then resizing it to what you want it to contain is alright for most I'd much prefer to be able to add nodes into a comment via a selection. Which is a quicker way to go about doing it.

**Comment by aylaylay** [comment]
Done

**Comment by QuackCocaine** [comment]
Thanks! But could you make it so you can keep the selection when you right-click while not over a node?

https://user-images.githubusercontent.com/23345567/232953194-692f39be-ad4d-4034-a1f2-31f18bac95e0.mp4

**Comment by aylaylay** [comment]
Done

**Comment by QuackCocaine** [comment]
Very Nice 👍 Have a good day
