### ISSUE TITLE
[Shader Graph] A way to Debug View output values from a node

### ISSUE THREAD

**Issue by QuackCocaine** [sboxgame/issues#3157]
### For?

Other

### What can't you do?

Currently, out of the box, you are unable to view and quickly examine the current output value of any given node. Say for example the result value of a _**Dot Product**_.

### How would you like it to work?

There are two ways you could go about doing this or perhaps both, they are as followed :

### Passthrough 
Much like the reroute node it would have no effect on the resulting shader. It would just act as a way to display any provided output value from another node within the  **_Debug Value Node_** Itself whether its a Float, Vector, etc...

### Dead End Debug Value
Or instead of it being a node that you can pass through values maybe just have an input and no output? Pretty much drag another output from a node and input it into the input of a _**Debug Value Node**_ which will just let you view the value of the current input and thats it.

### Blender Examples 
**_Float_**
![blender_MYi1BziG2q](https://user-images.githubusercontent.com/23345567/233139021-9317dfe4-aa75-47ba-9316-47ee53aeea54.png)
**_Vector_**
![blender_w4nVFfFNCj](https://user-images.githubusercontent.com/23345567/233139294-bc261d28-8d2f-4216-a52b-9a49aab9630c.png)
**_Color_**
![blender_AqObuy8mv9](https://user-images.githubusercontent.com/23345567/233141024-aa77d314-fe17-4baf-83d5-be332b1045b5.png)

### What have you tried?

Nothing aside from calculating the expected value externally. which isn't bad but I don't see any harm in being able todo it in the graph itself via a node.

### Additional context

Being able to debug what values you get from the output of a node immediately, would be a very useful feature to have available when creating Shaders.

**Comment by aylaylay** [comment]
I don't know in what context this works in blender but it's not really possible to always calculate an output value because it's a per pixel shader. The value could be completely different depending on the pixel that's being shaded. You would have to limit it to very specific situations which is why I didn't bother displaying a value output.

**Comment by QuackCocaine** [comment]
Ah that makes sense. sucks that it isn't feasible.
