### ISSUE TITLE
AE_CL/SV_SET_BODYGROUP not working outside of ModelDoc

### ISSUE THREAD

**Issue by Fortune117** [sboxgame/issues#3158]
### Describe the bug

I've set up a bread animation so that the bread disables body group as it gets eaten:

https://user-images.githubusercontent.com/7847372/233383993-395342c4-111d-4371-985f-4b52847980f4.mp4

However, the effect isn't seen in the animgraph or in game:

https://user-images.githubusercontent.com/7847372/233384300-d7f97ffa-82ae-4ff0-9b30-834df989857e.mp4

### To Reproduce

1. I've uploaded the model I was using, should have everything needed for the effect.
2. Open the model, check the animgraph.

### Expected behavior

Effect is visible outside of model doc.

### Media/Files

[bread_vm.zip](https://github.com/sboxgame/issues/files/11286821/bread_vm.zip)

**Comment by aylaylay** [comment]
I'm pretty sure animgraph doesn't support any playback of anim events. Can you confirm this doesn't work in game because there's nothing I can see that should be stopping it.

**Comment by Fortune117** [comment]
Just double checked and it is actually visible in game. All good then

**Comment by aylaylay** [comment]
Yeah it kinda sucks that anim events don't preview in animgraph but this isn't something I'd like to spend time supporting in a native tool.
