### ISSUE TITLE
Allow Input Actions to be rebindable via s&box's settings

### ISSUE THREAD

**Issue by KayaDLX** [sboxgame/issues#3159]
### Describe the bug

Say I've bound my movement to WASD and a key to Z on my project settings, and in-game I use ZQSD as my movement input:
It will not try to move those keys to an AZERTY-friendly layout and will give me two inputs at once, Z will be Z and won't be moved to W which would be its counterpart from QWERTY to AZERTY.

### To Reproduce

1. Bind movement to WASD in project settings and whatever action to Z
2. Bind movement to ZQSD in-game
3. Move foward
4. Notice how it inputs two actions at once

### Expected behavior

It should move those input keys based on the regional keyboard layout of the user.

### Media/Files

https://user-images.githubusercontent.com/67245359/233450200-d23699ca-011b-4443-b158-a20a18219735.mp4

![sbox-dev_5HTP7OkhPw](https://user-images.githubusercontent.com/67245359/233450223-e8414209-78b9-417a-8d6a-7a00a84292f2.png)
![sbox-dev_S6qoDPoyAm](https://user-images.githubusercontent.com/67245359/233450238-159f394b-7bbf-4f63-8894-a19a50c5849b.png)

**Comment by matekdev** [comment]
This is semi-unrelated, but what is the reason for needing to add `Forward`, `Backward`, `Left`, etc. if they are hard-coded names and cannot be rebound?

**Comment by garrynewman** [comment]
I'm not totally sure what this has got to do with non querty keyboards?

If I'm reading right the bug is that a button can be bound to two things?

**Comment by KayaDLX** [comment]
Not really no, basically I'm expecting any keys to be converted from the inputs to my regional layout.

The issue is that, while it is overwriting the movement bindings due to my user settings (making it override the WASD keys in my inputs to ZQSD in my user settings), this works fine. However, any other keys that the user cannot rebind through user settings will still be expected to be bound to those original keys meant for a QWERTY layout as that is the default for most devs. I'm expecting inputs to be converted to the user's regional layout.

Unless additional inputs (other than the ones I can find in s&box's settings) are meant to be reboundable in user settings later, which then would make sense.

Hope this makes sense.

**Comment by KayaDLX** [comment]
I think being able to rebind said inputs from gamemodes would make the most sense in this case 👍

**Comment by KayaDLX** [comment]
Ye ye
