### ISSUE TITLE
snd_soundscape_box will play outside of box

### ISSUE THREAD

**Issue by KingOfTheFBI** [sboxgame/issues#3160]
### Describe the bug

When you leave a snd_soundscape_box it will keep playing if you don't walk into a different box. It should just stop the sound or at least have a checkbox to do so instead of keep playing until you walk into a different soundscape. 

If this is intended a use case would be going indoors from rain sound outside.

### To Reproduce

1. Make a snd_soundscape_box and add any soundscape
2. Compile the map
3. Walk into the box until you hear the sound
4. Walk out of the box
5. Sound will continue to play despite being out of the box

### Expected behavior

Sound should stop playing since you are no longer in the bounds of a soundscape box

**Comment by bakscratch** [comment]
They work like triggers so you enter them to start the soundscape, then fade into another when entering a new soundscape box.

**Comment by KingOfTheFBI** [comment]
> They work like triggers so you enter them to start the soundscape, then fade into another when entering a new soundscape box.

Could there be an option to have it fade out when not walking into another soundscape?

**Comment by KingOfTheFBI** [comment]
closing entity dead
