### ISSUE TITLE
Allow us to trigger voice chat ourselves

### ISSUE THREAD

**Issue by matekdev** [sboxgame/issues#3161]
### What it is?

Right now, voice chat is triggered automatically somewhere in engine depending on which key you assign "voice". What if, your game had two forms of communication, one button that would voice chat to everyone, and another button that chats to your team. This is currently impossible with the current setup.

### What should it be?

Voice chat is the only button that is not called within our games code, I think it probably should be. Give us the ability to trigger voice chat using an input button somewhere in the game loop. I would remove `CanHearPlayerVoice` and instead allow us to pass in the clients that should receive the incoming voice chat. For instance...

```csharp
if (Input.Pressed("team_voice")
{
    SendVoice(To.Single(...)); // Similar to how clientrpcs work
}
```

I'm open to hear your thoughts and feedback.

**Comment by trende2001** [comment]
i agree

**Comment by sanny-io** [comment]
There should be no such thing. This is rife for abuse like how it was in gmod. Imagine having a private conversation only to find out it's been secretly being broadcasted to the whole server or recorded.

**Comment by matekdev** [comment]
Yeah that makes sense, I'd suggest either some obvious indicator in-game to let the player know their microphone is being used.

Otherwise yeah, the privacy issue is a big problem here. I know the windows taskbar indicators when a microphone is being used. But, I don't believe that is enough indication imo.

**Comment by DevulTj** [comment]
for now, let's not - maybe we'll go against this in a year's time
