### ISSUE TITLE
Recording broken as of today (Texture missing shader resource view when setting parameter)

### ISSUE THREAD

**Issue by yuberee** [sboxgame/issues#3162]
### Describe the bug

Using F6 to record videos will now output a video which is only a black screen.
Starting a recording for the first time will spam this in the console:

`Texture missing shader resource view when setting parameter "?" - returning error texture in CTextureManagerDx11::GetResourceView Texture: "swapchaincolor.vtex"`

### To Reproduce

Start a recording with F6
End a recording with F6

### Expected behavior

Normal video

### Media/Files

https://user-images.githubusercontent.com/59583743/233480330-9762805f-d449-466e-8695-0f6942fcad06.mp4

https://user-images.githubusercontent.com/59583743/233480331-bcab521b-47f9-484c-ab0e-859f0f88aeec.mp4

https://user-images.githubusercontent.com/59583743/233480326-a58e745f-2735-4132-85b6-5f92a054d739.mp4

Example outputs

### Additional context

It worked fine as of yesterday

**Comment by garrynewman** [comment]
I had this too. Not sure what changed, if anything. Noticed that it recorded successfully if I resized the window slightly so assume it's a texture resize issue?
