### ISSUE TITLE
Allow us to re-order input actions

### ISSUE THREAD

**Issue by matekdev** [sboxgame/issues#3163]
### For?

S&Box

### What can't you do?

I want to re-order the list of input actions

### How would you like it to work?

Let me drag them around

### What have you tried?

Dragging them around

### Additional context

![image](https://user-images.githubusercontent.com/32153021/233492352-5fc0ec43-1370-4ef1-9c2e-74aeb091c23c.png)

This is extremely minor, but just the ability to organize them would be nice. Or maybe sort them by grouping?

**Comment by DevulTj** [comment]
I'm sorting by group for now.. if it gets messy, we'll add proper user sorting.
