### ISSUE TITLE
`ctrl` key doesn't work unless it is named `Duck`

### ISSUE THREAD

**Issue by matekdev** [sboxgame/issues#3165]
### Describe the bug

If you want to setup an input that uses `ctrl`, you must name the key `Duck` otherwise it will not work.

### To Reproduce

1. Create an input key called anything but `Duck` assigned to `ctrl`
2. Try it ingame

### Expected behavior

`ctrl` should register ingame under a different name

### Media/Files

This does not work
![image](https://user-images.githubusercontent.com/32153021/233496641-e6204e55-f3f8-4c72-86a0-e6e4cd48053a.png)

**Comment by trende2001** [comment]
Yeah, I feel like there's some hard coded aspect to it

**Comment by SryEyes** [comment]
Could be beacuse of the changes in the bitflagvalues. Mind checking if its the same problem with run / shift?

**Comment by DevulTj** [comment]
weird, I'll see if I can reproduce this

**Comment by garrynewman** [comment]
Does your game have other keys named Duck? Can you post your `.addon` file?

**Comment by matekdev** [comment]
> Does your game have other keys named Duck? Can you post your `.addon` file?

Doesn't seem like it
<https://github.com/apetavern/parkour-painters/blob/main/.addon>

**Comment by garrynewman** [comment]
Thanks I know what this is

**Comment by garrynewman** [comment]
This should somewhat be fixed now, with the new game specific settings menu

**Comment by matekdev** [comment]
Still seems to be busted on my end, https://github.com/apetavern/parkour-painters should be a repo project

![image](https://github.com/sboxgame/issues/assets/32153021/ab95a62d-8f8d-4488-a6bb-70b73b89b59f)
![image](https://github.com/sboxgame/issues/assets/32153021/8b1f0cac-7c27-4356-b579-85b85877e7cd)
![image](https://github.com/sboxgame/issues/assets/32153021/ef4ff260-5a85-47ec-a5f7-716638fad0da)

**Comment by matekdev** [comment]
No longer an issue, thanks!
