### ISSUE TITLE
InputAction not released when in escape menu

### ISSUE THREAD

**Issue by SryEyes** [sboxgame/issues#3166]
### Describe the bug

when pressing a key for an action and pressing the escape key afterwards the first key is still getting processed and the state of the input action is "stuck" till you press forward again

### To Reproduce

go into a game
hold forward
press escape
let go of forward
press escape again to resume

---you are still waking forward

### Expected behavior

don't walk forwards anymore

**Comment by DevulTj** [comment]
good catch, I'll sort this out 😄

**Comment by DevulTj** [comment]
should be all good on the next steam build - thanks for the report! ❤️
