### ISSUE TITLE
More robust HTTP client with POST requests

### ISSUE THREAD

**Issue by Remscar** [sboxgame/issues#3168]
### For?

S&Box

### What can't you do?

I can't make POST requests with the `Sandbox.Internal.Http` client, only GET requests.

### How would you like it to work?

```
var client = new System.Net.Http.HttpClient();
```

Or an HTTP client that works similarly, with all the different HTTP methods and options.

### What have you tried?

I can make POST requests in a tool addon by using the Http client mentioned above, otherwise I have to host a service that can tunnel HTTP requests through a websocket, which is silly and jank.

**Comment by DevulTj** [comment]
This has been implemented
