### ISSUE TITLE
Search bar for models on sandbox gamemode 

### ISSUE THREAD

**Issue by sugmagaming** [sboxgame/issues#3170]
### For?

S&Box

### What can't you do?

Currently you cannot search for models on the sandbox gamemode. You can only browse through a limited list.

### How would you like it to work?

I would like to be able to type in a search bar for the model I am looking for.

### What have you tried?

I tried scrolling all the way down but there is a limit.

**Comment by handsomematt** [comment]
We'll get around to reworking the sandbox gamemode with all the good stuff from asset.party
