### ISSUE TITLE
Currently no method to stop a GameTask

### ISSUE THREAD

**Issue by yuberee** [sboxgame/issues#3172]
### What it is?

There is no way to stop a GameTask that is already running.
With normal Tasks you can use a CancellationToken or the Dispose() method, but neither are available since they're all whitelisted.
What I'm trying to achieve is the following:
```
public async Task<List<Cell>> ComputePathParallel( Cell startingCell, Cell targetCell )
{
	var fromTo = ComputePath( startingCell, targetCell );
	var toFrom = ComputePath( targetCell, startingCell );

	var pathResult = await GameTask.WhenAny( fromTo, toFrom ).Result;

	// Stop the other task

	return pathResult;

}
```
When a Task finishes first, it stops the other Task.
Right now I will receive the fastest path as soon as it's finished, but the other task will keep on running anyways.

### What should it be?

GameTask.Dispose
or pass a CancellationToken to GameTasks

**Comment by peter-r-g** [comment]
The cancellation of an asynchronous method is up to the person implementing it. `GameTask.WhenAny` will complete when the first of the N tasks are completed. If you're looking to cancel your ComputePath tasks; Can't you pass the same CancellationToken to each task and then cancel it at the end?

```cs
public async Task<List<Cell>> ComputePathParallel( Cell startingCell, Cell targetCell )
{
  // Use a single source for all tasks.
  var tokenSource = new CancellationTokenSource();
  
  var fromTo = ComputePath( startingCell, targetCell, tokenSource.Token );
  var toFrom = ComputePath( targetCell, startingCell, tokenSource.Token );
  
  var pathResult = await GameTask.WhenAny( fromTo, toFrom ).Result;
  
  // Cancels the token for any other compute still running.
  tokenSource.Cancel();
  // OPTIONAL: You can wait for all of the canceled tasks to finish
  await GameTask.WhenAll( fromTo, toFrom );
  
  return pathResult;
}

private async List<Cell> ComputePath( Cell startingCell, Cell targetCell, CancellationToken token )
{
  // Sprinkle this in your computing code, typically after you have awaited something
  if ( token.IsCancellationRequested )
    // Return some default value since the return value won't be used.
    return null;
}
```

**Comment by yuberee** [comment]
Right that worked, cheers
