### ISSUE TITLE
[Shader Graph]  Quicker way to add reroute nodes onto existing connections

### ISSUE THREAD

**Issue by QuackCocaine** [sboxgame/issues#3174]
### For?

Other

### What can't you do?

Currently, you cannot quickly add a **_reroute node_** onto an existing connection without having to disconnect it first. 

### One of two ways or both

1. By double-clicking or shift-clicking on a connection that's in between two nodes, a **_reroute node_** would be placed where you clicked on the connection line, splitting it but preserving the connection. 

2. By dragging and dropping a reroute node onto an existing connection to split it.

### What have you tried?

 1. Create reroute node and place where I want the connection routed.
 2. Disconnect the connection from the destination node and move it to the left side of the **_reroute node_**.
 3. Then drag a connection from the right of the **_reroute node_** node back to the destination node.

### Additional context

I'd much prefer having a better way to add reroute nodes to existing connections to make cleaning up a messy graph a bit quicker.  And id imagine others would as well.

**Comment by aylaylay** [comment]
Done

**Comment by QuackCocaine** [comment]
Very nice :) 👍
