### ISSUE TITLE
Run event in ProjectRow.OnContextMenu

### ISSUE THREAD

**Issue by lotuspar** [sboxgame/issues#3175]
### For?

S&Box

### What can't you do?

No event provided - can't do much

### How would you like it to work?

`Event.Run("projectrow.contextmenu", menu)` like the other similar events (folder.contextmenu, asset.contextmenu)

### What have you tried?

You could edit the file locally, but that doesn't make sense for obvious reasons

**Comment by DevulTj** [comment]
I've added this event now.

Example usage:
```cs
[Event( "projectrow.contextmenu" )]
protected static void OnContextMenu( ProjectRowContextMenu e )
{
	e.Menu.AddOption( "Testing option", "waving_hand" );
}
```

![image](https://user-images.githubusercontent.com/22372616/234014432-4c97ac77-62c8-4213-8f85-b8509c2da0b1.png)
