### ISSUE TITLE
Shadow atlases hog a lot of vram

### ISSUE THREAD

**Issue by Wall3rHM2** [sboxgame/issues#3176]
### Describe the bug

if you load a map and disconnect, close the game, or change the map it will still keep the map resources stuff, such as textures, in VRam. So if you enter in a game with a different map, your VRam now have to store resources from TWO maps. That being said, GPUs with 2 gb ram such as mine can't run the game that way, only if i choose to play on the map that is already in my vram and do the usual graphics config commands.

### To Reproduce

1. Open S&box
2. do r_gpu_mem_stats in console, you will see that you already have a lot of textures and garbage saved in your vram
3. if you are in developer s&box mode, you will probably get that the vram is alright with r_gpu_mem_stats, so just do the following
4. Open a map and play on it
5. Disconnect
6. Do r_gpu_mem_stats
7. You should see a lot of garbage in the already vram
8. Open another map
9. Do r_gpu_mem_stats again
10. Boom now you have both maps garbage in your vram

### Expected behavior

Not keep the last played map resources in vram

### Media/Files

![image](https://user-images.githubusercontent.com/38440423/233789123-06196b01-ae88-425b-a1fa-3452884fe462.png)

### Additional context

Windows 10
Gtx 960 2GB
8 GB RAM

**Comment by handsomematt** [comment]
Are you actually running out of VRAM?

If I remember right the texture streaming doesn't bother evicting textures unless it needs to allocate new ones.

**Comment by Wall3rHM2** [comment]
> Are you actually running out of VRAM?
> 
> If I remember right the texture streaming doesn't bother evicting textures unless it needs to allocate new ones.

Yes, i am running out of VRAM. Here is the spam i get in my console:
![image](https://user-images.githubusercontent.com/38440423/233795680-c45b6dc7-2fcf-4b42-b7d8-aab4bf64f17d.png)

And its not because my VRAM can't handle the map, because if i use a map, close the game, open s&box again and enter the SAME map, i am able to handle it and no spam of VRAM "Extremely low memory" thing

**Comment by handsomematt** [comment]
I will have a look into this on Monday

**Comment by Wall3rHM2** [comment]
ok

> I will have a look into this on Monday

ok, thank you. Also, it seens that not only the last map gets on this, but if you keep disconnecting and entering in the same exact map, it accumulates more and more garbage, its almost as like there is not garbage collector
![image](https://user-images.githubusercontent.com/38440423/233796435-ef5198bc-32ca-4913-9f20-087953ccd836.png)

**Comment by handsomematt** [comment]
So I had a look at this - there's no leak of anything. We just have very large shadow atlases (512MB), @samzanemesis will reduce these down soon.

But at the same time you are on a drastically low amount of VRAM, so I doubt you'll even really be able to play the game properly after this.

**Comment by Wall3rHM2** [comment]
> So I had a look at this - there's no leak of anything. We just have very large shadow atlases (512MB), @samzanemesis will reduce these down soon.
> 
> But at the same time you are on a drastically low amount of VRAM, so I doubt you'll even really be able to play the game properly after this.

Oh yes, i have noticed this thing about shadow atlases in the textures for about some few days ago... Please make a command to be able to configure the resolution of that texture. This is not the only texture that occupies a lot of VRAM, there are more textures that are used for things that i disable on my game, but they still are kept in my VRAM (for example volume fog).

I am able to run much more complex maps in Garry's Mod maps using only about 600 VRAM. It would be cool if i could get a  similar performance even if i had to run on graphics like Source 1, because as of now the game for me and the people i talk to, has a worse graphics overrall and require better hardware tier. Its not something i expected considering its Source 2.
