### ISSUE TITLE
Launch Config Editor entry names do not update until re-opening the window

### ISSUE THREAD

**Issue by trundlr** [sboxgame/issues#3179]
### Describe the bug

![image](https://user-images.githubusercontent.com/57276947/233799752-a8b7d3e3-3781-44ae-a6d6-48094d1e4d8c.png)

When saving a launch config, the matching name in the sidebar does not update until you close and re-open the window. This is annoying because renaming multiple launch configs at once is confusing.

### To Reproduce

1. Create a launch config
2. Name it something
3. Press save
4. The config does not update

### Expected behavior

The config name should update when the save button is pressed.

**Comment by cr4yz** [comment]
This should be fixed in the next build

**Comment by trundlr** [comment]
Works great, thanks Crayz!
