### ISSUE TITLE
Project settings are not properly setting to default

### ISSUE THREAD

**Issue by trundlr** [sboxgame/issues#3180]
### Describe the bug

Whenever I try to start a lobby for Grubs, the project settings are defaulting to the minimum values instead of the default values:
![image](https://user-images.githubusercontent.com/57276947/233800018-a3e0b626-3d6a-448e-a1b5-8e33631916f7.png)
![image](https://user-images.githubusercontent.com/57276947/233800019-cdd51b2d-e59c-49ea-9251-9b4106acdf08.png)

Maybe this is being caused by the default value being a string value instead of an integer in the .addon?
```
      {
        "DisplayType": "Integer",
        "Choices": [],
        "ConVarName": "terrain_length",
        "DisplayName": "Terrain Length",
        "DefaultValue": "2048",
        "Description": "The length of the terrain.",
        "Group": "Terrain",
        "Minimum": 512,
        "Maximum": 4096
      },
      {
        "DisplayType": "Integer",
        "Choices": [],
        "ConVarName": "terrain_height",
        "DisplayName": "Terrain Height",
        "DefaultValue": "1024",
        "Description": "The height of the terrain.",
        "Group": "Terrain",
        "Minimum": 256,
        "Maximum": 2048
      },
```

### To Reproduce

1. Start a lobby for Grubs
2. Click the project settings
3. Notice terrain length and height are going to the minimum despite the default value being nowhere near that

### Expected behavior

The project settings should be setting to the default value properly.

**Comment by cr4yz** [comment]
This should be fixed in the next build

**Comment by trundlr** [comment]
Works great, thanks again Crayz 👍
