### ISSUE TITLE
[UI] Image bleeding if content is too close to the image's border

### ISSUE THREAD

**Issue by KayaDLX** [sboxgame/issues#3182]
### Describe the bug

Any UI image will bleed if its content is too close to the image's edges, causing very ugly looking UI elements.
To workaround this, you need to resize the image's content to the center so it doesn't bleed.
![image](https://user-images.githubusercontent.com/67245359/233815707-d3b75c41-5cf4-4e4e-b213-9201ef65507a.png)
![image](https://user-images.githubusercontent.com/67245359/233815719-3ceb50b4-7aad-4fb6-9944-98798f8a82be.png)
![image](https://user-images.githubusercontent.com/67245359/233815725-28f3ef49-3e7b-4dd5-8695-5424d887938b.png)

### To Reproduce

1. Get any image
2. Render it on your UI
3. Notice the bleed around the edges

### Expected behavior

Should not bleed.

**Comment by xezno** [comment]
Hey, this should be fixed on next update. This fix won't apply to border images - I'll have a look at those separately later.
Let me know if you find any issues.
