### ISSUE TITLE
info_player_start always faces EAST regardless of rotation

### ISSUE THREAD

**Issue by eagleonedevteam** [sboxgame/issues#3184]
### Describe the bug

Every player spawn will always have the player facing in the east direction regardless of whatever position you rotate the entity

This uses the info_player_start entity

### To Reproduce

Put info_player_start onto map in hammer

Compile map

Note direction the spawn always faces

![image](https://user-images.githubusercontent.com/70182442/233864940-28cbace2-1050-4640-ad81-e0c82f015aa7.png)

![image](https://user-images.githubusercontent.com/70182442/233864972-16dadaa5-66ef-4393-9cc4-9d8bf23ebdda.png)

![image](https://user-images.githubusercontent.com/70182442/233865076-5547de1c-d9fe-4bb1-9854-932365079398.png)

### Expected behavior

Player should spawn in the direction the entity is facing

![image](https://user-images.githubusercontent.com/70182442/233865088-17dbde58-46f1-49ad-9d2e-650505a3279b.png)

### Media/Files

Attached is sample vmap used 

https://drive.google.com/file/d/1qkWi41eBGKbG1Lg5Vn4UwuonIROhbqCV/view?usp=sharing

**Comment by DevulTj** [comment]
Your game controls the direction that the player spawns in - you have that information available to you

Boomer sets the player's view angles manually to avoid this issue - https://github.com/Facepunch/sbox-boomer/blob/main/code/DeathmatchGame.cs#L160

**Comment by eagleonedevteam** [comment]
Bless you for the fast and informative response <3
