### ISSUE TITLE
Ability to select BodyGroups in the Hammer Asset Properties

### ISSUE THREAD

**Issue by drednorzt** [sboxgame/issues#3188]
### For?

Hammer

### What can't you do?

Change between BodyGroups for any given asset when working in Hammer

### How would you like it to work?

Excactly the same way MaterialGroups are changeable through the 'Skin' dropdown field in the Asset Properties.

Having A dropdown field for each Set of MaterialGroups

### What have you tried?

No solutions I can figure out

### Additional context

This would be great for making more universally useful assets. Currently I have to make seperate .vmdl's for different versions of the same asset that have subtly different meshes. Being able to choose between BodyGroups exactly like how you can choose MaterialGroups in Hammer would speed workflow up & cut down on the number of different assets in a project.

For my purposes I'm talking about static props, but it would probably be handy for any kind of asset.

e.g. A metal bar that has a 'Straight' version and a 'Bent' Version.

Obviously this is already doable with code during runtime, but the ability to do it in hammer would be very useful.

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/233867617-64079a6c-4674-4635-9739-5b4ac47ce06e.png)

You already can.

**Comment by Gmod4phun** [comment]
Looks like we can't do it on prop_static, but we can change it's MaterialGroup (skin). We can do it on prop_physics

**Comment by drednorzt** [comment]
aha!

Is it possible to make it work for a prop_static as well?

**Comment by robotboy655** [comment]
I have made it possible to have bodygroups for static props, as well as made the "Convert model to editable mesh" feature in Hammer respect bodygroup choices like expected.

**Comment by drednorzt** [comment]
Working :D

this is awesome

![image](https://user-images.githubusercontent.com/5728855/234983373-da8118f0-c31f-4c61-83a3-ad0613cb6e70.png)
