### ISSUE TITLE
[Shader Graph] Parameters on a node can refuse to unhide if the connection and the node the connection came from were deleted at once 

### ISSUE THREAD

**Issue by QuackCocaine** [sboxgame/issues#3190]
### Describe the bug

When deleting a node and its output connection at the same time when it was connected to another node's input that happens to have parameter controls for that input, the parameter controls won't unhide unless you re-connect and disconnect a connection to the affected input.

### To Reproduce

1. Drag out a connection from the output of one node into the input of another that has a parameter control next to it.
2. Then select both the node you dragged the connection from and the connection itself.
3. Delete them both at the same time.

You should notice the parameter control next to the input that has been removed didn't un-hide itself even though it should have.

### Expected behavior

For the parameter control on the node to unhide when the input next to it is disconnected.

### Media/Files

https://user-images.githubusercontent.com/23345567/233903666-18d4a8fe-7691-4cc0-85a5-a628fa4363d9.mp4

**Comment by aylaylay** [comment]
Done
