### ISSUE TITLE
BBox Rotate Function

### ISSUE THREAD

**Issue by Jake-NSW** [sboxgame/issues#3192]
### For?

S&Box

### What can't you do?

Currently you can't easily rotate a bounding box, which sucks. I'd like to be able to get the collision bounding box, then rotate it and translate it to an entity position or bone.

### How would you like it to work?

```csharp
BBox box = default;
box.Rotate(Entity.Rotation);

// or

box.Translate(Entity.Position, Entity.Rotation)
```

### What have you tried?

I know DebugOverlay.Box() has an overload where it rotates a bounding box, but decompiling the code just went to native stuff, so I couldn't find anything...

**Comment by garrynewman** [comment]
BBox is an AABB. If you want to trace against it, un-rotate the trace.

**Comment by Jake-NSW** [comment]
My bad! Thank you for the correction. 😸
