### ISSUE TITLE
Search through all sub-directories, not just current directory

### ISSUE THREAD

**Issue by drednorzt** [sboxgame/issues#3196]
### For?

S&Box

### What can't you do?

In the asset browser, a search only seems to look through the current directory and no sub-directories.

### How would you like it to work?

Include sub-directories in search results

### What have you tried?

n/a

### Additional context

Not sure if this is missing or just a bug.

**Comment by robotboy655** [comment]
Try toggling this option: 
![image](https://user-images.githubusercontent.com/3299036/234153597-d2e318d2-d8c5-4a99-a7df-9f5518ed9442.png)

**Comment by drednorzt** [comment]
done & done
