### ISSUE TITLE
Deeper text field for 'Description'

### ISSUE THREAD

**Issue by drednorzt** [sboxgame/issues#3199]
### For?

S&Box

### What can't you do?

Fill out the public facing details when uploading assets, as thoroughly as I'd like to.

### How would you like it to work?

Be able to fill out my assets visible info thoroughly without having to go to asset.party afterwards to finish the job.

All it needs to be is a scrollable text field that allows line-breaks.

### What have you tried?

Currently go directly to asset.party to fill in the description field properly. Adds an unnecessary step.

**Comment by robotboy655** [comment]
Should be done when the game next updates.

**Comment by drednorzt** [comment]
Can confirm its working 🎉

![image](https://user-images.githubusercontent.com/5728855/234982836-4fd467d3-bb5e-4026-bf0c-c59c7d9d5d14.png)
