### ISSUE TITLE
Client's profile picture URL property

### ISSUE THREAD

**Issue by yuberee** [sboxgame/issues#3201]
### For?

S&Box

### What can't you do?

A property for IClient to provide the URL of their profile picture, right now we can only load it directly as a texture.

### How would you like it to work?

Similar to other IClient properties.
IClient.ProfilePicture which returns the url as a string, maybe with a better name because I'm bad at those.

### What have you tried?

I tried looking into how it's done for getting the texture and setting it on a panel, but it's all engine code or I wasn't able to find the URL.
I also tried looking into steamworks api but I need an api key to use it.

**Comment by DevulTj** [comment]
ISteamFriends doesn't really have a nice way to implement this, only works for animated avatars.
