### ISSUE TITLE
Input actions for MOUSE lock when a pointer-events panel is added

### ISSUE THREAD

**Issue by kodi022** [sboxgame/issues#3202]
### Describe the bug

Could be a bug in my game but I really couldn't figure out how.

When I have MOUSE1 held down (using the new input actions), then a `pointer-events: all;` panel is added, unlocking the mouse, the MOUSE1 event stays held whether it is actually pressed or not, until the `pointer-events: all;` panel is closed and the mouse is locked again.

### To Reproduce

1. have an input action to MOUSE1
2. `Log.Info(Input.Down("inputwithMOUSE1"));` in simulate or somnmth
3. add a `pointer-events: all;` panel to rootpanel while the MOUSE1 input is true
4. the log stays true when button is released

### Expected behavior

When a pointer-events panel gets added, all mouse bound input actions should possibly be set to false.
Maybe a way to pass it through could be cool but it's beside the point.

### Media/Files

![sbox-dev_hWnsF8oZR8](https://user-images.githubusercontent.com/29390269/234400057-5f76503b-8362-417c-80dc-d93bf61cd577.png)
left mouse button was not being pressed at time of screenshot, and mouse was unlocked
```
	public override void Simulate(IClient cl) {
		base.Simulate(cl);
		if (InMenu || !IsPlaying) return;

		SimulateMovement();
		SimulateUse();
		Log.Info(Input.Down("attack1"));
		if (Input.Down("attack1") && Game.IsServer) {
			FireGun();
		}
	}
```

**Comment by DevulTj** [comment]
I pushed something that might've solved this - can you try again?

**Comment by kodi022** [comment]
apologies, it does seem it is fixed now though. thank you
