### ISSUE TITLE
Most access endpoints fail to reach for asset.party.

### ISSUE THREAD

**Issue by FoxTTT** [sboxgame/issues#3204]
### Describe the bug

I have tried to use GET /asset/{ident} and  GET /asset/list both don't work, however, GET /status does.

https://wiki.facepunch.com/sbox/Backend_API

### To Reproduce

Click on the links and see if it loads the "Text" (Idk formal definition).

### Expected behavior

To show text and not be unreachable.

**Comment by xezno** [comment]
This page on the wiki isn't up-to-date, a lot of the endpoints have moved around, e.g. https://sap.facepunch.com/package/get/1/alex.instagib
If nobody else does it beforehand, I'll update the wiki page this evening

**Comment by FoxTTT** [comment]
> This page on the wiki isn't up-to-date, a lot of the endpoints have moved around, e.g. https://sap.facepunch.com/package/get/1/alex.instagib If nobody else does it beforehand, I'll update the wiki page this evening

Doing it now.
