### ISSUE TITLE
Whitelist Environment.StackTrace (or something similar)

### ISSUE THREAD

**Issue by lotuspar** [sboxgame/issues#3208]
### For?

S&Box

### What can't you do?

Get stack trace

I want to make a debug function that logs the current function name. Would be nice!

### How would you like it to work?

Environment.StackTrace

I'd still have to parse the string after... if there's another way to get the current function (well not the current function... the one that called the function...) please lmk

### What have you tried?

Environment.StackTrace

**Comment by handsomematt** [comment]
I'll whitelist it as it's harmless, but it sounds like you want to be using [caller info](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/caller-information)

**Comment by lotuspar** [comment]
thanks!

**Comment by lotuspar** [comment]
> I'll whitelist it as it's harmless, but it sounds like you want to be using [caller info](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/caller-information)

yeah I think theres like a StackTrace class that's easier to use and nicer to code with but I wasn't sure if it'd be ok with the whitelist
