### ISSUE TITLE
Curve Editor Widget  time range slider also moves the window around

### ISSUE THREAD

**Issue by TheBoxTrot** [sboxgame/issues#3215]
### Describe the bug

when moving your mouse on the time range options of a curve it will move the popup window with it

### To Reproduce

create a game resource that has a curve property. try to adjust the time range with move 

### Expected behavior

the window doesnt move, this bug doesnt seem to happen with the value range sliders

**Comment by cr4yz** [comment]
I'm unable to reproduce this, could you show me a video?


https://user-images.githubusercontent.com/9637557/235716191-9483d647-ccfd-4726-8309-dc69566225ed.mp4

**Comment by TheBoxTrot** [comment]
It seems to have fixed itself. could have been a one off too will close I guess

**Comment by cr4yz** [comment]
> It seems to have fixed itself. could have been a one off too will close I guess

Lemme know if it shows up again and if there's anything in particular you notice that might be causing it
