### ISSUE TITLE
Multiple Commands in one line dont work in the ingame console

### ISSUE THREAD

**Issue by TheBoxTrot** [sboxgame/issues#3216]
### Describe the bug

you are not able to use multiple commands in one line in the game console but you can in the editor modes console. you can get around this though if you bind multiple commands.

commands such as noclip;noclip;kill;restart in the editor console will do all the commands but in the in game console it only does the first

### To Reproduce

type in a command then a ; and type in another command 

### Expected behavior

same as the editor console

**Comment by cr4yz** [comment]
This should work in the next build, lemme know if you have any trouble with it
