### ISSUE TITLE
Unable to bind numpad keys in console

### ISSUE THREAD

**Issue by TheBoxTrot** [sboxgame/issues#3217]
### Describe the bug

Not sure if it doesnt work at all or if the key names are just not prominent but I cant seem to bind anything to number pad buttons. i have tried num7 and bind KP_HOME (which apparently works in csgo)

### To Reproduce

try and bind num7 or smth 

### Expected behavior

you can bind these keys

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/235307636-10b5f2f9-1203-46f7-9da6-28ec39828a0a.png)

You can, but the number keys now use the actual numbers, not their "Num Lock Off" actions like in S1.
