### ISSUE TITLE
Aiming/shooting in 3rd person camera doesnt work properly

### ISSUE THREAD

**Issue by fdghrdtyrfs** [sboxgame/issues#3218]
### Describe the bug

While shooting in 3rd person camera, you need to aim little bit more to left to hit your target. **The bullet does not go where the crosshair is aimed.**

### To Reproduce

1. Open game
2. Go to any game supporting 3rd person
3. Try to shoot
4. --> bullet go wronk!!!!1!!!1 >:(

### Expected behavior

What should happen is that the bullet goes where crosshair is aimed

### Media/Files

![20230429135249_1](https://user-images.githubusercontent.com/132138158/235299218-c6329beb-5731-4281-ae9c-83d56d1f5030.jpg)

**Comment by xezno** [comment]
I think it's up to the authors of 3rd person games to decide whether they trace from the player's eyes (as seen in your screenshot) or from the camera itself
