### ISSUE TITLE
Entity Possession Callbacks

### ISSUE THREAD

**Issue by Jake-NSW** [sboxgame/issues#3220]
### For?

S&Box

### What can't you do?

Current we aren't able to know when a client starts or stops possessing an Entity.

### How would you like it to work?

On the Entity class, adding an override for when a client tries to possess a client. 

Or alternatively turn the Client.Pawn into an interface, that declares the callback functions.

```csharp
void OnPossess( IClient cl );
void OnUnPossess( IClient cl );
```

### What have you tried?

Tried looking for it but couldn't find anything in the API.

### Additional context

I wanted to use this on my components for declaring UI. That way I can create and destory UI based on the context of a pawn. Instead of it being a massive UI root created when the game starts.

**Comment by chrisspieler** [comment]
A feature like this would be quite useful for games where there are many "pilotable" pawns in the world. It would be a good entry point for game-agnostic pilotable entity addons, which I believe are something that will be embraced more and more as this community comes to appreciate the promise of the package system.

**Comment by LeQuackers** [comment]
This would be pretty useful for what I'm working on as well.

I'd opt for this to be implemented as event like [ClientJoined](https://asset.party/api/Sandbox.GameEvent.Server.ClientJoinedAttribute) was instead of a method so it'd have more flexibility. The `PossessEvent`/`UnPossessEvent` argument passed to it would just have the associated `IEntity` and `IClient` as properties, just like the [`ClientJoinedEvent`](https://asset.party/api/Sandbox.ClientJoinedEvent).

**Comment by Igrium** [comment]
It would also be nice to get a reference to the previous entity the client was possessing.

**Comment by LeQuackers** [comment]
I'm in the same boat now and need to create and destroy UI components based on what pawn the client is possessing; have any devs seen this yet? Are there any alternatives that can be used in the meantime (besides creating a massive UI when the game starts)?

**Comment by Jake-NSW** [comment]
![image](https://github.com/sboxgame/issues/assets/55055481/6ac90359-eb66-4e0d-aac5-1dc06dde986c)
I just did this in my Pawns simulate for the time being. Wheres those Event.Run stuff dispatches events to some component to handle the creation of UI for that entity when its possessed. 

Base Component
https://github.com/Jake-NSW/Signals/blob/main/Signals/Library/Platforms/S%26Box/Components/EntityHudComponent.cs

Component for creating RootPanels for BaseComponent
https://github.com/Jake-NSW/Signals/blob/main/Signals/Library/Platforms/S%26Box/Components/HudComponentHandler.cs

Usage
https://github.com/Jake-NSW/Espionage/blob/master/Code/UI/Operator/Components/InventoryNotificationHudComponent.cs
