### ISSUE TITLE
Scale per axis

### ISSUE THREAD

**Issue by Mbk10201** [sboxgame/issues#3229]
### For?

S&Box

### What can't you do?

Actually we can only scale per axis on hammer but it can be very useful if we can do it as well in the game.

I need this feature because I'm working on a vehicle system and the wheels are independent prop attached to the vehicle but here comes the problem with them, imagine we want to be able to use the same wheels to others vehicles but the sizes of them are smaller or bigger depends of the vehicle, a scalable options can save this issue.

This gonna be useful to avoid duplicates models of the prop with differents sizes and make only one model scalable by vehicle.

### How would you like it to work?

Be able to scale a model by X Y Z axis like 

### What have you tried?

Nothing

**Comment by NevaVerse** [comment]
Can't approve more

**Comment by DoctorGurke** [comment]
#19 #1186

**Comment by kristiker** [comment]
I'd rather make 3 different types of tires

**Comment by Mbk10201** [comment]
> I'd rather make 3 different types of tires

Yeah if there implementation of the scale i will do it, but others vehicles games have this features on their game, such as forza, assetto corsa and many more.

**Comment by handsomematt** [comment]
scale is uniform only in source 2, no plans to change this
