### ISSUE TITLE
Entities network extremely slow on client

### ISSUE THREAD

**Issue by timmybo5** [sboxgame/issues#3230]
### Describe the bug

Situation: my game class has `[Net] public Gamemode Gamemode { get; set; }`
when I instantiate a new gamemode on server `Gamemode = new GunGame()` it takes about 5 seconds to set it for clients.

When Gamemode was a BaseNetworkable this update was almost instantly but as an Entity it takes way too long.

## DEMO
I type a command to recreate the gamemode and the UI shows how long it takes to update on client.

https://user-images.githubusercontent.com/4988198/235677974-d7059cd4-6c89-4ca2-b9a5-100d7a08bfd4.mp4

**Comment by handsomematt** [comment]
When you have it as an entity are you doing TransmitType.Always

**Comment by timmybo5** [comment]
That works, thanks! :)
