### ISSUE TITLE
Input.Pressed firing twice inside UI Tick Event

### ISSUE THREAD

**Issue by Geeknerd1337** [sboxgame/issues#3232]
### Describe the bug

When I try to have something triggered by a single button press in the UI using `Input.Pressed`, it triggers twice.

### To Reproduce

1. Open your gamemode and add a UI razor template
2. Override your Tick method and put the following code:
```cs
if(Input.Pressed("view"){
     Log.Info("Test");
}
```
3. Notice `Test` printing twice on occasion in the console.

### Expected behavior

This should only be printed once.

### Media/Files
![SboxBug-min](https://user-images.githubusercontent.com/15205856/235831524-10206ffd-a202-4c9d-971d-e1a72cc78bcd.gif)

**Comment by handsomematt** [comment]
Had fixed this previously, I think input actions stomped it all though. Will try to sort it

**Comment by Remscar** [comment]
This also happens in FrameSimulate

**Comment by handsomematt** [comment]
Works consistently even at low fps for me now, let me know if it's not fixed for you though.

**Comment by Geeknerd1337** [comment]
As far as I can tell this is fixed now, thanks!
