### ISSUE TITLE
Whitelist the usage of System.Environment

### ISSUE THREAD

**Issue by Arr-n-D** [sboxgame/issues#3245]
### For?

S&Box

### What can't you do?

I would like to be able to store .env files in my project containing environment variables for my code to read and set as environment variables and then use.
Currently both System.Environment.GetEnvironmentVariable and SetEnvironmentVariable are restricted

### How would you like it to work?

N/A

### What have you tried?

Could possibly use appsettings.json as an alternative. 

Would still appreciate access to those two methods.

**Comment by lotuspar** [comment]
while I don't really disagree with adding GetEnvironmentVariable (could be nice for servers), are you sure your use case makes sense?

**Comment by Arr-n-D** [comment]
I'm currently setting up an API framework/library that could benefit from having access to Get and Set. I do agree that it'd be useful for servers and that's the gist of what I have in mind once a stable Linux server build is available

**Comment by peter-r-g** [comment]
I think this would need to bring another allow list defining what environment variables you can get and set. At some point, all of these allow-listed things will probably need to be portrayed to the end player to show them what games can and cannot do/access from your machine. Explaining environment variables and what a game can touch sounds like a pain.

**Comment by Arr-n-D** [comment]
> I think this would need to bring another allow list defining what environment variables you can get and set. At some point, all of these allow-listed things will probably need to be portrayed to the end player to show them what games can and cannot do/access from your machine. Explaining environment variables and what a game can touch sounds like a pain.

Obviously I think environment variables should only be accessible server side and NEVER never know anything about the client, if they're able to be split.

**Comment by peter-r-g** [comment]
> Obviously I think environment variables should only be accessible server side and NEVER never know anything about the client, if they're able to be split. 

A majority of games will be played with a client also being the server so that would not matter. A solution could be to lock the feature to games that do not allow clients to host their own server.

**Comment by Arr-n-D** [comment]
> > Obviously I think environment variables should only be accessible server side and NEVER never know anything about the client, if they're able to be split.
> 
> A majority of games will be played with a client also being the server so that would not matter. A solution could be to lock the feature to games that do not allow clients to host their own server.

I agree that for clients also being the server that would be bad, but games running as purely dedicated servers should be able to access and set environment variables imo

**Comment by garrynewman** [comment]
This doesn't seem like a good idea

**Comment by handsomematt** [comment]
Since the only use case is for a dedicated server, why wouldn't you just pass them into a convar at launch, this'd be fully compatible with docker env/arg too

**Comment by Arr-n-D** [comment]
> Since the only use case is for a dedicated server, why wouldn't you just pass them into a convar at launch, this'd be fully compatible with docker env/arg too

Not going to lie, I didn't think about that. That would work
