### ISSUE TITLE
[Hammer] Weird fog volume behavior

### ISSUE THREAD

**Issue by trende2001** [sboxgame/issues#3247]
### Describe the bug

When you have more than 1 fog volume in your map, the fog volumes after that will start behaving super weirdly.
Such behavior is: 
1. fog teleporting to certain spots
2. turning invisible when you're inside the said fog volumes

Weirdly enough, at a certain angle, sometimes these fog volumes actually spawn within their bounds and don't teleport anywhere

### To Reproduce

Reproduction map (not allowed to send .vmap files)
[fog_lights_repro.zip](https://github.com/sboxgame/issues/files/11412402/fog_lights_repro.zip)

### Expected behavior

There seems to be a strange limitation with fog volumes. It needs to work regardless of how many fog volumes you have spawned in your map. 

### Media/Files

![image](https://user-images.githubusercontent.com/68961063/236625627-f71659ed-59b4-4eb4-af04-62199e8e540e.png)

https://user-images.githubusercontent.com/68961063/236625750-1a4ed00f-0df8-49e0-b396-18b509754eb6.mp4

Said behavior happens in the game as well.

**Comment by samzanemesis** [comment]
should be gucci
