### ISSUE TITLE
Making a Map project instead creates a Content project

### ISSUE THREAD

**Issue by SplatzyXD** [sboxgame/issues#3248]
### Describe the bug

I try to make a new map project. and it instead makes a content project. 

### To Reproduce

Create new Project
Select map project
Apply name
Create

BAM makes a content project instead of a map project

### Expected behavior

It should make a map project with a premade map instead of a content project with nothing in it.

### Media/Files

https://user-images.githubusercontent.com/101920640/236635034-d54f18c9-1cee-4211-a174-9d5e6d859da3.mp4

**Comment by DoctorGurke** [comment]
This is normal. Map projects are deprecated. Maps are just assets now and uploaded as such.

**Comment by SplatzyXD** [comment]
Why were map projects made deprecated?

**Comment by handsomematt** [comment]
To publish your map, you no longer do it via the Project tab. Map Projects no longer exist.

To publish find the vmap in the asset browser and select it, you'll have the option in the inspector to publish.

This change brings the following benefits:

1. Can edit multiple maps in one project
2. Can name your map whatever you want
3. Works exactly the same as publishing models
4. Map can be in any folder
5. Model/Addon references work again

**Comment by SplatzyXD** [comment]
Is there a way i can reobtain the old preset file for the map?

**Comment by DoctorGurke** [comment]
![IJD2Fwo94l](https://user-images.githubusercontent.com/12602100/236636938-36d90a3a-4cfe-41b3-bcfe-ef1bf5619a10.png)

**Comment by SplatzyXD** [comment]
thank you !
