### ISSUE TITLE
Foliage shader is busted in VR

### ISSUE THREAD

**Issue by MuffinTastic** [sboxgame/issues#3251]
### Describe the bug

A video is worth a thousand words, see below. I think it might simply not be accounting for VR

### To Reproduce

Load into any map with foliage. Gamemode does not matter. This is with `sbox.exe -vr`, haven't tested sbox-dev

### Expected behavior

Rendering properly in both eyes

### Media/Files

Recorded using the right eye as dominant

https://user-images.githubusercontent.com/10884425/236653318-a3bbfccd-b07f-453a-bbb3-0d7c92cf1a96.mp4

### Additional context

RTX 4080
Driver 531.41

**Comment by handsomematt** [comment]
![image](https://github.com/sboxgame/issues/assets/1388267/4f3f57f3-7ea5-4b49-ad73-f7c5d2e3e74f)

@samzanemesis got this one
