### ISSUE TITLE
Unlisted gamemodes show up in new & trending

### ISSUE THREAD

**Issue by timmybo5** [sboxgame/issues#3253]
### Describe the bug

Unlisted gamemodes are unlisted for a reason, could they be hidden from new & trending?

![image](https://user-images.githubusercontent.com/4988198/236700798-db83819d-bcf3-4c1b-9ceb-1f6cc265da0d.png)

**Comment by trundlr** [comment]
For what it is worth, these games only appear to users who also belong to the organization. So I would not (and do not currently) see Strike Force in my New & Trending.

**Comment by timmybo5** [comment]
Oohh I didn't know, thanks for sharing! I'll close the issue :)
