### ISSUE TITLE
Single frame ScenePanels to avoid massive drops when using multiple

### ISSUE THREAD

**Issue by timmybo5** [sboxgame/issues#3262]
### For?

S&Box

### What can't you do?

I use ScenePanels to display weapon models in a menu, however when there are more than 6-8 scenes active on the screen fps drops from 90+ to +-20, my guess is that recalculating all the frames for each ScenePanel is expensive.

Once the model has been set there really is no need to keep recalculating each scene panel frame.
It would be nice to have an option to calculate just a single frame and then to reuse that frame until a method forces it to recalculate the frame.

If there is a better solution already available then I am unaware of it, feel free to inform me :)

### How would you like it to work?

Could be a property indicating to use a single frame only:
- `ScenePanel.SingleFrame = true`

And then a method to recalculate the frame so we can choose when to visually update:
- `ScenePanel.DisposeFrame()`

**Comment by DoctorGurke** [comment]
are You not able to render the scene to a texture?

**Comment by chrisspieler** [comment]
Is this what you're looking for?

https://asset.party/api/Sandbox.UI.ScenePanel.RenderOnce

**Comment by timmybo5** [comment]
Wow that's exactly what I was looking for! :D
