### ISSUE TITLE
Unable to open prefabs

### ISSUE THREAD

**Issue by matekdev** [sboxgame/issues#3263]
### Describe the bug

Prefabs seem to be completely busted and cannot be opened. The icon is missing and it throws a null ref when attempting to open a prefab.

### To Reproduce

1. Find a prefab
2. Try and open it

### Expected behavior

The prefab should open

### Media/Files

Here are some example prefabs from grubs
![image](https://github.com/sboxgame/issues/assets/32153021/15f66e09-b169-4f87-ad7f-68441935ea3d)
![image](https://github.com/sboxgame/issues/assets/32153021/6bac3649-2baa-476e-846a-836d8d30f7a4)
![image](https://github.com/sboxgame/issues/assets/32153021/1f0292d2-f807-4d92-9271-2c23a141dd20)
Stack trace from the failed attempt to open a prefab

**Comment by matekdev** [comment]
Maybe related to this commit?
https://discordapp.com/channels/833983068468936704/835035328779518023/971013201347092481
![image](https://github.com/sboxgame/issues/assets/32153021/57f51a6a-0f34-43af-a547-e15d7177cc86)

Seems a bit long though for prefabs to be broken for a week and nobody to report it.

**Comment by DoctorGurke** [comment]
sir that commit was over a year ago, how did you even find that

**Comment by matekdev** [comment]
uhh... I just woke up, didn't check the year haha.

**Comment by DoctorGurke** [comment]
seems like any of the icon thumbnails work, something related to the pixmaps broke 

here with a .sound asset
![Discord_2n89Bc5Erl](https://github.com/sboxgame/issues/assets/12602100/a0dadff6-d0e1-4361-9f14-723d4681c697)

**Comment by matekdev** [comment]
thanks
