### ISSUE TITLE
Unable to compile lightmaps in hammer on latest update

### ISSUE THREAD

**Issue by KingOfTheFBI** [sboxgame/issues#3277]
### Describe the bug

looks like something got broken with the last update, lightmaps or broke and this is the exit code
![b91a6514a7661f80cfaafc2e0ed4100f](https://github.com/sboxgame/issues/assets/105941502/2122fd4d-1cd9-4093-a598-963cdabeac66)
![e1f2203587e7569c00dc2757ef55fc65](https://github.com/sboxgame/issues/assets/105941502/2861e086-dbb8-41dc-89f9-0bbabef57d6b)

### To Reproduce

1. Open a map with lights
2. Compile with generate lightmaps ticked

### Expected behavior

The compile works

**Comment by garrynewman** [comment]
Should be fixed on next build - sorry about that!
