### ISSUE TITLE
Make a separate SetVariable[A/B] input (compare and not compare)

### ISSUE THREAD

**Issue by ItsRifter** [sboxgame/issues#3278]
### For?

Hammer

### What can't you do?

For my case, its impossible to make a keypad code logic system.

While the logic entity serves its simple purposes, it might make complex logic very difficult or impossible.

Speaking for others that intend making maps for the sandbox gamemode (adventure type etc), this could help in certain situations.

### How would you like it to work?

Make SetVariableA and SetVariableB not compare and instead make separate inputs simply SetVariableACompare and SetVariableBCompare.

### What have you tried?

I don't see any possible workarounds with this problem without creating a separate game with its own hammer entities.

### Additional context

A map with this issue can be viewed here (VPK/VMap included)

Filename: madhouse
https://www.dropbox.com/sh/nr0qabr5lzmifes/AACje_Apknya_IUHlNH54hIda?dl=0

when pressing the buttons seems to throw an error with the logic entity on trigger.

**Comment by robotboy655** [comment]
The logic entity is kept very basic on purpose. It's a stopgap solution. It will probably be removed in favor of maps using custom entities from asset.party (which would make it much easier to set up in Hammer and also be more efficient for execution), or maybe a node basic approach to logic one day.

**Comment by ItsRifter** [comment]
Ah alright, in that case I'll just close this issue
