### ISSUE TITLE
SpotLightEntity.LightCookie set after initialization is not used by light

### ISSUE THREAD

**Issue by chrisspieler** [sboxgame/issues#3288]
### Describe the bug

When you set the LightCookie property of a light in an object initializer, the light cookie is applied as normal. If you were to set the property at later time instead, the light cookie would not be applied at all.

Pictured: Lights that have had their light cookie changed to dog pictures, but no dogs are visible.
<img width="376" alt="image" src="https://github.com/sboxgame/issues/assets/8889285/b60b9be8-13b9-4510-a4f9-175ca82db8b3">

### To Reproduce

In the S&box editor, import the game project attached in Media/Files. Run the "Light Cookie Repro" game using the included map file, "maps/light_cookie_repro.vmap". Look at the part of the map depicted in the previous screenshot.

### Expected behavior

The lights depicted in the screenshot should cycle through cute dog photo textures.

### Media/Files

[light_repro.zip](https://github.com/sboxgame/issues/files/11481529/light_repro.zip)

**Comment by o-brkyr** [comment]
+1
Would also be nice to use materials for cookies rather than just textures
