### ISSUE TITLE
Spotlight light is not updated when LightCookie is written to by compute shader

### ISSUE THREAD

**Issue by chrisspieler** [sboxgame/issues#3289]
### Describe the bug

When the LightCookie of a spotlight is updated via a compute shader, the light that is cast by the spotlight will not be affected despite the Texture for the light cookie having apparently been updated.

https://github.com/sboxgame/issues/assets/8889285/d72c8f7f-9c89-4fff-99af-e08e7cb1f6f9

### To Reproduce

Import the game from the attachment in media/files. Launch the included vmap, "maps/light_cookie_repro.vmap". Go to the "COMPUTE SHADER TEST" room. Observe the dog photo that is projected on the wall. Run "cookie_shader_debug 1" in the console. Observe the dog photo that appears in the debug overlay.

### Expected behavior

Because the texture in the debug overlay is read from the LightCookie texture of the spotlight entity, the light on the wall will update whenever the Texture in the debug overlay is updated.

### Media/Files

[light_repro.zip](https://github.com/sboxgame/issues/files/11481595/light_repro.zip)

**Comment by samzanemesis** [comment]
Add a renderer target flag to it and it should work, this really isn’t the most optimal way to do this though

**Comment by samzanemesis** [comment]
Alright, I've made it so that an UAV texture also updates the spotlight cookie as well so it should apply for your case

This is due a rewrite soon anyway

**Comment by chrisspieler** [comment]
> Alright, I've made it so that an UAV texture also updates the spotlight cookie as well so it should apply for your case
> 
> This is due a rewrite soon anyway

Thanks, it works! 

https://github.com/sboxgame/issues/assets/8889285/304e2faf-4216-46f9-b9bc-e12977f17853
