### ISSUE TITLE
asset.partys key raffle isnt working for me

### ISSUE THREAD

**Issue by weedgoose** [sboxgame/issues#3300]
### Describe the bug

well i wanna try go to the raffle but the system doesnt working for me so

### To Reproduce

asset.party
log in (if not already)
click on key/click here area
nothing(well the count down, the user icon not popping up, the key is stuck on five, ect.)

### Expected behavior

?

### Media/Files

?

### Additional context

?

**Comment by DrakeFruit** [comment]
this is not a bug, the raffle is disabled 🤦

**Comment by Andiq** [comment]
The key raffle has been suspended indefinetly the only way you can get a key now is to apply trough the forum.
