### ISSUE TITLE
[ServerOnly] Attribute

### ISSUE THREAD

**Issue by Weldify** [sboxgame/issues#3308]
### For?

S&Box

### What can't you do?

Currently I'm unable to write code that exist in a single realm. There are things you don't want the client to see.

### How would you like it to work?

The `[ServerOnly]` attribute should be applicable to basically everything - classes, methods, properties, etc.
When the game is compiled/exported (not sure how that works), everything with the `[ServerOnly]` attribute should be stripped from the client.

### What have you tried?

Nothing

### Additional context

It would be nice if this could be added earlier than later, even if it won't do anything, sorta like the `[Local]` attribute - it doesn't seem to do anything right now, but I still use it in my code because it will benefit me later on.

Im surprised that there still isn't an issue on this yet, that being said maybe I'm just blind and can't search properly so if someone made this issue before me I'd be happy to close this

**Comment by TheBoxTrot** [comment]
Do you have any examples on where this would be actually used. Since I can't think of anything that you wouldn't want to be replicated on the client too

**Comment by Weldify** [comment]
> Do you have any examples on where this would be actually used. Since I can't think of anything that you wouldn't want to be replicated on the client too

Discord webhook links, weapon damage stats, area names/descriptions for something like an RPG, quest names/descriptions, serverside only functions in general, you wouldn't want clients snooping around.

Leaving serverside code in makes your game easily reverse engineerable. Without the serverside code it becomes ten times harder

**Comment by garrynewman** [comment]
I can see the usefulness of this

**Comment by Brassx** [comment]
This has been brought up in discord a bunch, and usually sparks a long winded debate, but it's definitely something that should exist eventually, in my opinion.  Years ago when it was brought up, it was seen as very low priority, hoping that has shifted a bit.

(Also please ServerRPC's 🥲 I don't like using console commands for everything )
