### ISSUE TITLE
Mappable hotkey for HammerApp 'Toggle world space'

### ISSUE THREAD

**Issue by drednorzt** [sboxgame/issues#3312]
### For?

Hammer

### What can't you do?

Set up a hotkey to quickly change between world & local manipulation spaces.

### How would you like it to work?

I don't know what a default hotkey could be that wouldn't conflict with anything else, so maybe just the option to map it manually would be straightforward.

(I'd personally set it up to be something extremely convenient, i.e. a single key on the left side of the keyboard, or even a modifier key + a mouse click of some kind)

### What have you tried?

Currently have to toggle it manually with the mouse up in the toolbar, or use the F1 menu and search for it (too many steps).

Have tried finding it in the hotkey settings list but it ain't there.

**Comment by DoctorGurke** [comment]
have you tried tab

**Comment by bakscratch** [comment]
Is it not Tab?

**Comment by chrisspieler** [comment]
https://github.com/sboxgame/issues/assets/8889285/4a68fe5a-1458-4706-b8e3-f44fa5e05a41

**Comment by drednorzt** [comment]
hahaha what an idiot i am. turns out my fantasy is already reality!
