### ISSUE TITLE
Panel scroll via touch controls interferes with actual input elements and hangs a lot

### ISSUE THREAD

**Issue by DoctorGurke** [sboxgame/issues#3316]
### Describe the bug

Scrolling panels with touch controls (click and drag) feels very jarring due to a hang spike when you start dragging and interferes with other input elements like sliders.

### To Reproduce

1. Quickly start swiping up and down in the main menu and compare it to regular scrolling.
2. Try to use elements like sliders on scroll panels
3. Notice Jarring experience

### Expected behavior

Touch scroll shouldn't hang this much or interfere with other input elements on the same panel.

### Media/Files

https://github.com/sboxgame/issues/assets/12602100/c658f2b5-5090-46ac-a716-37b2b5f6d40f

https://github.com/sboxgame/issues/assets/12602100/573db51a-edaf-421e-bb2f-03d8530cbe27

**Comment by garrynewman** [comment]
I haven't experienceecond one define seeing in the first issue.

The second one confirmed, I've got a fix for it but I don't like it, so will push when I get a real one.

**Comment by garrynewman** [comment]
I found the problem here, it was the styles rebuilding. Managed to get it down from ~70ms to 0.7ms on my branch, so should feel a lot better when I merge in.
