### ISSUE TITLE
Couldn't load game - Unable to find package error when using the Inspector

### ISSUE THREAD

**Issue by yuberee** [sboxgame/issues#3320]
### Describe the bug

Whenever I inspect an entity in the Explorer I get the following error:
```
Couldn't create Editor.Inspectors.EntityInspector
System.MissingMethodException: Constructor on type 'Editor.Inspectors.EntityInspector' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Sandbox.Internal.TypeLibrary.Create[T](Type type, Object[] args)
   at Editor.CanEditAttribute.CreateWidget(Type t, IEnumerable`1 attributes, Type[] generics, Object obj)
```
And if I have the Inspector still showing the entity, WHILE the explorer is on the Entities tab, I receive the following error:
```
Couldn't load game - Unable to find package 'local.bomb_survival#local'
System.IO.FileNotFoundException: Unable to find package 'local.bomb_survival#local'
   at Sandbox.PackageManager.InstallAsync(String packageIdent, String contextTag, CancellationToken token, ILoadingInterface loading, Boolean allowLocalPackages)
   at Sandbox.ServerDll.ServerLoad()
```
And the game won't launch

### To Reproduce

1. Launch your game
2. Select an entity in the Entities tab of the Explorer, so it shows up on the Inspector (Make sure to stay on the Entities tab of the Explorer or else it won't happen)
3. Restart the game (Either through the Launcher or through console command)

### Expected behavior

-

### Media/Files

https://www.youtube.com/watch?v=XSQtQy0P9NA

### Additional context

I've already restarted S&box and my PC, if it ends up being a problem with my game I'll share the repository.

**Comment by CarsonKompon** [comment]
Can confirm that this is happening as of a recent update.

Another way to reproduce is by simply opening the UI explorer tab and then restarting the addon
![image](https://github.com/sboxgame/issues/assets/5159369/b44db125-5251-43bb-b1ae-8d47acb3c313)

**Comment by DoctorGurke** [comment]
This is quite annoying while I'm also troubleshooting new bugs from recent UI updates...
![sbox-dev_FBSr5UBymp](https://github.com/sboxgame/issues/assets/12602100/b74cecb5-7ce6-41d7-a2c1-150111d00c42)

**Comment by PolSpock** [comment]
I'm fed up to restart my game all the time cause i'm using the in game inspector too, what's why i'm sharing another video

https://github.com/sboxgame/issues/assets/5229571/532527c1-2856-4118-b6b1-f95b482df40d

**Comment by VanderCat** [comment]
> I'm fed up to restart my s&box editor all the time

As a workaround you can switch to projects tab and it should launch fine

**Comment by PolSpock** [comment]
> @PolSpock
> 
> > I'm fed up to restart my s&box editor all the time
> 
> As a workaround you can switch to projects tab and it should launch fine

i didn't know that, thx 😍

**Comment by Jake-NSW** [comment]
I am having this issue is and have been having this issue for a couple of weeks now. It's incredibly frustrating...
