### ISSUE TITLE
Custom launch configs do not get hidden when a referenced project is disabled

### ISSUE THREAD

**Issue by peter-r-g** [sboxgame/issues#3321]
### Describe the bug

If you have custom launch configurations that reference a certain project and it gets disabled; it will not get hidden. In cases where you are referencing a game and it becomes disabled. Only the generated configuration is hidden. When you look at the custom config after disabling the referenced project it will no longer show anything in its place.

### To Reproduce

1. Create a custom launch configuration that references X project.
2. Disable X project.
3. Observe generated config for X (if it is a game) is hidden, but custom configs that reference X are not.

### Expected behavior

Once a project is disabled, any custom launch configurations that have a reference to it become hidden.

**Comment by DevulTj** [comment]
This might add unnecessary complexity to the launcher, but I'd like to know what other people think about this

**Comment by ItsRifter** [comment]
Perhaps not to make it hidden instead add a warning indicator (a icon and/or pop-up message).

This would only apply if a game is not selected in the launch config.

**Comment by DoctorGurke** [comment]
Definitely shouldn't show configs for local games that aren't enabled

**Comment by Adesii** [comment]
i sometimes have lots of smaller prototypes that i enable/disable a lot, it gets annoying having 10's of launch configs which don't work just to find the one im currently working on. Having them disabled or moved to the very bottom would be great imo.

**Comment by peter-r-g** [comment]
No longer relevant
