### ISSUE TITLE
`TimeUntil` no longer works when comparing to a number

### ISSUE THREAD

**Issue by Remscar** [sboxgame/issues#3323]
### Describe the bug

You used to be able to do this, but it doesn't seem to work anymore.

When I try to do
```
bool finished = TImeUntilSomething < 0
```
finished will never be true unless I do `TimeUntilSomething.Relative`

### To Reproduce

```cs
TimeUntil foo = -1;
bool finished = foo < 0;
Log.Info(finished);
```
You will get `False` in your logs
```cs
TimeUntil foo = -1;
bool finished = foo.Relative < 0;
Log.Info(finished);
```
Works though

### Expected behavior

Comparing a `TimeUntil` to a number should default to checking the relative time, just like the behavior of `TimeSince`

**Comment by garrynewman** [comment]
That's weird, that class hasn't changed in 200 days, and that's exactly how I use it still..

**Comment by Remscar** [comment]
> That's weird, that class hasn't changed in 200 days, and that's exactly how I use it still..

I know right? I thought I was going insane but that's how it's behaving when I write some new code using it.
Maybe I am insane?

**Comment by Weldify** [comment]
This is still an issue, just spent around 30 minutes trying to figure out whether im braindead or something is wrong with it. It looks fine in the inspector - all values are correct. So its just something wrong with comparison.

I managed to work around this by doing `TimeUntil.Fraction == 1f`

**Comment by garrynewman** [comment]
Can you tell me more about this problem? Does it always happen, or just after a long uptime?

**Comment by trundlr** [comment]
In both examples I've seen, the user with the issue is instantiating the TimeUntil with a negative number. Not sure if it's related.

**Comment by Weldify** [comment]
![image](https://github.com/sboxgame/issues/assets/66477673/76315cf2-b6fb-428f-a3e1-c0c75727cccf)
Interesting, the runtime has a different version. I will reinstall the runtime and test it again in my game.

**Comment by Weldify** [comment]
> In both examples I've seen, the user with the issue is instantiating the TimeUntil with a negative number. Not sure if it's related.

Not in my case, was broken for me and I didn't set it to a negative number

**Comment by garrynewman** [comment]
Oh man, that's crazy.

**Comment by Remscar** [comment]
Can confirm, updating to latest runtime version fixes this.
