### ISSUE TITLE
[Asset Browser] Dump thumbnail to png in new Asset Browser

### ISSUE THREAD

**Issue by Jammie3d** [sboxgame/issues#3324]
### For?

S&Box

### What can't you do?

In the legacy asset browser you can dump thumbnails to a png, this is very useful for UI icons like the weapons in Grubs.

It's handy being able to rotate a model in modeldoc, dump the thumbnail and then undo the rotation so that it still works as it did ingame.

I assume that the legacy asset browser will be removed at some point, so I hope this can be implemented before then.

### How would you like it to work?

Right click a model file in the asset browser, choose the dump thumbnail to png option, an image file is created in the same directory with the same filename as the model.

### What have you tried?

Using the legacy asset browser, which currently works fine.

**Comment by xezno** [comment]
Should be added in next build, let me know if there's any problems - feel free to close otherwise.
