### ISSUE TITLE
Devcam requires specific inputs to be defined in gamemode to function

### ISSUE THREAD

**Issue by matekdev** [sboxgame/issues#3331]
### Describe the bug

Attempting to use the devcam when you don't have the default input actions defined (i.e "run", "duck", "slot1", etc.) breaks the functionality associated with them.

### To Reproduce

Attempt to use the dev cam with a game mode that doesn't have the default input actions defined (i.e no "run" defined). Notice that the associated functionality will no longer work.

### Expected behavior

It should function as expected.

### Additional context

Matt said he had some ideas on how to improve this. I feel as though if a function is a default in every single gamemode, it should function regardless of the input action structure of the gamemode.

**Comment by handsomematt** [comment]
my general thinking here is that devcam should be something the editor does, not part of games
