### ISSUE TITLE
Parallax doesnt light up when dynamic lights hit it at 90° 

### ISSUE THREAD

**Issue by Andiq** [sboxgame/issues#3349]
### Describe the bug

When you shine a dynamic light on a parallax material at 90° it will only light up parts that are on the surface.

### To Reproduce

1. Grab a dynamic light.
2. shine it onto a parallax material at 90°
3. Only the parts that are level with the surface light up.

### Expected behavior

1. Grab a dynamic light.
2. shine it onto a parallax material at 90°
3. The material lights up correctly.

### Media/Files

https://cdn.discordapp.com/attachments/833983416390385685/1112709276717285436/sbox_0014.mp4
![grafik](https://github.com/sboxgame/issues/assets/17596636/0d1c6e85-3022-467f-8f55-0ea26437e6b9)

**Comment by Baik90** [comment]
To see that in motion.
https://github.com/sboxgame/issues/assets/88790023/bdef5d36-681e-4cf6-9a14-b95d2bd0707b
