### ISSUE TITLE
Voxel Surface no longer works

### ISSUE THREAD

**Issue by trende2001** [sboxgame/issues#3350]
### Describe the bug

Whenever I try to use the voxel surface entity, either by creating it with a block or quad, it wouldn't spawn in game

### To Reproduce

1. Go in Hammer
2. Find Voxel Surface in the entity list
3. Create it by dragging out a brush
4. Compile (preferably fast compile)
5. Doesn't work

### Expected behavior

It should spawn the entity.. I don't know why it randomly stopped working

**Comment by aylaylay** [comment]
Should be fixed now.. although sandbox gamemode will need to be updated unless you're running a local version.
