### ISSUE TITLE
Dark Materials/Models

### ISSUE THREAD

**Issue by PixelQubed** [sboxgame/issues#3351]
### Describe the bug

When viewing your own assets that you have the source files for in any viewport ingame after they have been loaded, they seem to appear almost black light the contrast on them is really high. This is recent. From what I can tell it seems to only happen to models you preview and have source file access to. Stuff downloaded from asset.party cant be recompiled without access to the source material so they don't appear to have this issue.

### To Reproduce

1. Go to the material editor or model doc and open a material or model you have the source files for.
2. Look at the preview. It will appear black.

### Expected behavior

Materials should not appear black in viewports or in game.

### Media/Files

<img width="1070" alt="sbox-dev_xRvLxqJhNW" src="https://github.com/sboxgame/issues/assets/32498714/7eebca45-4461-4f51-968e-76a3f29e76a7">

https://github.com/sboxgame/issues/assets/32498714/cc801043-c214-4b89-9dcc-8437ea885f83

### Additional context

I'm running Windows 11 Pro, Ryzen 3900x CPU, 16GB 3200mhz RAM, B450 Motherboard, GTX 1080TI running at 4k.

**Comment by handsomematt** [comment]
My bad, should be fixed in the next build in about 15 minutes or so.

**Comment by PixelQubed** [comment]
> My bad, should be fixed in the next build in about 15 minutes or so.

Sorry for the late reply. Yes this is fixed. Thanks matt.
