### ISSUE TITLE
Viewmodel shadow cascade is too big and looks crap

### ISSUE THREAD

**Issue by Xenthio** [sboxgame/issues#3352]
### Describe the bug

Viewmodels (which as far as i know have their own shadow cascade) have really low quality shadows when they are at their proper world scale
![image](https://github.com/sboxgame/issues/assets/28588188/8a18bfed-a825-4695-8848-3459a3f3b754)

### To Reproduce

create a game with a viewmodel.
look at the shadows on the model.

### Expected behavior

the shadows should be more like this:
![image](https://github.com/sboxgame/issues/assets/28588188/a58c38ff-170b-4815-9d08-94c584d31481)
 (achieved by scaling the model up 4.8 times)

**Comment by samzanemesis** [comment]
we merged the new system, have a try
