### ISSUE TITLE
Entities have laggy movements if Inspector is open and a Pawn is selected

### ISSUE THREAD

**Issue by Gmod4phun** [sboxgame/issues#3353]
### Describe the bug

When the Inspector is open and a Pawn is selected, entities appear to have laggy movements.

The first video shows the problem while dragging the entities using the physgun. The second video shows the entities moving around freely, but the laggy movement is still there, although might be a bit harder to notice.

### To Reproduce

1. Open Inspector
2. Select a Pawn
3. Move some objects and see their movements

### Expected behavior

Movement should be lag free.

### Media/Files

https://github.com/sboxgame/issues/assets/5991682/fee02447-f67c-447e-9966-8e2c54047ba1

https://github.com/sboxgame/issues/assets/5991682/921bbf89-a13b-430c-90a7-b3cd5473c8fb

**Comment by Weldify** [comment]
If you open a parented entity in the inspector, it starts spinning uncontrollably too.
