### ISSUE TITLE
Breakable props sometimes throw a NRE during collision

### ISSUE THREAD

**Issue by Gmod4phun** [sboxgame/issues#3365]
### Describe the bug

I can't get this to reproduce, or more like, I am not sure precisely when it happens. I think it happens when the breakable prop breaks and gets deleted by another action at the same time.

![image](https://github.com/sboxgame/issues/assets/5991682/c275a001-7c67-42a1-9add-601c362f5015)

### To Reproduce

Literally no idea

### Expected behavior

Probably shouldn't error

**Comment by robotboy655** [comment]
Is this still a problem for you? I am not sure what that `DMD<` bit is on your screenshot or why your stack trace looks different to how it should look:
![image](https://github.com/sboxgame/issues/assets/3299036/0a0478ce-7eaa-4606-a792-7691abeee0cd)
 
Specifically it would be very useful to have stack trace with line numbers so I know where the issue actually happens.

**Comment by Gmod4phun** [comment]
Honestly, I have no idea under what conditions precisely it happens. I will try and see if I can reproduce it consistently and let you know.

**Comment by robotboy655** [comment]
Does it happen to you at all since you first reported it? What gamemode does it happen in?

**Comment by Gmod4phun** [comment]
My Stargate gamemode, if I remember correctly, it happened when I was launching objects at high velocity with the box shooter and they broke right before they were about to teleport. It can probably happen in other gamemodes if the right conditions are met.

**Comment by Gmod4phun** [comment]
I can't get this to reproduce, so maybe it got fixed a while back. I will close this and if it happens again, I will make a new issue.

I do however have another issue regarding water and breakable props, opened that just now.
