### ISSUE TITLE
Creating images from in-game created textures

### ISSUE THREAD

**Issue by timmybo5** [sboxgame/issues#3367]
### For?

S&Box

### What can't you do?

I would like to create images from a scenepanel's texture (`ScenePanel.RenderTexture`) but right now it is not possible getting the binary data of the texture.

Right now using a bunch of scenepanels drains performance (even with RenderOnce), what would be better is to dynamically generate all the textures needed and save them to disk.

It would also be very useful having a s&box match to `https://wiki.facepunch.com/gmod/render.Capture`.

### How would you like it to work?

Getting the binary data or a helper function to save a texture to disk.

**Comment by handsomematt** [comment]
Texture.GetPixels
