### ISSUE TITLE
Whitelist certain file formats to save inside of mounted addon path

### ISSUE THREAD

**Issue by timmybo5** [sboxgame/issues#3368]
### What it is?

Right now it is impossible to save in your own addon's path, this could be very useful for gamemodes that use in-game tools to generate configs that should be shipped with the gamemode.

This functionality could be restricted to certain file formats like .json or .txt

**Comment by handsomematt** [comment]
This is what Filesystem.Data is for?

**Comment by DoctorGurke** [comment]
Are you asking about saving in one project's filesystem from another? Org data could help but tools can't access that last I checked #2635

**Comment by timmybo5** [comment]
@handsomematt I mean saving in `sbox\addons\mygamemode\afolder\data.json` instead of `sbox\data\mygamemode\data.json`. As far as I know we can only write to the data folder unless that changed.

**Comment by handsomematt** [comment]
Not gonna happen sorry, should just be done with an actual tool.
