### ISSUE TITLE
Trace.WorldOnly also hits entities, but it should not

### ISSUE THREAD

**Issue by Gmod4phun** [sboxgame/issues#3372]
### Describe the bug

When running a Trace with `WorldOnly`, it also hits entities, despite the name and description saying it shouldn't. Using a trace with `WithTag("world")` instead properly ignores entities.

### To Reproduce

1. Run a WorldOnly trace towards an entity
2. See it hit the entity, even when it shouldn't

### Expected behavior

Should not hit entities, but only world

**Comment by handsomematt** [comment]
![image](https://github.com/sboxgame/issues/assets/1388267/deef5922-b544-474b-9bb0-97584da7bf83)

What sort of entities is it hitting for you?

**Comment by Gmod4phun** [comment]
It seems to be hitting my custom entities (Stargates, DHD's, Rings) that are derived from Prop. It seems to ignore regular props (the crate, the rings props), and also entities whose physics are sleeping (such as the Stargate that was leaning on the wall). Here is the video showing the issue:
https://www.youtube.com/watch?v=3gAFTE8NRGA

**Comment by handsomematt** [comment]
I see you're setting your entities with `PhysicsBody.BodyType = PhysicsBodyType.Static;`

I think Trace.WorldOnly actually means StaticOnly and EntitesOnly means DynamicOnly, I'll have a think about changing these, if you do want to check world specifically the "world" tag is probably the best way.

**Comment by Gmod4phun** [comment]
That sounds plausible. In that case it probably would be wise to rename WorldOnly to avoid any confusion.
