### ISSUE TITLE
ShaderGraph: Nodes are fetched from all assemblies in the TypeLibrary

### ISSUE THREAD

**Issue by peter-r-g** [sboxgame/issues#3375]
### Describe the bug

Right now any types that derive from `BaseNode` in any tools are used by the ShaderGraph. This becomes a problem when you are creating graph nodes for a completely different tool.

### To Reproduce

1. Create a tool
2. Create a type that derives from `BaseNode`
3. That node will now appear in the ShaderGraphs palette and "Create Node" menu.

### Expected behavior

For unrelated types deriving from `BaseNode` to not be added to the ShaderGraph.

**Comment by aylaylay** [comment]
It will now only find nodes derived from ShaderNode

**Comment by peter-r-g** [comment]
The Palette widget still fetches all nodes from TypeLibrary
`IEnumerable<IGrouping<string, DisplayInfo>>.GetItems L#58`

**Comment by aylaylay** [comment]
Woopsie
