### ISSUE TITLE
Namespaces on https://asset.party/api/ throw errors.

### ISSUE THREAD

**Issue by LiminalCrab** [sboxgame/issues#3383]
### Describe the bug

Attempting to access the namespaces on https://asset.party/api/ such as https://asset.party/api/Sandbox.Engine redirects you to an error page.

### To Reproduce

Go to any namespace on the API page: https://asset.party/api/System.Collections.ObjectModel 
https://asset.party/api/Sandbox.UI
https://asset.party/api/Sandbox.Bind

ect

### Expected behavior

The website should render related information to that namespace.

**Comment by DevulTj** [comment]
This should be sorted now, thank you for reporting this issue 👍🏻
