### ISSUE TITLE
Gamepad controller input completely stopped working (Dualshock 4)

### ISSUE THREAD

**Issue by Phyksar** [sboxgame/issues#3390]
### Describe the bug

The game has no response to any gamepad action, I'm testing primarily with the default Sandbox game mode. The only thing that's responding is Steam Input s&box controller layout window which is accessible via input settings. I'm using Dualshock 4 connected with Bluetooth with Steam Input emulation enabled, I have no such problem running any other game. I tried reinstalling S&box but that had no effect, I also tried using DS4Windows emulation to create virtual Xbox controller - that didn't work too.

### To Reproduce

1. Connect Dualshock 4 controller
2. Enable Steam Input in S&box Steam game properties
3. Launch S&box and go to `Settings` > `Input` > `Configure PS4Controller`
4. Select and apply `Official Layout for s&box`
5. Start a Sandbox game, try moving around with controller

### Expected behavior

I expect that gamepad controls should be working, they have been working some time ago, moreover a post mentioning gamepad controls came out recently - [Input Actions | Controller Support](https://sbox.facepunch.com/news/input-actions#ControllerSupport), and none of that I can experience myself, this is very confusing.

### Media/Files

![2023-06-05 21_22_12-Window](https://github.com/sboxgame/issues/assets/13320416/e88d987a-8113-4527-ab21-d98758c4e052)
![2023-06-05 21_23_01-Window](https://github.com/sboxgame/issues/assets/13320416/b6fa0412-5db5-421a-9c50-0f0e8a80d0a4)
![2023-06-05 21_28_57-Window](https://github.com/sboxgame/issues/assets/13320416/871071a0-d5c4-496f-a394-64c81b649203)
![2023-06-05 21_29_11-Window](https://github.com/sboxgame/issues/assets/13320416/f4aa1beb-83d1-40d2-b14d-97241e0fbad9)

**Comment by DevulTj** [comment]
yeah I've noticed this too

**Comment by Phyksar** [comment]
@DevulTj so is this issue being in the process of resolving or the gamepad support is being dropped compeletely by now?

**Comment by DevulTj** [comment]
Resolved

**Comment by Phyksar** [comment]
@DevulTj thank you
