### ISSUE TITLE
Support implicit usings

### ISSUE THREAD

**Issue by verdie-g** [sboxgame/issues#3392]
### For?

S&Box

### What can't you do?

Since we don't control the csproj we can't use [implict usings](https://devblogs.microsoft.com/dotnet/welcome-to-csharp-10) which is handy to avoid repeating the same usings in all files.

### How would you like it to work?

Add
```xml
<ImplicitUsings>enable</ImplicitUsings>
```
to the generated csproj.

It could make sense to also add
```xml
<Using Remove="Sanbox" />
```

### What have you tried?

I've tried creating my own csproj but it seems like it's not something that will be supported: https://github.com/sboxgame/issues/issues/3363.

**Comment by ItsRifter** [comment]
You can just do this in the game class or in a separate one (or wherever).
``
global using [namespace]
``

that'll use the namespaces in that project and only that.

**Comment by verdie-g** [comment]
That's indeed a good work-around. Though I would say the `ImplicitUsing` property still add some value.

**Comment by DevulTj** [comment]
I still don't see much use for supporting implicit usings. As @ItsRifter suggested, make a file, stick a bunch of global usings in there, and then never worry about it again.
