### ISSUE TITLE
RootNamespace harcoded to Sandbox

### ISSUE THREAD

**Issue by verdie-g** [sboxgame/issues#3393]
### For?

S&Box

### What can't you do?

The generated csproj has a hardcoded `RootNamespace` which create confusion to know if a type, given its full name, is coming from the current project or from the base library. Also since the base library is part of the generated sln, it's easy to jump on a file that is not from your project and not realizing it by reading the namespace keyword since you probably use `namespace Sandbox` everywhere.

Additionally, when you create a new file using an IDE (VS or Rider) it will generate a file with a `namespace Sandbox` which is not what you want, and depending on the IDE, it may also raise a warning `Namespace does not correspond to file location, must be: 'Sandbox'`.

### How would you like it to work?

In my opinion, `AssemblyName`, `PackageId`, and `RootNamespace` should not be specified but we should rely on the csproj name so the consistency between those four is guaranteed.

Now it means having a correctly generated csproj name. Currently it's generated from the `Title` which can contains spaces and special characters, also it's sometimes that can change over time so it's probably not the way.

A better way would be to use the `Ident` which shouldn't not have all the problems mentioned for the title. However, it seems like the convention is to use camelCase when the convention in .NET is PascalCase so it could raise some warnings and it would not be super clean.

The safest way would be to add an `AssemblyName` property in the `.addon` file that would be used as the csproj name.

### What have you tried?

I've tried creating my own csproj but it seems like it's not something that will be supported: https://github.com/sboxgame/issues/issues/3363.

**Comment by DoctorGurke** [comment]
you can change the root namespace in project settings

**Comment by verdie-g** [comment]
Indeed, thanks.
