### ISSUE TITLE
SCSS stacking filter effects doesn't work.

### ISSUE THREAD

**Issue by dch-GH** [sboxgame/issues#3403]
### Describe the bug

Can't use multiple filter effects on an element at once.

### To Reproduce

What works:
```
filter: blur(20px);
```

What doesn't work:
```
filter: blur(20px) saturate(200%) brightness(50%);
```

### Expected behavior

To stack multiple filter effects on an element.

**Comment by xezno** [comment]
Hey, this should be fixed on next build, let me know if there's any more problems with this.
