### ISSUE TITLE
Sound.Stop() doesn't work.

### ISSUE THREAD

**Issue by dch-GH** [sboxgame/issues#3404]
### Describe the bug

Try to stop a sound, it doesn't stop.

### To Reproduce

```cs
using Sandbox;

public partial class MyGame : GameManager
{
	private Sound snd;
	private RealTimeUntil stopTheSound;

	public MyGame()
	{
		stopTheSound = 3;
		snd = Sound.FromScreen( "sounds/diagnostics/counting_120.sound" );
	}

	public override void Simulate( IClient cl )
	{
		if ( stopTheSound )
		{
			Log.Info( "Stopping the sound." );
			snd.Stop();
		}
	}
}
```

### Expected behavior

The sound should stop playing but it doesn't.

**Comment by CarsonKompon** [comment]
I noticed that other functions like SetVolume also don't work, I thought I had broke everything 😅

**Comment by kurozael** [comment]
This should be sorted for the next build - including SetVolume etc. Let me know if you have any further issues 👍

**Comment by dch-GH** [comment]
Fixed, thank you!
