### ISSUE TITLE
Allow developers to access avatar (clothing) data in the menu

### ISSUE THREAD

**Issue by trundlr** [sboxgame/issues#3407]
### For?

S&Box

### What can't you do?

Currently, there is no way to access avatar/clothing data in the menu. Client is rightfully not instantiated in the menu, but there is no other way to get this information as far as I can see.

### How would you like it to work?

Either through a convar, or expose the information through the API.

### What have you tried?

.

**Comment by DevulTj** [comment]
This is now possible w/ ConsoleSystem.GetValue
