### ISSUE TITLE
Implement .opus support for sounds

### ISSUE THREAD

**Issue by Retroeer** [sboxgame/issues#3411]
### For?

S&Box

### What can't you do?

Currently, you're unable to use files encoded with opus as a sound in s&box

### How would you like it to work?

It would functionally be identical to .mp3 support, just, y'know... .opus

### What have you tried?

Put two of the same sounds together, one as .opus the other as .mp3, s&box would only register the .mp3 as a viable sound.

### Additional context

The opus codec is royalty free and open source, capable of providing mp3 sounding quality at nearly half the file size, this would be an incredible tool to have as file size is important in a game like s&box, even more so when working with a main menu, where looking good and being of a reasonable size are critical factors.

**Comment by aylaylay** [comment]
The engine compiles it's own resource for sounds, wav, mp3 etc are only used at compile time so this wouldn't reduce any file size. It would only give you another option to compile sound from and because no one really exports opus, it wouldn't be useful to support.
