### ISSUE TITLE
SCSS: Add Support for "background-blend-mode" Property

### ISSUE THREAD

**Issue by rndtrash** [sboxgame/issues#3412]
### For?

S&Box

### What can't you do?

I can't do cool effects on background images.

### How would you like it to work?

I'd like it to work as described in the MDN documentation: https://developer.mozilla.org/en-US/docs/Web/CSS/background-blend-mode.

### What have you tried?

```css
background-blend-mode: multiply, normal;
```
```
 03:02:08   Generic Unknown Property: background-blend-mode / multiply, normal
 03:02:08   GameMenu /ui/menu/../common/common.scss: multiply, normal is not valid with background-blend-mode
 ```

**Comment by xezno** [comment]
Should be implemented in next build. Do note that we only support normal, lighten, and multiply right now - other blend modes will be implemented after the Vulkan merge.
https://files.facepunch.com/alexguthrie/1b1311b1/sbox-dev_K5OMPBk2v6.png
