### ISSUE TITLE
ClientDisconnect not called on shutdown

### ISSUE THREAD

**Issue by yikegaming** [sboxgame/issues#3417]
### For?

S&Box

### What can't you do?

When a client leaves the game, BaseGameManager.ClientDisconnect is called, which is right obviously, but when the server is shut down, that same method isn't called, despite the console saying `CL:  disconnect`. and there is a NetworkDisconnectionReason enum called SHUTDOWN which would imply this should be called on server shutdown, but it's not. This means that when the server is shutdown I can't perform any actions with the clients, such as saving information

### How would you like it to work?

I just want ClientDisconnect to be called when the server is shutdown

### What have you tried?

I tried accessing the clients through BaseGameManager.Shutdown but by the time that is called all the clients have already been disconnected so I can't use any information.

**Comment by anthonysharpy** [comment]
in my experience this also doesn't get called if the client crashes, but i could be wrong about that
