### ISSUE TITLE
Asset Party's API Reference not working

### ISSUE THREAD

**Issue by xhayper** [sboxgame/issues#3418]
### Describe the bug

The API reference site is not working at all

### To Reproduce

1. Navigate to https://asset.party/api

### Expected behavior

The API reference site should works

### Additional context

I am using Firefox 114.0.1

**Comment by trende2001** [comment]
a certain individual made an organization called "api", therefore it just broke cause it's running into a conflict

**Comment by Gmod4phun** [comment]
Probably would be wise to have it as orgs/org_name

**Comment by yuberee** [comment]
> a certain individual made an organization called "api", therefore it breaks cause it's running into a conflict

Hey! We at Arcade Interactive Productions (API) have had the ident "api" for at least a year, we're sorry for the conchfusion.

**Comment by NotGaylien** [comment]
unfortunately we had to rebrand to a different name because of an issue with our org page being stolen by this other api thing...

**Comment by trende2001** [comment]
> > a certain individual made an organization called "api", therefore it breaks cause it's running into a conflict
> 
> Hello, we at Arcade Productions Interactive (API) have had the ident "api" for at least a year, we're sorry for the conchfusion.

No problem. I thought it was the organization that broke the API page...........

**Comment by garrynewman** [comment]
Fixed
