### ISSUE TITLE
Game.LocalClient and Game.LocalPawn return null in Pause Menu

### ISSUE THREAD

**Issue by CarsonKompon** [sboxgame/issues#3419]
### Describe the bug

`Game.LocalClient` and `Game.LocalPawn` return null from an `IGameMenuPanel` even when checking if `Game.InGame`.

### To Reproduce

1. From your main menu (implements `IGameMenuPanel`), try something such as
```cs
if(Game.InGame)
{
    Log.Info(Game.LocalClient);
}
```

2. Load into your game and then press ESC to open the Pause Menu. The console will spit out `null`

### Expected behavior

I would expect to be able to retrieve the LocalClient and LocalPawn so that you could display things like client information from your game's pause menu.

**Comment by Sp00n3xJR** [comment]
I don't think you are able to access any game code from the game menu side yet. I wanted to add a warning before pressing a "leave game" button in my game menu if a match was on-going, but GameManager.Current returns null in the game menu even if we are in-game.

Would be cool to get some game access here too ^^

**Comment by Weldify** [comment]
Facepunch already declined a similar issue I made but I just want to say again that it would be really nice if we could access `Game.LocalClient` from the menu too.

**Comment by CarsonKompon** [comment]
I don't think there's much reason in the menu (unless I'm just not thinking of other use cases). What more information are you looking to get than `Game.SteamId` and `Game.UserName`?

**Comment by Weldify** [comment]
Would just be nicer to always have access to `LocalClient`. No extra properties, you access `LocalClient` both in game and the menu. Just makes the API nicer imo.

**Comment by PolSpock** [comment]
> I don't think there's much reason in the menu (unless I'm just not thinking of other use cases). What more information are you looking to get than `Game.SteamId` and `Game.UserName`?

In my case, i have a game with Rounds (and Timers for each of the rounds).
I recently moved all my settings from Game State into the GameMenu state.

I used `Game.LocalClient.IsListenServerHost` in my Settings Panel to display and edit Rounds Timer only for the host, like this :
```
if (Game.LocalClient.IsListenServerHost)
{
	Setting.GetRoundsTimers();
}
```
but i can't use it anymore in GameMenu state cause Game.LocalClient is null

**Comment by kebabulon** [comment]
This is also useful if you have an Inventory system something like TF2's
You would want this inventory system to be accessible in the main menu as well as the game.
Something happens in game -> Item drop happens -> The item is sent to the menu and added to the inventory.

I am currently working on a hat system myself so this issue really effects me lol.
