### ISSUE TITLE
Assets used in loading screens do not download from cloud, even if path is specified in Menu Files

### ISSUE THREAD

**Issue by Gmod4phun** [sboxgame/issues#3420]
### Describe the bug

Trying to make a loading screen with some models, but they don't get downloaded. I guess it's because it does not download the vmdl_c, but the vmdl instead, and the game does not seem to compile that.

The path to the models and materials is specified in the Menu Files list:
![image](https://github.com/sboxgame/issues/assets/5991682/6a96eb34-c356-4d87-b1a2-0e79e4e34cac)

What it should look like:
![image](https://github.com/sboxgame/issues/assets/5991682/63c7373b-efd1-4e24-9d95-9f048dfd8ba3)

What it looks like when loading the game from cloud:
![image](https://github.com/sboxgame/issues/assets/5991682/1cc6f390-2128-4d16-add0-5f726354badb)

### To Reproduce

1. Use custom models in loading screen
2. Add the paths of the assets to Menu Files
3. Upload game to cloud
4. Load game

### Expected behavior

Models and materials (probably all kinds of specified assets) should download from cloud properly.

**Comment by CarsonKompon** [comment]
You must specify `*.vmdl_c` specifically. Which is odd because those file types don't show on the right. Would be nice if using `*.vmdl` would automatically recognize `*.vmdl_c` files

**Comment by Gmod4phun** [comment]
Thanks for that. Indeed, specifying `vmdl_c`, `vmat_c `and `vtex_c` made it work. I think this step should be automatic and once specifiying a vmdl, all assets used by that (materials, textures) should get downloaded, too. The worst part about this is that you have to upload to cloud, disable the project locally, restart the game to clear cached assets and then check if the cloud version works as intended, which is very tedious. I'll make another issue since this is now resolved.
