### ISSUE TITLE
A base pawn class for classic Source Engine movement

### ISSUE THREAD

**Issue by Sam54123** [sboxgame/issues#3430]
### For?

S&Box

### What can't you do?

I reckon many of the gamemodes in S&Box will be centered around FPS, and because it's Source 2, people will expect it to feel consistent. An optional, "stock" FPS pawn with Source Engine controls will help with this consistency, as well as making the development of FPS games more streamlined. Most game engines already have this, and with S&Box's creator-focused nature, it doesn't make sense *not* to have one.

### How would you like it to work?

A C# class that derives from `AnimatedEntity` should be provided in the base game or in an official library. This class would take care of all player movement physics, and programmers could use it directly or make a subclass of it.

### What have you tried?

I've tried using the various "FPS Base" addons from Asset Party, as well as writing my own system. They always feel rather janky and lack the nostalgic Source Engine feel we're all used to.

### Additional context

This isn't an "essential" feature, but it would make a lot of people's lives easier, as well as improving the baseline quality of content.

**Comment by DevulTj** [comment]
We have no plan of packing a stock fps pawn like this - we might release a template, or the community will. We have some plans about allowing for project templates on asset.party which will make discoverability for community templates nice and easy.
