### ISSUE TITLE
Servers don't get named properly

### ISSUE THREAD

**Issue by Weldify** [sboxgame/issues#3432]
### Describe the bug

Starting a server with menu API doesn't respect the specified name:
![image](https://github.com/sboxgame/issues/assets/66477673/0535c749-90a5-4688-b7aa-9dcaa5d33527)
![image](https://github.com/sboxgame/issues/assets/66477673/9b80a4b7-33ad-4c59-8df1-36190da2950f)

### To Reproduce

1. Create a named server with the menu API
2. The name won't be correct

### Expected behavior

Servers should start with the correct name

**Comment by GerardRey** [comment]
And if you remove the Game.UserName does it work for you? Testing such as Test Server or also Weldify's Server

I don't have an s&box key to test this error, but let's see if this helps you

**Comment by DevulTj** [comment]
This should be sorted when the next game build hits steam
