### ISSUE TITLE
Override individual materials of a model aka SubMaterial

### ISSUE THREAD

**Issue by Gmod4phun** [sboxgame/issues#3435]
### For?

S&Box

### What can't you do?

Currently, we can't override a specific individual material of a model by its name, we can only override all of the materials, or those with a specific User Attribute. The problem is that we can't replace a single material unless it has an user attribute, and even then, there can be multiple materials with the same attribute, which would result in replacing all of them, even if we want to replace only one.

The specific use case here is to replace the Material of a TV/Monitor screen of a custom cloud model.

### How would you like it to work?

Similiar to the existing `SetMaterialOverride`, there could be a `SetSubMaterialOverride` that takes in the name of the material to replace, and then the new material to replace it with.

### What have you tried?

Tried the above mentioned methods, but they can't be used to replace just a single material unless it has custom user attributes (which they most often don't, as is the case with most cloud models).

**Comment by Nebual** [comment]
I discovered a workaround to achieve this:
```
var mats = modelEnt.Model.Materials.ToList();
for ( int i = 0; i < mats.Count; i++ ) {
	mats[i].Attributes.Set( "materialIndex" + i, 1 );
}
modelEnt.SetMaterialOverride( Material.Load( material ), "materialIndex" + materialIndex );
modelEnt.SceneObject?.SetMaterialOverride( Material.Load( material ), "materialIndex" + materialIndex, 1 );
```
Its super awkward and unergonomic, but implies this should be a pretty straightforward thing to add to the API.

I'll also note that ModelEntity.SetMaterialOverride does not have a signature that lets you filter by the attribute value, yet ModelEntity.SceneObject.SetMaterialOverride _does_ have an `attributeValue` parameter.

Also, from my experimentation, `ModelEntity.SetMaterialOverride` does not immediately take effect, but seems to require me to touch/interact with the prop before it updates. `ModelEntity.SceneObject.SetMaterialOverride` _does_ immediately take effect, but is temporary (eg. touching the prop clears it). So I'm going to run both...
