### ISSUE TITLE
Uploading new video does not update background image on asset.party

### ISSUE THREAD

**Issue by CarsonKompon** [sboxgame/issues#3436]
### Describe the bug

After deleting the old background image video I had on asset.party, I uploaded a new one and re-selected "Use As Background". The video shows up on https://asset.party/carsonk/home but if you hover over the icon at https://asset.party/t/game/newest?q=home then it will play the old video (it also plays the old video in-game on the menu)

### To Reproduce

1. Delete a video set as the background
![image](https://github.com/sboxgame/issues/assets/5159369/db3e017c-6ad1-4bcf-9eb0-414ae2ee7995)

2. Upload a new video and set it as the background after it has finished processing
![image](https://github.com/sboxgame/issues/assets/5159369/a25ef46d-9c8e-4ac0-aaf6-ae9bf92cd085)

### Expected behavior

The new video should appear. This is likely a cache or something but I think that cache should be flushed if the video is outright removed.

**Comment by CarsonKompon** [comment]
![image](https://github.com/sboxgame/issues/assets/5159369/0d81ad18-1d34-404b-86e2-2164f262d7e3)
This most recent commit does solve the issue, but it's worth noting I had to un-check "Use As Background" and re-check it to get it to do so.

**Comment by garrynewman** [comment]
Yep that is expected, just needs to reindex
