### ISSUE TITLE
Support OpenTelemetry

### ISSUE THREAD

**Issue by verdie-g** [sboxgame/issues#3445]
### For?

S&Box

### What can't you do?

This is not high priority but at some point we will need to collect some telemetry about our game, for example the number of connected players. I'm not sure about the use-case of other telemetry signals such as traces so I'll focus on metrics here.

### How would you like it to work?

.NET 6+ has a built-in [OpenTelemetry](https://opentelemetry.io) API under [System.Diagnostics.Metrics](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.metrics) so you could just whitelist that.

For sending the metrics you need to use the OpenTelemetry SDK (nugets OpenTelemetry*). You might want to initialize the SDK yourself with a Grpc OpenTelemetry protocol and only allow us to choose the endpoint to send the data too. That will allow us to send the metrics to a Grafana or Datadog agent.

For the logs I haven't checked but I suppose they can be written to a file so our telemetry agent could already collect them.

### What have you tried?

N/A

**Comment by garrynewman** [comment]
We will be adding an API for this in the distant future, it is on the roadmap
