### ISSUE TITLE
Extreme lag when getting too close to prop_animated

### ISSUE THREAD

**Issue by sugmagaming** [sboxgame/issues#3447]
### Describe the bug

When you get too close to a prop_animated it lags.

https://github.com/sboxgame/issues/assets/15720147/623873f4-6277-4699-9411-12f9658ef002

### To Reproduce

1.Go on sugmagaming.nuketown
2.Admire the beauty.
3. Go to the animated rotating fan in one of the houses on the first floor.
4. Get close to it
5. Lag

### Expected behavior

Don't lag.

**Comment by anthonysharpy** [comment]
also get this

**Comment by eEight-dev** [comment]
Did some testing related to this: It seems that the one that's most affected by this is the server host (both in frame drops and server lag). A player (that isn't the server host) who causes this by looking at the fan doesn't get any frame drops but can feel the server lag.

**Comment by aylaylay** [comment]
I'm not sure I'd consider this a bug. The model has a stupid amount of triangles in the collision mesh, the player has a bunch of collision triggers that are going to intersect it, bad performance is bound to happen. It's important to optimize your collision.
![sbox-dev_ne0UaVIScq](https://github.com/sboxgame/issues/assets/1667289/0be2cb3d-b7b3-4325-a8d5-254b3ec76e9c)
This model should have a collision model of a box, or a simple convex volume.

**Comment by sugmagaming** [comment]
You were right. Changing the collisions to a physbox fixed this issue. Thank you very much.
