### ISSUE TITLE
Http.RequestAsync not working when game/library deployed to asset.party

### ISSUE THREAD

**Issue by CarsonKompon** [sboxgame/issues#3448]
### Describe the bug

After making a `Http.RequestAsync` call you will be met with zero issues when running the game locally. However, if you upload that game to asset.party, you will be met with the following error:
![image](https://github.com/sboxgame/issues/assets/5159369/22e50394-85b8-491a-b5c5-59898d232a15)

This also happens if you contain that code within a library and reference that library though Package References.

### To Reproduce

1. Add "https://www.youtube.com/" to the Http Allow List for your game
2. Run the following code in an async function:
```cs
var response = Http.RequestAsync("POST", "https://www.youtube.com/youtubei/v1/player");
```
3. Try running it locally, and see that you get a response.
4. Try uploading to asset.party, and see that you get the same `Exception waiting for task to finish` error pictured above.

Here's a link to the exact line that's causing me issues from a library that I've already uploaded to asset.party: https://github.com/CarsonKompon/sbox-mediahelpers/blob/48884f6c7d7cdeaf05288e7378a3d08431289b07/code/MediaHelper.cs#LL102C1-L102C2

### Expected behavior

Behave how it does when testing locally

**Comment by CarsonKompon** [comment]
Okay I made a pretty large discovery regarding this issue:

I was under the impression that if the game was uploaded to asset party then playing it would not allow you to make Http requests. This turns out to be incorrect, you CAN in-fact make Http reqeusts...**AS THE HOST**... Meaning if you host a game, you (the host) are able to make Http requests from your client, but **anyone else** who connects to your server is NOT.

When it comes to dedicated servers (which is what I had been testing on the entire time) it just means NO clients can make Http requests.

I believe Matt has said this is because of the Http Allow List being improperly fetched, and if that is the case, it is only Clients who are unable to fetch this list.

**Comment by chrisspieler** [comment]
That's the behavior we've seen in: https://github.com/sboxgame/issues/issues/3366

Until this issue is fixed, I don't think we can actually play videos from the internet on Cinema servers unless we use a WebSurface.

**Comment by garrynewman** [comment]
The http whitelist is dumb and we should just enable logging of http requests and allow any fully qualified domain name to be accessed. 

Show me some thumbs up or thumbs down.

**Comment by CarsonKompon** [comment]
> The http whitelist is dumb and we should just enable logging of http requests and allow any fully qualified domain name to be accessed.
> 
> Show me some thumbs up or thumbs down.

How would this work for addons such as mediaplayers? Do those requests get logged to the addon, the gamemode or both?
