### ISSUE TITLE
Change the default missing material texture to a non see-through one

### ISSUE THREAD

**Issue by KayaDLX** [sboxgame/issues#3449]
### For?

S&Box, Hammer

### What can't you do?

Currently in s&box, the default missing material is a red flashing wireframe texture which allows you to see through the map.

While this worked fine for games like Half-Life: Alyx that are solo, s&box has multiplayer and this can be used to grief games.
E.g you play a competitive game on s&box, you just remove half of your materials in your download folder, then you can literally see everything that's happening behind walls and such.

![image](https://github.com/sboxgame/issues/assets/67245359/67da4eb4-85d3-460f-b480-94625562520d)

### How would you like it to work?

Counter-Strike 2 changed the default missing material texture to a non see-through red flashing checkerboard texture, we could use something like that. Also this is far more useful when working in Hammer in case you're missing textures, the wireframe makes it hard to understand what's going on if you have a lot missing.

![image](https://github.com/sboxgame/issues/assets/67245359/c6331bb3-a6ea-474b-9b70-9c07bec87e96)

### What have you tried?

N/A

**Comment by handsomematt** [comment]
Should be the same as CS2 now

**Comment by KayaDLX** [comment]
Oh thank you so much that's awesome
