### ISSUE TITLE
Crash To Desktop When Starting Gamemode In Editor

### ISSUE THREAD

**Issue by anthonysharpy** [sboxgame/issues#3450]
### Describe the bug

whenever i try to start my gamemode in the editor i crash to desktop

steam id: 76561197997412036

### To Reproduce

can send gamemode files if needed

### Expected behavior

doesn't crash

### Additional context

tried verifying files

can't see anything helpful in /logs/

i was messing around with worldpanels when it started happening but idk if that's actually the cause since even if i remove all that it still crashes

**Comment by handsomematt** [comment]
your crash was on a release just before one intended to fix a crash, can you try again making sure your game is updated?

**Comment by anthonysharpy** [comment]
still getting it after restarting steam and verifying a few times, but will keep trying 😃

**Comment by anthonysharpy** [comment]
hmm still getting this. have tried updating nvidia drivers and seems to be same issue. it was last working today in the early afternoon (BST) sometime, not sure exactly when it broke tho

**Comment by anthonysharpy** [comment]
this seems to be fixed now, hopefully it is fixed for you too @DaddyFrosty 😃 

thanks

**Comment by DaddyFrosty** [comment]
unfortunately not... Will have to make a new issue
