### ISSUE TITLE
Game crashes when using Graphics.RenderToTexture when not in Editor

### ISSUE THREAD

**Issue by CarsonKompon** [sboxgame/issues#3452]
### Describe the bug

When using `Graphics.RenderToTexture` to render a SceneCamera to a Texture, the game will throw the following error when not running sbox-dev.exe:
![image](https://github.com/sboxgame/issues/assets/5159369/8a87fd63-470f-4127-8d4b-8ea8ab97d201)
```
CSceneSystem::BeginRenderingViews():
Begin has already been called without an intervening renderer
```
Tested Graphics Cards:
1070 - crashes ❌
2080Ti - ok ✅
3070 - crashes ❌
3070Ti - crashes ❌
3090 - crashes ❌
4070 - crashes ❌

### To Reproduce

Here is the function I am calling that causes the crashes:
```cs
public static Texture CreateModelThumbnail(string modelString, int size = 96)
{
    float scalar = 3f;
    Model model = Model.Load(modelString);
    Texture texture = Texture.CreateRenderTarget()
                    .WithHeight(size).WithWidth(size)
                    .Create();
    var scene = new SceneCamera();
    scene.AntiAliasing = true;
    scene.World = new SceneWorld();
    scene.FieldOfView = 10;
    var maxBound = model.Bounds.Size.Length;
    var dist = (maxBound / scalar) / MathF.Tan(MathX.DegreeToRadian(scene.FieldOfView / 2));
    
    SceneObject obj = new SceneObject(scene.World, model, Transform.Zero);
    var box = (obj.Bounds.Mins + obj.Bounds.Maxs) / 2;
    scene.Position = new Vector3(1, 1, 0.9f) * dist;
    scene.Rotation = Rotation.LookAt(-1 * (scene.Position - box).Normal);
    var light = new SceneLight(scene.World, new Vector3(32, 128, 128), 1024, Color.White);
    light.LightColor = Color.White.Lighten(2);
    light.ShadowsEnabled = true;
    scene.AmbientLightColor = Color.White.Darken(0.5f);

    Graphics.RenderToTexture(scene, texture);
    obj.Delete();
    scene.World.Delete();
    return texture;
}
```

But removing the following line prevents all crashes from happening (and obviously prevents the function from doing what it's intended to do):
```cs
Graphics.RenderToTexture(scene, texture);
```

You can experience the crash for yourself by loading into my "Home" game and speaking to one of the shop NPCs as it will try to create the item thumbnails by calling that function

### Expected behavior

The game should not crash and instead render the texture :)

### Additional context

The error message is a Source 2 error message presumably since googling the error returns results for the same error in Dota 2.

**Comment by SilentlessVoid** [comment]
Nvidia P4 - ✅
1050 ti (Double checking)
Nvidia P40 - crashes ❌
Nvidia M40- crashes ❌

**Comment by MuffinTastic** [comment]
RTX 4080 ✅
tested in both normal and dev/editor modes
commit bbe9ef

**Comment by CarsonKompon** [comment]
Okay so it actually seems that Graphics.RenderToTexture was not to blame here. I think what is to blame is the fact that the function was called in a getter as the texture was needed instead of being made in advance. I will try to find out how to easily reproduce later but closing this issue until then.

**Comment by PolSpock** [comment]
Hello,

I was encountering the same issue, after a discussion with Ceitine & Carson) on [discord](https://discord.com/channels/833983068468936704/902501842724978699/1154005597956620330) the way to fix this issue is to use a Render block
So basically do the logic in https://asset.party/api/Sandbox.UI.Panel.DrawBackground(RenderState)

Thx :)
