### ISSUE TITLE
Joining one of the games in the Servers List will not show the loading screen of said game

### ISSUE THREAD

**Issue by trende2001** [sboxgame/issues#3455]
### Describe the bug

People who use the server list daily aren't aware if they are loading into the game or not whenever they click on the server they want to join. It simply does not show them the loading screen of the game.

Results in people thinking that the joining doesn't work, so they start aggressively clicking trying to get in

### To Reproduce

1. Go to the server list in the s&box menu
2. Click on one of the servers
3. You are joining the game, but there is no loading screen

### Expected behavior

Download and load the loading screen (funnily enough) first before actually letting you join in. Less confusion

**Comment by trundlr** [comment]
This also occurs from the config launcher in the editor.

**Comment by trende2001** [comment]
bump

**Comment by trende2001** [comment]
@DevulTj fixed this.
