### ISSUE TITLE
Zoom out texture view further in the Fast Texturing Tool

### ISSUE THREAD

**Issue by drednorzt** [sboxgame/issues#3456]
### For?

Hammer

### What can't you do?

Can't zoom out the texture view in order to set up tiling textures with more accuracy.

<img width="554" alt="image" src="https://github.com/sboxgame/issues/assets/5728855/33e89c3c-9e7f-4f35-90c8-707ae714c663">

### How would you like it to work?

Currently it seems to lock at a zoom where the texture is the same size as the Texturing tool preview window. It would be extremely useful if you could zoom further out than that (the UV's are much larger than the UV square when your tiling the texture).

### What have you tried?

Resizing the window on a single axis, to get a larger field of view, without the texture preview scaling up to (which happens when you resize the window on the diagonal.

<img width="1378" alt="image" src="https://github.com/sboxgame/issues/assets/5728855/175bb275-79b7-449e-8775-1659cef82c91">

### Additional context

Not exactly the same issue, but it would be great to be able to lock the proportions when scaling the UV's to, so you can get it squared by scaling it on a single axis, and then scale it up and down without losing the aspect ratio. Could be done with a modifier key.

**Comment by QuackCocaine** [comment]
yes please! it really sucks that you cant zoom in and out in the fast texture tool.

**Comment by aylaylay** [comment]
I've allowed it to zoom out a bit more
