### ISSUE TITLE
`Box.Rect.Height` is calculated incorrectly

### ISSUE THREAD

**Issue by timmybo5** [sboxgame/issues#3457]
### Describe the bug

This used to work fine before but idk when it changed to this behavior exactly.

Due to how vertical scrollable panels work a min-height property is required.
I use Box.Rect.Height to calculate the height dynamically but for some reason the height is now always the same.

### Box.Rect.Height = 24
![image](https://github.com/sboxgame/issues/assets/4988198/daa706ec-b3f8-4492-9222-60e4d654d2e8)

### Box.Rect.Height = 24
![image](https://github.com/sboxgame/issues/assets/4988198/a6cc40d1-6f74-4714-b70a-32ba7e6ba152)

The result is that the next messages sent will be overlapping with the previous one 
![image](https://github.com/sboxgame/issues/assets/4988198/95d9ab89-afca-4eab-9bf8-7ececc3f0f94)

**Comment by anthonysharpy** [comment]
yes! i also noticed my chat starting to spazz out lately, it seems as if everything tries to overlap eachother. i guess this is probably the cause. would say this probably broke this week sometime.

**Comment by garrynewman** [comment]
You'll have to explain more about what you're doing.. you shouldn't really ever have to mess with these variables manually

**Comment by timmybo5** [comment]
@garrynewman  Right now children in vertical scrollable panels:
```css
flex-direction: column;
overflow: scroll;
```
Need `min-height: X` property set to enable scrolling otherwise the parent tries to fit them within the set size.

This is an example without min-height:
![image](https://github.com/sboxgame/issues/assets/4988198/abf2c546-4be4-47a0-b817-24f22c9f47f4)

This is a problem with multi line messages because they can have a variable height, to fix this issue I dynamically set min-height using the box height (which used to work fine):

```csharp
// When initialized on DOM
if (message.Box.Rect.Height > 0)
{
    var msgHeight = message.Box.Rect.Height * ScaleFromScreen;
    msgWrapper.Style.MinHeight = Length.Pixels(msgHeight);
}
```

Best case scenario min-height is not needed at all, like how it works on web.

**Comment by handsomematt** [comment]
Have you tried flex-shrink: 0

**Comment by garrynewman** [comment]
There's like 50 examples of this working in the main menu and UI lab without having to explicitly define the height

**Comment by timmybo5** [comment]
I see, I didn't know about this method, been using  it like this for 2 years now xD
Thanks for informing me! :)
