### ISSUE TITLE
Full crash during startup of game.

### ISSUE THREAD

**Issue by DaddyFrosty** [sboxgame/issues#3458]
### Describe the bug

Most of the time when I start my game in s&box it will just crash no logs, nothing. The closest I have gotten to a cause is 
`2023/06/17 15:19:01.5393	engine/Entity System	m_16ByteOrLessStack out of space, falling through after 8192 entries, consider upping NETWORKFIELDSCRATCHDATA_16BYTE_COUNT` and 
2023/06/15 22:38:22.4503	engine/RenderSystem	Texture missing shader resource view when setting parameter "?" - returning error texture in CTextureManagerDx11::GetResourceView Texture: "swapchaindepth.vtex"`

But when I do get in sometimes it will still print those errors and I will still be able to play, as if nothing happened, this started around the 15th of June. I don't think it's my fault, but for all I know it could be. There are 0 logs related to the crash, no dump files, nothing... For all I could know this could be a divide by zero issue in the C++ exe...

I also did try running a older build of my game from a week ago and I did still crash. So I have no clue.

### To Reproduce

Well it's one of those "It doesn't run fine on my machine"...
but gamemode ...
map ...

Game freezes
Crash

### Expected behavior

Well to allow me to develop my game

### Additional context

I didn't crash but now I got this in my console. Happened 2 times consecutively after a restart.
http://sx.frosty.co.nz/Exert%20of%20logs.txt

I haven't touched networking in probably the last 30 days as far as I know, I did also try checking out a older build ( 9th of June ), but I would still crash. That build is way older than when this started being an issue, which adds to the confusion.

Edit: I tracked down the network issue, still crashing, even after fixing it.

**Comment by lotuspar** [comment]
does it happen with other games, and could you provide your game to test with

**Comment by DaddyFrosty** [comment]
I didn't crash but now I got this in my console. Happened 2 times consecutively after a restart.
http://sx.frosty.co.nz/Exert%20of%20logs.txt

I haven't touched networking in probably the last 30 days as far as I know, I did also try checking out a older build, but I would still crash.

**Comment by DaddyFrosty** [comment]
> does it happen with other games, and could you provide your game to test with

My game is still private, access may be granted to s&box developers

**Comment by lotuspar** [comment]
i'm a s&box developer you may give me access

**Comment by DaddyFrosty** [comment]
> i'm a s&box developer you may give me access

as in that you work professionally for FP

**Comment by yuberee** [comment]
> as in that you work professionally for FP

I work for Facepunch but I do it for free.

**Comment by DaddyFrosty** [comment]
Alright yeah you got access in like the second wave right? What's your steam/steamid?

**Comment by lotuspar** [comment]
?

**Comment by yuberee** [comment]
> Alright yeah you got access in like the second wave right? What's your steam/steamid? @yuberee

76561198049395102

**Comment by anthonysharpy** [comment]
bit of a long shot and is probably a s&box bug at the end of the day but i don't suppose you happen to be implementing INetworkSerializer anywhere and/or are trying to network massive amounts of data anywhere? like networking a string that's tens of thousands of characters long or something? that's caused crashes for me before.

**Comment by DaddyFrosty** [comment]
> bit of a long shot and is probably a s&box bug at the end of the day but i don't suppose you happen to be implementing INetworkSerializer anywhere and/or are trying to network massive amounts of data anywhere? like networking a string that's tens of thousands of characters long or something? that's caused crashes for me before.

No I actually think I tracked down that problem and it was a networked list.... I removed the Net attr, no errors still crashing

**Comment by DaddyFrosty** [comment]
It had something to do with my game install, I'm quite unsure why or how this happened out of nowhere, but I seemed to have gotten it to stop by redownloading s&box and git cloning...
