### ISSUE TITLE
When uploading on the asset.party a map there is no files upload

### ISSUE THREAD

**Issue by TaviotBaptiste** [sboxgame/issues#3461]
### Describe the bug

Hello,

When I try tu upload a map (Compiled) with my organization. As suppose :
Select the ressource inside the asset browser -> Use the inspector -> Upload -> Add organization ...

After the "add organization" -> on "File uploads" there is always a pending file, a "thumb.png" that won't upload.

![image](https://github.com/sboxgame/issues/assets/30879857/2b27a077-4c57-4f58-9c90-0d5bdeeb898f)

If I select "Upload File" it go next "Revision details" -> and "Package Publish successful". But when i go on asset.party there is not version or anything ... 

![image](https://github.com/sboxgame/issues/assets/30879857/fa0adb17-8820-47d1-9b97-2ead998c7ab5)

If found something more, If i delete on the remote "asset.party" the ressources and retry to compile there is style this thumb and when i try tu upload S&box say : 'invalide package'

### To Reproduce

1. Select a map (compiled)
2. try to upload it on the asset.party
3. You have nothing on asset.party except if I do something wrong

### Expected behavior

1. It should upload the ressources (map) on asset.party
2. It should take or remove the thumb file 

### Additional context

I'm running on Windows 10 (x64), I have a I7-8086K and 16 GB ram. 
For upload I have the fiber (Approximatly 400GB download / 500 upload)

My map is inside ->Asset browser -> Projects -> Addon -> maps (Folder) -> map.vmap    ||   XildriteAddon\maps\bhop_hot.vmap
![image](https://github.com/sboxgame/issues/assets/30879857/46432995-10dd-4ea3-95a2-d2cee4ee8b6f)

And compiled files are inside the : C:\Users\USERNAME\Documents\s&box projects\xildriteaddon\maps\
(Sorry i'm french, maybe Documents is suppose to be files)

![image](https://github.com/sboxgame/issues/assets/30879857/cbf3f75d-c965-4b2a-a745-c237a3594d4e)

**Comment by garrynewman** [comment]
This should be fixed now

**Comment by TaviotBaptiste** [comment]
Working for me ! Thanks you ! (Hope it's the same for others ! ) 💯
