### ISSUE TITLE
Voice chat is really quiet with no way to modify

### ISSUE THREAD

**Issue by KingOfTheFBI** [sboxgame/issues#3468]
### Describe the bug

Voice chat is way quieter than expected. Having it at max is still really quiet, 

### To Reproduce

Just hop into a game like Trouble in Terrorist Town with voice enabled and talk with someone else, it will be really quiet

### Expected behavior

Be pretty loud at max so there is wiggle room

**Comment by NotGaylien** [comment]
im pretty sure its any game with in general that has this issue. sandbox, grubs and so on.

**Comment by KingOfTheFBI** [comment]
> im pretty sure its any game with in general that has this issue. sandbox, grubs and so on.

yeah its anything with voice

**Comment by e1m1j** [comment]
There's a loosely related issue here that we picked up while testing voip this evening:

https://github.com/sboxgame/issues/issues/3469

**Comment by KingOfTheFBI** [comment]
@aylaylay looks to be fixed, going to close this one out, thanks
