### ISSUE TITLE
Setting voice parameter on Citizen animgraph does not move mouth

### ISSUE THREAD

**Issue by chrisspieler** [sboxgame/issues#3469]
### Describe the bug

The Citizen model's mouth does not move as the voice parameter gets set. 

### To Reproduce

1. Start a facepunch.sandbox session and have someone join
2. Each of you hold "V" on your keyboard and yell in to the microphone

### Expected behavior

The mouths of each player model will move based on the voice level of the client.

### Additional context

This issue also happens in a custom game if directly setting the "voice" parameter of the animgraph to the IClient.Voice.CurrentLevel of a player. But in the animgraph editor, you can preview what changing the voice parameter does, and it seems correct, so maybe it's a networking issue or something?

**Comment by aylaylay** [comment]
It's working for me?

**Comment by chrisspieler** [comment]
I can't seem to get it to work for whatever reason. This is the current version of the Sandbox game. In this clip, I'm tapping on and yelling at the microphone.

https://github.com/sboxgame/issues/assets/8889285/928a4128-d8b0-46cb-9fd7-79c437f5c42d

**Comment by aylaylay** [comment]
I have a feeling this has never worked for other players, only your local player, i'll see what I can do.

**Comment by aylaylay** [comment]
I'm now setting Voice.CurrentLevel on the server too which should mean you'll see other players mouths move

**Comment by chrisspieler** [comment]
This is fixed now. Thank you!
