### ISSUE TITLE
Wrong shader loaded in non-local version if shader with the same name already exists in core

### ISSUE THREAD

**Issue by SharpMars** [sboxgame/issues#3472]
### Describe the bug

When having material that uses custom shader that has the same name as one of shaders in core, material will always use the one from core if its non-local version. It works completely fine in local version.

### To Reproduce

1. Make shader with the same name as one of the shaders in core, example "unlit"
2. Make material using it and use it in a map
3. Upload it
4. It references the core shader, instead of custom one

### Expected behavior

Custom shader should be used instead of one from core.
If not fixable warn developer that this will happen.

**Comment by handsomematt** [comment]
Resources need a unique name, we have no plans to change this currently
