### ISSUE TITLE
EntityComponent.NetworkIdent should be unique

### ISSUE THREAD

**Issue by Weldify** [sboxgame/issues#3473]
### What it is?

`EntityComponent.NetworkIdent` currently points to the entity that owns the component. This isn't useful because you can't differentiate between multiple components, for example when passing them through a ConCommand.

### What should it be?

`EntityComponent.NetworkIdent` should be unique.
There should also be a static method to find an entity component based on its NetworkIdent: `EntityComponent.FromId(id)`

**Comment by xezno** [comment]
I don't understand what this is for, `EntityComponent.FindByIndex()` isn't a function

**Comment by Weldify** [comment]
Reworded the issue so that it makes sense

**Comment by xezno** [comment]
What is your use case

**Comment by Weldify** [comment]
Im making an interaction system where interactions are components, when the player wants to interact with an interactable component it is passed to the server through a `ConCmd.Server`, currently I can't pass the component. One thing to note is entities can have multiple interactable components, so I can't just grab a random interactable component serverside. I ended up writing a library that makes this possible - but it should definitely exist natively.

**Comment by handsomematt** [comment]
Doesn't make sense, they're networked on the entities. Pass the entity through a concommand and grab it's component after.

**Comment by Weldify** [comment]
There are multiple occasions where components in my game aren't singletons
