### ISSUE TITLE
Hammer Gizmo inheritance 

### ISSUE THREAD

**Issue by TheBoxTrot** [sboxgame/issues#3476]
### What it is?

being able to inherit hammer gizmos from parent classes

### What should it be?

being able to define a hammer gizmo inside a base class and have all its children have that same gizmo would be really helpful and cut down on copying and pasting code

**Comment by handsomematt** [comment]
they're just static methods, can't you do

```csharp
public class DerivedEntity : ParentEntity
{
    public static DrawGizmos()
    {
        ParentEntity.DrawGimos();
        // then more gizmos here
    }
}
```
