### ISSUE TITLE
Voice chat logs excessive data to console

### ISSUE THREAD

**Issue by chrisspieler** [sboxgame/issues#3478]
### Describe the bug

When using voice chat, a bunch of stuff similar to the below gets logged:
```
 08:26:09   Client Data amount: 270
 08:26:09   Client Data amount: 194
 08:26:09   Client Data amount: 192
 08:26:09   Client Data amount: 261
 08:26:10   Client Data amount: 18
```
Here's the stack trace:
<img width="306" alt="image" src="https://github.com/sboxgame/issues/assets/8889285/d946a22d-b3c5-4f52-a5f6-26cdc714a1f6">

### To Reproduce

1. In the S&box editor, start a game such as Sandbox that supports voice chat.
2. Hold the voice chat button (`V`)
3. Speak in to your microphone
4. Watch the console

### Expected behavior

We shouldn't be getting this much stuff logged to the console.

**Comment by aylaylay** [comment]
Done
