### ISSUE TITLE
Blendable materials aren't being lightmapped?

### ISSUE THREAD

**Issue by PixelNovaVT** [sboxgame/issues#3483]
### Describe the bug

When I apply a bendable material to a mesh, it seems as though it isn't being lightmapped.

### To Reproduce

1. Create a clean empty map.
2. Create 2 mesh planes and subdivide to make them displacements.
3. Apply a normal material (Reflectivity30 or whatever you want) to one, and a blendable material to the other.
4. Add a lighting prefab to the map, and an object to cast shadows on the planes.
5. compile.

### Expected behavior

Meshes with blendable materials should lightmap like any other mesh.

### Media/Files

![sbox-dev_0PVl9jgM3c](https://github.com/sboxgame/issues/assets/76824004/b66e8cea-5e63-43a7-9382-c6a2b973d67a)
Shadow abruptly stops at the blendable material.

![sbox-dev_wWW2o9IZP8](https://github.com/sboxgame/issues/assets/76824004/0823f203-bf8c-4524-8dd7-7ab7e59df15a)
Same as above but with Baked Light Result debug view enabled.

![Screenshot 2023-06-22 003430](https://github.com/sboxgame/issues/assets/76824004/ac9b8341-5e25-449a-9582-11f6802525d5)
High Quality RT Lighting Preview in Hammer.

**Comment by handsomematt** [comment]
Should be fixed next update
