### ISSUE TITLE
Hiding A Model With Camera.Main.ExcludeTags Retains Shadows

### ISSUE THREAD

**Issue by anthonysharpy** [sboxgame/issues#3489]
### Describe the bug

when i hide the player by setting Camera.Main.ExcludeTags (which happens when i go into first person), the player disappears as expected, but their shadow stays behind in the spot they disappeared in. 

https://github.com/sboxgame/issues/assets/55365296/34444cab-b761-49ca-8602-084d48e1907d

### To Reproduce

hide the player using Camera.Main.ExcludeTags. probably works on non-player models too.

### Expected behavior

shadow should be gone

**Comment by handsomematt** [comment]
These were ao proxies being left behind, I fixed this a while ago
