### ISSUE TITLE
Disable click-and-drag scrolling for panels with overflow: scroll

### ISSUE THREAD

**Issue by CarsonKompon** [sboxgame/issues#3491]
### For?

S&Box

### What can't you do?

I cannot disable the click-and-drag scrolling that comes with a panel being given `overflow: scroll;`

What I'm trying to do specifically is allow users to scroll on this panel while still maintaining the drag-and-drop functionality of the panel within.

https://github.com/sboxgame/issues/assets/5159369/30c4d046-812f-4d71-af47-d6136b469529

I believe what's happening here is that the mouse release function of my drag-and-drop panel is being called when the click-and-drag starts for virtual scrolling.

### How would you like it to work?

I would like to be able to do something such as
```cs
Panel.CanDragScroll = false;
```

This seems like the best option to me considering there are already member variables in the Panel class such as `WantsDragScrolling` (amongst other scrolling-related)

### What have you tried?

I checked all over the api reference on [asset.party](https://asset.party/api/Sandbox.UI.Panel) and skimmed through all the intellisense I could and could not find anything that allows me to disable this.

**Comment by CarsonKompon** [comment]
For anyone else who comes across this issue in the meantime, I made my own custom scrollable Panel that doesn't use `overflow: scroll;` so you can safely click-and-drag from within it.

Here's an example of how I did it (kind of ugly code but do what you want with it):

```razor
@using Sandbox;
@using Sandbox.UI;

<root>
    <label class="inventory-header">#inventory.inventory</label>
    <div @ref="ContainterContainer" class="inventory-container">
        <div @ref="InventoryContainer" class="container-offset">
            @foreach (StashEntry item in GetInventory())
            {
                @if(item == null || item.Amount == 0) continue;
                <HomeInventoryEntry Entry="@item" />
            }
        </div>
    </div>
</root>

@code
{
  public Panel ContainterContainer {get; set;}
  public Panel InventoryContainer {get; set;}
  private float ScrollY = 0;
  private float ScrollVel = 0;

  public override void OnMouseWheel(float value)
  {
      if(value != 0)
      {
          ScrollVel = -value * 1000;
          UpdateScroll();
      }
  }
  
  [GameEvent.Client.Frame]
  public void OnFrame()
  {
      if(InventoryContainer == null) return;
      ScrollVel = ScrollVel.LerpTo(0, Time.Delta * 10f);
      if(Math.Abs(ScrollVel) < 0.1f) ScrollVel = 0;
      if(ScrollVel != 0)
      {
          ScrollY += ScrollVel * Time.Delta;
          UpdateScroll();
      }
      if(ScrollY > 0f)
      {
          ScrollVel = -ScrollY * 10f;
          UpdateScroll();
      }
      float height = (InventoryContainer.Box.Rect.Height - ContainterContainer.Box.Rect.Height) * ScaleFromScreen;
      if(ScrollY < -height)
      {
          ScrollVel = -(ScrollY + height) * 10f;
          UpdateScroll();
      }
  }
  
  public void UpdateScroll()
  {
      InventoryContainer.Style.Top = Length.Pixels(ScrollY);
      InventoryContainer.Style.Dirty();
  }
}
```

**Comment by xezno** [comment]
I've added `CanDragScroll` to Panel, you can use that to opt-out of drag scrolling on that panel.
If you're not using C# you can also just set it in razor:

```html
<div class="scrollable" CanDragScroll="false">
	<label class="canvas">ONE</label>
	<label class="canvas">TWO</label>
	<label class="canvas">THREE</label>
	<label class="canvas">FOUR</label>
	<label class="canvas">FIVE</label>
	<label class="canvas">SIX</label>
	<label class="canvas">SEVEN</label>
	<label class="canvas">EIGHT</label>
	<label class="canvas">NINE</label>
	<label class="canvas">TEN</label>
</div>
```
