### ISSUE TITLE
RenderSceneObject on SceneCustomObject is not being invoked.

### ISSUE THREAD

**Issue by dch-GH** [sboxgame/issues#3493]
### Describe the bug

RenderSceneObject() doesn't seem to be getting called at all.

### To Reproduce

Setup a SceneCustomObject, either as an inheriting class or by using the base type SceneCustomObject with a RenderOverride set. Neither work.

### Expected behavior

RenderSceneObject() should be getting ran.

### Media/Files

```cs
public class TestSceneCustomObject : SceneCustomObject
{
	public TestSceneCustomObject( SceneWorld sceneWorld ) : base( sceneWorld )
	{
		Log.Info( $"Created a TestSceneCustomObject" );
	}

	public override void RenderSceneObject()
	{
		// This will not be logged.
		Log.Info( $"Logging from: RenderSceneObject" );
		base.RenderSceneObject();
	}
}
```

```cs
	SceneCustomObject cso;
	TestSceneCustomObject test;

	public MyGame()
	{
		if ( Game.IsServer )
			return;

		test = new TestSceneCustomObject( Camera.Main.World );

		cso = new SceneCustomObject( Camera.Main.World );
		cso.RenderOverride += ( so ) =>
		{
			// This won't be logged either.
			Log.Info( "Logging from the RenderOverride." );
		};
	}
}
```

From what it looks like, this should be run automatically internally: 
![image](https://github.com/sboxgame/issues/assets/66768086/90766538-62a8-4f48-83a2-7b1bc524917e)

**Comment by handsomematt** [comment]
It's likely Camera.Main.World doesn't exist yet in the game constructor, we use these in plenty of other places just fine.

**Comment by dch-GH** [comment]
> It's likely Camera.Main.World doesn't exist yet in the game constructor, we use these in plenty of other places just fine.

In my actual use case I'm not setting things up from inside the game constructor, I just put it there in the example for simplicity. Setting it up from somewhere like FrameSimulate doesn't work either, nor does setting up a new SceneWorld for it to use.
```cs
	public override void FrameSimulate( IClient cl )
	{
		base.FrameSimulate( cl );
		if ( Input.Released( "attack1" ) )
		{
			var testWorld = new SceneWorld();
			Camera.Main.Worlds.Add( testWorld );

			test = new TestSceneCustomObject( testWorld );

			cso = new SceneCustomObject( testWorld );
			cso.RenderOverride += ( so ) =>
			{
				Log.Info( "Logging from the RenderOverride." );
			};
		}
	}
```
Am I just doing something incredibly wrong?

**Comment by dch-GH** [comment]
Wasn't setting the Bounds 🤦.
Works fine.
