### ISSUE TITLE
Add a keybind in Hammer to quickly duplicate an object in place

### ISSUE THREAD

**Issue by WereTech** [sboxgame/issues#3494]
### For?

Hammer

### What can't you do?

Currently (as far as I know) the only way to duplicate an object is by shift+dragging it or using the Paste Special window, which is very inconvenient as you need to copy the objects first then deal with the window. It would be great if there was a keybind that can be pressed to quickly duplicate an object in place so it will be much easier for maintaining a fast workflow.

### How would you like it to work?

Press a keybind to quickly duplicate an object in place.

### What have you tried?

Searching the list of keybinds for anything related to this, it does not exist.

**Comment by handsomematt** [comment]
Seems like the first thing you'd do after duplicating is move it. Manipulation tools all have a shift drag that duplicates the object on operation.
