### ISSUE TITLE
S&box fails to use Main GPU on Laptop

### ISSUE THREAD

**Issue by gidgeesheep** [sboxgame/issues#3502]
### Describe the bug

When I try to run S&box on my ROG Strix G513QY, Sandbox fails to utilize the second more powerful GPU. Letting Windows 11 handle the application allocation leads it to use only the low power GPU. Forcing it through the Windows settings to use the better graphics card seems to improve performance but cause new bugs elsewhere, including UI image glitches, and audio hitching.

### To Reproduce

1. Own a ROG Strix G513QY with Windows 11 or equivalent
2. Make no changes to windows settings or steam launch
3. Simply Open S&box or S&box Dev
4. Lose all the fps and burn your legs

### Expected behavior

S&box should be able to choose and utilize the proper GPU automatically. I believe extra issues are caused by forcing it through windows settings.

### Media/Files

Zero GPU Activity on the Radeon RX 6800 while playing Goblin Tide
![image](https://github.com/sboxgame/issues/assets/55063683/dbfb8e35-7b70-4f93-8e95-86f4d2715c1b)

The Windows Settings to force an application to use one or another GPU
<img width="1280" alt="Screenshot 2023-06-26 194642" src="https://github.com/sboxgame/issues/assets/55063683/2c2db99c-9554-451f-8b56-6006baeeccd4">

Graphical issues caused by force switching to the proper GPU
<img width="1280" alt="Screenshot 2023-06-26 194839" src="https://github.com/sboxgame/issues/assets/55063683/e5b46331-d00c-46b8-90df-c2f22e5e61f4">

Very High Usage but Better Performance overall now that the Correct GPU is in use
<img width="1280" alt="Screenshot 2023-06-26 194924" src="https://github.com/sboxgame/issues/assets/55063683/26da4d9e-8544-4296-8747-93a31f48f149">

### Additional context

Computer Specs
https://rog.asus.com/us/laptops/rog-strix/2021-rog-strix-g15-advantage-edition-series/spec/

Running on Windows 11

**Comment by lotuspar** [comment]
graphical issues are probably #3347

**Comment by gidgeesheep** [comment]
> graphical issues are probably #3347

That's very similar, probably related.

**Comment by handsomematt** [comment]
I've added the stuff for enabling discreet GPU usage but don't have a way to test, so let me know if it's fixed for you

**Comment by gidgeesheep** [comment]
Yep, after changing setting to let windows choose the GPU, it now chooses the correct one. The graphics glitches remain.

**Comment by handsomematt** [comment]
Awesome, I'll get those glitches with #3347 when I can recreate them

**Comment by desumachii** [comment]
<img width="1919" height="1033" alt="Image" src="https://github.com/user-attachments/assets/b34dab24-4547-4dae-bbdb-04bca8f4decd" />

i have the same issue
