### ISSUE TITLE
Unable to use Http Requests in Game Menu

### ISSUE THREAD

**Issue by PolSpock** [sboxgame/issues#3504]
### Describe the bug

Hello,

_I have created a [similar issue (closed)](https://github.com/sboxgame/issues/issues/3484) tagged with `feature` whereas i'm sure it's a `bug` now since i have seen we can open [WebPanel](https://asset.party/api/Sandbox.UI.WebPanel) in [GameMenu](https://asset.party/api/Sandbox.Menu.IGameMenu)_

I'm looking to retrieve player information from my API in the [Game Menu](https://asset.party/api/Sandbox.Menu.IGameMenu)  but i'm not able to make an HTTP GET request to my API

Each time i tried to make a sample HTTP GET or POST request i have the Exception
`Exception waiting for task to finish System.InvalidOperationException: Access to 'URL' is not allowed.`

### To Reproduce
_Local environment :_
Try to make a sample HTTP GET or POST request with :
`string response = await Http.RequestStringAsync("https://google.com/");`
You will get :
`Exception waiting for task to finish System.InvalidOperationException: Access to 'https://google.com/' is not allowed.`

![image](https://github.com/sboxgame/issues/assets/5229571/5a5d5191-5f91-40ca-8a46-50b84a712f77)

Whereas i correctly set the URL in the Http Allow list :
![image](https://github.com/sboxgame/issues/assets/5229571/8116fa42-cafb-410e-9510-57f90908aea4)

And this work well "in game" state :
![image](https://github.com/sboxgame/issues/assets/5229571/59c98a3d-610e-4105-b176-bfb43ad7cdcc)

### Expected behavior

Be able to use HTTP POST / GET Requests in the Game Menu state

**Comment by CarsonKompon** [comment]
This issue could be related to https://github.com/sboxgame/issues/issues/3448
Not entirely sure but I thought I would mention it in case it's worth noting :)

**Comment by PolSpock** [comment]
By reading trundler issue : https://github.com/sboxgame/issues/issues/3514
I was surprised to read that he didn't encounter the same issue as me.

But after investigation, he used localhost URL.
So i tried and it's working too. Without adding localhost into the `Http Allow List`
But once i'm returning to "production" URL, i have the `Exception waiting for task to finish System.InvalidOperationException: Access to 'https://myurl/' is not allowed.`

So i definitely think there are problems with this `Http Allow List` on Game.Menu

**Comment by handsomematt** [comment]
Removed allow list
