### ISSUE TITLE
[AnimGraph] [ShaderGraph] Portal node.

### ISSUE THREAD

**Issue by eEight-dev** [sboxgame/issues#3506]
### For?

S&Box, Other

### What can't you do?

In Substance Designer there is a portal node that essentially has the same functionality as the re-route node but also helps keep things much cleaner if used correctly.

### How would you like it to work?

1. This is the normal way:
![no_portal](https://github.com/sboxgame/issues/assets/120290229/de875116-c929-4b56-a723-f39dfce2e195)
2. This is the portal node way: 
![portal](https://github.com/sboxgame/issues/assets/120290229/34fe7d64-8194-40f6-9cda-76c0fa564699)
3. This is not a very good example, but for a complicated graph like the citizen.vanmgrph this would help keep things much cleaner and organized.

### What have you tried?

.

### Additional context

1. It would be really nice if we could select our own color for the portal node:
![portal_color](https://github.com/sboxgame/issues/assets/120290229/bd50b9b7-447f-41ab-af4e-0c3d76e34024)
2. If two portal nodes are very close to each other it would be nice if they would automatically change to a smaller icon.
3. More info here: https://www.youtube.com/watch?v=n8ihB3YBRPo

**Comment by aylaylay** [comment]
That's shadergraph not animgraph and I think it's awful so this wont be added sorry.
