### ISSUE TITLE
Physgun bug

### ISSUE THREAD

**Issue by gregiv** [sboxgame/issues#3507]
### Describe the bug

When you hold an object with your physgun and enter the following command: "respawn_entities", the physgun will be bugged and its laser will remain effective as if the object was still there. From then on, it will continue to work but there will be no effect.

The error code: "client.frame on Physgun 202" 
The number is not constant and changes each time I relaunch a game and repeat the operation. 

### To Reproduce

1. Spawn any object.
2. Taking it with a physigun.
3. Open your console and enter the command: respawn_entities.
4. Congratulations, you've just made a bug !

### Expected behavior

The effect should normally stop when the object disappears. 

### Media/Files

https://github.com/sboxgame/issues/assets/36164870/289c32a6-e622-48b1-8135-fcc2946eddb0

**Comment by WheatleyMF** [comment]
This seems to be an issue related to Sandbox gamemode itself, not an engine bug. Go to https://github.com/Facepunch/sandbox/issues and make an issue there (although it doesn't seem to be active as of recently), or make a fix for this and pull request it there.

**Comment by aylaylay** [comment]
Fixed
