### ISSUE TITLE
Many PhysicsBody properties have irrelevant or broken server-to-client networking

### ISSUE THREAD

**Issue by Phyksar** [sboxgame/issues#3513]
### Describe the bug

I've noticed that some properties of physics body are not networked properly, I was trying to access `Velocity`, `AngularVelocity`, `Mass`, `LocalMassCenter`, `Inertia` and `InertiaRotation` on client domain, then I realized that there's a common problem with many properties. I tried my best to list all of them.
- `LocalMassCenter` - value changes along with server but does not match
- `Mass` - doesn't match even the initial mass of model
- `Density` - likely related to mass networking
- `Scale` - should represent the entity's scale, but is always `1` clientside, `Entity.Scale` is networked just fine
- `SurfaceMaterial` - likely related to shapes networking

All of these doesn't change at all:
- `LinearDamping`
- `AngularDamping`
- `LinearDrag`
- `AngularDrag`
- `Inertia`
- `InertiaRotation`
- `LastWaterEffect`
- `AngularVelocity`
- `Velocity`
- `GravityEnabled`
- `UseController`
- `EnableTouch`
- `EnableTouchPersists`
- `EnableSolidCollisions`
- `EnableTraceAndQueries`
- `Enabled`
- `MotionEnabled`
- `SpeculativeContactEnabled`
- `DragEnabled`

Any changes to physics shapes are also not appearing on client according to Physics Debug Overlay, I can describe that later if needed.

### To Reproduce

This is the code I use to spawn entity (based on the default game template):
```csharp
if ( Game.IsServer && Input.Pressed( "attack1" ) )
{
	var melon = new ModelEntity();
	melon.SetModel( "models/sbox_props/watermelon/watermelon.vmdl" );
	melon.Transmit = TransmitType.Always;
	melon.Position = Position + Rotation.Forward * 40;
	melon.Rotation = Rotation.LookAt( Vector3.Random.Normal );
	melon.SetupPhysicsFromModel( PhysicsMotionType.Dynamic, false );
	melon.PhysicsGroup.Velocity = Rotation.Forward * 1000;
	melon.Scale = Random.Shared.Float(0.5f, 1.5f);
	melon.PhysicsBody.Mass = Random.Shared.Float(1.0f, 10.0f);
	melon.PhysicsBody.LinearDamping = Random.Shared.Float(0.0f, 1.0f);
	melon.PhysicsBody.AngularDamping = Random.Shared.Float(0.0f, 1.0f);
	melon.PhysicsBody.LinearDrag = Random.Shared.Float(0.0f, 1.0f);
	melon.PhysicsBody.AngularDrag = Random.Shared.Float(0.0f, 1.0f);
	melon.PhysicsBody.LastWaterEffect = Random.Shared.Float(0.0f, 1.0f);
	melon.PhysicsBody.SurfaceMaterial = Random.Shared.FromArray(new [] { "melonwater", "wood", "metal" });
	melon.PhysicsBody.LocalMassCenter = Vector3.Random;
	Melon = melon;
}
```

### Expected behavior

I expect that all properties of `PhysicsBody` should be networked along with the entity.

### Media/Files

![2023-06-29 01_34_01-sbox-dev](https://github.com/sboxgame/issues/assets/13320416/59276368-6307-448b-b29e-f58df9a788b4)

**Comment by Owningle** [comment]
I am now also running into this as an issue.

**Comment by aylaylay** [comment]
Nothing on physicsbody should be networked and it would be a bad idea to. If there's a specific value you need networked you should network that yourself.

**Comment by Phyksar** [comment]
@aylaylay that's very bad to hear, that's not how I expected this issue to be resolved just by closing it. What you've suggested seems non-obvious and impractical - imagine I wanted to access inertia but it doesn't have a setter, so I can't update it on client. And if you want me to create some different component to store all these data it raises a question - why should I use another object instead of already made PhysicsBody? Why clientside physics bodies have irrelevant state and how a new developer would know that this was, by your words, the intended idea?
