### ISSUE TITLE
vr_multiview_instancing should be set to 0 by default

### ISSUE THREAD

**Issue by CarsonKompon** [sboxgame/issues#3516]
### For?

S&Box

### What can't you do?

Use VR without a headache due to foliage/water shaders being utterly broken while `vr_multiview_instancing` is set to 1 (which is currently the default)

### How would you like it to work?

While VR is in a less-than-ideal state I think that `vr_multiview_instancing` should be set to 0 by default since foliage and water shaders draw horribly incorrectly without.

### What have you tried?

I have tried setting `vr_multiview_instancing 1` but that convar resets to 0 every time you launch the game

**Comment by samzanemesis** [comment]
That's hiding the problem rather than solving it
