### ISSUE TITLE
Corruped images on home screen

### ISSUE THREAD

**Issue by eye-tie** [sboxgame/issues#3526]
### Describe the bug

When I first opened the s&box client the game tiles' pictures were all pixly/corrupted, same with the second reboot.
![image](https://github.com/sboxgame/issues/assets/138244699/b8c533b3-dfb3-4baa-90cc-a5ea14bf9461)

### To Reproduce

You literally open up the game and it appears.

### Expected behavior

Non corrupted game images.

### Media/Files

![image](https://github.com/sboxgame/issues/assets/138244699/8d7cf453-1560-4e38-9bdf-e2539a568f76)

### Additional context

Not sure if it matters at all, but since it's on the preset I'm running windows 11, using a ryzen 5 5600x, and a rx 6600xt gpu.

**Comment by handsomematt** [comment]
#3347
