### ISSUE TITLE
ShaderGraph: Can't compile shaders with Alpha Test

### ISSUE THREAD

**Issue by DeltaDesigns** [sboxgame/issues#3529]
### Describe the bug

When you try to compile a shader that uses alpha test ("masked" blend mode), it fails and gives error
"common/material.hlsl(41,8-27): error X3003: redefinition of 'g_boolAttr_alphatest'"

### To Reproduce

1. Make a new shader graph shader
2. Set Blend Mode to Masked
3. Compile
4. Fail

### Expected behavior

Should not fail

**Comment by aylaylay** [comment]
Is this still happening? Seem to work fine for me

**Comment by DeltaDesigns** [comment]
> Is this still happening? Seem to work fine for me

It seems to have gotten fixed sometime between then and now so ill close this
