### ISSUE TITLE
Materials should reference shaders without the `_c` suffix

### ISSUE THREAD

**Issue by kristiker** [sboxgame/issues#3531]
### For?

Material Editor

### What can't you do?

To keep things consistent with how other content works, materials should reference shaders without the `_c` suffix.

### How would you like it to work?

Instead of:
```vdf
Layer0
{
    shader "my/effects.shader_c"
}
```
It should be:
```vdf
Layer0
{
    shader "my/effects.shader"
}
```

### What have you tried?

-

**Comment by aylaylay** [comment]
This didn't really matter but I agree other resources reference without the _c so this should too.
You'll have to resave the material to get the change because I didn't want it to trigger loads of material recompiles.
