### ISSUE TITLE
Add Support for Cloud.Particle and Cloud.Sound

### ISSUE THREAD

**Issue by Jake-NSW** [sboxgame/issues#3536]
### For?

S&Box

### What can't you do?

Currently uploading all my assets for my game to asset.party, and I currently can't easily download and load particles and sounds through code.

### How would you like it to work?

Being able to use Cloud.Sound and Cloud.Particle and work similar to Cloud.Model

### What have you tried?

Not sure if I am able to mount a package first and go through those hops. But my monkey brain likes the 1 function call and it works.

**Comment by dch-GH** [comment]
What about Cloud.Shader too? 🤯
