### ISSUE TITLE
Adding a Net attribute to a property in an incorrect setup breaks Visual Studio

### ISSUE THREAD

**Issue by peter-r-g** [sboxgame/issues#3537]
### Describe the bug

When you apply a `Net` attribute to a property that is not implemented properly within its class it will crash a majority of Visual Studio's components and force you to restart the IDE.

### To Reproduce

1. Copy the following code to a CSharp file in a project that uses the `Sandbox.Generator` source generator:
```cs
using Sandbox;

namespace MyGame;

public class Test
{
	[Net] public float TestFloat { get; set; }
}
```
2. Observe tons of crashes inside Visual Studio components.

### Expected behavior

For my entire IDE to not implode when I am in the middle of writing networking code.

### Media/Files

![image](https://github.com/sboxgame/issues/assets/11802285/86e3dc8a-3cfd-422e-9047-cc2353fc9815)
![image](https://github.com/sboxgame/issues/assets/11802285/00b8a7b1-401b-4757-b22d-ba746de2b457)

### Additional context

This issue is only present with the `Net` attribute. In my testing, I could not get Visual Studio to crash with `Predicted`, `Local`, `ClientInput`, and `ClientRpc` for methods. It seems something specific to the code gen around the `Net` attribute.

**Comment by yuberee** [comment]
Same happens with ConCmd attributes if you don't implement them properly in a static method.

https://github.com/sboxgame/issues/assets/59583743/7966e8f4-0f2d-4115-8a11-6c41e31b02da

**Comment by handsomematt** [comment]
Garry pushed something today that should've solved this.

**Comment by peter-r-g** [comment]
> Garry pushed something today that should've solved this.

Still happening

**Comment by peter-r-g** [comment]
No longer relevant
