### ISSUE TITLE
Missing pixels in imiges

### ISSUE THREAD

**Issue by Pysia20** [sboxgame/issues#3541]
### Describe the bug

most imiges have a lot of missing pixels 

### To Reproduce

i don't know

### Expected behavior

normal imiges

### Media/Files

![image_2023-07-03_113151125](https://github.com/sboxgame/issues/assets/59027162/eb7ed679-d0b9-485b-9805-dbb70f5ee40f)
![image_2023-07-03_113303530](https://github.com/sboxgame/issues/assets/59027162/a6acd6de-69f9-4cec-bc79-a7e51b05586a)

### Additional context

I'm running on windows 10
Graphics card: radeon 6700xt
Processor: Ryzen 5 5600
RAM: 32GB

**Comment by handsomematt** [comment]
#3347
