### ISSUE TITLE
Entities with `PhysicsMotionType.Static` won't be picked up by `Entity.FindInSphere`

### ISSUE THREAD

**Issue by AWildErin** [sboxgame/issues#3543]
### Describe the bug

In my project I need to find objects within a sphere, I can't use `PhysicsMotionType.Dynamic` because they will fall to the ground, so the choice would be to use `PhysicsMotionType.Static` but this will not find objects within the sphere.

### To Reproduce

1. Clone and run https://github.com/AWildErin/static_repro
2. Run `map repro_map`
3. See that keyframed and dynamic entities are hit, but not static

### Expected behavior

Logically I feel static should also be counted in this check as happens with traces (albeit that is optional). There could be some argument against having this, but the only alternative is to have it using `PhysicsMotionType.Keyframed` instead.

**Comment by Gmod4phun** [comment]
All of the FindIn* functions rely on physics. It should still be able to find static objects imo, so I guess its indeed a bug.

**Comment by AWildErin** [comment]
> All of the FindIn* functions rely on physics. It should still be able to find static objects imo, so I guess its indeed a bug.

It was a headache finding out that this was the cause of the issue for me, I don't see a reason why static objects are excluded from the FindIn methods.

**Comment by aylaylay** [comment]
It'll find statics now too (except the world)

**Comment by AWildErin** [comment]
Works as expected now, thanks!
