### ISSUE TITLE
Sandbox.Voice.Decode is public

### ISSUE THREAD

**Issue by chrisspieler** [sboxgame/issues#3548]
### Describe the bug

We don't have access to raw voice data, so this method shouldn't be public. The fact that it is public is very misleading for people who dig around the API docs and IntelliSense to find out what's possible.

### To Reproduce

1. Go here https://asset.party/api/Sandbox.Voice.Decode(Span,Span)
2. See that there is something

### Expected behavior

Sandbox.Voice.Decode is not exposed as part of the public API.

### Additional context

Whoops, this should've been an API design type issue.

**Comment by DevulTj** [comment]
Made internal for now
