### ISSUE TITLE
Allow modifying an EntityModel's RenderBounds

### ISSUE THREAD

**Issue by fluffybagel** [sboxgame/issues#3549]
### What it is?

In some instances, it can be useful to prevent an entity from culling and changing its render bounds could help.

For example, when rendering a full body avatar for a VR player, they could easily move their heads outside the model's precalculated render bounds, but we would want to keep rendering the player's body.

### What should it be?

Allow modifying Model.RenderBounds on a ModelEntity

**Comment by ShmishDD** [comment]
I'd love to this happen, without it we can't do custom culling.
