### ISSUE TITLE
Mr Facepunch removed models/props_doors/door01_left_03.vmdl with no replacement

### ISSUE THREAD

**Issue by sugmagaming** [sboxgame/issues#3553]
### Describe the bug

YOU PEOPLE removed models/props_doors/door01_left_03.vmdl without uploading it to assparty.

### To Reproduce

Have a map with models/props_doors/door01_left_03.vmdl
Open that bad boy.
Shits gone.

### Expected behavior

Should be uploaded to asset party.

**Comment by sugmagaming** [comment]
![Screenshot 2023-07-04 164410](https://github.com/sboxgame/issues/assets/15720147/5f917ecf-aa51-44a5-bb4f-fe85576d5e27)

**Comment by bakscratch** [comment]
I don't think this is our model, We have never had door models. I've looked through everything and can't find a reference anywhere to it.

**Comment by sugmagaming** [comment]
> I don't think this is our model, We have never had door models. I've looked through everything and can't find a reference anywhere to it. Ours would also have been to the correct scale.
I scaled them in hammer that's why the dimensions are a lil silly. That is so weird. I swear I remember placing these when I made the map and they were just assets that came with sbox. I even re-enabled all my projects in case its there but it still doesn't show up.

**Comment by anthonysharpy** [comment]
maybe it's these ones?

![image](https://github.com/sboxgame/issues/assets/55365296/f0bc1468-cea5-46a8-8c80-56a2d0f05af9)

they're here

https://asset.party/eurorp
