### ISSUE TITLE
Allow access to the FileSystem from game menus.

### ISSUE THREAD

**Issue by GermanDerpySkies** [sboxgame/issues#3560]
### For?

S&Box

### What can't you do?

I'm unable to call any methods when using `FileSystem.Data` (or any of the other ones such as `OrganizationData`) such as `OpenWrite` or `WriteAllText` from my game's main menu. Anytime I try it throws an "Object reference not set to an instance of an object" error.

### How would you like it to work?

I want this feature to work the same as when calling `Filesystem.Data` from the game, just being able to read and write to the files from the game menu. This way, the game menu and game itself can both access the same file as needed.

### What have you tried?

I've tried using ConVars but the system I tried felt disorganized and also I couldn't store binary formats. If there is a system that works I haven't been able to find it.

**Comment by DevulTj** [comment]
I've pushed something to fix this.
