### ISSUE TITLE
Project Setting, Map Selection 'This List & Any With Support'

### ISSUE THREAD

**Issue by kodi022** [sboxgame/issues#3568]
### For?

S&Box

### What can't you do?

I built my game around facepunch.flatgrass, but people made maps that support the game, but i have to manually find and add each of those maps to the list or lose flatgrass support switching to 'supported maps'

### How would you like it to work?

add 'This List & Any With Support' as a option, still show the map list to manually add maps

funny silly idea, to have it be kind of like a checklist if more options/combinations were needed
[  ] Unrestricted
[  ] Hidden
[X] Any With Support
[X] Manual List
[  ] Empty Map

or a drop down for like
Unrestricted/Hidden/Specific
and specific could lead to the 
[X] Any with support
[X] Manual List
[  ] Empty Map
[  ] Cartoony 
[  ] Small
[X] Large

### What have you tried?

either setting, i have to stick with 'this list only' right now

**Comment by CarsonKompon** [comment]
I could see them removing the "Manual List" and just having:
- Unrestricted
- Any with support
- Empty Map

Then there would be a section for adding additional maps to the list regardless of current setting. And maybe if you were on "unrestricted", then the "additional maps" for the gamemode would be the featured maps so-to-speak

**Comment by DevulTj** [comment]
this is gone - you'll want to implement this in your game menu
