### ISSUE TITLE
Thumbnail backgrounds are now Blue instead of transparent like they were before.

### ISSUE THREAD

**Issue by ShadowBrian** [sboxgame/issues#3572]
### Describe the bug

As of the recent video rendering update all thumbnails of recently compiled assets have a blue backdrop- this makes them terrible for use in games because the blue color doesn't always fit in where you're displaying asset thumbnails.

I think it was done to make the video not render a transparent backdrop but honestly it seems like something you could color in using the thumbnail background color on the asset.party website if it was transparent, making it still match the video rendering with the blue backdrop.

### To Reproduce

Compile any model and you'll see the backdrop is blue.

### Expected behavior

I would expect the backdrop of asset thumbnails to be transparent to maximise the usability of them in different UI settings and color schemes.

**Comment by CarsonKompon** [comment]
![image](https://github.com/sboxgame/issues/assets/5159369/816e61b8-3bc8-40eb-b8d6-1c9ed5f9750f)
You can fix this yourself for your own asset thumbnails by doing the above (The videos will have a black background however. Transparent videos would be awesome for integrating into any UI)
Result: https://asset.party/carsonk/arcade_machine_dev_01

**Comment by ShadowBrian** [comment]
Yeah I'd rather the video background just stay whatever color facepunch wants- transparant would be nice for sure but honestly if it's a blocker for making the thumbnails transparent just forget about it until later, the thumbnails is really what I'm after here as they completely clash with loads of use cases for them.

**Comment by CarsonKompon** [comment]
That's fair, transparent videos would be amazing for my game where the rotating model previews are shown on the left 
![image](https://github.com/sboxgame/issues/assets/5159369/c6fad27d-26d2-40a9-8a19-ddea9473824c)
Kinda forces me to re-design my UI to be blue-themed if I want it to look decent.

**Comment by ShadowBrian** [comment]
This was fixed a while back.
