### ISSUE TITLE
SceneObjects inside a game menu not working properly

### ISSUE THREAD

**Issue by Aero56** [sboxgame/issues#3573]
### Describe the bug

Things I've found:

- Deserializing clothing containers in a SceneObject rendered in a game menu don't work
- Values in a `GameEvent.Client.Frame` of a SceneObject are not updated correctly inside a game menu

### To Reproduce

Clothing container issue:
1. Inside a scene object try deserializing a json in a clothing container `Container.Deserialize( AvatarJson )`
2. The container is not updated

GameEvent.Client.Frame issue:
1. Add a scene object with a `GameEvent.Client.Frame`
3. Manipulate something outside of the event
4. It is not being updated inside the event

### Expected behavior

Clothing container issue:
The json is correctly deserialized

GameEvent.Client.Frame issue:
It should update inside the `GameEvent.Client.Frame`

### Media/Files

SceneObject ingame vs inside game menu

https://github.com/sboxgame/issues/assets/30606372/2c844daf-4fa7-4be4-b767-64024a04ec92

**Comment by xezno** [comment]
Is this still the case?

**Comment by Aero56** [comment]
Clothing thing seems to be resolved, but OnFrame doesn't work at all in game menu's anymore so have to go with tick
