### ISSUE TITLE
Widget Gallery - Colorbox behavior

### ISSUE THREAD

**Issue by bobberman** [sboxgame/issues#3583]
### Describe the bug

Colorpicker demo in Widget Gallery has two colors, I'll call them primary and secondary. When switching between them, they seem to set themselves to the other one before editing. Primary color is blue, you switch to secondary color (it's made blue), you make it green, then you switch to primary color and it's been set to green from its original blue color.

Could also be related to me using an ultrawide display?

### To Reproduce

1. Go to Widget Gallery
2. Go to ColorPicker
3. Change primary color, then switch to secondary color.

### Expected behavior

Primary and secondary option should keep its color after switching to another one.

### Media/Files

![sbox-dev_c3AmUIf1Mt](https://github.com/sboxgame/issues/assets/52549023/fd6bb325-ede6-402d-a4c6-2a5d5957f375)

### Additional context

Windows 10, RTX 4080, i9-13900k, 3440x1440 resolution

**Comment by cr4yz** [comment]
The behaviour for the colors at top is to remember/preview the original color vs currently picked color, so whatever the color picker initializes to the one at left will always have that color in case you want to revert.

The palette at the bottom should give the behaviour you're after

**Comment by cr4yz** [comment]
Closing this, lemme know if I misunderstood or you have ideas to improve it.
