### ISSUE TITLE
Models created with hammer which use a Cloud material have an error material on the client in-game.

### ISSUE THREAD

**Issue by dch-GH** [sboxgame/issues#3595]
### Describe the bug

Says on the tin.

### To Reproduce

1. Create a cube in hammer. 
![image](https://github.com/sboxgame/issues/assets/66768086/bac9360f-13a3-4db9-9f0a-9dcd492349dc)
2. Get a Cloud material and apply it to the cube.
![image](https://github.com/sboxgame/issues/assets/66768086/8f235455-1114-4903-82a4-b3016ee4d069)
![image](https://github.com/sboxgame/issues/assets/66768086/a98c41e4-9ca8-4fce-b92f-87b952a72492)
3. Create a model from it.
![image](https://github.com/sboxgame/issues/assets/66768086/f7257774-cc41-4d7f-836a-ff9420714c7c)
4. Load it in game, on the server it works fine, on the client it does not. (I am testing locally with 2 instances, that might be the issue? Maybe if it were a true remote client it would work?)

Server: 
![image](https://github.com/sboxgame/issues/assets/66768086/775f5df2-aa45-4900-a27d-886d04905bb1)
Client: 
![image](https://github.com/sboxgame/issues/assets/66768086/9e2b1d64-7022-403c-a8c9-8113a55e7e98)

### Expected behavior

I want the materials to work on both the server and the client.

**Comment by handsomematt** [comment]
#3075
