### ISSUE TITLE
Every time when I open the game it shows the loading screen and then crashes.

### ISSUE THREAD

**Issue by The1AndTrueWeirdKid** [sboxgame/issues#3599]
### What it is?

So every time when I open sandbox it just shows the loading screen and then it shows do you want to close the game or wait and I press on wait and then a couple of seconds later it crashes. can I get help?

### What should it be?

So the game is supposed to load without crashing.

**Comment by handsomematt** [comment]
what are your system specs? can you post your log file? are you using intel graphics?

**Comment by The1AndTrueWeirdKid** [comment]
ɢᴘᴜ: AMD Ryzen 1600X CPU @ 3.60GHz (6CPUs), ~3,6GHZ
ɢᴘᴜ: MSI GeForce GTX 1080 8GB Gaming X GDDR5
ᴍᴏʙᴏ: X370 Gaming Pro Carbon
ʀᴀᴍ: HyperX Fury DDR4 2666 C15 8GB
ᴘꜱᴜ: Corsair TX 550M
