### ISSUE TITLE
razor string doesn't support accent

### ISSUE THREAD

**Issue by dictateurfou** [sboxgame/issues#3607]
### Describe the bug

the character é , è and other is replaced by ?
if i write Crée ton personnage the result is here
![13dd73316d3a037f67f0552e037bc747](https://github.com/sboxgame/issues/assets/12927420/ad996c57-9827-405f-8e4d-a109b81675cc)

### To Reproduce

in razor template
```html
 <h2>Crée ton personnage</h2>
```
### Expected behavior

accents should work without make code
actually i have make little function for replace char with accent (exemple)
```csharp
public string encodeChar(string text)
	{
		Dictionary<string, string> Escaped = new Dictionary<string, string>() { { "é", "\u00e9" } };

		foreach (KeyValuePair<string, string> data in Escaped)
		{
			text = text.Replace(data.Key, data.Value);
			// do something with entry.Value or entry.Key
		}
		Log.Info(text);
		return text;
	}
```

**Comment by cr4yz** [comment]
That's probably the font itself missing glyphs with accents.  Could you upload the font here?

**Comment by dictateurfou** [comment]
sorry for the late reply, I hadn't seen it.
The font have the accent isn't a problem of my font i use in multiple projec andt with the basic font used by the game is the same result but with unicode its work.
github doesn't support ttf for upload file i add link of font
https://www.fontmirror.com/pricedown (website where im download)
or with discord upload
https://cdn.discordapp.com/attachments/929305618911752282/1131471014501564536/Pricedown.ttf

**Comment by cr4yz** [comment]
Thanks, I'll have a closer look at it and see what's up.

**Comment by cr4yz** [comment]
I'm unable to reproduce:

![sbox-dev_abPdgLKPgg](https://github.com/sboxgame/issues/assets/9637557/eaef51cb-03a0-47de-917a-0eaf0ed02bca)

Are you able to put together a very simple project with the font included and a UI element to show it?

**Comment by dictateurfou** [comment]
it's strange but I copied and pasted my template on a new game and I don't have this problem so I can't reproduce the problem on new project.
but I still have the problem on my main project that I created several months ago and I don't know why given that I haven't changed anything between the 2 projects.

I can invite you to my main repo if you want?

**Comment by cr4yz** [comment]
> I can invite you to my main repo if you want?

Yeah please do

**Comment by dictateurfou** [comment]
i send you an invite the path of the file is ui/CharCreator.razor
https://github.com/dictateurfou/slife/invitations (idk if link here work i just copy from github xD)

**Comment by garrynewman** [comment]
Is the file saved with utf8 encoding?

**Comment by dictateurfou** [comment]
after some checking it doesn't seem to be in utf8, i opened the files on vscode to check and it also had ? in the code, while on the new project I made the file does not have this problem.
 I haven't touched anything my visual studio is basic I don't even know how to change its xD

**Comment by dictateurfou** [comment]
I managed to solve the problem by adding its in my .editorconfig "charset = utf-8" but I still don't understand why the project I created recently does not need its but as long as it works.
I don't know if you want me to close the issue so I'll let you do it thank you
