### ISSUE TITLE
Cannot change Launch Configuration map from asset.party

### ISSUE THREAD

**Issue by skyfezzer** [sboxgame/issues#3613]
### Describe the bug

The project settings window holds the focus, making the selection of the map impossible.
If you close the project settings window in order to select a map, you get a 

` 09:04:48   Interop QWidget was null when calling hasFocus`

### To Reproduce

1. Right click on your current game, select "Project Settings"
2. Under development, select Launch Configs
3. Create a new Configuration
4. Under Identity, Map, click on the folder button, and select From asset.party
5. The map selection window is behind the project settings, unfocusable.

### Expected behavior

The map selection window should appear above the project settings window, and should be interactable.

**Comment by xezno** [comment]
Should be fixed on next build

https://github.com/sboxgame/issues/assets/12881812/caad12c0-6f7f-478a-8217-81570fa58aa9
