### ISSUE TITLE
Local libraries cant be found properly causing an error

### ISSUE THREAD

**Issue by PixelQubed** [sboxgame/issues#3614]
### Describe the bug

When you reference a local library, you can't launch the gamemodes menu preventing you from seeing it if you want to edit it before pushing it to asset.party.
<img width="1073" alt="sbox-dev_0Aph20iDBb" src="https://github.com/sboxgame/issues/assets/32498714/8c6a6741-c00c-481e-abab-8712880d272c">

### To Reproduce

1. Create a gamemode.
2. Create a library.
3. In the gamemode, go to the project settings and reference the library you created. Here is an example.
<img width="962" alt="sbox-dev_jWAD5KZOH0" src="https://github.com/sboxgame/issues/assets/32498714/592365d9-2f55-4a58-b3dc-e825e07ce0fe">

4. Restart S&Box and observe the error.
5. Try starting the gamemode via the menu.
6. Observe the blank menu caused by this error.
<img width="1921" alt="sbox-dev_VRdf7Bv5AW" src="https://github.com/sboxgame/issues/assets/32498714/9c995f2e-0611-483d-9060-2f4e6fc9c0cc">

### Expected behaviour

This error shouldn't exist since you can force the gamemode to start by bypassing the menu screen and using a launch config. I have checked, and the library does get loaded by the gamemode, so this error is just some weird bug. If the library were missing, the gamemode wouldn't compile because the gamemode depends on the library even to compile in the first place. Hopefully, this gets fixed soon, so we don't have to deal with this any more because it's annoying to work around.

**Comment by PixelQubed** [comment]
Is there any ETA on this since we can't just remove the library from our gamemode? It won't compile without it now.

**Comment by Longboyy** [comment]
I seem to be running into the exact same problem as mentioned.

**Comment by PixelQubed** [comment]
Well, this is now causing another issue, it seems. The menu apparently stays active when trying to enter the game sometimes so the cursor is on the screen and its a pain in the ass, especially when you're trying to restart the gamemode.

**Comment by Game4Freak** [comment]
I found a quite reproducable workaround.

- Remove the library from the editor
- Remove the library reference from the gamemode
- Completely close the editor (the start menu aswell)
- Start the editor and readd the library
- Readd the library reference on the gamemode

You have to restart the editor else the complier might not be updated correctly

**Comment by PixelQubed** [comment]
> I found a quite reproducable workaround.
> 
> * Remove the library from the editor
> * Remove the library reference from the gamemode
> * Completely close the editor (the start menu aswell)
> * Start the editor and readd the library
> * Readd the library reference on the gamemode
> 
> You have to restart the editor else the compiler might not be updated correctly

Yeah this fix doesn't work.

**Comment by kurozael** [comment]
This should now work in that it will find local referenced packages if we are not ourself a remote package. That is to say if you load the menu locally for the project, it will find local packages.
