### ISSUE TITLE
Calling any DebugOverlay function from inside a GameManager constructor causes a crash to desktop.

### ISSUE THREAD

**Issue by dch-GH** [sboxgame/issues#3616]
### Describe the bug

Try to call a DebugOverlay function in the constructor.

### To Reproduce

Self-explanatory.

### Expected behavior

It's cool if DebugOverlay can't function correctly in the game constructor because maybe a system responsible for it isn't ready yet, but probably shouldn't be crashing to desktop.

**Comment by chrisspieler** [comment]
DebugOverlay also crashes if you call it from UI in a menu-only game. Maybe it's the same crash, so I'm mentioning it here instead of making a new issue.
