### ISSUE TITLE
`NetRead` Needs Some Love

### ISSUE THREAD

**Issue by LeQuackers** [sboxgame/issues#3620]
### What it is?

Currently the `NetRead` struct isn't looking to good; it's a pain to use because its generic methods are locked-in with `unmanaged` and `class` constraints, which means if you use it in some other generic, then it also gets locked-in with the same constraints. Also, `NetRead` is struct while `NetWrite` is a class, which is a bit confusing.

### What should it be?

`NetRead` should probably be a class and implement methods that are equivalent to `NetWrite`, i.e.:

|What it currently is:|What it should be:|
|-|-|
|`T[] ReadArray<T>(T[] val) where T : unmanaged`<br />`T[] ReadArrayClass<T>(T[] val) where T : class`|`T[] ReadArray<T>()`|
|`Span<T> ReadData<T>(Span<T> _) where T : unmanaged`|`Span<T> ReadSpan<T>()`|
|`T ReadData<T>(T _) where T : unmanaged`<br />`T Read<T>() where T : unmanaged`<br />`T ReadClass<T>(T def = null) where T : class`|`T Read<T>(T def = default)`|

**Comment by garrynewman** [comment]
NetRead will be replaced with ByteSteam
