### ISSUE TITLE
Hammer: Prop Scale Only Uses Highest Value

### ISSUE THREAD

**Issue by hadynpark** [sboxgame/issues#3621]
### Describe the bug

**prop_physics** only scales a prop by the highest axis.

### To Reproduce

1. In hammer place a **prop_physics**
2. Under **Transform** set **Scale**  X: 0.1 Y: 0.1 Z: 2
3. The model appears to be scaled correctly in Hammer
4. Load the map in game and the prop will appear to be scaled by 2 in every axis.

### Expected behavior

The Prop should appear in game as it does in hammer

### Media/Files

![image](https://github.com/sboxgame/issues/assets/48180413/fc4c02ad-a7d0-478a-b91c-91a9eb49cf69)
![image](https://github.com/sboxgame/issues/assets/48180413/562512a7-14fa-4a1d-a4b1-4082d52f95cc)

**Comment by Gmod4phun** [comment]
Source 2's scale is uniform, aka you can't scale entities along a certain axis individually. Iirc devs said it most likely isnt gonna change, certainly not anytime soon, which is a shame.

**Comment by aylaylay** [comment]
You can't non uniformly scale a convex collision, this isn't possible and never will be. You should be able to scale anything static but nothing tied to physics.
