### ISSUE TITLE
Maps section missing in Game Setup

### ISSUE THREAD

**Issue by yuberee** [sboxgame/issues#3622]
### Describe the bug

Opening your Project Settings and navigating to Game Setup shows that the Maps section is missing, the .addon file still contains info about it.

### Media/Files

Screenshot from a video made a few months ago
![image](https://github.com/sboxgame/issues/assets/59583743/6ba2f90e-379c-4b71-b929-a681cf32af29)

Screenshot taken today
![image](https://github.com/sboxgame/issues/assets/59583743/9f908375-c62f-4db8-93ad-5d4203f6a67b)

**Comment by DevulTj** [comment]
This was intended, it's up for your game menu to set up preferred maps now
