### ISSUE TITLE
Login not possible in dev editor 

### ISSUE THREAD

**Issue by SteveExodus** [sboxgame/issues#3623]
### Describe the bug

Well..lets start with the newest bug :D 

1. I cannot login into the dev editor anymore...Dunno what changed but its like on the picture

2. I still have the black screen if i launch s&box :( 
Newest windows10 updates, newest 3070 nvidia driver installed and .net 7.0.8

### To Reproduce

not possible :D?

### Expected behavior

login and no blackscreen lol

### Media/Files

![grafik](https://github.com/sboxgame/issues/assets/139625388/5eb9a157-9bfd-42a1-9a5a-d8599bf91b5b)
[Log.log](https://github.com/sboxgame/issues/files/12061215/Log.log)

**Comment by aylaylay** [comment]
Are you using a VPN

**Comment by SteveExodus** [comment]
No

**Comment by handsomematt** [comment]
Something on your machine or network is messing with or blocking your connection. This could be a proxy, firewall or antivirus.

Nothing can be done our end.
