### ISSUE TITLE
Lag compensation should be a library

### ISSUE THREAD

**Issue by Weldify** [sboxgame/issues#3624]
### What it is?

Currently lag compensation is a method on `Entity`. Its inconvenient to use within components, etc.

### What should it be?

make a `LagCompensation` library similar to the `Prediction` library

**Comment by handsomematt** [comment]
Why

**Comment by Weldify** [comment]
I enable it in weapon code in a component, currently its an entity method which made me confused for a while, would be more neat as a library

**Comment by garrynewman** [comment]
what the fuck

**Comment by Weldify** [comment]
It doesn't make sense to be on entities though - every entity has the method, does that mean I can turn it on from any entity even if it's unrelated to the pawn at all? Does it even have to do anything with the entity? Having it separate will make it more clear, if we had prediction stuff on the entity that would suck, so why should lag compensation be like this

**Comment by garrynewman** [comment]
Show me how it'd work

**Comment by Weldify** [comment]
```cs
using (LagCompensation.Enable())
{

}
```

Separating it also makes room for future   additions if need be, for example `IsEnabled` to see whether lag compensation is enabled (although I dont have a use case for it right now, its just an example)

**Comment by handsomematt** [comment]
> Does it even have to do anything with the entity?

it's a static method

**Comment by brannanz** [comment]
Why

**Comment by trende2001** [comment]
Why

**Comment by Weldify** [comment]
Are you guys **REALLY** sure about this? IMO currently it looks kinda shite
![image](https://github.com/sboxgame/issues/assets/66477673/e5cfc499-e2e4-4573-9bf4-559ecf386cf1)
I have to do this within components, since this is a static method i cant just use the `Entity` property

```cs
using ( LagCompensation.On() )
{
}
```
Wouldnt this be a lot nicer?
