### ISSUE TITLE
Interpolation is incorrect

### ISSUE THREAD

**Issue by Weldify** [sboxgame/issues#3629]
### Describe the bug
Interpolation seems to always be a bit off. As you increase the ping, the interpolation also starts jittering

### To Reproduce

1. Observe interpolated entities at non 0 ping

### Expected behavior

Lag compensation should make entity positions and velocities match exactly as the client has seen them.
Interpolation shouldnt lag behind.

### Media/Files

no fakelag
https://github.com/sboxgame/issues/assets/66477673/d73734a0-8c7a-49ef-8a41-7ad1b917c3d8

200 ping
https://github.com/sboxgame/issues/assets/66477673/ab80035d-d4b1-4247-a6b2-b93fb12b25c6

200 ping in the s&box gamemode
https://github.com/sboxgame/issues/assets/66477673/3ca725db-5be1-45c5-b231-202a08b469c2

Notice the jitter in videos with >0 ping

**Comment by handsomematt** [comment]
i'm confused what this has to do with lag compensation

the moving platforms have a velocity, your player controller should inherit the velocity

**Comment by Weldify** [comment]
Conna helped me investigate it a little. It turns out to be a problem exclusively with interpolation, I was using lag compensation wrong.
