### ISSUE TITLE
game crash on logo

### ISSUE THREAD

**Issue by andreyp1mpl** [sboxgame/issues#3633]
### Describe the bug

the game crashes the first time you start the game

### To Reproduce

1. run s&box with steam
2. if you see facepunch logo and it crash you got the bug

### Expected behavior

game's menu

### Media/Files

[Log.log](https://github.com/sboxgame/issues/files/12064016/Log.log)

### Additional context

Specs: windows 10
16 gb ram
xeon e3 1270
1050 ti

**Comment by handsomematt** [comment]
#3579
