### ISSUE TITLE
Consider Making `Var.Write(NetWrite)` and `Var.Read(NetRead)` Protected

### ISSUE THREAD

**Issue by LeQuackers** [sboxgame/issues#3634]
### What it is?

Currently we're able to network [several different types](https://wiki.facepunch.com/sbox/Networked_Types#networkabletypes), but collections are definitely a sore spot. Implementing whatever collection you need by deriving from `Var` would be great, but because `Var.Write(NetWrite)` and `Var.Read(NetRead)` are internal, it can't be done.

### What should it be?

Making `Var.Write(NetWrite)` and `Var.Read(NetRead)` protected would allow `Var` to be derived, which would add a lot of flexibility with networking. With [`NetRead` being replaced with `ByteSteam`](https://github.com/sboxgame/issues/issues/3620#issuecomment-1636667532), I'd assume `Var` is going to be cleaned up as well; if common collections like `HashSet`, `Stack`, `Queue`, etc. aren't added during that, then we should at least have the ability to implement them ourselves.

**Comment by Weldify** [comment]
If `Var` is what I think it is, it's awesome! Is it for defining how a type is networked?
Would be really cool to be able to do manual serialization by type
