### ISSUE TITLE
Networked properties no longer being replicated to client after mounting package

### ISSUE THREAD

**Issue by chrisspieler** [sboxgame/issues#3635]
### Describe the bug

It seems that mounting an addon or library can cause completely unrelated entities to stop sending updated values for their `[Net]` properties to clients.

### To Reproduce

1. Import the attached game project
2. Play the game
3. Watch the console for a few seconds to confirm that the numbers being logged keep ticking up
4. After the "adding plugin" line is logged, observe that the numbers being logged have stopped increasing

### Expected behavior

Mounting an addon or library should not break networking for existing entities.

### Media/Files

[net_repro.zip](https://github.com/sboxgame/issues/files/12064338/net_repro.zip)

**Comment by handsomematt** [comment]
Should be good now, this was also fucking up the Sandbox gamemode.

**Comment by chrisspieler** [comment]
Works for me now. Thank you!
