### ISSUE TITLE
Deriving from BasePhysics causes a whitelist error.

### ISSUE THREAD

**Issue by Igrium** [sboxgame/issues#3636]
### Describe the bug

I was trying to debug a whitelist error in my code, and I found that one (dead simple) entity was the culprit. All it did was derive from `BasePhysics` and set the model:

```cs
public partial class AppleEntity : BasePhysics
{

    public override void Spawn()
    {
        base.Spawn();
        SetModel("models/computer/apple2.vmdl");

        PhysicsEnabled = true;
        UsePhysicsCollision = true;

        Tags.Add("solid");
        Log.Info("spawning");
    }
}
```

Commenting out this class made it load properly. I eventually figured out that if I switched it to derive from `ModelEntity` and manually enabled physics, it worked.

### To Reproduce

1. Make an addon, and put an entity in it that derives from `BasePhysics`
2. Profit (?)

See our non-working commit for an example: https://github.com/michaelsshaw/sbox_pcmod/blob/93b1ae2091b2783583c9bcc12f10f681131acb4e/code/game/AppleEntity.cs

### Expected behavior

It should load into the game without a whitelist error.

**Comment by Redhacker1** [comment]
duplicate #3592
