### ISSUE TITLE
Include base game menu when creating a new project

### ISSUE THREAD

**Issue by yuberee** [sboxgame/issues#3637]
### For?

S&Box

### What can't you do?

Right now you only get the Game and Pawn when starting a new game, and the base game menu is used by default.
This conchfuses new developers that are looking to customize their game menu but aren't able to find it.
It is also more convenient to have the base game menu shipped with new games, that way you can start modifying it and build on top of it instead of creating your own from scratch/copying someone else's.

### How would you like it to work?

Together with the Game and Pawn files, ship also the game menu files with new games.

### What have you tried?

Without mentioning new developers and new games, I'm always putting off creating my own menu since I'm not the best at UI.
Modifying a menu that's already there would be much easier.

**Comment by DevulTj** [comment]
Planned - the shooter template game ships a pretty small standard menu right now as a test
