### ISSUE TITLE
Have a way to access a game projects assets like a content project

### ISSUE THREAD

**Issue by NotGaylien** [sboxgame/issues#3639]
### For?

S&Box

### What can't you do?

Right now i have assets, models, materials, particles in various game projects i made them for originally.

Although when im doing stuff i have been using assets from other game projects mostly as placeholders or just because it also fits well in my current game project and so on.

with the one game project stuff this isnt possible as them assets will only show up if i take them all out the game project and put them into a content project.

### How would you like it to work?

A way to access only the assets within a game project as if they were a content project. and not load any of the game specific stuff.

That or just automatically create a content project which contains them assets whenever you have a game project.

### What have you tried?

I could upload them to asset party and use them like that,
But if i want to quickly edit an asset i will have to 
close my current game project, 
go into that other game project, 
make my changes to the asset, 
upload it to asset party, 
go back to my first game project i was working on.
thats a massive nightmare personally.

Or rip all assets out of game projects and create an additional content project along side that game project.
and do that going forward.
which could work but it also a pain.

Or create copies of them assets between game projects so they have local versions, but i want to keep my assets as a single asset and not have duplicates if possible.

### Additional context

I know avoiding asset file paths clashing and so on was an issue.
but this has made artists (i say artists but it might only be me dealing with this) have a much worse time.

**Comment by eagleonedevteam** [comment]
This has completely been devastating for content creation. I cannot create maps because I use assets that are from different projects, especially because we have an asset repo just for licensed assets separate of our game projects.

**Comment by handsomematt** [comment]
Put stuff in content projects, they are game independent
