### ISSUE TITLE
Setting a props PhysicsEnabled to false or it's PhysicsBody MotionEnabled to False resets scale

### ISSUE THREAD

**Issue by Owningle** [sboxgame/issues#3641]
### Describe the bug

Setting a props PhysicsEnabled to false or it's PhysicsBody MotionEnabled to False resets scale to 1.

### To Reproduce

Scale a prop in hammer to scale 2. Set that props PhysicsEnabled to false, try walking on it, or check it's physicsbody scale.

### Expected behavior

Scale should remain the same

**Comment by aylaylay** [comment]
Should be fixed now.

**Comment by Owningle** [comment]
Seems good to me, thanks.
