### ISSUE TITLE
Last Game Project is loaded in content mode asset browser.

### ISSUE THREAD

**Issue by NotGaylien** [sboxgame/issues#3642]
### Describe the bug

I last had for example, the smallfish game Goblintide game project selected.

When i next open s&box and chose content mode.

it loads all my content projects, but also seems to load up goblintide in the asset browser,
and the only game projects assets that are loaded are goblintide.
then all the normal content projects aswell as usual.

### To Reproduce

1. Open s&box, and choose a game project.
2. close s&box or go File -> close game project.
3. go into content mode.

the last selected game project will be loaded into the asset browser.

### Expected behavior

Either this is meant to happen, but its meant to load all game projects assets.
or its meant to load none of them.

im not sure which is intended. 
personally i would prefer all game projects assets to be loaded.

**Comment by xezno** [comment]
Hey, so the intention here is that no game project is mounted - the idea is that there's always a maximum of 1 game project enabled at once. I've gone ahead and made it so that content mode mounts no games, let me know if this is shit.

**Comment by NotGaylien** [comment]
Looks good to me!

after the discussion about content addons and game addons a few days ago i agree with only content projects being mounted,
i take back that game content being mounted idea.

thanks alex!
