### ISSUE TITLE
Package.IsMounted when called on client does not return true if package was installed on server

### ISSUE THREAD

**Issue by chrisspieler** [sboxgame/issues#3644]
### Describe the bug

After installing a package on a server, calling [Package.IsMounted()](https://asset.party/api/Sandbox.Package.IsMounted(bool,bool)) on the package from a client will return false.

### To Reproduce

1. In server code, mount a package
2. In client code, find all packages matching a query that would contain the installed package
3. For each of the returned packages check `p => p.IsMounted()`
4. Even though the client has access to the code and assets of the mounted package, `p.IsMounted()` returns false.

### Expected behavior

If a client has access to the code and assets of a package, then from the perspective of a client, that package should be considered as mounted.

### Additional context

If called from a server, Package.IsMounted behaves as expected.

This is an issue I've encountered when trying to make a plugin system using libraries. I want to show a list of available plugins on Asset Party, but I want to hide the ones that are already installed.

**Comment by chrisspieler** [comment]
The workaround to this issue is probably to keep a list of mounted idents on the server and network it to clients, but I can't do that because of issue #3635

**Comment by handsomematt** [comment]
This was only happening on listen server hosts as far as I could tell, should be fixed now.

**Comment by chrisspieler** [comment]
Awesome, works now!
