### ISSUE TITLE
Player Resize glitch

### ISSUE THREAD

**Issue by p7rco** [sboxgame/issues#3645]
### Describe the bug

Make the player bigger or smaller

### To Reproduce

Resize the sedan car to bigger/smaller
Get in the car
Get out of the car

### Expected behavior

Player get bigger or smaller

### Media/Files

![Desktop Screenshot 2023 07 17 - 18 32 13 57](https://github.com/sboxgame/issues/assets/139789602/e22635df-0f58-4227-9569-685aa515b44d)

### Additional context

Found the glitch today

**Comment by aylaylay** [comment]
Not an engine issue.
