### ISSUE TITLE
Informative server menu

### ISSUE THREAD

**Issue by darkfated** [sboxgame/issues#3651]
### For?

S&Box

### What can't you do?

View detailed information about the server

### How would you like it to work?

On the example of the same Rust, where when you select a server (when you click), a menu opens. Detailed information is written there, as well as a description of the server that the owner can write. As part of the s&box, you can also add even more things for customization by the owner (for example, a button to go to the server's website), if you wish. So it will be easier for an ordinary user to navigate among the servers and find a certain one to taste

### What have you tried?

Nothing

**Comment by DevulTj** [comment]
all the UI is in flux and will be remade a hundred times before we release - we'll sort something like this out as time goes on
