### ISSUE TITLE
Sphere collider does not Scale properly with models

### ISSUE THREAD

**Issue by youarereadingthis** [sboxgame/issues#3655]
### Describe the bug

If you set the `Scale` and then `SetupPhysicsFromSphere`, it can scale the collider to be less than or greater than the model. It does the same thing if you set Scale after setting up physics.

### To Reproduce

1. Init sphere collision with `SetupPhysicsFromSphere` of `32f` radius.
1. Set a ModelEntity's `Scale` to `2.0f` or `0.5f`.
2. Enable debug collision view on server/client.
3. Notice the inconsistency, as if the collider were double-scaled.

### Expected behavior

Until today, setting `Scale` scaled up or down the collider to fit with the model.

### Media/Files

Models pictured are scaled to `3.0f` and `1.5f`.
![0YdNucP](https://github.com/sboxgame/issues/assets/100040020/46287cda-7e27-49a2-a909-64b27b834e6c)

**Comment by garrynewman** [comment]
Can you give me more explanation on this?

**Comment by aylaylay** [comment]
If this started happening very recently, I might have caused it so I'll have a look

**Comment by aylaylay** [comment]
Should be good now

**Comment by aylaylay** [comment]
Server should have always been correct, it was client being out of sync
