### ISSUE TITLE
Overriding LoadSavedGame isnt work as expected

### ISSUE THREAD

**Issue by WildFearless** [sboxgame/issues#3659]
### Describe the bug

![image](https://github.com/sboxgame/issues/assets/58618673/3880f8d3-6092-4a20-ad44-b0b99b2fc299)

There's my save file. Overriding` public override void LoadSavedGame( SavedGame save ) { } `does not make it get called when a client joins. It does absolutely nothing. 

Game.CurrentSavedGame and Game.Menu.SavedGames also is null.

### To Reproduce

Have a save file.

Click on load game -> select the save

Create a server

Load a server, put the debugger on LoadSavedGames, it never goes into it because its never called.

### Expected behavior

LoadSavedGame should be getting called when selecting a save file, then creating a server on said game mode.

### Media/Files

![image](https://github.com/sboxgame/issues/assets/58618673/3880f8d3-6092-4a20-ad44-b0b99b2fc299)

### Additional context

If you need more information, let me know

**Comment by kurozael** [comment]
@WildFearless this isn't actually a bug with Saved Games. LoadSavedGame would get called, but the issue here is actually with the default menu, when you select a Saved Game it's creating a lobby and setting the Saved Game but then returning you to the main menu. So when you then click Create Game it's discarding the current lobby and making a new one without the Saved Game.

I'll fix this so that selecting a Saved Game in the default menu will immediately load into server.

**Comment by WildFearless** [comment]
> @WildFearless this isn't actually a bug with Saved Games.
> 
> LoadSavedGame would get called, but the issue here is actually with the default menu, when you select a Saved Game it's creating a lobby and setting the Saved Game but then returning you to the main menu. So when you then click Create Game it's discarding the current lobby and making a new one without the Saved Game.
> 
> I'll fix this so that selecting a Saved Game in the default menu will immediately load into server.

Thank you so much, i wasnt sure if i was doing it wrong. Thing is, will you still access to create server screen? Because you need to select a name, max players and the map. And some modes only work on specific map and the default map option is currently broken

**Comment by kurozael** [comment]
Hey @WildFearless you can try it now, should be good. Unfortunately selecting a game to load will mean it loads immediately with the map it was saved on, the max players it was set at when it was saved as well. You can completely override this behaviour with a custom menu though :)

**Comment by WildFearless** [comment]
> Hey @WildFearless you can try it now, should be good. Unfortunately selecting a game to load will mean it loads immediately with the map it was saved on, the max players it was set at when it was saved as well. You can completely override this behaviour with a custom menu though :)

Yeah, that or having backend for savedgames but that could be more complicated.

I'll test it this evening and come back to confirm that it is working. Thanks

**Comment by WildFearless** [comment]
I confirm that it now gets called, for some reason its bugging out my inputs and dismisses the creation of the pawn and its attribute. I'll have to take the time to investigate

**Comment by kurozael** [comment]
Worth noting that LoadSavedGame should get called after all entities on the map have been loaded. You should take that into consideration 😊

**Comment by WildFearless** [comment]
> Worth noting that LoadSavedGame should get called after all entities on the map have been loaded. You should take that into consideration 😊

Is there an example or a wiki link for this, or any facepunch mode that uses it? Else i'll ask around in the discord or figure it out...

**Comment by kurozael** [comment]
Yep you can check out facepunch/sbox-forsaken which uses it 👍

**Comment by WildFearless** [comment]
Cheers !
