### ISSUE TITLE
Cannot access BaseType of a class from TypeLibrary

### ISSUE THREAD

**Issue by Mbk10201** [sboxgame/issues#3660]
### Describe the bug

We cannot access to the basetype of a class,
Its says: Whitelist Error: System.Private.CoreLib/System.Type.get_BaseType()

Its wasn't supposed that `TypeLibrary` provide a full whitelist of system.reflection ?

### To Reproduce

```
foreach ( var type in TypeLibrary.GetTypes().Where( x => x.IsClass && !x.IsAbstract ) )
{
    if ( type.TargetType.BaseType is not null )
    {
        Log.Info( type.TargetType.BaseType.Name );
    }
}
```
### Expected behavior

To be able to access the base type through the `TargetType.BaseType`

**Comment by quntherdev** [comment]
Same issue here! Very annoying.

**Comment by Game4Freak** [comment]
There was an issue ~1 year ago about this but it's still not added :(
https://github.com/sboxgame/issues/issues/2611

**Comment by Game4Freak** [comment]
Thanks Garry :)
