### ISSUE TITLE
Manual networking pipeline

### ISSUE THREAD

**Issue by KelpyCode** [sboxgame/issues#3663]
### For?

S&Box

### What can't you do?

Currently, the networking system efficiently utilizes the [Net] attribute on properties for most entity-based networking. However, there seems to be a lack of ease in manually creating a networked pipeline and performing read and write operations. 

 I believe implementing this following improvement would greatly enhance the networking capabilities of s&box and provide greater flexibility for developer

### How would you like it to work?

I propose the implementation of a named pipeline instance on both the client and server sides, enabling data transmission through the NetWrite and NetRead classes. The intended functionality is akin to a WebSocket client/server setup but without any additional dependencies.

This enhancement would serve multiple purposes, including facilitating Client to Server Remote Procedure Calls (RPC) and enabling specialized networking. Moreover, it would greatly simplify the process of handling anti-cheat network communications.

Please excuse possible issues with the following pseudo code (since I'm currently on mobile)

```cs
// Create new named instance
NetPipeline n = new("pipeline1");
// If instanced on client, the connection goes to the server
// If instanced on server, you can target single client connections or multiple

class NetPipeline {
// When I'm server
void OnMessageFromClient(Client client, NetRead Nr) {
  NetWrite nw;
  this.Send(client, nw);
}

// When I'm client
void OnMessageFromServer(NetRead nr) {
  NetWrite nw;
  this.Send(nw);
}
}



```

### What have you tried?

I've tried implementing custom networking by "abusing" INetworkSerializer but that seems very limiting, especially the control on *when* to send data and communicating from client to server.

**Comment by DevulTj** [comment]
A form of this is planned. We plan to possibly deprecate INetworkSerializer, NetRead/NetWrite, etc.

https://sbox.facepunch.com/news/retooling
