### ISSUE TITLE
[Hammer Editor] Object Properties - Implement "Copy Keys" and "Paste Keys"

### ISSUE THREAD

**Issue by LiminalCrab** [sboxgame/issues#3665]
### For?

Hammer

### What can't you do?

When attempting to copy the keys from your object properties window, "(TODO: Hammer clipboard data on the system clipboad.)" is copied instead. 

Implementing this would give us a quick and easy way to not only share our entities with one another in a quick copy and paste, but make it easier to quickly look through and adjust the settings in a notepad if need be.

### How would you like it to work?

I would like to click "Copy Keys" and have it copy all of the keys and their set values to my clipboard. I would like to click "Paste keys" in the Object Properties and have it paste the content of my "Copied keys" into the Object Properties. 

### What have you tried?

You can copy them individually at the moment, though the naming is off a bit. I honestly wouldn't mind it stuck like this for now so long as we just had it implemented. 

```
This is Quadratic Attenuation
{
	attenuation2 = "0"
}

This is Linear:

{
	attenuation1 = "1"
}


```

**Comment by robotboy655** [comment]
Related: https://github.com/sboxgame/issues/issues/2815

**Comment by LiminalCrab** [comment]
You can control + shift select and copy

{
	cubemapfogheightstart = "2000.0"
	cubemapfogheightwidth = "0.0"
	cubemapfogfalloffexponent = "2.0"
	cubemapfogenddistance = "6000.0"
	cubemapfogstartdistance = "0.0"
	cubemapfogheightexponent = "2.0"
}
