### ISSUE TITLE
D3D error launching game, freezing editor

### ISSUE THREAD

**Issue by webcrawls** [sboxgame/issues#3670]
### Describe the bug

I'm working on a game that involves pretty heavy use of Razor UI. When launching the game from the editor, I get stuck on the "Loading Server" screen , and the console spits out many D3D errors.

I'm not exactly sure on the cause of the error, but it could have something to do with rendering overlapping `ScenePanel`s and transparency? That's the only "special" thing my game does that I can think of.

### To Reproduce

1. Launch s&box editor
2. Open game project that triggers error ([Link to commit triggering error](https://github.com/webcrawls/sandtype/tree/219be9936f2cb2be97e6c6b5085a5c74fbab8f2e))
3. Run game through editor
4. Encounter crash

### Expected behavior

The game should not crash.

### Media/Files

- [Log of the original error I encountered](https://gist.github.com/webcrawls/91dc76cd623ea21a83f28fc619e79683)
- [Link to the commit triggering the issue](https://github.com/webcrawls/sandtype/tree/219be9936f2cb2be97e6c6b5085a5c74fbab8f2e)

this code is unholy and I take full responsibility for that. if you dare unravel the monstrosity, the relevant bits may be:
- [Hud.razor](https://github.com/webcrawls/sandtype/blob/219be9936f2cb2be97e6c6b5085a5c74fbab8f2e/code/UI/Hud.razor), the `RootPanel`
- [GameWorld.cs](https://github.com/webcrawls/sandtype/blob/219be9936f2cb2be97e6c6b5085a5c74fbab8f2e/code/UI/Game/GameWorld.cs) and [GameView.razor](https://github.com/webcrawls/sandtype/blob/219be9936f2cb2be97e6c6b5085a5c74fbab8f2e/code/UI/Game/GameView.razor) - rendering lovely Terry `SceneModel`s
- [BossPanelBase.cs](https://github.com/webcrawls/sandtype/blob/219be9936f2cb2be97e6c6b5085a5c74fbab8f2e/code/UI/Game/BossPanelBase.cs) - a bigger Terry, made transparent and thrown on the top layer via SCSS rules

### Additional context

- `Windows 10 21H2 19044.3208`
- Steam ID: `76561198092348104`

I wanted to make a reproduction repo, but I've used up all my mental dexterity for tonight. I'll take a go tomorrow if no progress gets made :)

**Comment by webcrawls** [comment]
Made no changes, but it seems to be working now? Closing, will reopen if it come back :D

**Comment by webcrawls** [comment]
Recountered this issue again - exact same error logs, with the exact same solution of re-opening the editor, or opening a different game and then returning to the offending project.

Seems that #3675 is another instance of this as well, so I think this is something that needs to be looked into. Let me know if I can provide any more information.

**Comment by handsomematt** [comment]
Should be fixed now

**Comment by webcrawls** [comment]
Haven't ran into anything, so will close this o>
