### ISSUE TITLE
Cannot change sequence time on animated entities

### ISSUE THREAD

**Issue by krotter0** [sboxgame/issues#3671]
### Describe the bug

Changing either CurrentSequence.Time or CurrentSequence.TimeNormalized on animated entities does not change the animation's current time properly - it seems that the time only changes for a frame/tick, then snaps back to the previous time. It doesn't matter if the entity is client only, neither does the value of AnimateOnServer.

### To Reproduce

- [Download the repro code](https://github.com/sboxgame/issues/files/12105660/SequenceTest.zip)
- Run `test_sequence_clientspawn` and/or `test_sequence_serverspawn` in console
- Run `test_sequence_client` and/or `test_sequence_server` in console
- Animation time does not change

### Expected behavior

Animation's current time should change.

**Comment by DoctorGurke** [comment]
I can't check the code on mobile, are you trying to use this on a regular animgraph animated entity? Animgraph and sequences are mutually exclusive when driven through code, besides direct playback

**Comment by krotter0** [comment]
No, UseAnimGraph is set to false in the code, and I've also had issues with models that didn't have an animgraph.
