### ISSUE TITLE
Mouse.Delta does not scale with system mouse sensitivity

### ISSUE THREAD

**Issue by youarereadingthis** [sboxgame/issues#3672]
### Describe the bug

`Mouse.Delta` does not scale with system mouse sensitivity.

### To Reproduce

Have something, like a constrained crosshair, move using `Mouse.Delta`.

### Expected behavior

`Mouse.Delta` should be scaled to the system cursor sensitivity, for consistency.

### Additional context

This is a problem for my 2D shooter since we have no way of grabbing mouse delta that's consistent with the system cursor, for 1:1 aiming. Decided to use `Input.MouseDelta` for now but neither is that 1:1 with the system cursor.

**Comment by garrynewman** [comment]
Mouse.Delta should be the amount of pixels moved in that frame. In what way isn't it 1:1?

**Comment by garrynewman** [comment]
This is by design, it's the number of pixels, it doesn't obey sensitivity
