### ISSUE TITLE
game won't start

### ISSUE THREAD

**Issue by therealdum** [sboxgame/issues#3676]
### Describe the bug

whenever I press play on s&box it says playing then crashes and I don't know what to do because I've done everything like verifying the files, uninstall/reinstall. 

### To Reproduce

1. go onto steam 
2. go to s&box
3. click play
4. and that's when the bug happens

### Expected behavior

the game should start and I should be able to play it.

### Media/Files

![image](https://github.com/sboxgame/issues/assets/140112304/b005f1d0-4893-40ad-9eb5-72099e3875bf)

### Additional context

I'm running on windows 10

**Comment by handsomematt** [comment]
Can you look for the error in event viewer:
Event Viewer (Local) > Windows Logs > Application 

And can you tell us more about your system; CPU, RAM, GPU.

And finally can you share your steam id
