### ISSUE TITLE
Add a "bullet response" parameter to surface definitions

### ISSUE THREAD

**Issue by Igrium** [sboxgame/issues#3678]
### For?

Other

### What can't you do?

In Source 1 (and other branches of Source 2), its possible to declare whether bullets and other traces can pass through materials (grates etc). It would be nice to have something like that in S&Box. 

Although it would be up to individual games to implement this, there should be a standard way to "declare" a surface definition as bullet penetrable so that you can be more confident that Asset Party assets will work properly.

### How would you like it to work?

There could be a checkbox in the surface property editor that marks something as a "grate" which code can check for. 

Alternatively, it might be better to support arbitrary tags in surface properties and standardize "grate" as a tag.

### What have you tried?

Manually implementing a system to ignore certain materials in traces. This is really janky, and it means I have to declare all my assets in code.

### Additional context

*Edit:* it might do to have a similar parameter for "ground friction" on pawns like HL2 had.

**Comment by garrynewman** [comment]
Maybe tags in the surface properties would be more useful? So you can add a tag "penetrate" for what you want, but could be infinitely extendable for other uses?

**Comment by DevulTj** [comment]
I added a tag container to surfaces, let me know if you have any issues with this.

Surface.HasTag, HasAnyTag, HasAllTags - add tags in the resource.

**Comment by Igrium** [comment]
Noice
