### ISSUE TITLE
Whitelisted way to access System.Threading.Thread.ManagedThreadId

### ISSUE THREAD

**Issue by peter-r-g** [sboxgame/issues#3679]
### What it is?

The assembly to access said item (`System.Threading.Thread`) is currently not whitelisted so I'm guessing what the entries would be:

`System.Threading.Thread/System.Threading.Thread.get_CurrentThread()`
`System.Threading.Thread/System.Threading.Thread.get_ManagedThreadId()`

### Why do you need to use this?

I am working on a performance tracing library that can record from any thread or task. This becomes a problem when I cannot differentiate what thread it is coming from. Right now my bandaid fix is to just mark the main thread (which is found from [ThreadSafe.IsMainThread](https://asset.party/api/Sandbox.ThreadSafe.IsMainThread)) as thread one and anything outside of it as thread two. This does not blow up my library but it becomes pretty confusing to see graphs of different threads merging into each other.

With the `System.Threading.Thread` assembly not being whitelisted I think just implementing the property in S&box itself fits better. There is already the [ThreadSafe](https://asset.party/api/Sandbox.ThreadSafe) class which it would fit in.

**Comment by garrynewman** [comment]
Added `Added ThreadSafe.CurrentThreadId`
