### ISSUE TITLE
game freezes on Sending Client Info

### ISSUE THREAD

**Issue by Cureisu** [sboxgame/issues#3680]
### Describe the bug

I've attempted joining a server of TTT and Jenga and while ill load in, my screen stays permanently stuck on the "sending client info" and doesn't ever load in. Cant click on cancel to back out of it either.

### To Reproduce

1. pick any game
2. try to join a server
3. permanently stuck on "sending client info"

### Expected behavior

I load into the game

### Additional context

running windows 11, using NVIDIA GeForce RTX 3060 Ti & AMD Ryzen 9 3900x 12-Core Processor, 64 GB ram

**Comment by handsomematt** [comment]
Should be fixed now
