### ISSUE TITLE
.sbproj stopped opening projects

### ISSUE THREAD

**Issue by Weldify** [sboxgame/issues#3687]
### Describe the bug

Opening the editor via `.sbproj` no longer opens the project

### To Reproduce

1. Open a `.sbproj` file
2. The editor will launch, but the project will not

### Expected behavior

Should launch the editor and open the project properly.

### Media/Files

![image](https://github.com/sboxgame/issues/assets/66477673/5b25c1a4-4001-4cf8-bdd2-c93df4dbeb49)

**Comment by handsomematt** [comment]
I think I'd already fixed this and can't really see why this would happen still. But if it does can you post your Log.txt and config/addons.json file?

**Comment by Weldify** [comment]
Works now, thank you Matt
