### ISSUE TITLE
Launch multiple projects

### ISSUE THREAD

**Issue by youarereadingthis** [sboxgame/issues#3690]
### For?

S&Box

### What can't you do?

Launch more than one project at a time.

### How would you like it to work?

Imagine that instead of only being able to click on one project to launch it, you may click on tickboxes next to the projects you want to work with and then press "Launch".

If you select multiple projects then you are booted into the main menu, not a single project's menu.

### What have you tried?

There are no options like I'm asking for yet.

### Additional context

Limiting the number of projects you are launching is a great feature. Limiting it to just one is not IMO and does not enable multitasking and/or fixing those bugs across your projects that pop up due to sbox updates.

**Comment by DoctorGurke** [comment]
The whole point of the launcher is to lock you into one game project at a time. You can still pile as many content projects on top of this as you want

**Comment by DevulTj** [comment]
this is intended

**Comment by DoctorGurke** [comment]
You can switch projects super fast though? Top left File let's you get back to the launcher instantly
