### ISSUE TITLE
Receive git updates for Projects clones from asset.party

### ISSUE THREAD

**Issue by CarsonKompon** [sboxgame/issues#3692]
### For?

S&Box

### What can't you do?

If you clone a game project from asset.party via the following button:
![image](https://github.com/sboxgame/issues/assets/5159369/c432cdb4-b3dc-4b07-baca-4a3826efdad3)

Then you will not receive any further updates that are made to the repo unless using an external piece of software.

### How would you like it to work?

It would be nice if there was a proper UI that notified you when there's new changes to pull and other necessary git interactions.

### What have you tried?

Manually pulling changes through Github Desktop. But working on a project without checking external programs first could lead you to miss updates or cause merge conflicts once you do realize.

**Comment by handsomematt** [comment]
> (or even the .git folder which allows you to do it yourself via Github Desktop or VSCode)

It uses git clone, there will always be a .git folder there.

**Comment by CarsonKompon** [comment]
> It uses git clone, there will always be a .git folder there.

Oh this is my mistake. In my tests I was looking in the wrong folder because the Single Project update had reset my S&box Projects folder directory. The newly downloaded folders definitely have the `.git` folder. Correcting the original post 👍

**Comment by handsomematt** [comment]
I don't think we should be writing Git integration into the editor, no reason an editor addon couldn't do it though.
