### ISSUE TITLE
S&box can't invoke CPU

### ISSUE THREAD

**Issue by Thricons** [sboxgame/issues#3703]
### Describe the bug

I am using latest s&box in steam. When I was playing sandbox mode's FlatGrass Map, the CPU's 
occupancy is pretty low, and I get low fps. But the GPU's occupancy is pretty high. 

### To Reproduce

I don't know. I am using Windows11 Pro 22H2 and Lenovo Xiaoxin 2019 Ryzen Version(?) I am using R5 3500U with Vega 8 Graphics.

### Expected behavior

CPU should be have more occupancy and get higher FPS

### Media/Files

![QQ图片20230723112828](https://github.com/sboxgame/issues/assets/109009233/5f49e2d4-0e37-4a53-935b-075e83095926)
![QQ截图20230723113253](https://github.com/sboxgame/issues/assets/109009233/94a3f2f6-abb2-4d85-b7df-f8b1263e36fb)

**Comment by Thricons** [comment]
sorry about bad English, I am tring my best to describes my problem ;w;

**Comment by robotboy655** [comment]
Programs use as much CPU as they need. Your low FPS is due to other factors, such as your weak integrated GPU, low amount of free RAM/VRAM.
