### ISSUE TITLE
`Prediction.FirstTime` should be `Prediction.IsReconciling`

### ISSUE THREAD

**Issue by Weldify** [sboxgame/issues#3712]
### What it is?

`Prediction.FirstTime` essentially tells you when you're not reconciling. The current naming is VERY confusing, took me a long time to understand what it actually was.

### What should it be?

`Prediction.FirstTime` should become `Prediction.IsReconciling`. It makes more sense because that's exactly what what it represents.

```cs
/// <summary>
/// Returns true if we are currently recalculating mispredicted ticks.
/// Use this to exclude effects such as sounds and particles so they don't get spammed.
/// </summary>
public bool IsReconciling { get; }
```

**Comment by garrynewman** [comment]
It's more accurate - but I don't think it's as easy to understand

**Comment by robotboy655** [comment]
Especially for people for whom English is not the first language. Reconciling is a pretty rarely used word, especially in contact of programming.

The property has documentation summary either way, so I don't see how it's hard to understand what it does.

**Comment by trende2001** [comment]
English in programming should be as plain as possible, I don't agree with this change
