### ISSUE TITLE
Panel.Blur should be Panel.Unfocus or something similiar

### ISSUE THREAD

**Issue by Gmod4phun** [sboxgame/issues#3718]
### What it is?

After reading a similiar issue related to naming of methods, one thing comes to mind regarding panels.

In the past, I had an issue of not finding a way to lose focus on a panel, by looking for a LoseFocus or Unfocus method, since the method to focus on the panel is called `Focus`. After a fellow community member helped me, it turns out the method to stop focusing on a panel is called `Blur`.

I am not a native english speaker, but I understand english pretty much perfectly and use it every day, however it would never occur to me to look for a `Blur` method. If this is not a problem and its a common term regarding UI elements in other game engines/web dev, then just ignore the issue, but I think the current naming is confusing.

### What should it be?

I think it should be either called `Unfocus` or `LoseFocus`, or something having to do with the word focus, since I would expect that `Blur` would have something to do with applying a blur effect to the panel. `OnBlur` would also have to be renamed.

**Comment by garrynewman** [comment]
The UI system tries to follow similar naming schemes to the web, and on the web it's called blur. I agree it isn't ideal but it's the symmetry we want.

**Comment by Gmod4phun** [comment]
Understandable. I wonder who in their right mind came up with the name in the first place,
