### ISSUE TITLE
Model and Material Inspectors should have useful information in them.

### ISSUE THREAD

**Issue by NotGaylien** [sboxgame/issues#3721]
### For?

S&Box

### What can't you do?

If i download a model or material from asset party.
there is no way of easily getting all the useful information from them.

![image](https://github.com/sboxgame/issues/assets/82092361/87b7b234-fef8-46f4-8d64-0ac6be078ac3)

Does this model have material groups?
Does this model have body groups?
Does this model have Attachment points?
Does this model have animations?
Does this model have an Animgraph?
If it has an animgraph what Parameters do we have to access it?
Do the materials on this model have a Dynamic expressions that allow us to access them via code?
Do the materials on this model have Attributes we can use to replace them?

### How would you like it to work?

There should be something that detects all these useful things we would want to know.
For example
a much better version of this.
![image](https://github.com/sboxgame/issues/assets/82092361/00c1460a-5090-4072-a2cc-bef0dcbfb405)

having it all in that window would be a life saver, and can help you avoid uploading with a bunch of test stuff, or missing stuff, being able to quickly look and see all your stuff is there.

Also to mention, the model on asset party should have a new 3rd tab too imo
view, versions, **details**

The details tab should have all this information within it 
for the nerds who need a specific model, for example
a specific light model with on and off material groups, bodygroups to enable and disabled the lightbulb and an attachment point for the light. in a specific case.

### What have you tried?

Currently we can download models, view them in modeldoc which can give us 95% of stuff in this list,
but we dont have access to all that stuff, especially stuff within animgraph and materials.

**Comment by aylaylay** [comment]
Agree, there's a fair amount of info we could show here.

**Comment by robotboy655** [comment]
Related issue: https://github.com/sboxgame/issues/issues/2049

**Comment by aylaylay** [comment]
https://github.com/sboxgame/issues/assets/1667289/6b678883-5847-435b-8f41-d2f200888137

**Comment by NotGaylien** [comment]
Thats bloody wonderful.

The params are a massive help especially.
thinking about it all more, i reckon most information could be put on asset party, stats for nerds sort of deal.
the only other things i think would be lovely would be bodygroups, material group and maybe a way to view any potential attachment points (their positions on the model). as i reckon they would be a big use for alot of games.
but we can get them in modeldoc anyway so no big worry regarding them.

but its really lovely, thanks layla. <3

**Comment by DoctorGurke** [comment]
God I would love a quick preview of attachment transforms + names

**Comment by aylaylay** [comment]
Out of curiosity, why would you need the transforms? Surely you'd just want the names to copy paste?

**Comment by aylaylay** [comment]
https://github.com/sboxgame/issues/assets/1667289/08358359-3ab0-431b-b73c-daee6f3081aa

**Comment by DoctorGurke** [comment]
> Out of curiosity, why would you need the transforms? Surely you'd just want the names to copy paste?

I meant it like a quick preview of the transform on the model when it's selected to get a rough feel of where the attachment is. Maybe it's fine to just open it in model doc tho idk
