### ISSUE TITLE
Hammer editor -ent_door Crashes

### ISSUE THREAD

**Issue by InsaneSaintGamer** [sboxgame/issues#3724]
### Describe the bug

I have tried making a door made up of different meshes that are tinted differently. I have made one of the meshes into an ent_door and parented the other meshes(which are func_detail) to the door, I tried making all the meshes into separate ent_doors and parented them, I also tried "other doors to open" and all of these resulted in the editor crashing when loading into the map after a successful compile.

Parenting prop_animated to the door doesn't crash upon loading.

This is the last error I keep getting in the logs (doors is the map name):
engine/ResourceSystem	Error loading resource file "maps/doors/world_visibility.vvis_c" (Error: ERROR_FILEOPEN: File not found)

### To Reproduce

Make a cube, make it an ent_door, make another cube, make it a door as well, and try to make them both open together.

Probably going to get a better explanation from above, sorry.

### Expected behavior

It's understandable if parenting two doors crashes but using "other doors to open" shouldn't be ¯\_(ツ)_/¯

**Comment by robotboy655** [comment]
The crash can be look into, but your ent_door can easily consist of multiple meshes - simply select multiple meshes and tie them to the door entity (or any other entity). You can even add meshes to existing entities via the exact same process, but also selecting the entity to add to. You should be able to find the "Tie mesh to entity" option in the F1 menu.

**Comment by InsaneSaintGamer** [comment]
I know I can make them all under the same ent_door, however, I want the different meshes tinted differently and when you make the different meshes under the same ent_door then all the meshes use the tint color under ent_door.

**Comment by InsaneSaintGamer** [comment]
I know that you can tie all the meshes together under ent_door, however, I have different meshes tinted differently and when you tie the different meshes under a single ent_door then all of them use the tint color under ent_door and no longer use their own mesh tint color.
