### ISSUE TITLE
[Shader Graph] Add World Mapping to Shader Graph Shaders

### ISSUE THREAD

**Issue by Jammie3d** [sboxgame/issues#3732]
### For?

S&Box, Material Editor

### What can't you do?

I'd like to be able to set the world mapping width and height in a shader that has been created in the shader graph, like you can with traditional shaders.

### How would you like it to work?

Same as with most shaders like `complex`, a Set World Mapping section in the Attributes tab.
![image](https://github.com/sboxgame/issues/assets/60801006/893ef151-a2ca-46ea-83bf-8718089bc708)

Ideally this could be added by default to shader graph shaders, but having it as a node or option in the shader properties would also be fine.

### What have you tried?

Manually scale materials in Hammer instead.

**Comment by ShmishDD** [comment]
I'm confused, if I go to any of my material that use any of my shaders made in shader graph, I have this section and can set values here. Do they just not apply to the material/shader at all?

**Comment by Jammie3d** [comment]
Oh you're right, it's there now after a shader recompile.
I was using a shader I made a while ago, didn't realise it was already added, thanks for having a look!
