### ISSUE TITLE
.sbproj opens cloud version of project

### ISSUE THREAD

**Issue by Weldify** [sboxgame/issues#3737]
### Describe the bug

Opening your project through .sbproj will load the cloud version of your project. Changes to assets and code are not visible and hotloading doesn't work.

### To Reproduce

1. Open S&box, if you have a project open, do `File -> Close Game Project`
2. Reopen S&box, at the welcome screen open S&box with `Content mode`
3. Close S&box
4. Open a .sbproj file

### Expected behavior

Should load the local version

### Media/Files

[Log.log](https://github.com/sboxgame/issues/files/12188376/Log.log)

**Comment by handsomematt** [comment]
Thank you for the thorough reproduction steps, should be solved now
