### ISSUE TITLE
have hammer open active game instead of sandbox

### ISSUE THREAD

**Issue by TheBoxTrot** [sboxgame/issues#3739]
### For?

Hammer

### What can't you do?

When you compile a map with hammer and it loads in game if you haven't started a game yet it opens the map in sandbox

### How would you like it to work?

since we now have a single game projects it safe to assume what gamemode we want to open the map in so it should launch the game we are working on not sandbox

### What have you tried?

nothin

**Comment by robotboy655** [comment]
Duplicate of internal issue https://github.com/Facepunch/sbox/issues/1174

**Comment by DevulTj** [comment]
This should be the case now
