### ISSUE TITLE
This game needs at least DirectX 11 (launch game)

### ISSUE THREAD

**Issue by Rymeeen** [sboxgame/issues#3744]
### Describe the bug

Hello! I decided to install s&box on my old laptop, but it won't start. I changed DirectX to 11, I launch it, the logo appears and after a couple of seconds it crashes.
Error:
CRenderDeviceMgrDx11::CreateDevice():
This game needs at least DirectX 11 capable hardware, you really should consider upgrading your computer.

The laptop is certainly weak, but are there any options for launching this game?

### To Reproduce

1. Click on the program shortcut; 2. An error appears

### Expected behavior

Launch game

### Media/Files

![IMG_2159](https://github.com/sboxgame/issues/assets/140849511/94a28f51-1365-4d45-83fd-3d1ae2863a93)
![IMG_2160](https://github.com/sboxgame/issues/assets/140849511/04b865cd-b0d1-4227-99d7-e60f2568fabb)

### Additional context

I am working on wimdows 10 home, Asus M50Vn laptop, Nvidia Geforce 9650m GT 1gb

**Comment by DrewBritt** [comment]
No, if your machine isn't capable of DX11 it definitely won't be capable of Vulkan. Your graphics card is nearly 15 years old and has 1GB of VRAM, I think it's time to put it to rest...

**Comment by Rymeeen** [comment]
This is really very sad, apparently you will only have to play garrys mod
