### ISSUE TITLE
Input System not working

### ISSUE THREAD

**Issue by GhostgsYT** [sboxgame/issues#3746]
### Describe the bug

the bug wouldn't let me look around in game even when i move my mouse also i can't launch the editor or the vr version , please any help for this issue 

### To Reproduce

it bugged for every game i play on every single one

### Expected behavior

it like makes me not able to do anything with the engine and it's so bad that i been hyped for years and in the end i can't even play the game or make my own game

### Media/Files

sadly i don't have any clips

### Additional context

i'm running it on Windows 10 , and i have a good pc that can run it

**Comment by DevulTj** [comment]
Please find a way to record a clip for this. I have no idea what this issue means.
