### ISSUE TITLE
Infinite Jumps

### ISSUE THREAD

**Issue by ekaliclua** [sboxgame/issues#3756]
### Describe the bug

When we jump we can rejump after the animation of the jumping.

### To Reproduce

Go in sandbox
Jump and spam jump

### Expected behavior

Just jump and wait to touch the floor to rejump.

### Media/Files

https://streamable.com/wwqqht

**Comment by Gmod4phun** [comment]
You are enabling noclip by doubletapping spacebar and just flying upward
