### ISSUE TITLE
`ITagSet` Should Implement `ISet<string>`

### ISSUE THREAD

**Issue by LeQuackers** [sboxgame/issues#3759]
### What it is?

Tags and `ITagSet` behave like an `ISet<string>`, but don't use the `ISet<string>` interface.

### What should it be?

`ITagSet` should implement the `ISet<string>` interface. Honestly `ITagSet` could just be replaced entirely by the `ISet<string>` interface, but that'd probably break a lot of stuff.

**Comment by DevulTj** [comment]
Not sure if I agree, ISet<string> implements a bunch of fluff that we don't need

**Comment by LeQuackers** [comment]
Maybe just `IReadOnlySet<T>` then?

**Comment by DevulTj** [comment]
To me, IReadOnlySet<T> still has loads of random unrelated methods, I'm gonna say no for now

**Comment by LeQuackers** [comment]
> To me, IReadOnlySet still has loads of random unrelated methods, I'm gonna say no for now

Can we at least get `IEnumerable<string>` on it? [`ITagSet.TryGetAll`](https://asset.party/api/Sandbox.ITagSet.TryGetAll()) is clunky and it doesn't fit the normal "Try" pattern because it doesn't return a `bool` our have an out parameter; it'd be way more concise just to pass the `ITagSet` instead of calling an extra method everywhere. On top of that, it would allow `ITagSet` to use `IEnumerable<string>` extension methods.

**Comment by Weldify** [comment]
`IEnumerable<string>` would be very nice

**Comment by LeQuackers** [comment]
> `IEnumerable<string>` would be very nice

Moved to a new issue: #4037
