### ISSUE TITLE
Weightlists do not expand correctly to show names, causing some to be cut out

### ISSUE THREAD

**Issue by Grodbert** [sboxgame/issues#3761]
### Describe the bug

When you have many bones in a hierarchy, each child is shown slightly offset, to indicate it's a bone's child, and if this process is repeated enough time, the text will be cut off.

It would not be a problem if expanding the window to either side would reveal the cut text, but instead, it just makes the sliders longer.

In some cases, some bones are left with no name and no way to see it.

### To Reproduce

1. Go to terry
2. select a weightlist
3. see that some bone names are cut off
4. try to expand the window and fail

### Expected behavior

the cut off text should reveal itself instead of just making the sliders longer.

### Media/Files

https://github.com/sboxgame/issues/assets/86626409/412a4014-16b5-4353-918b-d01c7fac4bfa

**Comment by Grodbert** [comment]
Seems like you can expand the names:
https://i.gyazo.com/a9b426af48b6aee26b15816b76560394.mp4
As shown here by Kaesar,
However, this is highly unintuitive! I still think it should expand the names by default, as that's the most intuitive outcome.

**Comment by aylaylay** [comment]
Unfortunately this is just how that Qt widget works. I'm sure there's probably a way to hack it but that's why you can resize the column.
