### ISSUE TITLE
S&box stuck in stopping state in the Steam library after closing. Must restart steam to relaunch the game.

### ISSUE THREAD

**Issue by LiminalCrab** [sboxgame/issues#3768]
### Describe the bug

This has been happening since we changed over to the new Single Game Projects system. Every single time I close S&box, without fail it's stuck in a 'stopping' state on Steam. I have no instance of VS Code running, there is no additional Sbox-dev processes running on my machine after closing it. I originally ignored the issue while working on maps because I very rarely left the editor.

I've tried to reinstall the game completely which didn't work. The only solution I have is to kill the Steam process entirely. (Killing the sbox-dev process does nothing, it's still gets stuck).

This is hindering me at this point, because I frequently have to relaunch the game during development.

https://github.com/sboxgame/issues/assets/78995156/804e0736-14e2-4bf2-b7fb-fcca6fe62d33

### To Reproduce

It's hard to say if others are really having an issue with this.

1. Launch Sbox.
2. Close Sbox.
3. Check library to see if the game has exited.

### Expected behavior

Sbox should be in a stopped state on Steam and launch-able again.

**Comment by TheBoxTrot** [comment]
Do you still have your ide opened? Cause that's a known issue and probably won't be fixed

**Comment by LiminalCrab** [comment]
No I don't

**Comment by TheBoxTrot** [comment]
what IDE do you use?

**Comment by LiminalCrab** [comment]
It's not my IDE, none of these things are running on my system. I made sure of out, over a month ago during our last conversation about it.

**Comment by LiminalCrab** [comment]
I had to reinstall Steam.

For some reason, GameOverlayUI.exe & GameOverlayRenderer64 had various instances of Git using them. Once I ended the git processes targeting GameOverlayUI &  GameOverlayRenderer64 S&box showed up as closed. I reinstalled Steam anyway.

**Comment by LiminalCrab** [comment]
> The asset party clone function uses git, that could be related if you've been doing that?

Nah I haven't used any git related features from Asset Party. I think I've figured it out

https://github.com/sboxgame/issues/assets/78995156/eef0a727-d309-493e-9f94-e09e08896964

@TheBoxTrot was right, VS Code is actually the cause of the game not closing in Steam. What seems to be happening with it is, the VS Code's version control stays attached to the C:\Program Files (x86)\Steam\GameOverlayRenderer64.dll, you can close VS Code, you can ensure it's not running on your system at all, but those git processes stay alive and attached to your editor until they're killed. S&box can remain in a "stopping" state in Steam until this happens.

I'm not sure this is an issue that Facepunch will be able to fix but I'll leave it open for their verdict on the problem

**Comment by LiminalCrab** [comment]
xaizone — Today at 11:53 PM
what happens if you disable the steam overlay?

Aleph — Today at 11:54 PM
Let's find out

@xaizone
what happens if you disable the steam overlay?

Aleph — Today at 11:57 PM
ATM it doesn't matter, I have the Overlay disabled for S&box and git is still attaching itself to GameOverlayRenderer64.dll

xaizone — Today at 11:57 PM
weird

Aleph — Today at 11:57 PM
When I get off work today I'll run some captures in process explorer and see whats going on
[11:57 PM]
I deleted all of the data for the overlay as well

xaizone — Today at 11:57 PM
tbh the new steam ui is really buggy

Message #💻general-dev

**Comment by xaizone** [comment]
Have you tried disabling VSCode's Git integration? This seems more of a VSCode issue to me - not exiting itself in a proper manner.

**Comment by LiminalCrab** [comment]
> manner

Also definitely a possibility considering I never use it. Will give that a shot too.

**Comment by garrynewman** [comment]
Steam is viral. If you launch a game, which launches another exe (say notepad).. then when you close the game it'll still think that it's running until notepad is closed too.

**Comment by LiminalCrab** [comment]
Yeah, I suppose we should document this as a known issue, and a workaround is disabling VS code's version control and just using the Github desktop / third party apps.

**Comment by glimpsebeyond** [comment]
I was able to make S&box successfully close on steam by killing some Git For Windows processes.
