### ISSUE TITLE
ModelDoc: Slider for MinMaxAttribute

### ISSUE THREAD

**Issue by krotter0** [sboxgame/issues#3770]
### For?

Other

### What can't you do?

ModelDoc currently doesn't show a slider for properties marked with MinMaxAttribute, which makes editing certain kinds of values somewhat painful.

### How would you like it to work?

Show a slider for properties marked with MinMax.

### What have you tried?

Adding a MinMax attribute to a property.

### Additional context

I'm guessing the min, max attributes are just being ignored when the fgd is generated, since this is already a thing in Alyx:
`	finger_thumb(float)		[ min="0", max="1" ] : "Param: finger_thumb"		: "0"`

![img](https://github.com/sboxgame/issues/assets/65136069/a37bab87-6440-4fc5-9678-337558ebc842)

And this is how it looks right now in sbox:
```cs
[JsonPropertyName( "finger_thumb" ), MinMax( 0, 1 )]
public float ThumbCurl { get; set; } = 0f;
```
![img](https://github.com/sboxgame/issues/assets/65136069/68e10741-f828-4182-96b4-02f9a939710a)

**Comment by aylaylay** [comment]
Added this but haven't tested it, let me know if it works please

**Comment by krotter0** [comment]
It's working great, thanks.
