### ISSUE TITLE
A func_voxelsurface has to be broken entirely before you can walk through it

### ISSUE THREAD

**Issue by sugmagaming** [sboxgame/issues#3771]
### For?

Hammer

### What can't you do?

When you make a func_voxelsurface you can't for example break a hole in the wall and go through it. The entire block has to be destroyed before you can.
![Screenshot 2023-08-01 230212](https://github.com/sboxgame/issues/assets/15720147/1b86e2d4-d2ca-4104-98f9-6bf9202b8087)

### How would you like it to work?

Have the physics mesh adjust as the pieces get shot.

### What have you tried?

Everything.

**Comment by aylaylay** [comment]
Should be fixed now
