### ISSUE TITLE
Unable to login to steam on assetparty, its logging me out. 

### ISSUE THREAD

**Issue by Shroomys** [sboxgame/issues#3772]
### Describe the bug

Asset.party website logs me out as soon as i login using steam. 

### To Reproduce

1. Went to asset.party 
2. Logged in using steam 
3. Signs in for 1-2 sec before logging you out. 

### Expected behavior

It should let you login. 

### Media/Files

![asset party login error ](https://github.com/sboxgame/issues/assets/141203159/8c6f90c1-affb-4133-80db-f8c6ef80d88e)

### Additional context

I've tried Google chrome and microsoft edge broswers.

**Comment by PeteBroccoli** [comment]
This often happens when the user is on a VPN, which I assume you are.

**Comment by Shroomys** [comment]
No I'm not on a vpn.

**Comment by BillCosbysOvaries** [comment]
I have also had this problem a couple times despite my VPN being turned off. I restarted my browser and reopened asset party, it worked fine after that.

**Comment by Shroomys** [comment]
I'll have to try restarting my computer, I've already tried resetting my browsers.

**Comment by Shroomys** [comment]
It still doesn't work I give up :(

**Comment by garrynewman** [comment]
How dynamic is your IP?

**Comment by Shroomys** [comment]
My DHCP is enabled if that's what you mean?

**Comment by Shroomys** [comment]
I figured it out, it was the cookies...
