### ISSUE TITLE
`AE_CL_PLAYSOUND` broken => no weapon animation sounds

### ISSUE THREAD

**Issue by timmybo5** [sboxgame/issues#3775]
### Describe the bug

Model `AE_CL_PLAYSOUND` events stopped working which means all gamemodes with weapons have missing weapon sounds (beside shooting), you can hear the sounds being played in ModelDoc when previewing the animation there.

![image](https://github.com/sboxgame/issues/assets/4988198/ab1597ae-1547-46f3-9647-5ea36b4f0dd8)

### To Reproduce

1. Create a new model in ModelDoc
2. Add an animation to the model with a new AE_CL_PLAYSOUND sound event
3. Sound event plays in ModelDoc but not in-game

**Comment by KingOfTheFBI** [comment]
Can confirm broke all sounds in Trouble in Terrorist Town too

**Comment by handsomematt** [comment]
Only on clientside models? @kurozael recent change with authorative maybe

**Comment by kurozael** [comment]
I can investigate it :)

**Comment by kurozael** [comment]
@timmybo5 this should be resolved in the next Steam build. Let me know if you have any more problems 👍

**Comment by timmybo5** [comment]
Works! Thank you for fixing it so fast <3
