### ISSUE TITLE
Joining the same project in the same house

### ISSUE THREAD

**Issue by NubNub11** [sboxgame/issues#3776]
### Describe the bug

Me and my brother attempted to join the same game and i figured we couldnt because we are in the same IP after that i attempted to join with a vpn and it worked for some time but crashed after that

### To Reproduce

![Screenshot 2023-08-03 012345](https://github.com/sboxgame/issues/assets/141282050/02b7dcc4-39fa-4827-92f5-3716915ca130)
it is stuck on connecting if one of us is connected to the server

### Expected behavior

we should be able to join from the same house

### Media/Files

![Screenshot 2023-08-03 012345](https://github.com/sboxgame/issues/assets/141282050/48f32cb6-a79b-4913-b749-6c09277e42a4)

### Additional context

I'm running windows 10

**Comment by handsomematt** [comment]
Not an issue tracker for non-engine issues.
