### ISSUE TITLE
Boundary Box of Rust Prop Too Big

### ISSUE THREAD

**Issue by InsaneSaintGamer** [sboxgame/issues#3779]
### Describe the bug

The boundary box for concrete_debris_c is like 3 times larger than the prop.

### To Reproduce

Just spawn the prop, models/rust_props/concrete_debris/concrete_debris_c.vmdl and you can see it.

### Expected behavior

Should fit the right amount of space.

### Media/Files

![Screenshot (729)](https://github.com/sboxgame/issues/assets/138017592/0b827a3b-f65d-4ecf-929a-516fe2018c92)

**Comment by bakscratch** [comment]
Should be fixed now, thanks
