### ISSUE TITLE
viewmodel doesn't work in animgraph

### ISSUE THREAD

**Issue by pesogamer** [sboxgame/issues#3780]
### Describe the bug

the bug is when i put my viewmodel into animgraph it shows this and i tryed downloading an animation from the internet and putting it into the model but it didn't work etheir

### To Reproduce

1.create a model in modeldoc
2.doesn't need to have an materiel but mine did have one
3.go to animgraph and add the model

### Expected behavior

the intended behavior is my viewmodel working

### Media/Files

![error](https://github.com/sboxgame/issues/assets/68095594/615b42a3-cdea-46dc-93cf-e1347f9efbe1)

**Comment by aylaylay** [comment]
Your model has no animations and either doesn't exist or isn't compiled properly. I've tested loading models in animgraph and everything is working as expected.

**Comment by pesogamer** [comment]
yeah it doesn't have models i cancled the project
