### ISSUE TITLE
Attempting to set the scale of a clientside spawned entity complains about No Authority

### ISSUE THREAD

**Issue by Zach-Calhoun** [sboxgame/issues#3784]
### Describe the bug

When an entity is spawned clientside, for example in the FrameSimulate() function, attempting to set the scale via the Entity's Scale property will display an error message about No Authority, stating that the server entity needs to be predictable. Unless i'm misunderstanding something about how spawning entities works, and somehow the entity is also spawned on the server?

![image](https://github.com/sboxgame/issues/assets/18699961/cd46e3ad-7a5d-4178-a9ce-cea121998251)

![image](https://github.com/sboxgame/issues/assets/18699961/c2512b4c-7a1e-47f6-9d23-f0d9a81cedc7)

The commented out line causes the error, while setting the Transform directly works without issue.
The code is executed in the FrameSimulate function of a Pawn, which is described as being clientside only.

### To Reproduce

Spawn an entity clientside, in my case, in the FrameSimulate() function.

Attempt to change the entity's scale using the Scale property

### Expected behavior

There shouldn't be anny issues in changing the scale of an entity that exists only on the clientside.

**Comment by aylaylay** [comment]
Make sure you actually are creating it on the client. I tried creating an entity in frame simulate and set the scale and it works fine. Setting transform will also set scale in the same way so there's no reason that would work while setting scale directly doesn't.

**Comment by Zach-Calhoun** [comment]
@aylaylay thanks for the reply.

As I was listing out the code to post as a reply, i Just noticed that I was setting the Scale on the hovered variable instead of hoverModel, which hovered is indeed a server side entity, my bad. Sorry, it's very late here so I got a bit confused.

Closing Issue.
