### ISSUE TITLE
Fuel barrel missing model

### ISSUE THREAD

**Issue by alobxplayer** [sboxgame/issues#3785]
### Describe the bug

This is probably isnt an bug but there are missing fuel barrel model in game.

### To Reproduce

Spawn fuel barrel model in any gamemode

### Expected behavior

Expected normal fuel barrel model

### Media/Files

![image](https://github.com/sboxgame/issues/assets/139641395/42b3ad84-04fb-48ce-9d33-a35d471e7305)
![image](https://github.com/sboxgame/issues/assets/139641395/b08f9a1a-5762-4266-ab0a-302b040158b7)

**Comment by MoskalykA** [comment]
Hi, this is a problem with the Sandbox game mode and not the game, the [model ](https://asset.party/rust/fuel_barrel) does exist

**Comment by bakscratch** [comment]
Use the asset party one, i've removed the png thumbnail so it should be gone
