### ISSUE TITLE
Water visual bug #1

### ISSUE THREAD

**Issue by alobxplayer** [sboxgame/issues#3786]
### Describe the bug

This is new visual bug that added in the game after some updates
You will se a line at the coast

### To Reproduce

Just look at the coast and you will see line 

### Expected behavior

No line

### Media/Files

![image](https://github.com/sboxgame/issues/assets/139641395/671c3b49-2cb2-4ca4-b5aa-5bfda5eb7f4e)

**Comment by samzanemesis** [comment]
should be good
