### ISSUE TITLE
Infinite script errors after map cleaning

### ISSUE THREAD

**Issue by alobxplayer** [sboxgame/issues#3788]
### Describe the bug

After typing respawn_entities command you will get infinite errors in console, they can dissapear if you look into side but not for infinity. They're dissapearing after server restart.

### To Reproduce

Type in console respawn_entities command

### Expected behavior

No script errors

### Media/Files

![image](https://github.com/sboxgame/issues/assets/139641395/930b13fd-00d6-4a49-8f0f-84fd5977c25b)
![image](https://github.com/sboxgame/issues/assets/139641395/9af98682-7b8e-4410-a1dc-2ab6103acded)

**Comment by aylaylay** [comment]
Should be fixed now
