### ISSUE TITLE
Add tile view for Fast Texturing tool.

### ISSUE THREAD

**Issue by FullStack0verfl0w** [sboxgame/issues#3789]
### For?

Hammer

### What can't you do?

I'm unable to see what's going on beyond the texture rectangle.

### How would you like it to work?

Like this:
![ftt](https://github.com/sboxgame/issues/assets/36414434/6e887992-8972-47a6-a151-a22d942d2b9b)

It will work best with #3456 implemented.

### What have you tried?

𝅵𝅵𝅵𝅵𝅵 𝅵𝅵

**Comment by aylaylay** [comment]
Added, let me know how you get on with it. We'll probably remake this tool in C# at some point

**Comment by MrBrax** [comment]
incredible change, really wanted something like this. been wondering what's up with the grid though, it doesn't seem to use the regular ^2 units? or that you can't disable the grid altogether
