### ISSUE TITLE
Teleporter Resetting Scale

### ISSUE THREAD

**Issue by B0zy** [sboxgame/issues#3791]
### Describe the bug

Default Hammer Teleporter resets AnimatedEntity Scale after gone through. 

E.i Setting Scale to 0.7 on spawn then going through a teleporter will reset the scale to 1

### To Reproduce

1. Make a basic game and set the animated entity's scale to something other then 1, for example 0.7 
2. Make a basic map with a default hammer teleporter and a exit 
3. Go through the teleporter with the animated entity and the scale will be altered back to 1. 

### Expected behavior

Teleporter's should not change the model's scale, it should stay consistent no matter what. 

### Media/Files

Here's a example of the bug, if you look in the console I am always printing out the Player's Scale. 

[Clip](https://medal.tv/games/nt-desktop/clips/1nkGdZZ8b62US9/d1337U4OYWdO?invite=cr-MSxIaXIsMTQzNDUyMzMs)

**Comment by handsomematt** [comment]
Done
