### ISSUE TITLE
Game Crashes on startup

### ISSUE THREAD

**Issue by JustTab** [sboxgame/issues#3793]
### Describe the bug

Trying to start the game crashes every time. It starts the loading screen for 2-3 seconds, then exits. The same occurs when trying to start in dev mode. I also did a clean install of the game and the same occurred. The log file does not seem to answer the issue very well.

### To Reproduce

Launch the game. Thats it.

### Expected behavior

The game should start up normally

### Media/Files

Log:
2023/08/05 14:27:47.5498	engine/Engine	SteamAPI_Init succeeded.  SteamID is [U:1:1141097715] (76561199101363443), AppID is 590830	
2023/08/05 14:27:47.5876	engine/Steam	CSteam3Client::Activate succeeded.  SteamID is [U:1:1141097715] (76561199101363443), AppID is 590830	
2023/08/05 14:27:49.2355	Generic	Trying to restore menu cookies from a backup...	
2023/08/05 14:27:49.2355	Generic	Failed to load menu cookies from disk!	
2023/08/05 14:27:49.2925	Generic	Trying to restore gamemmenu cookies from a backup...	
2023/08/05 14:27:49.2925	Generic	Failed to load gamemmenu cookies from disk!	
2023/08/05 14:27:49.5760	engine/RenderSystem	Saved video settings config to 'cfg\video.txt'	
2023/08/05 14:27:49.7232	engine/RenderSystem	Saved video settings config to 'cfg\video.txt'	

### Additional context

PC:
Windows 10.0.19045
Intel Core I7-10700 2.90 Ghz
Nvidia RTX 2060 Super
32 Gb RAM

**Comment by DevulTj** [comment]
reverted https://github.com/Facepunch/sbox/commit/02e13ee057b7394fe7831e732d6eff6f4621b7a5, should be live in ~15 minutes, sorry for the inconvenience

**Comment by JustTab** [comment]
Thanks a lot

**Comment by MoskalykA** [comment]
Bug fixed
