### ISSUE TITLE
cube brushes appear as solid color when texture is applied

### ISSUE THREAD

**Issue by JustTab** [sboxgame/issues#3794]
So I am trying to port a hl2 beta map to s&box (e3_industrial to be specific) and in the map, most stuff is made up of these block brushes (not the s&box block brush, but whatever hammer had back then) and trying to apply a custom texture makes it turn into a solid color. I didn't know whether to put this under bugs because it could be a problem with the map. Do you know if anyone here has a fix?
Thanks

P.S. ill probably be in to read responses tomorrow.

**Comment by aylaylay** [comment]
There's not enough information here to fix anything. This will be a problem with however you're porting the map.

**Comment by JustTab** [comment]
I found a fix. It was rendering my custom textures, they were just very small, so you'll have to make the texture scale a small value in the texture editor.
