### ISSUE TITLE
Add ability to change texture scaling per block/shape

### ISSUE THREAD

**Issue by JustTab** [sboxgame/issues#3799]
### For?

Hammer

### What can't you do?

Currently, to change the scale of an image, you use the material editor, but this isn't very useful for porting a map from source 1. It would help a lot to be able to change the scale of a texture for a single mesh or block because one block could have a larger scaling than the other, and there is no way to change this in the editor.

### How would you like it to work?

I want it to work like the texture application tool in the source 1 hammer, or at least a slider that multiplies the scale of the texture by its number.

### What have you tried?

Besides the aforementioned material editor, there is simply no way around the mismatched texture size in old maps.

### Additional context

![Capture1](https://github.com/sboxgame/issues/assets/124010376/201a9e68-ae0e-4eab-b5cd-b293dc63eccf)
![Capture2](https://github.com/sboxgame/issues/assets/124010376/39183c8b-f698-426e-9306-0baf6bbb0a9b)

**Comment by Gmod4phun** [comment]
I suggest you to watch some tutorials because there is texture scaling per face available in Hammer
![image](https://github.com/sboxgame/issues/assets/5991682/4a6a2540-44c2-41e1-b07d-af140bbe3267)

**Comment by bakscratch** [comment]
are you setting the worldscale in the material 
![image](https://github.com/sboxgame/issues/assets/8184184/c3acd125-98ec-419e-a088-cb0e38176d1a)

**Comment by JustTab** [comment]
oh ok thanks guys i could really find that but ill try finding it now

**Comment by JustTab** [comment]
gmod4phun where do you find that menu cause I cant find anything about it online so far

**Comment by JustTab** [comment]
i got it now
