### ISSUE TITLE
Input bug

### ISSUE THREAD

**Issue by ghost** [sboxgame/issues#3800]
### Describe the bug

Sometimes when you join a game s&box doesn't pick up on any input you do, so you have to leave and rejoin that game.

### To Reproduce

1. Join any gamemode
2. And sometimes it happens

### Expected behavior

I shouldnt have to rejoin, should work on the first try.

### Media/Files

no

**Comment by DevulTj** [comment]
I've noticed this too, in the console it'll say all your inputs can't be found which is odd.
