### ISSUE TITLE
How to select all faces that use the same texture

### ISSUE THREAD

**Issue by JustTab** [sboxgame/issues#3803]
I am writing this comment here because I can't get access to the discord, I made a post on Reddit 3 hours ago and it hasn't been approved. The title says it all, I'm trying to do this because I am porting a source map to source 2 with higher quality textures, and its very tedious to select a face 1 by 1 and apply the texture, especially when every texture is replaced with a flashing red checkerboard. Thanks for the responses.

**Comment by handsomematt** [comment]
This is an issue tracker not a support forum.

**Comment by JustTab** [comment]
i explained it in the beginning but okay

**Comment by bakscratch** [comment]
Face mode, right click the material in the current material bit, select faces using material
