### ISSUE TITLE
Razor files with the character "<" result in an error while generating code

### ISSUE THREAD

**Issue by 143mailliw** [sboxgame/issues#3805]
### Describe the bug

Putting the character `<` (including the escaped form, `\<`) anywhere in a Razor file (except for within an @ block) results in the error "Error when generating code" in the log, and "The type or namespace name 'MyPanel' could not be found (are you missing a using directive or an assembly reference?)" in the error list.

### To Reproduce

1. Open a project in the editor, and navigate to Game -> Open in [editor].
2. In the editor, open any Razor file, and in any part of the DOM tree, place a `<`.
3. Observe the bug.

### Expected behavior

The character `<` should appear in the user interface defined in the Razor file.

### Additional context

`<tag><<tag>` is valid: https://codepen.io/william341/pen/BaGEjYv

**Comment by the-remeko** [comment]
Try &lt; instead of <
https://www.rapidtables.com/web/html/html-codes.html

**Comment by 143mailliw** [comment]
> Try `&lt;` instead of < https://www.rapidtables.com/web/html/html-codes.html

I don't actually need to type `<`, I just noticed it and thought it was worth reporting.

**Comment by handsomematt** [comment]
Unescaped < is invalid...
