### ISSUE TITLE
Creating a projected light crashes S2FM

### ISSUE THREAD

**Issue by Wheat-guy** [sboxgame/issues#3809]
### Describe the bug

Creating a projected light immediately crashes S2FM

### To Reproduce

Create a projected light in S2FM

### Expected behavior

Creating a projected light should spawn a Source 1 light, just like in Half-Life Alyx S2FM.

**Comment by aylaylay** [comment]
Shouldn't crash now

**Comment by Wheat-guy** [comment]
> Shouldn't crash now

It doesn't crash anymore, but the light itself isn't working. Also, the option to enable volumetrics is missing. (I know other lights have a fog feature, but at times old volumetrics look way better)
