### ISSUE TITLE
Scroll bug when scrolling on a element with ondoubleclick event

### ISSUE THREAD

**Issue by Mbk10201** [sboxgame/issues#3810]
### What it is?

When we scroll and move at the same time on a element who listen to ondoubleclick, it seems to act like an double click action.

```
<div style="height:200px; width:200px; background-color:red;" ondoubleclick=@(()=> Log.Info("Double click"))>
     Click here
</div>
```
Here the example video: https://cdn.discordapp.com/attachments/1110259447256842332/1138209564743979038/Enregistrement_2023-08-07_223806.mp4

### Why do you need to use this?

To block this effect

**Comment by Mbk10201** [comment]
My bad for the whitelist tag, i missclicked

**Comment by cr4yz** [comment]
This should be fixed in the next build, please lemme know if you have any more troubles around it

**Comment by Mbk10201** [comment]
> This should be fixed in the next build, please lemme know if you have any more troubles around it

Alright thanks, appreciate 🤝
