### ISSUE TITLE
World Text Entity - Message

### ISSUE THREAD

**Issue by MoskalykA** [sboxgame/issues#3817]
### Describe the bug

The `Message` property of the `WorldTextEntity` entity cannot be assigned in C#, the property has `protected set`

### To Reproduce

1. Copy this code
```csharp
var text = new WorldTextEntity
{
	Message = "helllo"
};
```
2. Run this code

### Expected behavior

Be able to assign the `Message` property

**Comment by aylaylay** [comment]
They're now all public

**Comment by MoskalykA** [comment]
thanks
![image](https://github.com/sboxgame/issues/assets/100430077/fb215e29-a184-495f-8837-7e0131624d96)
