### ISSUE TITLE
Animation scaling update destroys some skeletalmeshes

### ISSUE THREAD

**Issue by KaesarZZ** [sboxgame/issues#3821]
### Describe the bug

After today's recompile I found that some playermodels are fucked up. 

This doesn't happen in all my playermodels and the nodepreview works perfectly, so I assume that the problem comes with the skeletalmesh + animgraph.

### To Reproduce

- Download the repro model:

https://drive.google.com/file/d/1OdVgbgKjT-c7P79jUHRM2AM0BsCFOc6v/view?usp=sharing

- Play the animgraph
- The model will disappear

### Expected behavior

It should work as usual.

### Media/Files

https://github.com/sboxgame/issues/assets/40291120/aa0f64e6-d35f-4845-b4a9-2eeb91f78009

**Comment by aylaylay** [comment]
Thanks, I'll look into this

**Comment by aylaylay** [comment]
This should be fixed when the game next updates.

**Comment by KaesarZZ** [comment]
Fixed :)
