### ISSUE TITLE
Can't reset media playback in UI

### ISSUE THREAD

**Issue by Bilbard** [sboxgame/issues#3822]
### For?

S&Box

### What can't you do?

If you create a panel with an animated background gif, there is no way to stop/reset its playback. Further, if you create another panel using the same gif, the two panels are synchronized in animation.

### How would you like it to work?

Either there needs to be a way to reset the playback of a gif, or the ability to use the same piece media twice without synchronization among every instance (this way, you can just create a new panel when needed and the animation can "reset").

### What have you tried?

- Setting the panel's background color to rgba(0,0,0,0) before instantly swapping back to the intended one
- Setting the panel's image to a blank image before instantly swapping back to the intended one
- Setting the panel's image to a different gif with more than 1 frame before instantly swapping back to the intended one
- Deleting and recreating the panel
- All of the above at once and in different combinations

**Comment by aylaylay** [comment]
If you really need to do something like this, I would suggest you create a sprite sheet and a custom shader that selects the sprite for the frame you want. This is only ideal if there's not many frames and the image isn't huge.
