### ISSUE TITLE
Animation scaling doesn't work if model contains jigglebones

### ISSUE THREAD

**Issue by Grodbert** [sboxgame/issues#3823]
### Describe the bug

The new animation scaling is great, but they didn't work when I tried it on a model of mine, I stripped down until I found what broke it and turns out it's jigglebones, disabling them makes the scaling work perfectly.

I have attached the stripped-down file.

### To Reproduce

1. Download .zip file
2. Disable/Enable "balls" jigglebone to see change

### Expected behavior

Scaling should work even with jigglebones, probably not ON jigglebones, just with.

### Media/Files

[models.zip](https://github.com/sboxgame/issues/files/12316829/models.zip)

https://github.com/sboxgame/issues/assets/86626409/77da48ab-f9a2-492e-a8dc-6e738d443b29

### Additional context

Thank you so much Laylard for this feature! I hope seeing a couple bugs don't bug you out, behind closed doors, everyone is very happy with this change.

**Comment by aylaylay** [comment]
Should be fixed now :)

**Comment by Grodbert** [comment]
It works correctly now, thanks.
