### ISSUE TITLE
Add GIF support for vmats

### ISSUE THREAD

**Issue by sugmagaming** [sboxgame/issues#3830]
### For?

Material Editor

### What can't you do?

The texture animation system sucks balls. You have to put every frame on a grid in a single photo perfectly aligned and its annoying and is lame. 

### How would you like it to work?

Let us use gifs for texture animation. It is way simpler.

### What have you tried?

The shitty texture animation system. It's too time consuming to get right.

**Comment by xezno** [comment]
duplicate of #3087
