### ISSUE TITLE
Scrolling too fast on panel with `overflow: scroll` breaks panel 

### ISSUE THREAD

**Issue by quizque** [sboxgame/issues#3834]
### Describe the bug

When you apply the property `overflow: scroll` to a panel and scroll too fast (in this case, a G502 Hero with its scroll wheel unlocked), its contents vanish and don't return until the panel is recreated.

### To Reproduce

1. Create a panel with a series of labels containing text.
2. Apply `overflow: scroll` to the panel
3. Scroll fast

### Expected behavior

The contents should rebound back into view after a user scrolls.

### Additional context

This issue can be seen recreated quickly by opening a chat in any game mode that supports message history (such as sandbox) and scrolling quickly.

**Comment by cr4yz** [comment]
I don't have a hyperscroll mouse to test the insane scrolling but this should be fixed.  Please let me know if it's all good

**Comment by quizque** [comment]
`overflow: scroll` is now working as intended, thank you.
