### ISSUE TITLE
Unable to drag in overlays from asset.party

### ISSUE THREAD

**Issue by micah6082** [sboxgame/issues#3835]
### Describe the bug

When an overlay material is uploaded to asset.party, it is unable to be dragged into hammer from the asset browser.

The Current work around is to download the asset by double clicking and then navigating to your local copy of the asset in the special>everything tab of the asset browser.

### To Reproduce

1. Upload or find an overlay texture on asset.party
2. Attempt to drag it into the 3d view in Hammer (or create an info_overlay and point the asset.party asset to it)
3. Will not drag in/Will not show up as an info overlay.

### Expected behavior

The expected behavior is that the overlay will autoplace like similar overlays in the core game files.

**Comment by handsomematt** [comment]
Give it an overlay tag

**Comment by micah6082** [comment]
> Give it an overlay tag
If you're talking about an overlay tag on asset.party somewhere, there is no obvious place to apply this tag. Additionally, it would then not explain the issue with trying to bring in facepunch official overlays (e.g. facepunch.wall_brick_trim_a_overlay_scaled) failing.

In order to use overlays from asset party you have to first double click the asset to download a local copy, and then navigate to the local copy in the Special>Recent tab of the new asset browser. Then it can be dragged in. This is likely not the intended behavior.

If you're talking about an overlay tag in the .VMAT file through material editor, this is not and was not the issue listed above.

**Comment by handsomematt** [comment]
You'd add it in the settings

![image](https://github.com/sboxgame/issues/assets/1388267/39aa640b-72be-4b1c-af39-dcd30dfb9bda)

**Comment by handsomematt** [comment]
Fuck it, this was shit so I redid how it's done. You don't need the tags anymore and it'll handle static overlays too.

Let me know how you get on.

**Comment by micah6082** [comment]
Works flawlessly and without lag, even when pulled from asset.party. Well done.
