### ISSUE TITLE
Clear/ClearActions does not work in BuildInput event

### ISSUE THREAD

**Issue by f37ch** [sboxgame/issues#3844]
### Describe the bug

Any type of clearing actions does not work in BuildInput event after input system updates.

### To Reproduce

1. Create Client.BuildInput event.
2. Add inside input.ClearActions()/Clear().
3. See that player still can move/use any button.

### Expected behavior

Those methods should work as usual.

**Comment by DevulTj** [comment]
This event doesn't get called anymore
