### ISSUE TITLE
Forklift lift with physics props problem 

### ISSUE THREAD

**Issue by KandaHauK** [sboxgame/issues#3847]
### Describe the bug

Lift not working properly on physics props, need to change another way to use the lift
Try it, you will see show video

I think the problem is the weight, I'm trying with light objects, like balloons, and it seems to work. I also tried with the ragdoll, and it works. A little difficult to maneuver because of small objects, but it works

### To Reproduce

...

### Expected behavior

...

### Media/Files

https://github.com/sboxgame/issues/assets/142222568/c1f1573a-9338-4a98-90be-ad5a0e1d15e6

### Additional context

...

**Comment by yuberee** [comment]
How thick is the collision for the forks?

You either make them thicker or increase physics substeps, it's always about having a compromise when simulating physics with realism and performance.

**Comment by Phyksar** [comment]
This is not the issue with S&box, Facepunch does not implement forklift, you are implementing one and you haven't even provided any code how it works. As an alternative you can provide a simple test case which replicates your problem.
