### ISSUE TITLE
Upload Tilesets to asset.party

### ISSUE THREAD

**Issue by FireKeep-HLA** [sboxgame/issues#3850]
### For?

S&Box, Hammer

### What can't you do?

I can't upload tilesets onto asset.party. This is unfortunate as I've created a wainscot tileset for anyone to use, however I cannot share it with anyone due to this lacking feature.

### How would you like it to work?

You should be able to upload any included materials and models alongside the tileset .vmap and ship it either as one package or a split of the materials/models and .vmap and have them combined into one collection.

### What have you tried?

Crying.

**Comment by handsomematt** [comment]
Renamed #3814 to include tileset, but they're basically the same thing
