### ISSUE TITLE
Cannot move after joining a server, "Couldn't find Input Action"

### ISSUE THREAD

**Issue by chrisspieler** [sboxgame/issues#3855]
### Describe the bug

When joining a Sandbox server, I will often receive numerous errors in console saying things like `Couldn't find Input Action called "voice"`, but there will be a line logged for each action.

When this happens, pressing the movement keys to move around doesn't seem to do anything at all. The only remedy is to reconnect to the server. This happens often enough to me that I usually have to connect to a server twice before I am actually able to do anything.

This issue doesn't seem to be exclusive to Sandbox, as multiple people have reported encountering this issue when playtesting another game.

### To Reproduce

1. Join someone else's game server (e.g. Sandbox)
2. Check the F1 console

### Expected behavior

Inputs should always work after joining a server.

### Media/Files

![20230815032645_1](https://github.com/sboxgame/issues/assets/8889285/13e22a3e-d13d-4d8d-a29d-95a0a370976d)

### Additional context

This issue has been occurring for several weeks.

**Comment by DevulTj** [comment]
I got this today, will try to reproduce and fix

**Comment by f1ndme** [comment]
This has been a long time issue, an potentially frustrating find/fix. But if solved, I believe this would relieve a huge burden on clients.

Also kinda sucks having to explain to completely new S&box players, that it's a common issue. In the hopes they don't assume your game is just junk, and never come back.

**Comment by DevulTj** [comment]
Been looking into this, and it's dead weird.

Sometimes if you join a server, it'll subscribe to stringtables which have the current input settings, but sometimes it'll fail to send them to the client.

Still investigating.

**Comment by theWildRaptor** [comment]
DevulTj, I replicated this glitch multiple times joining a server, this is the log file
[Log - Copy.log](https://github.com/sboxgame/issues/files/12450869/Log.-.Copy.log)

**Comment by theWildRaptor** [comment]
And replicated it from another server as well.
[Log - Copy (2).log](https://github.com/sboxgame/issues/files/12450989/Log.-.Copy.2.log)

**Comment by theWildRaptor** [comment]
Perhaps this is the issue causing it? @DevulTj 
`Client	Error when downloading content	System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.SandboxSystemExtensions.ForEachTaskAsync[T](IEnumerable`1 source, Func`2 body, Int32 maxRunning, CancellationToken token)
   at Sandbox.Package.Download(String absoluteLocation, ILoadingInterface loader, PackageDownloadMode downloadMode, CancellationToken token)
   at Sandbox.PackageManager.ActivePackage.DownloadAsync(ILoadingInterface loader, PackageDownloadMode downloadMode, CancellationToken token)
   at Sandbox.PackageManager.ActivePackage.Create(Package package, ILoadingInterface loader, PackageDownloadMode downloadMode, CancellationToken token)
   at Sandbox.PackageManager.InstallAsync(String packageIdent, String contextTag, CancellationToken token, Nullable`1 options)
   at Sandbox.NetworkClient.DownloadContent(CancellationToken cancelToken)`

**Comment by DevulTj** [comment]
nah, that's unrelated

**Comment by LaggyAsBalls** [comment]
I've been also having this glitch and it seems to be an issue with the lag attributed to the server, such as if a person already in the server is currently spam spawning a bunch of entities while someone is spawning.
