### ISSUE TITLE
s&box Pixels not displayed as current playing game in Steam friends list rich presence

### ISSUE THREAD

**Issue by James76931** [sboxgame/issues#3857]
### Describe the bug

s&box Pixels is not displayed as being open on the Steam friends list. Instead, it says someone (or yourself) has the main menu open despite this not being the case.
For example, this person on my Steam friends list has Pixels open right now:
<img width="317" alt="Screenshot 2023-08-15 at 11 43 48" src="https://github.com/sboxgame/issues/assets/15969024/049868e3-7dfb-48e9-b4e5-ffdba1a7c0bb">

### To Reproduce

1. Launch s&box.
2. Open Pixels from the main menu.
3. Open your Steam friends list, either via the Steam in-game overlay or Steam client itself.
4. At the top of the friends list window, observe that you are displayed as being in the Main Menu despite Pixels being open.
<img width="171" alt="Screenshot 2023-08-15 at 11 49 58" src="https://github.com/sboxgame/issues/assets/15969024/4e8a0df2-8d0d-4d32-b9a0-f98c44d33571">

### Expected behavior

s&box should report to Steam that Pixels is open and not the main menu.

### Additional context

I'm using Windows 11 22H2 (latest stable), RTX 2080 Super, AMD Ryzen 9 3900x.

**Comment by DevulTj** [comment]
Next game build should amend this

**Comment by James76931** [comment]
Sorted. Thank you @DevulTj !
![image](https://github.com/sboxgame/issues/assets/15969024/0c1e4f0f-f27b-4b23-aa85-073aa05ee3d2)

**Comment by James76931** [comment]
Sorry @DevulTj, actually... not 100% sorted. you get a blank rich presence now just after launching s&box and being shown the main menu:
![image](https://github.com/sboxgame/issues/assets/15969024/13c86c9d-0941-4437-a177-1d3cbd1baf1a)
"Main menu" text is only re-displayed after closing a game (in this example I tried Pixels):
![image](https://github.com/sboxgame/issues/assets/15969024/2f1b13a7-0b0f-4612-803c-69173a8f221a)

**Comment by DevulTj** [comment]
Next game build should amend this - let me know how that works out for you

**Comment by James76931** [comment]
Yep the main menu text now displays on first launch. All good now 🎉🎉😄

**Comment by James76931** [comment]
It seems there's a problem with this again. When launching s&box for the first time and selecting a menus-based game (e.g. Pixels), Steam rich presence correctly updates to indicate that you are playing the chosen game. However, it then reverts to stating that you are on the main menu.

Furthermore, if you proceed to play a standard game that places you within a map (e.g. gunfight or sandbox), and subsequently return to the main menu, there is an issue. Upon launching a menus-based game, s&box incorrectly reports that you are playing the previously accessed map-based game. Although there might be a brief moment where the menus-based game is displayed as the currently played game, it quickly switches over.

**Comment by DevulTj** [comment]
Sorry about that - I rewrote how we update rich presence and missed this out. Should be back to normal now 😄

**Comment by James76931** [comment]
Can confirm all is back to normal again 🎉
