### ISSUE TITLE
Rider / ReSharper does not analyse correctly razor files

### ISSUE THREAD

**Issue by Guilhem-Pech** [sboxgame/issues#3859]
### Describe the bug

When creating a new game project and opening it with Rider or Visual with ReSharper plugin, the code analysis is broken on base files and tell me errors that doesn't exist (no error in engine):
![image](https://github.com/sboxgame/issues/assets/15714248/354bee93-f3a8-4930-bb2b-902929d8bba4)
![image](https://github.com/sboxgame/issues/assets/15714248/966df62a-0acb-426b-826e-4d319ca0d2ec)

![image](https://github.com/sboxgame/issues/assets/15714248/ab9f084e-f7e5-44e0-be08-65ce0f26637c)

I also have a warning icon in the dependency without finding what it means 
![image](https://github.com/sboxgame/issues/assets/15714248/7eb106a1-c621-4aa0-8148-ea6d01ce965b)

### To Reproduce

1. Create a new game project
2. Open the solution on Visual with ReSharper or Rider
3. Open a random razor file

### Expected behavior

No error

### Additional context

I mainly use Rider developing C# application

**Comment by handsomematt** [comment]
You'll have to [submit an issue with Rider](https://youtrack.jetbrains.com/)
