### ISSUE TITLE
Particles from asset party don't work.

### ISSUE THREAD

**Issue by sugmagaming** [sboxgame/issues#3862]
### Describe the bug

When you download a particle from asset party they just straight up don't work my guy

### To Reproduce

Download a particle from asset party.
Try to use it.
Shit don't work.

### Expected behavior

Work please.

**Comment by handsomematt** [comment]
do you mean hammer or code

**Comment by sugmagaming** [comment]
> do you mean hammer or code

Hammer

**Comment by handsomematt** [comment]
sorted
