### ISSUE TITLE
Couldn't create MenuSystem

### ISSUE THREAD

**Issue by FatalDarknessReal** [sboxgame/issues#3869]
### Describe the bug

When i joining in the game i always getting this message and getting black screen

### To Reproduce

Join in game
Get facepunch logo
Get error

### Expected behavior

Getting menu screen

### Additional context

I am running windows 10 ltsc with Intel graphics with 312 mb and intel pentium n3700 1.60GHzb(4 cores or smth)

**Comment by handsomematt** [comment]
So far below minimum spec
