### ISSUE TITLE
Game crashes on startup with System.AccessViolationException

### ISSUE THREAD

**Issue by starwarswii** [sboxgame/issues#3872]
### Describe the bug

when launching the game, (either through steam or by running the exe directly), steam shows it as running, and i get a bit of loading activity indicated on my mouse, but then about 4 seconds later, steam says the game is no longer running

there's never any sort of loading screen popping up or icon appearing on my taskbar. when starting the game while looking at task manager, it appears in there for a few seconds, and then disappears as it crashes

i've heard that the logs are supposed to appear in `sbox/logs/`, but that folder doesn't exist, and isn't created when the crash happens. manually creating the folder also doesn't result in any logs

i've tried this on 2 different computers, and got the same result

### To Reproduce

- launch the game
- nothing happens for 4 seconds
- the came closes/crashes, without ever giving any visuals (besides steam saying the game was running, and then not running)

### Expected behavior

the game launches normally, and i get to some sort of main menu

### Media/Files

as mentioned above, there are no logs. i'm hoping some logs will appear connected to my steam id: `76561198046623712`

### Additional context

steam id: `76561198046623712`

computer 1:
windows 10 home, version 1803
intel core i7-4720HQ, 2.60ghz
16 gb ram
intel HD graphics 4600
nvidia geforce gtx 960M
directx version 12

computer 2:
windows 10 home, version 22H2
amd A8-6410 APU
8 gb ram
AMD R5 graphics
directx version 12

not 100% sure if these meet the min requirements (though pretty sure the first one should), but i was just hoping for anything more than an immediate crash. poor performance is acceptable

**Comment by starwarswii** [comment]
checked event viewer, got these logs. this seems more useful:

```
Application: sbox.exe
CoreCLR Version: 7.0.723.27404
.NET Version: 7.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at NativeEngine.EngineGlobal.SourceEngineInit(CMaterialSystem2AppSystemDict)
   at Sandbox.SourceEngineApp.Initialize()
   at Sandbox.Program.LaunchGame()
   at Sandbox.Program.Main()
```

```
Faulting application name: sbox.exe, version: 1.0.1.0, time stamp: 0x64b07659
Faulting module name: coreclr.dll, version: 7.0.723.27404, time stamp: 0x646e214e
Exception code: 0xc0000005
Fault offset: 0x00000000001c9f06
Faulting process id: 0x5ed0
Faulting application start time: 0x01d9d225808369b5
Faulting application path: C:\Program Files (x86)\Steam\steamapps\common\sbox\sbox.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.7\coreclr.dll
Report Id: 035f8858-2ced-4558-938b-a29b4408a4c9
Faulting package full name: 
Faulting package-relative application ID: 

```

**Comment by handsomematt** [comment]
Event viewer logs are helpful thanks, can you try the following:

* Verifying game files
* Updating .NET to latest (7.0.10)
* Maybe running with -vulkan but that's a shot in the dark

Do you have any third party antivirus software too?

**Comment by starwarswii** [comment]
I have .net versions 7.0.7 and 7.0.2 installed
should I uninstall them both when installing 7.0.10?

Also, wanted to double check which installer I need from here
https://dotnet.microsoft.com/en-us/download/dotnet/7.0

No third party antivirus

**Comment by Vysp3r** [comment]
I have the same exact problem, but I only have the latest .net version installed. https://github.com/sboxgame/issues/issues/3876

**Comment by handsomematt** [comment]
Yeah try uninstalling them and doing a complete reinstall with https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-7.0.10-windows-x64-installer

**Comment by starwarswii** [comment]
i uninstalled both versions, than ran this to install, but same error

```
Application: sbox.exe
CoreCLR Version: 7.0.1023.36312
.NET Version: 7.0.10
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at NativeEngine.EngineGlobal.SourceEngineInit(CMaterialSystem2AppSystemDict)
   at Sandbox.SourceEngineApp.Initialize()
   at Sandbox.Program.LaunchGame()
   at Sandbox.Program.Main()
```

this event viewer message makes it seem that it is indeed picking up the new dotnet version

**Comment by starwarswii** [comment]
i tried verifying game files, and restarting my computer, but same result

**Comment by starwarswii** [comment]
this is still a problem. using newest version of s&box.

tried installing `Microsoft Windows Desktop Runtime 7.0.10 x64` (the option it sends you to if you try to run the game without a dotnet runtime installed), as well as the normal `Microsoft .NET Runtime 7.0.10 x64`. neither fixed the issue

**Comment by starwarswii** [comment]
i think i fixed it. i had a pretty old version of steam installed, just updated to the latest one. now it works and the game boots and plays normally
