### ISSUE TITLE
The game doesn't open

### ISSUE THREAD

**Issue by Vysp3r** [sboxgame/issues#3876]
### Describe the bug

Last night I tried to play, but the game was not starting anymore. I was playing fine that morning. I tried to verify the game files and make a clean install of the game, but to no avail.

### To Reproduce

1. Start the game
2. Does not open

### Expected behavior

I would expect the game to start and run like it was previously.

### Media/Files

```
Description: A .NET application failed.
Application: sbox.exe
Path: C:\Program Files (x86)\Steam\steamapps\common\sbox\sbox.exe
Message: Failed to load System.Private.CoreLib.dll (error code 0x80070002)
Path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.10\System.Private.CoreLib.dll
Error message: Could not load file or assembly 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.10\System.Private.CoreLib.dll'. The system cannot find the file specified. (0x80070002)
Failed to create CoreCLR, HRESULT: 0x80070002
```

### Additional context

I play on Windows 11, but I have Fedora 38 also installed on my system.

**Comment by Vysp3r** [comment]
I fixed it by reinstalling .NET 7!

**Comment by starwarswii** [comment]
@Vysp3r can you give more details about how exactly you re-installed it? just removed it and ran the new installer? any computer restarts or s&box re-installs involved?

**Comment by Vysp3r** [comment]
@starwarswii I mean you go in your control panel and delete the .NET 7 stuff and go on the official website to download it and then install it

**Comment by starwarswii** [comment]
i tried that, but no luck. you just reinstalled the 'Microsoft .NET Runtime - 7.0.10 (x64)' correct? s&box also installed some c++ redistributables for me on first launch. wasn't sure if you also re-installed any of those
