### ISSUE TITLE
Weird error textures in avatar editor

### ISSUE THREAD

**Issue by berryeater** [sboxgame/issues#3877]
### Describe the bug

When you go to the avatar editor and move the camera a bit you can see 3 error models and a missing texture

### To Reproduce

Go to "avatar" tab
Move the camera to the right
See the error models and texture

### Expected behavior

There shouldn't be error models in the avatar editor

### Media/Files

![image](https://github.com/sboxgame/issues/assets/142694486/88d30d8c-6eef-4868-bb0f-a4fe508f54d8)

**Comment by aylaylay** [comment]
I believe @bakscratch fixed this recently
