### ISSUE TITLE
Add Vector2.Abs() to API

### ISSUE THREAD

**Issue by thief** [sboxgame/issues#3879]
### For?

S&Box

### What can't you do?

Instead of having to write your own absolute value function for the Vector2 type, include it in the API (Vector3 already has [its own](https://asset.party/api/Vector3.Abs()) Abs function in the API). 

### How would you like it to work?

Same as Vector3.Abs(), return a new Vector2 where both values are positive.

### What have you tried?

n/a

**Comment by aylaylay** [comment]
Added
