### ISSUE TITLE
Antivirus False-Positive

### ISSUE THREAD

**Issue by 4g0tt3nSou1** [sboxgame/issues#3884]
### Describe the bug

S&Box is being falsely detected by Bitdefender's Cloud/Heuristic Detection.
Part of the game is being detected as suspicious.

Flagged as: Gen:Suspicious.Cloud.4.1DW@aa7f!nci

### To Reproduce

Have S&Box, Update to build 11987874.
Have Bitdefender Antivirus
File is quarantined.

### Expected behavior

Not throw a false-positive? Not really a you guys issue moreso someone probably needs to reach out to bitdefender and check and see about getting removed as a detection

### Media/Files

![image](https://github.com/sboxgame/issues/assets/20174713/2952949a-842e-4be9-9c2f-8f3f4b1fcebe)

### Additional context

Don't think relevant, But:
![image](https://github.com/sboxgame/issues/assets/20174713/f22fb2ac-7531-4ed6-9a83-6fd4cbfbc767)

![image](https://github.com/sboxgame/issues/assets/20174713/4e93c226-9bf6-4c8e-9b79-0a4fc5ddfe49)

VirusTotal DOES NOT echo the same detection:
https://www.virustotal.com/gui/file/f2e41d5c304dbf00f04ea7e3bdfd404013b3e72941a59a1f935cc605fda3252d?nocache=1

**Comment by 4g0tt3nSou1** [comment]
Now, because false-positive, Course of action of just restoring the file and adding to detections was done. Do NOT need to troubleshoot this myself, moreso trying to let the appropriate people know that they are being detected as a false-positive

**Comment by 4g0tt3nSou1** [comment]
Uhm, I agree You guys should. It's not my app, Due respect, This is for a rep on your guy's side to handle, not an end user

**Comment by kuba64534** [comment]
did you found a way out of this?

**Comment by 4g0tt3nSou1** [comment]
> did you found a way out of this?

Ultimately, This has little to no end-user impact. I simply whitelist the file as I trust it as a false positive and move on.

From Dev/Facepunch/Etc's POV, Impact is a bit greater. Obviously one doesn't want part of or a project itself falsely flagged. 
I mean, I get you guys are busy, Got a lot to do and bigger fish to fry. But this isn't something an end-user fixes for you. This is 100% something where someone internal writes up an email explaining what's going on, and internally handles resolution. Sorry but I mean let's say there were more detections. You REALLY want an END-USER responsible for being the face to these companies advocating for your software?

**Comment by kuba64534** [comment]
how to i whitelist it i searched it but i can't find it

**Comment by 4g0tt3nSou1** [comment]
> how to i whitelist it i searched it but i can't find it

![image](https://github.com/sboxgame/issues/assets/20174713/1e03af11-d75c-4171-8275-72832004c0a5)

![image](https://github.com/sboxgame/issues/assets/20174713/e5abbfa5-ef07-424f-9daf-756834b0c19a)

This slightly varies based on your AV.

**Comment by kuba64534** [comment]
hey um antivirus right but should i mark on demand scan only

**Comment by 4g0tt3nSou1** [comment]
> hey um antivirus right but should i mark on demand scan only (only)
> 
> also should i mark embbeded scripts

Ultimately I suggest against this, but at this point this derails this report. If you want some help with antivirus stuff, I'd be 100% down to help you out and answer whatever questions, but I suggest instead you message me directly as it's off-topic. I am in their discord and we can talk there or you can PM me should you wish

Name is the same as in github.

**Comment by 4g0tt3nSou1** [comment]
I additionally messaged a "Ryleigh" in the discord, labeled as facepunch staff, was the first person showing online at the time. 

We need to get this addressed from the team's end, don't place it on end-users to talk to vendors on a "Trust me bro". Not good practice.

**Comment by handsomematt** [comment]
The game updates 10+ times a day with new binaries, false positives will happen on commercial anti-virus software that tries hard to oversell its value with crappy detection. We're not going to reach out to every shit av vendor for every update we push, that's insanity.

**Comment by 4g0tt3nSou1** [comment]
So I 100% respect where ur coming from here. 1000% this was to be expected and should continue to be expected. However; I do think you do have to consider impact a bit more here. 99% of people are not going to be willing to decompile the binaries to figure out if the detection is a falsepos or not, and jump to the wrong conclusion. Now, at the same time, 100% would be insanity to handle every single falsepos in this stage. However; I'd disagree with the assessment that Bitdefender is some shitty AV vendor, While like every vendor of course they are up to their own game; but as of current it is also one of the more reputable vendors.

End of the day, it's your project, your reputation. I just don't see the logic of having an enduser of all people being the spokesperson for that. I mean I just see too many what-ifs here that aren't good for facepunch when it comes to trusting an enduser to handle this. I get from a dev standpoint, y'all are busy, y'all don't have time to be hunting this stuff down. But then again, Facepunch isn't exactly an indie dev. You really telling us that there isn't someone who liasons public relations, whom  could reach out?

**Comment by TheBoxTrot** [comment]
The game is in dev preview so even if this was something to fix it would be after release, and like Matt said these anti viruses have false positives all the time no real point in wasting time on this imo.
