### ISSUE TITLE
facepunch.v_silencer_9mm is set at the wrong scale.

### ISSUE THREAD

**Issue by eEight-dev** [sboxgame/issues#3885]
### Describe the bug

This asset is set at the wrong scale: https://asset.party/facepunch/v_silencer_9mm
![1](https://github.com/sboxgame/issues/assets/120290229/9a358258-1eeb-46e2-8388-d48ef65ab4ab)
Every time I want to use it with one of my assets, I have to scale it down in code.
Please set it to cm instead of inches.

### To Reproduce

.

### Expected behavior

Correct scale:
![1](https://github.com/sboxgame/issues/assets/120290229/fd8dc80b-4978-4d1c-9c2f-1ce5fd453237)

### Additional context

The world model version of this asset seems to be at the right scale. It's only the viewmodel that isn't right.

**Comment by bakscratch** [comment]
Should be correct now thanks.

**Comment by eEight-dev** [comment]
![1](https://github.com/sboxgame/issues/assets/120290229/99618555-850a-475b-a9f0-1cbe20ee9889)
It's still like this @bakscratch
