### ISSUE TITLE
snd_event_point will not play if no player in radius when activated

### ISSUE THREAD

**Issue by KingOfTheFBI** [sboxgame/issues#3896]
### Describe the bug

snd_event_point will not start playing its sound if no players are in range when activated. It will if "Start on Spawn" is checked.

If this is intended I highly recommend there is a check for this.

My use case is a song playing around a map from speakers all activating at the same time when a certain event on the map is triggered. This will not happen for all of them if no players are not in radius of all of them.

### To Reproduce

1. Make a snd_event_point
2. Put a sound on it
3. Make it activate when you are out of its radius
4. Walk into radius

### Expected behavior

It should be playing

**Comment by handsomematt** [comment]
When you say activate, do you mean via a Hammer input?

**Comment by KingOfTheFBI** [comment]
> When you say activate, do you mean via a Hammer input?

The input is set up correctly, it just not play when it is set an output.

Ex press button to play sound set up but if out of radius it wont play and when I get in radius will still be silent even if it SHOULD be playing.

**Comment by handsomematt** [comment]
Deleted entity
