### ISSUE TITLE
Likely False Positive

### ISSUE THREAD

**Issue by ploonyplane** [sboxgame/issues#3903]
### Describe the bug

Seems a file located at ~.\SteamLibrary\steamapps\common\sbox\bin\win64 causes a false positive in Bitdefender and a couple of other AVs. The file in question is "resourceinfo.exe". Attached is a screenshot from Bitdefender and here is a link to the Virustotal scan: https://www.virustotal.com/gui/file/f7707217fe44814d2f724680d1dcbf977e68d0c6a589b566c5b1e34ead86a7f3/detection
![image](https://github.com/sboxgame/issues/assets/136959043/bb73a3f8-c588-4719-8124-03aab6dd5a3f)

### To Reproduce

Automated scan of file "resourceinfo.exe" or by dragging file to virustotal shows a handful of what are likely false positives.

### Expected behavior

There should be no detected malware within the game.

### Additional context

Windows 11, NVIDIA graphics, intel processor. Game installed on non boot SSD.

**Comment by Adesii** [comment]
duplicate of #3884

**Comment by ploonyplane** [comment]
> duplicate of #3884

tried searching over and over different terms, somehow didn't find this. apologies.
