### ISSUE TITLE
Custom GameResource extension naming collisions

### ISSUE THREAD

**Issue by Phyksar** [sboxgame/issues#3904]
### Describe the bug

Currently in S&box you can create multiple custom resources with one same extension, there's nothing preventing you from doing that. The problem starts when you want to edit these resources, because when you double-clicking them in the Assets Browser, S&box should decide which editor it should open and for different resources it will always be the editor of one type.

### To Reproduce

```csharp
[GameResource("Game Resource A", "res", "")]
public class GameResourceA : GameResource {}

[GameResource("Game Resource B", "res", "")]
public class GameResourceB : GameResource {}

[GameResource("Game Resource C", "res", "")]
public class GameResourceC : GameResource {}
```
- GameResourceA opens with editor for GameResourceC
- GameResourceB opens with editor for GameResourceC
- GameResourceC opens with editor for GameResourceC

### Expected behavior

First time when I saw this way of game resource implementation, I though - "why do we need to specify an extension?", because these files are just plain JSONs, there's no need to disguise them as some "strange" files. Looks like some developer liked the idea of declaring custom extensions, but really this idea is bad because it doesn't solve the naming collisions which will happen, since the maximum size of an extension is only 8 letters and developers will try to type words associated with its resource. My idea is that you should remove the need to specify extension completely
```csharp
[GameResource("Game Resource A", "")]
public class GameResourceA : GameResource {}
```
And how does the S&box will know what editor it should open? Well, since these file are JSONs you can write their types right in the structure, like this:
```json
{
  "type": "Sandbox.GameResourceA",
  "data": {}
}
```
The `data` field will be the container for all serialized properties of the `GameResourceA`.

**Comment by handsomematt** [comment]
I don't see us changing to this polymorphism system.

**Comment by Phyksar** [comment]
@handsomematt but you still have the bug, why do you closing this issue?

**Comment by handsomematt** [comment]
I added a warning when you have ambigious GameResources now.

**Comment by Phyksar** [comment]
@handsomematt thanks
