### ISSUE TITLE
ToType extension method throws when type has multiple implicit converters

### ISSUE THREAD

**Issue by peter-r-g** [sboxgame/issues#3910]
### Describe the bug

The ToType extension method gives us the ability to convert strings into any type so long as it contains an implicit operator to the type from a string. If you define that as well as any other implicit converters S&box will start throwing an `AmbiguousMatchException`.

### To Reproduce

1. Create a type with two or more implicit converters.
2. Try to use the ToType extension method to convert a string into your type.
3. AmbiguousMatchException thrown.

### Expected behavior

For no exception to be thrown and for the string to be converted into the desired type.

### Additional context

Obtaining the implicit method should be something like the following:
```cs
MethodInfo method = t.GetMethod( "op_Implicit", BindingFlags.Static | BindingFlags.Public, new Type[] { typeof(string) } );
```

**Comment by handsomematt** [comment]
Hate this fucking method, thanks!
