### ISSUE TITLE
Localization Not working

### ISSUE THREAD

**Issue by Nicorebo-18** [sboxgame/issues#3915]
### Describe the bug

So in the game, i try to change the language to spanish, for example but when I save it and come back, it just doesen't save and it's still on english

### To Reproduce

1. Open S&Box (Not editor)
2. Go to settings> Language
3. Change it to spanish for example
4. Save and return
5. Go back to Settings>Language

### Expected behavior

To save the state of your localization

**Comment by DevulTj** [comment]
Duplicate of https://github.com/sboxgame/issues/issues/3891
