### ISSUE TITLE
My antivirus (bitdefender) detect an malware if i install the game

### ISSUE THREAD

**Issue by Khimalthan** [sboxgame/issues#3918]
### Describe the bug

My antivirus (bitdefender) detect in the game files a malware if i install the lastest update or reinstall the game (with older updates i never had problems). the file name is resourceinfo.exe and i think theres others files he detects. and when i make an exception in the antivirus or restore the file. steam stop the download and says disk write error

### To Reproduce

1. install the game or the lastest update with bitdefender open

### Expected behavior

my antivirus should not "protect" me for an "malware". it never happened before.

**Comment by sphaxa** [comment]
duplicate of #3884 

contact bitdefender yourself, facepunch has made it clear that they won't (and they shouldn't have to) reach out on behalf of players with different antivirus programs. The game is in a constant updating state so you will need to find a way around it on your own.

**Comment by Khimalthan** [comment]
Okay i will try to do something thanks

**Comment by beefypogalo** [comment]
Can confirm, this happens to me too. I've reported the file to bitdefender as a false positive.
