### ISSUE TITLE
`justify-content: flex-end;` causes unexpected behaviour with `overflow: scroll;`

### ISSUE THREAD

**Issue by quizque** [sboxgame/issues#3919]
### Describe the bug

Using `justify-content: flex-end;` on an element with `overflow: scroll;` causes the drag scroll behaviour to freak out and reset while dragging.

### To Reproduce

1. Add `overflow: scroll;` to the element
2. Add enough children to allow for drag scrolling
3. Add `justify-content: flex-end;`  to the element
4. Drag scroll

### Expected behavior

Ideally, it will would be the same as `justify-content: flex-start;`.

### Media/Files

Video of expected behavior (`justify-content: flex-start;`): https://imgur.com/ARyFoSl
Video of current behaviour (`justify-content: flex-end;`): https://imgur.com/BZgNKtE

**Comment by cr4yz** [comment]
I reverted my commit that broke this a while ago, please re-open this and let me know if you still have troubles with scrolling.
