### ISSUE TITLE
Make Game Menu optional

### ISSUE THREAD

**Issue by yuberee** [sboxgame/issues#3920]
### For?

S&Box

### What can't you do?

I'm unable to play games without having to click 8 buttons first.
Game Menus are nice, all of my games will have them and I hope most games can use them, but it would be nice to just boot up a game the old way because at the end of the day UI, especially main menu, is one of the last things most developers work on, so right now most singleplayer games shipped are the following experience:
1. Open the game
2. Download menu files
3. Click Create Game
4. Drag slider to 1 player
5. Click on the maps
6. Look for the correct map (Impossible if the map gets shipped with the game, so this is a point of failure already)
7. Create your server
8. Download the game
Then you finally get to play the singleplayer game.

I understand that if we give people a way not to use Game Menus, chances are they won't use them at all, but I think that's fine, not every game needs a custom menu and I definitely prefer a game where I just boot up immediately instead of going through the aforementioned steps.

### How would you like it to work?

First off, as mentioned on other issues, the default Game Menu files aren't shipped with the game, developers can say you just copy the one on the core folder onto your game and fix compatability issues, but this isn't beginner friendly at all. I'll just chalk this up as Facepunch already knowing it's a problem since it's pretty obvious, but I'll still give my opinion because of what's coming up next:
![image](https://github.com/sboxgame/issues/assets/59583743/005a7425-5764-490f-b776-5e3a8853123c)
By not selecting the Include default Game Menu, your game will automatically not have a Game Menu and launch straight into the Loading Screen. This setting can be changed in the Project Settings:
![image](https://github.com/sboxgame/issues/assets/59583743/34e23ea3-44e0-413b-945f-49bfb4cc580c)
When you have the "Has Game Menu" checkbox not selected, the Menu Files section on the left disappears, and the Launch Config text field appears, which lets you select a Launch Config to use to boot up your game, it will be the standard Launch Config if not selected or invalid.
You could also expand the Launch Config to include Player Count, Server Name etc... This way you can select local maps shipped with the game, which is currently impossible if you were to use the default Game Menu, and I'm sure that drives off a lot of developers upon seeing they have to mess around with the Game Menu just to get their first singleplayer game working, which is the opposite of beginner friendly.

### What have you tried?

I've been around for long enough, made enough games, and made enough tutorials that I can say right now making a game is the most beginner unfriendly it has ever been, all because of the Game Menu, which hit S&box the worst moment as Invite Codes were opened up and we received a huge influx of potential developers.

### Additional context

I hope I don't sound condescending, because I know Facepunch knows it's a problem, and this Feature Request is just me giving my opinion on what would be the most beginner friendly to make your first game, or hell just develop a game at any point of your journey.

Also to note that Game Menu is a very early feature, that it's prone to changes, that it will probably get reworked on, just hoping this feature request gives you the POV of both a developer and a player.

**Comment by ShadowBrian** [comment]
Menu templates would probably solve this entirely, just have specific example/placeholder menus that are easily added to your project at creation (and later on) that just give you close to the exact feature set your game needs (not every game needs a map selection screen for example)

**Comment by CarsonKompon** [comment]
> Menu templates would probably solve this entirely, just have specific example/placeholder menus that are easily added to your project at creation (and later on) that just give you close to the exact feature set your game needs (not every game needs a map selection screen for example)

I was going to suggest exactly this. Especially since you could have user-defined menu templates that expedite certain processes if you have no menu programming knowledge/experience.
