### ISSUE TITLE
[Website] Stats on most games don't increment properly

### ISSUE THREAD

**Issue by trende2001** [sboxgame/issues#3922]
### Describe the bug

I've encountered a problem where the code to increment the value of a stat is correct but it doesn't seem to be doing anything on the asset.party side of things. I've done a little more research and it turns out that only some games are able to see their stats being updated (like TTT)

### To Reproduce

See Media/Files

### Expected behavior

Stats should propagate the correct value for every game properly.

### Media/Files

![carbon (1)](https://github.com/sboxgame/issues/assets/68961063/827401b0-b6ca-4f94-bfff-87cfdc45b938)
![image](https://github.com/sboxgame/issues/assets/68961063/7a1097b9-4c0c-47bf-b2e7-2d686808dd3d)

**Comment by trende2001** [comment]
For clarification, LastDamage.Attacker does work in my code. I set the attackers health to 100 whenever the attacker kills someone

**Comment by chrisspieler** [comment]
I've also noticed this on duccsoft.ohio_rp

<img width="1020" alt="image" src="https://github.com/sboxgame/issues/assets/8889285/5e1a5fed-551a-48bc-987e-c597052659c7">

From the behind code of some menu UI:
<img width="266" alt="image" src="https://github.com/sboxgame/issues/assets/8889285/3d6cc744-342a-4ca4-b738-0e5eed538ebc">
Under the same conditions that the counter on screen gets updated, the stat online should also be getting updated.

**Comment by CarsonKompon** [comment]
This is also an issue in Wise Guys. I implemented stats at the same time as I did in Home but it isn't working in Wise Guys (but is working in Home). I threw debug logs in each call and I know the functions are being called but no results...

**Wise Guys:**
![image](https://github.com/sboxgame/issues/assets/5159369/8688de7d-c9fa-4f63-ab2a-048077dbe841)

**Home:**
![image](https://github.com/sboxgame/issues/assets/5159369/06f73907-dd94-42ee-b605-c2d159f3131f)

**Comment by trende2001** [comment]
Works
