### ISSUE TITLE
[Shadergraph] Shader Preview Render Backface Toggle

### ISSUE THREAD

**Issue by Jammie3d** [sboxgame/issues#3923]
### For?

S&Box

### What can't you do?

When working on shaders in the shadergraph I can't easily see how things will look with render backfaces enabled.

I'm currently working on a fireball effect which is intended to be 2 sided, but I currently have to go back and forth between the shadergraph and material editor previews to check my changes.

### How would you like it to work?

Add a toggle either in the Preview window settings, or the shader properties next to the Blend Mode dropdown.
![image](https://github.com/sboxgame/issues/assets/60801006/89d079b2-5da0-48ee-bd9a-bd315ae8a3f1)

### What have you tried?

Having the material editor open with render backfaces enabled, and checking that.

### Additional context

If we ever have an "Is Front Face" node it would be vital for previewing the effects of that.

**Comment by aylaylay** [comment]
Added render option

**Comment by Jammie3d** [comment]
Perfect, thank you very much!
