### ISSUE TITLE
`Sandbox.BaseFileSystem.ReadJson` does not throw an exception when the file is missing

### ISSUE THREAD

**Issue by PolSpock** [sboxgame/issues#3925]
### Location

https://asset.party/api/Sandbox.BaseFileSystem.ReadJson%3CT%3E(string,T)

### Summary

`Sandbox.BaseFileSystem.ReadJson` does not throw an exception when the file is missing

The documentation say `Read Json from a file using System.Text.Json.JsonSerializer. This will throw exceptions if the file is missing, inaccessible or not valid json.`

However if you `try/catch` and use `ReadJson` on an inexistent file, you will not grab any exception. You will get a `null` value.
However, you will get an exception if the JSON is malformed.

```
try
{
	var test = FileSystem.Data.ReadJson<IDictionary<string, string>>( "test.json" );
	// return null but no exception like the documentation says
}
catch ( Exception e )
{
	Log.Info( e );
}
```

**Comment by DevulTj** [comment]
Updated the docs to reflect a lack of exception, since the second argument of ReadJson is a default value
