### ISSUE TITLE
Demo camera bug (Spazzes out and can not use devcam while in demo mode)

### ISSUE THREAD

**Issue by subzerohurley** [sboxgame/issues#3926]
### Describe the bug

As the title says.
Of course it's not game breaking and is certainly low on the priority list but i wanted to report it because personally it's useful for creators!
Basically the Demo mode is essentially theater/replay mode. 
problem is that while watching the demo's, you can NOT enter devcam (free cam, no clip, call it whatever) 

### To Reproduce

while in a game/match, you hit ~ to open the console and type "record (name)" and it records.
it then records every movement and action, once you're done and type "stop" it saves. 
go to the main menu and type "demoplay (the name you set)" and it'll play!
while the demo plays, there's been ALOT of camera jank i've noticed and outside of that, when i hit F2, it doesnt go into devcam. 
Even if it's enabled, even if i hosted, etc, simply doesnt work

### Expected behavior

It's meant to go to devcam when you hit F2

**Comment by DevulTj** [comment]
It's pretty unsurprising that the demo system doesn't really work - we should probably remove the native system at some point, and with the meld project (the process of removing server.dll, client.dll and bringing a lot more of the loop into C#) it'll be feasible to implement in your own projects, or as a feature we release ourselves.
