### ISSUE TITLE
Add Entity.IsPawn

### ISSUE THREAD

**Issue by chrisspieler** [sboxgame/issues#3927]
### For?

S&Box

### What can't you do?

There are some cases where it's useful to know whether a given entity is a pawn. Entity.Client and Entity.Owner are set on more than just active pawns, so those properties won't reliably tell you whether an entity is a pawn. 

### How would you like it to work?

```csharp
public bool IsPawn => Client != null && Client.Pawn == this;
```

### What have you tried?

Manually doing this check myself. It works, but it would be nice for discoverability reasons if there were an IsPawn property that shows up via Intellisense.

**Comment by xezno** [comment]
Should be fixed on next build
