### ISSUE TITLE
Error loading models with Cloud.Model if the model has a underscore

### ISSUE THREAD

**Issue by FEinerhand** [sboxgame/issues#3929]
### Describe the bug

Some Models generate an error: Generic CloudAsset: Unknown package (facepunch.v_mp5) when loading it via the Cloud.Model function. It seems like it is related to the underscore.

### To Reproduce

Open Any GameMode
Call Cloud.Model("facepunch.v_mp5");
Error appears in the console.

### Expected behavior

It should load the model without issues.

### Additional context

I tried some models without an underscore and it worked fine.

**Comment by FEinerhand** [comment]
Also tested with other Models with underscores same behavior
![image](https://github.com/sboxgame/issues/assets/63034968/8cd92fcc-1143-4374-a306-cec06c0345a6)
even tho it does exist: https://asset.party/facepunch/v_silencer_9mm

**Comment by DevulTj** [comment]
Tried reproducing this to no avail. I've spoken to you on Discord about getting a repro project - just waiting on that now.

Note: Cloud.Model/Material/etc uses codegen to reference the package to be downloaded automatically. You can't use `Cloud.Model( GameResource.Model )` for example, as it's all done at compile time.

(This may not be the case for this specific issue, but is worth noting)

**Comment by MrBrax** [comment]
I can't get this to work, is it because I'm using a dedicated server with a local project?
