### ISSUE TITLE
Steam Networking Relay Implementation

### ISSUE THREAD

**Issue by Niconami** [sboxgame/issues#3933]
### For?

S&Box

### What can't you do?

Steam networking is currently either unimplemented or not currently working correctly, as a result you cannot use a relay to hide your IP address when connecting to a server. 

### How would you like it to work?

Standard implementation allows you to do this and the feature would work as standard such as in other games.

### What have you tried?

Currently the only way to achieve this would be a VPN.

**Comment by cashmen123** [comment]
S&Box uses steam datagram relay, you cannot opt out of it. Your IP is hidden from the server.

Any entities to "leak" your IP address are not the server leaking it.

**Comment by cashmen123** [comment]
Even so, HTTP requests are offloaded to Steam Web Helper. It runs as an entirely different process and handles the networking for grabbing web data itself. I obviously don't have docs on it but I'd be surprised if there's a way to route steam web helper requests through SDR.

**Comment by Niconami** [comment]
Steam In-Game interface usually tells you if your going through a relay when connecting to a server, it didn't when I connected so I assumed it doesnt
