### ISSUE TITLE
Physgun rotation speed setting

### ISSUE THREAD

**Issue by NotSteamMan** [sboxgame/issues#3939]
### For?

S&Box

### What can't you do?

It would be amazing if you added a rotation speed setting for the physgun.

### How would you like it to work?

I want the setting to be slider, similar to the FoV slider.

### What have you tried?

I have tried setting mouse rotation speed, worked but wasn't great to play with.

**Comment by TheBoxTrot** [comment]
this is an issue for the gamemode not the actual game post it here https://github.com/Facepunch/sandbox/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc although keep in mind the gamemode is getting remade at some point
