### ISSUE TITLE
Phys Gun ray is not visible with water behind

### ISSUE THREAD

**Issue by WolfRayet11** [sboxgame/issues#3942]
### Describe the bug

When using a Phys Gun, the ray of the phys gun wont be visible when water is behind it from a player's vision.

The ray's reflection is still visible in the water though.

### To Reproduce

1. Open a map with a big water source in it
2. Walk to the edge of the water source.
3. Aim and use your physics gun so it's ray will be right above the water or under it.

### Expected behavior

The ray will be visible as expected from a normal ray. For example a phys gun ray with no water in it's background. 

### Media/Files

![image](https://github.com/sboxgame/issues/assets/22033420/957d3253-a312-41ae-aae3-9d32a211b3c2)

**Comment by MaxLebled** [comment]
Water is currently being reworked, this will be addressed
