### ISSUE TITLE
Accessing the storage location from the Cache and storage tab in Options.

### ISSUE THREAD

**Issue by Dalkead** [sboxgame/issues#3943]
### For?

S&Box

### What can't you do?

Im unable to access the storage location from the Cache and storage tab in Options. I think that this is something that should be accessible easier since after only having played on 3-4 games there is already almost 2GBs of unknown data in there.

### How would you like it to work?

Simply having a button right next to "Refresh" that opens file explorer in the correct location to display all the data downloaded in storage.

### What have you tried?

I tried accessing the file location starting from my drive itself but once in the "sbox" folder, i was unsure which folder was the one being referenced in the Cache & Storage tab.

### Additional context

Overall, this might not be something actually useful or needed but personally i feel like it might be.

**Comment by handsomematt** [comment]
There's really no point in accessing that folder
