### ISSUE TITLE
Limit fps in menus and in background like in rust

### ISSUE THREAD

**Issue by realspinelle** [sboxgame/issues#3947]
### For?

S&Box

### What can't you do?

.

### How would you like it to work?

just a toggle like in rust

### What have you tried?

nothing cause i dont think i can do anything about it

### Additional context

i get more than 2k fps in menu and my gpu coil whine like hell

**Comment by Gmod4phun** [comment]
There is a `fps_max` ConVar for this very purpose

**Comment by realspinelle** [comment]
no i dont want to limit my fps but limit my fps in menu and background

**Comment by andy013** [comment]
`fps_max_inactive` works for when the game isn't the active window. I don't think there is a ConVar for limiting menu FPS though.
