### ISSUE TITLE
PhysicsJoint.Remove() does not trigger .OnBreak handlers

### ISSUE THREAD

**Issue by Nebual** [sboxgame/issues#3949]
### Describe the bug

PhysicsJoint.OnBreak says it is "Called when the joint breaks.", and it appears to be intended to cleanup side effects of the joint, such as the visual component of a rope (as [the Sandbox Rope tool does](https://github.com/Facepunch/sandbox/blob/1e5d72e6f1dd67247191b195bf9585050a45edbc/code/tools/Rope.cs#L85)).

However it is not called when removing the joint via `PhysicsJoint.Remove()`, so those side effects remain.

I also can't seem to workaround it by explicitly invoking `OnBreak()` myself.

### To Reproduce

1. Edit Facepunch/Sandbox 's [code/tools/Rope.cs](https://github.com/Facepunch/sandbox/blob/master/code/tools/Rope.cs#L85)
2. After it creates the spring constraint (eg. [Line 87](https://github.com/Facepunch/sandbox/blob/master/code/tools/Rope.cs#L87)), add `spring.Remove();` and save
3. Launch Sandbox and use the Rope tool on two props
4. Observe that, with the joint removed, there is no rope constraint behaviour, but a visual rope particle system remains, as the OnBreak's `rope?.Destroy()` was never called.

### Expected behavior

Joints should invoke their OnBreak when they're either explicitly .Remove()'d or (ideally) implicitly destroyed by any mechanism.

**Comment by Phyksar** [comment]
No, it's not meant to be called upon removal, breaking is not the same as destroying, the conditions of the breaking event are met when a `PhysicsJoint` is trying to produce more force than its specified limits:
```csharp
//
// Summary:
//     Strength of the linear constraint. If it takes any more energy than this, it'll
//     break.
public float Strength { get; set; }
//
// Summary:
//     Strength of the angular constraint. If it takes any more energy than this, it'll
//     break.
public float AngularStrength { get; set; }
```
I believe, the main purpose of `OnBreak` event is to link any effects such as sounds or particles, forcing the event invocation on remove would not be something convenient because in most cases no one would want these effects to fire when the things are cleaning up.

**Comment by Nebual** [comment]
Right, I'm hoping to cleanup the (rope) particles, amongst other things, _on .Remove()_ of the constraint, in addition to when it breaks from exceeding the Strength limit.

So maybe we need both an `OnRemove` and `OnBreak`, and then I'd define the same particle cleanup behaviour in both. Personally I struggle to imagine what I'd put in `OnBreak` that I wouldn't also put in `OnRemove`, so I'd suggest just combining them to keep the api smaller, but either's better than having these rope particles left dangling after I undo the rope.

**Comment by aylaylay** [comment]
Break and Remove should be two seperate things but I agree that we should have a function for OnRemove
