### ISSUE TITLE
asset.party is shit on mobile 

### ISSUE THREAD

**Issue by Tony322** [sboxgame/issues#3953]
### Describe the bug

As title says. Asset.party is shit on mobile. Doesn't scale property and the buttons leak way onto the sides. Not really a priority, but yeah. Try it yourselves on your phones and you will see it.

### To Reproduce

On Android or probably any phone
Go-to asset.party
See how nothing fits
??
Profit

### Expected behavior

Everything should fit. Mostly menu items seem not to be able to handle it. Maybe a burger menu is in order.

**Comment by handsomematt** [comment]
Not targeting mobile
