### ISSUE TITLE
Add CS2's new surface properties to material editor attributes

### ISSUE THREAD

**Issue by sugmagaming** [sboxgame/issues#3955]
### For?

Material Editor

### What can't you do?

There are a lot new surface properties in CS2. Ask Volvo for it.
![Screenshot 2023-09-01 142859](https://github.com/sboxgame/issues/assets/15720147/1f9c63d1-1ec1-4b7c-9c0b-eb9469b73e6f)

### How would you like it to work?

More surface properties.

### What have you tried?

Asking right now.

**Comment by bakscratch** [comment]
you can make your own easy 
![image](https://github.com/sboxgame/issues/assets/8184184/a8a8a073-2f91-459f-9bb0-7351b8de652c)
