### ISSUE TITLE
Kick Reason

### ISSUE THREAD

**Issue by AncientEntity** [sboxgame/issues#3958]
### For?

S&Box

### What can't you do?

Currently we can only kick users but we can't kick with a reason, it would be nice if we could kick with a reason, even if it was never automatically displayed by S&Box and we had to integrate it into our UI or something. Would still be nice if something was passed.

### How would you like it to work?

Client.Kick(string Reason), where Reason="No Reason Given" so it's optional.

### What have you tried?

N/A

**Comment by KingOfTheFBI** [comment]
Totally agree, we need it for ban reasons too. Right now all that can be done is stating they were kicked when they joined a server they are banned from.
