### ISSUE TITLE
Rotation.Random not sufficient for a random direction

### ISSUE THREAD

**Issue by thief** [sboxgame/issues#3959]
### Describe the bug

When using Rotation.Random, the distribution of dot products between each direction of the rotation and a given direction is not uniform.

### To Reproduce

Consider the following... The distribution of which direction had the highest dot product is not uniform.
```csharp
int[] results = new int[6];

for (int i = 0; i < 1000000; ++i )
{
      Rotation r = Rotation.Random;
      
      var dots = new[]
      {
	      Vector3.Dot( r.Up, Vector3.Up ),
	      Vector3.Dot( r.Down, Vector3.Up ),
	      Vector3.Dot( r.Left, Vector3.Up ),
	      Vector3.Dot( r.Right, Vector3.Up ),
	      Vector3.Dot( r.Forward, Vector3.Up ),
	      Vector3.Dot( r.Backward, Vector3.Up ),
      };
      
      // record which dot product was the highest
      ++results[ Array.IndexOf( dots, dots.Max() ) ];
}

Log.Info( $"{results[0]} {results[1]} {results[2]} {results[3]} {results[4]} {results[5]}" );
```

### Expected behavior

You would expect the dot products to be uniformly distributed, but in practice the forward and backward direction will appear more/less commonly (depending on which direction you're taking the dot between) disproportionally compared to other directions. This is because Rotation.Random is generating a random rotation by picking a random float [-359, 359] for the pitch, yaw, and roll.

To make the distribution uniform, you can generate a random rotation from a random quaternion instead. This is a bit slower than the current method Rotation.Random uses, but the following code is quite performant and solves the issue described ([source](https://web.archive.org/web/20211105205926/http://planning.cs.uiuc.edu/node198.html)):
```csharp
Random random = new Random();
double u = random.NextDouble();
double v = random.NextDouble();
double w = random.NextDouble();

Rotation r = new Rotation(
      (float)(Math.Sqrt( 1 - u ) * Math.Sin( 2 * Math.PI * v )),
      (float)(Math.Sqrt( 1 - u ) * Math.Cos( 2 * Math.PI * v )),
      (float)(Math.Sqrt( u ) * Math.Sin( 2 * Math.PI * w )),
      (float)(Math.Sqrt( u ) * Math.Cos( 2 * Math.PI * w )));
```

The current behavior of Rotation.Random is probably sufficient for the majority of use cases, but I believe adding a different Random method or changing the current one to include the described behavior would be beneficial. In my case, I needed to randomly rotate a 6-sided die to get a random number, but Rotation.Random favored the numbers on the forward/backward faces.

**Comment by handsomematt** [comment]
@Metapyziks has a pending change that should fix this

**Comment by Metapyziks** [comment]
Should be fixed now, thanks for reporting 👍
