### ISSUE TITLE
Website: Organization problem.

### ISSUE THREAD

**Issue by jacklollz2** [sboxgame/issues#3963]
### Describe the bug

I created an Organization back in 2021, after signing back in today, when I click on my name at the top right it says "Create Organization", rather than my organization.

When I go to my Organizations URL ( https://asset.party/rgl/ ), it says I am the owner, and I can configure its settings, however I am unable to invite members.

### To Reproduce

I think this is a me problem.

### Expected behavior

When I click on my profile, it shows my Organization, not the create button. When I want to invite someone, I am able to do so.

**Comment by DevulTj** [comment]
Please provide your asset.party profile URL - go to the top right of asset party, click your avatar, then click your name, and give me the URL there.

**Comment by jacklollz2** [comment]
https://asset.party/u/76561198032518299

**Comment by DevulTj** [comment]
Looks like you have archived your organization:
![msedge_iGAO2KA0gw](https://github.com/sboxgame/issues/assets/22372616/ec82dfdd-32c1-47b2-89b5-c2c8bef557dd)

**Comment by jacklollz2** [comment]
I haven't done this myself. How would I unarchive it?

**Comment by DevulTj** [comment]
https://asset.party/rgl/~edit

**Comment by jacklollz2** [comment]
I don't see a place to unarchive, is that in the Danger zone?
