### ISSUE TITLE
Can't select any model in Asset Spray tool.

### ISSUE THREAD

**Issue by FullStack0verfl0w** [sboxgame/issues#3966]
### Describe the bug

I'm unable to select any model in Asset Spray tool.
Loading a preset works fine.

### To Reproduce

1. Go to Asset Spray tool.
2. Try to select a model.

### Expected behavior

It should add a model.

### Additional context

Dragging a model from Asset Browser also doesn't work.

**Comment by handsomematt** [comment]
Should be fixed
