### ISSUE TITLE
s&box dev launcher forgets projects if on recently disconnected external drive

### ISSUE THREAD

**Issue by e1m1j** [sboxgame/issues#3970]
### Describe the bug

When you store your .sbproj files on an external drive, and the drive is for some reason disconnected (happens occasionally to me automatically on my Windows setup) s&box fails to redetect these projects. This means s&box launches without these projects loaded, if your SSD has been disconnected and reconnected at some point between s&box launches.

The issue is, if you have multiple projects, it becomes tedious and time-consuming to re-add every single project. I've had to have done this at least 5 times now.

### To Reproduce

1) Store your .sbjproj files on an external SSD/HDD.
2) Load them into s&box.
3) Close s&box.
4) Remove your external drive, and launch.
5) Naturally, projects will not appear.
6) Close s&box again.
7) Reconnect SSD/HDD with projects.
8) Relaunch s&box.
9) Projects cannot be found.

### Expected behavior

s&box should ideally scan for missing projects on historic drives or last known locations.

**Comment by the-remeko** [comment]
I keep my projects on a flash drive, and it is super annoying when I forget to plug it in before starting s&box.

**Comment by handsomematt** [comment]
I can see how this would be annoying, we're clearing any unfound addons because it's assumed you've deleted them from explorer and wouldn't want them hanging around. We'll have to think of something.
