### ISSUE TITLE
Error calling event 'camera.post' on 'ViewModel' - Gunpoint

### ISSUE THREAD

**Issue by CyberStudioUnited** [sboxgame/issues#3973]
### Describe the bug

When you look straight up or down the game glitches and the viewmodel detaches from the camera.

### To Reproduce

1. Go into a gunpoint match.
2. Look up or down.
3. It breaks

### Expected behavior

It shouldn't detach.

### Media/Files

![20230905011944_1](https://github.com/sboxgame/issues/assets/72953518/830c798b-6176-489a-a73e-f517b09303e7)
![20230905011948_1](https://github.com/sboxgame/issues/assets/72953518/b007a6f0-9bb0-41aa-9ef3-eeffa33550f6)

**Comment by handsomematt** [comment]
Not for gamemode issues
