### ISSUE TITLE
point_worldtext does not show text 

### ISSUE THREAD

**Issue by KingOfTheFBI** [sboxgame/issues#3975]
### Describe the bug

point_worldtext still works but doesn't show any text

### To Reproduce

1. Make the entity
2. Type something in it

### Expected behavior

the text should show

**Comment by handsomematt** [comment]
is this a recent issue? do you mean only in editor or in game or both?

**Comment by KingOfTheFBI** [comment]
> is this a recent issue? do you mean only in editor or in game or both?

Sorry, let me clarify, when you type it in in hammer it doesn't show you what is typed, the hint is broken, it will show up in game though. But you need to see it as a helper in the editor

**Comment by handsomematt** [comment]
Looks like the native code for rendering the entity in Hammer got deleted... so I've now made it use the same text renderer as the game so its equal and custom fonts etc work..

![image](https://github.com/sboxgame/issues/assets/1388267/3df0947f-4aa6-40f2-a5f2-d800f36bdfb4)

Let me know if there's anything wrong.

**Comment by QuackCola** [comment]
> Looks like the native code for rendering the entity in Hammer got deleted.. which is good as I've now made it use the same text renderer as the game so its equal and custom fonts etc work
> 
> ![image](https://user-images.githubusercontent.com/1388267/265864144-3df0947f-4aa6-40f2-a5f2-d800f36bdfb4.png)
> 
> Let me know if there's anything wrong.

Seems like in hammer the rendered text is no long using the assigned color . the ingame color however still appears correctly.
![Screenshot 2023-09-06 011226](https://github.com/sboxgame/issues/assets/23345567/3c817229-0f87-4fb9-b59b-c2b87929feef)

**Comment by handsomematt** [comment]
Tghere we go

**Comment by QuackCola** [comment]
now the text dosent show up at all 🤔 
![Screenshot 2023-09-06 183412](https://github.com/sboxgame/issues/assets/23345567/d04491b7-4894-4691-a05c-c1df10c0950a)
