### ISSUE TITLE
Remove the VPN/Proxy restriction

### ISSUE THREAD

**Issue by oniongithub** [sboxgame/issues#3979]
### For?

S&Box

### What can't you do?

I cannot load S&Box without turning my VPN off or split tunneling S&Box.

### How would you like it to work?

I get the reason VPNs are blocked is probably to stop alting and bypassing bans, but having to turn your internet condom off and hand your IP over to someone who popped an IP logger into an addon isn't very cash money. People can just buy rotating residential proxies and bypass the restriction, so it's just more of a nuisance to people who don't wanna have an 11-year-old putting their IP into a GeoIP lookup and saying their town and IP in chat when they are mad.

### What have you tried?

MullVad #1

**Comment by chrisspieler** [comment]
I haven't had any problems playing S&box on Private Internet Access, so the issue probably only occurs with some VPNs.

**Comment by handsomematt** [comment]
Use a VPN not blocked by Cloudflare

**Comment by VIEWVIEWVIEW** [comment]
> Use a VPN not blocked by Cloudflare

Cloudflare does not "block" VPNs. Cloudflare merely applies the rules you set. It's a config issue on your side.
Would be great if you could allow all IPs from ASN3320 (which has nothing to do with VPNs btw)
