### ISSUE TITLE
Easy way to find what map we're loading into in a loading screen

### ISSUE THREAD

**Issue by Xenthio** [sboxgame/issues#3980]
### What it is?

The loading screen already knows what we're loading into before anything we can fetch in code can tell us (Game,Server.MapIdent).

It would be neat to have a way to fetch what we're currently loading into from the loading screen as soon as possible

### What should it be?

Game.Menu.LoadingMap or something would be very handy to have

**Comment by DevulTj** [comment]
You should notice that some Game.Server fields will be populated when running Game.Menu.StartServerAsync() now, namely `MapIdent`, `MaxPlayers`, `ServerTitle`, `GameIdent` and `GameTitle`. Please let me know if this is working for you.

**Comment by Xenthio** [comment]
Haven't tested it yet, but do you think some of the fields could be populated when connecting to a sever too?

**Comment by DevulTj** [comment]
Doesn't seem really worth having a whole response in managed from native imo since it'll all get shelved with the meld project
