### ISSUE TITLE
Viewmodel bones and attachments no longer respect Viewmodel FOV  

### ISSUE THREAD

**Issue by Xenthio** [sboxgame/issues#3981]
### Describe the bug

Fetching viewmodel bones and attachments no longer respects the viewmodel fov causing all attachment positions to be offset
![image](https://github.com/sboxgame/issues/assets/28588188/a5099fe1-5289-4102-af05-5059bd52e106)

### To Reproduce

1. create viewmodel
2. set viewmodel fov to something that isnt the normal fov
3. fetch an attachement (ViewModelEntity.GetAttachment( "muzzle", true );)
4. see attachment is offset

### Expected behavior

previously fetching attachments on a viewmodel were corrected to match the fov of the viewmodel

**Comment by garrynewman** [comment]
Should be fixed in next build - please let me know

**Comment by Xenthio** [comment]
> Should be fixed in next build - please let me know

seems to be fixed! thank you so much!
