### ISSUE TITLE
Physics Debug no longer display

### ISSUE THREAD

**Issue by yuberee** [sboxgame/issues#3983]
### Describe the bug

Selecting any physics debug overlay doesn't show anything

### To Reproduce

1. Open a game with physics
2. Select any physics debug overlay

### Expected behavior

n/a

### Media/Files

![image](https://github.com/sboxgame/issues/assets/59583743/e739ea6e-8f27-49f0-9933-b91543e06740)

**Comment by garrynewman** [comment]
Should be fixed in next build

**Comment by yuberee** [comment]
Works now, thank you all for supporting me in this journey.
