### ISSUE TITLE
Cameras when looking almost directly up or down snap their pitch to either 90 or -90 degrees

### ISSUE THREAD

**Issue by Xenthio** [sboxgame/issues#3984]
### Describe the bug

Cameras have this weird snapping behaviour, where if the pitch of a camera is almost 90 degrees, it'll snap it to the nearest 90.

### To Reproduce

Go to any game,
look directly up or down
you can see the snap

### Expected behavior

Camera shouldn't do this

### Media/Files

https://github.com/sboxgame/issues/assets/28588188/0e6c1bd2-a73c-4caf-8045-c027094345ca

**Comment by garrynewman** [comment]
Could this be the Angles() fix @Metapyziks?

**Comment by Metapyziks** [comment]
Yep my bad, on it now
