### ISSUE TITLE
Camera.Size is not set to the correct size

### ISSUE THREAD

**Issue by kolexxx** [sboxgame/issues#3987]
### Describe the bug

`Camera.Size` is not set to the correct size, resulting in `Camera.Main.GetRay()` giving bad results.

### To Reproduce

When the game loads, `Camera.Main.Size` should be `512, 512`.

### Expected behavior

`Camera.Size` should return the correct size.

**Comment by handsomematt** [comment]
Why should it be 512, 512?

**Comment by kolexxx** [comment]
It shouldn't, it's just automatically set to it for some reason.

**Comment by garrynewman** [comment]
Should be fixed now - let me know
