### ISSUE TITLE
Cannot join dedicated servers

### ISSUE THREAD

**Issue by sphaxa** [sboxgame/issues#3988]
### Describe the bug

An issue was recently fixed to prevent Dedicated Servers from crashing (https://commits.facepunch.com/457038)

However, while the servers load just fine, when a client connects they are disconnected right at the end of the loading process, and this NRE is spammed on the client.

`2023/09/07 09:07:13.8604    Interop    Object reference not set to an instance of an object.    System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.ClientDll.OnRender()
   at Sandbox.EngineLoop.OnClientOutput()
   at Managed.SandboxEngine.Exports.Sandbox_EngineLoop_OnClientOutput()`
   
   This has been tested on TTT and S&Tycoon Dedicated Servers on the latest version of s&box.
   
   Listen servers appear to still work just fine.

### To Reproduce

1. Attempt to join dedicated server.
2. Observe disconnect and NRE spam.

### Expected behavior

Not be instantly disconnected from dedicated servers.

**Comment by Kolya142** [comment]
i only know: this for any server

**Comment by Oneleg3** [comment]
Happens with hosted lobbies as well now, not just dedicated servers. 

Error spams in console while player is brought back to the server browser. In-game sounds can be heard, but the server browser UI is stuck on-screen with no functionality/intractability

**Comment by MrBrax** [comment]
Clients are getting "FileRecv isn't null" error spammed in console for me, but at least connecting seems to work now.

**Comment by sphaxa** [comment]
> Clients are getting "FileRecv isn't null" error spammed in console for me, but at least connecting seems to work now.

Have not noticed this, may be a different Issue so I will let you decide if you need to make a new one for that.

Otherwise, this appears to be resolved.
