### ISSUE TITLE
Camera auto exposure doesn't work

### ISSUE THREAD

**Issue by Xenthio** [sboxgame/issues#3989]
### Describe the bug

maps are suddenly much more darker than before
it seems that auto exposure is broken
![image](https://github.com/sboxgame/issues/assets/28588188/99c26d53-2a05-41ff-8aa1-f42a86a65fc7)

### To Reproduce

1. Load up a map with a dark and bright area.

### Expected behavior

cameras should adjust the exposure when in dark areas
it should look like this
![image](https://github.com/sboxgame/issues/assets/28588188/a72f98fc-5398-4762-823e-d9f9b6a4a6a3)

**Comment by Xenthio** [comment]
wait hold on this issue might be invalid other people are reporting it working

**Comment by Xenthio** [comment]
I found I can very easily set `Camera.Main.Tonemap.Enabled = true;` to fix it, is it being disabled just the new default or something?

**Comment by aylaylay** [comment]
Should be enabled by default now

**Comment by garrynewman** [comment]
You know, in `EnginePostProcess.ActivePostProcessEntity` should we really be setting the variables on the Camera.Main instead? That way it'll only get enabled if it's meant to, and the accessor will be ground truth

**Comment by aylaylay** [comment]
Tonemap params from ActivePostProcessEntity now get copied to scene cameras

**Comment by KingOfTheFBI** [comment]
I still get it
