### ISSUE TITLE
Allow the possibility to ignore missing css properties

### ISSUE THREAD

**Issue by bub-bl** [sboxgame/issues#3997]
### For?

S&Box

### What can't you do?

I try to use some libraries like Tailwind, but this is not possible. Tailwind add some default properties/selectors in the compiled.css file and this properties does not exists in S&box and that trigger an compilation error.

### How would you like it to work?

 Add a way to disable missing properties error in css file

### What have you tried?

Use Tailwind in hud

**Comment by handsomematt** [comment]
Would be bad
