### ISSUE TITLE
Water you doing

### ISSUE THREAD

**Issue by rodlopt** [sboxgame/issues#4000]
### Describe the bug

Sandbox code shugs re-write it

### To Reproduce

1. Box-shooter
2. Aim at water
3. Click r
4. Shoot
5. Chaos

### Expected behavior

The 3d skybox shouldn't fuck up? 

### Media/Files

https://github.com/sboxgame/issues/assets/142238897/0de2806b-7332-487d-9d56-ebcb25b15405

### Additional context

I also did respawn_entities so maybe that's why

**Comment by dinga989** [comment]
gosh fp, WATER you doing!?!?!?

**Comment by handsomematt** [comment]
You were duplicating the water model with the box shooter, I've made that impossible now.

I can't recreate the issue with the skybox, but if it occurs again please make an issue with some recreation steps.

**Comment by trende2001** [comment]
> You were duplicating the water model with the box shooter, I've made that impossible now.
> 
> I can't recreate the issue with the skybox, but if it occurs again please make an issue with some recreation steps.

The skybox being removed and re-created is from Game.ResetMap, it doesn't have the sky_camera in its filters by default

**Comment by handsomematt** [comment]
I ran respawn_entities and nothing happened, the sky entities get remade with the exact same values.

**Comment by trende2001** [comment]
> I ran respawn_entities and nothing happened, the sky entities get remade with the exact same values.

I think it's a matter of how many times it's done, then it starts creating duped sky_cameras and the console starts logging "Multiple sky_camera?"
