### ISSUE TITLE
SoundEventEntity.PlayingSound doesn't get set with given sound.

### ISSUE THREAD

**Issue by GrandpaTroll** [sboxgame/issues#4002]
### Describe the bug

SoundEventEntity.PlayingSound is null no matter what sound file you give it to play.

### To Reproduce

Just Create any sound with SoundEventEntity and no matter what sound you choose, The variable PlayingSound will be null.

### Expected behavior

SoundEventEntity.PlayingSound should be the given sound that PlaySound creates.

**Comment by handsomematt** [comment]
Entity deleted
