### ISSUE TITLE
other player's playermodel gets screwed up on low spec PC's

### ISSUE THREAD

**Issue by gingusScringus** [sboxgame/issues#4004]
### Describe the bug

i was trying to play s&box using my alt account on my old HP TS14 Notebook with an NVIDIA Geforce GT 740M and an Intel i5 4200U. it's literally in an unplayable state. i created a 2 player server just to test my old laptop, but the FPS was so bad that; when i try to get in to my alt account's view. i noticed my character was glitching out on the old laptop, although my character in my main PC looks fine.

### To Reproduce

1. create and run a server
2. join the server as the alt account on the low spec PC
3. get in the alt's view and witness it yourself

### Expected behavior

obviously, the character should've looked normal no matter the framerate. just like most games

### Media/Files

old laptop screenshots:
![20230911165958_1](https://github.com/sboxgame/issues/assets/67906219/c544b6a5-d1a7-4537-8a07-fb6549aa9eea)
![20230911170118_1](https://github.com/sboxgame/issues/assets/67906219/756361dd-b34f-4d1a-80aa-c24e72a326d7)
![20230911170123_1](https://github.com/sboxgame/issues/assets/67906219/006bebbf-9c2d-4c7c-baa6-3e2bbf04ffb7)
![20230911170134_1](https://github.com/sboxgame/issues/assets/67906219/b06d31f9-2849-4189-879c-cfab75aea725)

### Additional context

# my old laptop specs
 HP Pavilion TouchSmart 14-n049tx Notebook PC
- Intel Core i5 4200U
- NVIDIA GeForce GT 740M
- 16GB DDR3 RAM
- Windows 10 Home

**Comment by MrBrax** [comment]
curious, how do you even play the game at all with only 2gb vram? it turns all my textures into 8x8 and spams the console with out of vram errors

**Comment by gildas64** [comment]
> curious, how do you even play the game at all with only 2gb vram? it turns all my textures into 8x8 and spams the console with out of vram errors

not sure about that. and if you could even call it playable, the old laptop plays about idk 2-5 fps (i don't have an fps counter installed on the old laptop so this is just my approximation). or maybe it has something to do with the OS or the old laptop's GPU is a bit newer than yours?

**Comment by MrBrax** [comment]
> > curious, how do you even play the game at all with only 2gb vram? it turns all my textures into 8x8 and spams the console with out of vram errors
> 
> not sure about that. and if you could even call it playable, the old laptop plays about idk 2-5 fps (i don't have an fps counter installed on the old laptop so this is just my approximation). or maybe it has something to do with the OS or the old laptop's GPU is a bit newer than yours?

my other pc with the worse gpu is a gtx 770 with 2gb vram and i'd call that below what's required for this game

**Comment by DrewBritt** [comment]
If you don't meet [minimum specs](https://wiki.facepunch.com/sbox/System_Requirements) I'm not sure what you think can be done for you.

**Comment by MrBrax** [comment]
definitely going to alienate *a lot* of people with the minimum specs, will be interesting to follow

**Comment by handsomematt** [comment]
we'll get right on supporting 10+ year old hardware

**Comment by MrBrax** [comment]
even with my 1070 it's barely hitting 60 fps in a lot of spots, and buying a new low to mid tier gpu for 800€ just isn't my thing. but i digress, too offtopic.
