### ISSUE TITLE
the images in razor stopped resizing with the size at 100%

### ISSUE THREAD

**Issue by dictateurfou** [sboxgame/issues#4006]
### Describe the bug

In recent days my panel razors using images have broken. Usually I set width and height to 100% but this one no longer has any effect.

before I could do its "height:100%; width:100%"
 but now I have to do for have 100% div resize
 
```css
background-size: contain;
background-position: center;
background-repeat: no-repeat;
position: absolute;
left: 1px;
right: 1px;
top: 1px;
bottom: 1px;
```

### To Reproduce

add image with more resolution of you div
exemple if you have 500px image try to show in razor panel with 100px
and add height and width at 100% on you image

### Expected behavior

100% should work

### Media/Files

before break:
![a3ca09e82327d6c5fb7e3c78f1f928a4](https://github.com/sboxgame/issues/assets/12927420/8b7adf07-26c5-4790-a547-70a9e5a7c8aa)

after break:
![3f3d18bae51726dc0f4b3d9e860fffcd](https://github.com/sboxgame/issues/assets/12927420/0c683001-027a-4323-b2d1-22f452fa8dd2)

**Comment by xezno** [comment]
Should be fixed next build
