### ISSUE TITLE
Wrong math in VelocityClipPlanes (used by MoveHelper)

### ISSUE THREAD

**Issue by AltimorTASDK** [sboxgame/issues#4007]
### Describe the bug

`VelocityClipPlanes.TryAdd` erroneously multiplies velocity by the magnitude of the 2-plane cross product when trying to slide along the crease.

```c#
			// Hit the floor and the wall, go along the join
			if ( Count == 2 )
			{
				var dir = Vector3.Cross( Planes[0], Planes[1] );
				velocity = dir.Normal * dir.Dot( velocity );
			}
```

The unnormalized cross product is used to calculate the dot product. This bug isn't present in Source's `CGameMovement::TryPlayerMove`:

```c++
				CrossProduct (planes[0], planes[1], dir);
				dir.NormalizeInPlace();
				d = dir.Dot(mv->m_vecVelocity);
				VectorScale (dir, d, mv->m_vecVelocity );
```

### To Reproduce

Collide with two surfaces at an acute angle in one tick. Your velocity in the perpendicular axis will be reduced.

### Expected behavior

Your velocity in the perpendicular axis should be preserved.

**Comment by aylaylay** [comment]
You're right, good catch

**Comment by AltimorTASDK** [comment]
The effects of this are actually caused by #4010. This bug is there, but will currently never be hit.
