### ISSUE TITLE
Option for playing a sound when game is not focused

### ISSUE THREAD

**Issue by thief** [sboxgame/issues#4014]
### For?

S&Box

### What can't you do?

I can't force the player hear a sound when s&box isn't focused.

### How would you like it to work?

Add a property to [Sound](https://asset.party/api/Sandbox.Sound) that can be enabled for playing a sound even if s&box is not focused. Would be nice for notification-esque sounds (e.g. CSGO queue sound)

### What have you tried?

Playing a sound and tabbing out.

**Comment by andy013** [comment]
Could you toggle `snd_mute_losefocus`?

**Comment by thief** [comment]
> Could you toggle `snd_mute_losefocus`?

Works, but ideally you could configure specific sounds to be heard without focus.

**Comment by handsomematt** [comment]
Fuck this
