### ISSUE TITLE
[asset.party] Secure Connection Failed: SSL_ERROR_NO_CYPHER_OVERLAP

### ISSUE THREAD

**Issue by Jammie3d** [sboxgame/issues#4015]
### Describe the bug

When visiting asset.party I get the following error:

> Secure Connection Failed
> 
> An error occurred during a connection to asset.party. Cannot communicate securely with peer: no common encryption algorithm(s).
> 
> Error code: SSL_ERROR_NO_CYPHER_OVERLAP
> 
> - The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
> - Please contact the web site owners to inform them of this problem.

https://gmod2.com/ works in the meantime, and I'm still able to upload to asset.party from s&box.

### To Reproduce

Go to https://asset.party/
See Problem loading page

### Expected behavior

No Problem loading page

### Additional context

Happens on Firefox and Edge, Windows 11, ISP is BT, DNS is automatic.

**Comment by handsomematt** [comment]
https://www.blocked.org.uk/site/https://asset.party/

We've requested to be unblocked, you can fix this in the mean time by turning off BT Web Protect or using alternative DNS servers.

**Comment by MrBrax** [comment]
>there is no content that is deemed 18+ nor is it allowed on our platform

current most popular game on the front page is boob clicker

**Comment by Pollux12** [comment]
Cloudflare thinks it is a phishing site which is likely why it is being blocked: https://radar.cloudflare.com/domains/feedback/asset.party

![image](https://github.com/sboxgame/issues/assets/39353174/161df445-6abe-4818-a119-0019efe6e7f6)
