### ISSUE TITLE
VR.Anchor seems broken, isn't moving the camera correctly

### ISSUE THREAD

**Issue by Nebual** [sboxgame/issues#4018]
### Describe the bug

Changing `VR.Anchor` no longer seems to move the camera correctly - I'm guessing it may have been broken by the OOG Rendering commit that merged Sept 6th. I'm not confident on details as I only recently started looking at VR in sbox and so haven't seen `VR.Anchor` working previously, but the only published VR game I could find that worked was Note Beater, which intentionally leaves `VR.Anchor` at 0,0,0, and thus seems immune to the bug. 

https://asset.party/shadb/bulletwave does not work: the camera shows a black void with a few broken lights, presumably rendering outside of the intended level bounds.

In my efforts to have `VR.Anchor` follow the player pawn around in Sandbox (trying in PostCamera, Frame, and BuildInput), the camera instead rendered very close to 0,0,0, moving very slightly as the VR.Anchor was moved across the entire map, like it was operating at a ~1/100th coordinate scale (though I was not able to workaround it by changing `VR.Scale`). Changing `VR.Anchor.Rotation` did nothing I could see.

### To Reproduce

1. Open https://asset.party/shadb/bulletwave in VR
2. Observe the camera is not anywhere useful, but instead is rendering outside of the level in blackness

### Expected behavior

`VR.Anchor` should "sets where the center of the VR play area is in world space", including (if I understand right) the camera's origin

### Additional context

I'm using an HTC Vive. I saw the same results in my own gamemode testing in `-vr -tools`, and via "Launch s&box in Steam VR Mode". The editor's flatscreen view showed an equivalently 0,0,0'd view (so you don't have to actually put on a headset to repro)

**Comment by xezno** [comment]
Should be fixed now, setting VR.Anchor should apply to the headset, controller, and all other tracked devices
