### ISSUE TITLE
[UI] Rotated/translated UI elements behaviour changed after a recent update

### ISSUE THREAD

**Issue by Gmod4phun** [sboxgame/issues#4027]
### Describe the bug

After a recent update, some parts of my UI broke because of (I assume) changes to the behaviour of transform: rotate/translate and how stuff is positioned relative to its parent when transformed. I am unsure if this was an intentional change or an oversight, so I dont know if I should adjust my code or if this gets reverted.

It worked fine on 10th of September, and I first noticed it was broken on the 15th.

Before:
![image](https://github.com/sboxgame/issues/assets/5991682/23e4268b-a9b2-4ef4-b3ca-eb452cbbdebe)

After:
![image](https://github.com/sboxgame/issues/assets/5991682/d640123d-d921-483c-87bc-e436bbd35ef8)

### To Reproduce

I don't know, have rotating elements that are also translated :P

### Expected behavior

Behaviour prior to one of the updates that changed it.

**Comment by Gmod4phun** [comment]
Just noticed another part of my thing is broken. The gradient bars are a static image, with a black rectangle on top of them that slowly changes its height in order to simulate the gradient bar growing. Before, it worked as intended, now the black rectangles covering the gradients change their size relative to its center.

Before:
![image](https://github.com/sboxgame/issues/assets/5991682/88bc9da2-3346-4439-9f1c-910e603f9cc2)

After:
![image](https://github.com/sboxgame/issues/assets/5991682/2a09ea80-a4ee-41ec-889e-c243d35edf18)

**Comment by xezno** [comment]
Do you have any code so that I can repro this

**Comment by Gmod4phun** [comment]
I will try to have one for you soon.

**Comment by Gmod4phun** [comment]
Here's a simple repro game (load any map, left click to spawn the panel. Transform-origin doesnt do anything

[transformoriginrepro.zip](https://github.com/sboxgame/issues/files/12688634/transformoriginrepro.zip)

**Comment by xezno** [comment]
Thanks, should be fixed on next build

**Comment by Gmod4phun** [comment]
Thank you very much, it is working again. There is one more problem though, but I am not sure if it was like that before the update, too.
Setting the origin with numeric values (`0 0` for top left, `50% 50%` for center) works, but using the keywords like `center`, `bottom`, `top right` do nothing.

**Comment by xezno** [comment]
Looking into it

**Comment by Gmod4phun** [comment]
Yep, seems to be the case. Thanks once again :)
