### ISSUE TITLE
Recording a video on a fresh install crashes the game

### ISSUE THREAD

**Issue by trundlr** [sboxgame/issues#4032]
### Describe the bug

When recording a video on a fresh install (no screenshots folder), the game will crash.

```
2023/09/17 16:26:12.5706	engine/Engine	Error occurred when opening AVIO	
2023/09/17 16:26:12.9230	engine/Movie	Video finished.	
```

Taking a screenshot will create the screenshots folder as expected, but the video recording will instantly crash the game.

### To Reproduce

1. Fresh install or delete screenshots folder
2. Take a recording with F6
3. Finish recording with F6
4. Game crash

### Expected behavior

Game does not crash

**Comment by aylaylay** [comment]
Should be fixed now

**Comment by trundlr** [comment]
Oh God Bless you, happy day!
