### ISSUE TITLE
`Sandbox.Hitbox.GetName()` return <invalid>

### ISSUE THREAD

**Issue by PolSpock** [sboxgame/issues#4036]
### Describe the bug

Hi,

If you try to use [Sandbox.Hitbox.GetName()](https://asset.party/api/Sandbox.Hitbox.GetName()), you will never grab the name of the hitbox hit by a Trace.
You always get `<invalid>` instead

Is problematic if you want to do some debugging of the hitbox for your player model

### To Reproduce

1) Download [sandbox](https://github.com/Facepunch/sandbox) game (to be sure you playing with Terry models/citizen/citizen.vmdl)
2) Edit the `Player.cs` `TakeDamage` function :
Add something like this :
```
public override void TakeDamage( DamageInfo info )
{
	Log.Info( info.Hitbox.GetName() );
	if ( info.Hitbox.HasTag("head")) // Just be sure your trace uses UseHitboxes()
	{
		Log.Info( "Headshot" );
	}
	// [...] trunc
	base.TakeDamage( info );
}
```
3) Start a sandbox game, spawn a bot, and shoot him: you will get an `<invalid>` for `info.Hitbox.GetName()` but you will get "Headshot" printed if you shoot in the head.

PS : I also tried to add these lines in the Respawn() function but the error is still present
```
EnableHitboxes = true;
SurroundingBoundsMode = SurroundingBoundsType.Hitboxes;
```

### Expected behavior

The documentation says "Grab the name of the hitbox, please note that internally we store this as a string token, so using this frequently is ill advised." but invalid is not the correct name of the hitbox 🤓

**Comment by DevulTj** [comment]
Repro'd - This happens if native fails to grab the string token's original string. Will look into it

**Comment by DevulTj** [comment]
This struct doesn't exist anymore
