### ISSUE TITLE
`ITagSet` Should Implement `ICollection<string>`

### ISSUE THREAD

**Issue by LeQuackers** [sboxgame/issues#4037]
### What it is?

Tags and `ITagSet` have methods that are functionally equivalent to those from `ICollection<string>`, but don't use the `ICollection<string>` interface, e.g.:

|`ICollection<string>`|`ITagSet`|
|-|-|
|[`Add(string)`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.icollection-1.add?view=net-7.0)|[`Add(string)`](https://asset.party/api/Sandbox.ITagSet.Add(string))|
|[`Contains(string)`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.icollection-1.contains?view=net-7.0)|[`Has(string)`](https://asset.party/api/Sandbox.ITagSet.Has(string))|
|[`Remove(string)`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.icollection-1.remove?view=net-7.0)|[`Remove(string)`](https://asset.party/api/Sandbox.ITagSet.Remove(string))|
|[`Clear()`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.icollection-1.clear?view=net-7.0)|[`RemoveAll()`](https://asset.party/api/Sandbox.ITagSet.RemoveAll())|
|[`GetEnumerator()`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.ienumerable.getenumerator?view=net-7.0)|[`TryGetAll()`](https://asset.party/api/Sandbox.ITagSet.TryGetAll()) *|
|[`Count`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.icollection-1.count?view=net-7.0)| Not Implemented|
[`CopyTo(string[], Int32)`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.icollection-1.copyto?view=net-7.0)|Not Implemented|

\* [`ITagSet.TryGetAll()`](https://asset.party/api/Sandbox.ITagSet.TryGetAll()) is clunky and it doesn't fit the normal "Try" pattern because it doesn't return a `bool` or have an out parameter; it'd be way more concise just to pass the `ITagSet` instead of calling an extra method everywhere. On top of that, if it implemented the normal `GetEnumerator()` method it would allow `ITagSet` to use `IEnumerable<string>` extension methods.

### What should it be?

`ITagSet` should implement `ICollection<string>`; most of the methods are already there, they just have different names.

**Comment by DevulTj** [comment]
I really don't think this is something that needs a big discussion, this interface might cease to exist as it's only used in bleeding edge systems that are in flux.

I'd suggest making a utility method that handles this in your own project.
