### ISSUE TITLE
sbox-server network protocol is older than client network protocol

### ISSUE THREAD

**Issue by Vulp-OS** [sboxgame/issues#4043]
### Describe the bug

sbox-server installed via SteamCMD (ID:1892930 - steam change list 20345805) is incompatible with the later versions of S&Box Client (ID:590830 - steam change list 20362761 and newer) that were released this morning (9/20/2023). It is possible to use `connect IP_ADDRESS` to connect to a server running from the Steam Client install directory, but when the same is attempted with an instance of sbox-server running from the SteamCMD version, the session fails with `NETWORK_DISCONNECT_REJECT_OLDPROTOCOL`

```
> connect 127.0.0.1
Opened Steam Net Connection on socket 'client' to 127.0.0.1:27015, connection #124233263 UDP invalid@127.0.0.1:27015
Sending connect to 127.0.0.1:27015
Received S2C_CHALLENGE [2405033151 auth 3] from 127.0.0.1:27015
Sending C2S_CONNECT [1011 protocol 2405033151 auth 3] to 127.0.0.1:27015
CL:  Server disconnected: 141: NETWORK_DISCONNECT_REJECT_OLDPROTOCOL
Discarding pending request 'Remote Connect (127.0.0.1), 4'
```

I believe this was caused when [#34e27d](https://commits.facepunch.com/459701) was pushed and made available to clients at around 9:00a Mountain Time on 9/20/2023. The steam client was updated, but sbox-server was not. 

### To Reproduce

1. Install sbox-server with ID 1892930 using SteamCMD
2. start a server running any +gamemode
3. Notice that the server does not appear in the S&Box Client Server list and cannot be connected to via the console command `connect IP_ADDRESS`

### Expected behavior

sbox-server should have new builds produced when core stacks are updated, such as networking. If that were to happen, the above bug would not have occurred and all the servers running off ID:1892930 would not have dropped from the server list for clients that received the core stack updates.

`connect IP_ADDRESS` should succeed with output like the following:
```
Opened Steam Net Connection on socket 'client' to 127.0.0.1:27015, connection #331793406 UDP invalid@127.0.0.1:27015
Sending connect to 127.0.0.1:27015
Received S2C_CHALLENGE [2235535073 auth 3] from 127.0.0.1:27015
Sending C2S_CONNECT [1011 protocol 2235535073 auth 3] to 127.0.0.1:27015
Received S2C_CONNECTION from 127.0.0.1:27015 [addons:'']
CL:  Suppress INetchannel::Transmit() in loopmode( remoteconnect )
CL:  CLoopModeRemoteConnect::OnClientFrameSimulate switching to "levelload" loopmode with addons:  
CL:  Permit INetchannel::Transmit()
```

### Additional context

This is kind of a procedural bug rather than an actual bug with the game, as it was caused by the update of core components of the game that were not reflected on the server

**Comment by Oneleg3** [comment]
Also experiencing this problem, dedicated servers do not work currently.

**Comment by handsomematt** [comment]
We had issues with Steam not accepting our uploads for the server.
