### ISSUE TITLE
border-image is unaffected by image-rendering setting

### ISSUE THREAD

**Issue by Fortune117** [sboxgame/issues#4054]
### Describe the bug

Adding a border image to a panel is really blurry and I can't change the filter the same way I can for the background image:
![image](https://github.com/sboxgame/issues/assets/7847372/02076ba8-d0a3-4f5a-9a77-5c877cd6d410)

Setting `image-rendering` to `pixelated` doesn't affect the border.

### To Reproduce

1. Add a border image to a panel
2. Can't change how it's rendered

### Expected behavior

Should be able to adjust this like you can with the background image. Could either make it use the same setting as the background image or give it its own setting, such as `border-image-rendering`

**Comment by xezno** [comment]
Will follow `image-rendering` property because otherwise I think the shader would become too slow or complex - but I might add a separate property when I get around to reworking borders.
