### ISSUE TITLE
Wont compile lighting after subdividing a 50k mesh in hammer to displace and paint on it.

### ISSUE THREAD

**Issue by sugmagaming** [sboxgame/issues#4055]
### Describe the bug

![AnyDesk_GZi0wjoDic](https://github.com/sboxgame/issues/assets/15720147/cd59ff46-ac37-43ff-9bb6-d0ff71032292)
I subdivided a model of terrain that is 50,000 faces and painted on it and displaced it. Now it wfails when doing light importance tree. When i delete the ground the map compiles.
![image (2)](https://github.com/sboxgame/issues/assets/15720147/f6303833-006f-4fb0-ab74-25f8e93e5249)

### To Reproduce

I guess try subdividing a high poly mesh in hammer, displacing, and painting it and compiling lighting.

### Expected behavior

Should work.

**Comment by rodlopt** [comment]
Have you tried like separating the terrain?

**Comment by KayaDLX** [comment]
have u considered not doing that

**Comment by sugmagaming** [comment]
![sbox-dev_OpvlGyrdyC](https://github.com/sboxgame/issues/assets/15720147/0c81546e-bae4-4321-80d8-27e6145c233d)

**Comment by sugmagaming** [comment]
it goes farther on my computer than on the server

**Comment by handsomematt** [comment]
This isn't reasonable to expect to work.
