### ISSUE TITLE
Restarting the game doesn't overwrite old Console Commands

### ISSUE THREAD

**Issue by andy013** [sboxgame/issues#4063]
### Describe the bug

 ![image](https://github.com/sboxgame/issues/assets/10728824/98365ba4-954e-4d94-b724-a264a38a743b)
If you restart a launch config using the buttons in the top left of the game window then console commands aren't properly overwritten. This error will appear in console:

`"Console command or convar is being ignored because it conflicts with a convar with the same name"` 

Any changes you make to the new command will not be used by the game. 

### To Reproduce

1. Create a ConCmd.
2. Load into the game.
3. Restart the game using the launch config buttons.
4. See the error in console

### Expected behavior

Console Commands should hotload correctly overwriting old versions.

**Comment by MrBrax** [comment]
yup, concommands totally break now with big spam on hotload listing all the concommands in my project

**Comment by andy013** [comment]
Fixed on current staging branch.
