### ISSUE TITLE
black square in center of screen

### ISSUE THREAD

**Issue by gwiddypwofessional** [sboxgame/issues#4070]
### Describe the bug

black square in center of screen when tabbed into game after a few seconds

### To Reproduce

loaded into sandbox on staging using the launch commands -vulkan and -skip_start_screen
black box appears over the right side of crosshair with the following showing in console every time it occurs:

* CSwapChainVulkan::SwapBuffers vkAcquireNextImageKHR - completed result = VK_SUBOPTIMAL_KHR
Vulkan swapchain out-of-date, suboptimal, or surface lost -recreating.  Result: (VK_SUBOPTIMAL_KHR)*
Swapchain extent(s) are 0, skipping swapchain creation * 

### Expected behavior

should not have black box in center of screen

### Media/Files

disappears if i screenshot

### Additional context

windows 11
rx 6600 XT challenger
r5 5600x
32gb ddr4

**Comment by yuberee** [comment]
What was the solution to this issue for documentation sake?

**Comment by gwiddypwofessional** [comment]
disabled vulkan launch command lol
