### ISSUE TITLE
Physics objects sometimes fall through the world

### ISSUE THREAD

**Issue by andy013** [sboxgame/issues#4073]
### Describe the bug

I have this bug where sometimes physics objects will fall through the world and disappear. 

If I add this code to the Simulate method of a minimal project then it will spawn brooms when left click is pressed. Sometimes the brooms will just pass though the walls or the floors and disappear. It seems to happen more often with complex physics shapes, but even with simple shapes it will still happen on rare occasions. 

```csharp	
if ( Game.IsServer && Input.Pressed( "attack1" ) )
{
        var model = new ModelEntity();
        model.SetModel( "models/citizen_props/broom01.vmdl_c" );
        model.SetupPhysicsFromModel( PhysicsMotionType.Dynamic );
        model.Position = Position + Rotation.Forward * 40 + Rotation.Up * 50;
        model.Rotation = Rotation.LookAt( Vector3.Random.Normal );
        model.Velocity = Rotation.Forward * 400;
}
```

I tried messing around with the project physics settings but nothing seems to help. 

### To Reproduce

1. Create a minimal project. 
2. Spawn some physics objects against the wall
3. Watch as some will fall through. 

### Expected behavior

Physics objects should never fall through the map. 

### Media/Files

Here's an example of it happening with a weapon model:

https://github.com/sboxgame/issues/assets/10728824/ba2dc544-ef66-4103-8458-31a419289b7c

**Comment by yuberee** [comment]
What does the collisions look like on that gun?

**Comment by MrBrax** [comment]
for me they fall through the floor if i step on them, but it might be because of the shooter movement controller

**Comment by FancyApricot** [comment]
switching my colliders from PhysicsHullFromRender to Capsule's works for me

**Comment by andy013** [comment]
@yuberee  This is what the physics hull looked like on that gun. I know this could be simplified but I just used it as an example because it happens more often with complex shapes. 

<img src=https://github.com/sboxgame/issues/assets/10728824/ab80065e-8671-46a4-9aeb-ebd868fcd11d) width="25%">
</br>
</br>

> for me they fall through the floor if i step on them, but it might be because of the shooter movement controller

@MrBrax You can change the collision matrix in your project settings if you want to stop this from happening. 

> switching my colliders from PhysicsHullFromRender to Capsule's works for me

@FancyApricot This works but if you want to use a shape that is slightly more complex that the predefined ones then it will fall through. 

I have this physics model on a grenade and 95% of the time it works fine, but every now and then it will just fall through the map and disappear.
<img src=https://github.com/sboxgame/issues/assets/10728824/cff52186-dce2-4613-807b-0483c93e6bb1 width="25%">

**Comment by FancyApricot** [comment]
you can [attach multiple shapes](https://wiki.facepunch.com/sbox/Importing_Rust_Weapon_Models#physics)

**Comment by andy013** [comment]
Yes. I know. I have already done this as a workaround for now, but I would like to use a mesh for some of my physics objects.

**Comment by MrBrax** [comment]
@andy013 
But that would just make me walk through everything, right? I still want all my props to be an obstacle.
