### ISSUE TITLE
Cubemaps capture player's AO.

### ISSUE THREAD

**Issue by FullStack0verfl0w** [sboxgame/issues#4076]
### Describe the bug

Yet another cubemap bug.

### To Reproduce

1. Place a cubemap somewhere.
2. Place info_player_start near the cubemap.
3. Run the map.

### Expected behavior

Cubemaps shouldn't capture player's AO.

### Media/Files

![image](https://github.com/sboxgame/issues/assets/36414434/5348dd29-11cf-4cf2-b324-72abc1f42249)

**Comment by aylaylay** [comment]
Should be fixed now, let me know
