### ISSUE TITLE
Cannot interact with some widgets on peripheral screens

### ISSUE THREAD

**Issue by Cryotheus** [sboxgame/issues#4079]
### Describe the bug

When the editor is on any screen other than my main screen (number 1 in Window's display settings) some widgets cannot be clicked.  
It seems to affect:
- [`Editor.ControlSheet`](https://asset.party/api/Editor.ControlSheet)
- [`Editor.TreeView`](https://asset.party/api/Editor.TreeView)

These widgets are essential in the asset browser, entity tree, and UI panels tree.
Scrolling seems to work fine.

### To Reproduce

1. Open a game project on any monitor other than your primary
2. Attempt to interect with any of the aforementioned widgets using the mouse buttons

### Expected behavior

The widgets should respond to mouse clicks.

### Game Details
App ID: 590830
Build ID: 12378218
Last updated: Oct 6, 2023 at 18:09

### System Details
Microsoft Windows 11 Pro (10.0.22621 Build 22621)
CPU Architecture: 64bit
Plenty of resources (RAM, CPU time, GPU time) were available during testing

**Comment by handsomematt** [comment]
#4072
