### ISSUE TITLE
[Hammer] While in an active instance, hovering your mouse over any other instance should reveal the edges of the mesh inside.

### ISSUE THREAD

**Issue by LiminalCrab** [sboxgame/issues#4080]
### For?

Hammer

### What can't you do?

When you activate an instance in Hammer, you can't see other loop cuts made on other instances. This can make it difficult to line up your loop cuts for things like texturing or merging later on.

![measurement1](https://github.com/sboxgame/issues/assets/78995156/a39c8cd7-b09a-4a5d-a72b-8d16116a53e5)

### How would you like it to work?

Hover your mouse over other instances should show what edges the mesh inside has.

### What have you tried?

I mostly just enter and exit them as I need to but it can be tedious with many different cuts.

**Comment by e1m1j** [comment]
Have you tried pressing F8 for wireframe mode?
