### ISSUE TITLE
Editor has a redundant QToolBar widget

### ISSUE THREAD

**Issue by Cryotheus** [sboxgame/issues#4084]
### Describe the bug

The editor has a blank second tool bar.

### To Reproduce

1. Open the Editor with a game project or in content mode
2. The extra tool bar is present

### Expected behavior

There shouldn't be a blank second toolbar, like this:
<img width="924" alt="sbox-dev_uM8BohcCBD" src="https://github.com/sboxgame/issues/assets/14439112/1fb269fb-45e6-480b-86da-36759c4f09ca">

### Media/Files

Extra widget highlighted  
<img width="924" alt="sbox-dev_6AUgEQgoKw" src="https://github.com/sboxgame/issues/assets/14439112/a5f46501-88ae-4fca-957e-7cd002232a0d">  

The widgets listed using the Widget Debugger  
<img width="558" alt="sbox-dev_UXHSrGrIl2" src="https://github.com/sboxgame/issues/assets/14439112/6a5b77be-896e-4ce9-9eb0-2bbe0d64801e">

### Game Details
App ID: 590830
Build ID: 12384173
Last updated: Oct 6, 2023 at 18:09

### System Details
Microsoft Windows 11 Pro (10.0.22621 Build 22621)
CPU Architecture: 64bit
Plenty of resources (RAM, CPU time, GPU time) were available during testing

**Comment by Cryotheus** [comment]
After a bit of experimenting, it seems the tools can be docked inside of it. But the issue still stands as the tools can be docked below it anyways. No other widget can be docked in that spot, just the tools can.

https://github.com/sboxgame/issues/assets/14439112/5900bbdf-e541-47ab-9038-d3519ed076d5

**Comment by handsomematt** [comment]
This is intended and is / will be used by the new scene editor
