### ISSUE TITLE
Able to use HTTP localhost web image

### ISSUE THREAD

**Issue by PolSpock** [sboxgame/issues#4087]
### For?

S&Box

### What can't you do?

Hi,

I'm unable to use a localhost self-hosted image cause `Sandbox.TextureLoader.Image.Load` throws an error if my web image path contains `:` and uses an insecure environment (HTTP)

It's quite frequent if i am in a localhost environment and when i use my local web service host images.

Edit: After investigation, the error is thrown cause the URL is in an unsecured environment (HTTP where it has to be HTTPS), but in localhost, it is annoying to configure a secure HTTPS for that case.

For example when i use :
```
Style.BackgroundImage = await Texture.LoadAsync("http://localhost:8080/public/images/shop/bmc-button.png");
```
or
```
Style.SetBackgroundImageAsync("http://localhost:8080/public/images/shop/bmc-button.png");
```

It will be thrown :
```
Generic Image.Load: http://localhost:8080/public/images/shop/bmc-button.png: The path `/http:/localhost:8080/public/images/shop/bmc-button.png` cannot contain the `:` character
```

### How would you like it to work?

It will be cool to allow image path to use `:` and/or `HTTP` for the [allowed URLs](https://wiki.facepunch.com/sbox/http#allowedurls) : `localhost:80` / `localhost:443` / `localhost:8080` / `localhost:8443`

### What have you tried?

```
Style.BackgroundImage = await Texture.LoadAsync("http://localhost:8080/public/images/shop/bmc-button.png");
// or
Style.SetBackgroundImageAsync("http://localhost:8080/public/images/shop/bmc-button.png");
```

**Comment by PolSpock** [comment]
Edit : After investigation, the error is thrown cause the URL is in an unsecured environment (HTTP where it has to be HTTPS), but in localhost, it is annoying to configure a secure HTTPS for that case.

**Comment by MrBrax** [comment]
isn't the static non-async function meant for http and the async one is for local filesystems?

**Comment by handsomematt** [comment]
should be able to use http:// images now
