### ISSUE TITLE
`Inspector` editor tab is empty on `Entity` inspection (`no beta` branch)

### ISSUE THREAD

**Issue by PolSpock** [sboxgame/issues#4092]
### Describe the bug

Hello,

Since a recent update (end of September 2023), the editor `Inspector` tab has stopped working when you try to inspect an Entity by clicking it through the `Entities` editor tab.

I'm currently on the "no beta" branch of S&box

### To Reproduce

1) Launch S&box in editor mode (`no beta` branch)
2) Start a Game
3) Goto the `Entities` tab
![image](https://github.com/sboxgame/issues/assets/5229571/eb418501-4cf9-4f7e-b800-c985070ac46f)
4) Click on any Entity
5) Constat your `Inspector` tab will not be updated with any Entity information

![image](https://github.com/sboxgame/issues/assets/5229571/e7f7c715-4cf3-483d-a7e7-094c1211b6b0)

### Expected behavior

The expected result should be like before the update when we're able to see Entity property.

### Additional context

Build ID : 12440761

**Comment by MrBrax** [comment]
it's empty when you click an ui element in the tree too
