### ISSUE TITLE
Prefab Editor doesn't work properly on legacy s&box

### ISSUE THREAD

**Issue by ceitine** [sboxgame/issues#4099]
### Describe the bug

The legacy prefab editor only shows the adding entities part, but you can't edit the properties or anything.
Would be nice to have this working for Papa's s&box gamejam.🥺 

### To Reproduce

1. Open legacy s&box tools. 
2. Create a prefab.
3. Open the prefab and add an entity.
4. Click on the entity and nothing will show up in the properties area.

### Expected behavior

The prefab editor should let you modify properties and add components.

### Media/Files

![image](https://github.com/sboxgame/issues/assets/19620198/00c52c7d-73d5-4baf-b4ad-4b3d4381066e)

**Comment by DevulTj** [comment]
Should be fine now, but please let me know if that's not working for you
