### ISSUE TITLE
Input Actions in Project Settings use the wrong code for the Right and Middle Mouse Buttons

### ISSUE THREAD

**Issue by rndtrash** [sboxgame/issues#4100]
### Describe the bug

When making a new action that uses the right mouse button in the project settings, in the game that action is actually triggered by the middle mouse button.

### To Reproduce

1. Make a new action or edit an existing one
2. Click on "Keyboard Code"
3. Press the right or middle mouse button
4. You will see MOUSE3 after pressing RMB or MOUSE2 after pressing MMB

### Expected behavior

RMB is MOUSE2, MMB is MOUSE3, that's how it works in the game.

### Additional context

OS: Windows 10

**Comment by DevulTj** [comment]
Fixed that, my bad 😄
