### ISSUE TITLE
Models fail to load every other restart

### ISSUE THREAD

**Issue by yuberee** [sboxgame/issues#4105]
### Describe the bug

All the models from our hammer entities fail to load in our game.
To fix it requires a restart, but sometimes some models fail to load still, even duplicate ones (Let's say 1 door out of 6 is missing even if it's the same model)
We thought Matt's latest "Fix Model.Load exception" fixed it but it's still been happening.

### To Reproduce

Pull https://github.com/Small-Fish-Dev/In-This-House
Start game
Restart until there are no models showing up

### Expected behavior

To load the models correctly the first time

### Media/Files

https://github.com/sboxgame/issues/assets/59583743/591aae30-2714-4531-a281-26b61aeb8d58

### Additional context

Happens on both branches, this is using the entity system not the scene system.

**Comment by yuberee** [comment]
I also noticed that sometimes the light gets messed up when it happens, it's clearer inside the actual game where it's supposed to be dark but it's all bright
![image](https://github.com/sboxgame/issues/assets/59583743/f8f8eebf-4648-4e00-9079-5ae328390150)
![image](https://github.com/sboxgame/issues/assets/59583743/9ca38bc5-e5d1-461f-85e4-486b3a041a94)

**Comment by handsomematt** [comment]
whats the video showing, whats the green stuff

**Comment by yuberee** [comment]
The video is showing the first bootup, where there are no models loaded, but when I enable the physics wireframe it shows that the entities are there, same with collisions, just not on the client. If they were we would be able to see the "PRESS E TO..." option.
I then restart the game and everything shows up correctly.
They are basic HammerEntity ModelEntities with model set on Spawn

**Comment by handsomematt** [comment]
sounds like they're there on the server but not client then, probably something to do with the horrid precache system. will look into it.

**Comment by handsomematt** [comment]
Seems to be the vis in your map. I recompiled the map with vis off and it all works fine.

**Comment by yuberee** [comment]
https://www.youtube.com/watch?v=2cJcrqHNbTc

I have made sure that there was no compiled VIS in the map, deleted the previous compiled map, and did so for all other prefabs (We have each level as a prefab, we then place them in the final map that gets compiled and used for gameplay)

The first playthrough is fine, then stops working after a restart, then another restart, and then works again the 4th time.

**Comment by yuberee** [comment]
https://www.youtube.com/watch?v=83x84zRyxgI

I tried switching branches, made sure to delete all vmap.meta and vpk files from our game, double checked the vis and disabled it like shown in the screenshot.
Good news is it seems to always work on the first startup, so it's harder for a player to encounter.

**Comment by yuberee** [comment]
![image](https://github.com/sboxgame/issues/assets/59583743/ff28d770-a2eb-439f-9dbf-f509958e7175)
![image](https://github.com/sboxgame/issues/assets/59583743/75b7cc2f-ada7-48a0-941f-42386836c347)

Now that's weird...
Doors are spawned ON CLIENT but not ON SERVER.
Nowhere in the code we spawn/delete doors, it's all handled by Hammer and [HammerEntity]

**Comment by yuberee** [comment]
![image](https://github.com/sboxgame/issues/assets/59583743/dff0ccbf-7313-4946-a12a-f32a69821e2b)

And now the door collisions are weird? I don't recognize that shape from any of our models

**Comment by yuberee** [comment]
While the original problem has been solved (We were creating an entity inside of the Game's constructor)
It seems that every first time that we start the game, the entities will be missing, if you restart the game they will work as intended, if you restart again they will only work on client but not on server.
I've been up from 4am to 8am(now) trying to find what was causing the issue, between removing combinations of anything (entities, meshes, our stuff, hammer stuff) and recompiling the map, nothing worked.
Sometimes it seemed like removing entire levels from the final map worked, but then it would inexplicably come back.

**Comment by handsomematt** [comment]
iirc this was a problem with native entity constructors, so not applicable anymore
