### ISSUE TITLE
Hammer move/rotate/etc gizmos not showing up

### ISSUE THREAD

**Issue by BatterySand** [sboxgame/issues#4106]
### Describe the bug

title, but it shows up if you move to a certain angle or go far away but then disappears if you slightly move.

### To Reproduce

go to hammer

try to use move gizmos on objects 

### Expected behavior

gizmos should show up

### Media/Files

![image](https://github.com/sboxgame/issues/assets/96210425/4dbb5e30-5fc7-40a3-9ff2-83e85b9654e5)
![image](https://github.com/sboxgame/issues/assets/96210425/86c94514-e3b0-4f98-92d9-d5c68a67ac02)

**Comment by yuberee** [comment]
This seems to have been fixed by the commit:
`Revert "None of this is used, prove me wrong"`
