### ISSUE TITLE
`sbox-server`: memory leak with `INetworkSerializer` and `BaseNetworkable.OnCallRemoteProcedure`

### ISSUE THREAD

**Issue by PolSpock** [sboxgame/issues#4109]
### Describe the bug

Hello,

I'm using the Facepunch [`sbox-sdf`](https://github.com/Facepunch/sbox-sdf) library for my game, and in the past, i used [`sbox-csg`](https://github.com/Facepunch/sbox-csg).

The common point between the 2 that i'm encountering `***** OUT OF MEMORY! /+/ attempted allocation size: 5000055 ****` error on my `sbox-server.exe` running on windows dedicated server.

I've decided to investigate myself for spotting the error, and i have spotted 2 interesting crashing behavior, based on how you used the S&box Networks API.
Here are steps to reproduce :

### 1st Behaviour: Investigation based on SDF/CSG library

~~The SDF and CSG libraries are the only projects from Facepunch that used override of https://github.com/search?q=OnCallRemoteProcedure&type=code~~

~~By my investigation, i found that the use of it will produce an `***** OUT OF MEMORY! /+/ attempted allocation size: 5000055 ****` the more time passed.~~

~~Here are the steps to reproduce :~~

~~1) Download my custom `sandbox` game enhanced with Networked entities: [`sbox-memory-leak`](https://github.com/PolSpock/sbox-memory-leak)~~

~~For this one memory leak behavior, look at my [`code\entities\OnCallRemoteProcedureEntity.cs`](https://github.com/PolSpock/sbox-memory-leak/blob/main/code/entities/OnCallRemoteProcedureEntity.cs) which implements the `OnCallRemoteProcedure`~~
~~It basically implements an override from `BaseNetworkable.OnCallRemoteProcedure` like [this one](https://github.com/Facepunch/sbox-sdf/blob/3c0bd6040d0796d1bcb2ec541ede30279e23c6a4/libsdf/code/SdfWorld.Entity.cs#L114C32-L114C32)~~

~~2) Start a `sbox-server` with my [custom sandbox game published on asset.party](https://asset.party/garrycity/sandbox_entity_net) (you can also create your one)
`.\sbox-server.exe +gamemode garrycity.sandbox_entity_net +map facepunch.flatgrass +maxplayers 12 +hostname Testo`~~

~~3) Join the started server. Once in the game, it works like sandbox game. Select the tool "OnCallRemoteProcedureEntitySpawner" and then press `attack1` to spawn the `OnCallRemoteProcedureEntity` entity.~~

~~I recommend you spawn only a few boxes.
The 128-tick server will start to send you a lot of NetWrite messages based on the Tick loop written.~~

~~**Be careful**, if you running the `sbox-server` on your computer, your PC will run out of memory too! Don't blame me if you have to restart your PC.~~

~~4) Open your Windows `Task Manager` and look at your `sbox-server` line. See how your memory starts to continuously increase.~~
~~Wait until 1200Mo of used RAM, you will get an `***** OUT OF MEMORY! /+/ attempted allocation size: 5000055 ****` memory error and your `sbox-server` will automatically crash.~~

~~Also, note that if you haven't any player on the server, the memory will stop to increase but never reduce.~~

**[UPDATE 26/10/2023]**: the first behavior has been fixed with a simple `using`. In fact, the problem was [`NetWrite`](https://asset.party/api/Sandbox.NetWrite) implemented the IDisposable interface. So it has to release the memory at the end of the block. Find more info on this fixed issue: https://github.com/Facepunch/sbox-sdf/issues/20
The second behavior is still relevant, where memory still increases with time: more time passed, more `Dictionary+Entry<Int32, Byte[]>[]` are accumulated
![image](https://github.com/sboxgame/issues/assets/5229571/63089ebb-cd78-4973-ab42-5eceba267abc)

### 2nd Behaviour: Investigation based on `sbox-sandblox` and custom `INetworkSerializer`

So because the `OnCallRemoteProcedure` is a pretty unique usage from SDF/CSG libraries, i wanted to know how a custom [`INetworkSerializer`](https://wiki.facepunch.com/sbox/Networked_Types#inetworkserializer) implementation will react.

I started to look at [`sbox-sandblox`](https://github.com/Facepunch/sbox-sandblox/blob/master/code/Chunk.cs) and i have implemented my own `NetworkSerializer`.

Look at the [`NetworkSerializerEntity.cs` entity](https://github.com/PolSpock/sbox-memory-leak/blob/main/code/entities/NetworkSerializerEntity.cs). This entity has a `[Net] public NetSerializer Data { get; set; }` that contains the basic `INetworkSerializer` implementation.

The class has also a `[GameEvent.Tick.Server]` in order to send data to clients. To always pass data to clients, i randomly changed the Size property.

So once again, if you haven't done it on the first behavior explanation :
1) Download my custom `sandbox` game enhanced with Networked entities: `sbox-memory-leak`

2) Start a `sbox-server` with my [custom sandbox game published on asset.party](https://asset.party/garrycity/sandbox_entity_net) (you can also create your one)
`.\sbox-server.exe +gamemode garrycity.sandbox_entity_net +map facepunch.flatgrass +maxplayers 12 +hostname Testo`

3) Join the started server. Once in the game, it works like sandbox game. Select the tool "NetworkSerializerEntitySpawner" and then press `attack1` to spawn the `NetworkSerializerEntity` entity.
I recommend you spawn many boxes.

4) Open your Windows `Task Manager` and look at your `sbox-server` line. See how your memory starts to continuously increase.
HOWEVER, a difference between the first behavior, is your server will not crash after 1200mo. You will not run out of memory but your memory consumption will increase as time passes.

Also, note once again, that if you haven't any player on the server, the memory will stop to increase but never reduce.

See my media below to observe the RAM consumption based on my CPU profiling investigation

### Expected behavior

Sending networking packages must not increase RAM consumption as hell.

_Moreover:_
~~- For the 1st behaviour: use `BaseNetworkable.OnCallRemoteProcedure` must not result in a `***** OUT OF MEMORY! /+/ attempted allocation size: 5000055 ****` crash~~ **[UPDATE 26/10/2023]**: 🆗 see my update comment above
- For the 2nd behavior: maybe my `INetworkSerializer` is wrongly implemented, in this case, the [Wiki page](https://wiki.facepunch.com/sbox/Networked_Types#inetworkserializer) has to be more detailed in order to avoid memory leak.

### Media/Files

I have limited knowledge of Visual Studio Profiler, but i've been able to spot some weird RAM behaviors during my investigation of my `INetworkSerializer` implementation :

1st picture: more time passes with my `NetworkSerializerEntity` entities spawned, more RAM increased
![ram4](https://github.com/sboxgame/issues/assets/5229571/8836c6ce-eacf-4a0c-9298-1ec4a0ac3b24)

2nd picture: i've been able to open the difference between 2 stacks. Each time the number of `Dictionary+Entry<Int32, Byte[]>[]` are increasing. However, i haven't been able to see the value of these entries.
![ram2](https://github.com/sboxgame/issues/assets/5229571/2420894f-2141-4a15-b63b-f38fc48d88a0)

3rd picture: only 20 `NetworkSerializerEntity` entities spawned, and i've reached 4go RAM usage after 2,5hours of idling with my secondary sbox account on my sbox-server!
![image](https://github.com/sboxgame/issues/assets/5229571/bcfb90d2-3ef5-46c6-9cec-c0fb7220f176)

### Additional context

My `sbox-server.exe` is running on `Microsoft Windows Server 2022 Standard`

**Comment by DevulTj** [comment]
Worth mentioning that this will not be an issue when legacy networking is removed.
