### ISSUE TITLE
Flex Not Interpreting Basis Properly

### ISSUE THREAD

**Issue by Andrei15193** [sboxgame/issues#4112]
### Describe the bug

I'm trying to use `flex: 0 0 10px`, however it throws an error.

```
Couldn't parse flex 0 0 10px - expected a float or length
```

The flex basis does work if I set the parts individually:
```css
flex-grow: 0;
flex-shrink: 0;
flex-basis: 10px;
```

### To Reproduce

In a `.scss` file write `flex: 0 0 10px;`, e.g.:

```css
Main {
    flex: 0 0 10px;
}
```

### Expected behavior

There is no error thrown and the flex grow, shrink, and basis components are set accordingly.

### Additional context

N/A

**Comment by cr4yz** [comment]
This should be fixed in the next update, please let us know if you've got any more troubles

**Comment by Andrei15193** [comment]
Switched the places where I had the individual parts set, I'm using it with `flex: 0 0 0%`, `flex: 0 0 100%`, and `flex: 0 0 10px` and it works. Thanks! 😃
