### ISSUE TITLE
CSS white-space: normal does not work

### ISSUE THREAD

**Issue by Andrei15193** [sboxgame/issues#4114]
### Describe the bug

Having a text go across multiple lines does not have its white space collapsed between the lines, setting `white-space: normal` has no effect.

### To Reproduce

On any panel, add text that spans across multiple lines with indentation:

```html
<root>
    <div>
        <label>
            This
            white space
            should
            collapse
        </label>
    </div>
</root>
```

Setting `white-space: normal` has no effect.

```html
<root>
    <div>
        <label style="white-space: normal;">
            This
            white space
            should
            collapse
        </label>
    </div>
</root>
```

The above will display the following on the UI

![image](https://github.com/sboxgame/issues/assets/3336988/590c5c12-267f-44c6-a958-711abfdfe49a)

### Expected behavior

The white space between lines should be collapsed and everything should be displayed continuously.

![image](https://github.com/sboxgame/issues/assets/3336988/7418afe5-3eb9-4630-b28f-642da36ba98f)

### Additional context

N/A

**Comment by cr4yz** [comment]
I switched us to collapse white space by default to fit the standard.  `white-space: normal` is supported now but not necessary as its the default.  Please let me know if you have any troubles.

**Comment by Andrei15193** [comment]
I can confirm, it works nicely now. Thanks! 😃
