### ISSUE TITLE
Add env_texturetoggle entity to Hammer

### ISSUE THREAD

**Issue by Asphaltian** [sboxgame/issues#4117]
### For?

Hammer

### What can't you do?

Currently, there is no support for the env_texturetoggle entity in Hammer, which makes it challenging for level designers to incorporate this crucial functionality into their maps. This entity is commonly used to switch between different textures or materials dynamically, which can significantly enhance the visual quality and interactivity of levels.

### How would you like it to work?

I would like to propose the addition of the env_texturetoggle entity to Hammer, similar to its functionality in other Source Engine iterations. The env_texturetoggle entity should work as follows:

1. **Entity Creation:** Level designers should be able to place the env_texturetoggle entity in the map through Hammer's interface.

2. **Texture Toggle:** The entity should allow designers to define a list of textures or materials to toggle between. It could include options to specify the transition speed and looping behavior, similar to how it functions in other Source Engine games.

3. **Triggering Mechanism:** Designers should be able to trigger the entity through various mechanisms, including inputs from other entities, player interactions, or scripted events.

4. **Material Control:** The entity should be able to toggle between textures or materials assigned to different surfaces or objects in the map.

### What have you tried?

I have reviewed the current entity list and tools available in Hammer for s&box, and it appears that there is no support for the env_texturetoggle entity at the moment. I've also searched for documentation or discussions on this topic but haven't found any relevant information or workarounds.

**Comment by handsomematt** [comment]
We're moving away from entities, I would've said this would be a ugc entity anyway
