### ISSUE TITLE
Allow custom function calls in Dynamic Expressions

### ISSUE THREAD

**Issue by DeltaDesigns** [sboxgame/issues#4124]
### For?

Material Editor

### What can't you do?

Material dynamic expression functions are currently limited to the ones provided by valve
https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Materials/Dynamic_Material_Expressions

### How would you like it to work?

Being able to define a custom function in the expression or to be able to call functions from the shader the material is using

### What have you tried?

Making a simple function in the shader and trying to call it in a dynamic expression, this just returns that the provided function is invalid

**Comment by QuackCola** [comment]
im pretty sure dynamic expression functions would be defined c# and not hlsl

**Comment by handsomematt** [comment]
Dynamic expressions are a very lightweight custom scripting language defined in C++, letting people define custom stuff is gonna make it slow as shit and kind of defeats the point of it.
