### ISSUE TITLE
Streaming integration doesn't work (possibly only in GameMenu space?)

### ISSUE THREAD

**Issue by ShadowBrian** [sboxgame/issues#4129]
### Describe the bug

Even connecting your twitch/whatever streaming service doesn't work, I can't find it anywhere, but beyond that any of the example code I can find about it is 2 years old and written for the Entity system, and uses client console commands for a lot of things which I don't think we can make in GameMenu space to begin with.

### To Reproduce

Can't find twitch login anywhere, can't use the API in GameMenu space so Scene-based games won't work with it.

### Expected behavior

I would expect it to work even if there was no working example code anywhere on how to use it.

**Comment by garrynewman** [comment]
Does this link work? https://sbox.facepunch.com/link/

**Comment by ShadowBrian** [comment]
It does! I'll run some tests.

**Comment by ShadowBrian** [comment]
Not sure how to get it working- Streamer.Service seems to return None and it's not letting me send a test message- I think something's busted

**Comment by ShadowBrian** [comment]
Apparently there was something related to turning it on in settings that's gone now?

**Comment by xezno** [comment]
Will re-add it to the menu where it was before, but I think it'd be better off in settings somewhere

**Comment by ShadowBrian** [comment]
Alright so I've got it mostly working, at least the base chat message reading, I'm not sure the poll creation/reading functions still work, couldn't get them to work anyway, other features might also be broken and need looking at.
