### ISSUE TITLE
[Shadergraph] Shader preview fails to compile resulting in broken preview 

### ISSUE THREAD

**Issue by QuackCola** [sboxgame/issues#4130]
### Describe the bug

When attempting to use shadergraph any changes i make to either a new or existing shadergraph shader are not visible in the _**Preview window**_. I do notice _**Compile Failed**_ being printed in the console each time i click on the compile button.

### To Reproduce

1. Open Shadergraph 
2.  Open an existing shadergraph shader or create a new one.
3. make some changes and compile and notice that none of your changes will visible in the **_preview viewport_**. Also notice  the _**Compile Failed**_ error being printed in the console.

### Expected behavior

The compile should succeed  and thus any changes to the graph should be visible on the preview model in the _**Preview Viewport**_. 

### Media/Files

https://github.com/sboxgame/issues/assets/23345567/54aa8a21-02ae-4bba-bd9f-6383cb678e01

**Comment by handsomematt** [comment]
should be 🆗 now

**Comment by QuackCola** [comment]
> should be 🆗 now

I  can confirm its working as expected now. Thanks!
