### ISSUE TITLE
connecting to servers timeout

### ISSUE THREAD

**Issue by neonoxd** [sboxgame/issues#4131]
### Describe the bug

I am unable to connect local (and remote) games by IP using the `connect` command. Not even lan servers
It probably broke during the last few days/weeks.

Note: dedicated server also seem to suffer from the same problem

### To Reproduce

A:
- Start the game
- `sv_lan 1` in console
- Start **sandbox** game
- Create a server

- Start another instance of the game
- `sv_lan 1` in console
- Try to connect using `connect localhost` in console

B:
- Ask someone to host a game (with port forwarding and everything properly setup)
- Start your game
- Try to connect using `connect <ip>` in console

### Expected behavior

Connect to the server

### Media/Files

```
> connect localhost
Opened Steam Net Connection on socket 'client' to 127.0.0.1:27015, connection #3371104680 UDP invalid@127.0.0.1:27015
Failed to connect to 127.0.0.1:27015.  Reason code 5003.  Timed out attempting to connect
CL:  Server disconnected: 72: NETWORK_DISCONNECT_CONNECT_REQUEST_TIMEDOUT
Discarding pending request 'Remote Connect (localhost), 6'
```

### Additional context

- Windows 11
- Have WSL installed therefore I have additional network adapters, could be useful to know but I doubt it's related

**Comment by PolSpock** [comment]
I have the same issue, also without lan parameter

https://github.com/sboxgame/issues/assets/5229571/864440b0-f334-4d8f-85af-ee6d10b23a79
