### ISSUE TITLE
`Editor` folder does not work for addons.

### ISSUE THREAD

**Issue by badandbest** [sboxgame/issues#4133]
### Describe the bug

`Editor` folder doesn't appear to work in addons. 

More importantly, this seems to prevent me from making widgets in my addon.

### To Reproduce

1. In the code directory, create a folder named `Editor`.
2. For game projects, a .editor gets added. ( Shown below )
3. Doing the same thing in an addon project, no such .editor appears. ( Shown below )
![image](https://github.com/sboxgame/issues/assets/91832803/466cc4c5-9321-4571-afde-c52d6083938f)

### Expected behavior

An Editor folder in addon projects should work similarly to that of ones inside a game project.
![image](https://github.com/sboxgame/issues/assets/91832803/8c5ceec6-0b81-4971-b077-310e5ecb8755)

**Comment by DevulTj** [comment]
This is intended, it is only available for game projects

**Comment by badandbest** [comment]
:(

**Comment by badandbest** [comment]
I hope this gets changes in the future.
