### ISSUE TITLE
Animated ent_door doesn't run animations when used first time. 

### ISSUE THREAD

**Issue by FullStack0verfl0w** [sboxgame/issues#4143]
### Describe the bug

Animated ent_door doesn't run animations on client side when used first time. 

### To Reproduce

1. Create ent_door with "Movement type" set to "Animation only".
2. Compile the map and try to open the door.

### Expected behavior

Animations should run every time it opens/closes.

### Media/Files

[window_animation.webm](https://github.com/sboxgame/issues/assets/36414434/ece22b22-003b-4874-9cc7-dec31089ccc9)

**Comment by NotGaylien** [comment]
Question, are you using the door animgraph for this

**Comment by NotGaylien** [comment]
im 99% sure its this which is screwing you over.
https://github.com/sboxgame/issues/issues/565

**Comment by FullStack0verfl0w** [comment]
> im 99% sure its this which is screwing you over. #565

Yeah.

**Comment by DevulTj** [comment]
This entity is gone
