### ISSUE TITLE
Can't make Post Processing components in Scene (AddHookBeforeOverlay was made internal during the scene merge) 

### ISSUE THREAD

**Issue by CarsonKompon** [sboxgame/issues#4153]
### Describe the bug

It's currently not possible to make custom post processing components since AddHookBeforeOverlay was made internal when merged into the engine, so there is no longer a way to hook your render effect into a CameraComponent.

### To Reproduce

Try to create a component similar to the Vignette or other post-processing components (from when the scene system was on the facepunch/sbox-scenestaging branch).

![image](https://github.com/sboxgame/issues/assets/5159369/edb75a7d-1a80-4a2e-86be-d70abbd579e3)

### Expected behavior

You should be able to AddHookBeforeOverlay. Or at least add some way to create post-processing components for the camera as easily as it was.

**Comment by DevulTj** [comment]
I fixed this today

**Comment by CarsonKompon** [comment]
Oh you totally did, my bad 😅
