### ISSUE TITLE
Exception thrown when trying to access the preferences menu

### ISSUE THREAD

**Issue by Retroeer** [sboxgame/issues#4157]
### Describe the bug

![image](https://github.com/sboxgame/issues/assets/44037603/c4de30b2-81db-4b9d-9593-bd9884ec8162)
Preferences window doesn't open

### To Reproduce

![image](https://github.com/sboxgame/issues/assets/44037603/b7b8463e-7faa-405f-8957-594b7a1670a4)
1. Click on Edit
2. Click Preferences
3. :(

### Expected behavior

Preferably the Preferences panel should probably be performing as planned

**Comment by handsomematt** [comment]
fixed next update
