### ISSUE TITLE
Allow folders in the scene hierarchy

### ISSUE THREAD

**Issue by trundlr** [sboxgame/issues#4160]
### For?

S&Box

### What can't you do?

Currently all gameobjects in the scene hierarchy exist flat unless nested within another gameobject. It would be great if we could have folders just to organize a scene with lots of gameobjects.

### How would you like it to work?

Right click -> create folder, drag and drop objects in or out of folders

### What have you tried?

N/A

**Comment by yuberee** [comment]
![image](https://github.com/sboxgame/issues/assets/59583743/45b510da-67c7-454c-adae-f19d3f5d29c4)

Haha yea...
Trying to SHIFT select all these game objects is hard, if I could just select the entire folder it would be better

**Comment by garrynewman** [comment]
This makes no sense imo. The GameObject's are like folders.

**Comment by TNMPlayer** [comment]
Pffft look at that pointless apostrophe
