### ISSUE TITLE
Shift+Click selecting multiple objects inside of the Scene Hierarchy doesn't work when original selection is out of view

### ISSUE THREAD

**Issue by yuberee** [sboxgame/issues#4161]
### Describe the bug

When the first game object selected is out of view (scrolled down or up) you can't shift+click select multiple scene objects.

### To Reproduce

1. Have at least 20 game objects, or enough that you have to scroll down to view them all.
2. Select the first game object
3. Scroll down so the selected game object is out of view
4. Shift+Click any other object

### Expected behavior

To select all objects regardless of being out of view.

### Media/Files

https://github.com/sboxgame/issues/assets/59583743/f3ad2ac1-abba-4f13-89a7-1b7b01fcf55c

**Comment by cr4yz** [comment]
This should be fixed in the next build.  Please let me know if you have any more troubles with shift selecting

**Comment by yuberee** [comment]
Works as expected
