### ISSUE TITLE
CameraComponent's Frustum Gizmo Doesn't Respect Ortho Setting

### ISSUE THREAD

**Issue by Willco2** [sboxgame/issues#4163]
### Describe the bug

The frustum gizmo drawn by the `CameraComponent` only shows a perspective frustum, and doesn't respond to toggling "Orthographic".

### To Reproduce

Toggle "Orthographic" on a `CameraComponent` while in the scene view.

### Expected behavior

Displayed frustum changes depending on ortho setting.

**Comment by DevulTj** [comment]
Should work as intended now 

https://github.com/sboxgame/issues/assets/22372616/1394b5eb-fdcf-48e0-987f-7f745f0b8e16
