### ISSUE TITLE
Saving scenes / prefabs will sometimes change order of properties arbitrarily

### ISSUE THREAD

**Issue by trundlr** [sboxgame/issues#4169]
### Describe the bug

Sometimes, opening a prefab and just clicking on a gameobject will dirty the scene. When saving, the properties may be out of order.
<img width="373" alt="image" src="https://github.com/sboxgame/issues/assets/57276947/2d6e3958-63d6-4003-8655-8d0a010bc85d">

We should guarantee order of properties in scene so that we are not unnecessarily making changes to files when working with teams. It is frustrating to have to resolve merge conflicts just because the order of properties are changed for no reason.

### To Reproduce

1. Clone a scene game
2. Open a scene and click around
3. The scene will probably dirty, and after saving the order of some properties will have changed.

### Expected behavior

The properties in a scene should save in some deterministic way.

**Comment by handsomematt** [comment]
Saving should definitely be deterministic
