### ISSUE TITLE
Missing properties and outputs on prop_physics and func_physbox

### ISSUE THREAD

**Issue by Haaselh0ff** [sboxgame/issues#459]
**Describe the bug**
Prop_Physics and func_physbox appear to be missing all outputs in the Outputs tab, as well as some of their properties such as MotionEnabled (boolean), StartAsleep (Boolean) in their Object Properties

**To Reproduce**

1. Go to Object Properties of a prop_physics or func_physbox
2. Click on Outputs
3. Create new Output
4. Observe no Output names in My Output Named
5. Observing Properties reveals many missing values as well from its HLA counterpart.

**Expected behavior**

Multiple outputs should be present here such as OnPlayerPickup, OnAwake, OnMotionEnabled. As stated above, many object properties also appear to be missing, primarily the ones listed but others are as well. Unsure if this is intended or not.

**Screenshots**
![image](https://user-images.githubusercontent.com/21314618/124861649-993ed200-df79-11eb-96c6-0121dcff9607.png)
![image](https://user-images.githubusercontent.com/21314618/124862107-6812d180-df7a-11eb-91dc-f04dd0de0116.png)

**Comment by robotboy655** [comment]
We will not be bringing back every property/output/input from HLA or Source 1. If you have specific things you actually need that aren't available - do tell what they are and what you need them for.

**Comment by Haaselh0ff** [comment]
Understandable as it's a lot of work I'm sure. I'm trying to make a system where you can board up windows using planks of wood and was wanting to allow the player to pick up and destroy the planks and was planning on doing this through func_physbox. I would only really need OnDamaged and OnPlayerPickup as outputs for the func_physbox and from there I would be able to do most everything I would need.

**Comment by robotboy655** [comment]
I have added `OnDamaged` to both, but with `OnPlayerPickup` its gonna be trickier. Right now anything that "picks up" props (grav gun, phys gun) are all exclusive to the Sandbox gamemode, so there isn't a cross-gamemode way to implement this right now.
