### ISSUE TITLE
Implement ; in the s&box console

### ISSUE THREAD

**Issue by KayaDLX** [sboxgame/issues#482]
**What can't you do?**
Can't execute multiple commands at once using `;` symbol in console.

**How would you like it to work?**
When I send a group of commands in console as one string, separated by `;` symbol they should be executed one by one.

**What have you tried?**
Running multiple commands with `;` and it didn't work.

**Additional context**
Same feature exists in all Source 1 games.

**Comment by Acecool** [comment]
It does work. You can't use spaces in the commands, etc..

For instance - 
```
bind ' "sv_password blah;say TestingTestingTesting;sv_visiblemaxplayers 1"
``` works. But 

```

bind ' "sv_password blah;say Testing Te stingT esting;sv_visiblemaxplayers 1"
```

doesn't because there is a space in the say command.

**Comment by Ryhon0** [comment]
`;` only works inside binds and aliases, not when typing it in the console, typing it in a console will just parse it as a command parameter

**Comment by KayaDLX** [comment]
🤓👆

**Comment by justynboi** [comment]
Yeah, this is still an issue.

**Comment by KayaDLX** [comment]
This would still be a nice addition to the console.

**Comment by KayaDLX** [comment]
This is still relevant, the editor currently supports it but not the in-game console.
