### ISSUE TITLE
Attaching particles to models is broken

### ISSUE THREAD

**Issue by ImWill0w0** [sboxgame/issues#502]
**Describe the bug**
Can't attach particles to models

**To Reproduce**

Add the 'particle' gamedata and try to apply it to a model, it won't render it ingame

**Expected behavior**

For the particles to be attached to the model

**Screenshots**

![sbox-dev_I9NWWYCh8h](https://user-images.githubusercontent.com/28235017/127046824-0c170879-d893-4786-9101-50c58fb273fa.png)

**Comment by bakscratch** [comment]
After Testing it seems to just be Prop_Physics that it doesn't work for.

**Comment by aylaylay** [comment]
I've made a start on this, currently it doesn't support all attachment types and they don't clean up when the parent entity is deleted.

**Comment by aylaylay** [comment]
I'd like to clean up these attachment types, a lot of them are bullshit
