### ISSUE TITLE
Built in JWT authentication for web requests

### ISSUE THREAD

**Issue by Jake-Rich** [sboxgame/issues#507]
**What can't you do?**

Authenticate your steam id when connecting to a web api.

**How would you like it to work?**

By having FP is providing the JWTs all your web api needs to implement is validating the token signature.

Each time you make a web request, it will check if it has a locally cached JWT for that domain. The JWT will also include the domain name in the token to prevent sites from spoofing users by reusing their tokens on other sites.

If no token is found for that domain, the client will generate a steam session token and send it to `api.facepunch.com/token/example` (along with the domain it wants the token for)

The response from the FP api will provide a JWT to the client. Since it is stored on the client it can be added manually in code as a header or (optionally) included automatically in each request to that domain.

The FP api would also provide a route to get the public key. Web apis can use that key to validate the token's signature and ensure the token is for their domain.

**What have you tried?**

You could roll your own system to try and provide tokens but that still requires the functionality for sandbox clients to generate steam session tokens, and THEN you need rely on users to validate the steam session & provide their own JWTs. At that point you may as well do the whole thing from your API saving developers time and making the tokens more secure.

**Additional context**

Eventually people will want to overwrite how domains are cached for SASS / big orgs ( should api.facepunch.com and other.facepunch.com use the same token? what about facepunch.com/app1 and facepunch.com/app2? ) but for now this will be good enough for most people.

**Comment by Rohansi** [comment]
Kind of a duplicate of https://github.com/Facepunch/sbox-issues/issues/496 except this is probably closer to what we'd do instead of exposing Steam auth tickets directly

**Comment by Jake-Rich** [comment]
> 
> 
> Kind of a duplicate of #496 except this is probably closer to what we'd do instead of exposing Steam auth tickets directly

I searched for 'token' before posting the issue, my bad on missing yours. Your right it is basically a duplicate but I'll leave it open until the solution is decided / implemented.

**Comment by MStruntze** [comment]
> Since it is stored on the client it can be added manually in code as a header or (optionally) included automatically in each request to that domain.

If it's stored on the client, what's preventing malicious code from requesting a jwt for a different audience (a competitor might operate) and then sending it to their own service for it to be abused?

**Comment by Rohansi** [comment]
> If it's stored on the client, what's preventing malicious code from requesting a jwt for a different audience (a competitor might operate) and then sending it to their own service for it to be abused?

How would you abuse it? This would just provide you with a way to identify someone by their SteamID without the possibility of spoofing as someone else.

Maybe there's a bit of confusion here since this is asking for JWT. Whatever tokens we end up using would likely only be valid for a short period of time and not support refreshing - like Steam's auth tickets (kind of, they are meant to be revoked by the client). JWTs are generally valid for much longer times.

**Comment by garrynewman** [comment]
I think for this to work we'd need to be sure of a few things

- The token needs to be game specific
- We'd need to be 100% sure the token came from your game
- We'd need to be 100% sure that it's running your code

It shouldn't be possible for my game to authenticate with your server. It shouldn't be possible for someone to download your code and compile it so it talks to your server in a different way than you designed.

Obviously this is near impossible but we work through things to get us there.

**Comment by Jake-Rich** [comment]
> 
> 
> > Since it is stored on the client it can be added manually in code as a header or (optionally) included automatically in each request to that domain.
> 
> If it's stored on the client, what's preventing malicious code from requesting a jwt for a different audience (a competitor might operate) and then sending it to their own service for it to be abused?

There are two situations where tokens can be "stolen":

1) User sniffs their own network traffic to get a JWT being sent:

Doesn't matter, the user sniffing the traffic is the user who the token belongs to, so they already have access.

2) A malicious addon gets access to another addon's header in a completely seperate gamemode:

Not good but can be avoided by never giving addons access to the token, only giving them a bool on whether they want to include the JWT in request.

**Comment by P4sca1** [comment]
If I understood correctly, the token is for authenticating users by their SteamID. Why do we need Steam session tokens then, instead of just writing the actual SteamID into the JWT payload?
Also, every custom addon / gamemode could authenticate as the player on any Web API using this approach, if the token is always available via user code or is automatically sent with every request.
To avoid these CSRF-like issues, there could be a user prompt like "Addon x wants to access site www.example.com on your behalf". And only when the user aggrees to this, the token can be returned.

**Comment by kurozael** [comment]
Garry has now added auth tokens for s&box that can achieve this. You can find information on how to use them here here https://wiki.facepunch.com/sbox/AuthTokens
