### ISSUE TITLE
SpotLightEntity isn't enables/disables if it's not moving 

### ISSUE THREAD

**Issue by DangerKiddy** [sboxgame/issues#526]
**Describe the bug**
When trying to enable/disable light using `light.TurnOn()` or `light.TurnOff()` or `light.Enabled = whatever` then if light not changing its position, it won't change its state.

**To Reproduce**

1. Create a Player class
2. Create a `SpotLightEntity` once in `Player.FrameSimulate` and make it flashing. Do not move it.
Take a look how it's working and then make it moving
```csharp
private SpotLightEntity light;
public override void FrameSimulate(Client cl)
{
	if (light == null || !light.IsValid())
	{
		light = new SpotLightEntity
		{
			Enabled = false,
			DynamicShadows = true,
			Range = 512,
			Falloff = 1.0f,
			LinearAttenuation = 0.0f,
			QuadraticAttenuation = 1.0f,
			Brightness = 2,
			Color = Color.White,
			InnerConeAngle = 20,
			OuterConeAngle = 40,
			FogStength = 1.0f,
			Owner = client.Pawn
		};
	}

	bool test = Time.Tick % 10;
	if (test < 5)
		light.TurnOn();
	else
		light.TurnOff();

	// Fix:  Rand.Float(0, .01f)
	light.Position = EyePos + EyeRot.Forward * 20 + Rand.Float(0, .01f);
	light.Rotation = EyeRot;
}
```

**Expected behavior**
When switching `SpotLightEntity`'s state using `light.TurnOn()` or `light.TurnOff()` or `light.Enabled = whatever` it should immediately change light's state(or aty next frame)

**GIFs**
https://i.gyazo.com/45c70ee7ecb7fe71ed6cd5fe2592469f.gif - NOTE: For second player it works good because `SpotLightEntity` moves with bone

**Comment by robotboy655** [comment]
I suspect this might have something to do with dormancy. `info_particle_system` has a similar/same issue, if you parent a particle effect to the `info_particle_system` itself, the effect will not update its position unless you base the particle entity from Model/AnimEntity.
