### ISSUE TITLE
Vertex color as albedo support for non-procedural/non-runtime generated models

### ISSUE THREAD

**Issue by walllable** [sboxgame/issues#527]
**What can't you do?**
Use an imported model's vertex colors as the albedo/color texture.

**How would you like it to work?**
Potentially a checkbox (Probably on the simple shader? Complex also works too, if it's not too much of a pain to implement) under the "Rendering" section in the shader settings to use vertex color for albedo, instead of textures. 
If you want to go the extra mile, it would be nice if the texture options in the shader variables under the "Color" section was replaced with a slider for saturation. Now that I think about it, that's a good suggestion for regular albedo textures, too... But I digress, here's a mockup of what I mean.
![vertex colors mockup](https://user-images.githubusercontent.com/10066958/127571740-0649b46b-339b-48f0-89d4-1244ecdc0ff4.png)

**What have you tried?**
I tried using the vertex color dev shader, but that only seems to be useful for models made with code, not for models imported in ModelDoc. I *could* go into something like Blender, UV map the model, and bake the colors to a texture, but that has the potential to be tedious if the model is complex.

**Additional context**
I feel like this could be especially useful for models imported from asset packs which only use vertex colors, since there aren't any tools to batch-convert models from using vertex colors to textures, and converting each model manually one-by-one would be very time-consuming.

**Comment by handsomematt** [comment]
Can just do a shader yourself for this thesedays
