### ISSUE TITLE
`EntityCreated` and `EntityRemoved`

### ISSUE THREAD

**Issue by Dragoteryx** [sboxgame/issues#542]
**What can't you do?**
I need to execute code when entities are created/removed, but there is no way to do that currently.

**How would you like it to work?**
Functions called on the Game instance when an entity is created or removed, with the entity passed as a parameter. 
```cs
public abstract void EntityCreated(Entity ent);
public abstract void EntityRemoved(Entity ent);
```

**What have you tried?**
I don't think there is a way to do this currently.

**Additional context**
`EntityCreated` would be S&box's version of [GM:OnEntityCreated](https://wiki.facepunch.com/gmod/GM:OnEntityCreated).

**Comment by thegrb93** [comment]
Related https://github.com/Facepunch/sbox-issues/issues/447
