### ISSUE TITLE
setang not functioning (again?)

### ISSUE THREAD

**Issue by zxz41** [sboxgame/issues#543]
During a S&box Livestream yesterday (31/07). We were trying to help someone set up a fixed perspective (since camera tool isn't available.) With setang and setpos.

However, the angles never updated, instead spewing some prediction error message. (Something about DevCam iirc)
`sv_cheats` were enabled.

setpos did function, but even with supposedly(?) now 6 arguments, it didn't set the angles.

From what I understand #224 was already fixed, but my guess is that https://github.com/Facepunch/sandbox/commit/1867ea9db947e0284697b54fb87db68b0d096d6d _might_ have broken it by making the camera predicted. (which could cause prediction to reset the angles to the predicted ones.)

The video of the stream isn't public, and I don't own a S&box key. So I can't check it out again.

Reproducing the issue should be fairly easy, just start a singleplayer session on any map in sandbox, Enable `sv_cheats` and try to use `setang 0 0 0`. The angles should remain the same (and possibly spew prediction errors.)

**Comment by robotboy655** [comment]
There's is currently no way to set the view angles of a player in the Sandbox gamemode due to the pawn system.

**Comment by robotboy655** [comment]
This is now fixed.
