### ISSUE TITLE
Material Editor: Add a way to use the RGB channels separately to reuse the same texture across multiple grayscale texture maps

### ISSUE THREAD

**Issue by Grodbert** [sboxgame/issues#554]
**What can't you do?**
Use RGB channels individually in the material editor to save space when using multiple grayscale textures.

**How would you like it to work?**
Here is a quick concept I made for it:
![image](https://user-images.githubusercontent.com/86626409/127782768-4902e6d2-e1ca-4409-b367-1a84a9a42321.png)
Essentially in the texture option you should be able to check a box and select which channel you'd like it to use, in this case I have a map that's yellow/orange, because I use green and red for roughness and metalness respectively, obviously the texture isn't real but if this were to be added, it would be easy to create these textures with photoshop or paint.net by simply overlaying them.

**What have you tried?**
Tried searching for it but it's not there

**Additional context**
Textures are the biggest file for a model, and with PBR you end up using a lot of them, if we can use RGB channels the size of textures needed can be essentially cut in half across all models that use this method, that would save countless of space.
As you can see from the screenshot I'm trying to remake snotfarm and since the snot will be all over the place, I want to optimize it as much as possible to lessen the impact on performance, not sure if this would help in that regard but it definitely will on space usage.

**Comment by wouterpleizier** [comment]
As far as I can tell, the material compiler already packs channels based on which shader and textures/parameters are used. Take a look at the Compiled Textures tab in the material editor:

![image](https://user-images.githubusercontent.com/8166218/127839978-12d0a281-1892-4a07-8626-7309b046abdc.png)

Here you can see that the second texture contains the normal map in its RG channels (the third normal map component is likely recalculated in the shader) and the roughness map in its B channel. Not sure why it's also showing an empty alpha channel, though. Might be a bug or something that's reserved for another purpose.

One could argue that in this example, the AO could be packed into the color texture's alpha channel instead, but that's not necessarily better. Different kinds of maps have different compression needs, and keeping them as separate textures can result in better performance, visuals and file size (the screenshot says the AO texture is 2.67 MB for some reason, but the actual file is only 179 KB).

**Comment by handsomematt** [comment]
Like the comment above says, this is done automatically on the compiled materials.
