### ISSUE TITLE
Hammer undo randomly stops working

### ISSUE THREAD

**Issue by MrBrax** [sboxgame/issues#556]
**Describe the bug**
After working a random amount of time, the undo function completely stops working. The option gets greyed out. Restarting hammer fixes it, but very annoying if you messed up something and you haven't saved in a minute.

**To Reproduce**
Currently unknown, maybe others who have gotten this can brainstorm. I can chip in that it might have to do with prefabs.

**Expected behavior**
For undo to work all the time.

**Comment by bakscratch** [comment]
How many times are you undo'ing? there is a limit on undo history which you can change in the settings.

<img width="601" alt="sbox_IQhpyMwb7v" src="https://user-images.githubusercontent.com/8184184/127787546-97e654a4-3a57-4894-8202-ba09be8787fd.png">

**Comment by MrBrax** [comment]
> 
> 
> How many times are you undo'ing? there is a limit on undo history which you can change in the settings.
> 
> <img alt="sbox_IQhpyMwb7v" width="601" src="https://user-images.githubusercontent.com/8184184/127787546-97e654a4-3a57-4894-8202-ba09be8787fd.png">

Unless that counts for the entirety of the session, i don't see how it could affect this. I can be working on something undoing and moving edges, then suddenly it just stops working.

**Comment by bakscratch** [comment]
I assume it looks something like this? this is after doing 100 undo.

<img width="319" alt="sbox_Ft1pQfRfOY" src="https://user-images.githubusercontent.com/8184184/127787663-9d276072-0426-4075-bfe4-7b07818756ef.png">

**Comment by MrBrax** [comment]
I haven't actually checked that panel when it happens, i'll try to remember when it does. But i'm not pressing undo a hundred times at once is what i'm saying.

**Comment by MrBrax** [comment]
Now it stopped working again, i was just moving some faces. It's stuck on "Undo: Clear Selection" and doesn't do anything.

![1628089177054](https://user-images.githubusercontent.com/1517911/128204499-3bf082a2-67b5-4bce-9007-01032428991d.png)

Clicking on the arrows or any of the entries do nothing.

**Comment by MrBrax** [comment]
![1628368497940](https://user-images.githubusercontent.com/1517911/128613239-942b2149-ddec-48e8-965d-e425496bd424.png)

stopped working again. seems that just closing the map and reopening it fixes it

**Comment by MrBrax** [comment]
Broke again. Of note is that the undo history doesn't get populated either. Here it's blank because i tried disabling and enabling the undo history.

https://user-images.githubusercontent.com/1517911/130367227-dac19518-669c-473e-a89e-50fa5b59aac2.mp4
