### ISSUE TITLE
Box shadow inconsistent when using corner radius

### ISSUE THREAD

**Issue by louiefox** [sboxgame/issues#557]
**Describe the bug**
box-shadow is odd when using corner-radius

**To Reproduce**

1. Use box-shadow
2. Use border-radius: 16px;
3. Shadow wont look the same on the corners

**Expected behavior**
The shadow should look the same all the way around the element

**Screenshots**
![image](https://user-images.githubusercontent.com/16431607/127788775-f4533982-5145-4985-977f-5b431722d497.png)
![image](https://user-images.githubusercontent.com/16431607/127788781-f0a01cca-2254-4de1-a400-f26272c3feb5.png)

**Comment by louiefox** [comment]
Code for the red test one
`.test1 {
	width: 200px;
	height: 200px;
	left: 50%;
	top: 50%;
	background-color: red;
	box-shadow: 0 0 10px black;
	border-radius: 16px;
}

.test2 {
	width: 100px;
	height: 100px;
	left: 50%;
	top: 50%;
	transform: translateX(-50%) translateY(-50%);
	background-color: grey;
	box-shadow: 0 0 10px blue;
	border-radius: 16px;
}`

**Comment by handsomematt** [comment]
I fixed this a while ago

![image](https://github.com/sboxgame/issues/assets/1388267/6e97bc79-8105-4829-a720-431aeaa3224a)
