### ISSUE TITLE
Animgraph StateMachines not properly synced until after 1-2 transitions.

### ISSUE THREAD

**Issue by Fortune117** [sboxgame/issues#565]
**Describe the bug**
Animgraph StateMachines do not properly sync animations until after 1-2 transitions. This is extremely noticeable on the NPCs I've been working on and is a bit of a chore to work around. It doesn't actually effect the server side bone coordinates of the NPC, as the ragdolls appear in the expected location if they're killed while bugging out like this.

**To Reproduce**

1. Spawn something animated with an animgraph that uses state machines.

**Expected behavior**
Animations should be synced without the need for prior state transitions.

**Screenshots**

**Additional context**
Rubat knows what this bug is and how to reproduce it (not to throw him under the bus )

**Comment by Fortune117** [comment]
Bump.

**Comment by lotuspar** [comment]
bump - we'd really like this for a game we're working on!

**Comment by chrisspieler** [comment]
https://github.com/sboxgame/issues/assets/8889285/4064efa9-fa28-40f0-ac06-a1473ea47f5e

Here's a recent example of what this looks like. When a player uses this chair entity, an animgraph parameter is set to true, prompting a state machine to transition to a state that uses the animation for pulling the seat down. On the very first use of this entity, said animation briefly flickers on screen, while on subsequent uses of the chair the animation smoothly plays as expected.

**Comment by yuberee** [comment]
We have another easy reproduction here:
https://github.com/Small-Fish-Dev/Sauna/blob/main/code/Entities/Hammer/Stove.cs
Walking inside of the Sauna you can interact with the stove to open the door, but it doesn't open first time even though the animparameter returns true.
The animgraph and code are as minimal as it gets.
We've also encountered the issue in other games being developed but less reliable to reproduce.

**Comment by dch-GH** [comment]
Encountered this issue with chests in my game. My setup is probably very similar to the Sauna stove example. Just a simple "open" parameter and an opening animation.

https://github.com/sboxgame/issues/assets/66768086/1daeab55-dc79-4374-9ffd-9c7634c764bf

**Comment by NotGaylien** [comment]
actually had i have gotten this a few times now you mention it.

We are getting it in sauna.

https://github.com/sboxgame/issues/assets/82092361/f925d7e9-7c37-4a33-8362-183b8a4619b3

and i also have had this when doing doors with custom animations.

https://github.com/sboxgame/issues/assets/82092361/7a261826-a484-4f8a-af4a-effaf94dc6ea


interesting info which might be useful.

Its playing the animation perfectly fine on the server, 
but doesn't on the client until after the duration of the 1st animation is complete, 
in which it decides to sync back up the next time you play an animation.
