### ISSUE TITLE
HTTP Request and Response Headers

### ISSUE THREAD

**Issue by Ryhon0** [sboxgame/issues#566]
**What can't you do?**
Set request headers and retrieve headers from HTTP responses.

**How would you like it to work?**
`Headers` property in the `Sandbox.Internal.Http` class and `GetAsync()` method, which returns a `HttpResponse`, which would have properties like `Headers`, `Content` and `StatusCode`. 

**What have you tried?**
Using the `Http` class

**Comment by Rohansi** [comment]
That whole `Http` class needs a revamp. I'll try and get this one done soon

**Comment by handsomematt** [comment]
This is all possible with the [new Http class](https://asset.party/api/Sandbox.Http)
