### ISSUE TITLE
Images do not update when overwritten

### ISSUE THREAD

**Issue by AdamSai** [sboxgame/issues#580]
**Describe the bug**
I am editing icons for my UI in an external image editor. When overwriting the old icons they game does not update the image that it uses. To see the changed image a full game restart is required, restarting the gamemode does not use the new image.

**To Reproduce**

1. Use an image for a UI background
2. Update the image in an external editor
3. Save the image and overwrite the old one
4. Nothing happens ingame

**Expected behavior**
Just as with other asset types a detection in file changes would be neat so we don't have to restart s&box to see image changes.

**Screenshots**
Original image:  
![image](https://user-images.githubusercontent.com/11211186/128165889-3ef9d340-e9b0-4c55-9842-9817cd4a78e9.png)
Overwrite the image with this:  
![image](https://user-images.githubusercontent.com/11211186/128165968-8f6348a2-faab-43f3-b1a4-54c5c5056975.png)  
Ingame image still looks like this, even after restarting the gamemode, also after exiting to menu and recreating the gamemode:  
![image](https://user-images.githubusercontent.com/11211186/128166037-90fb23e6-5334-4fcb-8576-4d57c7354ea2.png)
After a complete game restart:  
![image](https://user-images.githubusercontent.com/11211186/128166132-aa605286-82a8-4e9d-82b6-96594312e2e7.png)

**Comment by Ryhon0** [comment]
Do you have the dev tools open while you edit them?

**Comment by AdamSai** [comment]
I did not. I just tried with them open and it's the same result

**Comment by garrynewman** [comment]
Yeah this is a pain

**Comment by kebabulon** [comment]
Any updates on this issue?

**Comment by handsomematt** [comment]
This has been in for a long time, is it not working for you?
