### ISSUE TITLE
Server sends all files in addon folder to clients

### ISSUE THREAD

**Issue by Jake-Rich** [sboxgame/issues#59]
**What can't you do?**

Limit server from sending all files to the client with the `sharedassets` filter.

**How would you like it to work?**

Allow multiple filters to the `.addon` file either through a list field in the json or splitting up filters with `|` and keeping the single field. A whitelist / blacklist could help but might not be needed.

**What have you tried?**
Decompiling `BaseFileSystem` to see how the regex works.

**Additional context**
Even if its possible to use the existing filter via a giant regex it is probably better to add concrete formatting that is understandable.

**Comment by garrynewman** [comment]
Which files do you not want to send?

**Comment by Jake-Rich** [comment]
I don't want to send source textures for materials (jpg, png) but can't just filter `*.*_c` for compiled files due to needing some pngs for UI

**Comment by garrynewman** [comment]
Yeah it's a bit messy eh. I'll have a think. I don't want to use the .addon file any more than we are right now because I want to get rid of it.

**Comment by JustPlayerDE** [comment]
What is wrong with the .addon file tho, or do you just wanna have it more "plug and play" (in terms of addon creation) so we have less to care about in the future?

**Comment by Nebual** [comment]
While it seems some source files (eg. `.png`) are no longer being sent, there's still silly files being transferred like:
```
2021/06/27 12:03:34.487	FileSend	Sending 'nebtown/content/randomtext.txt' to MuffinTastic	
2021/06/27 12:04:17.283	FileSend	Sending 'content2/.git/objects/ec/f2e3d90d2e0f8e19520922f5ac0780ee778dc5' to MuffinTastic	
2021/06/27 12:06:23.464	FileSend	Sending 'nebtown/content/.git/objects/pack/pack-8c1e166609180a95b1a18ce5fb00900f52711758.pack' to MuffinTastic	
2021/06/27 12:06:23.836	FileSend	Sending 'nebtown/content/.git/refs/tags/1.0-beta' to MuffinTastic	
2021/06/27 12:06:23.836	FileSend	Sending 'nebtown/content/.git/objects/pack/pack-8c1e166609180a95b1a18ce5fb00900f52711758.idx' to MuffinTastic	
```
Globally blocking `.git/`, and generally adding some sort of addon-defined block/allow list (list of globs to block?), seems ideal

**Comment by birdbrainswagtrain** [comment]
I'd also like some more control over what files get sent.

**Comment by MrBrax** [comment]
Game still seems to be sending vmap/los/obj/mtl/png whatever, pretty much anything that's in the folder. Pretty bad for secrets leaking?

**Comment by JustPlayerDE** [comment]
Just dont put any secrets in your code for now until there is a way to limit sent files

**Comment by MrBrax** [comment]
> 
> 
> Just dont put any secrets in your code for now until there is a way to limit sent files

i mean a vmap file is bad enough already to be distributed i think

**Comment by birdbrainswagtrain** [comment]
FYI It already excludes a ton of different source file types. I'm pretty sure you can prefix a a top-level directory with a dot `.` to disable sending everything in that directory. It would still be nice to specify a list of filters.

**Comment by KeithAlt** [comment]
> Which files do you not want to send?

I want to send the client files they need and nothing more.
I should not need to send the client code that otherwise can be run on the server-side exclusively. I hope I'm mistaken in my assertion, but this sounds like a devastating security concern especially with database reliant systems.

Please correct me if I'm wrong, I would really like to be 👍

**Comment by birdbrainswagtrain** [comment]
I decided to document the default behavior. https://wiki.facepunch.com/sbox/DefaultSharedAssetFilter

**Comment by MrBrax** [comment]
Creating a local dedicated server with a local gamemode and connecting to it seems to send all the files in my gamemode (2000 files), the client doesn't even receive them (FileRecv isn't null!) and it takes multiple seconds per file, making joining impossible.
