### ISSUE TITLE
point_worldtext breaks when changing video mode

### ISSUE THREAD

**Issue by SharpMars** [sboxgame/issues#593]
**Describe the bug**

When changing video mode in Settings when loaded in map all point_worldtext break.

**To Reproduce**

1. Open map including point_worldtext
2. Go into S&box's video settings
3. Change video mode

**Screenshots**
Before changing video mode:
![image](https://user-images.githubusercontent.com/70289680/128338505-221fd31c-4a17-4208-9434-3194b827b6cd.png)
After changing video mode:
![image](https://user-images.githubusercontent.com/70289680/128338351-845fe952-36bd-4b69-95eb-1d76bdcdc52e.png)

**Additional context**
Bug was tested on map called mobenix which heavily uses point_worldtext.
Gamemode used to test bug: Sandbox
Font used in point_worldtext: Arial Black
My OS: Windows 10 (21H1)
CPU: Intel Core i5-4210U
GPU: AMD Radeon HD 8500M

**Comment by samzanemesis** [comment]
Might be a better idea to just reimplement this with worldpanels for both flexibility and code clarity, I don't like the underlying code on point_worldtext
