### ISSUE TITLE
"Alpha" option when selecting a mesh does not work

### ISSUE THREAD

**Issue by conneath** [sboxgame/issues#611]
**Describe the bug**
you can change it, and it'll appear correctly in hammer but ingame it doesn't work

**To Reproduce**
1. change a mesh's alpha to 0 in hammer and see it become invisible in the hammer view
2. compile the map 
3. see that the mesh is still visible

**Expected behavior**
mesh should have become invisible ingame

**Comment by conneath** [comment]
does this mean the alpha option will be removed?

**Comment by robotboy655** [comment]
For as long as it doesn't work - yes, I think it's a good idea to avoid confusion. Not closing this as we might look into this later.
