### ISSUE TITLE
Add text-overflow as a supported scss property

### ISSUE THREAD

**Issue by AdamSai** [sboxgame/issues#615]
**What can't you do?**
Use the text-overflow scss property to style overflowing text.  

**How would you like it to work?**
At least support for ellipsis would be nice. Firefox also supports the options for custom strings instead of the ellipsis.
https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

**What have you tried?**
Adding the property in SCSS, and got that it was an unknown property
**Additional context**

**Comment by notmatical** [comment]
bump, needing this

**Comment by Weldify** [comment]
Bump!

**Comment by cr4yz** [comment]
This is done, please let me know if you there are any problems with it.
