### ISSUE TITLE
Need OnColor hook

### ISSUE THREAD

**Issue by Wgis** [sboxgame/issues#627]
Need hook when color changed, oldcolor and newcolor

**Comment by garrynewman** [comment]
Why?

**Comment by Wgis** [comment]
Same as OnUse, for doing things.
For example, player change main entity color, and we can change color for parented entitys. If you know other way, i listen.

**Comment by garrynewman** [comment]
How does the player change the main entity color?

**Comment by Wgis** [comment]
Base sandbox tool

**Comment by thegrb93** [comment]
Maybe that could be generalized to something like EntityPropertyChanged

**Comment by Wgis** [comment]
Maybe maybe

**Comment by Wgis** [comment]
Maybe maybe
