### ISSUE TITLE
Asset tags for addons

### ISSUE THREAD

**Issue by AWildErin** [sboxgame/issues#641]
**What can't you do?**
Assign tags to an asset (at least to my knowledge)

**How would you like it to work?**
Source 2 ships with an `asset_tags.txt` in the core folder. My proposal would be to allow addons to define their own asset tags file with the same format and allow us to assign them to our assets. These tags would appear within the tags menu on the asset browser.

I feel individuals and teams alike could benefit from this as people with a bunch of assets can now tag their assets for specific purposes, or in the case of the default tags, define assets as incomplete/completed.

I'm not sure how tagging is done in the engine, and unfortunately, I can't comment on that much. But this feature would be extremely useful for creating things.

Tags follow this format in `asset_tags.txt`
```
id = "otherproject"
name = "From Other Project"
desc = "This asset was copied from another project"
color = [ 15, 150, 240 ]
icon = "tools:images/common/otherproject_asset.png"
```
I'm not sure if the `tool:` path carries onto addons or if that's just within core, HL:A has their own tools folder in hlvr and core so it might? But it'd be nice to be able to define images for these.

Another note would be that defining it all manually like that isn't the most user-friendly approach but I can't think of any other method.

**What have you tried?**
Nothing

**Comment by robotboy655** [comment]
This was added, right click on any asset and use the Tags menu.
