### ISSUE TITLE
Add Sound.Play()

### ISSUE THREAD

**Issue by Fronkln** [sboxgame/issues#645]
**What can't you do?**
The Sound object has a method for stopping it, but no method for Play() exists, blocking me from playing sounds on demand.

**How would you like it to work?**
Sound.Play() plays the sound like how AudioSource.Play() from Unity does.

**What have you tried?**
I thought that maybe i could implement my own extension method to play Sound directly.
So for clues i decided to view the game's code with a decompiler. (no malicious intent)

I have noticed that **both Entity.PlaySound(soundName) and Sound.Stop() calls functions from a internal class called GameSoundManager.**

So i thought, "Oh well, i have used Reflection before, i could invoke the method."

And i write this extension  method for playing the sound manually with Reflection, except SBox is not really happy with me using Reflection and tells me it's not allowed.

As a result, i am stuck, unable to write a custom Sound.Play() method because the SBox API doesn't have it and prevents me from accessing the internal function with Reflection.

**Comment by Willco2** [comment]
`Sound.FromWorld(...)` or `Sound.FromEntity(...)` or `Sound.FromScreen(...)` are static methods that serve this purpose.

**Comment by Fronkln** [comment]
> `Sound.FromWorld(...)` or `Sound.FromEntity(...)` or `Sound.FromScreen(...)` are static methods that serve this purpose.

While those methods do play the Sounds, they create a new object and return it to do this. What i was hoping for was to create the sound objects at the spawn method, then control their playback directly from the object itself, while this is partially possible with `Sound.Stop()`, it's not possible to ever play the sound again.

**Comment by JetBoom** [comment]
Sound.FadeIn, Sound.FadeOut will both be useful too.

**Comment by GamerXCZ** [comment]
> Sound.FadeIn, Sound.FadeOut will both be useful too.

Yes, but FP rather making on absolutely useless thing like stream integration instead on full completion of sound events and commissioning model anim events and o lot more...
