### ISSUE TITLE
Files download extremely slow from the server

### ISSUE THREAD

**Issue by Jake-Rich** [sboxgame/issues#65]
**To Reproduce**

1. Join a local server
2. Wait for big files to download really slow.

**Expected behavior**

Files download fast expecially when the server is on the same machine.

**Additional context**

Think the limit is in `Sandbox.FileSend.Tick` where it is only sending 8KB chunks every Tick() but not sure why that limit is there.

**Comment by FlorianLeChat** [comment]
Unless there have been significant changes since the weekend, this issue is still present.
