### ISSUE TITLE
Wrap/expand console exception messages 

### ISSUE THREAD

**Issue by nykez** [sboxgame/issues#679]
**What can't you do?**
View full console errors, exceptions, stack traces... etc

**How would you like it to work?**
Wrap the console exceptions instead of the text running off screen or make the exceptions/stack traces expandable. 

**What have you tried?**

**Additional context**

**Comment by randomperson189** [comment]
Yes we really need this. Plz read this Facepunch devs

**Comment by AMastryukov** [comment]
I would suggest to at least add a way to copy the messages to clipboard by clicking them.
