### ISSUE TITLE
Right Alt + V pastes on some systems

### ISSUE THREAD

**Issue by bela333** [sboxgame/issues#680]
**Describe the bug**
On a Hungarian layout keyboard, hitting Alt Gr (Right Alt) + V in chat pastes the contents of the clipboard.

**To Reproduce**

1. Set keyboard layout to Hungarian
2. Put some text on your clipboard
3. Open chat in S&box
4. Hit Right Alt + V
5. An at sign (@) and the contents of the clipboard appear in the chat box

**Expected behavior**
Only the at sign (@) appears in the chat box.

**Additional context**

With certain keyboard layouts, such as the Hungarian one, the right alt button is called Alt Gr and is used to write a variety of characters. On the Hungarian keyboard Alt Gr + V produces the at (@) sign. I believe in some cases holding down this Alt Gr button is interpreted as Ctrl+Alt, thus Alt Gr+V is Ctrl+Alt+V, which could be the reason for this occurance.

**Comment by xezno** [comment]
Should be fixed in next build
