### ISSUE TITLE
SCSS `box-shadow` ignores background transparency

### ISSUE THREAD

**Issue by Adesii** [sboxgame/issues#696]
**Describe the bug**

`box-shadow` ignores the transparency of elements instead coloring the background the same color as the shadow.

**To Reproduce**

have a transparent panel and add box-shadow to it.

I made a minimal gamemode to showcase this issue.
[panel-boxshadow.zip](https://github.com/Facepunch/sbox-issues/files/6989396/panel-boxshadow.zip)

Here is a video showcasing the issue:

https://user-images.githubusercontent.com/37816311/129503132-078684fa-90e5-45c1-9fb6-5a47ea895e7a.mp4

**Expected behavior**
i would expect it to work the same as in normal css where it keeps the background transparent and instead just makes a border around the div/panel.
like in this example:

https://user-images.githubusercontent.com/37816311/129503238-3fdf0ef3-49be-4b59-9989-43a15780c688.mp4

Codepen of the HTML version: https://codepen.io/Adesii/pen/JjNVeyY

**Additional context**

This would be useful for more organic borders around panels that add a glow effect to a selection or such.
instead of just a simple border

Here is how i currently handle the border around a selection:

![image](https://user-images.githubusercontent.com/37816311/129503669-54134c17-c198-421f-976c-ce597e5d7ef1.png)

Here is how i wanted it to look but the box shadow doesn't allow for this (This isn't in sbox and is just a concept art. from our artist):

![image](https://user-images.githubusercontent.com/37816311/129503478-0fdb0a21-52b6-4001-beb0-75a1dd3b7ee0.png)

**Comment by handsomematt** [comment]
thanks for the issue, this should behave properly now

before
![image](https://user-images.githubusercontent.com/1388267/211210873-efbdaba6-263f-4472-9922-d95e675afd98.png)

after
![image](https://user-images.githubusercontent.com/1388267/211210877-9e2dde06-5b53-4d97-bb22-d412ef5696fd.png)
