### ISSUE TITLE
Render.CopyGBuffer(GBufferType type) method

### ISSUE THREAD

**Issue by ogniK5377** [sboxgame/issues#698]
**What can't you do?**
There is no trivial way to currently fetch any GBuffers in s&box. Having the ability to create and copy them within a shader allows for higher quality post-processing effects & more precision with certain operations without having to rely on a depth buffer and an approximation. An example of a few GBuffers are as follows:
- `GBufferAlbedo`
- `GBufferDepth`
- `GBufferNormal`
- `GBufferPosition`
- `GBufferNormalSpecExp`
etc

**How would you like it to work?**
Similar to how `Render.CopyFrameBuffer();` works where it passes a texture to an attribute in the shader, a method should exist which does the same thing and passes itself to the respective attribute, eg
`Render.CopyGBuffer(GBufferType.Normal); // Renders a GBuffer and copies it into "GBufferNormal"`

As the renderer is a forward renderer these buffers typically aren't generated but should be able to get generated from the C# side for usage when needed.

**What have you tried?**
Currently, the only workaround is to fetch the current scene depth and approximate asmall subset of the GBuffers. This can be done specifically for the normal & position GBuffer however it leads to inaccurate results as the player moves and looks around

**Additional context**
Normal GBuffer approximation based on depth buffer
![image](https://user-images.githubusercontent.com/25727384/129571263-f0d79d33-3bb6-410a-8ef5-259c2727acdf.png)

**Comment by samzanemesis** [comment]
We use forward shading in our current pipeline so there's no gbuffer, those references you're seeing are likely from Dota's rendering pipeline

You might be able to generate a gbuffer from the mat_fullbright visualizations and then rendering the scene again with them enabled to texture

**Comment by samzanemesis** [comment]
The best way to generate these easily might be to generate a gbuffer from the mat_fullbright visualizations and then rendering the scene again with them enabled to texture
