### ISSUE TITLE
Lagspike from friend list

### ISSUE THREAD

**Issue by Dimentio** [sboxgame/issues#703]
**Describe the bug**
If you have a huge friend list the game will lag spike every 2-3 seconds from going through your friend list.

**To Reproduce**
Have a lot of friends. I have 1996 Friends but I'd guess 1000 should do it.

**Expected behavior**
I'd expect to not lag spike.

**Temporary workaround**
You can go offline on steam to avoid this issue.

**Screenshots**
https://user-images.githubusercontent.com/3157366/129628488-46849293-08ec-4a7f-aff6-f57265096d88.mp4

**Additional context**
I have a pretty good computer so I'd think it might be even easier to diagnose on a average computer.

**Comment by DevulTj** [comment]
shouldn't be the case for a good while now
