### ISSUE TITLE
Bloom and missing textures on s&box settings change

### ISSUE THREAD

**Issue by TitusStudiosMediaGroup** [sboxgame/issues#731]
**Describe the bug**
When you change your game settings (eg, global volume), a bloom effect is applyed to the map (tested on Construct, and custom map), and (only tested on Construct) some textures such as the signage turns into missing textures.

This is persistent till you close and reopen the game.

**In console:**
```
Error: View "Player 0", layer "Ambient Occlusion Proxies": 
	Error allocating render target binding! Different render target dimensions/MSAA assigned from the depth target!
	Main: 1920x1080, Depth: 1920x1080
CRenderContextDx11_SoftwareCommandLists:: Cannot resolve from a non-MSAA buffer to an MSAA buffer!
```

**To Reproduce**

1. Load into Construct
2. Open settings menu
3. Change volume to any other value and click Apply Changes

**Screenshots**

![https://i.imgur.com/zX2vdka.png](https://i.imgur.com/zX2vdka.png)
![https://i.imgur.com/Neh3xhb.png](https://i.imgur.com/Neh3xhb.png)
![https://i.imgur.com/1DXSpkV.png](https://i.imgur.com/1DXSpkV.png)
![https://i.imgur.com/ozxN6ZB.png](https://i.imgur.com/ozxN6ZB.png)

**Comment by SharpMars** [comment]
Missing texture where text was is because point_worldtext breaks. I've already made issue about it here if you want to check it out: #593

**Comment by TitusStudiosMediaGroup** [comment]
Interesting, I wonder whats causing the weird blooming, it was really bad on Construct but its now far less noticeable
