### ISSUE TITLE
Ability to Read TrackedObject Device ID

### ISSUE THREAD

**Issue by gvarados1** [sboxgame/issues#796]
**What can't you do?**
We should be able to get the Device ID of the individual tracked objects. They get shuffled around the Input.VR.TrackedObjects[] array when SteamVR restarts. (It's probably not called Device ID, that's just what I called it)
![image](https://user-images.githubusercontent.com/39461072/130903546-742c77dc-0879-4c3e-b389-778129b8d421.png)

**How would you like it to work?**
Probably something similar to Input.VR.TrackedObjects[].GetID()
Maybe we could be able to access the TrackedObject by it's ID too.

This way we'll be able to save our device configurations. Currently, every time I restart SteamVR I have to spend 5 minutes figuring out which physical tracker is linked to which TrackedObject index.

**Comment by gvarados1** [comment]
still waiting on this one

**Comment by ShadowBrian** [comment]
You don't need the ID you need the tracker role system @gvarados1 
Basically it's a list of roles you can assign to trackers that goes all along the body, feet, knees, hip, chest, elbow, hands etc.

**Comment by handsomematt** [comment]
Roles sounds good. I think they are all accessible through IVRInput::GetInputSourceHandle using paths like `/user/hand/left`, `/user/foot/left`, `/user/hand/chest`. And then I'll see if I can get them working in a non dopey way for our API.

**Comment by gvarados1** [comment]
I thought tracker roles were outdated and a lot of users don't even have them setup

**Comment by xezno** [comment]
I can't see how it would be useful for a developer to have access to a device ID here, but I can see the value in having access to the assigned roles, I'll take a look at this

**Comment by xezno** [comment]
You can access tracked device roles now (`TrackedObject.Role`), these reflect the role you set up in SteamVR (left wrist, waist, chest, etc.)
Eventually when the scene system becomes more mature this will get rolled in to the VR tracked object component, so you'll just be able to select "tracker" and then the role you want - hopefully this covers your use case.
