### ISSUE TITLE
OnPhysicsCollision is not called at the exact moment of the collision.

### ISSUE THREAD

**Issue by sas41** [sboxgame/issues#857]
**OnPhysicsCollision does not run at the moment of impact, thus, returns incorrect collision positions.**

**To Reproduce**

1. Create a physics object with a ``OnPhysicsCollision`` override.
2. Make the method mark the point of impact.
3. Launch the object at a static surface.
4. Observe the difference.

**Expected behavior**
Returns the exact point in space where the two objects collided.

**Screenshots**
![image](https://user-images.githubusercontent.com/2854477/132042683-b6edf9ed-599b-4e0e-bb5b-65f322116976.png)

In the screenshot, RED, GREEN and BLUE are used to visualize the PreCollision velocity, collision surface normal and PostCollision velocity, respectively.

The MAGENTA sphere spawns with it's outer edge touching the point of impact, meaning that it should not be visible at all against a large, flat surface such as a wall.

**Additional context**

Code used to test:
```cs
protected override void OnPhysicsCollision(CollisionEventData eventData)
{
	base.OnPhysicsCollision(eventData);	
	if ( IsServer )
	{
		float time = 10f;
		float size = 20f;
		Vector3 position = eventData.Pos;
		DebugOverlay.Sphere(position + eventData.Normal * size, size, Color.Magenta, true, time);
		DebugOverlay.Line(position, eventData.Pos - eventData.PreVelocity.Normal * size, Color.Red, time, true);
		DebugOverlay.Line(position, eventData.Pos - eventData.Normal * size, Color.Green, time, true);
		DebugOverlay.Line(position, eventData.Pos + eventData.PostVelocity.Normal * size, Color.Blue, time, true);

	}
}
```

- Using ``this.Position`` instead of ``eventData.Pos`` is still inacurate.
- The issue persists across different velocities and for any value of ``Sandbox.Global.PhysicsSubSteps``.
- Higher velocities produce higher inaccuracies.
- With the details mentioned above, I suspect that the function calls seems to come one server tick / physics update after the collision has happened, since the position of the collision usually is off towards where the object would bounce.

**Comment by handsomematt** [comment]
I think I fixed this a while back whilst refactoring how physics collisions are called.
