### ISSUE TITLE
WorldPanel entity for Hammer

### ISSUE THREAD

**Issue by walllable** [sboxgame/issues#890]
**What can't you do?**
At the moment, WorldPanels can only be created (and set basic properties such as its location, rotation, width/height, etc) through code. I feel like being able to place WorldPanels down in Hammer and define those basic properties in it would be beneficial for quick prototyping, or mappers who want to be able to more easily specify where they want WorldPanels, and how they want them to look.

**How would you like it to work?**
Ideally you'd be able to place an entity down in Hammer (let's say it's called `ent_worldpanel`) and its origin is at the center of the WorldPanel that would be created in-game. With this, the mapper would be able to...
* Define its X/Y/Z transform coordinates
* Define its rotation, or if it should follow the player's view
* Width/height in hammer units 
* Scale/"resolution" of the content that's being shown (Maybe? I dunno if that's configured in the WorldPanel itself, or if that's just set through scss)
* Point to which html and/or scss file they want the WorldPanel to display

Ideally there could also be a basic editor, similar to the one that `point_worldtext` has, to allow quick creation of a sign or to create quick placeholder text that would be changed later. It would be nice if this supported basic HTML formatting via tags (bold, italics, underline, strikethrough, text alignment, etc,) setting the font, and text coloring. I figure if they want to do more complex things like changing the position of text or add buttons or things like that, they can point to an html/scss file.

**Comment by handsomematt** [comment]
Seems like something that should be a cloud entity
