### ISSUE TITLE
Graphical bugs when instantiating an Entity-derived class in the Client.Pawn's constructor. 

### ISSUE THREAD

**Issue by kai13xd** [sboxgame/issues#935]
**Describe the bug**
Graphical bugs seem to appear when trying to initialize an `Entity`-derived object in the `Client.Pawn` 's constructor or by member initialization during `Sandbox.Game.ClientJoined` . Various ugly stuff like invisible models, black textures, z-fighting, as well as the water gets funky. Weirdly enough the graphical bugs were sometimes inconsistent and didn't always appear upon first load.

Depending on how the `Entity` is initialized, an exception can be thrown that reads: 
> Tried to create Sandbox.ICamera from stored class Sandbox.WalkController named WalkController.

Might explain why the graphics are getting funky. idk

Due to this being a somewhat silent failure that confused me and took up a bit of my time, I thought it'd probably be worth addressing.

**To Reproduce**
After finally pinpointing the code that was going apeshit I put the offending code into a repo. Just shove this into sbox and contemplate it for as much as it worth.
https://github.com/kai13xd/PawnCtorBugs

**Expected behavior**
I can instantiate Pawn-related Entity objects via it's ctor without the game turning emo on me, it throws an exception, or even better yet a compile-time assertion.

**Screenshots**

The bug are out.
![20210917051838_1](https://user-images.githubusercontent.com/7115703/133790971-08786a01-cd1b-467f-8e1d-c6f0096bdeb7.jpg)

**Comment by Spiralexe** [comment]
Not having same visual issues but having client view model turns invisible if doing this, no errors in console
