### ISSUE TITLE
Allow gamemodes to decode and play h264/av1/vp9 videos

### ISSUE THREAD

**Issue by walllable** [sboxgame/issues#993]
**What can't you do?**
At the moment, we can't stream video or audio from sources like youtube, soundcloud, bandcamp, or from direct links to audio files. This could be useful for a variety of things, for example a cinema gamemode, or a jukebox where people can queue up music to play in a map or something.

**How would you like it to work?**
Instead of doing this via a web browser like GMod's Cinema gamemode, I think it'd be best to do this via [`youtube-dl`](https://github.com/ytdl-org/youtube-dl) instead. VRChat has this implemented, and I think it's a much nicer way of doing it than through a browser.
Something VRChat also does is render the video to a texture/material, instead of just restricting it to a plane. I really like this because it allows you to upload a UV mapped video that you can put onto a similarly UV mapped model (could come in handy for 360-degree videos as well) and would love for this to be possible in s&box as well. Maybe by having a material that just has a video player shader that youtube-dl outputs to?

**Additional context**
`youtube-dl` doesn't just support youtube, it supports other sources as well, such as the aforementioned sources at the beginning, vimeo, twitch, and a lot more. A full list can be seen [here.](https://ytdl-org.github.io/youtube-dl/supportedsites.html)

**Comment by garrynewman** [comment]
I can see the benefits of this. My main worry is about the sustainability of it. 

What I mean by that is, if we're showing the website then we're playing by YouTube's rules. That's what it's there for, they can show ads, everything is as it normally is.

If we're downloading then aren't we sidestepping that and just eating their bandwidth. Isn't it inevitable that they're going to shut this method down, and then we're going to have to change it at some point in the future?

**Comment by aylaylay** [comment]
Surely this can just be a library that someone makes, I think someone already has. Would feel wrong to include it in the API

**Comment by handsomematt** [comment]
Expose some ways to decode popular video codecs like h264 / av1 and let addons use whatever source they want without you having to worry about supporting it.

There was also a feature request at some point to allow video playing from local webm sources for things like tutorial videos in games, a more generic API would allow this too.

**Comment by m0uka** [comment]
Including youtube-dl would still be completely useless for playing videos. You need to decode the videos, which youtube-dl doesn't do. Your backend should probably handle downloading and serving the videos.  

We need a proper way to decode and play videos like matt suggested - currently my s&box Cinema gamemode uses MJPEG (streamed JPEG frames from a backend) for playing videos.  
That's a terrible way of doing it - but currently the only way.

**Comment by walllable** [comment]
> Your backend should probably handle downloading and serving the videos.

By that do you mean having a server set up just to download from whatever service and then send the videos to the client? That sounds a bit inefficient to me. I figure not everyone who wants to play via youtube or twitch or something like that would want to pay for a server just to do that.

**Comment by m0uka** [comment]
It might be inconvenient, but it will probably be the easiest way.  

You could also implement your own video downloader in C#. It's not going to be easy, but it should be possible.
Youtube-dl can break whenever YouTube changes something. I don't think Facepunch will be happy updating the binaries everytime one of the video services changes something - not to mention that youtube-dl is a gray area in legal terms.

**Comment by walllable** [comment]
As long as it's possible for someone to implement their own downloader (or player I suppose, in livestreaming websites' case) then I don't see much of a problem with that. YouTube's a big enough thing that I figure someone will make something like that eventually.
I'll go ahead and rename the issue to better fit what we want here.
